# Site settings
title: Thrill
email: thrill@panthema.net
description: > # this means to ignore newlines until "baseurl:"
  Thrill is a C++ framework for distributed Big Data computations on a cluster.
  It is currently in development and aims to be more versatile and performant
  than Java-based alternatives.
baseurl: ""
url: "http://thrill.github.io"
github_username: thrill

# Build settings

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
markdown: kramdown
highlighter: pygments
