Thrill: StackArena< Size > Class Template Reference
StackArena< Size > Class Template Reference
Detailed Description
template<size_t Size>
class tlx::StackArena< Size >
Storage area allocated on the stack and usable by a StackAllocator.
Definition at line 32 of file stack_allocator.hpp.
#include <stack_allocator.hpp>
Classes
union AlignmentHelper
union to enforce alignment of buffer area
Public Member Functions
StackArena () noexcept
default constructor: free pointer at the beginning.
StackArena (const StackArena &)=delete
~StackArena ()
destructor clears ptr_ for debugging.
char * allocate (size_t n)
void deallocate (char *p, size_t n) noexcept
StackArena & operator= (const StackArena &)=delete
void reset () noexcept
reset memory area
size_t used () const noexcept
return number of bytes used in StackArena
Static Public Member Functions
static constexpr size_t size () noexcept
size of memory area
Private Member Functions
bool pointer_in_buffer (char *p) noexcept
debug method to check whether ptr_ is still in buf_.
Private Attributes
union {
char buf_ [Size]
stack memory area used for allocations.
AlignmentHelper dummy_for_alignment_
enforce alignment
};
char * ptr_
pointer into free bytes in buf_
Static Private Attributes
static constexpr size_t alignment = 16
Constructor & Destructor Documentation
StackArena () inline noexcept
default constructor: free pointer at the beginning.
Definition at line 64 of file stack_allocator.hpp.
~StackArena () inline
destructor clears ptr_ for debugging.
Definition at line 67 of file stack_allocator.hpp.
References StackArena< Size >::ptr_.
StackArena (const StackArena< Size > &) delete
Member Function Documentation
char* allocate (size_t n) inline
Definition at line 72 of file stack_allocator.hpp.
References StackArena< Size >::alignment, StackArena< Size >::buf_, malloc(), StackArena< Size >::pointer_in_buffer(), and StackArena< Size >::ptr_.
void deallocate (char * p, size_t n) inline noexcept
Definition at line 88 of file stack_allocator.hpp.
References free(), StackArena< Size >::pointer_in_buffer(), and StackArena< Size >::ptr_.
StackArena& operator= (const StackArena< Size > &) delete
bool pointer_in_buffer (char * p) inline private noexcept
debug method to check whether ptr_ is still in buf_.
Definition at line 59 of file stack_allocator.hpp.
References StackArena< Size >::buf_.
Referenced by StackArena< Size >::allocate(), and StackArena< Size >::deallocate().
void reset () inline noexcept
reset memory area
Definition at line 110 of file stack_allocator.hpp.
References StackArena< Size >::buf_, and StackArena< Size >::ptr_.
static constexpr size_t size () inline static noexcept
size of memory area
Definition at line 104 of file stack_allocator.hpp.
size_t used () const inline noexcept
return number of bytes used in StackArena
Definition at line 107 of file stack_allocator.hpp.
References StackArena< Size >::buf_, and StackArena< Size >::ptr_.
Member Data Documentation
union { ... }
constexpr size_t alignment = 16 static private
Definition at line 34 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate().
char buf_[Size]
stack memory area used for allocations.
Definition at line 50 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate(), StackArena< Size >::pointer_in_buffer(), StackArena< Size >::reset(), and StackArena< Size >::used().
AlignmentHelper dummy_for_alignment_
enforce alignment
Definition at line 52 of file stack_allocator.hpp.
char* ptr_ private
pointer into free bytes in buf_
Definition at line 56 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate(), StackArena< Size >::deallocate(), StackArena< Size >::reset(), StackArena< Size >::used(), and StackArena< Size >::~StackArena().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/stack_allocator.hpp