Thrill: UPtrStdStringSet Class Reference
UPtrStdStringSet Class Reference
Detailed Description
Class implementing StringSet concept for a std::vector containing std::string objects.
Definition at line 371 of file string_set.hpp.
#include <string_set.hpp>
Public Member Functions
UPtrStdStringSet (const Iterator &begin, const Iterator &end)
Construct from begin and end string pointers.
UPtrStdStringSet (Container &c)
Construct from a string container.
Iterator begin () const
Iterator representing first String position.
Iterator end () const
Iterator representing beyond last String position.
CharIterator get_chars (const String &s, size_t depth) const
Return CharIterator for referenced string, which belongs to this set.
std::string get_string (const String &s, size_t depth=0) const
Return complete string (for debugging purposes)
bool is_end (const String &s, const CharIterator &i) const
Returns true if CharIterator is at end of the given String.
String & operator[] (const Iterator &i) const
Array access (readable and writable) to String objects.
void print () const
size_t size () const
Return size of string array.
UPtrStdStringSet sub (Iterator begin, Iterator end) const
Subset this string set using iterator range.
Public Member Functions inherited from StringSetBase< UPtrStdStringSet, UPtrStdStringSetTraits >
bool check_order (const typename UPtrStdStringSetTraits::String &s1, const typename UPtrStdStringSetTraits::String &s2) const
bool check_order () const
void print () const
UPtrStdStringSet subi (size_t begin, size_t end) const
Subset this string set using index range.
bool is_equal (const typename UPtrStdStringSetTraits::String &a, const typename UPtrStdStringSetTraits::CharIterator &ai, const typename UPtrStdStringSetTraits::String &b, const typename UPtrStdStringSetTraits::CharIterator &bi) const
check equality of two strings a and b at char iterators ai and bi.
bool is_leq (const typename UPtrStdStringSetTraits::String &a, const typename UPtrStdStringSetTraits::CharIterator &ai, const typename UPtrStdStringSetTraits::String &b, const typename UPtrStdStringSetTraits::CharIterator &bi) const
check if string a is less or equal to string b at iterators ai and bi.
UPtrStdStringSetTraits::Char get_char (const typename UPtrStdStringSetTraits::String &s, size_t depth) const
uint8_t get_uint8 (const typename UPtrStdStringSetTraits::String &s, typename UPtrStdStringSetTraits::CharIterator i) const
uint8_t get_uint8 (const typename UPtrStdStringSetTraits::String &s, size_t depth) const
uint16_t get_uint16 (const typename UPtrStdStringSetTraits::String &s, typename UPtrStdStringSetTraits::CharIterator i) const
uint16_t get_uint16 (const typename UPtrStdStringSetTraits::String &s, size_t depth) const
Static Public Member Functions
static Container allocate (size_t n)
Allocate a new temporary string container with n empty Strings.
static void deallocate (Container &c)
Deallocate a temporary string container.
Protected Attributes
Iterator begin_
vector of std::string objects
Iterator end_
Additional Inherited Members
Public Types inherited from UPtrStdStringSetTraits
typedef uint8_t Char
exported alias for character type
typedef const Char * CharIterator
iterator of characters in a string
typedef std::pair< Iterator,
size_t > Container
exported alias for assumed string container
typedef String * Iterator
Iterator over string references: using std::vector's iterator.
typedef std::unique_ptr
< std::string > String
String reference: std::string, which should be reference counted.
Constructor & Destructor Documentation
UPtrStdStringSet (const Iterator & begin, const Iterator & end) inline
Construct from begin and end string pointers.
Definition at line 377 of file string_set.hpp.
Referenced by UPtrStdStringSet::sub().
UPtrStdStringSet (Container & c) inline explicit
Construct from a string container.
Definition at line 382 of file string_set.hpp.
Member Function Documentation
static Container allocate (size_t n) inline static
Allocate a new temporary string container with n empty Strings.
Definition at line 414 of file string_set.hpp.
Iterator begin () const inline
Iterator representing first String position.
Definition at line 389 of file string_set.hpp.
References UPtrStdStringSet::begin_.
Referenced by UPtrStdStringSet::print().
static void deallocate (Container & c) inline static
Deallocate a temporary string container.
Definition at line 418 of file string_set.hpp.
Iterator end () const inline
Iterator representing beyond last String position.
Definition at line 391 of file string_set.hpp.
References UPtrStdStringSet::end_.
Referenced by UPtrStdStringSet::print().
CharIterator get_chars (const String & s, size_t depth) const inline
Return CharIterator for referenced string, which belongs to this set.
Definition at line 398 of file string_set.hpp.
std::string get_string (const String & s, size_t depth = 0) const inline
Return complete string (for debugging purposes)
Definition at line 406 of file string_set.hpp.
Referenced by UPtrStdStringSet::print().
bool is_end (const String & s, const CharIterator & i) const inline
Returns true if CharIterator is at end of the given String.
Definition at line 402 of file string_set.hpp.
String& operator[] (const Iterator & i) const inline
Array access (readable and writable) to String objects.
Definition at line 394 of file string_set.hpp.
void print () const inline
Definition at line 421 of file string_set.hpp.
References UPtrStdStringSet::begin(), UPtrStdStringSet::end(), UPtrStdStringSet::get_string(), and TLX_LOG1.
size_t size () const inline
Return size of string array.
Definition at line 387 of file string_set.hpp.
References UPtrStdStringSet::begin_, and UPtrStdStringSet::end_.
UPtrStdStringSet sub (Iterator begin, Iterator end) const inline
Subset this string set using iterator range.
Definition at line 410 of file string_set.hpp.
References UPtrStdStringSet::UPtrStdStringSet().
Member Data Documentation
Iterator begin_ protected
vector of std::string objects
Definition at line 432 of file string_set.hpp.
Referenced by UPtrStdStringSet::begin(), and UPtrStdStringSet::size().
Iterator end_ protected
Definition at line 432 of file string_set.hpp.
Referenced by UPtrStdStringSet::end(), and UPtrStdStringSet::size().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/string_set.hpp