Thrill: LeastSquaresGradient< Vector > Class Template Reference
LeastSquaresGradient< Vector > Class Template Reference
Detailed Description
template<typename Vector>
class examples::stochastic_gradient_descent::LeastSquaresGradient< Vector >
simple implementation of a gradient computation class using a least squares cost function and a linear model (y = w*x)
Definition at line 86 of file stochastic_gradient_descent.hpp.
#include <stochastic_gradient_descent.hpp>
Static Public Member Functions
static GradientResult< Vector > Compute (const Vector &data, double label, const Vector &weights)
Member Function Documentation
Compute()
static GradientResult<Vector> Compute (const Vector & data, double label, const Vector & weights) inline static
Definition at line 89 of file stochastic_gradient_descent.hpp.
References DataPoint< Vector >::data, Vector< D, Type >::dot(), examples::logistic_regression::gradient(), and DataPoint< Vector >::label.
Referenced by StochasticGradientDescent< Vector >::optimize().
The documentation for this class was generated from the following file:
examples/stochastic_gradient_descent/stochastic_gradient_descent.hpp