Thrill: MixBlockQueueReader Class Reference
MixBlockQueueReader Class Reference
Data Subsystem Layer
Detailed Description
Reader to retrieve items in unordered sequence from a MixBlockQueue.
This is not a full implementation of all methods available in a normal BlockReader. Mainly, this is because only retrieval of whole items are possible. Due to the unordered sequence, these probably have to be all of equal type as well.
The Reader supports all combinations of consuming and keeping. However, do not assume that the second round of reading delivers items in the same order as the first. This is because once items are cached inside the BlockQueues of MixBlockQueue, we use a plain CatReader to deliver them again (which is probably faster as it has a sequential access pattern).
See MixBlockQueue for more information on how items are read.
Definition at line 203 of file mix_block_queue.hpp.
#include <mix_block_queue.hpp>
Public Types
using CatBlockReader = BlockReader< CatBlockSource >
using CatBlockSource = data::CatBlockSource< DynBlockSource >
Public Member Functions
MixBlockQueueReader (MixBlockQueue &mix_queue, bool consume, size_t local_worker_id)
MixBlockQueueReader (const MixBlockQueueReader &)=delete
non-copyable: delete copy-constructor
MixBlockQueueReader (MixBlockQueueReader &&)=default
move-constructor: default
~MixBlockQueueReader ()
Possibly consume unread blocks.
bool HasNext ()
HasNext() returns true if at least one more item is available.
template<typename T >
T Next ()
Next() reads a complete item T.
MixBlockQueueReader & operator= (const MixBlockQueueReader &)=delete
non-copyable: delete assignment operator
MixBlockQueueReader & operator= (MixBlockQueueReader &&)=default
move-assignment operator: default
Private Member Functions
bool PullBlock ()
Private Attributes
CatBlockReader cat_reader_ { CatBlockSource() }
MixBlockQueue & mix_queue_
reference to mix queue
const bool reread_
Attributes for Mix Reading
std::vector< BlockQueue::Reader > readers_
sub-readers for each block queue in mix queue
size_t selected_ = size_t(-1)
reader currently selected
size_t available_ = 0
number of available items on the selected reader
std::vector< size_t > available_at_
size_t open_ = mix_queue_.num_workers_
number of readers still open
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
using CatBlockReader = BlockReader<CatBlockSource>
Definition at line 209 of file mix_block_queue.hpp.
using CatBlockSource = data::CatBlockSource<DynBlockSource>
Definition at line 208 of file mix_block_queue.hpp.
Constructor & Destructor Documentation
MixBlockQueueReader (MixBlockQueue & mix_queue, bool consume, size_t local_worker_id)
Definition at line 147 of file mix_block_queue.cpp.
References MixBlockQueueReader::available_at_, MixBlockQueueReader::cat_reader_, MixBlockQueueReader::mix_queue_, MixBlockQueue::num_workers_, MixBlockQueue::queues_, MixBlockQueueReader::readers_, and MixBlockQueueReader::reread_.
MixBlockQueueReader (const MixBlockQueueReader &) delete
non-copyable: delete copy-constructor
MixBlockQueueReader (MixBlockQueueReader &&) default
move-constructor: default
~MixBlockQueueReader ()
Possibly consume unread blocks.
Definition at line 173 of file mix_block_queue.cpp.
Member Function Documentation
bool HasNext () inline
HasNext() returns true if at least one more item is available.
Definition at line 227 of file mix_block_queue.hpp.
References MixBlockQueueReader::available_, MixBlockQueueReader::cat_reader_, BlockReader< BlockSource >::HasNext(), MixBlockQueueReader::open_, MixBlockQueueReader::PullBlock(), and MixBlockQueueReader::reread_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp(), MixBlockQueueReader::Next(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::ReceiveItems().
T Next () inline
Next() reads a complete item T.
Definition at line 238 of file mix_block_queue.hpp.
References MixBlockQueueReader::available_, MixBlockQueueReader::cat_reader_, MixBlockQueueReader::HasNext(), MixBlockQueueReader::PullBlock(), MixBlockQueueReader::readers_, MixBlockQueueReader::reread_, and MixBlockQueueReader::selected_.
MixBlockQueueReader& operator= (const MixBlockQueueReader &) delete
non-copyable: delete assignment operator
MixBlockQueueReader& operator= (MixBlockQueueReader &&) default
move-assignment operator: default
bool PullBlock () private
Definition at line 177 of file mix_block_queue.cpp.
References MixBlockQueueReader::available_, MixBlockQueueReader::available_at_, MixBlockQueue::SrcBlockPair::block, Block::IsValid(), LOG, MixBlockQueueReader::mix_queue_, Block::num_items(), MixBlockQueueReader::open_, MixBlockQueue::Pop(), MixBlockQueue::queues_, MixBlockQueueReader::readers_, MixBlockQueueReader::selected_, and MixBlockQueue::SrcBlockPair::src.
Referenced by MixBlockQueueReader::HasNext(), and MixBlockQueueReader::Next().
Member Data Documentation
size_t available_ = 0 private
number of available items on the selected reader
Definition at line 278 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::HasNext(), MixBlockQueueReader::Next(), and MixBlockQueueReader::PullBlock().
std::vector<size_t> available_at_ private
number of additional items available at reader (excluding current available_)
Definition at line 282 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::MixBlockQueueReader(), and MixBlockQueueReader::PullBlock().
CatBlockReader cat_reader_ { CatBlockSource() } private
for rereading the mix queue: use a cat reader on the embedded BlockQueue's files.
Definition at line 291 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::HasNext(), MixBlockQueueReader::MixBlockQueueReader(), and MixBlockQueueReader::Next().
constexpr bool debug = false static private
Definition at line 205 of file mix_block_queue.hpp.
MixBlockQueue& mix_queue_ private
reference to mix queue
Definition at line 262 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::MixBlockQueueReader(), and MixBlockQueueReader::PullBlock().
size_t open_ = mix_queue_.num_workers_ private
number of readers still open
Definition at line 285 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::HasNext(), and MixBlockQueueReader::PullBlock().
std::vector<BlockQueue::Reader> readers_ private
sub-readers for each block queue in mix queue
Definition at line 272 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::MixBlockQueueReader(), MixBlockQueueReader::Next(), and MixBlockQueueReader::PullBlock().
const bool reread_ private
flag whether we are rereading the mix queue by reading the files using a cat_reader_.
Definition at line 266 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::HasNext(), MixBlockQueueReader::MixBlockQueueReader(), and MixBlockQueueReader::Next().
size_t selected_ = size_t(-1) private
reader currently selected
Definition at line 275 of file mix_block_queue.hpp.
Referenced by MixBlockQueueReader::Next(), and MixBlockQueueReader::PullBlock().
The documentation for this class was generated from the following files:
thrill/data/mix_block_queue.hpp
thrill/data/mix_block_queue.cpp