Thrill: Dispatcher Class Reference
Dispatcher Class Reference abstract
Network Subsystem Layer
Detailed Description
Dispatcher is a high level wrapper for asynchronous callback processing.
. One can register Connection objects for readability and writability checks, buffered reads and writes with completion callbacks, and also timer functions.
Definition at line 522 of file dispatcher.hpp.
#include <dispatcher.hpp>
Classes
class AsyncReadBuffer
struct Timer
struct for timer callbacks
Public Member Functions
Dispatcher (mem::Manager &mem_manager)
default constructor
Dispatcher (const Dispatcher &)=delete
non-copyable: delete copy-constructor
virtual ~Dispatcher ()
virtual destructor
Dispatcher & operator= (const Dispatcher &)=delete
non-copyable: delete assignment operator
Timeout Callbacks
void AddTimer (const std::chrono::milliseconds &timeout, const TimerCallback &cb)
Register a relative timeout callback.
Connection Callbacks
virtual void AddRead (Connection &c, const AsyncCallback &read_cb)=0
Register a buffered read callback and a default exception callback.
virtual void AddWrite (Connection &c, const AsyncCallback &write_cb)=0
Register a buffered write callback and a default exception callback.
virtual void Cancel (Connection &c)=0
Cancel all callbacks on a given connection.
Asynchronous Data Reader/Writer Callbacks
virtual void AsyncRead (Connection &c, size_t size, const AsyncReadBufferCallback &done_cb)
asynchronously read n bytes and deliver them to the callback
virtual void AsyncRead (Connection &c, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &done_cb)
asynchronously read the full ByteBlock and deliver it to the callback
virtual void AsyncWrite (Connection &c, Buffer &&buffer, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
virtual void AsyncWrite (Connection &c, data::PinnedBlock &&block, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, const void *buffer, size_t size, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, const std::string &str, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
Dispatch
void Dispatch ()
Dispatch one or more events.
void Loop ()
Loop over Dispatch() until terminate_ flag is set.
virtual void Interrupt ()=0
Interrupt current dispatch.
void Terminate ()
bool HasAsyncWrites () const
Check whether there are still AsyncWrite()s in the queue.
Protected Types
using TimerPQ = std::priority_queue< Timer, std::vector< Timer, mem::GPoolAllocator< Timer > > >
priority queue of timer callbacks
Protected Member Functions
virtual void DispatchOne (const std::chrono::milliseconds &timeout)=0
Static Protected Member Functions
static bool ExceptionCallback (Connection &c)
Default exception handler.
Protected Attributes
std::deque< AsyncReadBuffer,
mem::GPoolAllocator
< AsyncReadBuffer > > async_read_
deque of asynchronous readers
std::deque< AsyncReadByteBlock,
mem::GPoolAllocator
< AsyncReadByteBlock > > async_read_block_
deque of asynchronous readers
std::deque< AsyncWriteBuffer,
mem::GPoolAllocator
< AsyncWriteBuffer > > async_write_
deque of asynchronous writers
std::deque< AsyncWriteBlock,
mem::GPoolAllocator
< AsyncWriteBlock > > async_write_block_
deque of asynchronous writers
mem::Manager & mem_manager_
superior memory manager
std::atomic< bool > terminate_ { false }
true if dispatcher needs to stop
TimerPQ timer_pq_
Private Types
using milliseconds = std::chrono::milliseconds
import into class namespace
using steady_clock = std::chrono::steady_clock
import into class namespace
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
using milliseconds = std::chrono::milliseconds private
import into class namespace
Definition at line 531 of file dispatcher.hpp.
using steady_clock = std::chrono::steady_clock private
import into class namespace
Definition at line 528 of file dispatcher.hpp.
using TimerPQ = std::priority_queue< Timer, std::vector<Timer, mem::GPoolAllocator<Timer> > > protected
priority queue of timer callbacks
Definition at line 790 of file dispatcher.hpp.
Constructor & Destructor Documentation
Dispatcher (mem::Manager & mem_manager) inline explicit
default constructor
Definition at line 538 of file dispatcher.hpp.
Dispatcher (const Dispatcher &) delete
non-copyable: delete copy-constructor
virtual ~Dispatcher () inline virtual
virtual destructor
Definition at line 547 of file dispatcher.hpp.
Member Function Documentation
virtual void AddRead (Connection & c, const AsyncCallback & read_cb) pure virtual
Register a buffered read callback and a default exception callback.
Implemented in Dispatcher, SelectDispatcher, and Dispatcher.
Referenced by Dispatcher::AsyncRead().
void AddTimer (const std::chrono::milliseconds & timeout, const TimerCallback & cb) inline
Register a relative timeout callback.
Definition at line 553 of file dispatcher.hpp.
References Dispatcher::timer_pq_.
virtual void AddWrite (Connection & c, const AsyncCallback & write_cb) pure virtual
Register a buffered write callback and a default exception callback.
Implemented in Dispatcher, SelectDispatcher, and Dispatcher.
Referenced by Dispatcher::AsyncWrite().
virtual void AsyncRead (Connection & c, size_t size, const AsyncReadBufferCallback & done_cb) inline virtual
asynchronously read n bytes and deliver them to the callback
Reimplemented in Dispatcher.
Definition at line 580 of file dispatcher.hpp.
References Dispatcher::AddRead(), Dispatcher::async_read_, Connection::IsValid(), and LOG.
virtual void AsyncRead (Connection & c, size_t size, data::PinnedByteBlockPtr && block, const AsyncReadByteBlockCallback & done_cb) inline virtual
asynchronously read the full ByteBlock and deliver it to the callback
Reimplemented in Dispatcher.
Definition at line 600 of file dispatcher.hpp.
References Dispatcher::AddRead(), Dispatcher::async_read_block_, Connection::IsValid(), and LOG.
virtual void AsyncWrite (Connection & c, Buffer && buffer, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline virtual
asynchronously write buffer and callback when delivered. The buffer is MOVED into the async writer.
Reimplemented in Dispatcher.
Definition at line 622 of file dispatcher.hpp.
References Dispatcher::AddWrite(), Dispatcher::async_write_, and Connection::IsValid().
Referenced by Dispatcher::AsyncWriteCopy().
virtual void AsyncWrite (Connection & c, data::PinnedBlock && block, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline virtual
asynchronously write buffer and callback when delivered. The buffer is MOVED into the async writer.
Reimplemented in Dispatcher.
Definition at line 643 of file dispatcher.hpp.
References Dispatcher::AddWrite(), Dispatcher::async_write_block_, and Connection::IsValid().
void AsyncWriteCopy (Connection & c, const void * buffer, size_t size, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline
asynchronously write buffer and callback when delivered. COPIES the data into a Buffer!
Definition at line 664 of file dispatcher.hpp.
References Dispatcher::AsyncWrite().
Referenced by Dispatcher::AsyncWriteCopy().
void AsyncWriteCopy (Connection & c, const std::string & str, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline
asynchronously write buffer and callback when delivered. COPIES the data into a Buffer!
Definition at line 672 of file dispatcher.hpp.
References Dispatcher::AsyncWriteCopy().
virtual void Cancel (Connection & c) pure virtual
Cancel all callbacks on a given connection.
Implemented in Dispatcher, SelectDispatcher, and Dispatcher.
void Dispatch () inline
Dispatch one or more events.
Definition at line 684 of file dispatcher.hpp.
References Dispatcher::async_read_, Dispatcher::async_read_block_, Dispatcher::async_write_, Dispatcher::async_write_block_, Dispatcher::Timer::cb, Dispatcher::DispatchOne(), LOG, Dispatcher::Timer::next_timeout, sLOG, Dispatcher::terminate_, Dispatcher::Timer::timeout, and Dispatcher::timer_pq_.
Referenced by Dispatcher::Loop().
virtual void DispatchOne (const std::chrono::milliseconds & timeout) protected pure virtual
Implemented in Dispatcher, Dispatcher, and SelectDispatcher.
Referenced by Dispatcher::Dispatch().
static bool ExceptionCallback (Connection & c) inline static protected
Default exception handler.
Definition at line 881 of file dispatcher.hpp.
References Connection::ToString().
bool HasAsyncWrites () const inline
Check whether there are still AsyncWrite()s in the queue.
Definition at line 752 of file dispatcher.hpp.
References Dispatcher::async_write_, and Dispatcher::async_write_block_.
virtual void Interrupt () pure virtual
Interrupt current dispatch.
Implemented in Dispatcher, Dispatcher, and SelectDispatcher.
void Loop () inline
Loop over Dispatch() until terminate_ flag is set.
Definition at line 735 of file dispatcher.hpp.
References Dispatcher::Dispatch(), and Dispatcher::terminate_.
Dispatcher& operator= (const Dispatcher &) delete
non-copyable: delete assignment operator
void Terminate () inline
Causes the dispatcher to break out after the next timeout occurred Does not interrupt the currently running read/write operation, but breaks after the operation finished or timed out.
Definition at line 747 of file dispatcher.hpp.
References Dispatcher::terminate_.
Member Data Documentation
std::deque<AsyncReadBuffer, mem::GPoolAllocator<AsyncReadBuffer> > async_read_ protected
deque of asynchronous readers
Definition at line 866 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncRead(), and Dispatcher::Dispatch().
std::deque<AsyncReadByteBlock, mem::GPoolAllocator<AsyncReadByteBlock> > async_read_block_ protected
deque of asynchronous readers
Definition at line 874 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncRead(), and Dispatcher::Dispatch().
std::deque<AsyncWriteBuffer, mem::GPoolAllocator<AsyncWriteBuffer> > async_write_ protected
deque of asynchronous writers
Definition at line 870 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncWrite(), Dispatcher::Dispatch(), and Dispatcher::HasAsyncWrites().
std::deque<AsyncWriteBlock, mem::GPoolAllocator<AsyncWriteBlock> > async_write_block_ protected
deque of asynchronous writers
Definition at line 878 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncWrite(), Dispatcher::Dispatch(), and Dispatcher::HasAsyncWrites().
constexpr bool debug = false static private
Definition at line 524 of file dispatcher.hpp.
mem::Manager& mem_manager_ protected
superior memory manager
Definition at line 765 of file dispatcher.hpp.
Referenced by SelectDispatcher::CheckSize(), Dispatcher::Dispatcher(), and Dispatcher::GetWatch().
std::atomic<bool> terminate_ { false } protected
true if dispatcher needs to stop
Definition at line 762 of file dispatcher.hpp.
Referenced by Dispatcher::Dispatch(), Dispatcher::Loop(), and Dispatcher::Terminate().
TimerPQ timer_pq_ protected
priority queue of timer callbacks, obviously kept in timeout order. Currently not addressable.
Definition at line 794 of file dispatcher.hpp.
Referenced by Dispatcher::AddTimer(), and Dispatcher::Dispatch().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp