Thrill: BufferBuilder Class Reference
BufferBuilder Class Reference
Network Subsystem Layer
Detailed Description
BufferBuilder represents a dynamically growable area of memory, which can be modified by appending integral data types via Put() and other basic operations.
Definition at line 42 of file buffer_builder.hpp.
#include <buffer_builder.hpp>
Public Member Functions
Construction, Movement, Destruction
BufferBuilder ()=default
Create a new empty object.
BufferBuilder (const BufferBuilder &other)
Copy-Constructor, duplicates memory content.
BufferBuilder (BufferBuilder &&other) noexcept
Move-Constructor, moves memory area.
BufferBuilder (const void *data, size_t size)
Constructor, copy memory area.
BufferBuilder (size_t size)
Constructor, create object with n bytes pre-allocated.
BufferBuilder (const std::string &str)
Constructor from std::string, COPIES string content.
BufferBuilder & operator= (const BufferBuilder &other)
Assignment operator: copy other's memory range into buffer.
BufferBuilder & operator= (BufferBuilder &&other) noexcept
Move-Assignment operator: move other's memory area into buffer.
~BufferBuilder ()
Destroys the memory space.
BufferBuilder & Deallocate ()
Data, Size, and Capacity Accessors
const Byte * data () const
Return a pointer to the currently kept memory area.
Byte * data ()
Return a writeable pointer to the currently kept memory area.
size_t size () const
Return the currently used length in bytes.
size_t capacity () const
Return the currently allocated buffer capacity.
Buffer Growing, Clearing, and other Management
BufferBuilder & Clear ()
Clears the memory contents, does not deallocate the memory.
BufferBuilder & set_size (size_t n)
BufferBuilder & Reserve (size_t n)
Make sure that at least n bytes are allocated.
BufferBuilder & DynReserve (size_t n)
const Byte * Detach ()
Detach the memory from the object, returns the memory pointer.
std::string ToString () const
Explicit conversion to std::string (copies memory of course).
Buffer ToBuffer ()
Explicit conversion to Buffer MOVING the memory ownership.
Assignment or Alignment
BufferBuilder & Assign (const void *data, size_t len)
BufferBuilder & Assign (const BufferBuilder &other)
BufferBuilder & Align (size_t n)
Align the size of the buffer to a multiple of n. Fills up with 0s.
Appending Write Functions
BufferBuilder & Append (const void *data, size_t len)
Append a memory range to the buffer.
BufferBuilder & Append (const class BufferBuilder &bb)
Append the contents of a different buffer object to this one.
BufferBuilder & AppendString (const std::string &s)
template<typename Type >
BufferBuilder & Put (const Type &item)
BufferBuilder & PutByte (Byte data)
Put a single byte to the buffer (used via CRTP from ItemWriterToolsBase)
template<typename Type >
BufferBuilder & PutRaw (const Type &item)
Access
iterator begin ()
return mutable iterator to first element
const_iterator begin () const
return constant iterator to first element
const_iterator cbegin () const
return constant iterator to first element
iterator end ()
return mutable iterator beyond last element
const_iterator end () const
return constant iterator beyond last element
const_iterator cend () const
return constant iterator beyond last element
reference operator[] (size_t i)
return the i-th position of the vector
Public Member Functions inherited from ItemWriterToolsBase< BufferBuilder >
BufferBuilder & PutString (const char *data, size_t len)
Put a string by saving it's length followed by the data itself.
BufferBuilder & PutString (const uint8_t *data, size_t len)
Put a string by saving it's length followed by the data itself.
BufferBuilder & PutString (const std::string &str)
Put a string by saving it's length followed by the data itself.
BufferBuilder & PutVarint (uint64_t v)
Append a varint to the writer.
BufferBuilder & PutVarint32 (uint32_t v)
Append a varint to the writer.
Private Types
using Byte = unsigned char
type used to store the bytes
using const_iterator = const Byte *
simple pointer iterators
using const_reference = const Byte &
simple pointer references
using iterator = Byte *
simple pointer iterators
using reference = Byte &
simple pointer references
Private Attributes
size_t capacity_ = 0
Total capacity of buffer.
Byte * data_ = nullptr
Allocated buffer pointer.
size_t size_ = 0
Size of valid data.
Member Typedef Documentation
using Byte = unsigned char private
type used to store the bytes
Definition at line 47 of file buffer_builder.hpp.
using const_iterator = const Byte * private
simple pointer iterators
Definition at line 52 of file buffer_builder.hpp.
using const_reference = const Byte & private
simple pointer references
Definition at line 56 of file buffer_builder.hpp.
using iterator = Byte * private
simple pointer iterators
Definition at line 50 of file buffer_builder.hpp.
using reference = Byte & private
simple pointer references
Definition at line 54 of file buffer_builder.hpp.
Constructor & Destructor Documentation
BufferBuilder () default
Create a new empty object.
BufferBuilder (const BufferBuilder & other) inline
Copy-Constructor, duplicates memory content.
Definition at line 75 of file buffer_builder.hpp.
References BufferBuilder::Assign().
BufferBuilder (BufferBuilder && other) inline noexcept
Move-Constructor, moves memory area.
Definition at line 80 of file buffer_builder.hpp.
BufferBuilder (const void * data, size_t size) inline
Constructor, copy memory area.
Definition at line 88 of file buffer_builder.hpp.
References BufferBuilder::Assign().
BufferBuilder (size_t size) inline explicit
Constructor, create object with n bytes pre-allocated.
Definition at line 93 of file buffer_builder.hpp.
References BufferBuilder::Reserve().
BufferBuilder (const std::string & str) inline explicit
Constructor from std::string, COPIES string content.
Definition at line 98 of file buffer_builder.hpp.
References BufferBuilder::Assign().
~BufferBuilder () inline
Destroys the memory space.
Definition at line 126 of file buffer_builder.hpp.
References BufferBuilder::Deallocate().
Member Function Documentation
BufferBuilder& Align (size_t n) inline
Align the size of the buffer to a multiple of n. Fills up with 0s.
Definition at line 263 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data_, BufferBuilder::DynReserve(), and BufferBuilder::size_.
BufferBuilder& Append (const void * data, size_t len) inline
Append a memory range to the buffer.
Definition at line 284 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data(), BufferBuilder::data_, BufferBuilder::DynReserve(), and BufferBuilder::size_.
Referenced by BufferBuilder::Append(), and BufferBuilder::AppendString().
BufferBuilder& Append (const class BufferBuilder & bb) inline
Append the contents of a different buffer object to this one.
Definition at line 295 of file buffer_builder.hpp.
References BufferBuilder::Append(), BufferBuilder::data(), and BufferBuilder::size().
BufferBuilder& AppendString (const std::string & s) inline
Append to contents of a std::string, excluding the null (which isn't contained in the string size anyway).
Definition at line 301 of file buffer_builder.hpp.
References BufferBuilder::Append().
BufferBuilder& Assign (const void * data, size_t len) inline
Copy a memory range into the buffer, overwrites all current data. Roughly equivalent to clear() followed by append().
Definition at line 243 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data(), BufferBuilder::data_, BufferBuilder::Reserve(), and BufferBuilder::size_.
Referenced by BufferBuilder::Assign(), BufferBuilder::BufferBuilder(), and BufferBuilder::operator=().
BufferBuilder& Assign (const BufferBuilder & other) inline
Copy the contents of another buffer object into this buffer, overwrites all current data. Roughly equivalent to clear() followed by append().
Definition at line 255 of file buffer_builder.hpp.
References BufferBuilder::Assign(), BufferBuilder::data(), and BufferBuilder::size().
iterator begin () inline
return mutable iterator to first element
Definition at line 339 of file buffer_builder.hpp.
References BufferBuilder::data_.
Referenced by BufferBuilder::cbegin(), ReadLinesNode::InputLineIteratorUncompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::Next(), ReadLinesNode::InputLineIteratorCompressed::Next(), BufferBuilder::operator[](), and ReadLinesNode::InputLineIterator::ReadBlock().
const_iterator begin () const inline
return constant iterator to first element
Definition at line 342 of file buffer_builder.hpp.
References BufferBuilder::data_.
size_t capacity () const inline
Return the currently allocated buffer capacity.
Definition at line 161 of file buffer_builder.hpp.
References BufferBuilder::capacity_.
const_iterator cbegin () const inline
return constant iterator to first element
Definition at line 345 of file buffer_builder.hpp.
References BufferBuilder::begin().
const_iterator cend () const inline
return constant iterator beyond last element
Definition at line 355 of file buffer_builder.hpp.
References BufferBuilder::end().
BufferBuilder& Clear () inline
Clears the memory contents, does not deallocate the memory.
Definition at line 171 of file buffer_builder.hpp.
References BufferBuilder::size_.
const Byte* data () const inline
Return a pointer to the currently kept memory area.
Definition at line 146 of file buffer_builder.hpp.
References BufferBuilder::data_.
Referenced by BufferBuilder::Append(), BufferBuilder::Assign(), BufferBuilder::Detach(), BufferBuilder::operator=(), BufferBuilder::PutByte(), ReadLinesNode::InputLineIterator::ReadBlock(), Connection::ReceiveSend(), Connection::Send(), Connection::SendN(), and Connection::SendReceive().
Byte* data () inline
Return a writeable pointer to the currently kept memory area.
Definition at line 151 of file buffer_builder.hpp.
References BufferBuilder::data_.
BufferBuilder& Deallocate () inline
Deallocates the kept memory space (we use dealloc() instead of free() as a name, because sometimes "free" is replaced by the preprocessor)
Definition at line 132 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data_, free(), and BufferBuilder::size_.
Referenced by BufferBuilder::~BufferBuilder().
const Byte* Detach () inline
Detach the memory from the object, returns the memory pointer.
Definition at line 217 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data(), BufferBuilder::data_, and BufferBuilder::size_.
Referenced by BufferBuilder::ToBuffer().
BufferBuilder& DynReserve (size_t n) inline
Dynamically allocate more memory. At least n bytes will be available, probably more to compensate future growth.
Definition at line 198 of file buffer_builder.hpp.
References BufferBuilder::capacity_, and BufferBuilder::Reserve().
Referenced by BufferBuilder::Align(), BufferBuilder::Append(), and BufferBuilder::Put().
iterator end () inline
return mutable iterator beyond last element
Definition at line 349 of file buffer_builder.hpp.
References BufferBuilder::data_, and BufferBuilder::size_.
Referenced by BufferBuilder::cend(), ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), ReadLinesNode::InputLineIteratorUncompressed::Next(), and ReadLinesNode::InputLineIteratorCompressed::Next().
const_iterator end () const inline
return constant iterator beyond last element
Definition at line 352 of file buffer_builder.hpp.
References BufferBuilder::data_, and BufferBuilder::size_.
BufferBuilder& operator= (const BufferBuilder & other) inline
Assignment operator: copy other's memory range into buffer.
Definition at line 103 of file buffer_builder.hpp.
References BufferBuilder::Assign(), BufferBuilder::data(), and BufferBuilder::size().
BufferBuilder& operator= (BufferBuilder && other) inline noexcept
Move-Assignment operator: move other's memory area into buffer.
Definition at line 111 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data_, free(), and BufferBuilder::size_.
reference operator[] (size_t i) inline
return the i-th position of the vector
Definition at line 359 of file buffer_builder.hpp.
References BufferBuilder::begin(), and BufferBuilder::size_.
BufferBuilder& Put (const Type & item) inline
Put (append) a single item of the template type T to the buffer. Be careful with implicit type conversions!
Definition at line 308 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data_, BufferBuilder::DynReserve(), and BufferBuilder::size_.
Referenced by StreamMultiplexerHeader::Serialize(), and PartitionMultiplexerHeader::Serialize().
BufferBuilder& PutByte (Byte data) inline
Put a single byte to the buffer (used via CRTP from ItemWriterToolsBase)
Definition at line 322 of file buffer_builder.hpp.
References BufferBuilder::data().
BufferBuilder& PutRaw (const Type & item) inline
Put (append) a single item of the template type T to the buffer. Be careful with implicit type conversions!
Definition at line 329 of file buffer_builder.hpp.
BufferBuilder& Reserve (size_t n) inline
Make sure that at least n bytes are allocated.
Definition at line 186 of file buffer_builder.hpp.
References BufferBuilder::capacity_, BufferBuilder::data_, and realloc().
Referenced by BufferBuilder::Assign(), BufferBuilder::BufferBuilder(), BufferBuilder::DynReserve(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), StreamMultiplexerHeader::Serialize(), and PartitionMultiplexerHeader::Serialize().
BufferBuilder& set_size (size_t n) inline
Set the valid bytes in the buffer, use if the buffer is filled directly.
Definition at line 178 of file buffer_builder.hpp.
References BufferBuilder::capacity_, and BufferBuilder::size_.
Referenced by ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), and ReadLinesNode::InputLineIterator::ReadBlock().
size_t size () const inline
Return the currently used length in bytes.
Definition at line 156 of file buffer_builder.hpp.
References BufferBuilder::size_.
Referenced by BufferBuilder::Append(), BufferBuilder::Assign(), ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), ReadLinesNode::InputLineIteratorUncompressed::Next(), BufferBuilder::operator=(), Connection::ReceiveSend(), Connection::Send(), Connection::SendN(), and Connection::SendReceive().
Buffer ToBuffer () inline
Explicit conversion to Buffer MOVING the memory ownership.
Definition at line 230 of file buffer_builder.hpp.
References Buffer::Acquire(), BufferBuilder::data_, BufferBuilder::Detach(), and BufferBuilder::size_.
Referenced by StreamSink::AppendPinnedBlock(), and StreamSink::Close().
std::string ToString () const inline
Explicit conversion to std::string (copies memory of course).
Definition at line 225 of file buffer_builder.hpp.
References BufferBuilder::data_, and BufferBuilder::size_.
Member Data Documentation
size_t capacity_ = 0 private
Total capacity of buffer.
Definition at line 65 of file buffer_builder.hpp.
Referenced by BufferBuilder::Align(), BufferBuilder::Append(), BufferBuilder::Assign(), BufferBuilder::capacity(), BufferBuilder::Deallocate(), BufferBuilder::Detach(), BufferBuilder::DynReserve(), BufferBuilder::operator=(), BufferBuilder::Put(), BufferBuilder::Reserve(), and BufferBuilder::set_size().
Byte* data_ = nullptr private
Allocated buffer pointer.
Definition at line 59 of file buffer_builder.hpp.
Referenced by BufferBuilder::Align(), BufferBuilder::Append(), BufferBuilder::Assign(), BufferBuilder::begin(), BufferBuilder::data(), BufferBuilder::Deallocate(), BufferBuilder::Detach(), BufferBuilder::end(), BufferBuilder::operator=(), BufferBuilder::Put(), BufferBuilder::Reserve(), BufferBuilder::ToBuffer(), and BufferBuilder::ToString().
size_t size_ = 0 private
Size of valid data.
Definition at line 62 of file buffer_builder.hpp.
Referenced by BufferBuilder::Align(), BufferBuilder::Append(), BufferBuilder::Assign(), BufferBuilder::Clear(), BufferBuilder::Deallocate(), BufferBuilder::Detach(), BufferBuilder::end(), BufferBuilder::operator=(), BufferBuilder::operator[](), BufferBuilder::Put(), BufferBuilder::set_size(), BufferBuilder::size(), BufferBuilder::ToBuffer(), and BufferBuilder::ToString().
The documentation for this class was generated from the following file:
thrill/net/buffer_builder.hpp