Thrill: BlockQueueSink Class Reference
BlockQueueSink Class Reference final
Data Subsystem Layer
Detailed Description
BlockSink which interfaces to a File.
Definition at line 175 of file block_queue.hpp.
#include <block_queue.hpp>
Public Member Functions
BlockQueueSink ()
BlockQueueSink (BlockQueue *queue)
BlockQueueSink (const BlockQueueSink &)=default
default copy-constructor
~BlockQueueSink ()
BlockQueueSink & operator= (const BlockQueueSink &)=default
default assignment operator
Methods of a BlockSink
void AppendBlock (const Block &b, bool is_last_block) final
void AppendBlock (Block &&b, bool is_last_block) final
void Close () final
Closes the sink. Must not be called multiple times.
Public Member Functions inherited from BlockSink
BlockSink (BlockPool &block_pool, size_t local_worker_id)
constructor with reference to BlockPool
BlockSink (BlockPool *block_pool, size_t local_worker_id)
constructor with reference to BlockPool
BlockSink (const BlockSink &)=default
default copy-constructor
BlockSink (BlockSink &&)=default
move-constructor: default
virtual ~BlockSink ()
required virtual destructor
virtual PinnedByteBlockPtr AllocateByteBlock (size_t block_size)
virtual void AppendPinnedBlock (PinnedBlock &&b, bool is_last_block)
Appends the PinnedBlock.
BlockPool * block_pool () const
Returns block_pool_.
size_t local_worker_id () const
local worker id to associate pinned block with
common::JsonLogger & logger ()
Returns BlockPool.logger_.
BlockSink & operator= (const BlockSink &)=default
default assignment operator
BlockSink & operator= (BlockSink &&)=default
move-assignment operator: default
virtual void ReleaseByteBlock (ByteBlockPtr &block)
Release an unused ByteBlock with n bytes backing memory.
size_t workers_per_host () const
return number of workers per host
Private Attributes
BlockQueue * queue_
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Static Public Attributes inherited from BlockSink
static constexpr bool allocate_can_fail_ = false
Protected Attributes inherited from BlockSink
size_t local_worker_id_
local worker id to associate pinned block with
Constructor & Destructor Documentation
BlockQueueSink () inline
Definition at line 180 of file block_queue.hpp.
BlockQueueSink (BlockQueue * queue) inline explicit
Definition at line 184 of file block_queue.hpp.
References LOG.
BlockQueueSink (const BlockQueueSink &) default
default copy-constructor
~BlockQueueSink () inline
Definition at line 195 of file block_queue.hpp.
References LOG, and BlockQueueSink::queue_.
Member Function Documentation
void AppendBlock (const Block & b, bool is_last_block) inline final virtual
Append a block to this file, the block must contain given number of items after the offset first.
Implements BlockSink.
Definition at line 204 of file block_queue.hpp.
References BlockQueue::AppendBlock(), and BlockQueueSink::queue_.
void AppendBlock (Block && b, bool is_last_block) inline final virtual
Append a block to this file, the block must contain given number of items after the offset first.
Implements BlockSink.
Definition at line 211 of file block_queue.hpp.
References BlockQueue::AppendBlock(), and BlockQueueSink::queue_.
void Close () inline final virtual
Closes the sink. Must not be called multiple times.
Implements BlockSink.
Definition at line 216 of file block_queue.hpp.
References BlockQueue::Close(), and BlockQueueSink::queue_.
BlockQueueSink& operator= (const BlockQueueSink &) default
default assignment operator
Member Data Documentation
constexpr bool debug = false static private
Definition at line 177 of file block_queue.hpp.
BlockQueue* queue_ private
Definition at line 226 of file block_queue.hpp.
Referenced by BlockQueueSink::AppendBlock(), BlockQueueSink::Close(), and BlockQueueSink::~BlockQueueSink().
The documentation for this class was generated from the following file:
thrill/data/block_queue.hpp