Thrill: block_scheduler_algorithm_simulation< SwappableBlockType > Class Template Reference
block_scheduler_algorithm_simulation< SwappableBlockType > Class Template Reference
Detailed Description
template<class SwappableBlockType>
class foxxll::block_scheduler_algorithm_simulation< SwappableBlockType >
Pseudo block scheduling algorithm only recording the request sequence.
Definition at line 759 of file block_scheduler.hpp.
#include <block_scheduler.hpp>
Public Member Functions
block_scheduler_algorithm_simulation (block_scheduler_type &bs)
block_scheduler_algorithm_simulation (block_scheduler_algorithm_type *old)
virtual ~block_scheduler_algorithm_simulation ()
virtual internal_block_type & acquire (const swappable_block_identifier_type sbid, const bool uninitialized=false)
virtual void deinitialize (swappable_block_identifier_type sbid)
virtual bool evictable_blocks_empty ()
virtual
swappable_block_identifier_type evictable_blocks_pop ()
virtual void explicit_timestep ()
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid)
virtual void initialize (swappable_block_identifier_type sbid, external_block_type)
virtual bool is_initialized (const swappable_block_identifier_type sbid) const
virtual bool is_simulating () const
virtual void release (swappable_block_identifier_type sbid, const bool dirty)
virtual void swappable_blocks_resize (swappable_block_identifier_type size)
Public Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm (block_scheduler_type &bs)
block_scheduler_algorithm (block_scheduler_algorithm *old)
block_scheduler_algorithm (const block_scheduler_algorithm &)=delete
non-copyable: delete copy-constructor
virtual ~block_scheduler_algorithm ()
virtual const
prediction_sequence_type & get_prediction_sequence () const
block_scheduler_algorithm & operator= (const block_scheduler_algorithm &)=delete
non-copyable: delete assignment operator
Protected Types
using block_scheduler_algorithm_type = block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using prediction_sequence_element_type = typename block_scheduler_type::prediction_sequence_element
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
using time_type = typename block_scheduler_algorithm_type::time_type
Protected Types inherited from block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using prediction_sequence_type = typename block_scheduler_type::prediction_sequence_type
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
using time_type = typename block_scheduler_type::time_type
Protected Member Functions
void init ()
void return_free_internal_block (internal_block_type *iblock)
Protected Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm * get_algorithm_from_block_scheduler ()
internal_block_type * get_free_internal_block_from_block_scheduler ()
void return_free_internal_block_to_block_scheduler (internal_block_type *iblock)
Return an internal_block to the block_scheduler.
Protected Attributes
internal_block_type dummy_block
std::stack
< swappable_block_identifier_type > evictable_blocks
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
bool last_op_release
std::vector< size_t > reference_counts
time_type time_count
Protected Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
prediction_sequence_type prediction_sequence
std::vector< SwappableBlockType > & swappable_blocks
Additional Inherited Members
Public Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_type & bs
Member Typedef Documentation
using block_scheduler_algorithm_type = block_scheduler_algorithm<SwappableBlockType> protected
Definition at line 763 of file block_scheduler.hpp.
using block_scheduler_type = block_scheduler<SwappableBlockType> protected
Definition at line 762 of file block_scheduler.hpp.
using external_block_type = typename block_scheduler_type::external_block_type protected
Definition at line 765 of file block_scheduler.hpp.
using internal_block_type = typename block_scheduler_type::internal_block_type protected
Definition at line 764 of file block_scheduler.hpp.
using prediction_sequence_element_type = typename block_scheduler_type::prediction_sequence_element protected
Definition at line 767 of file block_scheduler.hpp.
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type protected
Definition at line 766 of file block_scheduler.hpp.
using time_type = typename block_scheduler_algorithm_type::time_type protected
Definition at line 768 of file block_scheduler.hpp.
Constructor & Destructor Documentation
block_scheduler_algorithm_simulation (block_scheduler_type & bs) inline explicit
Definition at line 797 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::init().
block_scheduler_algorithm_simulation (block_scheduler_algorithm_type * old) inline explicit
Definition at line 804 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::init().
virtual ~block_scheduler_algorithm_simulation () inline virtual
Definition at line 811 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_simulation< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, and TLX_LOG1.
Member Function Documentation
virtual internal_block_type& acquire (const swappable_block_identifier_type sbid, const bool uninitialized = false) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 834 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::dummy_block, block_scheduler_algorithm_simulation< SwappableBlockType >::last_op_release, block_scheduler< SwappableBlockType >::op_acquire, block_scheduler< SwappableBlockType >::op_acquire_uninitialized, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
virtual void deinitialize (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 864 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_deinitialize, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
virtual bool evictable_blocks_empty () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 824 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::init().
virtual swappable_block_identifier_type evictable_blocks_pop () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 827 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::init().
virtual void explicit_timestep () inline virtual
Reimplemented from block_scheduler_algorithm< SwappableBlockType >.
Definition at line 899 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 880 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_extract_external_block, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
void init () inline protected
Definition at line 787 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm< SwappableBlockType >::get_algorithm_from_block_scheduler(), block_scheduler_algorithm_simulation< SwappableBlockType >::is_initialized(), block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::block_scheduler_algorithm_simulation().
virtual void initialize (swappable_block_identifier_type sbid, external_block_type) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 872 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_initialize, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
virtual bool is_initialized (const swappable_block_identifier_type sbid) const inline virtual
Reimplemented from block_scheduler_algorithm< SwappableBlockType >.
Definition at line 894 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::init().
virtual bool is_simulating () const inline virtual
Reimplemented from block_scheduler_algorithm< SwappableBlockType >.
Definition at line 902 of file block_scheduler.hpp.
virtual void release (swappable_block_identifier_type sbid, const bool dirty) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 849 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::last_op_release, block_scheduler< SwappableBlockType >::op_release, block_scheduler< SwappableBlockType >::op_release_dirty, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts, and block_scheduler_algorithm_simulation< SwappableBlockType >::time_count.
void return_free_internal_block (internal_block_type * iblock) inline protected
Definition at line 784 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::return_free_internal_block_to_block_scheduler().
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::~block_scheduler_algorithm_simulation().
virtual void swappable_blocks_resize (swappable_block_identifier_type size) inline virtual
Reimplemented from block_scheduler_algorithm< SwappableBlockType >.
Definition at line 889 of file block_scheduler.hpp.
References block_scheduler_algorithm_simulation< SwappableBlockType >::reference_counts.
Member Data Documentation
internal_block_type dummy_block protected
Definition at line 782 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::acquire().
std::stack<swappable_block_identifier_type> evictable_blocks protected
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
Definition at line 778 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_simulation< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm_simulation< SwappableBlockType >::init(), and block_scheduler_algorithm_simulation< SwappableBlockType >::~block_scheduler_algorithm_simulation().
bool last_op_release protected
Definition at line 780 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::acquire(), and block_scheduler_algorithm_simulation< SwappableBlockType >::release().
std::vector<size_t> reference_counts protected
Definition at line 781 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::acquire(), block_scheduler_algorithm_simulation< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_simulation< SwappableBlockType >::extract_external_block(), block_scheduler_algorithm_simulation< SwappableBlockType >::init(), block_scheduler_algorithm_simulation< SwappableBlockType >::initialize(), block_scheduler_algorithm_simulation< SwappableBlockType >::is_initialized(), block_scheduler_algorithm_simulation< SwappableBlockType >::release(), and block_scheduler_algorithm_simulation< SwappableBlockType >::swappable_blocks_resize().
time_type time_count protected
Definition at line 779 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_simulation< SwappableBlockType >::acquire(), block_scheduler_algorithm_simulation< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_simulation< SwappableBlockType >::explicit_timestep(), block_scheduler_algorithm_simulation< SwappableBlockType >::extract_external_block(), block_scheduler_algorithm_simulation< SwappableBlockType >::initialize(), and block_scheduler_algorithm_simulation< SwappableBlockType >::release().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/block_scheduler.hpp