Thrill: Dispatcher Class Reference
Dispatcher Class Reference final
MPI Network API
Detailed Description
Definition at line 79 of file dispatcher.hpp.
#include <dispatcher.hpp>
Classes
class MpiAsync
This is the big answer to what happens when an MPI async request is signaled as complete: it unifies all possible async requests, including the reference counts they hold on the appropriate buffers, and dispatches the correct callbacks when done.
struct Watch
callback vectors per peer
Public Types
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Public Member Functions
Dispatcher (size_t group_size)
constructor
~Dispatcher ()
destructor
void AddAsyncRequest (const MPI_Request &req, const AsyncRequestCallback &callback)
void AddRead (net::Connection &c, const Callback &read_cb) final
Register a buffered read callback and a default exception callback.
void AddWrite (net::Connection &, const Callback &) final
Register a buffered write callback and a default exception callback.
void AsyncRead (net::Connection &c, uint32_t seq, size_t size, const AsyncReadBufferCallback &done_cb=AsyncReadBufferCallback()) final
asynchronously read n bytes and deliver them to the callback
void AsyncRead (net::Connection &c, uint32_t seq, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &done_cb) final
asynchronously read the full ByteBlock and deliver it to the callback
void AsyncWrite (net::Connection &c, uint32_t seq, Buffer &&buffer, const AsyncWriteCallback &done_cb=AsyncWriteCallback()) final
void AsyncWrite (net::Connection &c, uint32_t seq, data::PinnedBlock &&block, const AsyncWriteCallback &done_cb=AsyncWriteCallback()) final
void Cancel (net::Connection &c) final
Cancel all callbacks on a given peer.
void DispatchOne (const std::chrono::milliseconds &timeout) final
Run one iteration of dispatching using MPI_Iprobe().
void Interrupt () final
Interrupt does nothing.
MPI_Request IRecv (Connection &c, uint32_t seq, void *data, size_t size)
MPI_Request ISend (Connection &c, uint32_t seq, const void *data, size_t size)
void PerformAsync (MpiAsync &&a)
Issue the encapsulated request to the MPI layer.
void PumpRecvQueue (int peer)
Check recv queue and perform waiting requests.
void PumpSendQueue (int peer)
Check send queue and perform waiting requests.
void QueueAsyncRecv (net::Connection &c, MpiAsync &&a)
Enqueue and run the encapsulated result.
void QueueAsyncSend (net::Connection &c, MpiAsync &&a)
Enqueue and run the encapsulated result.
void SetExcept (net::Connection &c, const Callback &except_cb)
Register a buffered write callback and a default exception callback.
Public Member Functions inherited from Dispatcher
Dispatcher ()=default
default constructor
Dispatcher (const Dispatcher &)=delete
non-copyable: delete copy-constructor
Dispatcher & operator= (const Dispatcher &)=delete
non-copyable: delete assignment operator
void AddTimer (const std::chrono::milliseconds &timeout, const TimerCallback &cb)
Register a relative timeout callback.
void AsyncWriteCopy (Connection &c, uint32_t seq, const void *buffer, size_t size, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, uint32_t seq, const std::string &str, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void Dispatch ()
Dispatch one or more events.
void Loop ()
Loop over Dispatch() until terminate_ flag is set.
void Terminate ()
bool HasAsyncWrites () const
Check whether there are still AsyncWrite()s in the queue.
Static Private Member Functions
static bool DefaultExceptionCallback ()
Default exception handler.
Private Attributes
std::vector< MpiAsync > mpi_async_
std::vector< int > mpi_async_out_
array of output integer of finished requests for MPI_Testsome().
std::vector< MPI_Request > mpi_async_requests_
array of current async MPI_Request for MPI_Testsome().
std::vector< MPI_Status > mpi_status_out_
array of output MPI_Status of finished requests for MPI_Testsome().
std::vector< size_t > recv_active_
number of active requests
std::deque< std::deque
< MpiAsync > > recv_queue_
queue of delayed requests for each peer
std::vector< size_t > send_active_
number of active requests
std::deque< std::deque
< MpiAsync > > send_queue_
queue of delayed requests for each peer
std::vector< Watch > watch_
callback watch vector
size_t watch_active_ { 0 }
counter of active watches
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Protected Types inherited from Dispatcher
using TimerPQ = std::priority_queue< Timer, std::vector< Timer, mem::GPoolAllocator< Timer > > >
priority queue of timer callbacks
Static Protected Member Functions inherited from Dispatcher
static bool ExceptionCallback (Connection &c)
Default exception handler.
Protected Attributes inherited from Dispatcher
std::deque< AsyncReadBuffer,
mem::GPoolAllocator
< AsyncReadBuffer > > async_read_
deque of asynchronous readers
std::deque< AsyncReadByteBlock,
mem::GPoolAllocator
< AsyncReadByteBlock > > async_read_block_
deque of asynchronous readers
std::deque< AsyncWriteBuffer,
mem::GPoolAllocator
< AsyncWriteBuffer > > async_write_
deque of asynchronous writers
std::deque< AsyncWriteBlock,
mem::GPoolAllocator
< AsyncWriteBlock > > async_write_block_
deque of asynchronous writers
std::atomic< bool > terminate_ { false }
true if dispatcher needs to stop
TimerPQ timer_pq_
Member Typedef Documentation
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Definition at line 87 of file dispatcher.hpp.
Constructor & Destructor Documentation
Dispatcher (size_t group_size)
constructor
Definition at line 32 of file dispatcher.cpp.
References Dispatcher::recv_active_, Dispatcher::recv_queue_, Dispatcher::send_active_, Dispatcher::send_queue_, and Dispatcher::watch_.
~Dispatcher () virtual
destructor
Reimplemented from Dispatcher.
Definition at line 44 of file dispatcher.cpp.
References thrill::net::mpi::g_mutex, LOG, LOG1, Dispatcher::mpi_async_, and Dispatcher::mpi_async_requests_.
Member Function Documentation
void AddAsyncRequest (const MPI_Request & req, const AsyncRequestCallback & callback)
Definition at line 105 of file dispatcher.cpp.
References LOG, Dispatcher::mpi_async_, Dispatcher::mpi_async_out_, Dispatcher::mpi_async_requests_, and Dispatcher::mpi_status_out_.
Referenced by Group::Barrier(), and Group::WaitForRequest().
void AddRead (net::Connection & c, const Callback & read_cb) inline final virtual
Register a buffered read callback and a default exception callback.
Implements Dispatcher.
Definition at line 96 of file dispatcher.hpp.
References Connection::peer(), Dispatcher::watch_, and Dispatcher::watch_active_.
void AddWrite (net::Connection & , const Callback &) inline final virtual
Register a buffered write callback and a default exception callback.
Implements Dispatcher.
Definition at line 107 of file dispatcher.hpp.
void AsyncRead (net::Connection & c, uint32_t , size_t size, const AsyncReadBufferCallback & done_cb = AsyncReadBufferCallback()) inline final virtual
asynchronously read n bytes and deliver them to the callback
Reimplemented from Dispatcher.
Definition at line 175 of file dispatcher.hpp.
References Connection::IsValid(), and Dispatcher::QueueAsyncRecv().
void AsyncRead (net::Connection & c, uint32_t , size_t size, data::PinnedByteBlockPtr && block, const AsyncReadByteBlockCallback & done_cb) inline final virtual
asynchronously read the full ByteBlock and deliver it to the callback
Reimplemented from Dispatcher.
Definition at line 188 of file dispatcher.hpp.
References Connection::IsValid(), and Dispatcher::QueueAsyncRecv().
void AsyncWrite (net::Connection & c, uint32_t , Buffer && buffer, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline final virtual
asynchronously write buffer and callback when delivered. The buffer is MOVED into the async writer.
Reimplemented from Dispatcher.
Definition at line 149 of file dispatcher.hpp.
References Connection::IsValid(), and Dispatcher::QueueAsyncSend().
void AsyncWrite (net::Connection & c, uint32_t , data::PinnedBlock && block, const AsyncWriteCallback & done_cb = AsyncWriteCallback()) inline final virtual
asynchronously write buffer and callback when delivered. The buffer is MOVED into the async writer.
Reimplemented from Dispatcher.
Definition at line 162 of file dispatcher.hpp.
References Connection::IsValid(), and Dispatcher::QueueAsyncSend().
void Cancel (net::Connection & c) inline final virtual
Cancel all callbacks on a given peer.
Implements Dispatcher.
Definition at line 124 of file dispatcher.hpp.
References Dispatcher::Watch::active, Dispatcher::Watch::except_cb, LOG, Connection::peer(), Dispatcher::Watch::read_cb, Dispatcher::watch_, and Dispatcher::watch_active_.
static bool DefaultExceptionCallback () inline static private
Default exception handler.
Definition at line 242 of file dispatcher.hpp.
void DispatchOne (const std::chrono::milliseconds & timeout) final virtual
Run one iteration of dispatching using MPI_Iprobe().
Implements Dispatcher.
Definition at line 265 of file dispatcher.cpp.
References Dispatcher::MpiAsync::connection(), die_unless, thrill::net::mpi::g_mutex, LOG, Dispatcher::mpi_async_, Dispatcher::mpi_async_out_, Dispatcher::mpi_async_requests_, Dispatcher::mpi_status_out_, Connection::peer(), Dispatcher::PumpRecvQueue(), Dispatcher::PumpSendQueue(), Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::recv_active_, Dispatcher::send_active_, sLOG, sLOG0, Dispatcher::MpiAsync::type_, Dispatcher::watch_, Dispatcher::watch_active_, Dispatcher::MpiAsync::WRITE_BLOCK, and Dispatcher::MpiAsync::WRITE_BUFFER.
void Interrupt () inline final virtual
Interrupt does nothing.
Implements Dispatcher.
Definition at line 221 of file dispatcher.hpp.
MPI_Request IRecv (Connection & c, uint32_t seq, void * data, size_t size)
Definition at line 83 of file dispatcher.cpp.
References thrill::net::mpi::g_mutex, LOG, Connection::peer(), and Connection::rx_bytes_.
Referenced by Dispatcher::PerformAsync(), and Connection::SyncRecv().
MPI_Request ISend (Connection & c, uint32_t seq, const void * data, size_t size)
Definition at line 61 of file dispatcher.cpp.
References thrill::net::mpi::g_mutex, LOG, Connection::peer(), and Connection::tx_bytes_.
Referenced by Dispatcher::PerformAsync(), Connection::SyncSend(), and Connection::SyncSendRecv().
void PerformAsync (MpiAsync && a)
Issue the encapsulated request to the MPI layer.
Definition at line 190 of file dispatcher.cpp.
References AsyncReadBuffer::connection(), AsyncWriteBuffer::connection(), AsyncReadByteBlock::connection(), AsyncWriteBlock::connection(), AsyncReadBuffer::data(), AsyncWriteBuffer::data(), AsyncReadByteBlock::data(), AsyncWriteBlock::data(), Dispatcher::IRecv(), Dispatcher::ISend(), Dispatcher::mpi_async_, Dispatcher::mpi_async_out_, Dispatcher::mpi_async_requests_, Dispatcher::mpi_status_out_, Connection::peer(), Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::recv_active_, Dispatcher::send_active_, AsyncReadBuffer::size(), AsyncWriteBuffer::size(), AsyncReadByteBlock::size(), AsyncWriteBlock::size(), Dispatcher::MpiAsync::WRITE_BLOCK, and Dispatcher::MpiAsync::WRITE_BUFFER.
Referenced by Dispatcher::PumpRecvQueue(), Dispatcher::PumpSendQueue(), Dispatcher::QueueAsyncRecv(), and Dispatcher::QueueAsyncSend().
void PumpRecvQueue (int peer)
Check recv queue and perform waiting requests.
Definition at line 174 of file dispatcher.cpp.
References thrill::net::mpi::g_simultaneous, LOG, Dispatcher::PerformAsync(), Dispatcher::recv_active_, Dispatcher::recv_queue_, and tlx::unused().
Referenced by Dispatcher::DispatchOne().
void PumpSendQueue (int peer)
Check send queue and perform waiting requests.
Definition at line 158 of file dispatcher.cpp.
References thrill::net::mpi::g_simultaneous, LOG, Dispatcher::PerformAsync(), Dispatcher::send_active_, Dispatcher::send_queue_, and tlx::unused().
Referenced by Dispatcher::DispatchOne().
void QueueAsyncRecv (net::Connection & c, MpiAsync && a)
Enqueue and run the encapsulated result.
Definition at line 137 of file dispatcher.cpp.
References thrill::net::mpi::g_simultaneous, Connection::peer(), Dispatcher::PerformAsync(), Dispatcher::recv_active_, Dispatcher::recv_queue_, and tlx::unused().
Referenced by Dispatcher::AsyncRead().
void QueueAsyncSend (net::Connection & c, MpiAsync && a)
Enqueue and run the encapsulated result.
Definition at line 117 of file dispatcher.cpp.
References thrill::net::mpi::g_simultaneous, Connection::peer(), Dispatcher::PerformAsync(), Dispatcher::send_active_, Dispatcher::send_queue_, and tlx::unused().
Referenced by Dispatcher::AsyncWrite().
void SetExcept (net::Connection & c, const Callback & except_cb) inline
Register a buffered write callback and a default exception callback.
Definition at line 113 of file dispatcher.hpp.
References Connection::peer(), Dispatcher::watch_, and Dispatcher::watch_active_.
Member Data Documentation
constexpr bool debug = false static private
Definition at line 81 of file dispatcher.hpp.
std::vector<MpiAsync> mpi_async_ private
array of asynchronous writers and readers (these have to align with mpi_async_requests_)
Definition at line 415 of file dispatcher.hpp.
Referenced by Dispatcher::AddAsyncRequest(), Dispatcher::DispatchOne(), Dispatcher::PerformAsync(), and Dispatcher::~Dispatcher().
std::vector<int> mpi_async_out_ private
array of output integer of finished requests for MPI_Testsome().
Definition at line 421 of file dispatcher.hpp.
Referenced by Dispatcher::AddAsyncRequest(), Dispatcher::DispatchOne(), and Dispatcher::PerformAsync().
std::vector<MPI_Request> mpi_async_requests_ private
array of current async MPI_Request for MPI_Testsome().
Definition at line 418 of file dispatcher.hpp.
Referenced by Dispatcher::AddAsyncRequest(), Dispatcher::DispatchOne(), Dispatcher::PerformAsync(), and Dispatcher::~Dispatcher().
std::vector<MPI_Status> mpi_status_out_ private
array of output MPI_Status of finished requests for MPI_Testsome().
Definition at line 424 of file dispatcher.hpp.
Referenced by Dispatcher::AddAsyncRequest(), Dispatcher::DispatchOne(), and Dispatcher::PerformAsync().
std::vector<size_t> recv_active_ private
number of active requests
Definition at line 437 of file dispatcher.hpp.
Referenced by Dispatcher::Dispatcher(), Dispatcher::DispatchOne(), Dispatcher::PerformAsync(), Dispatcher::PumpRecvQueue(), and Dispatcher::QueueAsyncRecv().
std::deque<std::deque<MpiAsync> > recv_queue_ private
queue of delayed requests for each peer
Definition at line 431 of file dispatcher.hpp.
Referenced by Dispatcher::Dispatcher(), Dispatcher::PumpRecvQueue(), and Dispatcher::QueueAsyncRecv().
std::vector<size_t> send_active_ private
number of active requests
Definition at line 434 of file dispatcher.hpp.
Referenced by Dispatcher::Dispatcher(), Dispatcher::DispatchOne(), Dispatcher::PerformAsync(), Dispatcher::PumpSendQueue(), and Dispatcher::QueueAsyncSend().
std::deque<std::deque<MpiAsync> > send_queue_ private
queue of delayed requests for each peer
Definition at line 428 of file dispatcher.hpp.
Referenced by Dispatcher::Dispatcher(), Dispatcher::PumpSendQueue(), and Dispatcher::QueueAsyncSend().
std::vector<Watch> watch_ private
callback watch vector
Definition at line 236 of file dispatcher.hpp.
Referenced by Dispatcher::AddRead(), Dispatcher::Cancel(), Dispatcher::Dispatcher(), Dispatcher::DispatchOne(), and Dispatcher::SetExcept().
size_t watch_active_ { 0 } private
counter of active watches
Definition at line 239 of file dispatcher.hpp.
Referenced by Dispatcher::AddRead(), Dispatcher::Cancel(), Dispatcher::DispatchOne(), and Dispatcher::SetExcept().
The documentation for this class was generated from the following files:
thrill/net/mpi/dispatcher.hpp
thrill/net/mpi/dispatcher.cpp