Thrill: GolombBitStreamReader< BlockReader > Class Template Reference
GolombBitStreamReader< BlockReader > Class Template Reference
Detailed Description
template<typename BlockReader>
class thrill::core::GolombBitStreamReader< BlockReader >
Definition at line 145 of file golomb_bit_stream.hpp.
#include <golomb_bit_stream.hpp>
Public Member Functions
GolombBitStreamReader (BlockReader &block_reader, const size_t &b)
GolombBitStreamReader (const GolombBitStreamReader &)=delete
non-copyable: delete copy-constructor
GolombBitStreamReader (GolombBitStreamReader &&)=default
move-constructor: default
size_t GetGolomb ()
bool HasNext ()
template<typename Type2 >
size_t Next ()
GolombBitStreamReader & operator= (const GolombBitStreamReader &)=delete
non-copyable: delete assignment operator
GolombBitStreamReader & operator= (GolombBitStreamReader &&)=default
move-assignment operator: default
Public Member Functions inherited from BitStreamReader< BlockReader >
BitStreamReader (BlockReader &block_reader)
BitStreamReader (const BitStreamReader &)=delete
non-copyable: delete copy-constructor
BitStreamReader (BitStreamReader &&)=default
move-constructor: default
size_t GetBits (unsigned bits)
Get bits at the cursor.
unsigned GetNumberOfOnesUntilNextZero ()
Returns the number of continuous 1 bits at the cursor, followed by a zero.
bool HasNextZeroTest ()
BitStreamReader & operator= (const BitStreamReader &)=delete
non-copyable: delete assignment operator
BitStreamReader & operator= (BitStreamReader &&)=default
move-assignment operator: default
Private Types
using Super = BitStreamReader< BlockReader >
Private Attributes
size_t b_
Golomb code parameter.
bool first_call_ = true
false, when PutGolomb_in was called already
int log2b_
ceil(log2(b_))
size_t max_little_value_
escape value
Additional Inherited Members
Protected Types inherited from BitStreamReader< BlockReader >
enum : size_t { buffer_bits_ = sizeof(size_t) * 8 }
number of bits in buffer_
enum : size_t { mask = (buffer_bits_ - 1) }
modulo mask of number of bits in buffer for pos_ counter
enum : size_t { msb_set = ((size_t)1) << (buffer_bits_ - 1) }
highest bit set
Protected Attributes inherited from BitStreamReader< BlockReader >
BlockReader & block_reader_
Input BlockReader.
size_t buffer_ = 0
current buffer of 32/64 bits
size_t pos_ = buffer_bits_
currently used number of bits
Member Typedef Documentation
using Super = BitStreamReader<BlockReader> private
Definition at line 148 of file golomb_bit_stream.hpp.
Constructor & Destructor Documentation
GolombBitStreamReader (BlockReader & block_reader, const size_t & b) inline
Definition at line 153 of file golomb_bit_stream.hpp.
GolombBitStreamReader (const GolombBitStreamReader< BlockReader > &) delete
non-copyable: delete copy-constructor
GolombBitStreamReader (GolombBitStreamReader< BlockReader > &&) default
move-constructor: default
Member Function Documentation
size_t GetGolomb () inline
Definition at line 176 of file golomb_bit_stream.hpp.
References GolombBitStreamReader< BlockReader >::b_, BitStreamReader< BlockReader >::block_reader_, GolombBitStreamReader< BlockReader >::first_call_, BitStreamReader< BlockReader >::GetBits(), BitStreamReader< BlockReader >::GetNumberOfOnesUntilNextZero(), GolombBitStreamReader< BlockReader >::log2b_, GolombBitStreamReader< BlockReader >::max_little_value_, and TLX_UNLIKELY.
Referenced by GolombBitStreamReader< BlockReader >::Next().
bool HasNext () inline
Definition at line 169 of file golomb_bit_stream.hpp.
References BitStreamReader< BlockReader >::block_reader_, GolombBitStreamReader< BlockReader >::first_call_, BitStreamReader< BlockReader >::HasNextZeroTest(), and TLX_UNLIKELY.
Referenced by LocationDetection< HashCount >::GolombPairReader::HasNext().
size_t Next () inline
Definition at line 192 of file golomb_bit_stream.hpp.
References GolombBitStreamReader< BlockReader >::GetGolomb(), and gen_data::value.
GolombBitStreamReader& operator= (const GolombBitStreamReader< BlockReader > &) delete
non-copyable: delete assignment operator
GolombBitStreamReader& operator= (GolombBitStreamReader< BlockReader > &&) default
move-assignment operator: default
Member Data Documentation
size_t b_ private
Golomb code parameter.
Definition at line 200 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb().
bool first_call_ = true private
false, when PutGolomb_in was called already
Definition at line 209 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb(), and GolombBitStreamReader< BlockReader >::HasNext().
int log2b_ private
ceil(log2(b_))
Definition at line 203 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb().
size_t max_little_value_ private
escape value
Definition at line 206 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb().
The documentation for this class was generated from the following file:
thrill/core/golomb_bit_stream.hpp