Thrill: DiskAllocator Class Reference
DiskAllocator Class Reference
Asynchronous I/O Layer
Detailed Description
Definition at line 41 of file disk_allocator.hpp.
#include <disk_allocator.hpp>
Public Member Functions
DiskAllocator (FileBase *storage, const DiskConfig &cfg)
DiskAllocator (const DiskAllocator &)=delete
non-copyable: delete copy-constructor
~DiskAllocator ()
template<size_t BlockSize>
void DeleteBlock (const BID< BlockSize > &bid)
int64_t free_bytes () const
template<size_t BlockSize>
void NewBlocks (BIDArray< BlockSize > &bids)
template<typename BidIterator >
void NewBlocks (BidIterator begin, BidIterator end)
DiskAllocator & operator= (const DiskAllocator &)=delete
non-copyable: delete assignment operator
int64_t total_bytes () const
int64_t used_bytes () const
Private Member Functions
void AddFreeRegion (int64_t block_pos, int64_t block_size)
template<typename SortSeqIterator >
void DeallocationError (int64_t block_pos, int64_t block_size, const SortSeqIterator &pred, const SortSeqIterator &succ) const
void Dump () const
void GrowFile (int64_t extend_bytes)
Private Attributes
bool autogrow_
int64_t cfg_bytes_
std::unique_ptr< Data > data_
int64_t disk_bytes_
int64_t free_bytes_
std::mutex mutex_
FileBase * storage_
Static Private Attributes
static constexpr bool debug = false
Constructor & Destructor Documentation
DiskAllocator (FileBase * storage, const DiskConfig & cfg)
Definition at line 50 of file disk_allocator.cpp.
References DiskAllocator::GrowFile(), and DiskConfig::size.
DiskAllocator (const DiskAllocator &) delete
non-copyable: delete copy-constructor
~DiskAllocator ()
Definition at line 58 of file disk_allocator.cpp.
References DiskAllocator::cfg_bytes_, DiskAllocator::disk_bytes_, FileBase::set_size(), and DiskAllocator::storage_.
Member Function Documentation
void AddFreeRegion (int64_t block_pos, int64_t block_size) private
Definition at line 235 of file disk_allocator.cpp.
References DiskAllocator::data_, DiskAllocator::DeallocationError(), DiskAllocator::free_bytes_, LOG, and THRILL_THROW2.
Referenced by DiskAllocator::DeleteBlock(), and DiskAllocator::GrowFile().
void DeallocationError (int64_t block_pos, int64_t block_size, const SortSeqIterator & pred, const SortSeqIterator & succ) const private
Definition at line 208 of file disk_allocator.cpp.
References DiskAllocator::data_, DiskAllocator::Dump(), and LOG1.
Referenced by DiskAllocator::AddFreeRegion().
template void DeleteBlock (const BID< BlockSize > & bid)
Definition at line 192 of file disk_allocator.cpp.
References DiskAllocator::AddFreeRegion(), DiskAllocator::disk_bytes_, DiskAllocator::free_bytes_, LOG, DiskAllocator::mutex_, BID< Size >::offset, and BID< Size >::size.
void Dump () const private
Definition at line 64 of file disk_allocator.cpp.
References DiskAllocator::data_, and LOG1.
Referenced by DiskAllocator::DeallocationError(), and DiskAllocator::NewBlocks().
int64_t free_bytes () const inline
Definition at line 86 of file disk_allocator.hpp.
References DiskAllocator::free_bytes_.
Referenced by BlockManager::new_blocks_int().
void GrowFile (int64_t extend_bytes) inline private
Definition at line 67 of file disk_allocator.hpp.
References DiskAllocator::AddFreeRegion(), DiskAllocator::disk_bytes_, FileBase::set_size(), and DiskAllocator::storage_.
Referenced by DiskAllocator::DiskAllocator(), and DiskAllocator::NewBlocks().
void NewBlocks (BIDArray< BlockSize > & bids) inline
Definition at line 99 of file disk_allocator.hpp.
Referenced by BlockManager::new_blocks_int(), and DiskAllocator::NewBlocks().
void NewBlocks (BidIterator begin, BidIterator end)
Definition at line 77 of file disk_allocator.cpp.
References DiskAllocator::autogrow_, DiskAllocator::data_, DiskAllocator::debug, DiskAllocator::disk_bytes_, DiskAllocator::Dump(), DiskAllocator::free_bytes_, DiskAllocator::GrowFile(), LOG, LOG1, DiskAllocator::mutex_, DiskAllocator::NewBlocks(), and THRILL_THROW.
DiskAllocator& operator= (const DiskAllocator &) delete
non-copyable: delete assignment operator
int64_t total_bytes () const inline
Definition at line 94 of file disk_allocator.hpp.
References DiskAllocator::disk_bytes_.
int64_t used_bytes () const inline
Definition at line 90 of file disk_allocator.hpp.
References DiskAllocator::disk_bytes_, and DiskAllocator::free_bytes_.
Member Data Documentation
bool autogrow_ private
Definition at line 54 of file disk_allocator.hpp.
Referenced by DiskAllocator::NewBlocks().
int64_t cfg_bytes_ private
Definition at line 52 of file disk_allocator.hpp.
Referenced by DiskAllocator::~DiskAllocator().
std::unique_ptr<Data> data_ private
Definition at line 49 of file disk_allocator.hpp.
Referenced by DiskAllocator::AddFreeRegion(), DiskAllocator::DeallocationError(), DiskAllocator::Dump(), and DiskAllocator::NewBlocks().
constexpr bool debug = false static private
Definition at line 43 of file disk_allocator.hpp.
Referenced by DiskAllocator::NewBlocks().
int64_t disk_bytes_ private
Definition at line 51 of file disk_allocator.hpp.
Referenced by DiskAllocator::DeleteBlock(), DiskAllocator::GrowFile(), DiskAllocator::NewBlocks(), DiskAllocator::total_bytes(), DiskAllocator::used_bytes(), and DiskAllocator::~DiskAllocator().
int64_t free_bytes_ private
Definition at line 50 of file disk_allocator.hpp.
Referenced by DiskAllocator::AddFreeRegion(), DiskAllocator::DeleteBlock(), DiskAllocator::free_bytes(), DiskAllocator::NewBlocks(), and DiskAllocator::used_bytes().
std::mutex mutex_ private
Definition at line 46 of file disk_allocator.hpp.
Referenced by DiskAllocator::DeleteBlock(), and DiskAllocator::NewBlocks().
FileBase* storage_ private
Definition at line 53 of file disk_allocator.hpp.
Referenced by DiskAllocator::GrowFile(), and DiskAllocator::~DiskAllocator().
The documentation for this class was generated from the following files:
thrill/io/disk_allocator.hpp
thrill/io/disk_allocator.cpp