Thrill: request Class Reference
request Class Reference
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management » I/O Primitives Layer » I/O Requests and Queues
Detailed Description
Request object encapsulating basic properties like file and offset.
Definition at line 49 of file request.hpp.
#include <request.hpp>
Public Member Functions
request (const completion_handler &on_complete, file *file, void *buffer, offset_type offset, size_type bytes, read_or_write op)
request (const request &)=delete
non-copyable: delete copy-constructor
request (request &&)=default
move-constructor: default
virtual ~request ()
request & operator= (const request &)=delete
non-copyable: delete assignment operator
request & operator= (request &&)=default
move-assignment operator: default
Accessors
file * get_file () const
void * buffer () const
offset_type offset () const
size_type bytes () const
read_or_write op () const
void check_alignment () const
std::ostream & print (std::ostream &out) const final
Dumps properties of a request.
void error_occured (const char *msg)
void error_occured (const std::string &msg)
void check_errors ()
Rises an exception if there were error with the I/O.
const char * io_type () const override
Identifies the type of I/O implementation.
void release_file_reference ()
Public Member Functions inherited from request_interface
request_interface ()=default
request_interface (const request_interface &)=delete
non-copyable: delete copy-constructor
virtual ~request_interface ()
virtual bool add_waiter (onoff_switch *sw)=0
virtual bool cancel ()=0
Cancel a request.
virtual void delete_waiter (onoff_switch *sw)=0
request_interface & operator= (const request_interface &)=delete
non-copyable: delete assignment operator
virtual bool poll ()=0
virtual void wait (bool measure_time=true)=0
Suspends calling thread until completion of the request.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Protected Member Functions
void check_nref (bool after=false)
Protected Member Functions inherited from request_interface
virtual void completed (bool canceled)=0
virtual void notify_waiters ()=0
Protected Attributes
std::unique_ptr< io_error > error_
completion_handler on_complete_
Base Parameter of an I/O Request
file * file_
file implementation to perform I/O with
void * buffer_
data buffer to transfer
offset_type offset_
offset within file
size_type bytes_
number of bytes at buffer_ to transfer
read_or_write op_
READ or WRITE.
Private Member Functions
void check_nref_failed (bool after)
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Types inherited from request_interface
using offset_type = uint64_t
type for offsets within a file
enum read_or_write { READ, WRITE }
using size_type = size_t
type for block transfer sizes
Constructor & Destructor Documentation
request() [1/3]
request (const completion_handler & on_complete, file * file, void * buffer, offset_type offset, size_type bytes, read_or_write op)
Definition at line 23 of file request.cpp.
References file::add_request_ref(), request::file_, ReferenceCounter::reference_count(), and TLX_LOG.
request() [2/3]
request (const request &) delete
non-copyable: delete copy-constructor
request() [3/3]
request (request &&) default
move-constructor: default
~request()
~request () virtual
Definition at line 35 of file request.cpp.
References ReferenceCounter::reference_count(), and TLX_LOG.
Member Function Documentation
buffer()
void* buffer () const inline
Definition at line 96 of file request.hpp.
References request::buffer_.
bytes()
size_type bytes () const inline
Definition at line 98 of file request.hpp.
References request::bytes_.
check_alignment()
void check_alignment () const
Definition at line 40 of file request.cpp.
References foxxll::BlockAlignment, request::buffer_, request::bytes_, request::offset_, and TLX_LOG1.
Referenced by request::op(), and serving_request::serving_request().
check_errors()
void check_errors () inline
Rises an exception if there were error with the I/O.
Definition at line 114 of file request.hpp.
References request::io_type(), and request::release_file_reference().
Referenced by BlockPool::OnReadComplete(), BlockPool::OnWriteComplete(), request_with_state::poll(), and request_with_state::wait().
check_nref()
void check_nref (bool after = false) inline protected
Definition at line 127 of file request.hpp.
References request::check_nref_failed(), foxxll::operator<<(), and ReferenceCounter::reference_count().
Referenced by serving_request::serve().
check_nref_failed()
void check_nref_failed (bool after) private
Definition at line 56 of file request.cpp.
References request::buffer_, request::bytes_, request::file_, file::io_type(), request::offset_, request::op_, request_interface::READ, ReferenceCounter::reference_count(), and TLX_LOG1.
Referenced by request::check_nref().
error_occured() [1/2]
void error_occured (const char * msg)
Inform the request object that an error occurred during the I/O execution.
Definition at line 80 of file request.cpp.
References request::error_.
Referenced by request::op(), and serving_request::serve().
error_occured() [2/2]
void error_occured (const std::string & msg)
Inform the request object that an error occurred during the I/O execution.
Definition at line 85 of file request.cpp.
References request::error_.
get_file()
file* get_file () const inline
Definition at line 95 of file request.hpp.
References request::file_.
io_type()
const char * io_type () const override virtual
Identifies the type of I/O implementation.
Returns
pointer to null terminated string of characters, containing the name of I/O implementation
Implements request_interface.
Reimplemented in serving_request.
Definition at line 90 of file request.cpp.
References request::file_, and file::io_type().
Referenced by request::check_errors().
offset()
offset_type offset () const inline
Definition at line 97 of file request.hpp.
References request::offset_.
op()
read_or_write op () const inline
Definition at line 99 of file request.hpp.
References request::check_alignment(), request::error_occured(), request::op_, and request::print().
operator=() [1/2]
request& operator= (const request &) delete
non-copyable: delete assignment operator
operator=() [2/2]
request& operator= (request &&) default
move-assignment operator: default
print()
std::ostream & print (std::ostream & out) const final virtual
Dumps properties of a request.
Implements request_interface.
Definition at line 70 of file request.cpp.
References request::buffer_, request::bytes_, request::file_, request::offset_, request::op_, and request_interface::READ.
Referenced by request::op(), and foxxll::operator<<().
release_file_reference()
void release_file_reference ()
Definition at line 95 of file request.cpp.
References file::delete_request_ref(), and request::file_.
Referenced by request::check_errors(), request_with_state::completed(), and BlockPool::OnReadComplete().
Member Data Documentation
buffer_
void* buffer_ protected
data buffer to transfer
Definition at line 65 of file request.hpp.
Referenced by request::buffer(), request_with_state::cancel(), request::check_alignment(), request::check_nref_failed(), request::print(), and serving_request::serve().
bytes_
size_type bytes_ protected
number of bytes at buffer_ to transfer
Definition at line 69 of file request.hpp.
Referenced by request::bytes(), request::check_alignment(), request::check_nref_failed(), request::print(), and serving_request::serve().
debug
constexpr bool debug = false static private
Definition at line 51 of file request.hpp.
error_
std::unique_ptr<io_error> error_ protected
Definition at line 56 of file request.hpp.
Referenced by request::error_occured().
file_
file* file_ protected
file implementation to perform I/O with
Definition at line 63 of file request.hpp.
Referenced by request_with_state::cancel(), request::check_nref_failed(), request::get_file(), serving_request::io_type(), request::io_type(), request::print(), request::release_file_reference(), request::request(), and serving_request::serve().
offset_
offset_type offset_ protected
offset within file
Definition at line 67 of file request.hpp.
Referenced by request_with_state::cancel(), request::check_alignment(), request::check_nref_failed(), request::offset(), request::print(), and serving_request::serve().
on_complete_
completion_handler on_complete_ protected
Definition at line 55 of file request.hpp.
Referenced by request_with_state::cancel(), and request_with_state::completed().
op_
read_or_write op_ protected
READ or WRITE.
Definition at line 71 of file request.hpp.
Referenced by request::check_nref_failed(), request::op(), request::print(), serving_request::serve(), and request_with_state::wait().
The documentation for this class was generated from the following files:
extlib/foxxll/foxxll/io/request.hpp
extlib/foxxll/foxxll/io/request.cpp