Thrill: ReferenceCount Class Reference
ReferenceCount Class Reference
Detailed Description
Provides reference counting abilities for use with CountingPtr.
Use as superclass of the actual object, this adds a reference_count value. Then either use CountingPtr as pointer to manage references and deletion, or just do normal new and delete.
Definition at line 264 of file counting_ptr.hpp.
#include <counting_ptr.hpp>
Public Member Functions
ReferenceCount () noexcept
new objects have zero reference count
ReferenceCount (const ReferenceCount &) noexcept
coping still creates a new object with zero reference count
~ReferenceCount ()
bool DecReference () const noexcept
Call whenever resetting (i.e.
void IncReference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCount & operator= (const ReferenceCount &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCount is referenced by only one CountingPtr.
Private Attributes
std::atomic< size_t > reference_count_
Constructor & Destructor Documentation
ReferenceCount () inline noexcept
new objects have zero reference count
Definition at line 273 of file counting_ptr.hpp.
ReferenceCount (const ReferenceCount &) inline noexcept
coping still creates a new object with zero reference count
Definition at line 277 of file counting_ptr.hpp.
~ReferenceCount () inline
Definition at line 284 of file counting_ptr.hpp.
References ReferenceCount::reference_count_.
Member Function Documentation
bool DecReference () const inline noexcept
Call whenever resetting (i.e.
overwriting) a pointer to the object. IMPORTANT: In case of self-assignment, call AFTER IncReference().
Returns
if the object has to be deleted (i.e. if it's reference count dropped to zero)
Definition at line 299 of file counting_ptr.hpp.
References ReferenceCount::reference_count_.
void IncReference () const inline noexcept
Call whenever setting a pointer to the object.
Definition at line 289 of file counting_ptr.hpp.
References ReferenceCount::reference_count_.
ReferenceCount& operator= (const ReferenceCount &) inline noexcept
assignment operator, leaves pointers unchanged
Definition at line 281 of file counting_ptr.hpp.
size_t reference_count () const inline noexcept
Return the number of references to this object (for debugging)
Definition at line 307 of file counting_ptr.hpp.
References ReferenceCount::reference_count_.
Referenced by Request::check_nref(), Request::check_nref_failed(), ByteBlock::Deleter::operator()(), Request::Request(), and Request::~Request().
bool unique () const inline noexcept
Test if the ReferenceCount is referenced by only one CountingPtr.
Definition at line 303 of file counting_ptr.hpp.
References ReferenceCount::reference_count_.
Member Data Documentation
std::atomic<size_t> reference_count_ mutable private
the reference count is kept mutable for CountingPtr<const Type> to change the reference count.
Definition at line 269 of file counting_ptr.hpp.
Referenced by ReferenceCount::DecReference(), ReferenceCount::IncReference(), ReferenceCount::reference_count(), ReferenceCount::unique(), and ReferenceCount::~ReferenceCount().
The documentation for this class was generated from the following file:
thrill/common/counting_ptr.hpp