Thrill: StringLcpPtr< StringSet_, LcpType_ > Class Template Reference
StringLcpPtr< StringSet_, LcpType_ > Class Template Reference
Detailed Description
template<typename StringSet_, typename LcpType_>
class tlx::sort_strings_detail::StringLcpPtr< StringSet_, LcpType_ >
Objectified string and LCP array pointer arrays.
Definition at line 93 of file string_ptr.hpp.
#include <string_ptr.hpp>
Public Types
typedef LcpType_ LcpType
typedef StringSet::String String
typedef StringSet_ StringSet
typedef StringShadowLcpPtr
< StringSet_, LcpType_ > WithShadow
objectified string and shadow pointer class
Public Member Functions
StringLcpPtr (const StringSet &ss, LcpType *lcp)
constructor specifying all attributes
const StringSet & active () const
return currently active array
WithShadow add_shadow (const StringSet &shadow) const
construct objectified string and shadow pointer class
LcpType get_lcp (size_t i) const
return LCP array value
void set_lcp (size_t i, const LcpType &v) const
set the i-th lcp to v and check its value
size_t size () const
return valid length
StringLcpPtr sub (size_t offset, size_t sub_size) const
Advance (both) pointers by given offset, return sub-array.
Static Public Attributes
static const bool with_lcp = true
if we want to save the LCPs
Protected Attributes
StringSet active_
strings (front) array
LcpType * lcp_
lcp array
Member Typedef Documentation
typedef LcpType_ LcpType
Definition at line 97 of file string_ptr.hpp.
typedef StringSet::String String
Definition at line 98 of file string_ptr.hpp.
typedef StringSet_ StringSet
Definition at line 96 of file string_ptr.hpp.
typedef StringShadowLcpPtr<StringSet_, LcpType_> WithShadow
objectified string and shadow pointer class
Definition at line 141 of file string_ptr.hpp.
Constructor & Destructor Documentation
StringLcpPtr (const StringSet & ss, LcpType * lcp) inline
constructor specifying all attributes
Definition at line 109 of file string_ptr.hpp.
Referenced by StringLcpPtr< StringSet_, LcpType_ >::sub().
Member Function Documentation
const StringSet& active () const inline
return currently active array
Definition at line 113 of file string_ptr.hpp.
References StringLcpPtr< StringSet_, LcpType_ >::active_.
StringShadowLcpPtr< StringSet_, LcpType_ > add_shadow (const StringSet & shadow) const
construct objectified string and shadow pointer class
Definition at line 319 of file string_ptr.hpp.
LcpType get_lcp (size_t i) const inline
return LCP array value
Definition at line 129 of file string_ptr.hpp.
References StringLcpPtr< StringSet_, LcpType_ >::lcp_, and StringLcpPtr< StringSet_, LcpType_ >::size().
void set_lcp (size_t i, const LcpType & v) const inline
set the i-th lcp to v and check its value
Definition at line 135 of file string_ptr.hpp.
References StringLcpPtr< StringSet_, LcpType_ >::lcp_, and StringLcpPtr< StringSet_, LcpType_ >::size().
size_t size () const inline
return valid length
Definition at line 116 of file string_ptr.hpp.
References StringLcpPtr< StringSet_, LcpType_ >::active_.
Referenced by StringLcpPtr< StringSet_, LcpType_ >::get_lcp(), StringLcpPtr< StringSet_, LcpType_ >::set_lcp(), and StringLcpPtr< StringSet_, LcpType_ >::sub().
StringLcpPtr sub (size_t offset, size_t sub_size) const inline
Advance (both) pointers by given offset, return sub-array.
Definition at line 119 of file string_ptr.hpp.
References StringLcpPtr< StringSet_, LcpType_ >::active_, StringLcpPtr< StringSet_, LcpType_ >::lcp_, StringLcpPtr< StringSet_, LcpType_ >::size(), and StringLcpPtr< StringSet_, LcpType_ >::StringLcpPtr().
Member Data Documentation
StringSet active_ protected
strings (front) array
Definition at line 102 of file string_ptr.hpp.
Referenced by StringLcpPtr< StringSet_, LcpType_ >::active(), StringLcpPtr< StringSet_, LcpType_ >::size(), and StringLcpPtr< StringSet_, LcpType_ >::sub().
LcpType* lcp_ protected
lcp array
Definition at line 105 of file string_ptr.hpp.
Referenced by StringLcpPtr< StringSet_, LcpType_ >::get_lcp(), StringLcpPtr< StringSet_, LcpType_ >::set_lcp(), and StringLcpPtr< StringSet_, LcpType_ >::sub().
const bool with_lcp = true static
if we want to save the LCPs
Definition at line 126 of file string_ptr.hpp.
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/string_ptr.hpp