Thrill: FunctionChain< Functors > Class Template Reference
FunctionChain< Functors > Class Template Reference
Meta-Template Programming
Detailed Description
template<typename... Functors>
class tlx::FunctionChain< Functors >
A FunctionChain is a chain of functors that can be folded to a single functors.
All functors within the chain receive a single input value, which is the result of all preceding functors in the chain.
The FunctionChain basically consists of a tuple that contains functors of varying types.
Template Parameters
Input_ Input to first functor functor.
Functors Types of the different functors.
Definition at line 87 of file function_chain.hpp.
#include <function_chain.hpp>
Public Member Functions
FunctionChain ()=default
default constructor: empty functor chain.
FunctionChain (const std::tuple< Functors...> &chain)
Initialize the function chain with a given tuple of functions.
auto fold () const
Build a single functor by "folding" the chain.
template<typename Functor >
auto operator& (const Functor &functor) const
Add a functor to the end of the chain.
template<typename... Input>
auto operator() (Input &&...value) const
Directly call the folded function chain with a value.
template<typename Functor >
auto push (const Functor &functor) const
Add a functor to the end of the chain.
Static Public Attributes
static constexpr bool empty = (sizeof ... (Functors) == 0)
Is true if the FunctionChain is empty.
static constexpr size_t size = sizeof ... (Functors)
Number of functors in the FunctionChain.
Private Member Functions
template<size_t... Is>
auto fold_chain (index_sequence< Is...>) const
Auxilary function for "folding" the chain.
Private Attributes
std::tuple< Functors...> chain_
Tuple of varying type that stores all functors.
Constructor & Destructor Documentation
FunctionChain () default
default constructor: empty functor chain.
FunctionChain (const std::tuple< Functors...> & chain) inline explicit
Initialize the function chain with a given tuple of functions.
Parameters
chain Tuple of functors.
Definition at line 98 of file function_chain.hpp.
Member Function Documentation
auto fold () const inline
Build a single functor by "folding" the chain.
Folding means that the chain is processed from front to back.
Returns
Single "folded" functor representing the chain.
Definition at line 135 of file function_chain.hpp.
References FunctionChain< Functors >::fold_chain().
Referenced by FunctionChain< Functors >::operator()().
auto fold_chain (index_sequence< Is...>) const inline private
Auxilary function for "folding" the chain.
This is needed to send all functors as parameters to the function that folds them together.
Returns
Single "folded" functor representing the chain.
Definition at line 164 of file function_chain.hpp.
References tlx::meta_detail::call_chain(), and FunctionChain< Functors >::chain_.
Referenced by FunctionChain< Functors >::fold().
auto operator& (const Functor & functor) const inline
Add a functor to the end of the chain.
Alias for fold().
Template Parameters
Functor Type of the functors.
Parameters
functor functor that should be added to the chain.
Returns
New chain containing the previous and new functor(s).
Definition at line 127 of file function_chain.hpp.
References FunctionChain< Functors >::push().
auto operator() (Input &&... value) const inline
Directly call the folded function chain with a value.
Definition at line 143 of file function_chain.hpp.
References FunctionChain< Functors >::fold(), and gen_data::value.
auto push (const Functor & functor) const inline
Add a functor to the end of the chain.
Template Parameters
Functor Type of the functors.
Parameters
functor functor that should be added to the chain.
Returns
New chain containing the previous and new functor(s).
Definition at line 111 of file function_chain.hpp.
References FunctionChain< Functors >::chain_.
Referenced by FunctionChain< Functors >::operator&().
Member Data Documentation
std::tuple<Functors...> chain_ private
Tuple of varying type that stores all functors.
Definition at line 155 of file function_chain.hpp.
Referenced by FunctionChain< Functors >::fold_chain(), and FunctionChain< Functors >::push().
constexpr bool empty = (sizeof ... (Functors) == 0) static
Is true if the FunctionChain is empty.
Definition at line 148 of file function_chain.hpp.
constexpr size_t size = sizeof ... (Functors) static
Number of functors in the FunctionChain.
Definition at line 151 of file function_chain.hpp.
The documentation for this class was generated from the following file:
extlib/tlx/tlx/meta/function_chain.hpp