Thrill: JsonLogger Class Reference
JsonLogger Class Reference
Detailed Description
JsonLogger is a receiver of JSON output objects for logging.
Definition at line 69 of file json_logger.hpp.
#include <json_logger.hpp>
Public Member Functions
JsonLogger ()=default
open JsonLogger with ofstream uninitialized to discard log output.
JsonLogger (const std::string &path)
open JsonLogger with ofstream
JsonLogger (JsonLogger *super)
open JsonLogger with a super logger
template<typename... Args>
JsonLogger (JsonLogger *super, const Args &...args)
JsonLine line ()
create new JsonLine instance which will be written to this logger.
template<typename Type >
JsonLine operator<< (const Type &t)
void StartProfiler ()
launch background profiler
Public Attributes
JsonVerbatim common_
common items outputted to each line
std::mutex mutex_
mutex to lock logger output
std::ofstream os_
direct output stream for top loggers
JsonLogger * super_ = nullptr
output to superior JsonLogger
Constructor & Destructor Documentation
JsonLogger () default
open JsonLogger with ofstream uninitialized to discard log output.
JsonLogger (const std::string & path) explicit
open JsonLogger with ofstream
Definition at line 31 of file json_logger.cpp.
References die, and JsonLogger::os_.
JsonLogger (JsonLogger * super) explicit
open JsonLogger with a super logger
Definition at line 41 of file json_logger.cpp.
JsonLogger (JsonLogger * super, const Args &... args) explicit
open JsonLogger with a super logger and some additional common key:value pairs
Definition at line 416 of file json_logger.hpp.
References JsonLogger::common_, and tlx::vexpand().
Member Function Documentation
JsonLine line ()
create new JsonLine instance which will be written to this logger.
Definition at line 44 of file json_logger.cpp.
References JsonLogger::common_, JsonLogger::line(), JsonLogger::os_, JsonVerbatim::str_, and JsonLogger::super_.
Referenced by JsonLogger::line(), JsonLogger::operator<<(), and Manager::RunTask().
JsonLine operator<< (const Type & t) inline
Definition at line 429 of file json_logger.hpp.
References JsonLogger::line().
void StartProfiler ()
launch background profiler
Member Data Documentation
JsonVerbatim common_
common items outputted to each line
Definition at line 106 of file json_logger.hpp.
Referenced by JsonLogger::JsonLogger(), and JsonLogger::line().
std::mutex mutex_
mutex to lock logger output
Definition at line 103 of file json_logger.hpp.
Referenced by JsonLine::JsonLine().
std::ofstream os_
direct output stream for top loggers
Definition at line 100 of file json_logger.hpp.
Referenced by JsonLogger::JsonLogger(), and JsonLogger::line().
JsonLogger* super_ = nullptr
output to superior JsonLogger
Definition at line 97 of file json_logger.hpp.
Referenced by JsonLogger::line().
The documentation for this class was generated from the following files:
thrill/common/json_logger.hpp
thrill/common/json_logger.cpp