Thrill: Singleton< Instance, destroy_on_exit > Class Template Reference
Singleton< Instance, destroy_on_exit > Class Template Reference
Detailed Description
template<typename Instance, bool destroy_on_exit = true>
class thrill::common::Singleton< Instance, destroy_on_exit >
Definition at line 27 of file singleton.hpp.
#include <singleton.hpp>
Public Member Functions
Singleton ()=default
Singleton (const Singleton &)=delete
non-copyable: delete copy-constructor
Singleton (Singleton &&)=default
move-constructor: default
Singleton & operator= (const Singleton &)=delete
non-copyable: delete assignment operator
Singleton & operator= (Singleton &&)=default
move-assignment operator: default
Static Public Member Functions
static instance_pointer GetInstance ()
Private Types
using instance_pointer = instance_type *
using instance_type = Instance
using volatile_instance_pointer = volatile instance_pointer
Static Private Member Functions
static instance_pointer CreateInstance ()
static void DestroyInstance ()
Static Private Attributes
static volatile_instance_pointer instance_ = nullptr
Member Typedef Documentation
instance_pointer
using instance_pointer = instance_type * private
Definition at line 30 of file singleton.hpp.
instance_type
using instance_type = Instance private
Definition at line 29 of file singleton.hpp.
volatile_instance_pointer
using volatile_instance_pointer = volatile instance_pointer private
Definition at line 31 of file singleton.hpp.
Constructor & Destructor Documentation
Singleton() [1/3]
Singleton () default
Singleton() [2/3]
Singleton (const Singleton< Instance, destroy_on_exit > &) delete
non-copyable: delete copy-constructor
Singleton() [3/3]
Singleton (Singleton< Instance, destroy_on_exit > &&) default
move-constructor: default
Member Function Documentation
CreateInstance()
Singleton< Instance, destroy_on_exit >::instance_pointer CreateInstance () static private
Definition at line 60 of file singleton.hpp.
References Singleton< Instance, destroy_on_exit >::DestroyInstance(), and Singleton< Instance, destroy_on_exit >::instance_.
Referenced by Singleton< Instance, destroy_on_exit >::GetInstance().
DestroyInstance()
void DestroyInstance () static private
Definition at line 72 of file singleton.hpp.
References Singleton< Instance, destroy_on_exit >::instance_.
Referenced by Singleton< Instance, destroy_on_exit >::CreateInstance().
GetInstance()
static instance_pointer GetInstance () inline static
Definition at line 50 of file singleton.hpp.
References Singleton< Instance, destroy_on_exit >::CreateInstance(), and Singleton< Instance, destroy_on_exit >::instance_.
operator=() [1/2]
Singleton& operator= (const Singleton< Instance, destroy_on_exit > &) delete
non-copyable: delete assignment operator
operator=() [2/2]
Singleton& operator= (Singleton< Instance, destroy_on_exit > &&) default
move-assignment operator: default
Member Data Documentation
instance_
Singleton< Instance, destroy_on_exit >::volatile_instance_pointer instance_ = nullptr static private
Definition at line 33 of file singleton.hpp.
Referenced by Singleton< Instance, destroy_on_exit >::CreateInstance(), Singleton< Instance, destroy_on_exit >::DestroyInstance(), and Singleton< Instance, destroy_on_exit >::GetInstance().
The documentation for this class was generated from the following file:
thrill/common/singleton.hpp