Thrill: block_manager Class Reference
block_manager Class Reference
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management » Block Management Layer
Detailed Description
Block manager class.
Manages allocation and deallocation of blocks in multiple/single disk setting
Remarks
is a singleton
Definition at line 54 of file block_manager.hpp.
#include <block_manager.hpp>
Public Member Functions
~block_manager ()
template<size_t BlockSize>
void delete_block (const BID< BlockSize > &bid)
template<typename BIDIterator >
void delete_blocks (const BIDIterator &bid_begin, const BIDIterator &bid_end)
template<typename DiskAssignFunctor , size_t BlockSize>
void new_block (const DiskAssignFunctor &functor, BID< BlockSize > &bid, size_t alloc_offset=0)
Allocates a new block according to the strategy given by functor and stores the block identifier to bid.
template<typename DiskAssignFunctor , typename BIDIterator >
void new_blocks (const DiskAssignFunctor &functor, BIDIterator bid_begin, BIDIterator bid_end, size_t alloc_offset=0)
Allocates new blocks.
Statistics
uint64_t total_bytes () const
return total number of bytes available in all disks
uint64_t free_bytes () const
Return total number of free bytes.
uint64_t total_allocation () const
return total requested allocation in bytes
uint64_t current_allocation () const
return currently allocated bytes
uint64_t maximum_allocation () const
return maximum number of bytes allocated during program run.
Public Member Functions inherited from singleton< block_manager >
singleton ()=default
singleton (const singleton &)=delete
non-copyable: delete copy-constructor
singleton & operator= (const singleton &)=delete
non-copyable: delete assignment operator
Private Member Functions
block_manager ()
private construction from singleton
Private Attributes
tlx::simple_vector< disk_block_allocator * > block_allocators_
one block allocator per disk
uint64_t current_allocation_ = 0
currently allocated bytes
tlx::simple_vector< file_ptr > disk_files_
vector of opened disk files
uint64_t maximum_allocation_ = 0
maximum number of bytes allocated during program run.
std::mutex mutex_
protect internal data structures
size_t ndisks_
number of managed disks
uint64_t total_allocation_ = 0
total requested allocation in bytes
Static Private Attributes
static constexpr bool debug = false
static constexpr bool verbose_block_life_cycle = false
log creation and destruction of blocks
Additional Inherited Members
Public Types inherited from singleton< block_manager >
using instance_pointer = instance_type *
using instance_type = block_manager
using volatile_instance_pointer = volatile instance_pointer
Static Public Member Functions inherited from singleton< block_manager >
static instance_pointer create_instance ()
create instance of SubInstanceType and move into singleton
static void destroy_instance ()
destroy singleton and mark as invalid
static instance_pointer get_instance ()
return instance or create base instance if empty
static instance_type & get_ref ()
Constructor & Destructor Documentation
~block_manager()
~block_manager ()
Definition at line 86 of file block_manager.cpp.
References block_manager::block_allocators_, block_manager::disk_files_, block_manager::ndisks_, and TLX_LOG.
Referenced by block_manager::new_block().
block_manager()
block_manager () private
private construction from singleton
Definition at line 33 of file block_manager.cpp.
References block_manager::block_allocators_, config::check_initialized(), file::CREAT, foxxll::create_file(), file::DEFAULT_QUEUE, config::disk(), block_manager::disk_files_, config::disks_number(), disk_config::fileio_string(), singleton< config >::get_instance(), singleton< disk_queues >::get_instance(), block_manager::ndisks_, disk_config::path, disk_config::queue, file::RDWR, disk_config::size, and TLX_LOG1.
Member Function Documentation
current_allocation()
uint64_t current_allocation () const
return currently allocated bytes
Definition at line 127 of file block_manager.cpp.
References block_manager::current_allocation_, and block_manager::mutex_.
Referenced by block_manager::new_block().
free_bytes()
uint64_t free_bytes () const
Return total number of free bytes.
Definition at line 109 of file block_manager.cpp.
References block_manager::block_allocators_, block_manager::mutex_, and block_manager::ndisks_.
Referenced by block_manager::new_block().
maximum_allocation()
uint64_t maximum_allocation () const
return maximum number of bytes allocated during program run.
Definition at line 133 of file block_manager.cpp.
References block_manager::maximum_allocation_, and block_manager::mutex_.
Referenced by Context::Launch(), and block_manager::new_block().
new_block()
void new_block (const DiskAssignFunctor & functor, BID< BlockSize > & bid, size_t alloc_offset = 0) inline
Allocates a new block according to the strategy given by functor and stores the block identifier to bid.
Allocation will be lined up with previous partial allocations of alloc_offset blocks.
Parameters
functor object of model of allocation_strategy concept
bid BID to store the block identifier
alloc_offset advance for functor to line up partial allocations
Definition at line 91 of file block_manager.hpp.
References block_manager::current_allocation(), block_manager::delete_block(), block_manager::delete_blocks(), block_manager::free_bytes(), block_manager::maximum_allocation(), block_manager::new_blocks(), block_manager::total_allocation(), block_manager::total_bytes(), and block_manager::~block_manager().
Referenced by swappable_block< ValueType, BlockSize >::get_external_block().
total_allocation()
uint64_t total_allocation () const
return total requested allocation in bytes
Definition at line 121 of file block_manager.cpp.
References block_manager::mutex_, and block_manager::total_allocation_.
Referenced by block_manager::new_block().
total_bytes()
uint64_t total_bytes () const
return total number of bytes available in all disks
Definition at line 97 of file block_manager.cpp.
References block_manager::block_allocators_, block_manager::mutex_, and block_manager::ndisks_.
Referenced by block_manager::new_block().
Member Data Documentation
block_allocators_
tlx::simple_vector<disk_block_allocator*> block_allocators_ private
one block allocator per disk
Definition at line 143 of file block_manager.hpp.
Referenced by block_manager::block_manager(), block_manager::delete_block(), block_manager::free_bytes(), block_manager::new_blocks(), block_manager::total_bytes(), and block_manager::~block_manager().
current_allocation_
uint64_t current_allocation_ = 0 private
currently allocated bytes
Definition at line 149 of file block_manager.hpp.
Referenced by block_manager::current_allocation(), block_manager::delete_block(), and block_manager::new_blocks().
debug
constexpr bool debug = false static private
Definition at line 56 of file block_manager.hpp.
disk_files_
tlx::simple_vector<file_ptr> disk_files_ private
vector of opened disk files
Definition at line 140 of file block_manager.hpp.
Referenced by block_manager::block_manager(), block_manager::delete_block(), block_manager::new_blocks(), and block_manager::~block_manager().
maximum_allocation_
uint64_t maximum_allocation_ = 0 private
maximum number of bytes allocated during program run.
Definition at line 152 of file block_manager.hpp.
Referenced by block_manager::maximum_allocation(), and block_manager::new_blocks().
mutex_
std::mutex mutex_ mutable private
protect internal data structures
Definition at line 158 of file block_manager.hpp.
Referenced by block_manager::current_allocation(), block_manager::delete_block(), block_manager::free_bytes(), block_manager::maximum_allocation(), block_manager::new_blocks(), block_manager::total_allocation(), and block_manager::total_bytes().
ndisks_
size_t ndisks_ private
number of managed disks
Definition at line 137 of file block_manager.hpp.
Referenced by block_manager::block_manager(), block_manager::free_bytes(), block_manager::new_blocks(), block_manager::total_bytes(), and block_manager::~block_manager().
total_allocation_
uint64_t total_allocation_ = 0 private
total requested allocation in bytes
Definition at line 146 of file block_manager.hpp.
Referenced by block_manager::new_blocks(), and block_manager::total_allocation().
verbose_block_life_cycle
constexpr bool verbose_block_life_cycle = false static private
log creation and destruction of blocks
Definition at line 161 of file block_manager.hpp.
Referenced by block_manager::delete_block(), and block_manager::new_blocks().
The documentation for this class was generated from the following files:
extlib/foxxll/foxxll/mng/block_manager.hpp
extlib/foxxll/foxxll/mng/block_manager.cpp