Thrill: HyperLogLogRegisters< p > Class Template Reference
HyperLogLogRegisters< p > Class Template Reference
Detailed Description
template<size_t p>
class thrill::core::HyperLogLogRegisters< p >
Definition at line 34 of file hyperloglog.hpp.
#include <hyperloglog.hpp>
Public Member Functions
HyperLogLogRegisters ()
template<typename ValueType >
void insert (const ValueType &value)
void insert_hash (const uint64_t &hash_value)
void mergeDense (const HyperLogLogRegisters< p > &b)
void mergeSparse ()
HyperLogLogRegisters operator+ (const HyperLogLogRegisters< p > &registers2) const
double result ()
calculate count estimation result adjusted for bias
bool shouldConvertToDense ()
bool shouldMerge ()
size_t size () const
void toDense ()
Private Attributes
std::vector< HyperLogLogSparseRegister > deltaSet_
std::vector< uint8_t > entries_
HyperLogLogRegisterFormat format_
unsigned sparse_size_ = 0
std::vector< uint8_t > sparseListBuffer_
Constructor & Destructor Documentation
HyperLogLogRegisters()
HyperLogLogRegisters () inline
Definition at line 37 of file hyperloglog.hpp.
Member Function Documentation
insert()
void insert (const ValueType & value) inline
Definition at line 47 of file hyperloglog.hpp.
References tlx::siphash().
insert_hash()
void insert_hash (const uint64_t & hash_value)
Definition at line 1715 of file hyperloglog.cpp.
References tlx::clz(), thrill::core::DENSE, and thrill::core::SPARSE.
mergeDense()
void mergeDense (const HyperLogLogRegisters< p > & b)
Definition at line 1761 of file hyperloglog.cpp.
References thrill::core::DENSE, HyperLogLogRegisters< p >::entries_, max(), and HyperLogLogRegisters< p >::size().
Referenced by HyperLogLogRegisters< p >::operator+().
mergeSparse()
void mergeSparse ()
Definition at line 1745 of file hyperloglog.cpp.
References thrill::core::hyperloglog::encodeSparseList().
Referenced by HyperLogLogRegisters< p >::operator+().
operator+()
HyperLogLogRegisters< p > operator+ (const HyperLogLogRegisters< p > & regs2) const
combine two HyperloglogRegisters, switches between sparse/dense representations
Definition at line 1817 of file hyperloglog.cpp.
References HyperLogLogRegisters< p >::deltaSet_, thrill::core::DENSE, die, HyperLogLogRegisters< p >::format_, HyperLogLogRegisters< p >::mergeDense(), HyperLogLogRegisters< p >::mergeSparse(), HyperLogLogRegisters< p >::shouldConvertToDense(), thrill::core::SPARSE, HyperLogLogRegisters< p >::sparseListBuffer_, and HyperLogLogRegisters< p >::toDense().
result()
double result ()
calculate count estimation result adjusted for bias
Definition at line 1771 of file hyperloglog.cpp.
References tlx::digest_detail::H(), and thrill::core::SPARSE.
shouldConvertToDense()
bool shouldConvertToDense ()
Definition at line 1700 of file hyperloglog.cpp.
Referenced by HyperLogLogRegisters< p >::operator+().
shouldMerge()
bool shouldMerge ()
Definition at line 1708 of file hyperloglog.cpp.
size()
size_t size () const inline
Definition at line 39 of file hyperloglog.hpp.
Referenced by Serialization< Archive, core::HyperLogLogRegisters< p > >::Deserialize(), and HyperLogLogRegisters< p >::mergeDense().
toDense()
void toDense ()
Definition at line 1676 of file hyperloglog.cpp.
References thrill::core::DENSE, max(), thrill::core::SPARSE, and gen_data::value.
Referenced by HyperLogLogRegisters< p >::operator+().
Member Data Documentation
deltaSet_
std::vector<HyperLogLogSparseRegister> deltaSet_ private
Definition at line 76 of file hyperloglog.hpp.
Referenced by Serialization< Archive, core::HyperLogLogRegisters< p > >::Deserialize(), HyperLogLogRegisters< p >::operator+(), and Serialization< Archive, core::HyperLogLogRegisters< p > >::Serialize().
entries_
std::vector<uint8_t> entries_ private
Definition at line 77 of file hyperloglog.hpp.
Referenced by Serialization< Archive, core::HyperLogLogRegisters< p > >::Deserialize(), HyperLogLogRegisters< p >::mergeDense(), and Serialization< Archive, core::HyperLogLogRegisters< p > >::Serialize().
format_
HyperLogLogRegisterFormat format_ private
Definition at line 71 of file hyperloglog.hpp.
Referenced by Serialization< Archive, core::HyperLogLogRegisters< p > >::Deserialize(), HyperLogLogRegisters< p >::operator+(), and Serialization< Archive, core::HyperLogLogRegisters< p > >::Serialize().
sparse_size_
unsigned sparse_size_ = 0 private
Definition at line 70 of file hyperloglog.hpp.
sparseListBuffer_
std::vector<uint8_t> sparseListBuffer_ private
Definition at line 75 of file hyperloglog.hpp.
Referenced by Serialization< Archive, core::HyperLogLogRegisters< p > >::Deserialize(), HyperLogLogRegisters< p >::operator+(), and Serialization< Archive, core::HyperLogLogRegisters< p > >::Serialize().
The documentation for this class was generated from the following files:
thrill/core/hyperloglog.hpp
thrill/core/hyperloglog.cpp