Thrill: CSimpleGlobTempl< SOCHAR > Class Template Reference
CSimpleGlobTempl< SOCHAR > Class Template Reference
Detailed Description
template<typename SOCHAR>
class thrill::vfs::glob_local::CSimpleGlobTempl< SOCHAR >
Implementation of the SimpleGlob class.
Definition at line 550 of file simple_glob.hpp.
#include <simple_glob.hpp>
Public Member Functions
CSimpleGlobTempl (unsigned int a_uiFlags=0, int a_nReservedSlots=0)
Initialize the class.
~CSimpleGlobTempl ()
Deallocate all memory buffers.
int Add (const SOCHAR *a_pszFileSpec)
Add a new filespec to the glob.
int Add (int a_nCount, const SOCHAR *const *a_rgpszFileSpec)
Add an array of filespec to the glob.
SOCHAR * File (int n)
Return the a single file.
int FileCount () const
Return the number of files in the argv array.
SOCHAR ** Files ()
Return the full argv array.
int Init (unsigned int a_uiFlags=0, int a_nReservedSlots=0)
Initialize (or re-initialize) the class in preparation for adding new filespecs.
Private Types
enum ARG_ARRAY_TYPE { OFFSETS, POINTERS }
The argv array has it's members stored as either an offset into the string buffer, or as pointers to their string in the buffer.
Private Member Functions
CSimpleGlobTempl (const CSimpleGlobTempl &)
int AppendName (const SOCHAR *a_pszFileName, bool a_bIsDir)
Add a filename to the array if it passes all requirements.
bool GrowArgvArray (int a_nNewLen)
Grow the argv array to the required size.
bool GrowStringBuffer (size_t a_uiMinSize)
Grow the string buffer to the required size.
CSimpleGlobTempl & operator= (const CSimpleGlobTempl &)
void SetArgvArrayType (ARG_ARRAY_TYPE a_nNewType)
Change the type of data stored in the argv array.
Private Member Functions inherited from SimpleGlobBase< SOCHAR >
SimpleGlobBase ()
~SimpleGlobBase ()
void FilePrep ()
void FindDone ()
int FindFirstFileS (const char *a_pszFileSpec, unsigned int a_uiFlags)
bool FindNextFileS (char)
const char * GetFileNameS (char) const
SG_FileType GetFileTypeS (const char *a_pszPath) const
bool IsDirS (char) const
Static Private Member Functions
static int fileSortCompare (const void *a1, const void *a2)
Compare two (possible nullptr) strings.
Private Attributes
ARG_ARRAY_TYPE m_nArgArrayType
argv is indexes or pointers
int m_nArgsLen
used length
int m_nArgsSize
allocated size of array
int m_nReservedSlots
client slots in argv array
SOCHAR * m_pBuffer
argv string buffer
SOCHAR ** m_rgpArgs
argv
SOCHAR m_szPathPrefix [PATH_MAX]
wildcard path prefix
size_t m_uiBufferLen
used length of buffer
size_t m_uiBufferSize
allocated size of buffer
unsigned int m_uiFlags
Member Enumeration Documentation
enum ARG_ARRAY_TYPE private
The argv array has it's members stored as either an offset into the string buffer, or as pointers to their string in the buffer.
The offsets are used because if the string buffer is dynamically resized, all pointers into that buffer would become invalid.
Enumerator
OFFSETS
POINTERS
Definition at line 636 of file simple_glob.hpp.
Constructor & Destructor Documentation
CSimpleGlobTempl (unsigned int a_uiFlags = 0, int a_nReservedSlots = 0) explicit
Initialize the class.
Parameters
a_uiFlags Combination of SG_GLOB flags.
a_nReservedSlots Number of slots in the argv array that should be reserved. In the returned array these slots argv[0] ... argv[a_nReservedSlots-1] will be left empty for the caller to fill in.
Definition at line 671 of file simple_glob.hpp.
~CSimpleGlobTempl ()
Deallocate all memory buffers.
Definition at line 684 of file simple_glob.hpp.
References free().
CSimpleGlobTempl (const CSimpleGlobTempl< SOCHAR > &) private
Member Function Documentation
int Add (const SOCHAR * a_pszFileSpec)
Add a new filespec to the glob.
The filesystem will be immediately scanned for all matching files and directories and they will be added to the glob.
Parameters
a_pszFileSpec Filespec to add to the glob.
Returns
SG_SUCCESS Matching files were added to the glob.
SG_ERR_NOMATCH Nothing matched the pattern. To ignore this error compare return value to >= SG_SUCCESS.
SG_ERR_MEMORY Out of memory failure.
SG_ERR_FAILURE General failure.
Definition at line 715 of file simple_glob.hpp.
References SimpleGlobBase< SOCHAR >::FindDone(), MAX_PATH, thrill::vfs::glob_local::SG_ERR_NOMATCH, thrill::vfs::glob_local::SG_FILETYPE_DIR, thrill::vfs::glob_local::SG_FILETYPE_INVALID, thrill::vfs::glob_local::SG_GLOB_FULLSORT, thrill::vfs::glob_local::SG_GLOB_NOCHECK, thrill::vfs::glob_local::SG_GLOB_NOSORT, SG_PATH_CHAR, thrill::vfs::glob_local::SG_SUCCESS, SimpleGlobUtil::strchr(), SimpleGlobUtil::strcpy_s(), and SimpleGlobUtil::strrchr().
int Add (int a_nCount, const SOCHAR *const * a_rgpszFileSpec)
Add an array of filespec to the glob.
The filesystem will be immediately scanned for all matching files and directories in each filespec and they will be added to the glob.
Parameters
a_nCount Number of filespec in the array.
a_rgpszFileSpec Array of filespec to add to the glob.
Returns
SG_SUCCESS Matching files were added to the glob.
SG_ERR_NOMATCH Nothing matched the pattern. To ignore this error compare return value to >= SG_SUCCESS.
SG_ERR_MEMORY Out of memory failure.
SG_ERR_FAILURE General failure.
Definition at line 796 of file simple_glob.hpp.
References thrill::vfs::glob_local::SG_SUCCESS.
int AppendName (const SOCHAR * a_pszFileName, bool a_bIsDir) private
Add a filename to the array if it passes all requirements.
Definition at line 812 of file simple_glob.hpp.
References thrill::vfs::glob_local::SG_ERR_MEMORY, thrill::vfs::glob_local::SG_GLOB_MARK, thrill::vfs::glob_local::SG_GLOB_NODOT, thrill::vfs::glob_local::SG_GLOB_ONLYDIR, thrill::vfs::glob_local::SG_GLOB_ONLYFILE, SG_PATH_CHAR, thrill::vfs::glob_local::SG_SUCCESS, SimpleGlobUtil::strcpy_s(), and SimpleGlobUtil::strlen().
SOCHAR* File (int n) inline
Return the a single file.
Definition at line 622 of file simple_glob.hpp.
References CSimpleGlobTempl< SOCHAR >::Files(), CSimpleGlobTempl< SOCHAR >::m_nArgsLen, and SG_ASSERT.
int FileCount () const inline
Return the number of files in the argv array.
Definition at line 613 of file simple_glob.hpp.
References CSimpleGlobTempl< SOCHAR >::m_nArgsLen.
SOCHAR** Files () inline
Return the full argv array.
Definition at line 616 of file simple_glob.hpp.
References CSimpleGlobTempl< SOCHAR >::m_rgpArgs, CSimpleGlobTempl< SOCHAR >::POINTERS, and CSimpleGlobTempl< SOCHAR >::SetArgvArrayType().
Referenced by CSimpleGlobTempl< SOCHAR >::File().
int fileSortCompare (const void * a1, const void * a2) static private
Compare two (possible nullptr) strings.
Definition at line 937 of file simple_glob.hpp.
References SimpleGlobUtil::strcasecmp().
bool GrowArgvArray (int a_nNewLen) private
Grow the argv array to the required size.
Definition at line 897 of file simple_glob.hpp.
References realloc().
bool GrowStringBuffer (size_t a_uiMinSize) private
Grow the string buffer to the required size.
Definition at line 917 of file simple_glob.hpp.
References realloc().
int Init (unsigned int a_uiFlags = 0, int a_nReservedSlots = 0)
Initialize (or re-initialize) the class in preparation for adding new filespecs.
All existing files are cleared. Note that allocated memory is only deallocated at object destruction.
Parameters
a_uiFlags Combination of SG_GLOB flags.
a_nReservedSlots Number of slots in the argv array that should be reserved. In the returned array these slots argv[0] ... argv[a_nReservedSlots-1] will be left empty for the caller to fill in.
Definition at line 691 of file simple_glob.hpp.
References thrill::vfs::glob_local::SG_ERR_MEMORY, and thrill::vfs::glob_local::SG_SUCCESS.
CSimpleGlobTempl& operator= (const CSimpleGlobTempl< SOCHAR > &) private
void SetArgvArrayType (ARG_ARRAY_TYPE a_nNewType) private
Change the type of data stored in the argv array.
Definition at line 872 of file simple_glob.hpp.
References SG_ASSERT.
Referenced by CSimpleGlobTempl< SOCHAR >::Files().
Member Data Documentation
ARG_ARRAY_TYPE m_nArgArrayType private
argv is indexes or pointers
Definition at line 655 of file simple_glob.hpp.
int m_nArgsLen private
used length
Definition at line 659 of file simple_glob.hpp.
Referenced by CSimpleGlobTempl< SOCHAR >::File(), and CSimpleGlobTempl< SOCHAR >::FileCount().
int m_nArgsSize private
allocated size of array
Definition at line 658 of file simple_glob.hpp.
int m_nReservedSlots private
client slots in argv array
Definition at line 657 of file simple_glob.hpp.
SOCHAR* m_pBuffer private
argv string buffer
Definition at line 660 of file simple_glob.hpp.
SOCHAR** m_rgpArgs private
argv
Definition at line 656 of file simple_glob.hpp.
Referenced by CSimpleGlobTempl< SOCHAR >::Files().
SOCHAR m_szPathPrefix[PATH_MAX] private
wildcard path prefix
Definition at line 663 of file simple_glob.hpp.
size_t m_uiBufferLen private
used length of buffer
Definition at line 662 of file simple_glob.hpp.
size_t m_uiBufferSize private
allocated size of buffer
Definition at line 661 of file simple_glob.hpp.
unsigned int m_uiFlags private
Definition at line 654 of file simple_glob.hpp.
The documentation for this class was generated from the following file:
thrill/vfs/simple_glob.hpp