Thrill: BlockWriter< BlockSink > Class Template Reference
BlockWriter< BlockSink > Class Template Reference
Data Subsystem Layer
Detailed Description
template<typename BlockSink>
class thrill::data::BlockWriter< BlockSink >
BlockWriter contains a temporary Block object into which a) any serializable item can be stored or b) any arbitrary integral data can be appended.
It counts how many serializable items are stored and the offset of the first new item. When a Block is full it is emitted to an attached BlockSink, like a File, a ChannelSink, etc. for further delivery. The BlockWriter takes care of segmenting items when a Block is full.
Definition at line 52 of file block_writer.hpp.
#include <block_writer.hpp>
Public Member Functions
BlockWriter (BlockSink *sink, size_t max_block_size=default_block_size)
Start build (appending blocks) to a File.
BlockWriter ()=default
default constructor
BlockWriter (const BlockWriter &)=delete
non-copyable: delete copy-constructor
BlockWriter (BlockWriter &&bw) noexcept
move-constructor
~BlockWriter ()
On destruction, the last partial block is flushed.
void AppendBlocks (const std::vector< Block > &blocks)
void AppendBlocks (const std::deque< Block > &blocks)
size_t block_size () const
Returns block_size_.
void Close ()
Explicitly close the writer.
void Flush ()
Flush the current block (only really meaningful for a network sink).
bool IsValid () const
Return whether an actual BlockSink is attached.
BlockWriter & operator= (const BlockWriter &)=delete
non-copyable: delete assignment operator
BlockWriter & operator= (BlockWriter &&bw) noexcept
move-assignment
Appending (Generic) Serializable Items
TLX_ATTRIBUTE_ALWAYS_INLINE
BlockWriter & MarkItem ()
Mark beginning of an item.
template<typename T >
TLX_ATTRIBUTE_ALWAYS_INLINE
BlockWriter & Put (const T &x)
Put appends a complete item, or fails with a FullException.
template<typename T >
TLX_ATTRIBUTE_ALWAYS_INLINE
BlockWriter & PutNoSelfVerify (const T &x)
template<typename T , bool NoSelfVerify = false>
TLX_ATTRIBUTE_ALWAYS_INLINE
BlockWriter & PutSafe (const T &x)
appends a complete item, or fails safely with a FullException.
template<typename T , bool NoSelfVerify = false>
TLX_ATTRIBUTE_ALWAYS_INLINE
BlockWriter & PutUnsafe (const T &x)
appends a complete item, or aborts with a FullException.
Appending Write Functions
BlockWriter & Append (const void *data, size_t size)
Append a memory range to the block.
BlockWriter & PutByte (Byte data)
Append a single byte to the block.
BlockWriter & Append (const std::string &str)
template<typename Type >
BlockWriter & PutRaw (const Type &item)
Public Member Functions inherited from ItemWriterToolsBase< BlockWriter< BlockSink > >
BlockWriter< BlockSink > & PutString (const char *data, size_t len)
Put a string by saving it's length followed by the data itself.
BlockWriter< BlockSink > & PutString (const uint8_t *data, size_t len)
Put a string by saving it's length followed by the data itself.
BlockWriter< BlockSink > & PutString (const std::string &str)
Put a string by saving it's length followed by the data itself.
BlockWriter< BlockSink > & PutVarint (uint64_t v)
Append a varint to the writer.
BlockWriter< BlockSink > & PutVarint32 (uint32_t v)
Append a varint to the writer.
Static Public Attributes
static constexpr bool debug = false
static constexpr bool self_verify = common::g_self_verify
Private Member Functions
void AllocateBlock ()
Allocate a new block (overwriting the existing one).
Private Attributes
size_t block_size_
size of data blocks to construct
PinnedByteBlockPtr bytes_
bool closed_ = false
Flag if Close was called explicitly.
Byte * current_ = nullptr
current write pointer into block.
bool do_queue_ = false
boolean whether to queue blocks
Byte * end_ = nullptr
size_t first_offset_ = 0
offset of first item
size_t max_block_size_
size of data blocks to construct
size_t nitems_ = 0
number of items in current block
BlockSink * sink_ = nullptr
file or stream sink to output blocks to.
std::deque< PinnedBlock > sink_queue_
queue of blocks to flush when the current item has fully been serialized
Constructor & Destructor Documentation
BlockWriter (BlockSink * sink, size_t max_block_size = default_block_size) inline explicit
Start build (appending blocks) to a File.
Definition at line 61 of file block_writer.hpp.
References BlockWriter< BlockSink >::max_block_size_.
BlockWriter () default
default constructor
BlockWriter (const BlockWriter< BlockSink > &) delete
non-copyable: delete copy-constructor
BlockWriter (BlockWriter< BlockSink > && bw) inline noexcept
move-constructor
Definition at line 79 of file block_writer.hpp.
~BlockWriter () inline
On destruction, the last partial block is flushed.
Definition at line 116 of file block_writer.hpp.
References BlockWriter< BlockSink >::Close(), and BlockWriter< BlockSink >::closed_.
Member Function Documentation
void AllocateBlock () inline private
Allocate a new block (overwriting the existing one).
Definition at line 395 of file block_writer.hpp.
References BlockSink::AllocateByteBlock(), BlockWriter< BlockSink >::block_size_, BlockWriter< BlockSink >::bytes_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::first_offset_, CountingPtr< Type, Deleter >::get(), BlockWriter< BlockSink >::max_block_size_, BlockWriter< BlockSink >::nitems_, BlockWriter< BlockSink >::sink_, and sLOG.
Referenced by BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::PutByte(), BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
BlockWriter& Append (const void * data, size_t size) inline
Append a memory range to the block.
Definition at line 330 of file block_writer.hpp.
References BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::Flush(), and TLX_UNLIKELY.
Referenced by BlockWriter< BlockSink >::Append(), and BlockWriter< BlockSink >::PutRaw().
BlockWriter& Append (const std::string & str) inline
Append to contents of a std::string, excluding the null (which isn't contained in the string size anyway).
Definition at line 367 of file block_writer.hpp.
References BlockWriter< BlockSink >::Append().
void AppendBlocks (const std::vector< Block > & blocks) inline
Directly write Blocks to the underlying BlockSink (after flushing the current one if need be).
Definition at line 166 of file block_writer.hpp.
References BlockSink::AppendBlock(), BlockWriter< BlockSink >::Flush(), and BlockWriter< BlockSink >::sink_.
void AppendBlocks (const std::deque< Block > & blocks) inline
Directly write Blocks to the underlying BlockSink (after flushing the current one if need be).
Definition at line 176 of file block_writer.hpp.
References BlockSink::AppendBlock(), BlockWriter< BlockSink >::Flush(), and BlockWriter< BlockSink >::sink_.
size_t block_size () const inline
Returns block_size_.
Definition at line 134 of file block_writer.hpp.
References BlockWriter< BlockSink >::block_size_.
void Close () inline
Explicitly close the writer.
Definition at line 122 of file block_writer.hpp.
References BlockSink::Close(), BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::Flush(), and BlockWriter< BlockSink >::sink_.
Referenced by GroupToIndexNode< ValueType, KeyExtractor, GroupFunction >::FlushVectorToFile(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::FlushVectorToFile(), MergeNode< ValueType, Comparator, kNumInputs >::StopPreOp(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StopPreOp(), and BlockWriter< BlockSink >::~BlockWriter().
void Flush () inline
Flush the current block (only really meaningful for a network sink).
Definition at line 137 of file block_writer.hpp.
References BlockSink::AppendPinnedBlock(), BlockWriter< BlockSink >::bytes_, BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::do_queue_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::first_offset_, CountingPtr< Type, Deleter >::get(), BlockWriter< BlockSink >::nitems_, BlockWriter< BlockSink >::self_verify, BlockWriter< BlockSink >::sink_, BlockWriter< BlockSink >::sink_queue_, and sLOG.
Referenced by BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::AppendBlocks(), BlockWriter< BlockSink >::Close(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::PutByte(), BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
bool IsValid () const inline
Return whether an actual BlockSink is attached.
Definition at line 131 of file block_writer.hpp.
References BlockWriter< BlockSink >::sink_.
TLX_ATTRIBUTE_ALWAYS_INLINE BlockWriter& MarkItem () inline
Mark beginning of an item.
Definition at line 189 of file block_writer.hpp.
References BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::bytes_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::first_offset_, BlockWriter< BlockSink >::Flush(), and BlockWriter< BlockSink >::nitems_.
Referenced by BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
BlockWriter& operator= (const BlockWriter< BlockSink > &) delete
non-copyable: delete assignment operator
BlockWriter& operator= (BlockWriter< BlockSink > && bw) inline noexcept
move-assignment
Definition at line 96 of file block_writer.hpp.
References BlockWriter< BlockSink >::block_size_, BlockWriter< BlockSink >::bytes_, BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::do_queue_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::first_offset_, BlockWriter< BlockSink >::max_block_size_, BlockWriter< BlockSink >::nitems_, BlockWriter< BlockSink >::sink_, and BlockWriter< BlockSink >::sink_queue_.
TLX_ATTRIBUTE_ALWAYS_INLINE BlockWriter& Put (const T & x) inline
Put appends a complete item, or fails with a FullException.
Definition at line 204 of file block_writer.hpp.
References BlockSink::allocate_can_fail_, BlockWriter< BlockSink >::closed_, and gen_data::x.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::AddEqualKeysToFile(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::AddEqualKeysToVec(), GroupToIndexNode< ValueType, KeyExtractor, GroupFunction >::FlushVectorToFile(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::FlushVectorToFile(), ZipNode< ValueType, ZipFunction, Pad, UnequalCheck, NoRebalance, kNumInputs >::RegisterParent::operator()(), ZipWindowNode< ValueType, ZipFunction_, Pad_, UnequalCheck, UseStdArray, kNumInputs_ >::RegisterParent::operator()(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2(), ReduceOldProbingHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig_, IndexFunction, KeyEqualFunction >::SpillPartition(), ReduceProbingHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig_, IndexFunction, KeyEqualFunction >::SpillPartition(), and ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::SpillPartition().
BlockWriter& PutByte (Byte data) inline
Append a single byte to the block.
Definition at line 355 of file block_writer.hpp.
References BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::Flush(), and TLX_UNLIKELY.
TLX_ATTRIBUTE_ALWAYS_INLINE BlockWriter& PutNoSelfVerify (const T & x) inline
PutNoSelfVerify appends a complete item without any self verification information, or fails with a FullException.
Definition at line 217 of file block_writer.hpp.
References BlockSink::allocate_can_fail_, BlockWriter< BlockSink >::closed_, and gen_data::x.
BlockWriter& PutRaw (const Type & item) inline
Put (append) a single item of the template type T to the buffer. Be careful with implicit type conversions!
Definition at line 374 of file block_writer.hpp.
References BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, TLX_LIKELY, and gen_data::value.
Referenced by BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
TLX_ATTRIBUTE_ALWAYS_INLINE BlockWriter& PutSafe (const T & x) inline
appends a complete item, or fails safely with a FullException.
Definition at line 229 of file block_writer.hpp.
References BlockWriter< BlockSink >::AllocateBlock(), BlockSink::AppendPinnedBlock(), BlockWriter< BlockSink >::bytes_, BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::do_queue_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::first_offset_, BlockWriter< BlockSink >::Flush(), CountingPtr< Type, Deleter >::get(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::nitems_, BlockWriter< BlockSink >::PutRaw(), BlockSink::ReleaseByteBlock(), BlockWriter< BlockSink >::self_verify, BlockWriter< BlockSink >::sink_, BlockWriter< BlockSink >::sink_queue_, and sLOG.
TLX_ATTRIBUTE_ALWAYS_INLINE BlockWriter& PutUnsafe (const T & x) inline
appends a complete item, or aborts with a FullException.
Definition at line 301 of file block_writer.hpp.
References BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::closed_, BlockWriter< BlockSink >::current_, BlockWriter< BlockSink >::end_, BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::PutRaw(), and BlockWriter< BlockSink >::self_verify.
Member Data Documentation
size_t block_size_ private
size of data blocks to construct
Definition at line 438 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::block_size(), and BlockWriter< BlockSink >::operator=().
PinnedByteBlockPtr bytes_ private
current block, already allocated as shared ptr, since we want to use make_shared.
Definition at line 413 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
bool closed_ = false private
Flag if Close was called explicitly.
Definition at line 444 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::Close(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::operator=(), BlockWriter< BlockSink >::Put(), BlockWriter< BlockSink >::PutByte(), BlockWriter< BlockSink >::PutNoSelfVerify(), BlockWriter< BlockSink >::PutRaw(), BlockWriter< BlockSink >::PutSafe(), BlockWriter< BlockSink >::PutUnsafe(), and BlockWriter< BlockSink >::~BlockWriter().
Byte* current_ = nullptr private
current write pointer into block.
Definition at line 416 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::operator=(), BlockWriter< BlockSink >::PutByte(), BlockWriter< BlockSink >::PutRaw(), BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
constexpr bool debug = false static
Definition at line 56 of file block_writer.hpp.
bool do_queue_ = false private
boolean whether to queue blocks
Definition at line 432 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
Byte* end_ = nullptr private
current end of block pointer. this is == bytes_.end(), just one indirection less.
Definition at line 420 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::Append(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::operator=(), BlockWriter< BlockSink >::PutByte(), BlockWriter< BlockSink >::PutRaw(), BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
size_t first_offset_ = 0 private
offset of first item
Definition at line 426 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
size_t max_block_size_ private
size of data blocks to construct
Definition at line 441 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::BlockWriter(), and BlockWriter< BlockSink >::operator=().
size_t nitems_ = 0 private
number of items in current block
Definition at line 423 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::MarkItem(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
constexpr bool self_verify = common::g_self_verify static
Definition at line 58 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::PutSafe(), and BlockWriter< BlockSink >::PutUnsafe().
BlockSink* sink_ = nullptr private
file or stream sink to output blocks to.
Definition at line 429 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), BlockWriter< BlockSink >::AppendBlocks(), BlockWriter< BlockSink >::Close(), BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::IsValid(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
std::deque<PinnedBlock> sink_queue_ private
queue of blocks to flush when the current item has fully been serialized
Definition at line 435 of file block_writer.hpp.
Referenced by BlockWriter< BlockSink >::Flush(), BlockWriter< BlockSink >::operator=(), and BlockWriter< BlockSink >::PutSafe().
The documentation for this class was generated from the following file:
thrill/data/block_writer.hpp