Thrill: AsyncWriteBuffer Class Reference
AsyncWriteBuffer Class Reference
Network Subsystem Layer
Detailed Description
Definition at line 179 of file dispatcher.hpp.
#include <dispatcher.hpp>
Public Member Functions
AsyncWriteBuffer (Connection &conn, Buffer &&buffer, const AsyncWriteCallback &callback)
Construct buffered writer with callback.
AsyncWriteBuffer (const AsyncWriteBuffer &)=delete
non-copyable: delete copy-constructor
AsyncWriteBuffer (AsyncWriteBuffer &&)=default
move-constructor: default
~AsyncWriteBuffer ()
Connection * connection () const
Returns conn_.
const uint8_t * data () const
underlying buffer pointer
void DoCallback ()
bool IsDone () const
bool operator() ()
Should be called when the socket is writable.
AsyncWriteBuffer & operator= (const AsyncWriteBuffer &)=delete
non-copyable: delete assignment operator
AsyncWriteBuffer & operator= (AsyncWriteBuffer &&)=default
move-assignment operator: default
size_t size () const
underlying buffer size
Private Attributes
Buffer buffer_
Send buffer (owned by this writer)
AsyncWriteCallback callback_
functional object to call once data is complete
Connection * conn_
Connection reference.
size_t write_size_ = 0
total size currently written
Constructor & Destructor Documentation
AsyncWriteBuffer (Connection & conn, Buffer && buffer, const AsyncWriteCallback & callback) inline
Construct buffered writer with callback.
Definition at line 183 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, AsyncWriteBuffer::conn_, thrill::net::debug_async, LOGC, Buffer::size(), and Connection::tx_active_.
AsyncWriteBuffer (const AsyncWriteBuffer &) delete
non-copyable: delete copy-constructor
AsyncWriteBuffer (AsyncWriteBuffer &&) default
move-constructor: default
~AsyncWriteBuffer () inline
Definition at line 203 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, thrill::net::debug_async, LOGC, and Buffer::size().
Referenced by Dispatcher::MpiAsync::~MpiAsync().
Member Function Documentation
Connection* connection () const inline
Returns conn_.
Definition at line 255 of file dispatcher.hpp.
References AsyncWriteBuffer::conn_.
Referenced by Dispatcher::MpiAsync::connection(), and Dispatcher::PerformAsync().
const uint8_t* data () const inline
underlying buffer pointer
Definition at line 258 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, and Buffer::data().
Referenced by Dispatcher::PerformAsync().
void DoCallback () inline
Definition at line 247 of file dispatcher.hpp.
References AsyncWriteBuffer::callback_, and AsyncWriteBuffer::conn_.
Referenced by Dispatcher::MpiAsync::DoCallback(), and AsyncWriteBuffer::operator()().
bool IsDone () const inline
Definition at line 245 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, Buffer::size(), and AsyncWriteBuffer::write_size_.
bool operator() () inline
Should be called when the socket is writable.
Definition at line 210 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, AsyncWriteBuffer::conn_, Buffer::data(), thrill::net::debug_async_recv, AsyncWriteBuffer::DoCallback(), LOG1, LOGC, Connection::SendOne(), Buffer::size(), Connection::tx_active_, and AsyncWriteBuffer::write_size_.
AsyncWriteBuffer& operator= (const AsyncWriteBuffer &) delete
non-copyable: delete assignment operator
AsyncWriteBuffer& operator= (AsyncWriteBuffer &&) default
move-assignment operator: default
size_t size () const inline
underlying buffer size
Definition at line 261 of file dispatcher.hpp.
References AsyncWriteBuffer::buffer_, and Buffer::size().
Referenced by Dispatcher::PerformAsync().
Member Data Documentation
Buffer buffer_ private
Send buffer (owned by this writer)
Definition at line 268 of file dispatcher.hpp.
Referenced by AsyncWriteBuffer::AsyncWriteBuffer(), AsyncWriteBuffer::data(), AsyncWriteBuffer::IsDone(), AsyncWriteBuffer::operator()(), AsyncWriteBuffer::size(), and AsyncWriteBuffer::~AsyncWriteBuffer().
AsyncWriteCallback callback_ private
functional object to call once data is complete
Definition at line 274 of file dispatcher.hpp.
Referenced by AsyncWriteBuffer::DoCallback().
Connection* conn_ private
Connection reference.
Definition at line 265 of file dispatcher.hpp.
Referenced by AsyncWriteBuffer::AsyncWriteBuffer(), AsyncWriteBuffer::connection(), AsyncWriteBuffer::DoCallback(), and AsyncWriteBuffer::operator()().
size_t write_size_ = 0 private
total size currently written
Definition at line 271 of file dispatcher.hpp.
Referenced by AsyncWriteBuffer::IsDone(), and AsyncWriteBuffer::operator()().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp