Thrill: ElementBlock< Type, Size > Class Template Reference
ElementBlock< Type, Size > Class Template Reference
Internals
Detailed Description
template<typename Type, size_t Size>
class thrill::io::mng_local::ElementBlock< Type, Size >
Contains data elements for TypedBlock , not intended for direct use.
Definition at line 70 of file typed_block.hpp.
#include <typed_block.hpp>
Public Types
enum { size = Size }
using const_iterator = const type *
using const_reference = const Type &
using iterator = pointer
using pointer = type *
using reference = Type &
using type = Type
using value_type = Type
Public Member Functions
ElementBlock ()
iterator begin ()
Returns iterator pointing to the first element.
const_iterator begin () const
Returns const_iterator pointing to the first element.
const_iterator cbegin () const
Returns const_iterator pointing to the first element.
const_iterator cend () const
Returns const_iterator pointing to the end element.
iterator end ()
Returns iterator pointing to the end element.
const_iterator end () const
Returns const_iterator pointing to the end element.
reference operator[] (size_t i)
An operator to access elements in the block.
Public Attributes
std::array< value_type, size > elem_
Array of elements of type Type.
Member Typedef Documentation
using const_iterator = const type *
Definition at line 79 of file typed_block.hpp.
using const_reference = const Type &
Definition at line 76 of file typed_block.hpp.
using iterator = pointer
Definition at line 78 of file typed_block.hpp.
using pointer = type *
Definition at line 77 of file typed_block.hpp.
using reference = Type &
Definition at line 75 of file typed_block.hpp.
using type = Type
Definition at line 73 of file typed_block.hpp.
using value_type = Type
Definition at line 74 of file typed_block.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
size
number of elements in the block
Definition at line 81 of file typed_block.hpp.
Constructor & Destructor Documentation
ElementBlock () inline
Definition at line 88 of file typed_block.hpp.
References LOG0.
Member Function Documentation
iterator begin () inline
Returns iterator pointing to the first element.
Definition at line 98 of file typed_block.hpp.
References ElementBlock< Type, Size >::elem_.
Referenced by ElementBlock< Type, Size >::cbegin().
const_iterator begin () const inline
Returns const_iterator pointing to the first element.
Definition at line 103 of file typed_block.hpp.
References ElementBlock< Type, Size >::elem_.
const_iterator cbegin () const inline
Returns const_iterator pointing to the first element.
Definition at line 108 of file typed_block.hpp.
References ElementBlock< Type, Size >::begin().
const_iterator cend () const inline
Returns const_iterator pointing to the end element.
Definition at line 123 of file typed_block.hpp.
References ElementBlock< Type, Size >::end().
iterator end () inline
Returns iterator pointing to the end element.
Definition at line 113 of file typed_block.hpp.
References ElementBlock< Type, Size >::elem_, and ElementBlock< Type, Size >::size.
Referenced by ElementBlock< Type, Size >::cend().
const_iterator end () const inline
Returns const_iterator pointing to the end element.
Definition at line 118 of file typed_block.hpp.
References ElementBlock< Type, Size >::elem_, and ElementBlock< Type, Size >::size.
reference operator[] (size_t i) inline
An operator to access elements in the block.
Definition at line 93 of file typed_block.hpp.
References ElementBlock< Type, Size >::elem_.
Member Data Documentation
std::array<value_type, size> elem_
Array of elements of type Type.
Definition at line 86 of file typed_block.hpp.
Referenced by ElementBlock< Type, Size >::begin(), ElementBlock< Type, Size >::end(), and ElementBlock< Type, Size >::operator[]().
The documentation for this class was generated from the following file:
thrill/io/typed_block.hpp