Thrill: CountingPtr< Type, Deleter > Class Template Reference
CountingPtr< Type, Deleter > Class Template Reference
Detailed Description
template<typename Type, typename Deleter = DefaultCountingPtrDeleter>
class thrill::common::CountingPtr< Type, Deleter >
High-performance smart pointer used as a wrapping reference counting pointer.
This smart pointer class requires two functions in the template type: void IncReference() and void DecReference(). These must increment and decrement a reference count inside the templated object. When initialized, the type must have reference count zero. Each new object referencing the data calls IncReference() and each destroying holder calls del_reference(). When the data object determines that it's internal count is zero, then it must destroy itself.
Accompanying the CountingPtr is a class ReferenceCount, from which reference counted classes may be derive from. The class ReferenceCount implement all methods required for reference counting.
The whole method is more similar to boost's instrusive_ptr, but also yields something resembling std::shared_ptr. However, compared to std::shared_ptr, this class only contains a single pointer, while shared_ptr contains two which are only related if constructed with std::make_shared.
Definition at line 63 of file counting_ptr.hpp.
#include <counting_ptr.hpp>
Public Types
using element_type = Type
contained type.
Public Member Functions
CountingPtr () noexcept
default constructor: contains a nullptr pointer.
CountingPtr (std::nullptr_t) noexcept
implicit construction from nullptr_t: contains a nullptr pointer.
CountingPtr (Type *ptr) noexcept
constructor from pointer: initializes new reference to ptr.
CountingPtr (const CountingPtr &other) noexcept
copy-constructor: also initializes new reference to ptr.
template<typename Down , typename = typename std::enable_if< std::is_convertible<Down*, Type*>::value, void>::type>
CountingPtr (const CountingPtr< Down, Deleter > &other) noexcept
copy-constructor: also initializes new reference to ptr.
CountingPtr (CountingPtr &&other) noexcept
move-constructor: just moves pointer, does not change reference counts.
template<typename Down , typename = typename std::enable_if< std::is_convertible<Down*, Type*>::value, void>::type>
CountingPtr (CountingPtr< Down, Deleter > &&other) noexcept
move-constructor: just moves pointer, does not change reference counts.
~CountingPtr ()
destructor: decrements reference count in ptr.
bool empty () const noexcept
test for a nullptr pointer
Type * get () const noexcept
return the enclosed pointer.
operator bool () const noexcept
cast to bool check for a nullptr pointer
bool operator!= (const CountingPtr &other) const noexcept
test inequality of only the pointer values.
bool operator!= (Type *other) const noexcept
test inequality of only the address pointed to
Type & operator* () const noexcept
return the enclosed object as reference.
Type * operator-> () const noexcept
return the enclosed pointer.
CountingPtr & operator= (const CountingPtr &other) noexcept
template<typename Down , typename = typename std::enable_if< std::is_convertible<Down*, Type*>::value, void>::type>
CountingPtr & operator= (const CountingPtr< Down, Deleter > &other) noexcept
CountingPtr & operator= (CountingPtr &&other) noexcept
move-assignment operator: move reference of other to current object.
template<typename Down , typename = typename std::enable_if< std::is_convertible<Down*, Type*>::value, void>::type>
CountingPtr & operator= (CountingPtr< Down, Deleter > &&other) noexcept
move-assignment operator: move reference of other to current object.
bool operator== (const CountingPtr &other) const noexcept
test equality of only the pointer values.
bool operator== (Type *other) const noexcept
test equality of only the address pointed to
void reset ()
release contained pointer
void swap (CountingPtr &b) noexcept
void unify ()
make and refer a copy if the original object was shared.
bool unique () const noexcept
if the object is referred by this CountingPtr only
bool valid () const noexcept
test for a non-nullptr pointer
Private Member Functions
void DecReference () noexcept
decrement reference count of current object and maybe delete it.
void IncReference () noexcept
increment reference count for current object.
void IncReference (Type *o) noexcept
increment reference count of other object.
Private Attributes
Type * ptr_
the pointer to the currently referenced object.
Member Typedef Documentation
using element_type = Type
contained type.
Definition at line 67 of file counting_ptr.hpp.
Constructor & Destructor Documentation
CountingPtr () inline noexcept
default constructor: contains a nullptr pointer.
Definition at line 91 of file counting_ptr.hpp.
CountingPtr (std::nullptr_t) inline noexcept
implicit construction from nullptr_t: contains a nullptr pointer.
Definition at line 95 of file counting_ptr.hpp.
CountingPtr (Type * ptr) inline explicit noexcept
constructor from pointer: initializes new reference to ptr.
Definition at line 99 of file counting_ptr.hpp.
CountingPtr (const CountingPtr< Type, Deleter > & other) inline noexcept
copy-constructor: also initializes new reference to ptr.
Definition at line 103 of file counting_ptr.hpp.
CountingPtr (const CountingPtr< Down, Deleter > & other) inline noexcept
copy-constructor: also initializes new reference to ptr.
Definition at line 110 of file counting_ptr.hpp.
CountingPtr (CountingPtr< Type, Deleter > && other) inline noexcept
move-constructor: just moves pointer, does not change reference counts.
Definition at line 114 of file counting_ptr.hpp.
CountingPtr (CountingPtr< Down, Deleter > && other) inline noexcept
move-constructor: just moves pointer, does not change reference counts.
Definition at line 121 of file counting_ptr.hpp.
~CountingPtr () inline
destructor: decrements reference count in ptr.
Definition at line 170 of file counting_ptr.hpp.
Member Function Documentation
void DecReference () inline private noexcept
decrement reference count of current object and maybe delete it.
Definition at line 82 of file counting_ptr.hpp.
Referenced by CountingPtr< FileBase >::operator=(), CountingPtr< FileBase >::reset(), and CountingPtr< FileBase >::~CountingPtr().
bool empty () const inline noexcept
test for a nullptr pointer
Definition at line 214 of file counting_ptr.hpp.
Referenced by RequestQueueImpl1Q::AddRequest(), RequestQueueImplQwQr::AddRequest(), and LinuxaioQueue::AddRequest().
Type* get () const inline noexcept
return the enclosed pointer.
Definition at line 186 of file counting_ptr.hpp.
Referenced by DiskQueues::AddRequest(), RequestQueueImpl1Q::AddRequest(), RequestQueueImplQwQr::AddRequest(), LinuxaioQueue::AddRequest(), BlockWriter< BlockSink >::AllocateBlock(), BlockPool::AllocateByteBlock(), LinuxaioRequest::cancel(), PinnedBlock::CopyPinnedByteBlock(), LinuxaioRequest::fill_control_block(), BlockWriter< BlockSink >::Flush(), LinuxaioQueue::HandleEvents(), ByteBlock::has_ext_file(), DIA< ValueType_, Stack_ >::IsValid(), LinuxaioRequest::LinuxaioRequest(), DiskQueues::MakeQueue(), BlockPool::MapExternalBlock(), BlockPool::OnReadComplete(), thrill::data::operator<<(), BlockPool::PinBlock(), LinuxaioQueue::PostRequests(), BlockWriter< BlockSink >::PutSafe(), RequestQueueImpl1Q::worker(), RequestQueueImplQwQr::worker(), and PinnedBlock::~PinnedBlock().
void IncReference () inline private noexcept
increment reference count for current object.
Definition at line 74 of file counting_ptr.hpp.
Referenced by CountingPtr< FileBase >::CountingPtr(), CountingPtr< FileBase >::IncReference(), and CountingPtr< FileBase >::operator=().
void IncReference (Type * o) inline private noexcept
increment reference count of other object.
Definition at line 78 of file counting_ptr.hpp.
operator bool () const inline noexcept
cast to bool check for a nullptr pointer
Definition at line 206 of file counting_ptr.hpp.
bool operator!= (const CountingPtr< Type, Deleter > & other) const inline noexcept
test inequality of only the pointer values.
Definition at line 194 of file counting_ptr.hpp.
bool operator!= (Type * other) const inline noexcept
test inequality of only the address pointed to
Definition at line 202 of file counting_ptr.hpp.
Type& operator* () const inline noexcept
return the enclosed object as reference.
Definition at line 174 of file counting_ptr.hpp.
Type* operator-> () const inline noexcept
return the enclosed pointer.
Definition at line 180 of file counting_ptr.hpp.
CountingPtr& operator= (const CountingPtr< Type, Deleter > & other) inline noexcept
copy-assignment operator: acquire reference on new one and dereference current object.
Definition at line 126 of file counting_ptr.hpp.
Referenced by PinnedByteBlockPtr::operator=().
CountingPtr& operator= (const CountingPtr< Down, Deleter > & other) inline noexcept
copy-assignment operator: acquire reference on new one and dereference current object.
Definition at line 139 of file counting_ptr.hpp.
CountingPtr& operator= (CountingPtr< Type, Deleter > && other) inline noexcept
move-assignment operator: move reference of other to current object.
Definition at line 149 of file counting_ptr.hpp.
CountingPtr& operator= (CountingPtr< Down, Deleter > && other) inline noexcept
move-assignment operator: move reference of other to current object.
Definition at line 161 of file counting_ptr.hpp.
bool operator== (const CountingPtr< Type, Deleter > & other) const inline noexcept
test equality of only the pointer values.
Definition at line 190 of file counting_ptr.hpp.
bool operator== (Type * other) const inline noexcept
test equality of only the address pointed to
Definition at line 198 of file counting_ptr.hpp.
void reset () inline
release contained pointer
Definition at line 228 of file counting_ptr.hpp.
Referenced by Request::cancel(), Request::completed(), ReduceByHashPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceNode::Emitter, VolatileKey, ReduceConfig, thrill::core::ReduceByHash, KeyEqualFunction >::Dispose(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Dispose(), BlockPool::OnReadComplete(), and PinnedBlock::Reset().
void swap (CountingPtr< Type, Deleter > & b) inline noexcept
swap enclosed object with another counting pointer (no reference counts need change)
Definition at line 235 of file counting_ptr.hpp.
void unify () inline
make and refer a copy if the original object was shared.
Definition at line 222 of file counting_ptr.hpp.
bool unique () const inline noexcept
if the object is referred by this CountingPtr only
Definition at line 218 of file counting_ptr.hpp.
bool valid () const inline noexcept
test for a non-nullptr pointer
Definition at line 210 of file counting_ptr.hpp.
Referenced by CountingPtr< FileBase >::operator bool(), PinnedByteBlockPtr::operator=(), PinnedByteBlockPtr::PinnedByteBlockPtr(), and PinnedByteBlockPtr::~PinnedByteBlockPtr().
Member Data Documentation
Type* ptr_ private
the pointer to the currently referenced object.
Definition at line 71 of file counting_ptr.hpp.
Referenced by CountingPtr< FileBase >::DecReference(), CountingPtr< FileBase >::empty(), CountingPtr< FileBase >::get(), CountingPtr< FileBase >::IncReference(), CountingPtr< FileBase >::operator!=(), CountingPtr< FileBase >::operator*(), CountingPtr< FileBase >::operator->(), CountingPtr< FileBase >::operator=(), CountingPtr< FileBase >::operator==(), CountingPtr< FileBase >::reset(), CountingPtr< FileBase >::swap(), CountingPtr< FileBase >::unify(), CountingPtr< FileBase >::unique(), and CountingPtr< FileBase >::valid().
The documentation for this class was generated from the following file:
thrill/common/counting_ptr.hpp