Thrill: ReadLinesNode Class Reference
ReadLinesNode Class Reference final
Thrill Layers » DIA API Layer
Detailed Description
A DIANode which performs a line-based Read operation.
Reads a file from the file system and delivers it as a DIA.
Definition at line 41 of file read_lines.hpp.
#include <read_lines.hpp>
Classes
class InputLineIterator
class InputLineIteratorCompressed
InputLineIterator gives you access to lines of a file.
class InputLineIteratorUncompressed
InputLineIterator gives you access to lines of a file.
Public Types
using Super = SourceNode< std::string >
Public Types inherited from SourceNode< std::string >
using Super = DIANode< std::string >
Public Types inherited from DIANode< std::string >
using Callback = tlx::delegate< void(const std::string &)>
Public Types inherited from DIABase
using DIABasePtr = tlx::CountingPtr< DIABase >
Public Member Functions
ReadLinesNode (Context &ctx, const std::vector< std::string > &globlist, bool local_storage)
Constructor for a ReadLinesNode. Sets the Context and file path.
ReadLinesNode (Context &ctx, const std::string &glob, bool local_storage)
Constructor for a ReadLinesNode. Sets the Context and file path.
void PushData (bool) final
Virtual method for pushing data. Triggers actual pushing in sub-classes.
DIAMemUse PushDataMemUse () final
Amount of RAM used by PushData()
Public Member Functions inherited from SourceNode< std::string >
SourceNode (Context &ctx, const char *label)
void Execute () override
SourceNodes generally do not Execute, they only PushData.
Public Member Functions inherited from DIANode< std::string >
DIANode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DIANode, which sets references to the parent nodes.
DIANode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DIANode, which sets references to the parent nodes.
virtual void AddChild (DIABase *node, const Callback &callback=Callback(), size_t parent_index=0)
Enables children to push their "folded" function chains to their parent.
std::vector< DIABase *> children () const override
Returns the children of this DIABase.
void PushFile (data::File &file, bool consume) const
void PushItem (const std::string &item) const
Method for derived classes to Push a single item to all children.
void RemoveAllChildren () override
void RemoveChild (DIABase *node) override
void RunPushData () override
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
virtual void DecConsumeCounter (size_t counter)
const size_t & dia_id () const
return unique id of DIANode subclass as stored by StatsNode
virtual bool ForwardDataOnly () const
virtual void IncConsumeCounter (size_t counter)
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
virtual void SetConsumeCounter (size_t counter)
DIAState state () const
virtual DIAMemUse PreOpMemUse ()
Amount of RAM used by PreOp after StartPreOp()
virtual void StartPreOp (size_t)
Virtual method for preparing start of PushData.
virtual bool OnPreOpFile (const data::File &, size_t)
virtual void StopPreOp (size_t)
Virtual method for preparing end of PushData.
virtual DIAMemUse ExecuteMemUse ()
Amount of RAM used by Execute()
virtual void Dispose ()
Virtual clear method. Triggers actual disposing in sub-classes.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Attributes
vfs::FileList filelist_
bool local_storage_
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Protected Attributes inherited from DIANode< std::string >
std::vector< Child > children_
Callback functions from the child nodes.
Protected Attributes inherited from DIABase
Context & context_
associated Context
const size_t dia_id_
DIA serial id.
const char *const label_
DOp node static label.
DIAState state_ = DIAState::NEW
State of the DIANode. State is NEW on creation.
std::vector< DIABasePtr > parents_
Parents of this DIABase.
DIAMemUse mem_limit_ = 0
size_t consume_counter_ = 1
Member Typedef Documentation
Super
using Super = SourceNode<std::string>
Definition at line 46 of file read_lines.hpp.
Constructor & Destructor Documentation
ReadLinesNode() [1/2]
ReadLinesNode (Context & ctx, const std::vector< std::string > & globlist, bool local_storage) inline
Constructor for a ReadLinesNode. Sets the Context and file path.
Definition at line 50 of file read_lines.hpp.
References die, thrill::vfs::File, ReadLinesNode::filelist_, thrill::vfs::Glob(), tlx::join(), and sLOG.
ReadLinesNode() [2/2]
ReadLinesNode (Context & ctx, const std::string & glob, bool local_storage) inline
Constructor for a ReadLinesNode. Sets the Context and file path.
Definition at line 65 of file read_lines.hpp.
Member Function Documentation
PushData()
void PushData (bool consume) inline final virtual
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Implements DIABase.
Definition at line 74 of file read_lines.hpp.
References FileList::contains_compressed, ReadLinesNode::filelist_, ReadLinesNode::InputLineIteratorUncompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::local_storage_, ReadLinesNode::InputLineIteratorUncompressed::Next(), ReadLinesNode::InputLineIteratorCompressed::Next(), and DIANode< std::string >::PushItem().
PushDataMemUse()
DIAMemUse PushDataMemUse () inline final virtual
Amount of RAM used by PushData()
Reimplemented from DIABase.
Definition at line 69 of file read_lines.hpp.
References thrill::data::default_block_size.
Member Data Documentation
debug
constexpr bool debug = false static private
Definition at line 43 of file read_lines.hpp.
filelist_
vfs::FileList filelist_ private
Definition at line 96 of file read_lines.hpp.
Referenced by ReadLinesNode::PushData(), and ReadLinesNode::ReadLinesNode().
local_storage_
bool local_storage_ private
true, if files are on a local file system, false: common global file system.
Definition at line 100 of file read_lines.hpp.
Referenced by ReadLinesNode::PushData().
The documentation for this class was generated from the following file:
thrill/api/read_lines.hpp