Thrill: CacheBlockQueueSource Class Reference
CacheBlockQueueSource Class Reference
Data Subsystem Layer
Detailed Description
A BlockSource to read Blocks from a BlockQueue using a BlockReader, and at the same time CACHE all items received.
All Blocks read from the BlockQueue are saved in the cache File. If the cache BlockQueue is initially already closed, then Blocks are read from the File instead.
Definition at line 214 of file block_queue.hpp.
#include <block_queue.hpp>
Public Member Functions
CacheBlockQueueSource (BlockQueue *queue, size_t local_worker_id)
Start reading from a BlockQueue.
CacheBlockQueueSource (const CacheBlockQueueSource &)=delete
non-copyable: delete copy-constructor
CacheBlockQueueSource (CacheBlockQueueSource &&s)
move-constructor: default
~CacheBlockQueueSource ()
Consume remaining blocks and cache them in the File.
PinnedBlock NextBlock ()
Return next block for BlockQueue, store into caching File and return it.
CacheBlockQueueSource & operator= (const CacheBlockQueueSource &)=delete
non-copyable: delete assignment operator
void Prefetch (size_t)
Private Attributes
size_t local_worker_id_
local worker id of the thread reading the BlockQueue
BlockQueue * queue_
Reference to BlockQueue.
Static Private Attributes
static constexpr bool debug = BlockQueue::debug
Constructor & Destructor Documentation
CacheBlockQueueSource (BlockQueue * queue, size_t local_worker_id) explicit
Start reading from a BlockQueue.
Definition at line 104 of file block_queue.cpp.
CacheBlockQueueSource (const CacheBlockQueueSource &) delete
non-copyable: delete copy-constructor
CacheBlockQueueSource (CacheBlockQueueSource && s)
move-constructor: default
Definition at line 108 of file block_queue.cpp.
~CacheBlockQueueSource ()
Consume remaining blocks and cache them in the File.
Definition at line 132 of file block_queue.cpp.
References PinnedBlock::IsValid(), CacheBlockQueueSource::NextBlock(), CacheBlockQueueSource::queue_, and BlockQueue::read_closed().
Member Function Documentation
PinnedBlock NextBlock ()
Return next block for BlockQueue, store into caching File and return it.
Definition at line 117 of file block_queue.cpp.
References File::AppendBlock(), BlockQueue::file_, CacheBlockQueueSource::local_worker_id_, LOG, PinnedBlock::PinWait(), BlockQueue::Pop(), CacheBlockQueueSource::queue_, and BlockQueue::read_closed().
Referenced by CacheBlockQueueSource::~CacheBlockQueueSource().
CacheBlockQueueSource& operator= (const CacheBlockQueueSource &) delete
non-copyable: delete assignment operator
void Prefetch (size_t)
Definition at line 113 of file block_queue.cpp.
Member Data Documentation
constexpr bool debug = BlockQueue::debug static private
Definition at line 216 of file block_queue.hpp.
size_t local_worker_id_ private
local worker id of the thread reading the BlockQueue
Definition at line 242 of file block_queue.hpp.
Referenced by CacheBlockQueueSource::NextBlock().
BlockQueue* queue_ private
Reference to BlockQueue.
Definition at line 239 of file block_queue.hpp.
Referenced by CacheBlockQueueSource::NextBlock(), and CacheBlockQueueSource::~CacheBlockQueueSource().
The documentation for this class was generated from the following files:
thrill/data/block_queue.hpp
thrill/data/block_queue.cpp