Thrill: WincallFile Class Reference
WincallFile Class Reference final
File I/O Implementations
Detailed Description
Implementation of file based on Windows native I/O calls.
Definition at line 44 of file wincall_file.hpp.
#include <wincall_file.hpp>
Public Member Functions
WincallFile (const std::string &filename, int mode, int queue_id=DEFAULT_QUEUE, int allocator_id=NO_ALLOCATOR, unsigned int device_id=DEFAULT_DEVICE_ID)
const char * io_type () const final
void serve (void *buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type) final
Public Member Functions inherited from WfsFileBase
~WfsFileBase ()
void close_remove () final
close and remove file
void lock () final
Locks file for reading and writing (acquires a lock in the file system).
void set_size (offset_type newsize) final
offset_type size () final
Public Member Functions inherited from FileBase
FileBase (const FileBase &)=delete
non-copyable: delete copy-constructor
FileBase (FileBase &&)=default
move-constructor: default
FileBase (unsigned int device_id=DEFAULT_DEVICE_ID)
Construct a new file, usually called by a subclass.
virtual ~FileBase ()
virtual void discard (offset_type offset, offset_type size)
unsigned int get_device_id () const
Returns the file's physical device id.
bool need_alignment () const
Returns need_alignment_.
FileBase & operator= (const FileBase &)=delete
non-copyable: delete assignment operator
FileBase & operator= (FileBase &&)=default
move-assignment operator: default
virtual void set_size (offset_type newsize)=0
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Public Member Functions inherited from DiskQueuedFile
DiskQueuedFile (int queue_id, int allocator_id)
RequestPtr aread (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
RequestPtr awrite (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
int get_allocator_id () const override
Returns the file's disk allocator number.
int get_queue_id () const override
Additional Inherited Members
Public Types inherited from FileBase
using offset_type = Request::offset_type
the offset of a request, also the size of the file
enum OpenMode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128,
REQUIRE_DIRECT = 256
}
using size_type = Request::size_type
the size of a request
Static Public Member Functions inherited from FileBase
static int unlink (const char *path)
unlink path from filesystem
static int truncate (const char *path, size_t length)
Static Public Attributes inherited from FileBase
static constexpr bool debug = false
static constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1)
static constexpr int DEFAULT_LINUXAIO_QUEUE = -2
static constexpr int DEFAULT_QUEUE = -1
static constexpr int NO_ALLOCATOR = -1
Protected Types inherited from WfsFileBase
using HANDLE = void *
Protected Member Functions inherited from WfsFileBase
WfsFileBase (const std::string &filename, int mode)
offset_type _size ()
void close ()
Protected Attributes inherited from WfsFileBase
offset_type bytes_per_sector
std::mutex fd_mutex_
HANDLE file_des_
const std::string filename
bool locked
int mode_
Protected Attributes inherited from FileBase
unsigned int device_id_
bool need_alignment_ = false
Flag whether read/write operations require alignment.
Constructor & Destructor Documentation
WincallFile (const std::string & filename, int mode, int queue_id = DEFAULT_QUEUE, int allocator_id = NO_ALLOCATOR, unsigned int device_id = DEFAULT_DEVICE_ID) inline
Constructs file object.
Parameters
filename path of file
mode open mode, see FileBase::OpenMode
queue_id disk queue identifier
allocator_id linked disk_allocator
device_id physical device identifier
Definition at line 53 of file wincall_file.hpp.
Member Function Documentation
const char * io_type () const final virtual
Identifies the type of I/O implementation.
Returns
pointer to null terminated string of characters, containing the name of I/O implementation
Reimplemented from WfsFileBase.
Definition at line 107 of file wincall_file.cpp.
Referenced by WincallFile::serve().
void serve (void * buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type) final virtual
Implements FileBase.
Definition at line 32 of file wincall_file.cpp.
References WfsFileBase::fd_mutex_, WfsFileBase::file_des_, WincallFile::io_type(), LOG1, thrill::common::max(), Request::READ, THRILL_THROW_WIN_LASTERROR, and Request::WRITE.
The documentation for this class was generated from the following files:
thrill/io/wincall_file.hpp
thrill/io/wincall_file.cpp