Thrill: ReducePostPhaseEmitter< TableItem, Value, Emitter, VolatileKey > Class Template Reference
ReducePostPhaseEmitter< TableItem, Value, Emitter, VolatileKey > Class Template Reference
Detailed Description
template<typename TableItem, typename Value, typename Emitter, bool VolatileKey>
class thrill::core::ReducePostPhaseEmitter< TableItem, Value, Emitter, VolatileKey >
Emitter implementation to plug into a reduce hash table for collecting/flushing items while reducing. Items flushed in the post-phase are passed to the next DIA node for processing.
Definition at line 216 of file reduce_functional.hpp.
#include <reduce_functional.hpp>
Public Member Functions
ReducePostPhaseEmitter (const Emitter &emit)
void Emit (const TableItem &p)
void Emit (const size_t &, const TableItem &p)
Public Attributes
Emitter emit_
Set of emitters, one per partition.
Constructor & Destructor Documentation
ReducePostPhaseEmitter()
ReducePostPhaseEmitter (const Emitter & emit) inline explicit
Definition at line 219 of file reduce_functional.hpp.
Member Function Documentation
Emit() [1/2]
void Emit (const TableItem & p) inline
output an element into a partition, template specialized for VolatileKey and non-VolatileKey types
Definition at line 224 of file reduce_functional.hpp.
Referenced by ReduceByHashPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceNode::Emitter, VolatileKey, ReduceConfig, thrill::core::ReduceByHash, KeyEqualFunction >::Flush(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Flush(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::FlushAndConsume(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::PushData(), and ReduceByHashPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceNode::Emitter, VolatileKey, ReduceConfig, thrill::core::ReduceByHash, KeyEqualFunction >::PushData().
Emit() [2/2]
void Emit (const size_t & , const TableItem & p) inline
output an element into a partition, template specialized for VolatileKey and non-VolatileKey types
Definition at line 230 of file reduce_functional.hpp.
Member Data Documentation
emit_
Emitter emit_
Set of emitters, one per partition.
Definition at line 236 of file reduce_functional.hpp.
Referenced by ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::PushData().
The documentation for this class was generated from the following file:
thrill/core/reduce_functional.hpp