Thrill: PS5SortStep Class Reference
PS5SortStep Class Reference abstract
Detailed Description
PS5SortStep Top-Level Class to Keep Track of Substeps.
Definition at line 171 of file parallel_sample_sort.hpp.
#include <parallel_sample_sort.hpp>
Public Member Functions
void substep_notify_done ()
Notify superstep that the currently substep is done.
Protected Member Functions
PS5SortStep ()
virtual ~PS5SortStep ()
void substep_add ()
Register new substep.
Private Member Functions
virtual void substep_all_done ()=0
Pure virtual function called by substep when all substeps are done.
Private Attributes
std::atomic< size_t > substep_working_
Number of substeps still running.
Constructor & Destructor Documentation
PS5SortStep () inline protected
Definition at line 181 of file parallel_sample_sort.hpp.
virtual ~PS5SortStep () inline protected virtual
Definition at line 183 of file parallel_sample_sort.hpp.
References PS5SortStep::substep_working_.
Member Function Documentation
void substep_add () inline protected
Register new substep.
Definition at line 188 of file parallel_sample_sort.hpp.
References PS5SortStep::substep_working_.
Referenced by PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work().
virtual void substep_all_done () private pure virtual
Pure virtual function called by substep when all substeps are done.
Implemented in PS5BigSortStep< Context, StringPtr >, and PS5SmallsortJob< Context, StringPtr, BktSizeType >.
Referenced by PS5SortStep::substep_notify_done().
void substep_notify_done () inline
Notify superstep that the currently substep is done.
Definition at line 194 of file parallel_sample_sort.hpp.
References PS5SortStep::substep_all_done(), and PS5SortStep::substep_working_.
Referenced by PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done(), and PS5BigSortStep< Context, StringPtr >::substep_all_done().
Member Data Documentation
std::atomic<size_t> substep_working_ private
Number of substeps still running.
Definition at line 175 of file parallel_sample_sort.hpp.
Referenced by PS5SortStep::substep_add(), PS5SortStep::substep_notify_done(), and PS5SortStep::~PS5SortStep().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/parallel_sample_sort.hpp