Thrill: ReducePrePhase< TableItem, Key, Value, KeyExtractor, ReduceFunction, VolatileKey, ReduceConfig, IndexFunction, EqualToFunction, HashFunction, true > Class Template Reference
ReducePrePhase< TableItem, Key, Value, KeyExtractor, ReduceFunction, VolatileKey, ReduceConfig, IndexFunction, EqualToFunction, HashFunction, true > Class Template Reference
Detailed Description
template<typename TableItem, typename Key, typename Value, typename KeyExtractor, typename ReduceFunction, const bool VolatileKey, typename ReduceConfig, typename IndexFunction, typename EqualToFunction, typename HashFunction>
class thrill::core::ReducePrePhase< TableItem, Key, Value, KeyExtractor, ReduceFunction, VolatileKey, ReduceConfig, IndexFunction, EqualToFunction, HashFunction, true >
Definition at line 216 of file reduce_pre_phase.hpp.
#include <reduce_pre_phase.hpp>
Public Types
using KeyValuePair = std::pair< Key, Value >
using Super = ReducePrePhase< TableItem, Key, Value, KeyExtractor, ReduceFunction, VolatileKey, ReduceConfig, IndexFunction, EqualToFunction, HashFunction, false >
Public Member Functions
ReducePrePhase (Context &ctx, size_t dia_id, size_t num_partitions, KeyExtractor key_extractor, ReduceFunction reduce_function, std::vector< data::DynBlockWriter > &emit, const ReduceConfig &config=ReduceConfig(), const IndexFunction &index_function=IndexFunction(), const EqualToFunction &equal_to_function=EqualToFunction(), const HashFunction hash_function=HashFunction())
void FlushAll ()
Flush all partitions.
void FlushPartition (size_t partition_id, bool consume, bool grow)
void Insert (const Value &v)
Public Attributes
Duplicate Detection
HashFunction hash_function_
std::vector< size_t > hashes_
Hashes of all keys.
std::vector< bool > non_duplicates_
size_t max_hash_
Modulo for all hashes in duplicate detection to reduce hash space.
size_t duplicated_elements_ = 0
size_t non_duplicate_elements_ = 0
Member Typedef Documentation
using KeyValuePair = std::pair<Key, Value>
Definition at line 241 of file reduce_pre_phase.hpp.
using Super = ReducePrePhase<TableItem, Key, Value, KeyExtractor, ReduceFunction, VolatileKey, ReduceConfig, IndexFunction, EqualToFunction, HashFunction, false>
Definition at line 240 of file reduce_pre_phase.hpp.
Constructor & Destructor Documentation
ReducePrePhase (Context & ctx, size_t dia_id, size_t num_partitions, KeyExtractor key_extractor, ReduceFunction reduce_function, std::vector< data::DynBlockWriter > & emit, const ReduceConfig & config = ReduceConfig(), const IndexFunction & index_function = IndexFunction(), const EqualToFunction & equal_to_function = EqualToFunction(), const HashFunction hash_function = HashFunction()) inline
Definition at line 243 of file reduce_pre_phase.hpp.
Member Function Documentation
void FlushAll () inline
Flush all partitions.
Definition at line 265 of file reduce_pre_phase.hpp.
References DuplicateDetection::FindNonDuplicates().
void FlushPartition (size_t partition_id, bool consume, bool grow) inline
Definition at line 277 of file reduce_pre_phase.hpp.
References BlockReader< BlockSource >::HasNext(), and BlockReader< BlockSource >::Next().
void Insert (const Value & v) inline
Definition at line 257 of file reduce_pre_phase.hpp.
Member Data Documentation
size_t duplicated_elements_ = 0
Definition at line 330 of file reduce_pre_phase.hpp.
HashFunction hash_function_
Definition at line 321 of file reduce_pre_phase.hpp.
std::vector<size_t> hashes_
Hashes of all keys.
Definition at line 323 of file reduce_pre_phase.hpp.
size_t max_hash_
Modulo for all hashes in duplicate detection to reduce hash space.
Definition at line 328 of file reduce_pre_phase.hpp.
size_t non_duplicate_elements_ = 0
Definition at line 331 of file reduce_pre_phase.hpp.
std::vector<bool> non_duplicates_
All elements occuring on more than one worker. (Elements not appearing here can be reduced locally)
Definition at line 326 of file reduce_pre_phase.hpp.
The documentation for this class was generated from the following file:
thrill/core/reduce_pre_phase.hpp