Thrill: set_switch_handler Class Reference
set_switch_handler Class Reference
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management » Block Management Layer » Block Scheduling Sublayer
Detailed Description
Definition at line 31 of file block_prefetcher.hpp.
#include <block_prefetcher.hpp>
Public Member Functions
set_switch_handler (onoff_switch &_switch, const completion_handler &on_complete)
void operator() (request *req, bool success)
Private Attributes
completion_handler on_complete_
onoff_switch & switch_
Constructor & Destructor Documentation
set_switch_handler()
set_switch_handler (onoff_switch & _switch, const completion_handler & on_complete) inline
Definition at line 37 of file block_prefetcher.hpp.
Referenced by block_prefetcher< BlockType, BidIteratorType >::block_consumed(), and block_prefetcher< BlockType, BidIteratorType >::block_prefetcher().
Member Function Documentation
operator()()
void operator() (request * req, bool success) inline
Definition at line 41 of file block_prefetcher.hpp.
References onoff_switch::on(), and set_switch_handler::on_complete_.
Member Data Documentation
on_complete_
completion_handler on_complete_ private
Definition at line 34 of file block_prefetcher.hpp.
Referenced by set_switch_handler::operator()().
switch_
onoff_switch& switch_ private
Definition at line 33 of file block_prefetcher.hpp.
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/block_prefetcher.hpp