Thrill: buf_istream_reverse< BlockType, BidIteratorType > Class Template Reference
buf_istream_reverse< BlockType, BidIteratorType > Class Template Reference
Block Scheduling Sublayer
Detailed Description
template<typename BlockType, typename BidIteratorType>
class foxxll::buf_istream_reverse< BlockType, BidIteratorType >
Buffered input stream, reading the items in the blocks in reverse order.
Reads data records from the stream of blocks in reverse order.
Remarks
Reading performed in the background, i.e. with overlapping of I/O and computation
Definition at line 37 of file buf_istream_reverse.hpp.
#include <buf_istream_reverse.hpp>
Public Types
using bid_iterator_type = BidIteratorType
using bid_vector_type = BIDArray< block_type::raw_size >
using block_type = BlockType
using reference = typename block_type::reference
using self_type = buf_istream_reverse< block_type, bid_iterator_type >
Public Member Functions
buf_istream_reverse (bid_iterator_type begin, bid_iterator_type end, size_t nbuffers)
buf_istream_reverse (const buf_istream_reverse &)=delete
non-copyable: delete copy-constructor
~buf_istream_reverse ()
Frees used internal objects.
reference current ()
Returns reference to the current record in the stream.
reference operator* ()
Returns reference to the current record in the stream.
self_type & operator++ ()
buf_istream_reverse & operator= (const buf_istream_reverse &)=delete
non-copyable: delete assignment operator
self_type & operator>> (reference record)
Protected Types
using prefetcher_type = block_prefetcher< block_type, typename bid_vector_type::iterator >
Protected Attributes
bid_vector_type bids_
block_type * current_blk
size_t current_elem
bool not_finished
size_t * prefetch_seq
prefetcher_type * prefetcher
Private Member Functions
buf_istream_reverse ()
Member Typedef Documentation
using bid_iterator_type = BidIteratorType
Definition at line 41 of file buf_istream_reverse.hpp.
using bid_vector_type = BIDArray<block_type::raw_size>
Definition at line 45 of file buf_istream_reverse.hpp.
using block_type = BlockType
Definition at line 40 of file buf_istream_reverse.hpp.
using prefetcher_type = block_prefetcher<block_type, typename bid_vector_type::iterator> protected
Definition at line 51 of file buf_istream_reverse.hpp.
using reference = typename block_type::reference
Definition at line 62 of file buf_istream_reverse.hpp.
using self_type = buf_istream_reverse<block_type, bid_iterator_type>
Definition at line 63 of file buf_istream_reverse.hpp.
Constructor & Destructor Documentation
buf_istream_reverse () inline private
Definition at line 48 of file buf_istream_reverse.hpp.
buf_istream_reverse (bid_iterator_type begin, bid_iterator_type end, size_t nbuffers) inline
Constructs input stream object, reading [first,last) blocks in reverse.
Parameters
begin bid_iterator pointing to the first block of the stream
end bid_iterator pointing to the (last + 1) block of the stream
nbuffers number of buffers for internal use
Definition at line 69 of file buf_istream_reverse.hpp.
References SimpleVector< ValueType, Mode >::begin(), buf_istream_reverse< BlockType, BidIteratorType >::bids_, foxxll::compute_prefetch_schedule(), buf_istream_reverse< BlockType, BidIteratorType >::current_blk, buf_istream_reverse< BlockType, BidIteratorType >::current_elem, config::disks_number(), SimpleVector< ValueType, Mode >::end(), singleton< config >::get_instance(), max(), config::max_device_id(), buf_istream_reverse< BlockType, BidIteratorType >::prefetch_seq, buf_istream_reverse< BlockType, BidIteratorType >::prefetcher, and SimpleVector< ValueType, Mode >::size().
buf_istream_reverse (const buf_istream_reverse< BlockType, BidIteratorType > &) delete
non-copyable: delete copy-constructor
~buf_istream_reverse () inline
Frees used internal objects.
Definition at line 172 of file buf_istream_reverse.hpp.
References buf_istream_reverse< BlockType, BidIteratorType >::prefetch_seq, and buf_istream_reverse< BlockType, BidIteratorType >::prefetcher.
Member Function Documentation
reference current () inline
Returns reference to the current record in the stream.
Definition at line 135 of file buf_istream_reverse.hpp.
References buf_istream_reverse< BlockType, BidIteratorType >::current_blk, and buf_istream_reverse< BlockType, BidIteratorType >::current_elem.
reference operator* () inline
Returns reference to the current record in the stream.
Definition at line 141 of file buf_istream_reverse.hpp.
References buf_istream_reverse< BlockType, BidIteratorType >::current_blk, and buf_istream_reverse< BlockType, BidIteratorType >::current_elem.
self_type& operator++ () inline
Moves to the previous record in the stream.
Returns
reference to itself after the advance
Definition at line 148 of file buf_istream_reverse.hpp.
References block_prefetcher< BlockType, BidIteratorType >::block_consumed(), buf_istream_reverse< BlockType, BidIteratorType >::current_blk, buf_istream_reverse< BlockType, BidIteratorType >::current_elem, buf_istream_reverse< BlockType, BidIteratorType >::not_finished, buf_istream_reverse< BlockType, BidIteratorType >::prefetcher, and UNLIKELY.
buf_istream_reverse& operator= (const buf_istream_reverse< BlockType, BidIteratorType > &) delete
non-copyable: delete assignment operator
self_type& operator>> (reference record) inline
Input stream operator, reads in record.
Parameters
record reference to the block record type, contains value of the next record in the stream after the call of the operator
Returns
reference to itself (stream object)
Definition at line 109 of file buf_istream_reverse.hpp.
References block_prefetcher< BlockType, BidIteratorType >::block_consumed(), buf_istream_reverse< BlockType, BidIteratorType >::current_blk, buf_istream_reverse< BlockType, BidIteratorType >::current_elem, buf_istream_reverse< BlockType, BidIteratorType >::not_finished, buf_istream_reverse< BlockType, BidIteratorType >::prefetcher, and UNLIKELY.
Member Data Documentation
bid_vector_type bids_ protected
Definition at line 59 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse().
block_type* current_blk protected
Definition at line 54 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), buf_istream_reverse< BlockType, BidIteratorType >::current(), buf_istream_reverse< BlockType, BidIteratorType >::operator*(), buf_istream_reverse< BlockType, BidIteratorType >::operator++(), and buf_istream_reverse< BlockType, BidIteratorType >::operator>>().
size_t current_elem protected
Definition at line 53 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), buf_istream_reverse< BlockType, BidIteratorType >::current(), buf_istream_reverse< BlockType, BidIteratorType >::operator*(), buf_istream_reverse< BlockType, BidIteratorType >::operator++(), and buf_istream_reverse< BlockType, BidIteratorType >::operator>>().
bool not_finished protected
Definition at line 57 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::operator++(), and buf_istream_reverse< BlockType, BidIteratorType >::operator>>().
size_t* prefetch_seq protected
Definition at line 55 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), and buf_istream_reverse< BlockType, BidIteratorType >::~buf_istream_reverse().
prefetcher_type* prefetcher protected
Definition at line 52 of file buf_istream_reverse.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), buf_istream_reverse< BlockType, BidIteratorType >::operator++(), buf_istream_reverse< BlockType, BidIteratorType >::operator>>(), and buf_istream_reverse< BlockType, BidIteratorType >::~buf_istream_reverse().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/buf_istream_reverse.hpp