Thrill: Range Class Reference
Range Class Reference
Detailed Description
represents a 1 dimensional range (interval) [begin,end)
Definition at line 40 of file math.hpp.
#include <math.hpp>
Public Member Functions
Range ()=default
Range (size_t begin, size_t end)
size_t CalculateBeginOfPart (size_t i, size_t parts) const
bool Contains (size_t x) const
true if the Range contains x
size_t FindPartition (size_t index, size_t parts) const
bool IsEmpty () const
range is empty (begin == end)
bool IsValid () const
valid non-empty range (begin < end)
Range operator+ (const size_t &shift) const
return shifted Range
Range Partition (size_t i, size_t parts) const
size_t size () const
size of range
void Swap ()
swap boundaries, making a valid range invalid.
Static Public Member Functions
static Range Invalid ()
Public Attributes
Attributes
size_t begin = 0
begin index
size_t end = 0
end index
Friends
std::ostream & operator<< (std::ostream &os, const Range &r)
ostream-able
Constructor & Destructor Documentation
Range () default
Referenced by Range::Invalid(), Range::operator+(), and Range::Partition().
Range (size_t begin, size_t end) inline
Definition at line 44 of file math.hpp.
Member Function Documentation
size_t CalculateBeginOfPart (size_t i, size_t parts) const inline
Definition at line 90 of file math.hpp.
References Range::begin, and Range::size().
Referenced by Range::Partition().
bool Contains (size_t x) const inline
true if the Range contains x
Definition at line 78 of file math.hpp.
References Range::begin, and Range::end.
size_t FindPartition (size_t index, size_t parts) const inline
calculate the partition (ranging from 0 to parts - 1) into which index falls
Definition at line 97 of file math.hpp.
References Range::begin, and Range::size().
Referenced by ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Insert().
static Range Invalid () inline static
Definition at line 46 of file math.hpp.
References thrill::common::max(), thrill::common::min(), and Range::Range().
bool IsEmpty () const inline
range is empty (begin == end)
Definition at line 65 of file math.hpp.
References Range::begin, and Range::end.
Referenced by ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Initialize().
bool IsValid () const inline
valid non-empty range (begin < end)
Definition at line 67 of file math.hpp.
References Range::begin, and Range::end.
Referenced by ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Initialize().
Range operator+ (const size_t & shift) const inline
return shifted Range
Definition at line 73 of file math.hpp.
References Range::begin, Range::end, and Range::Range().
Range Partition (size_t i, size_t parts) const inline
calculate a partition range [begin,end) by taking the current Range splitting it into p parts and taking the i-th one.
Definition at line 84 of file math.hpp.
References Range::CalculateBeginOfPart(), and Range::Range().
Referenced by thrill::common::CalculateLocalRange(), and ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Initialize().
size_t size () const inline
size of range
Definition at line 62 of file math.hpp.
References Range::begin, and Range::end.
Referenced by Range::CalculateBeginOfPart(), Range::FindPartition(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Initialize(), ReduceByIndex< Key >::inverse(), and ReduceByIndex< Key >::operator()().
void Swap () inline
swap boundaries, making a valid range invalid.
Definition at line 70 of file math.hpp.
References Range::begin, Range::end, and tlx::swap().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Range & r) friend
ostream-able
Definition at line 102 of file math.hpp.
Member Data Documentation
size_t begin = 0
begin index
Definition at line 55 of file math.hpp.
Referenced by Range::CalculateBeginOfPart(), Range::Contains(), DistributeNode< ValueType >::Execute(), Range::FindPartition(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Insert(), ReduceByIndex< Key >::inverse(), Range::IsEmpty(), Range::IsValid(), thrill::vfs::OpenReadStream(), ReduceByIndex< Key >::operator()(), Range::operator+(), EqualToDIANode< ValueType >::PushData(), GenerateNode< ValueType, GenerateFunction >::PushData(), ReadBinaryNode< ValueType >::ReadBinaryNode(), GroupToIndexNode< ValueType, KeyExtractor, GroupFunction >::RunUserFunc(), Range::size(), Range::Swap(), and thrill::vfs::SysOpenReadStream().
size_t end = 0
end index
Definition at line 57 of file math.hpp.
Referenced by Range::Contains(), DistributeNode< ValueType >::Execute(), ReadLinesNode::InputLineIteratorUncompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), ReduceByIndexPostPhase< TableItem, Key, ValueType, KeyExtractor, ReduceFunction, thrill::api::ReduceToIndexNode::Emitter, VolatileKey, ReduceConfig >::Insert(), Range::IsEmpty(), Range::IsValid(), Range::operator+(), EqualToDIANode< ValueType >::PushData(), GenerateNode< ValueType, GenerateFunction >::PushData(), ReadBinaryNode< ValueType >::ReadBinaryNode(), GroupToIndexNode< ValueType, KeyExtractor, GroupFunction >::RunUserFunc(), Range::size(), Range::Swap(), DuplicateDetection::WriteEncodedHashes(), and LocationDetection< thrill::api::JoinNode::HashCount >::WriteOccurenceCounts().
The documentation for this class was generated from the following file:
thrill/common/math.hpp