Thrill: StringView Class Reference
StringView Class Reference
Thrill Layers » tlx - C++ Extensions and Utilities » Containers and Data Structures
Detailed Description
StringView is a reference to a part of a string, consisting of only a char pointer and a length.
It does not have ownership of the substring and is used mainly for temporary objects.
Definition at line 32 of file string_view.hpp.
#include <string_view.hpp>
Public Types
using iterator = const char *
Public Member Functions
StringView ()=default
Default constructor for a StringView. Doesn't initialize anything.
StringView (const char *data, size_t size) noexcept
Creates a new StringView, given a const char* and the size.
StringView (const std::string::const_iterator &data, size_t size) noexcept
Creates a new StringView, given a const iterator to a std::string and the size.
StringView (const std::string::const_iterator &begin, const std::string::const_iterator &end) noexcept
Creates a new reference StringView, given two const iterators to a std::string.
StringView (const std::string &str) noexcept
Construct a StringView to the whole std::string.
iterator begin () const noexcept
Returns a pointer to the beginning of the data.
const char * data () const noexcept
Returns a pointer to the start of the data.
iterator end () const noexcept
Returns a pointer beyond the end of the data.
bool operator!= (const StringView &other) const noexcept
Inequality operator to compare a StringView with another StringView.
bool operator!= (const std::string &other) const noexcept
Inequality operator to compare a StringView with a std::string.
bool operator< (const StringView &other) const noexcept
bool operator< (const std::string &other) const noexcept
bool operator== (const StringView &other) const noexcept
Equality operator to compare a StringView with another StringView.
bool operator== (const std::string &other) const noexcept
Equality operator to compare a StringView with a std::string.
size_t size () const noexcept
Returns the size of this StringView.
std::string to_string () const
Returns the data of this StringView as a std::string.
Private Attributes
const char * data_
pointer to character data
size_t size_
size of data
Friends
std::ostream & operator<< (std::ostream &os, const StringView &sv)
make StringView ostreamable
Member Typedef Documentation
iterator
using iterator = const char*
Definition at line 35 of file string_view.hpp.
Constructor & Destructor Documentation
StringView() [1/5]
StringView () default
Default constructor for a StringView. Doesn't initialize anything.
StringView() [2/5]
StringView (const char * data, size_t size) inline noexcept
Creates a new StringView, given a const char* and the size.
Parameters
data pointer to start of data
size size of data in bytes.
Returns
new StringView object.
Definition at line 47 of file string_view.hpp.
StringView() [3/5]
StringView (const std::string::const_iterator & data, size_t size) inline noexcept
Creates a new StringView, given a const iterator to a std::string and the size.
Parameters
data iterator to start of data
size size of data in character.
Returns
new StringView object.
Definition at line 58 of file string_view.hpp.
StringView() [4/5]
StringView (const std::string::const_iterator & begin, const std::string::const_iterator & end) inline noexcept
Creates a new reference StringView, given two const iterators to a std::string.
Parameters
begin iterator to start of data
end iterator to the end of data.
Returns
new StringView object.
Definition at line 69 of file string_view.hpp.
StringView() [5/5]
StringView (const std::string & str) inline explicit noexcept
Construct a StringView to the whole std::string.
Definition at line 74 of file string_view.hpp.
Member Function Documentation
begin()
iterator begin () const inline noexcept
Returns a pointer to the beginning of the data.
Definition at line 83 of file string_view.hpp.
References StringView::data_.
data()
const char* data () const inline noexcept
Returns a pointer to the start of the data.
Definition at line 78 of file string_view.hpp.
References StringView::data_.
Referenced by hash< tlx::StringView >::operator()().
end()
iterator end () const inline noexcept
Returns a pointer beyond the end of the data.
Definition at line 88 of file string_view.hpp.
References StringView::data_, and StringView::size_.
operator!=() [1/2]
bool operator!= (const StringView & other) const inline noexcept
Inequality operator to compare a StringView with another StringView.
Definition at line 104 of file string_view.hpp.
References StringView::operator==().
operator!=() [2/2]
bool operator!= (const std::string & other) const inline noexcept
Inequality operator to compare a StringView with a std::string.
Definition at line 122 of file string_view.hpp.
References StringView::operator==().
operator<() [1/2]
bool operator< (const StringView & other) const inline noexcept
Less operator to compare a StringView with another StringView lexicographically
Definition at line 110 of file string_view.hpp.
References StringView::data_, and StringView::size_.
operator<() [2/2]
bool operator< (const std::string & other) const inline noexcept
Less operator to compare a StringView with a std::string lexicographically
Definition at line 128 of file string_view.hpp.
References StringView::data_, and StringView::size_.
operator==() [1/2]
bool operator== (const StringView & other) const inline noexcept
Equality operator to compare a StringView with another StringView.
Definition at line 98 of file string_view.hpp.
References StringView::data_, and StringView::size_.
Referenced by StringView::operator!=().
operator==() [2/2]
bool operator== (const std::string & other) const inline noexcept
Equality operator to compare a StringView with a std::string.
Definition at line 116 of file string_view.hpp.
References StringView::data_, and StringView::size_.
size()
size_t size () const inline noexcept
Returns the size of this StringView.
Definition at line 93 of file string_view.hpp.
References StringView::size_.
Referenced by examples::word_count::HashWordCountExample(), main(), hash< tlx::StringView >::operator()(), and examples::word_count::WordCount().
to_string()
std::string to_string () const inline
Returns the data of this StringView as a std::string.
Definition at line 139 of file string_view.hpp.
References StringView::data_, and StringView::size_.
Referenced by examples::word_count::HashWordCountExample(), main(), WordCount(), and examples::word_count::WordCount().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const StringView & sv) friend
make StringView ostreamable
Definition at line 134 of file string_view.hpp.
Member Data Documentation
data_
const char* data_ private
pointer to character data
Definition at line 147 of file string_view.hpp.
Referenced by StringView::begin(), StringView::data(), StringView::end(), StringView::operator<(), StringView::operator==(), and StringView::to_string().
size_
size_t size_ private
size of data
Definition at line 149 of file string_view.hpp.
Referenced by StringView::end(), StringView::operator<(), StringView::operator==(), StringView::size(), and StringView::to_string().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/container/string_view.hpp