Thrill: GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount Class Reference
GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount Class Reference
Detailed Description
template<typename ValueType, typename KeyExtractor, typename GroupFunction, typename HashFunction, bool UseLocationDetection>
class thrill::api::GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount
Definition at line 72 of file group_by_key.hpp.
Public Types
using CounterType = uint8_t
using HashType = size_t
Public Member Functions
bool NeedBroadcast () const
HashCount operator+ (const HashCount &b) const
HashCount & operator+= (const HashCount &b)
bool operator< (const HashCount &b) const
template<typename BitReader >
void ReadBits (BitReader &reader)
Read count from BitReader.
template<typename BitWriter >
void WriteBits (BitWriter &writer) const
Write count and dia_mask to BitWriter.
Public Attributes
CounterType count
size_t hash
Static Public Attributes
static constexpr size_t counter_bits_ = 8 * sizeof(CounterType)
Member Typedef Documentation
using CounterType = uint8_t
Definition at line 76 of file group_by_key.hpp.
using HashType = size_t
Definition at line 75 of file group_by_key.hpp.
Member Function Documentation
bool NeedBroadcast () const inline
method to check if this hash count should be broadcasted to all workers interested – for GroupByKey -> always.
Definition at line 98 of file group_by_key.hpp.
HashCount operator+ (const HashCount & b) const inline
Definition at line 83 of file group_by_key.hpp.
References thrill::common::AddTruncToType(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::count, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::hash.
HashCount& operator+= (const HashCount & b) inline
Definition at line 88 of file group_by_key.hpp.
References thrill::common::AddTruncToType(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::count, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::hash.
bool operator< (const HashCount & b) const inline
Definition at line 94 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::hash.
void ReadBits (BitReader & reader) inline
Read count from BitReader.
Definition at line 104 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::count, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::counter_bits_.
void WriteBits (BitWriter & writer) const inline
Write count and dia_mask to BitWriter.
Definition at line 110 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::count, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::counter_bits_.
Member Data Documentation
CounterType count
Definition at line 79 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::operator+(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::operator+=(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::ReadBits(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::WriteBits().
constexpr size_t counter_bits_ = 8 * sizeof(CounterType) static
Definition at line 81 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::ReadBits(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::WriteBits().
size_t hash
Definition at line 78 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::operator+(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::operator+=(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::HashCount::operator<().
The documentation for this class was generated from the following file:
thrill/api/group_by_key.hpp