Thrill: PS5Context< Parameters > Class Template Reference
PS5Context< Parameters > Class Template Reference
Detailed Description
template<typename Parameters>
class tlx::sort_strings_detail::PS5Context< Parameters >
Parallel Super Scalar String Sample Sort Context.
Definition at line 94 of file parallel_sample_sort.hpp.
Inherits Parameters.
#include <parallel_sample_sort.hpp>
Public Member Functions
PS5Context (size_t _thread_num)
context constructor
void donesize (size_t n)
decrement number of unordered strings
template<typename StringPtr >
void enqueue (PS5SortStep *sstep, const StringPtr &strptr, size_t depth)
enqueue a new job in the thread pool
size_t sequential_threshold ()
return sequential sorting threshold
Public Attributes
std::atomic< size_t > base_sort_steps
MultiTimer mtimer
timers for individual sorting steps
size_t num_threads
number of threads overall
std::atomic< size_t > para_ss_steps
counters
std::atomic< size_t > rest_size
number of remaining strings to sort
std::atomic< size_t > sequ_ss_steps
ThreadPool threads_
thread pool
size_t total_size
total size of input
Constructor & Destructor Documentation
PS5Context (size_t _thread_num) inline
context constructor
Definition at line 116 of file parallel_sample_sort.hpp.
Member Function Documentation
void donesize (size_t n) inline
decrement number of unordered strings
Definition at line 138 of file parallel_sample_sort.hpp.
References PS5Context< Parameters >::rest_size.
void enqueue (PS5SortStep * sstep, const StringPtr & strptr, size_t depth)
enqueue a new job in the thread pool
Definition at line 1394 of file parallel_sample_sort.hpp.
References StringPtr< StringSet_ >::size().
size_t sequential_threshold () inline
return sequential sorting threshold
Definition at line 127 of file parallel_sample_sort.hpp.
References max(), PS5Context< Parameters >::num_threads, PS5Context< Parameters >::rest_size, thrill::core::hyperloglog::threshold(), and PS5Context< Parameters >::total_size.
Member Data Documentation
std::atomic<size_t> base_sort_steps
Definition at line 104 of file parallel_sample_sort.hpp.
MultiTimer mtimer
timers for individual sorting steps
Definition at line 107 of file parallel_sample_sort.hpp.
size_t num_threads
number of threads overall
Definition at line 110 of file parallel_sample_sort.hpp.
Referenced by PS5Context< Parameters >::sequential_threshold().
std::atomic<size_t> para_ss_steps
counters
Definition at line 104 of file parallel_sample_sort.hpp.
std::atomic<size_t> rest_size
number of remaining strings to sort
Definition at line 101 of file parallel_sample_sort.hpp.
Referenced by PS5Context< Parameters >::donesize(), and PS5Context< Parameters >::sequential_threshold().
std::atomic<size_t> sequ_ss_steps
Definition at line 104 of file parallel_sample_sort.hpp.
ThreadPool threads_
thread pool
Definition at line 113 of file parallel_sample_sort.hpp.
size_t total_size
total size of input
Definition at line 98 of file parallel_sample_sort.hpp.
Referenced by PS5Context< Parameters >::sequential_threshold().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/parallel_sample_sort.hpp