Thrill: SimpleVector< ValueType, Mode > Class Template Reference
SimpleVector< ValueType, Mode > Class Template Reference
Thrill Layers » tlx - C++ Extensions and Utilities » Containers and Data Structures
Detailed Description
template<typename ValueType, SimpleVectorMode Mode = SimpleVectorMode::Normal>
class tlx::SimpleVector< ValueType, Mode >
Simpler non-growing vector without initialization.
SimpleVector can be used a replacement for std::vector when only a non-growing array of simple types is needed. The advantages of SimpleVector are that it does not initilize memory for POD types (-> faster), while normal structs are supported as well if default-contractible. The simple pointer types allow faster compilation and is less error prone to copying and other problems.
Definition at line 50 of file simple_vector.hpp.
#include <simple_vector.hpp>
Public Types
using const_iterator = const value_type *
using const_reference = const value_type &
using iterator = value_type *
using reference = value_type &
using size_type = size_t
using value_type = ValueType
Public Member Functions
SimpleVector ()
allocate empty simple vector
SimpleVector (const size_type &sz)
allocate vector's memory
SimpleVector (const SimpleVector &)=delete
non-copyable: delete copy-constructor
SimpleVector (SimpleVector &&v) noexcept
move-constructor
~SimpleVector ()
delete vector
iterator begin () noexcept
return mutable iterator to first element
const_iterator begin () const noexcept
return constant iterator to first element
const_iterator cbegin () const noexcept
return constant iterator to first element
const_iterator cend () const noexcept
return constant iterator beyond last element
iterator data () noexcept
return iterator to beginning of vector
const_iterator data () const noexcept
return iterator to beginning of vector
void destroy ()
deallocate contained array
iterator end () noexcept
return mutable iterator beyond last element
const_iterator end () const noexcept
return constant iterator beyond last element
void fill (const value_type &v=value_type()) noexcept
Zero the whole array content.
SimpleVector & operator= (const SimpleVector &)=delete
non-copyable: delete assignment operator
SimpleVector & operator= (SimpleVector &&v) noexcept
move-assignment
reference operator[] (size_type i) noexcept
return the i-th position of the vector
const_reference operator[] (size_type i) const noexcept
return constant reference to the i-th position of the vector
void resize (size_type new_size)
resize the array to contain exactly new_size items
size_type size () const noexcept
return number of items in vector
void swap (SimpleVector &obj) noexcept
swap vector with another one
Protected Attributes
value_type * array_
pointer to allocated memory area
size_type size_
size of allocated memory
Static Private Member Functions
static ValueType * create_array (size_t size)
static void destroy_array (ValueType *array, size_t size)
Member Typedef Documentation
const_iterator
using const_iterator = const value_type *
Definition at line 67 of file simple_vector.hpp.
const_reference
using const_reference = const value_type&
Definition at line 69 of file simple_vector.hpp.
iterator
using iterator = value_type *
Definition at line 66 of file simple_vector.hpp.
reference
using reference = value_type&
Definition at line 68 of file simple_vector.hpp.
size_type
using size_type = size_t
Definition at line 54 of file simple_vector.hpp.
value_type
using value_type = ValueType
Definition at line 53 of file simple_vector.hpp.
Constructor & Destructor Documentation
SimpleVector() [1/4]
SimpleVector () inline
allocate empty simple vector
Definition at line 73 of file simple_vector.hpp.
SimpleVector() [2/4]
SimpleVector (const size_type & sz) inline explicit
allocate vector's memory
Definition at line 78 of file simple_vector.hpp.
SimpleVector() [3/4]
SimpleVector (const SimpleVector< ValueType, Mode > &) delete
non-copyable: delete copy-constructor
SimpleVector() [4/4]
SimpleVector (SimpleVector< ValueType, Mode > && v) inline noexcept
move-constructor
Definition at line 90 of file simple_vector.hpp.
~SimpleVector()
~SimpleVector () inline
delete vector
Definition at line 110 of file simple_vector.hpp.
Member Function Documentation
begin() [1/2]
iterator begin () inline noexcept
return mutable iterator to first element
Definition at line 128 of file simple_vector.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), foxxll::compute_prefetch_schedule(), tlx::parallel_mergesort_detail::determine_samples(), disk_block_allocator::new_blocks(), tlx::parallel_multiway_merge_base(), tlx::parallel_mergesort_detail::parallel_sort_mwms_pu(), PS5BigSortStep< Context, StringPtr >::sample(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::SeqSampleSortStep().
begin() [2/2]
const_iterator begin () const inline noexcept
return constant iterator to first element
Definition at line 132 of file simple_vector.hpp.
cbegin()
const_iterator cbegin () const inline noexcept
return constant iterator to first element
Definition at line 136 of file simple_vector.hpp.
cend()
const_iterator cend () const inline noexcept
return constant iterator beyond last element
Definition at line 149 of file simple_vector.hpp.
create_array()
static ValueType* create_array (size_t size) inline static private
Definition at line 190 of file simple_vector.hpp.
data() [1/2]
iterator data () inline noexcept
return iterator to beginning of vector
Definition at line 115 of file simple_vector.hpp.
Referenced by PS5BigSortStep< Context, StringPtr >::count(), PS5BigSortStep< Context, StringPtr >::distribute(), PS5BigSortStep< Context, StringPtr >::distribute_finished(), tlx::parallel_multiway_merge_base(), PS5BigSortStep< Context, StringPtr >::sample(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::SeqSampleSortStep(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), and PS5BigSortStep< Context, StringPtr >::substep_all_done().
data() [2/2]
const_iterator data () const inline noexcept
return iterator to beginning of vector
Definition at line 119 of file simple_vector.hpp.
destroy()
void destroy () inline
deallocate contained array
Definition at line 178 of file simple_vector.hpp.
Referenced by PS5BigSortStep< Context, StringPtr >::distribute(), PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5BigSortStep< Context, StringPtr >::substep_all_done().
destroy_array()
static void destroy_array (ValueType * array, size_t size) inline static private
Definition at line 205 of file simple_vector.hpp.
end() [1/2]
iterator end () inline noexcept
return mutable iterator beyond last element
Definition at line 141 of file simple_vector.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), foxxll::compute_prefetch_schedule(), disk_block_allocator::new_blocks(), tlx::parallel_multiway_merge_base(), PS5BigSortStep< Context, StringPtr >::sample(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::SeqSampleSortStep().
end() [2/2]
const_iterator end () const inline noexcept
return constant iterator beyond last element
Definition at line 145 of file simple_vector.hpp.
fill()
void fill (const value_type & v = value_type()) inline noexcept
Zero the whole array content.
Definition at line 185 of file simple_vector.hpp.
Referenced by block_manager::new_blocks().
operator=() [1/2]
SimpleVector& operator= (const SimpleVector< ValueType, Mode > &) delete
non-copyable: delete assignment operator
operator=() [2/2]
SimpleVector& operator= (SimpleVector< ValueType, Mode > && v) inline noexcept
move-assignment
Definition at line 95 of file simple_vector.hpp.
operator[]() [1/2]
reference operator[] (size_type i) inline noexcept
return the i-th position of the vector
Definition at line 154 of file simple_vector.hpp.
operator[]() [2/2]
const_reference operator[] (size_type i) const inline noexcept
return constant reference to the i-th position of the vector
Definition at line 158 of file simple_vector.hpp.
resize()
void resize (size_type new_size) inline
resize the array to contain exactly new_size items
Definition at line 163 of file simple_vector.hpp.
Referenced by PS5BigSortStep< Context, StringPtr >::count(), tlx::multiway_merge_exact_splitting(), block_manager::new_blocks(), PS5BigSortStep< Context, StringPtr >::PS5BigSortStep(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache().
size()
size_type size () const inline noexcept
return number of items in vector
Definition at line 123 of file simple_vector.hpp.
Referenced by buf_istream_reverse< BlockType, BidIteratorType >::buf_istream_reverse(), disk_block_allocator::delete_blocks(), LoserTreeCopyBase< ValueType, Comparator >::insert_start(), LoserTreePointerBase< ValueType, Comparator >::insert_start(), LoserTreeCopyUnguardedBase< ValueType, Comparator >::insert_start(), LoserTreePointerUnguardedBase< ValueType, Comparator >::insert_start(), block_manager::new_blocks(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache().
swap()
void swap (SimpleVector< ValueType, Mode > & obj) inline noexcept
swap vector with another one
Definition at line 104 of file simple_vector.hpp.
Member Data Documentation
array_
value_type* array_ protected
pointer to allocated memory area
Definition at line 61 of file simple_vector.hpp.
size_
size_type size_ protected
size of allocated memory
Definition at line 58 of file simple_vector.hpp.
The documentation for this class was generated from the following file:
extlib/tlx/tlx/container/simple_vector.hpp