Thrill: SSTreeBuilderPreAndLevelOrder< key_type, num_splitters > Class Template Reference
SSTreeBuilderPreAndLevelOrder< key_type, num_splitters > Class Template Reference
Detailed Description
template<typename key_type, size_t num_splitters>
class tlx::sort_strings_detail::SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >
Recursive TreeBuilder for full-descent and unrolled variants, constructs a both a pre-order and level-order array of splitters and the corresponding LCPs.
Definition at line 122 of file sample_sort_tools.hpp.
#include <sample_sort_tools.hpp>
Public Member Functions
SSTreeBuilderPreAndLevelOrder (key_type splitter[num_splitters], key_type tree[num_splitters+1], unsigned char splitter_lcp[num_splitters+1], const key_type *samples, size_t samplesize)
key_type recurse (const key_type *lo, const key_type *hi, unsigned int treeidx, key_type &rec_prevkey)
ptrdiff_t snum (const key_type *s) const
Private Attributes
unsigned char * lcp_iter_
const key_type * samples_
key_type * splitter_
key_type * tree_
Static Private Attributes
static const bool debug_splitter = false
Constructor & Destructor Documentation
SSTreeBuilderPreAndLevelOrder (key_type splitter[num_splitters], key_type tree[num_splitters+1], unsigned char splitter_lcp[num_splitters+1], const key_type * samples, size_t samplesize) inline
Definition at line 129 of file sample_sort_tools.hpp.
References SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::lcp_iter_, SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse(), thrill::mem::sentinel, and SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::splitter_.
Member Function Documentation
key_type recurse (const key_type * lo, const key_type * hi, unsigned int treeidx, key_type & rec_prevkey) inline
Definition at line 150 of file sample_sort_tools.hpp.
References tlx::clz(), SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::debug_splitter, tlx::hexdump_type(), SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::lcp_iter_, SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::snum(), SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::splitter_, TLX_LOG0, TLX_LOGC, and SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::tree_.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::SSTreeBuilderPreAndLevelOrder().
ptrdiff_t snum (const key_type * s) const inline
Definition at line 146 of file sample_sort_tools.hpp.
References SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::samples_.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse().
Member Data Documentation
const bool debug_splitter = false static private
Definition at line 124 of file sample_sort_tools.hpp.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse().
unsigned char* lcp_iter_ private
Definition at line 225 of file sample_sort_tools.hpp.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse(), and SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::SSTreeBuilderPreAndLevelOrder().
const key_type* samples_ private
Definition at line 226 of file sample_sort_tools.hpp.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::snum().
key_type* splitter_ private
Definition at line 223 of file sample_sort_tools.hpp.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse(), and SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::SSTreeBuilderPreAndLevelOrder().
key_type* tree_ private
Definition at line 224 of file sample_sort_tools.hpp.
Referenced by SSTreeBuilderPreAndLevelOrder< key_type, num_splitters >::recurse().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/sample_sort_tools.hpp