Thrill: UfsFileBase Class Reference
UfsFileBase Class Reference
File I/O Implementations
Detailed Description
Base for UNIX file system implementations.
Definition at line 35 of file ufs_file_base.hpp.
#include <ufs_file_base.hpp>
Public Member Functions
~UfsFileBase ()
void close_remove () final
close and remove file
const char * io_type () const override
bool is_device () const
return true if file is special device node
void lock () final
Locks file for reading and writing (acquires a lock in the file system).
void set_size (offset_type newsize) final
offset_type size () final
void unlink ()
unlink file without closing it.
Public Member Functions inherited from FileBase
FileBase (const FileBase &)=delete
non-copyable: delete copy-constructor
FileBase (FileBase &&)=default
move-constructor: default
FileBase (unsigned int device_id=DEFAULT_DEVICE_ID)
Construct a new file, usually called by a subclass.
virtual ~FileBase ()
virtual RequestPtr aread (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler())=0
virtual RequestPtr awrite (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler())=0
virtual void discard (offset_type offset, offset_type size)
virtual int get_allocator_id () const =0
Returns the file's disk allocator number.
unsigned int get_device_id () const
Returns the file's physical device id.
virtual int get_queue_id () const =0
bool need_alignment () const
Returns need_alignment_.
FileBase & operator= (const FileBase &)=delete
non-copyable: delete assignment operator
FileBase & operator= (FileBase &&)=default
move-assignment operator: default
virtual void serve (void *buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type)=0
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Protected Member Functions
UfsFileBase (const std::string &filename, int mode)
void _after_open ()
void _set_size (offset_type newsize)
offset_type _size ()
void close ()
Protected Attributes
std::mutex fd_mutex_
int file_des_
bool is_device_
is special device node
int mode_
const std::string path_
Protected Attributes inherited from FileBase
unsigned int device_id_
bool need_alignment_ = false
Flag whether read/write operations require alignment.
Additional Inherited Members
Public Types inherited from FileBase
using offset_type = Request::offset_type
the offset of a request, also the size of the file
enum OpenMode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128,
REQUIRE_DIRECT = 256
}
using size_type = Request::size_type
the size of a request
Static Public Member Functions inherited from FileBase
static int unlink (const char *path)
unlink path from filesystem
static int truncate (const char *path, size_t length)
Static Public Attributes inherited from FileBase
static constexpr bool debug = false
static constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1)
static constexpr int DEFAULT_LINUXAIO_QUEUE = -2
static constexpr int DEFAULT_QUEUE = -1
static constexpr int NO_ALLOCATOR = -1
Constructor & Destructor Documentation
UfsFileBase (const std::string & filename, int mode) protected
Definition at line 33 of file ufs_file_base.cpp.
References UfsFileBase::_after_open(), FileBase::CREAT, FileBase::DIRECT, UfsFileBase::file_des_, LOG1, UfsFileBase::mode_, FileBase::need_alignment_, O_BINARY, O_DIRECT, O_DSYNC, O_RSYNC, O_SYNC, FileBase::RDONLY, FileBase::RDWR, FileBase::REQUIRE_DIRECT, FileBase::SYNC, THRILL_THROW_ERRNO, FileBase::TRUNC, and FileBase::WRONLY.
~UfsFileBase ()
Definition at line 115 of file ufs_file_base.cpp.
References UfsFileBase::close().
Member Function Documentation
void _after_open () protected
Definition at line 119 of file ufs_file_base.cpp.
References FileBase::DIRECT, UfsFileBase::file_des_, UfsFileBase::is_device_, UfsFileBase::lock(), LOG1, UfsFileBase::mode_, FileBase::NO_LOCK, UfsFileBase::path_, FileBase::REQUIRE_DIRECT, S_ISBLK, and THRILL_THROW_ERRNO_NE_0.
Referenced by UfsFileBase::UfsFileBase().
void _set_size (offset_type newsize) protected
Definition at line 206 of file ufs_file_base.cpp.
References UfsFileBase::_size(), UfsFileBase::file_des_, UfsFileBase::is_device_, lseek, UfsFileBase::mode_, UfsFileBase::path_, FileBase::RDONLY, THRILL_THROW_ERRNO_LT_0, THRILL_THROW_ERRNO_NE_0, and THRILL_THROW_WIN_LASTERROR.
Referenced by UfsFileBase::set_size().
FileBase::offset_type _size () protected
Definition at line 183 of file ufs_file_base.cpp.
References UfsFileBase::file_des_, lseek, off_t, UfsFileBase::path_, and THRILL_THROW_ERRNO.
Referenced by UfsFileBase::_set_size(), SyscallFile::serve(), and UfsFileBase::size().
void close () protected
Definition at line 156 of file ufs_file_base.cpp.
References UfsFileBase::fd_mutex_, UfsFileBase::file_des_, and THRILL_THROW_ERRNO.
Referenced by UfsFileBase::close_remove(), and UfsFileBase::~UfsFileBase().
void close_remove () final virtual
close and remove file
Reimplemented from FileBase.
Definition at line 241 of file ufs_file_base.cpp.
References UfsFileBase::close(), UfsFileBase::is_device_, LOG1, and UfsFileBase::path_.
const char * io_type () const override virtual
Identifies the type of I/O implementation.
Returns
pointer to null terminated string of characters, containing the name of I/O implementation
Implements FileBase.
Definition at line 29 of file ufs_file_base.cpp.
bool is_device () const
return true if file is special device node
Definition at line 263 of file ufs_file_base.cpp.
References UfsFileBase::is_device_.
Referenced by thrill::io::CreateFile().
void lock () final virtual
Locks file for reading and writing (acquires a lock in the file system).
Implements FileBase.
Definition at line 168 of file ufs_file_base.cpp.
References UfsFileBase::fd_mutex_, UfsFileBase::file_des_, UfsFileBase::mode_, UfsFileBase::path_, FileBase::RDONLY, and THRILL_THROW_ERRNO.
Referenced by UfsFileBase::_after_open(), and thrill::io::CreateFile().
void set_size (offset_type newsize) final virtual
Changes the size of the file.
Parameters
newsize new file size
Implements FileBase.
Definition at line 201 of file ufs_file_base.cpp.
References UfsFileBase::_set_size(), and UfsFileBase::fd_mutex_.
FileBase::offset_type size () final virtual
Returns size of the file.
Returns
file size in bytes
Implements FileBase.
Definition at line 196 of file ufs_file_base.cpp.
References UfsFileBase::_size(), and UfsFileBase::fd_mutex_.
Referenced by thrill::io::CreateFile().
void unlink ()
unlink file without closing it.
Definition at line 253 of file ufs_file_base.cpp.
References UfsFileBase::file_des_, UfsFileBase::is_device_, LOG1, UfsFileBase::path_, and THRILL_THROW_ERRNO.
Referenced by thrill::io::CreateFile().
Member Data Documentation
std::mutex fd_mutex_ protected
Definition at line 38 of file ufs_file_base.hpp.
Referenced by UfsFileBase::close(), UfsFileBase::lock(), SyscallFile::serve(), MmapFile::serve(), UfsFileBase::set_size(), and UfsFileBase::size().
int file_des_ protected
Definition at line 39 of file ufs_file_base.hpp.
Referenced by UfsFileBase::_after_open(), UfsFileBase::_set_size(), UfsFileBase::_size(), UfsFileBase::close(), LinuxaioRequest::fill_control_block(), UfsFileBase::lock(), SyscallFile::serve(), MmapFile::serve(), UfsFileBase::UfsFileBase(), and UfsFileBase::unlink().
bool is_device_ protected
is special device node
Definition at line 42 of file ufs_file_base.hpp.
Referenced by UfsFileBase::_after_open(), UfsFileBase::_set_size(), UfsFileBase::close_remove(), UfsFileBase::is_device(), and UfsFileBase::unlink().
int mode_ protected
Definition at line 40 of file ufs_file_base.hpp.
Referenced by UfsFileBase::_after_open(), UfsFileBase::_set_size(), UfsFileBase::lock(), and UfsFileBase::UfsFileBase().
const std::string path_ protected
Definition at line 41 of file ufs_file_base.hpp.
Referenced by UfsFileBase::_after_open(), UfsFileBase::_set_size(), UfsFileBase::_size(), UfsFileBase::close_remove(), UfsFileBase::lock(), SyscallFile::serve(), MmapFile::serve(), and UfsFileBase::unlink().
The documentation for this class was generated from the following files:
thrill/io/ufs_file_base.hpp
thrill/io/ufs_file_base.cpp