Thrill: VPoint Class Reference
VPoint Class Reference
Detailed Description
A D-dimensional point with double precision.
Definition at line 102 of file k-means.hpp.
#include <k-means.hpp>
Public Types
using Vector = std::vector< double >
Public Member Functions
VPoint (size_t D=0)
VPoint (Vector &&v)
size_t dim () const
double Distance (const VPoint &b) const
double DistanceSquare (const VPoint &b) const
VPoint operator+ (const VPoint &b) const
VPoint & operator+= (const VPoint &b)
VPoint operator/ (double s) const
VPoint & operator/= (double s)
template<typename Archive >
void serialize (Archive &archive)
Static Public Member Functions
static VPoint Make (size_t D)
template<typename Distribution , typename Generator >
static VPoint Random (size_t D, Distribution &dist, Generator &gen)
Public Attributes
Vector x
coordinates array
Friends
std::ostream & operator<< (std::ostream &os, const VPoint &a)
Member Typedef Documentation
using Vector = std::vector<double>
Definition at line 105 of file k-means.hpp.
Constructor & Destructor Documentation
VPoint (size_t D = 0) inline explicit
Definition at line 110 of file k-means.hpp.
Referenced by VPoint::Make().
VPoint (Vector && v) inline explicit
Definition at line 111 of file k-means.hpp.
Member Function Documentation
size_t dim () const inline
Definition at line 113 of file k-means.hpp.
References VPoint::x.
double Distance (const VPoint & b) const inline
Definition at line 131 of file k-means.hpp.
References VPoint::DistanceSquare().
double DistanceSquare (const VPoint & b) const inline
Definition at line 124 of file k-means.hpp.
References VPoint::x.
Referenced by VPoint::Distance().
static VPoint Make (size_t D) inline static
Definition at line 115 of file k-means.hpp.
References VPoint::VPoint().
VPoint operator+ (const VPoint & b) const inline
Definition at line 134 of file k-means.hpp.
References VPoint::x.
VPoint& operator+= (const VPoint & b) inline
Definition at line 140 of file k-means.hpp.
References VPoint::x.
VPoint operator/ (double s) const inline
Definition at line 145 of file k-means.hpp.
References VPoint::x.
VPoint& operator/= (double s) inline
Definition at line 150 of file k-means.hpp.
References VPoint::x.
static VPoint Random (size_t D, Distribution & dist, Generator & gen) inline static
Definition at line 119 of file k-means.hpp.
References VPoint::x.
void serialize (Archive & archive) inline
Definition at line 161 of file k-means.hpp.
References VPoint::x.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const VPoint & a) friend
Definition at line 154 of file k-means.hpp.
Member Data Documentation
Vector x
coordinates array
Definition at line 108 of file k-means.hpp.
Referenced by VPoint::dim(), VPoint::DistanceSquare(), VPoint::operator+(), VPoint::operator+=(), VPoint::operator/(), VPoint::operator/=(), VPoint::Random(), and VPoint::serialize().
The documentation for this class was generated from the following file:
examples/k-means/k-means.hpp