Thrill: PolynomialRegression< Type, WithStore > Class Template Reference
PolynomialRegression< Type, WithStore > Class Template Reference
Thrill Layers » tlx - C++ Extensions and Utilities » Math Functions
Detailed Description
template<typename Type = double, bool WithStore = false>
class tlx::PolynomialRegression< Type, WithStore >
Calculate the regression polynomial \(a_0+a_1x^1+a_2x^2+\cdots+a_nx^n \) from a list of 2D points.
See also https://en.wikipedia.org/wiki/Polynomial_regression
If WithStore is false, then the sums are aggregated directly such that the class retains O(1) size independent of the number of points. if WithStore is true then the points are stored in a vector and can be retrieved.
Definition at line 33 of file polynomial_regression.hpp.
#include <polynomial_regression.hpp>
Classes
struct Coefficients
struct Point
2D point
Public Member Functions
PolynomialRegression (size_t order)
start new polynomial regression calculation
PolynomialRegression & add (const Type &x, const Type &y)
add point. this invalidates cached coefficients until next evaluate()
const Coefficients & coefficients ()
return coefficients vector
Type evaluate (const Type &x)
returns value of y predicted by the polynomial for a given value of x
const Point & point (size_t i)
return a point. Only available if WithStore is true.
Type r_square ()
get r^2. Only available if WithStore is true.
size_t size () const
number of points
Protected Member Functions
void fit_coefficients ()
polynomial regression by inverting a Vandermonde matrix.
Protected Attributes
Coefficients coefficients_
cached coefficients
size_t order_
polynomial order
std::vector< Point > points_
list of stored points if WithStore, else empty.
size_t size_
number of points added
std::vector< Type > X_
X_ = vector that stores values of sigma(x_i^2n)
std::vector< Type > Y_
Y_ = vector to store values of sigma(x_i^order * y_i)
Constructor & Destructor Documentation
PolynomialRegression()
PolynomialRegression (size_t order) inline
start new polynomial regression calculation
Definition at line 37 of file polynomial_regression.hpp.
Member Function Documentation
add()
PolynomialRegression& add (const Type & x, const Type & y) inline
add point. this invalidates cached coefficients until next evaluate()
Definition at line 52 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::coefficients_, PolynomialRegression< Type, WithStore >::order_, PolynomialRegression< Type, WithStore >::points_, PolynomialRegression< Type, WithStore >::size_, PolynomialRegression< Type, WithStore >::Point::x, PolynomialRegression< Type, WithStore >::X_, PolynomialRegression< Type, WithStore >::Point::y, and PolynomialRegression< Type, WithStore >::Y_.
coefficients()
const Coefficients& coefficients () inline
return coefficients vector
Definition at line 127 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::coefficients_, and PolynomialRegression< Type, WithStore >::fit_coefficients().
Referenced by PolynomialRegression< Type, WithStore >::evaluate().
evaluate()
Type evaluate (const Type & x) inline
returns value of y predicted by the polynomial for a given value of x
Definition at line 122 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::coefficients(), and PolynomialRegression< Type, WithStore >::Coefficients::evaluate().
Referenced by PolynomialRegression< Type, WithStore >::r_square().
fit_coefficients()
void fit_coefficients () inline protected
polynomial regression by inverting a Vandermonde matrix.
Definition at line 154 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::order_, and tlx::swap().
Referenced by PolynomialRegression< Type, WithStore >::coefficients().
point()
const Point& point (size_t i) inline
return a point. Only available if WithStore is true.
Definition at line 78 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::points_.
r_square()
Type r_square () inline
get r^2. Only available if WithStore is true.
mean value of y
Definition at line 96 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::evaluate(), PolynomialRegression< Type, WithStore >::points_, PolynomialRegression< Type, WithStore >::size_, PolynomialRegression< Type, WithStore >::Point::y, and PolynomialRegression< Type, WithStore >::Y_.
size()
size_t size () const inline
number of points
Definition at line 42 of file polynomial_regression.hpp.
References PolynomialRegression< Type, WithStore >::size_.
Referenced by PolynomialRegression< Type, WithStore >::Coefficients::evaluate().
Member Data Documentation
coefficients_
Coefficients coefficients_ protected
cached coefficients
Definition at line 151 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add(), and PolynomialRegression< Type, WithStore >::coefficients().
order_
size_t order_ protected
polynomial order
Definition at line 136 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add(), and PolynomialRegression< Type, WithStore >::fit_coefficients().
points_
std::vector<Point> points_ protected
list of stored points if WithStore, else empty.
Definition at line 139 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add(), PolynomialRegression< Type, WithStore >::point(), and PolynomialRegression< Type, WithStore >::r_square().
size_
size_t size_ protected
number of points added
Definition at line 142 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add(), PolynomialRegression< Type, WithStore >::r_square(), and PolynomialRegression< Type, WithStore >::size().
X_
std::vector<Type> X_ protected
X_ = vector that stores values of sigma(x_i^2n)
Definition at line 145 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add().
Y_
std::vector<Type> Y_ protected
Y_ = vector to store values of sigma(x_i^order * y_i)
Definition at line 148 of file polynomial_regression.hpp.
Referenced by PolynomialRegression< Type, WithStore >::add(), and PolynomialRegression< Type, WithStore >::r_square().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/math/polynomial_regression.hpp