Thrill: DAryHeap< KeyType, Arity, Compare > Class Template Reference
DAryHeap< KeyType, Arity, Compare > Class Template Reference
Containers and Data Structures
Detailed Description
template<typename KeyType, unsigned Arity = 2, typename Compare = std::less<KeyType>>
class tlx::DAryHeap< KeyType, Arity, Compare >
This class implements a d-ary comparison-based heap usable as a priority queue.
Higher arity yields better cache efficiency.
Template Parameters
KeyType Key type.
Arity A positive integer.
Compare Function object to order keys.
Definition at line 37 of file d_ary_heap.hpp.
#include <d_ary_heap.hpp>
Public Types
using compare_type = Compare
using key_type = KeyType
Public Member Functions
DAryHeap (compare_type cmp=compare_type())
Allocates an empty heap.
DAryHeap (const DAryHeap &)=default
Copy.
DAryHeap (DAryHeap &&)=default
Move.
template<class InputIterator >
void build_heap (InputIterator first, InputIterator last)
Builds a heap from a container.
void build_heap (const std::vector< key_type > &keys)
Builds a heap from the vector keys. Items of keys are copied.
void build_heap (std::vector< key_type > &&keys)
Builds a heap from the vector keys. Items of keys are moved.
size_t capacity () const noexcept
Returns the capacity of the heap.
void clear ()
Empties the heap.
bool empty () const noexcept
Returns true if the heap has no items, false otherwise.
key_type extract_top ()
Removes and returns the top item.
DAryHeap & operator= (const DAryHeap &)=default
DAryHeap & operator= (DAryHeap &&)=default
void pop ()
Removes the top item.
void push (const key_type &new_key)
Inserts a new item.
void push (key_type &&new_key)
Inserts a new item.
void reserve (size_t new_size)
Allocates space for new_size items.
bool sanity_check ()
size_t size () const noexcept
Returns the number of items in the heap.
const key_type & top () const noexcept
Returns the top item.
void update_all ()
Rebuilds the heap.
Static Public Attributes
static constexpr size_t arity = Arity
Protected Attributes
compare_type cmp_
Compare function.
std::vector< key_type > heap_
Cells in the heap.
Private Member Functions
void heapify ()
Reorganize heap_ into a heap.
size_t left (size_t k) const
Returns the position of the left child of the node at position k.
size_t parent (size_t k) const
Returns the position of the parent of the node at position k.
void sift_down (size_t k)
void sift_up (size_t k)
Member Typedef Documentation
using compare_type = Compare
Definition at line 43 of file d_ary_heap.hpp.
using key_type = KeyType
Definition at line 42 of file d_ary_heap.hpp.
Constructor & Destructor Documentation
DAryHeap (compare_type cmp = compare_type()) inline explicit
Allocates an empty heap.
Definition at line 56 of file d_ary_heap.hpp.
DAryHeap (const DAryHeap< KeyType, Arity, Compare > &) default
Copy.
DAryHeap (DAryHeap< KeyType, Arity, Compare > &&) default
Move.
Member Function Documentation
void build_heap (InputIterator first, InputIterator last) inline
Builds a heap from a container.
Definition at line 129 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::heapify().
void build_heap (const std::vector< key_type > & keys) inline
Builds a heap from the vector keys. Items of keys are copied.
Definition at line 135 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::heapify().
void build_heap (std::vector< key_type > && keys) inline
Builds a heap from the vector keys. Items of keys are moved.
Definition at line 142 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::empty(), DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::heapify().
size_t capacity () const inline noexcept
Returns the capacity of the heap.
Definition at line 81 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_.
void clear () inline
Empties the heap.
Definition at line 73 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_.
bool empty () const inline noexcept
Returns true if the heap has no items, false otherwise.
Definition at line 84 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_.
Referenced by DAryHeap< KeyType, Arity, Compare >::build_heap(), DAryHeap< KeyType, Arity, Compare >::pop(), DAryHeap< KeyType, Arity, Compare >::sanity_check(), and DAryHeap< KeyType, Arity, Compare >::top().
key_type extract_top () inline
Removes and returns the top item.
Definition at line 116 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::pop(), and DAryHeap< KeyType, Arity, Compare >::top().
void heapify () inline private
Reorganize heap_ into a heap.
Definition at line 224 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::arity, DAryHeap< KeyType, Arity, Compare >::cmp_, DAryHeap< KeyType, Arity, Compare >::heap_, DAryHeap< KeyType, Arity, Compare >::left(), and gen_data::value.
Referenced by DAryHeap< KeyType, Arity, Compare >::build_heap(), and DAryHeap< KeyType, Arity, Compare >::update_all().
size_t left (size_t k) const inline private
Returns the position of the left child of the node at position k.
Definition at line 175 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::arity.
Referenced by DAryHeap< KeyType, Arity, Compare >::heapify(), DAryHeap< KeyType, Arity, Compare >::sanity_check(), and DAryHeap< KeyType, Arity, Compare >::sift_down().
DAryHeap& operator= (const DAryHeap< KeyType, Arity, Compare > &) default
DAryHeap& operator= (DAryHeap< KeyType, Arity, Compare > &&) default
size_t parent (size_t k) const inline private
Returns the position of the parent of the node at position k.
Definition at line 178 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::arity.
Referenced by DAryHeap< KeyType, Arity, Compare >::sift_up().
void pop () inline
Removes the top item.
Definition at line 107 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::empty(), DAryHeap< KeyType, Arity, Compare >::heap_, DAryHeap< KeyType, Arity, Compare >::sift_down(), and tlx::swap().
Referenced by DAryHeap< KeyType, Arity, Compare >::extract_top().
void push (const key_type & new_key) inline
Inserts a new item.
Definition at line 87 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::sift_up().
void push (key_type && new_key) inline
Inserts a new item.
Definition at line 94 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::sift_up().
void reserve (size_t new_size) inline
Allocates space for new_size items.
Definition at line 60 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_.
bool sanity_check () inline
For debugging: runs a BFS from the root node and verifies that the heap property is respected.
Definition at line 151 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::arity, DAryHeap< KeyType, Arity, Compare >::cmp_, DAryHeap< KeyType, Arity, Compare >::empty(), DAryHeap< KeyType, Arity, Compare >::heap_, and DAryHeap< KeyType, Arity, Compare >::left().
void sift_down (size_t k) inline private
Pushes the item at position k down until either it becomes a leaf or all its children have higher priority
Definition at line 194 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::arity, DAryHeap< KeyType, Arity, Compare >::cmp_, DAryHeap< KeyType, Arity, Compare >::heap_, DAryHeap< KeyType, Arity, Compare >::left(), min(), and gen_data::value.
Referenced by DAryHeap< KeyType, Arity, Compare >::pop().
void sift_up (size_t k) inline private
Pushes the node at position k up until either it becomes the root or its parent has lower or equal priority.
Definition at line 182 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::cmp_, DAryHeap< KeyType, Arity, Compare >::heap_, DAryHeap< KeyType, Arity, Compare >::parent(), and gen_data::value.
Referenced by DAryHeap< KeyType, Arity, Compare >::push().
size_t size () const inline noexcept
Returns the number of items in the heap.
Definition at line 78 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heap_.
const key_type& top () const inline noexcept
Returns the top item.
Definition at line 101 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::empty(), and DAryHeap< KeyType, Arity, Compare >::heap_.
Referenced by DAryHeap< KeyType, Arity, Compare >::extract_top().
void update_all () inline
Rebuilds the heap.
Definition at line 123 of file d_ary_heap.hpp.
References DAryHeap< KeyType, Arity, Compare >::heapify().
Member Data Documentation
constexpr size_t arity = Arity static
Definition at line 45 of file d_ary_heap.hpp.
Referenced by DAryHeap< KeyType, Arity, Compare >::heapify(), DAryHeap< KeyType, Arity, Compare >::left(), DAryHeap< KeyType, Arity, Compare >::parent(), DAryHeap< KeyType, Arity, Compare >::sanity_check(), and DAryHeap< KeyType, Arity, Compare >::sift_down().
compare_type cmp_ protected
Compare function.
Definition at line 52 of file d_ary_heap.hpp.
Referenced by DAryHeap< KeyType, Arity, Compare >::heapify(), DAryHeap< KeyType, Arity, Compare >::sanity_check(), DAryHeap< KeyType, Arity, Compare >::sift_down(), and DAryHeap< KeyType, Arity, Compare >::sift_up().
std::vector<key_type> heap_ protected
Cells in the heap.
Definition at line 49 of file d_ary_heap.hpp.
Referenced by DAryHeap< KeyType, Arity, Compare >::build_heap(), DAryHeap< KeyType, Arity, Compare >::capacity(), DAryHeap< KeyType, Arity, Compare >::clear(), DAryHeap< KeyType, Arity, Compare >::empty(), DAryHeap< KeyType, Arity, Compare >::heapify(), DAryHeap< KeyType, Arity, Compare >::pop(), DAryHeap< KeyType, Arity, Compare >::push(), DAryHeap< KeyType, Arity, Compare >::reserve(), DAryHeap< KeyType, Arity, Compare >::sanity_check(), DAryHeap< KeyType, Arity, Compare >::sift_down(), DAryHeap< KeyType, Arity, Compare >::sift_up(), DAryHeap< KeyType, Arity, Compare >::size(), and DAryHeap< KeyType, Arity, Compare >::top().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/container/d_ary_heap.hpp