Thrill: LinuxaioRequest Class Reference
LinuxaioRequest Class Reference final
I/O Requests and Queues
Detailed Description
Request for an linuxaio_file.
Definition at line 33 of file linuxaio_request.hpp.
#include <linuxaio_request.hpp>
Public Member Functions
LinuxaioRequest (const CompletionHandler &on_complete, const FileBasePtr &file, void *buffer, offset_type offset, size_type bytes, ReadOrWriteType type)
bool cancel () final
bool cancel_aio ()
Cancel already posted request.
void completed (bool posted, bool canceled)
void completed (bool canceled) final
called by file implementations when the request completes
bool post ()
Public Member Functions inherited from Request
Request (const CompletionHandler &on_complete, const FileBasePtr &file, void *buffer, offset_type offset, size_type bytes, ReadOrWriteType type)
ctor: initialize
Request (const Request &)=delete
non-copyable: delete copy-constructor
Request (Request &&)=default
move-constructor: default
virtual ~Request ()
Request & operator= (const Request &)=delete
non-copyable: delete assignment operator
Request & operator= (Request &&)=default
move-assignment operator: default
void wait (bool measure_time=true)
Suspends calling thread until completion of the request.
bool poll ()
Polls the status of the request.
const char * io_type () const
Identifies the type of I/O implementation.
const FileBasePtr & file () const
void * buffer () const
offset_type offset () const
size_type bytes () const
ReadOrWriteType type () const
void check_alignment () const
std::ostream & print (std::ostream &out) const
Dumps properties of a request.
void save_error (const mem::safe_string &msg)
IoError * error () const
return error if one occured
void check_error ()
Rises an exception if there was an error with the I/O.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Member Functions
void fill_control_block ()
Private Attributes
iocb cb_
control block of async request
Additional Inherited Members
Public Types inherited from Request
using offset_type = size_t
type for offsets within a file
enum ReadOrWriteType { READ, WRITE }
using size_type = size_t
type for block transfer sizes
enum State { OP = 0, DONE = 1, READY2DIE = 2 }
Protected Member Functions inherited from Request
void check_nref (bool after=false)
Protected Attributes inherited from Request
mem::safe_unique_ptr< IoError > error_
CompletionHandler on_complete_
FileBasePtr file_
file implementation to perform I/O with
void * buffer_
data buffer to transfer
offset_type offset_
offset within file
size_type bytes_
number of bytes at buffer_ to transfer
ReadOrWriteType type_
READ or WRITE.
Static Protected Attributes inherited from Request
static constexpr bool debug = false
Constructor & Destructor Documentation
LinuxaioRequest (const CompletionHandler & on_complete, const FileBasePtr & file, void * buffer, offset_type offset, size_type bytes, ReadOrWriteType type) inline
Definition at line 41 of file linuxaio_request.hpp.
References CountingPtr< Type, Deleter >::get(), and LOG.
Member Function Documentation
bool cancel () final virtual
Cancel the request
Routine is called by user, as part of the request interface.
Reimplemented from Request.
Definition at line 94 of file linuxaio_request.cpp.
References LinuxaioQueue::CancelRequest(), Request::file_, CountingPtr< Type, Deleter >::get(), Singleton< Instance, destroy_on_exit >::GetInstance(), and LOG.
bool cancel_aio ()
Cancel already posted request.
Definition at line 106 of file linuxaio_request.cpp.
References LinuxaioRequest::cb_, Request::file_, Singleton< Instance, destroy_on_exit >::GetInstance(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::io_context(), and LOG.
void completed (bool posted, bool canceled)
Definition at line 29 of file linuxaio_request.cpp.
References Request::bytes_, Request::completed(), Singleton< Stats >::GetInstance(), LOG, Request::READ, and Request::type_.
void completed (bool canceled) inline final virtual
called by file implementations when the request completes
Reimplemented from Request.
Definition at line 58 of file linuxaio_request.hpp.
References LinuxaioRequest::completed().
Referenced by LinuxaioRequest::completed().
void fill_control_block () private
Definition at line 50 of file linuxaio_request.cpp.
References Request::buffer_, Request::bytes_, LinuxaioRequest::cb_, Request::file_, UfsFileBase::file_des_, CountingPtr< Type, Deleter >::get(), Request::offset_, Request::READ, and Request::type_.
Referenced by LinuxaioRequest::post().
bool post ()
Submits an I/O request to the OS
Returns
false if submission fails
Definition at line 66 of file linuxaio_request.cpp.
References Request::bytes_, LinuxaioRequest::cb_, Request::file_, LinuxaioRequest::fill_control_block(), Singleton< Instance, destroy_on_exit >::GetInstance(), Singleton< Stats >::GetInstance(), LinuxaioQueue::io_context(), LOG, Request::READ, THRILL_THROW_ERRNO, thrill::io::timestamp(), and Request::type_.
Member Data Documentation
iocb cb_ private
control block of async request
Definition at line 36 of file linuxaio_request.hpp.
Referenced by LinuxaioRequest::cancel_aio(), LinuxaioRequest::fill_control_block(), and LinuxaioRequest::post().
The documentation for this class was generated from the following files:
thrill/io/linuxaio_request.hpp
thrill/io/linuxaio_request.cpp