Thrill: ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlockPool Class Reference
ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlockPool Class Reference
Detailed Description
template<typename TableItem, typename Key, typename Value, typename KeyExtractor, typename ReduceFunction, typename Emitter, const bool VolatileKey, typename ReduceConfig, typename IndexFunction, typename KeyEqualFunction = std::equal_to<Key>>
class thrill::core::ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlockPool
BucketBlockPool to stack allocated BucketBlocks.
Definition at line 552 of file reduce_bucket_hash_table.hpp.
#include <reduce_bucket_hash_table.hpp>
Public Member Functions
BucketBlockPool ()=default
BucketBlockPool (const BucketBlockPool &)=delete
non-copyable: delete copy-constructor
BucketBlockPool (BucketBlockPool &&)=default
move-constructor: default
~BucketBlockPool ()
void Deallocate (BucketBlock *o)
void Destroy ()
BucketBlock * GetBlock ()
BucketBlockPool & operator= (const BucketBlockPool &)=delete
non-copyable: delete assignment operator
BucketBlockPool & operator= (BucketBlockPool &&)=default
move-assignment operator: default
Private Attributes
std::stack< BucketBlock * > free
Constructor & Destructor Documentation
BucketBlockPool() [1/3]
BucketBlockPool () default
BucketBlockPool() [2/3]
BucketBlockPool (const BucketBlockPool &) delete
non-copyable: delete copy-constructor
BucketBlockPool() [3/3]
BucketBlockPool (BucketBlockPool &&) default
move-constructor: default
~BucketBlockPool()
~BucketBlockPool () inline
Definition at line 566 of file reduce_bucket_hash_table.hpp.
Member Function Documentation
Deallocate()
void Deallocate (BucketBlock * o) inline
Definition at line 587 of file reduce_bucket_hash_table.hpp.
References free(), ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlock::next, and ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlock::size.
Referenced by ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::FlushPartitionEmit(), and ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::SpillPartition().
Destroy()
void Destroy () inline
Definition at line 593 of file reduce_bucket_hash_table.hpp.
References free().
Referenced by ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::Dispose().
GetBlock()
BucketBlock* GetBlock () inline
Definition at line 571 of file reduce_bucket_hash_table.hpp.
References free(), ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlock::next, and ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::BucketBlock::size.
Referenced by ReduceBucketHashTable< TableItem, Key, Value, KeyExtractor, ReduceFunction, Emitter, VolatileKey, ReduceConfig, IndexFunction, KeyEqualFunction >::Insert().
operator=() [1/2]
BucketBlockPool& operator= (const BucketBlockPool &) delete
non-copyable: delete assignment operator
operator=() [2/2]
BucketBlockPool& operator= (BucketBlockPool &&) default
move-assignment operator: default
Member Data Documentation
free
std::stack<BucketBlock*> free private
Definition at line 603 of file reduce_bucket_hash_table.hpp.
The documentation for this class was generated from the following file:
thrill/core/reduce_bucket_hash_table.hpp