Thrill: BufferReader Class Reference
BufferReader Class Reference
Network Subsystem Layer
Detailed Description
BufferReader represents a BufferRef with an additional cursor with which the memory can be read incrementally.
Definition at line 34 of file buffer_reader.hpp.
#include <buffer_reader.hpp>
Public Member Functions
Construction
BufferReader (const BufferRef &br)
Constructor, assign memory area from BinaryBuilder.
BufferReader (const void *data, size_t n)
Constructor, assign memory area from pointer and length.
BufferReader (const std::string &str)
Constructor, assign memory area from string, does NOT copy.
Size Accessors
size_t cursor () const
Return the current read cursor.
bool available (size_t size) const
Return the number of bytes still available at the cursor.
bool empty () const
Return true if the cursor is at the end of the buffer.
size_t Size () const
bool IsNull () const
Indicates if the reader was initialized with a nullptr and size 0.
Cursor Movement and Checks
BufferReader & Rewind ()
Reset the read cursor.
void CheckAvailable (size_t n) const
BufferReader & Skip (size_t n)
Advance the cursor given number of bytes without reading them.
Cursor Reading Methods
BufferReader & Read (void *outdata, size_t datalen)
std::string Read (size_t datalen)
template<typename Type >
Type Get ()
Byte GetByte ()
Fetch a single byte from the buffer, advancing the cursor.
template<typename Type >
Type GetRaw ()
BufferRef GetBufferRef ()
Public Member Functions inherited from BufferRef
BufferRef (const BufferBuilder &bb)
Constructor, assign memory area from BufferBuilder.
BufferRef (const void *data, size_t size)
Constructor, assign memory area from pointer and length.
BufferRef (const std::string &str)
Constructor, assign memory area from string, does NOT copy.
BufferRef (const Buffer &b)
Constructor, assign memory area from net::Buffer, does NOT copy!
const void * data () const
Return a pointer to the currently kept memory area.
bool operator!= (const BufferRef &br) const noexcept
Compare contents of two BufferRefs.
bool operator== (const BufferRef &br) const noexcept
Compare contents of two BufferRefs.
size_t size () const
Return the currently valid length in bytes.
Buffer ToBuffer ()
Explicit conversion to Buffer MOVING the memory ownership.
std::string ToString () const
Explicit conversion to std::string (copies memory of course).
Public Member Functions inherited from ItemReaderToolsBase< BufferReader >
std::string GetString ()
Fetch a string which was Put via Put_string().
uint64_t GetVarint ()
Fetch a 64-bit varint from the reader at the cursor.
uint32_t GetVarint32 ()
Fetch a varint with up to 32-bit from the reader at the cursor.
Private Attributes
size_t cursor_ = 0
Current read cursor.
Additional Inherited Members
Protected Types inherited from BufferRef
using Byte = unsigned char
type used to store the bytes
Protected Attributes inherited from BufferRef
const Byte * data_
Allocated buffer pointer.
size_t size_
Size of valid data.
Constructor & Destructor Documentation
BufferReader (const BufferRef & br) inline
Constructor, assign memory area from BinaryBuilder.
Definition at line 47 of file buffer_reader.hpp.
BufferReader (const void * data, size_t n) inline
Constructor, assign memory area from pointer and length.
Definition at line 52 of file buffer_reader.hpp.
BufferReader (const std::string & str) inline explicit
Constructor, assign memory area from string, does NOT copy.
Definition at line 57 of file buffer_reader.hpp.
Member Function Documentation
bool available (size_t size) const inline
Return the number of bytes still available at the cursor.
Definition at line 72 of file buffer_reader.hpp.
References BufferReader::cursor_, and BufferRef::size_.
Referenced by BufferReader::CheckAvailable().
void CheckAvailable (size_t n) const inline
Throws a std::underflow_error unless n bytes are available at the cursor.
Definition at line 103 of file buffer_reader.hpp.
References BufferReader::available().
Referenced by BufferReader::Get(), BufferReader::Read(), and BufferReader::Skip().
size_t cursor () const inline
Return the current read cursor.
Definition at line 67 of file buffer_reader.hpp.
References BufferReader::cursor_.
bool empty () const inline
Return true if the cursor is at the end of the buffer.
Definition at line 77 of file buffer_reader.hpp.
References BufferReader::cursor_, and BufferRef::size_.
Type Get () inline
Fetch a single item of the template type Type from the buffer, advancing the cursor. Be careful with implicit type conversions!
Definition at line 146 of file buffer_reader.hpp.
References BufferReader::CheckAvailable(), BufferReader::cursor_, and BufferRef::data_.
Referenced by StreamMultiplexerHeader::Parse(), and PartitionMultiplexerHeader::Parse().
BufferRef GetBufferRef () inline
Fetch a BufferRef to a binary string or blob which was Put via Put_string(). Does NOT copy the data.
Definition at line 173 of file buffer_reader.hpp.
References BufferReader::cursor_, BufferRef::data_, ItemReaderToolsBase< BufferReader >::GetVarint(), and BufferReader::Skip().
Byte GetByte () inline
Fetch a single byte from the buffer, advancing the cursor.
Definition at line 160 of file buffer_reader.hpp.
Type GetRaw () inline
Fetch a single item of the template type Type from the buffer, advancing the cursor. Be careful with implicit type conversions!
Definition at line 167 of file buffer_reader.hpp.
bool IsNull () const inline
Indicates if the reader was initialized with a nullptr and size 0.
Definition at line 86 of file buffer_reader.hpp.
References BufferRef::data_.
BufferReader& Read (void * outdata, size_t datalen) inline
Fetch a number of unstructured bytes from the buffer, advancing the cursor.
Definition at line 123 of file buffer_reader.hpp.
References BufferReader::CheckAvailable(), BufferReader::cursor_, and BufferRef::data_.
std::string Read (size_t datalen) inline
Fetch a number of unstructured bytes from the buffer as std::string, advancing the cursor.
Definition at line 135 of file buffer_reader.hpp.
References BufferReader::CheckAvailable(), BufferReader::cursor_, and BufferRef::data_.
BufferReader& Rewind () inline
Reset the read cursor.
Definition at line 96 of file buffer_reader.hpp.
References BufferReader::cursor_.
size_t Size () const inline
Definition at line 81 of file buffer_reader.hpp.
References BufferRef::size_.
BufferReader& Skip (size_t n) inline
Advance the cursor given number of bytes without reading them.
Definition at line 109 of file buffer_reader.hpp.
References BufferReader::CheckAvailable(), and BufferReader::cursor_.
Referenced by BufferReader::GetBufferRef().
Member Data Documentation
size_t cursor_ = 0 private
Current read cursor.
Definition at line 40 of file buffer_reader.hpp.
Referenced by BufferReader::available(), BufferReader::cursor(), BufferReader::empty(), BufferReader::Get(), BufferReader::GetBufferRef(), BufferReader::Read(), BufferReader::Rewind(), and BufferReader::Skip().
The documentation for this class was generated from the following file:
thrill/net/buffer_reader.hpp