Thrill: SplayzTree< Key > Class Template Reference
SplayzTree< Key > Class Template Reference
Detailed Description
template<typename Key>
class thrill::common::SplayzTree< Key >
Definition at line 477 of file splay_tree.hpp.
#include <splay_tree.hpp>
Classes
struct Node
struct NodeCompare
Public Member Functions
bool erase (const Key &k)
bool exists (const Key &k)
Node * find (const Key &k)
bool insert (const Key &k)
insert key into tree if it does not exist, returns true if inserted.
const Node * rank (size_t i) const
template<typename Functor >
void traverse_preorder (const Functor &f) const
Public Attributes
Node * root_ = nullptr
Member Function Documentation
bool erase (const Key & k) inline
Definition at line 519 of file splay_tree.hpp.
References SplayzTree< Key >::root_, and thrill::common::splayz_erase().
bool exists (const Key & k) inline
Definition at line 526 of file splay_tree.hpp.
References SplayzTree< Key >::Node::key, SplayzTree< Key >::root_, and thrill::common::splayz().
Node* find (const Key & k) inline
Definition at line 535 of file splay_tree.hpp.
References SplayzTree< Key >::root_, and thrill::common::splayz().
bool insert (const Key & k) inline
insert key into tree if it does not exist, returns true if inserted.
Definition at line 504 of file splay_tree.hpp.
References SplayzTree< Key >::root_, thrill::common::splayz(), and thrill::common::splayz_insert().
const Node* rank (size_t i) const inline
Definition at line 531 of file splay_tree.hpp.
References SplayzTree< Key >::root_, and thrill::common::splayz_rank().
void traverse_preorder (const Functor & f) const inline
Definition at line 540 of file splay_tree.hpp.
References SplayzTree< Key >::Node::key, SplayzTree< Key >::root_, and thrill::common::splayz_traverse_preorder().
Member Data Documentation
Node* root_ = nullptr
Definition at line 501 of file splay_tree.hpp.
Referenced by SplayzTree< Key >::erase(), SplayzTree< Key >::exists(), SplayzTree< Key >::find(), SplayzTree< Key >::insert(), SplayzTree< Key >::rank(), and SplayzTree< Key >::traverse_preorder().
The documentation for this class was generated from the following file:
thrill/common/splay_tree.hpp