Thrill: MemoryConfig Class Reference
MemoryConfig Class Reference
Detailed Description
Definition at line 48 of file context.hpp.
#include <context.hpp>
Public Member Functions
void apply ()
MemoryConfig divide (size_t hosts) const
void print (size_t workers_per_host) const
void setup (size_t ram)
setup memory size
int setup_detect ()
detect memory configuration from environment
Public Attributes
size_t ram_
total amount of physical ram detected or THRILL_RAM
size_t ram_block_pool_hard_
amount of RAM dedicated to data::BlockPool – hard limit
size_t ram_block_pool_soft_
amount of RAM dedicated to data::BlockPool – soft limit
size_t ram_floating_
remaining free-floating RAM used for user and Thrill data structures.
size_t ram_workers_
bool verbose_ = true
StageBuilder verbosity flag.
Member Function Documentation
void apply ()
Definition at line 994 of file context.cpp.
References MemoryConfig::ram_, MemoryConfig::ram_block_pool_hard_, MemoryConfig::ram_block_pool_soft_, MemoryConfig::ram_floating_, MemoryConfig::ram_workers_, and thrill::mem::set_memory_limit_indication().
Referenced by MemoryConfig::setup(), and MemoryConfig::setup_detect().
MemoryConfig divide (size_t hosts) const
Definition at line 1007 of file context.cpp.
References MemoryConfig::ram_, MemoryConfig::ram_block_pool_hard_, MemoryConfig::ram_block_pool_soft_, and MemoryConfig::ram_workers_.
Referenced by thrill::api::RunLoopbackThreads().
void print (size_t workers_per_host) const
Definition at line 1019 of file context.cpp.
References tlx::format_iec_units(), MemoryConfig::ram_, MemoryConfig::ram_block_pool_hard_, MemoryConfig::ram_floating_, MemoryConfig::ram_workers_, and MemoryConfig::verbose_.
Referenced by thrill::api::RunBackendLoopback(), thrill::api::RunLocalSameThread(), and thrill::api::RunLoopbackThreads().
void setup (size_t ram)
setup memory size
Definition at line 930 of file context.cpp.
References MemoryConfig::apply(), and MemoryConfig::ram_.
Referenced by HostContext::ConstructLoopback(), thrill::api::RunLocalSameThread(), and thrill::api::RunLocalTests().
int setup_detect ()
detect memory configuration from environment
Definition at line 935 of file context.cpp.
References MemoryConfig::apply(), tlx::parse_si_iec_units(), MemoryConfig::ram_, and sLOG1.
Referenced by thrill::api::RunBackendLoopback().
Member Data Documentation
size_t ram_
total amount of physical ram detected or THRILL_RAM
Definition at line 63 of file context.hpp.
Referenced by MemoryConfig::apply(), MemoryConfig::divide(), MemoryConfig::print(), MemoryConfig::setup(), and MemoryConfig::setup_detect().
size_t ram_block_pool_hard_
amount of RAM dedicated to data::BlockPool – hard limit
Definition at line 66 of file context.hpp.
Referenced by MemoryConfig::apply(), MemoryConfig::divide(), and MemoryConfig::print().
size_t ram_block_pool_soft_
amount of RAM dedicated to data::BlockPool – soft limit
Definition at line 69 of file context.hpp.
Referenced by MemoryConfig::apply(), and MemoryConfig::divide().
size_t ram_floating_
remaining free-floating RAM used for user and Thrill data structures.
Definition at line 76 of file context.hpp.
Referenced by MemoryConfig::apply(), and MemoryConfig::print().
size_t ram_workers_
total amount of RAM for DIANode data structures such as the reduce tables. divide by the number of worker threads before use.
Definition at line 73 of file context.hpp.
Referenced by MemoryConfig::apply(), MemoryConfig::divide(), MemoryConfig::print(), and HostContext::worker_mem_limit().
bool verbose_ = true
StageBuilder verbosity flag.
Definition at line 79 of file context.hpp.
Referenced by HostContext::ConstructLoopback(), MemoryConfig::print(), thrill::api::RunLocalSameThread(), and thrill::api::RunLocalTests().
The documentation for this class was generated from the following files:
thrill/api/context.hpp
thrill/api/context.cpp