Thrill: file_stats Class Reference
file_stats Class Reference
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management » I/O Primitives Layer
Detailed Description
Definition at line 45 of file iostats.hpp.
#include <iostats.hpp>
Classes
class scoped_read_timer
class scoped_read_write_timer
class scoped_write_timer
Public Member Functions
file_stats (unsigned int device_id)
construct zero initialized
unsigned get_device_id () const
external_size_type get_read_bytes () const
unsigned get_read_count () const
double get_read_time () const
external_size_type get_write_bytes () const
unsigned get_write_count () const
double get_write_time () const
void read_canceled (const size_t size_)
void read_finished ()
void read_op_finished (const size_t size_, double duration)
void read_started (const size_t size_, double now=0.0)
void write_canceled (const size_t size_)
void write_finished ()
void write_op_finished (const size_t size_, double duration)
void write_started (const size_t size_, double now=0.0)
Private Attributes
int acc_reads_
number of requests, participating in parallel operation
int acc_writes_
const unsigned device_id_
associated device id
double p_begin_read_
start time of parallel operation
double p_begin_write_
external_size_type read_bytes_
number of bytes read/written
unsigned read_count_
number of operations: read/write
std::mutex read_mutex_
double read_time_
seconds spent in operations
external_size_type write_bytes_
unsigned write_count_
std::mutex write_mutex_
double write_time_
Constructor & Destructor Documentation
file_stats()
file_stats (unsigned int device_id) explicit
construct zero initialized
Definition at line 35 of file iostats.cpp.
Member Function Documentation
get_device_id()
unsigned get_device_id () const inline
Returns the device id.
Returns
device id
Definition at line 187 of file iostats.hpp.
References file_stats::device_id_.
get_read_bytes()
external_size_type get_read_bytes () const inline
Returns number of bytes read from disks.
Returns
number of bytes read
Definition at line 208 of file iostats.hpp.
References file_stats::read_bytes_.
Referenced by stats_data::stats_data().
get_read_count()
unsigned get_read_count () const inline
Returns total number of read_count_.
Returns
total number of read_count_
Definition at line 194 of file iostats.hpp.
References file_stats::read_count_.
Referenced by stats_data::stats_data().
get_read_time()
double get_read_time () const inline
Time that would be spent in read syscalls if all parallel read_count_ were serialized.
Returns
seconds spent in reading
Definition at line 223 of file iostats.hpp.
References file_stats::read_time_.
Referenced by stats_data::stats_data().
get_write_bytes()
external_size_type get_write_bytes () const inline
Returns number of bytes written to the disks.
Returns
number of bytes written
Definition at line 215 of file iostats.hpp.
References file_stats::write_bytes_.
Referenced by stats_data::stats_data().
get_write_count()
unsigned get_write_count () const inline
Returns total number of write_count_.
Returns
total number of write_count_
Definition at line 201 of file iostats.hpp.
References file_stats::write_count_.
Referenced by stats_data::stats_data().
get_write_time()
double get_write_time () const inline
Time that would be spent in write syscalls if all parallel write_count_ were serialized.
Returns
seconds spent in writing
Definition at line 231 of file iostats.hpp.
References file_stats::read_canceled(), file_stats::read_finished(), file_stats::read_op_finished(), file_stats::read_started(), file_stats::write_canceled(), file_stats::write_finished(), file_stats::write_op_finished(), file_stats::write_started(), and file_stats::write_time_.
Referenced by stats_data::stats_data().
read_canceled()
void read_canceled (const size_t size_)
Definition at line 115 of file iostats.cpp.
References file_stats::read_bytes_, file_stats::read_count_, file_stats::read_finished(), and file_stats::read_mutex_.
Referenced by file_stats::get_write_time().
read_finished()
void read_finished ()
Definition at line 126 of file iostats.cpp.
References file_stats::acc_reads_, singleton< stats >::get_instance(), file_stats::p_begin_read_, stats::p_read_finished(), file_stats::read_mutex_, file_stats::read_time_, and foxxll::timestamp().
Referenced by file_stats::get_write_time(), file_stats::read_canceled(), file_stats::scoped_read_write_timer::stop(), and file_stats::scoped_read_timer::stop().
read_op_finished()
void read_op_finished (const size_t size_, double duration)
Definition at line 141 of file iostats.cpp.
References file_stats::read_bytes_, file_stats::read_count_, file_stats::read_mutex_, and file_stats::read_time_.
Referenced by file_stats::get_write_time().
read_started()
void read_started (const size_t size_, double now = 0.0)
Definition at line 97 of file iostats.cpp.
References file_stats::acc_reads_, singleton< stats >::get_instance(), file_stats::p_begin_read_, stats::p_read_started(), file_stats::read_bytes_, file_stats::read_count_, file_stats::read_mutex_, file_stats::read_time_, and foxxll::timestamp().
Referenced by file_stats::get_write_time(), file_stats::scoped_read_write_timer::start(), and file_stats::scoped_read_timer::start().
write_canceled()
void write_canceled (const size_t size_)
Definition at line 62 of file iostats.cpp.
References file_stats::write_bytes_, file_stats::write_count_, file_stats::write_finished(), and file_stats::write_mutex_.
Referenced by file_stats::get_write_time().
write_finished()
void write_finished ()
Definition at line 73 of file iostats.cpp.
References file_stats::acc_writes_, singleton< stats >::get_instance(), file_stats::p_begin_write_, stats::p_write_finished(), foxxll::timestamp(), file_stats::write_mutex_, and file_stats::write_time_.
Referenced by file_stats::get_write_time(), file_stats::scoped_read_write_timer::stop(), file_stats::scoped_write_timer::stop(), and file_stats::write_canceled().
write_op_finished()
void write_op_finished (const size_t size_, double duration)
Definition at line 88 of file iostats.cpp.
References file_stats::write_bytes_, file_stats::write_count_, file_stats::write_mutex_, and file_stats::write_time_.
Referenced by file_stats::get_write_time().
write_started()
void write_started (const size_t size_, double now = 0.0)
Definition at line 44 of file iostats.cpp.
References file_stats::acc_writes_, singleton< stats >::get_instance(), file_stats::p_begin_write_, stats::p_write_started(), foxxll::timestamp(), file_stats::write_bytes_, file_stats::write_count_, file_stats::write_mutex_, and file_stats::write_time_.
Referenced by file_stats::get_write_time(), file_stats::scoped_read_write_timer::start(), and file_stats::scoped_write_timer::start().
Member Data Documentation
acc_reads_
int acc_reads_ private
number of requests, participating in parallel operation
Definition at line 60 of file iostats.hpp.
Referenced by file_stats::read_finished(), and file_stats::read_started().
acc_writes_
int acc_writes_ private
Definition at line 60 of file iostats.hpp.
Referenced by file_stats::write_finished(), and file_stats::write_started().
device_id_
const unsigned device_id_ private
associated device id
Definition at line 48 of file iostats.hpp.
Referenced by file_stats::get_device_id(), file_stats_data::get_device_id(), file_stats_data::operator+(), and file_stats_data::operator-().
p_begin_read_
double p_begin_read_ private
start time of parallel operation
Definition at line 57 of file iostats.hpp.
Referenced by file_stats::read_finished(), and file_stats::read_started().
p_begin_write_
double p_begin_write_ private
Definition at line 57 of file iostats.hpp.
Referenced by file_stats::write_finished(), and file_stats::write_started().
read_bytes_
external_size_type read_bytes_ private
number of bytes read/written
Definition at line 53 of file iostats.hpp.
Referenced by file_stats::get_read_bytes(), file_stats_data::get_read_bytes(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::read_canceled(), file_stats::read_op_finished(), and file_stats::read_started().
read_count_
unsigned read_count_ private
number of operations: read/write
Definition at line 51 of file iostats.hpp.
Referenced by file_stats::get_read_count(), file_stats_data::get_read_count(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::read_canceled(), file_stats::read_op_finished(), and file_stats::read_started().
read_mutex_
std::mutex read_mutex_ private
Definition at line 62 of file iostats.hpp.
Referenced by file_stats::read_canceled(), file_stats::read_finished(), file_stats::read_op_finished(), and file_stats::read_started().
read_time_
double read_time_ private
seconds spent in operations
Definition at line 55 of file iostats.hpp.
Referenced by file_stats::get_read_time(), file_stats_data::get_read_time(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::read_finished(), file_stats::read_op_finished(), and file_stats::read_started().
write_bytes_
external_size_type write_bytes_ private
Definition at line 53 of file iostats.hpp.
Referenced by file_stats::get_write_bytes(), file_stats_data::get_write_bytes(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::write_canceled(), file_stats::write_op_finished(), and file_stats::write_started().
write_count_
unsigned write_count_ private
Definition at line 51 of file iostats.hpp.
Referenced by file_stats::get_write_count(), file_stats_data::get_write_count(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::write_canceled(), file_stats::write_op_finished(), and file_stats::write_started().
write_mutex_
std::mutex write_mutex_ private
Definition at line 62 of file iostats.hpp.
Referenced by file_stats::write_canceled(), file_stats::write_finished(), file_stats::write_op_finished(), and file_stats::write_started().
write_time_
double write_time_ private
Definition at line 55 of file iostats.hpp.
Referenced by file_stats::get_write_time(), file_stats_data::get_write_time(), file_stats_data::operator+(), file_stats_data::operator-(), file_stats::write_finished(), file_stats::write_op_finished(), and file_stats::write_started().
The documentation for this class was generated from the following files:
extlib/foxxll/foxxll/io/iostats.hpp
extlib/foxxll/foxxll/io/iostats.cpp