Thrill: file_stats::scoped_read_write_timer Class Reference
file_stats::scoped_read_write_timer Class Reference
Detailed Description
Definition at line 68 of file iostats.hpp.
#include <iostats.hpp>
Public Member Functions
scoped_read_write_timer (file_stats *file_stats, size_type size, bool is_write=false)
~scoped_read_write_timer ()
void start (size_type size)
void stop ()
Private Types
using size_type = size_t
Private Attributes
file_stats & file_stats_
bool is_write_
bool running_ = false
Member Typedef Documentation
size_type
using size_type = size_t private
Definition at line 70 of file iostats.hpp.
Constructor & Destructor Documentation
scoped_read_write_timer()
scoped_read_write_timer (file_stats * file_stats, size_type size, bool is_write = false) inline explicit
Definition at line 77 of file iostats.hpp.
References file_stats::scoped_read_write_timer::start().
~scoped_read_write_timer()
~scoped_read_write_timer () inline
Definition at line 84 of file iostats.hpp.
References file_stats::scoped_read_write_timer::stop().
Member Function Documentation
start()
void start (size_type size) inline
Definition at line 89 of file iostats.hpp.
References file_stats::read_started(), and file_stats::write_started().
Referenced by file_stats::scoped_read_timer::scoped_read_timer(), file_stats::scoped_read_write_timer::scoped_read_write_timer(), stats::scoped_wait_timer::scoped_wait_timer(), and file_stats::scoped_write_timer::scoped_write_timer().
stop()
void stop () inline
Definition at line 100 of file iostats.hpp.
References file_stats::read_finished(), and file_stats::write_finished().
Referenced by file_stats::scoped_read_timer::~scoped_read_timer(), file_stats::scoped_read_write_timer::~scoped_read_write_timer(), stats::scoped_wait_timer::~scoped_wait_timer(), and file_stats::scoped_write_timer::~scoped_write_timer().
Member Data Documentation
file_stats_
file_stats& file_stats_ private
Definition at line 71 of file iostats.hpp.
is_write_
bool is_write_ private
Definition at line 73 of file iostats.hpp.
running_
bool running_ = false private
Definition at line 74 of file iostats.hpp.
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/io/iostats.hpp