Thrill: WriteLinesOneNode< ValueType > Class Template Reference
WriteLinesOneNode< ValueType > Class Template Reference final
Thrill Layers » DIA API Layer
Detailed Description
template<typename ValueType>
class thrill::api::WriteLinesOneNode< ValueType >
Definition at line 31 of file write_lines_one.hpp.
#include <write_lines_one.hpp>
Public Types
using Super = ActionNode
Public Types inherited from DIABase
using DIABasePtr = tlx::CountingPtr< DIABase >
Public Member Functions
template<typename ParentDIA >
WriteLinesOneNode (const ParentDIA &parent, const std::string &path_out)
void Execute () final
Closes the output file.
void PreOp (const ValueType &input)
void StopPreOp (size_t) final
Virtual method for preparing end of PushData.
Public Member Functions inherited from ActionNode
ActionNode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
std::vector< DIABase * > children () const final
ActionNodes do not have children.
void DecConsumeCounter (size_t) final
void IncConsumeCounter (size_t) final
void PushData (bool) final
ActionNodes do not push data, they only Execute.
void RemoveAllChildren () final
ActionNodes do not have children.
void RemoveChild (DIABase *) final
ActionNodes do not have children.
void RunPushData () final
ActionNodes do not push data, they only Execute.
void SetConsumeCounter (size_t) final
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
const size_t & dia_id () const
return unique id of DIANode subclass as stored by StatsNode
virtual bool ForwardDataOnly () const
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
DIAState state () const
virtual DIAMemUse PreOpMemUse ()
Amount of RAM used by PreOp after StartPreOp()
virtual void StartPreOp (size_t)
Virtual method for preparing start of PushData.
virtual bool OnPreOpFile (const data::File &, size_t)
virtual DIAMemUse ExecuteMemUse ()
Amount of RAM used by Execute()
virtual DIAMemUse PushDataMemUse ()
Amount of RAM used by PushData()
virtual void Dispose ()
Virtual clear method. Triggers actual disposing in sub-classes.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Attributes
std::ofstream file_
File to write to.
size_t local_lines_ = 0
size_t local_size_ = 0
Local file size.
std::string path_out_
Path of the output file.
data::File temp_file_ { context_.GetFile(this) }
Temporary File for splitting correctly?
data::File::Writer writer_ { temp_file_.GetWriter() }
File writer used.
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Protected Attributes inherited from DIABase
Context & context_
associated Context
const size_t dia_id_
DIA serial id.
const char *const label_
DOp node static label.
DIAState state_ = DIAState::NEW
State of the DIANode. State is NEW on creation.
std::vector< DIABasePtr > parents_
Parents of this DIABase.
DIAMemUse mem_limit_ = 0
size_t consume_counter_ = 1
Member Typedef Documentation
Super
using Super = ActionNode
Definition at line 36 of file write_lines_one.hpp.
Constructor & Destructor Documentation
WriteLinesOneNode()
WriteLinesOneNode (const ParentDIA & parent, const std::string & path_out) inline
Definition at line 40 of file write_lines_one.hpp.
References WriteLinesOneNode< ValueType >::file_, WriteLinesOneNode< ValueType >::path_out_, WriteLinesOneNode< ValueType >::PreOp(), and sLOG.
Member Function Documentation
Execute()
void Execute () inline final virtual
Closes the output file.
Implements DIABase.
Definition at line 68 of file write_lines_one.hpp.
References FlowControlChannel::Barrier(), DIABase::context_, FlowControlChannel::ExPrefixSum(), WriteLinesOneNode< ValueType >::file_, File::GetConsumeReader(), WriteLinesOneNode< ValueType >::local_lines_, WriteLinesOneNode< ValueType >::local_size_, DIABase::logger_, Context::my_rank(), Context::net, BlockReader< BlockSource >::Next(), File::num_items(), Context::num_workers(), and WriteLinesOneNode< ValueType >::temp_file_.
PreOp()
void PreOp (const ValueType & input) inline
Definition at line 57 of file write_lines_one.hpp.
References WriteLinesOneNode< ValueType >::local_lines_, WriteLinesOneNode< ValueType >::local_size_, BlockWriter< BlockSink >::Put(), and WriteLinesOneNode< ValueType >::writer_.
Referenced by WriteLinesOneNode< ValueType >::WriteLinesOneNode().
StopPreOp()
void StopPreOp (size_t) inline final virtual
Virtual method for preparing end of PushData.
Reimplemented from DIABase.
Definition at line 63 of file write_lines_one.hpp.
References BlockWriter< BlockSink >::Close(), and WriteLinesOneNode< ValueType >::writer_.
Member Data Documentation
debug
constexpr bool debug = false static private
Definition at line 33 of file write_lines_one.hpp.
file_
std::ofstream file_ private
File to write to.
Definition at line 96 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::Execute(), and WriteLinesOneNode< ValueType >::WriteLinesOneNode().
local_lines_
size_t local_lines_ = 0 private
Definition at line 107 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::Execute(), and WriteLinesOneNode< ValueType >::PreOp().
local_size_
size_t local_size_ = 0 private
Local file size.
Definition at line 99 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::Execute(), and WriteLinesOneNode< ValueType >::PreOp().
path_out_
std::string path_out_ private
Path of the output file.
Definition at line 93 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::WriteLinesOneNode().
temp_file_
data::File temp_file_ { context_.GetFile(this) } private
Temporary File for splitting correctly?
Definition at line 102 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::Execute().
writer_
data::File::Writer writer_ { temp_file_.GetWriter() } private
File writer used.
Definition at line 105 of file write_lines_one.hpp.
Referenced by WriteLinesOneNode< ValueType >::PreOp(), and WriteLinesOneNode< ValueType >::StopPreOp().
The documentation for this class was generated from the following file:
thrill/api/write_lines_one.hpp