Thrill: numeric_limits< foxxll::uint_pair< HighType > > Class Template Reference
numeric_limits< foxxll::uint_pair< HighType > > Class Template Reference
Detailed Description
template<typename HighType>
class std::numeric_limits< foxxll::uint_pair< HighType > >
template class providing some numeric_limits fields for uint_pair types.
Definition at line 273 of file uint_types.hpp.
#include <uint_types.hpp>
Static Public Member Functions
static const foxxll::uint_pair< HighType > epsilon ()
epsilon is zero
static foxxll::uint_pair< HighType > lowest ()
return an uint_pair instance containing the smallest value possible
static foxxll::uint_pair< HighType > max ()
return an uint_pair instance containing the largest value possible
static foxxll::uint_pair< HighType > min ()
return an uint_pair instance containing the smallest value possible
static const foxxll::uint_pair< HighType > round_error ()
rounding error is zero
Static Public Attributes
static const int digits = foxxll::uint_pair<HighType>::digits
number of binary digits (bits) in uint_pair
static const bool has_infinity = false
no infinity
static const bool is_exact = true
unit_pair types contain exact integers
static const bool is_integer = true
uint_pair types are integers
static const bool is_signed = false
unit_pair types are unsigned
static const bool is_specialized = true
yes we have information about uint_pair
static const int max_exponent = 0
no exponent
static const int max_exponent10 = 0
no exponent
static const int min_exponent = 0
no exponent
static const int min_exponent10 = 0
no exponent
static const int radix = 2
unit_pair radix is binary
Member Function Documentation
epsilon()
static const foxxll::uint_pair<HighType> epsilon () inline static
epsilon is zero
Definition at line 307 of file uint_types.hpp.
lowest()
static foxxll::uint_pair<HighType> lowest () inline static
return an uint_pair instance containing the smallest value possible
Definition at line 288 of file uint_types.hpp.
References uint_pair< HighType >::min().
max()
static foxxll::uint_pair<HighType> max () inline static
return an uint_pair instance containing the largest value possible
Definition at line 284 of file uint_types.hpp.
References uint_pair< HighType >::max().
min()
static foxxll::uint_pair<HighType> min () inline static
return an uint_pair instance containing the smallest value possible
Definition at line 280 of file uint_types.hpp.
References uint_pair< HighType >::min().
round_error()
static const foxxll::uint_pair<HighType> round_error () inline static
rounding error is zero
Definition at line 311 of file uint_types.hpp.
Member Data Documentation
digits
const int digits = foxxll::uint_pair<HighType>::digits static
number of binary digits (bits) in uint_pair
Definition at line 304 of file uint_types.hpp.
has_infinity
const bool has_infinity = false static
no infinity
Definition at line 327 of file uint_types.hpp.
is_exact
const bool is_exact = true static
unit_pair types contain exact integers
Definition at line 298 of file uint_types.hpp.
is_integer
const bool is_integer = true static
uint_pair types are integers
Definition at line 295 of file uint_types.hpp.
is_signed
const bool is_signed = false static
unit_pair types are unsigned
Definition at line 292 of file uint_types.hpp.
is_specialized
const bool is_specialized = true static
yes we have information about uint_pair
Definition at line 277 of file uint_types.hpp.
max_exponent
const int max_exponent = 0 static
no exponent
Definition at line 321 of file uint_types.hpp.
max_exponent10
const int max_exponent10 = 0 static
no exponent
Definition at line 324 of file uint_types.hpp.
min_exponent
const int min_exponent = 0 static
no exponent
Definition at line 315 of file uint_types.hpp.
min_exponent10
const int min_exponent10 = 0 static
no exponent
Definition at line 318 of file uint_types.hpp.
radix
const int radix = 2 static
unit_pair radix is binary
Definition at line 301 of file uint_types.hpp.
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/common/uint_types.hpp