Thrill: FixedBufferBuilder< Capacity > Class Template Reference
FixedBufferBuilder< Capacity > Class Template Reference
Network Subsystem Layer
Detailed Description
template<size_t Capacity>
class thrill::net::FixedBufferBuilder< Capacity >
Represents a FIXED length area of memory, which can be modified by appending integral data types via Put() and other basic operations.
Definition at line 38 of file fixed_buffer_builder.hpp.
#include <fixed_buffer_builder.hpp>
Public Member Functions
Data, Size, and Capacity Accessors
const Byte * data () const
Return a pointer to the currently kept memory area.
Byte * data ()
Return a writeable pointer to the currently kept memory area.
size_t size () const
Return the currently used length in bytes.
size_t capacity () const
Return the currently allocated buffer capacity.
Buffer Growing, Clearing, and other Management
FixedBufferBuilder & Clear ()
Clears the memory contents, does not deallocate the memory.
FixedBufferBuilder & set_size (size_t n)
std::string ToString () const
Explicit conversion to std::string (copies memory of course).
Appending Write Functions
FixedBufferBuilder & Append (const void *data, size_t len)
Append a memory range to the buffer.
FixedBufferBuilder & AppendString (const std::string &s)
template<typename Type >
FixedBufferBuilder & Put (const Type &item)
FixedBufferBuilder & PutByte (Byte data)
Put a single byte to the buffer (used via CRTP from ItemWriterToolsBase)
template<typename Type >
FixedBufferBuilder & PutRaw (const Type &item)
Access
iterator begin ()
return mutable iterator to first element
const_iterator begin () const
return constant iterator to first element
iterator end ()
return mutable iterator beyond last element
const_iterator end () const
return constant iterator beyond last element
reference operator[] (size_t i)
return the i-th position of the vector
Public Member Functions inherited from ItemWriterToolsBase< FixedBufferBuilder< Capacity > >
FixedBufferBuilder< Capacity > & PutString (const char *data, size_t len)
Put a string by saving it's length followed by the data itself.
FixedBufferBuilder< Capacity > & PutString (const uint8_t *data, size_t len)
Put a string by saving it's length followed by the data itself.
FixedBufferBuilder< Capacity > & PutString (const std::string &str)
Put a string by saving it's length followed by the data itself.
FixedBufferBuilder< Capacity > & PutVarint (uint64_t v)
Append a varint to the writer.
FixedBufferBuilder< Capacity > & PutVarint32 (uint32_t v)
Append a varint to the writer.
Private Types
using Byte = unsigned char
type used to store the bytes
using const_iterator = const Byte *
simple pointer iterators
using const_reference = const Byte &
simple pointer references
using iterator = Byte *
simple pointer iterators
using reference = Byte &
simple pointer references
Private Attributes
std::array< Byte, Capacity > data_
Allocated buffer.
size_t size_ = 0
Size of valid data.
Member Typedef Documentation
using Byte = unsigned char private
type used to store the bytes
Definition at line 43 of file fixed_buffer_builder.hpp.
using const_iterator = const Byte * private
simple pointer iterators
Definition at line 48 of file fixed_buffer_builder.hpp.
using const_reference = const Byte & private
simple pointer references
Definition at line 52 of file fixed_buffer_builder.hpp.
using iterator = Byte * private
simple pointer iterators
Definition at line 46 of file fixed_buffer_builder.hpp.
using reference = Byte & private
simple pointer references
Definition at line 50 of file fixed_buffer_builder.hpp.
Member Function Documentation
FixedBufferBuilder& Append (const void * data, size_t len) inline
Append a memory range to the buffer.
Definition at line 115 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data(), FixedBufferBuilder< Capacity >::data_, and FixedBufferBuilder< Capacity >::size_.
Referenced by FixedBufferBuilder< Capacity >::AppendString().
FixedBufferBuilder& AppendString (const std::string & s) inline
Append to contents of a std::string, excluding the null (which isn't contained in the string size anyway).
Definition at line 127 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::Append().
iterator begin () inline
return mutable iterator to first element
Definition at line 164 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_.
Referenced by FixedBufferBuilder< Capacity >::operator[]().
const_iterator begin () const inline
return constant iterator to first element
Definition at line 167 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_.
size_t capacity () const inline
Return the currently allocated buffer capacity.
Definition at line 80 of file fixed_buffer_builder.hpp.
FixedBufferBuilder& Clear () inline
Clears the memory contents, does not deallocate the memory.
Definition at line 90 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::size_.
const Byte* data () const inline
Return a pointer to the currently kept memory area.
Definition at line 65 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_.
Referenced by FixedBufferBuilder< Capacity >::Append(), and FixedBufferBuilder< Capacity >::PutByte().
Byte* data () inline
Return a writeable pointer to the currently kept memory area.
Definition at line 70 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_.
iterator end () inline
return mutable iterator beyond last element
Definition at line 171 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_, and FixedBufferBuilder< Capacity >::size_.
const_iterator end () const inline
return constant iterator beyond last element
Definition at line 174 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_, and FixedBufferBuilder< Capacity >::size_.
reference operator[] (size_t i) inline
return the i-th position of the vector
Definition at line 178 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::begin(), and FixedBufferBuilder< Capacity >::size_.
FixedBufferBuilder& Put (const Type & item) inline
Put (append) a single item of the template type T to the buffer. Be careful with implicit type conversions!
Definition at line 134 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_, FixedBufferBuilder< Capacity >::size_, and gen_data::value.
FixedBufferBuilder& PutByte (Byte data) inline
Put a single byte to the buffer (used via CRTP from ItemWriterToolsBase)
Definition at line 147 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data().
FixedBufferBuilder& PutRaw (const Type & item) inline
Put (append) a single item of the template type T to the buffer. Be careful with implicit type conversions!
Definition at line 154 of file fixed_buffer_builder.hpp.
FixedBufferBuilder& set_size (size_t n) inline
Set the valid bytes in the buffer, use if the buffer is filled directly.
Definition at line 97 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::size_.
size_t size () const inline
Return the currently used length in bytes.
Definition at line 75 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::size_.
std::string ToString () const inline
Explicit conversion to std::string (copies memory of course).
Definition at line 105 of file fixed_buffer_builder.hpp.
References FixedBufferBuilder< Capacity >::data_, and FixedBufferBuilder< Capacity >::size_.
Member Data Documentation
std::array<Byte, Capacity> data_ private
Allocated buffer.
Definition at line 55 of file fixed_buffer_builder.hpp.
Referenced by FixedBufferBuilder< Capacity >::Append(), FixedBufferBuilder< Capacity >::begin(), FixedBufferBuilder< Capacity >::data(), FixedBufferBuilder< Capacity >::end(), FixedBufferBuilder< Capacity >::Put(), and FixedBufferBuilder< Capacity >::ToString().
size_t size_ = 0 private
Size of valid data.
Definition at line 58 of file fixed_buffer_builder.hpp.
Referenced by FixedBufferBuilder< Capacity >::Append(), FixedBufferBuilder< Capacity >::Clear(), FixedBufferBuilder< Capacity >::end(), FixedBufferBuilder< Capacity >::operator[](), FixedBufferBuilder< Capacity >::Put(), FixedBufferBuilder< Capacity >::set_size(), FixedBufferBuilder< Capacity >::size(), and FixedBufferBuilder< Capacity >::ToString().
The documentation for this class was generated from the following file:
thrill/net/fixed_buffer_builder.hpp