Thrill: RingBuffer< Type, Allocator > Class Template Reference
RingBuffer< Type, Allocator > Class Template Reference
Detailed Description
template<typename Type, typename Allocator = std::allocator<Type>>
class thrill::common::RingBuffer< Type, Allocator >
A ring (circular) buffer of static (non-growing) size allocated.
This data structure is mostly used by the DIA.Window() transformation.
Due to many modulo operations with capacity_, the capacity is rounded up to the next power of two, even for powers of two! This is because otherwise size() == end - begin == 0 after filling the ring buffer, and adding another size_ member requires more book-keeping.
Definition at line 33 of file ring_buffer.hpp.
#include <ring_buffer.hpp>
Public Types
using alloc_traits = std::allocator_traits< allocator_type >
using allocator_type = Allocator
using const_pointer = typename allocator_type::const_pointer
using const_reference = typename allocator_type::const_reference
using difference_type = typename allocator_type::difference_type
using pointer = typename allocator_type::pointer
using reference = typename allocator_type::reference
using size_type = typename allocator_type::size_type
using value_type = Type
Public Member Functions
RingBuffer (const Allocator &alloc=allocator_type())
RingBuffer (size_t max_size, const Allocator &alloc=allocator_type())
RingBuffer (const RingBuffer &srb)
copy-constructor: create new ring buffer
RingBuffer (RingBuffer &&)=default
move-constructor: default
~RingBuffer ()
void allocate (size_t max_size)
allocate buffer
void deallocate ()
deallocate buffer
RingBuffer & operator= (const RingBuffer &)=delete
non-copyable: delete assignment operator
RingBuffer & operator= (RingBuffer &&)=default
move-assignment operator: default
Modifiers
void push_back (const value_type &t)
add element at the end
void push_back (value_type &&t)
add element at the end
template<typename... Args>
void emplace_back (Args &&...args)
emplace element at the end
void push_front (const value_type &t)
add element at the beginning
void push_front (value_type &&t)
add element at the beginning
template<typename... Args>
void emplace_front (Args &&...args)
emplace element at the beginning
void pop_front ()
remove element at the beginning
void pop_back ()
remove element at the end
void clear ()
reset buffer contents
void copy_to (std::vector< value_type > &out) const
copy all element into the vector
void move_to (std::vector< value_type > &out)
move all element from the RingBuffer into the vector
Element access
reference operator[] (size_type i)
Returns a reference to the i-th element.
const_reference operator[] (size_type i) const
Returns a reference to the i-th element.
reference front ()
Returns a reference to the first element.
const_reference front () const
Returns a reference to the first element.
reference back ()
Returns a reference to the last element.
const_reference back () const
Returns a reference to the last element.
Capacity
size_type size () const noexcept
return the number of items in the buffer
size_t max_size () const noexcept
return the maximum number of items in the buffer.
size_t capacity () const noexcept
return actual capacity of the ring buffer.
bool empty () const noexcept
returns true if no items are in the buffer
Protected Attributes
allocator_type alloc_
used allocator
size_type begin_ = 0
iterator at current begin of ring buffer
size_t capacity_
Type * data_
the circular buffer of static size.
size_type end_ = 0
iterator at current begin of ring buffer
size_t mask_
one-bits mask for calculating modulo of capacity using AND-mask.
size_t max_size_
Member Typedef Documentation
using alloc_traits = std::allocator_traits<allocator_type>
Definition at line 39 of file ring_buffer.hpp.
using allocator_type = Allocator
Definition at line 37 of file ring_buffer.hpp.
using const_pointer = typename allocator_type::const_pointer
Definition at line 44 of file ring_buffer.hpp.
using const_reference = typename allocator_type::const_reference
Definition at line 42 of file ring_buffer.hpp.
using difference_type = typename allocator_type::difference_type
Definition at line 47 of file ring_buffer.hpp.
using pointer = typename allocator_type::pointer
Definition at line 43 of file ring_buffer.hpp.
using reference = typename allocator_type::reference
Definition at line 41 of file ring_buffer.hpp.
using size_type = typename allocator_type::size_type
Definition at line 46 of file ring_buffer.hpp.
using value_type = Type
Definition at line 36 of file ring_buffer.hpp.
Constructor & Destructor Documentation
RingBuffer (const Allocator & alloc = allocator_type()) inline explicit
Definition at line 54 of file ring_buffer.hpp.
RingBuffer (size_t max_size, const Allocator & alloc = allocator_type()) inline explicit
Definition at line 58 of file ring_buffer.hpp.
RingBuffer (const RingBuffer< Type, Allocator > & srb) inline
copy-constructor: create new ring buffer
Definition at line 67 of file ring_buffer.hpp.
RingBuffer (RingBuffer< Type, Allocator > &&) default
move-constructor: default
~RingBuffer () inline
Definition at line 86 of file ring_buffer.hpp.
Member Function Documentation
void allocate (size_t max_size) inline
allocate buffer
Definition at line 91 of file ring_buffer.hpp.
reference back () inline
Returns a reference to the last element.
Definition at line 221 of file ring_buffer.hpp.
const_reference back () const inline
Returns a reference to the last element.
Definition at line 226 of file ring_buffer.hpp.
size_t capacity () const inline noexcept
return actual capacity of the ring buffer.
Definition at line 247 of file ring_buffer.hpp.
void clear () inline
reset buffer contents
Definition at line 174 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::deallocate().
void copy_to (std::vector< value_type > & out) const inline
copy all element into the vector
Definition at line 180 of file ring_buffer.hpp.
Referenced by DisjointWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::PushData().
void deallocate () inline
deallocate buffer
Definition at line 100 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::~RingBuffer().
void emplace_back (Args &&... args) inline
emplace element at the end
Definition at line 128 of file ring_buffer.hpp.
Referenced by OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::PushData().
void emplace_front (Args &&... args) inline
emplace element at the beginning
Definition at line 152 of file ring_buffer.hpp.
bool empty () const inline noexcept
returns true if no items are in the buffer
Definition at line 252 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::back(), RingBuffer< Input >::front(), RingBuffer< Input >::move_to(), RingBuffer< Input >::pop_back(), and RingBuffer< Input >::pop_front().
reference front () inline
Returns a reference to the first element.
Definition at line 210 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::move_to().
const_reference front () const inline
Returns a reference to the first element.
Definition at line 215 of file ring_buffer.hpp.
size_t max_size () const inline noexcept
return the maximum number of items in the buffer.
Definition at line 242 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate().
void move_to (std::vector< value_type > & out) inline
move all element from the RingBuffer into the vector
Definition at line 186 of file ring_buffer.hpp.
Referenced by OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute(), and DisjointWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute().
RingBuffer& operator= (const RingBuffer< Type, Allocator > &) delete
non-copyable: delete assignment operator
RingBuffer& operator= (RingBuffer< Type, Allocator > &&) default
move-assignment operator: default
reference operator[] (size_type i) inline
Returns a reference to the i-th element.
Definition at line 199 of file ring_buffer.hpp.
const_reference operator[] (size_type i) const inline
Returns a reference to the i-th element.
Definition at line 204 of file ring_buffer.hpp.
void pop_back () inline
remove element at the end
Definition at line 167 of file ring_buffer.hpp.
void pop_front () inline
remove element at the beginning
Definition at line 160 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::clear(), RingBuffer< Input >::move_to(), and OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::PushData().
void push_back (const value_type & t) inline
add element at the end
Definition at line 112 of file ring_buffer.hpp.
Referenced by OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute(), DisjointWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute(), and RingBuffer< Input >::RingBuffer().
void push_back (value_type && t) inline
add element at the end
Definition at line 119 of file ring_buffer.hpp.
void push_front (const value_type & t) inline
add element at the beginning
Definition at line 136 of file ring_buffer.hpp.
void push_front (value_type && t) inline
add element at the beginning
Definition at line 143 of file ring_buffer.hpp.
size_type size () const inline noexcept
return the number of items in the buffer
Definition at line 237 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::copy_to(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::empty(), OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute(), DisjointWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::Execute(), RingBuffer< Input >::operator[](), RingBuffer< Input >::push_back(), RingBuffer< Input >::push_front(), OverlapWindowNode< ValueType, Input, WindowFunction, PartialWindowFunction >::PushData(), and RingBuffer< Input >::RingBuffer().
Member Data Documentation
allocator_type alloc_ protected
used allocator
Definition at line 264 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate(), RingBuffer< Input >::deallocate(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::pop_back(), RingBuffer< Input >::pop_front(), RingBuffer< Input >::push_back(), and RingBuffer< Input >::push_front().
size_type begin_ = 0 protected
iterator at current begin of ring buffer
Definition at line 277 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::clear(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::front(), RingBuffer< Input >::operator[](), RingBuffer< Input >::pop_back(), RingBuffer< Input >::pop_front(), RingBuffer< Input >::push_front(), and RingBuffer< Input >::size().
size_t capacity_ protected
capacity of data buffer. rounded up from max_size_ to next unequal power of two.
Definition at line 268 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate(), RingBuffer< Input >::capacity(), and RingBuffer< Input >::deallocate().
Type* data_ protected
the circular buffer of static size.
Definition at line 274 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate(), RingBuffer< Input >::back(), RingBuffer< Input >::deallocate(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::front(), RingBuffer< Input >::operator[](), RingBuffer< Input >::pop_back(), RingBuffer< Input >::pop_front(), RingBuffer< Input >::push_back(), and RingBuffer< Input >::push_front().
size_type end_ = 0 protected
iterator at current begin of ring buffer
Definition at line 280 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::back(), RingBuffer< Input >::clear(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::pop_back(), RingBuffer< Input >::push_back(), and RingBuffer< Input >::size().
size_t mask_ protected
one-bits mask for calculating modulo of capacity using AND-mask.
Definition at line 271 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate(), RingBuffer< Input >::back(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::operator[](), RingBuffer< Input >::pop_back(), RingBuffer< Input >::pop_front(), RingBuffer< Input >::push_back(), RingBuffer< Input >::push_front(), and RingBuffer< Input >::size().
size_t max_size_ protected
target max_size of circular buffer prescribed by the user. Never equal to the data_.size(), which is rounded up to a power of two.
Definition at line 261 of file ring_buffer.hpp.
Referenced by RingBuffer< Input >::allocate(), RingBuffer< Input >::emplace_back(), RingBuffer< Input >::emplace_front(), RingBuffer< Input >::max_size(), RingBuffer< Input >::push_back(), and RingBuffer< Input >::push_front().
The documentation for this class was generated from the following file:
thrill/common/ring_buffer.hpp