Thrill: PinnedByteBlockPtr Class Reference
PinnedByteBlockPtr Class Reference
Data Subsystem Layer
Detailed Description
A pinned / pin-counted pointer to a ByteBlock.
By holding a pin, it is a guaranteed that the ByteBlock's underlying memory is loaded in RAM. Since pins are counted per thread, the PinnedByteBlockPtr is a counting pointer plus a thread id.
Be careful to move PinnedByteBlockPtr as must as possible, since copying costs a pinning and an unpinning operation, whereas moving is free.
Definition at line 205 of file byte_block.hpp.
#include <byte_block.hpp>
Public Member Functions
PinnedByteBlockPtr () noexcept=default
default ctor: contains a nullptr pointer.
PinnedByteBlockPtr (const PinnedByteBlockPtr &pbb) noexcept
copy-ctor: increment underlying's pin count
PinnedByteBlockPtr (PinnedByteBlockPtr &&pbb) noexcept
move-ctor: move underlying's pin
~PinnedByteBlockPtr ()
destructor: remove pin
size_t local_worker_id () const
local worker id of holder of pin
PinnedByteBlockPtr & operator= (PinnedByteBlockPtr &pbb) noexcept
copy-assignment: transfer underlying's pin count
PinnedByteBlockPtr & operator= (PinnedByteBlockPtr &&pbb) noexcept
move-assignment: move underlying's pin
ByteBlockPtr ReleasePin ()&&
relinquish pin
Public Member Functions inherited from ByteBlockPtr
ByteBlockPtr ()=default
default ctor: returns an empty ByteBlockPtr
Public Member Functions inherited from CountingPtr< Type, Deleter >
CountingPtr () noexcept
default constructor: contains a nullptr pointer.
CountingPtr (std::nullptr_t) noexcept
implicit conversion from nullptr_t: contains a nullptr pointer.
CountingPtr (Type *ptr) noexcept
constructor from pointer: initializes new reference to ptr.
CountingPtr (const CountingPtr &other) noexcept
copy-constructor: also initializes new reference to ptr.
template<typename Subclass , typename = typename std::enable_if< std::is_convertible<Subclass*, Type*>::value, void>::type>
CountingPtr (const CountingPtr< Subclass, Deleter > &other) noexcept
copy-constructor: also initializes new reference to ptr.
CountingPtr (CountingPtr &&other) noexcept
move-constructor: just moves pointer, does not change reference counts.
template<typename Subclass , typename = typename std::enable_if< std::is_convertible<Subclass*, Type*>::value, void>::type>
CountingPtr (CountingPtr< Subclass, Deleter > &&other) noexcept
move-constructor: just moves pointer, does not change reference counts.
CountingPtr & operator= (const CountingPtr &other) noexcept
template<typename Subclass , typename = typename std::enable_if< std::is_convertible<Subclass*, Type*>::value, void>::type>
CountingPtr & operator= (const CountingPtr< Subclass, Deleter > &other) noexcept
CountingPtr & operator= (CountingPtr &&other) noexcept
move-assignment operator: move reference of other to current object.
template<typename Subclass , typename = typename std::enable_if< std::is_convertible<Subclass*, Type*>::value, void>::type>
CountingPtr & operator= (CountingPtr< Subclass, Deleter > &&other) noexcept
move-assignment operator: move reference of other to current object.
~CountingPtr ()
destructor: decrements reference count in ptr.
Type & operator* () const noexcept
return the enclosed object as reference.
Type * operator-> () const noexcept
return the enclosed pointer.
Type * get () const noexcept
return the enclosed pointer.
bool valid () const noexcept
test for a non-nullptr pointer
operator bool () const noexcept
cast to bool checks for a nullptr pointer
bool empty () const noexcept
test for a nullptr pointer
bool unique () const noexcept
if the object is referred by this CountingPtr only
size_t use_count () const noexcept
void reset ()
release contained pointer, frees object if this is the last reference.
void swap (CountingPtr &b) noexcept
void unify ()
make and refer a copy if the original object was shared.
bool operator== (const CountingPtr &other) const noexcept
test equality of only the pointer values.
bool operator!= (const CountingPtr &other) const noexcept
test inequality of only the pointer values.
bool operator== (Type *other) const noexcept
test equality of only the address pointed to
bool operator!= (Type *other) const noexcept
test inequality of only the address pointed to
bool operator< (const CountingPtr &other) const noexcept
compare the pointer values.
bool operator<= (const CountingPtr &other) const noexcept
compare the pointer values.
bool operator> (const CountingPtr &other) const noexcept
compare the pointer values.
bool operator>= (const CountingPtr &other) const noexcept
compare the pointer values.
bool operator< (Type *other) const noexcept
compare the pointer values.
bool operator<= (Type *other) const noexcept
compare the pointer values.
bool operator> (Type *other) const noexcept
compare the pointer values.
bool operator>= (Type *other) const noexcept
compare the pointer values.
Private Member Functions
PinnedByteBlockPtr (ByteBlock *ptr, size_t local_worker_id) noexcept
protected ctor for calling from Acquire().
PinnedByteBlockPtr (ByteBlockPtr &&ptr, size_t local_worker_id) noexcept
protected ctor for calling from Acquire().
Private Attributes
size_t local_worker_id_
local worker id of holder of pin
Additional Inherited Members
Public Types inherited from CountingPtr< Type, Deleter >
using element_type = Type
contained type.
Protected Member Functions inherited from ByteBlockPtr
ByteBlockPtr (const PinnedByteBlockPtr &p)
(protected) ctor from PinnedByteBlockPtr
ByteBlockPtr (PinnedByteBlockPtr &&p)
(protected) ctor from PinnedByteBlockPtr
ByteBlockPtr (ByteBlock *ptr)
(protected) ctor from plain pointer
Constructor & Destructor Documentation
PinnedByteBlockPtr () default noexcept
default ctor: contains a nullptr pointer.
PinnedByteBlockPtr (const PinnedByteBlockPtr & pbb) inline noexcept
copy-ctor: increment underlying's pin count
Definition at line 212 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_, and CountingPtr< Type, Deleter >::valid().
PinnedByteBlockPtr (PinnedByteBlockPtr && pbb) inline noexcept
move-ctor: move underlying's pin
Definition at line 218 of file byte_block.hpp.
~PinnedByteBlockPtr () inline
destructor: remove pin
Definition at line 250 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_, and CountingPtr< Type, Deleter >::valid().
PinnedByteBlockPtr (ByteBlock * ptr, size_t local_worker_id) inline private noexcept
protected ctor for calling from Acquire().
Definition at line 265 of file byte_block.hpp.
PinnedByteBlockPtr (ByteBlockPtr && ptr, size_t local_worker_id) inline private noexcept
protected ctor for calling from Acquire().
Definition at line 269 of file byte_block.hpp.
Member Function Documentation
size_t local_worker_id () const inline
local worker id of holder of pin
Definition at line 255 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_.
PinnedByteBlockPtr& operator= (PinnedByteBlockPtr & pbb) inline noexcept
copy-assignment: transfer underlying's pin count
Definition at line 224 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_, CountingPtr< Type, Deleter >::operator=(), and CountingPtr< Type, Deleter >::valid().
PinnedByteBlockPtr& operator= (PinnedByteBlockPtr && pbb) inline noexcept
move-assignment: move underlying's pin
Definition at line 237 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_, CountingPtr< Type, Deleter >::operator=(), and CountingPtr< Type, Deleter >::valid().
ByteBlockPtr ReleasePin () inline
relinquish pin
Definition at line 258 of file byte_block.hpp.
References PinnedByteBlockPtr::local_worker_id_, and CountingPtr< Type, Deleter >::valid().
Member Data Documentation
size_t local_worker_id_ private
local worker id of holder of pin
Definition at line 273 of file byte_block.hpp.
Referenced by PinnedByteBlockPtr::local_worker_id(), PinnedByteBlockPtr::operator=(), PinnedByteBlockPtr::PinnedByteBlockPtr(), PinnedByteBlockPtr::ReleasePin(), and PinnedByteBlockPtr::~PinnedByteBlockPtr().
The documentation for this class was generated from the following file:
thrill/data/byte_block.hpp