Thrill: ZipfGraphGen Class Reference
ZipfGraphGen Class Reference
Detailed Description
Definition at line 32 of file zipf_graph_gen.hpp.
#include <zipf_graph_gen.hpp>
Public Types
using ZipfDistribution = thrill::common::ZipfDistribution
Public Member Functions
ZipfGraphGen (uint64_t _pages)
ZipfGraphGen (const ZipfGraphGen &base, uint64_t _pages)
template<typename Generator >
std::vector< size_t > GenerateOutgoing (Generator &rng)
void Initialize (uint64_t _pages)
reinitialize the random generator if parameters were changed.
void Initialize ()
reinitialize the random generator if parameters were changed.
Public Attributes
double link_zipf_exponent = 0.5
double link_zipf_scale = 0.3
uint64_t pages
number of pages in graph
double size_mean = 50
Gaussian mean and variance of content length.
double size_var = 10
Private Attributes
std::normal_distribution< double > content_length_dist_
Gaussian random variable for content length of a page.
ZipfDistribution link_zipf_
Zipf random variable for outgoing links.
Member Typedef Documentation
ZipfDistribution
using ZipfDistribution = thrill::common::ZipfDistribution
Definition at line 35 of file zipf_graph_gen.hpp.
Constructor & Destructor Documentation
ZipfGraphGen() [1/2]
ZipfGraphGen (uint64_t _pages) inline explicit
Definition at line 49 of file zipf_graph_gen.hpp.
References ZipfGraphGen::Initialize().
ZipfGraphGen() [2/2]
ZipfGraphGen (const ZipfGraphGen & base, uint64_t _pages) inline
Definition at line 53 of file zipf_graph_gen.hpp.
References ZipfGraphGen::Initialize().
Member Function Documentation
GenerateOutgoing()
std::vector<size_t> GenerateOutgoing (Generator & rng) inline
Definition at line 77 of file zipf_graph_gen.hpp.
References ZipfGraphGen::content_length_dist_, and ZipfGraphGen::link_zipf_.
Referenced by main().
Initialize() [1/2]
void Initialize (uint64_t _pages) inline
reinitialize the random generator if parameters were changed.
Definition at line 61 of file zipf_graph_gen.hpp.
References ZipfGraphGen::content_length_dist_, ZipfGraphGen::link_zipf_, ZipfGraphGen::size_mean, and ZipfGraphGen::size_var.
Referenced by main().
Initialize() [2/2]
void Initialize () inline
reinitialize the random generator if parameters were changed.
Definition at line 72 of file zipf_graph_gen.hpp.
Referenced by ZipfGraphGen::ZipfGraphGen().
Member Data Documentation
content_length_dist_
std::normal_distribution<double> content_length_dist_ private
Gaussian random variable for content length of a page.
Definition at line 95 of file zipf_graph_gen.hpp.
Referenced by ZipfGraphGen::GenerateOutgoing(), and ZipfGraphGen::Initialize().
link_zipf_
ZipfDistribution link_zipf_ private
Zipf random variable for outgoing links.
Definition at line 98 of file zipf_graph_gen.hpp.
Referenced by ZipfGraphGen::GenerateOutgoing(), and ZipfGraphGen::Initialize().
link_zipf_exponent
double link_zipf_exponent = 0.5
Definition at line 47 of file zipf_graph_gen.hpp.
Referenced by main().
link_zipf_scale
double link_zipf_scale = 0.3
Zipf distribution scale and exponent for generating outgoing links over the page number universe.
Definition at line 46 of file zipf_graph_gen.hpp.
Referenced by main().
pages
uint64_t pages
number of pages in graph
Definition at line 38 of file zipf_graph_gen.hpp.
size_mean
double size_mean = 50
Gaussian mean and variance of content length.
Definition at line 41 of file zipf_graph_gen.hpp.
Referenced by ZipfGraphGen::Initialize(), and main().
size_var
double size_var = 10
Definition at line 42 of file zipf_graph_gen.hpp.
Referenced by ZipfGraphGen::Initialize(), and main().
The documentation for this class was generated from the following file:
examples/page_rank/zipf_graph_gen.hpp