Thrill: DeltaStreamReader< StreamReader, Type, offset_ > Class Template Reference
DeltaStreamReader< StreamReader, Type, offset_ > Class Template Reference
Detailed Description
template<typename StreamReader, typename Type, Type offset_ = Type()>
class thrill::core::DeltaStreamReader< StreamReader, Type, offset_ >
Definition at line 52 of file delta_stream.hpp.
#include <delta_stream.hpp>
Public Member Functions
DeltaStreamReader (StreamReader &reader, const Type &initial=Type())
bool HasNext ()
template<typename Type2 >
Type Next ()
Private Attributes
Type delta_ = Type()
delta for output
StreamReader & reader_
output reader
Constructor & Destructor Documentation
DeltaStreamReader (StreamReader & reader, const Type & initial = Type()) inline explicit
Definition at line 55 of file delta_stream.hpp.
Member Function Documentation
bool HasNext () inline
Definition at line 59 of file delta_stream.hpp.
References DeltaStreamReader< StreamReader, Type, offset_ >::reader_.
Referenced by LocationDetection< thrill::api::JoinNode::HashCount >::Flush(), and DuplicateDetection::ReadEncodedHashesToVector().
Type Next () inline
Definition at line 64 of file delta_stream.hpp.
References DeltaStreamReader< StreamReader, Type, offset_ >::delta_, DeltaStreamReader< StreamReader, Type, offset_ >::reader_, and gen_data::value.
Referenced by LocationDetection< thrill::api::JoinNode::HashCount >::Flush(), LocationDetection< HashCount >::GolombPairReader::Next(), and DuplicateDetection::ReadEncodedHashesToVector().
Member Data Documentation
Type delta_ = Type() private
delta for output
Definition at line 76 of file delta_stream.hpp.
Referenced by DeltaStreamReader< StreamReader, Type, offset_ >::Next().
StreamReader& reader_ private
output reader
Definition at line 73 of file delta_stream.hpp.
Referenced by DeltaStreamReader< StreamReader, Type, offset_ >::HasNext(), and DeltaStreamReader< StreamReader, Type, offset_ >::Next().
The documentation for this class was generated from the following file:
thrill/core/delta_stream.hpp