Thrill: Multiplexer Class Reference
Multiplexer Class Reference
Data Subsystem Layer
Detailed Description
Multiplexes virtual Connections on Dispatcher.
A worker as a TCP conneciton to each other worker to exchange large amounts of data. Since multiple exchanges can occur at the same time on this single connection we use multiplexing. The slices are called Blocks and are indicated by a MultiplexerHeader. Multiple Blocks form a Stream on a single TCP connection. The multiplexer multiplexes all streams on all sockets.
All sockets are polled for headers. As soon as the a header arrives it is either attached to an existing stream or a new stream instance is created.
Definition at line 67 of file multiplexer.hpp.
#include <multiplexer.hpp>
Public Member Functions
Multiplexer (mem::Manager &mem_manager, BlockPool &block_pool, net::DispatcherThread &dispatcher, net::Group &group, size_t workers_per_host)
Multiplexer (const Multiplexer &)=delete
non-copyable: delete copy-constructor
~Multiplexer ()
Closes all client connections.
BlockPool & block_pool ()
Get the used BlockPool.
void Close ()
Closes all client connections.
common::JsonLogger & logger ()
Get the JsonLogger from the BlockPool.
size_t my_host_rank () const
my rank among the hosts.
size_t num_hosts () const
total number of hosts.
size_t num_workers () const
total number of workers.
Multiplexer & operator= (const Multiplexer &)=delete
non-copyable: delete assignment operator
size_t workers_per_host () const
number of workers per host
CatStreamData
size_t AllocateCatStreamId (size_t local_worker_id)
Allocate the next stream.
CatStreamDataPtr GetOrCreateCatStreamData (size_t id, size_t local_worker_id, size_t dia_id)
Get stream with given id, if it does not exist, create it.
CatStreamPtr GetNewCatStream (size_t local_worker_id, size_t dia_id)
Request next stream.
MixStream
size_t AllocateMixStreamId (size_t local_worker_id)
Allocate the next stream.
MixStreamDataPtr GetOrCreateMixStreamData (size_t id, size_t local_worker_id, size_t dia_id)
Get stream with given id, if it does not exist, create it.
MixStreamPtr GetNewMixStream (size_t local_worker_id, size_t dia_id)
Request next stream.
Private Types
using Connection = net::Connection
Private Member Functions
void AsyncReadMultiplexerHeader (size_t peer, Connection &s)
CatStreamDataPtr CatLoopback (size_t stream_id, size_t to_worker_id)
CatStreamDataPtr IntGetOrCreateCatStreamData (size_t id, size_t local_worker_id, size_t dia_id)
MixStreamDataPtr IntGetOrCreateMixStreamData (size_t id, size_t local_worker_id, size_t dia_id)
void IntReleaseCatStream (size_t id, size_t local_worker_id)
release pointer onto a CatStreamData object
void IntReleaseMixStream (size_t id, size_t local_worker_id)
release pointer onto a MixStream object
MixStreamDataPtr MixLoopback (size_t stream_id, size_t to_worker_id)
void OnCatStreamBlock (size_t peer, Connection &s, const StreamMultiplexerHeader &header, const CatStreamDataPtr &stream, PinnedByteBlockPtr &&bytes)
Receives and dispatches a Block to a CatStreamData.
void OnMixStreamBlock (size_t peer, Connection &s, const StreamMultiplexerHeader &header, const MixStreamDataPtr &stream, PinnedByteBlockPtr &&bytes)
Receives and dispatches a Block to a MixStream.
void OnMultiplexerHeader (size_t peer, uint32_t seq, Connection &s, net::Buffer &&buffer)
Private Attributes
std::atomic< size_t > active_streams_ { 0 }
number of active Cat/MixStreams
BlockPool & block_pool_
reference to host-global BlockPool.
bool closed_ = false
closed
std::unique_ptr< Data > d_
pimpl data structure
net::DispatcherThread & dispatcher_
net::Group & group_
std::atomic< size_t > max_active_streams_ { 0 }
maximu number of active Cat/MixStreams
mem::Manager & mem_manager_
reference to host-global memory manager
std::mutex mutex_
protects critical sections
size_t num_parallel_async_
number of parallel recv requests
size_t send_size_limit_
Calculated send queue size limit for StreamData semaphores.
size_t workers_per_host_
Number of workers per host.
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
using Connection = net::Connection private
Definition at line 208 of file multiplexer.hpp.
Constructor & Destructor Documentation
Multiplexer (mem::Manager & mem_manager, BlockPool & block_pool, net::DispatcherThread & dispatcher, net::Group & group, size_t workers_per_host)
Definition at line 128 of file multiplexer.cpp.
References Multiplexer::AsyncReadMultiplexerHeader(), Group::connection(), thrill::data::default_block_size, Multiplexer::group_, BlockPool::hard_ram_limit(), max(), Group::my_host_rank(), Group::num_hosts(), Group::num_parallel_async(), Multiplexer::num_parallel_async_, and Multiplexer::send_size_limit_.
Multiplexer (const Multiplexer &) delete
non-copyable: delete copy-constructor
~Multiplexer ()
Closes all client connections.
Definition at line 177 of file multiplexer.cpp.
References Group::Close(), Multiplexer::Close(), Multiplexer::closed_, and Multiplexer::group_.
Member Function Documentation
size_t AllocateCatStreamId (size_t local_worker_id)
Allocate the next stream.
Definition at line 184 of file multiplexer.cpp.
References Multiplexer::d_, and Multiplexer::mutex_.
size_t AllocateMixStreamId (size_t local_worker_id)
Allocate the next stream.
Definition at line 216 of file multiplexer.cpp.
References Multiplexer::d_, and Multiplexer::mutex_.
void AsyncReadMultiplexerHeader (size_t peer, Connection & s) private
expects the next MultiplexerHeader from a socket and passes to OnMultiplexerHeader
Definition at line 282 of file multiplexer.cpp.
References DispatcherThread::AsyncRead(), Multiplexer::d_, Multiplexer::dispatcher_, Multiplexer::num_parallel_async_, Multiplexer::OnMultiplexerHeader(), Connection::rx_seq_, and MultiplexerHeader::total_size.
Referenced by Multiplexer::Multiplexer().
BlockPool& block_pool () inline
Get the used BlockPool.
Definition at line 108 of file multiplexer.hpp.
References Multiplexer::block_pool_.
CatStreamDataPtr CatLoopback (size_t stream_id, size_t to_worker_id) private
Pointer to queue that is used for communication between two workers on the same host.
Definition at line 449 of file multiplexer.cpp.
Referenced by CatStreamData::GetWriters().
void Close ()
Closes all client connections.
Definition at line 162 of file multiplexer.cpp.
References Multiplexer::closed_, Multiplexer::d_, die_unless, LOG1, and Multiplexer::mutex_.
Referenced by Multiplexer::~Multiplexer().
CatStreamPtr GetNewCatStream (size_t local_worker_id, size_t dia_id)
Request next stream.
Definition at line 195 of file multiplexer.cpp.
References Multiplexer::d_, Multiplexer::IntGetOrCreateCatStreamData(), and Multiplexer::mutex_.
Referenced by Context::GetNewCatStream().
MixStreamPtr GetNewMixStream (size_t local_worker_id, size_t dia_id)
Request next stream.
Definition at line 227 of file multiplexer.cpp.
References Multiplexer::d_, Multiplexer::IntGetOrCreateMixStreamData(), and Multiplexer::mutex_.
Referenced by Context::GetNewMixStream().
CatStreamDataPtr GetOrCreateCatStreamData (size_t id, size_t local_worker_id, size_t dia_id)
Get stream with given id, if it does not exist, create it.
Definition at line 189 of file multiplexer.cpp.
References Multiplexer::IntGetOrCreateCatStreamData(), and Multiplexer::mutex_.
Referenced by Multiplexer::OnMultiplexerHeader().
MixStreamDataPtr GetOrCreateMixStreamData (size_t id, size_t local_worker_id, size_t dia_id)
Get stream with given id, if it does not exist, create it.
Definition at line 221 of file multiplexer.cpp.
References Multiplexer::IntGetOrCreateMixStreamData(), and Multiplexer::mutex_.
CatStreamDataPtr IntGetOrCreateCatStreamData (size_t id, size_t local_worker_id, size_t dia_id) private
Definition at line 203 of file multiplexer.cpp.
References Multiplexer::d_, Multiplexer::send_size_limit_, and Multiplexer::workers_per_host_.
Referenced by Multiplexer::GetNewCatStream(), and Multiplexer::GetOrCreateCatStreamData().
MixStreamDataPtr IntGetOrCreateMixStreamData (size_t id, size_t local_worker_id, size_t dia_id) private
Definition at line 235 of file multiplexer.cpp.
References Multiplexer::d_, Multiplexer::send_size_limit_, and Multiplexer::workers_per_host_.
Referenced by Multiplexer::GetNewMixStream(), and Multiplexer::GetOrCreateMixStreamData().
void IntReleaseCatStream (size_t id, size_t local_worker_id) private
release pointer onto a CatStreamData object
Definition at line 248 of file multiplexer.cpp.
References Multiplexer::d_, LOG, and sLOG.
Referenced by CatStreamData::Close().
void IntReleaseMixStream (size_t id, size_t local_worker_id) private
release pointer onto a MixStream object
Definition at line 262 of file multiplexer.cpp.
References Multiplexer::d_, LOG, and sLOG.
Referenced by MixStreamData::Close().
common::JsonLogger & logger ()
Get the JsonLogger from the BlockPool.
Definition at line 276 of file multiplexer.cpp.
References Multiplexer::block_pool_, and BlockPool::logger().
Referenced by CatStreamData::CatStreamData(), and StreamData::OnAllClosed().
MixStreamDataPtr MixLoopback (size_t stream_id, size_t to_worker_id) private
Definition at line 456 of file multiplexer.cpp.
Referenced by MixStreamData::GetWriters().
size_t my_host_rank () const inline
my rank among the hosts.
Definition at line 93 of file multiplexer.hpp.
References Multiplexer::group_, and Group::my_host_rank().
Referenced by StreamData::my_host_rank().
size_t num_hosts () const inline
total number of hosts.
Definition at line 88 of file multiplexer.hpp.
References Multiplexer::group_, and Group::num_hosts().
Referenced by StreamData::num_hosts(), and Multiplexer::num_workers().
size_t num_workers () const inline
total number of workers.
Definition at line 98 of file multiplexer.hpp.
References Multiplexer::num_hosts(), and Multiplexer::workers_per_host_.
Referenced by MixStreamData::GetWriters(), CatStreamData::GetWriters(), and StreamData::num_workers().
void OnCatStreamBlock (size_t peer, Connection & s, const StreamMultiplexerHeader & header, const CatStreamDataPtr & stream, PinnedByteBlockPtr && bytes) private
Receives and dispatches a Block to a CatStreamData.
Definition at line 399 of file multiplexer.cpp.
References die_unless, MultiplexerHeader::first_item, MultiplexerHeader::is_last_block, MultiplexerHeader::num_items, StreamMultiplexerHeader::sender_worker, StreamMultiplexerHeader::seq, MultiplexerHeader::size, sLOG, StreamMultiplexerHeader::stream_id, and MultiplexerHeader::typecode_verify.
Referenced by Multiplexer::OnMultiplexerHeader().
void OnMixStreamBlock (size_t peer, Connection & s, const StreamMultiplexerHeader & header, const MixStreamDataPtr & stream, PinnedByteBlockPtr && bytes) private
Receives and dispatches a Block to a MixStream.
Definition at line 424 of file multiplexer.cpp.
References die_unless, MultiplexerHeader::first_item, MultiplexerHeader::is_last_block, MultiplexerHeader::num_items, StreamMultiplexerHeader::sender_worker, StreamMultiplexerHeader::seq, MultiplexerHeader::size, sLOG, StreamMultiplexerHeader::stream_id, and MultiplexerHeader::typecode_verify.
void OnMultiplexerHeader (size_t peer, uint32_t seq, Connection & s, net::Buffer && buffer) private
parses MultiplexerHeader and decides whether to receive Block or close Stream
Definition at line 296 of file multiplexer.cpp.
References BlockPool::AllocateByteBlock(), DispatcherThread::AsyncRead(), Multiplexer::block_pool_, bytes, thrill::data::CatStreamBlock, Multiplexer::d_, die_unless, Multiplexer::dispatcher_, MultiplexerHeader::first_item, Multiplexer::GetOrCreateCatStreamData(), StreamMultiplexerHeader::IsEnd(), LOG, MultiplexerHeader::magic, MultiplexerHeader::num_items, Multiplexer::OnCatStreamBlock(), StreamMultiplexerHeader::Parse(), StreamMultiplexerHeader::receiver_local_worker, tlx::round_up_to_power_of_two(), StreamMultiplexerHeader::sender_worker, StreamMultiplexerHeader::seq, MultiplexerHeader::size, sLOG, StreamMultiplexerHeader::stream_id, THRILL_DEFAULT_ALIGN, and MultiplexerHeader::typecode_verify.
Referenced by Multiplexer::AsyncReadMultiplexerHeader().
Multiplexer& operator= (const Multiplexer &) delete
non-copyable: delete assignment operator
size_t workers_per_host () const inline
number of workers per host
Definition at line 103 of file multiplexer.hpp.
References Multiplexer::workers_per_host_.
Referenced by MixStreamData::GetWriters(), CatStreamData::GetWriters(), StreamData::OnAllClosed(), and StreamData::workers_per_host().
Member Data Documentation
std::atomic<size_t> active_streams_ { 0 } private
number of active Cat/MixStreams
Definition at line 173 of file multiplexer.hpp.
Referenced by MixStreamData::Close(), CatStreamData::Close(), MixStreamData::GetWriters(), and CatStreamData::GetWriters().
BlockPool& block_pool_ private
reference to host-global BlockPool.
Definition at line 148 of file multiplexer.hpp.
Referenced by Multiplexer::block_pool(), CatStreamData::CatStreamData(), MixStreamData::GetWriters(), CatStreamData::GetWriters(), Multiplexer::logger(), and Multiplexer::OnMultiplexerHeader().
bool closed_ = false private
closed
Definition at line 164 of file multiplexer.hpp.
Referenced by Multiplexer::Close(), and Multiplexer::~Multiplexer().
std::unique_ptr<Data> d_ private
pimpl data structure
Definition at line 191 of file multiplexer.hpp.
Referenced by Multiplexer::AllocateCatStreamId(), Multiplexer::AllocateMixStreamId(), Multiplexer::AsyncReadMultiplexerHeader(), Multiplexer::Close(), Multiplexer::GetNewCatStream(), Multiplexer::GetNewMixStream(), Multiplexer::IntGetOrCreateCatStreamData(), Multiplexer::IntGetOrCreateMixStreamData(), Multiplexer::IntReleaseCatStream(), Multiplexer::IntReleaseMixStream(), and Multiplexer::OnMultiplexerHeader().
constexpr bool debug = false static private
Definition at line 69 of file multiplexer.hpp.
net::DispatcherThread& dispatcher_ private
dispatcher used for all communication by data::Multiplexer, the thread never leaves the data components!
Definition at line 152 of file multiplexer.hpp.
Referenced by Multiplexer::AsyncReadMultiplexerHeader(), and Multiplexer::OnMultiplexerHeader().
net::Group& group_ private
Definition at line 155 of file multiplexer.hpp.
Referenced by MixStreamData::GetWriters(), CatStreamData::GetWriters(), Multiplexer::Multiplexer(), Multiplexer::my_host_rank(), Multiplexer::num_hosts(), and Multiplexer::~Multiplexer().
std::atomic<size_t> max_active_streams_ { 0 } private
maximu number of active Cat/MixStreams
Definition at line 176 of file multiplexer.hpp.
Referenced by MixStreamData::GetWriters(), and CatStreamData::GetWriters().
mem::Manager& mem_manager_ private
reference to host-global memory manager
Definition at line 145 of file multiplexer.hpp.
std::mutex mutex_ private
protects critical sections
Definition at line 161 of file multiplexer.hpp.
Referenced by Multiplexer::AllocateCatStreamId(), Multiplexer::AllocateMixStreamId(), MixStreamData::Close(), Multiplexer::Close(), CatStreamData::Close(), Multiplexer::GetNewCatStream(), Multiplexer::GetNewMixStream(), Multiplexer::GetOrCreateCatStreamData(), Multiplexer::GetOrCreateMixStreamData(), MixStreamData::GetWriters(), and CatStreamData::GetWriters().
size_t num_parallel_async_ private
number of parallel recv requests
Definition at line 167 of file multiplexer.hpp.
Referenced by Multiplexer::AsyncReadMultiplexerHeader(), and Multiplexer::Multiplexer().
size_t send_size_limit_ private
Calculated send queue size limit for StreamData semaphores.
Definition at line 170 of file multiplexer.hpp.
Referenced by Multiplexer::IntGetOrCreateCatStreamData(), Multiplexer::IntGetOrCreateMixStreamData(), and Multiplexer::Multiplexer().
size_t workers_per_host_ private
Number of workers per host.
Definition at line 158 of file multiplexer.hpp.
Referenced by Multiplexer::IntGetOrCreateCatStreamData(), Multiplexer::IntGetOrCreateMixStreamData(), Multiplexer::num_workers(), and Multiplexer::workers_per_host().
The documentation for this class was generated from the following files:
thrill/data/multiplexer.hpp
thrill/data/multiplexer.cpp