Thrill: BlockSink Class Reference
BlockSink Class Reference abstract
Data Subsystem Layer
Detailed Description
Pure virtual base class for all things that can receive Blocks from a BlockWriter.
Definition at line 28 of file block_sink.hpp.
#include <block_sink.hpp>
Public Member Functions
BlockSink (BlockPool &block_pool, size_t local_worker_id)
constructor with reference to BlockPool
BlockSink (const BlockSink &)=default
default copy-constructor
BlockSink (BlockSink &&)=default
move-constructor: default
virtual ~BlockSink ()
required virtual destructor
virtual PinnedByteBlockPtr AllocateByteBlock (size_t block_size)
virtual void AppendBlock (const Block &b, bool is_last_block)=0
Appends the (unpinned) Block.
virtual void AppendBlock (Block &&b, bool is_last_block)=0
Appends the (unpinned) Block.
virtual void AppendPinnedBlock (const PinnedBlock &b, bool is_last_block)
Appends the PinnedBlock.
virtual void AppendPinnedBlock (PinnedBlock &&b, bool is_last_block)
Appends the PinnedBlock.
BlockPool * block_pool () const
Returns block_pool_.
virtual void Close ()=0
Closes the sink. Must not be called multiple times.
size_t local_worker_id () const
local worker id to associate pinned block with
common::JsonLogger & logger ()
Returns BlockPool.logger_.
BlockSink & operator= (const BlockSink &)=default
default assignment operator
BlockSink & operator= (BlockSink &&)=default
move-assignment operator: default
virtual void ReleaseByteBlock (ByteBlockPtr &block)
Release an unused ByteBlock with n bytes backing memory.
size_t workers_per_host () const
return number of workers per host
Static Public Attributes
static constexpr bool allocate_can_fail_ = false
Protected Attributes
size_t local_worker_id_
local worker id to associate pinned block with
Private Attributes
BlockPool * block_pool_
Constructor & Destructor Documentation
BlockSink (BlockPool & block_pool, size_t local_worker_id) inline explicit
constructor with reference to BlockPool
Definition at line 32 of file block_sink.hpp.
BlockSink (const BlockSink &) default
default copy-constructor
BlockSink (BlockSink &&) default
move-constructor: default
virtual ~BlockSink () inline virtual
required virtual destructor
Definition at line 46 of file block_sink.hpp.
Member Function Documentation
virtual PinnedByteBlockPtr AllocateByteBlock (size_t block_size) inline virtual
Allocate a ByteBlock with n bytes backing memory. If returned ByteBlockPtr is a nullptr, then memory of this BlockSink is exhausted.
Reimplemented in BoundedBlockSink.
Definition at line 51 of file block_sink.hpp.
References BlockPool::AllocateByteBlock(), BlockSink::block_pool_, and BlockSink::local_worker_id_.
Referenced by BlockWriter< BlockSink >::AllocateBlock(), and BoundedBlockSink::AllocateByteBlock().
virtual void AppendBlock (const Block & b, bool is_last_block) pure virtual
Appends the (unpinned) Block.
Implemented in MixBlockQueueSink, File, BlockQueue, StreamSink, and DiscardSink.
Referenced by BlockWriter< BlockSink >::AppendBlocks(), and BlockSink::AppendPinnedBlock().
virtual void AppendBlock (Block && b, bool is_last_block) pure virtual
Appends the (unpinned) Block.
Implemented in MixBlockQueueSink, File, BlockQueue, StreamSink, and DiscardSink.
virtual void AppendPinnedBlock (const PinnedBlock & b, bool is_last_block) inline virtual
Appends the PinnedBlock.
Reimplemented in StreamSink.
Definition at line 84 of file block_sink.hpp.
References BlockSink::AppendBlock(), and PinnedBlock::ToBlock().
Referenced by BlockWriter< BlockSink >::Flush(), and BlockWriter< BlockSink >::PutSafe().
virtual void AppendPinnedBlock (PinnedBlock && b, bool is_last_block) inline virtual
Appends the PinnedBlock.
Reimplemented in StreamSink.
Definition at line 89 of file block_sink.hpp.
References BlockSink::AppendBlock().
BlockPool* block_pool () const inline
Returns block_pool_.
Definition at line 64 of file block_sink.hpp.
References BlockSink::block_pool_.
Referenced by File::Copy().
virtual void Close () pure virtual
Closes the sink. Must not be called multiple times.
Implemented in MixBlockQueueSink, File, BlockQueue, StreamSink, and DiscardSink.
Referenced by BlockWriter< BlockSink >::Close().
size_t local_worker_id () const inline
local worker id to associate pinned block with
Definition at line 94 of file block_sink.hpp.
References BlockSink::local_worker_id_.
Referenced by StreamSink::AppendBlock(), File::Copy(), and BlockQueue::GetBlockSource().
common::JsonLogger& logger () inline
Returns BlockPool.logger_.
Definition at line 61 of file block_sink.hpp.
References BlockSink::block_pool_, and BlockPool::logger().
Referenced by MixBlockQueueSink::Close(), StreamSink::Finalize(), StreamSink::StreamSink(), and File::~File().
BlockSink& operator= (const BlockSink &) default
default assignment operator
BlockSink& operator= (BlockSink &&) default
move-assignment operator: default
virtual void ReleaseByteBlock (ByteBlockPtr & block) inline virtual
Release an unused ByteBlock with n bytes backing memory.
Reimplemented in BoundedBlockSink.
Definition at line 56 of file block_sink.hpp.
Referenced by BlockWriter< BlockSink >::PutSafe().
size_t workers_per_host () const inline
return number of workers per host
Definition at line 67 of file block_sink.hpp.
References BlockSink::block_pool_, and BlockPool::workers_per_host().
Referenced by StreamSink::AppendPinnedBlock(), StreamSink::Close(), StreamSink::my_worker_rank(), and StreamSink::peer_worker_rank().
Member Data Documentation
constexpr bool allocate_can_fail_ = false static
boolean flag whether to check if AllocateByteBlock can fail in any subclass (if false: accelerate BlockWriter to not be able to cope with nullptr).
Definition at line 72 of file block_sink.hpp.
Referenced by BlockWriter< BlockSink >::Put(), and BlockWriter< BlockSink >::PutNoSelfVerify().
BlockPool* block_pool_ private
reference to BlockPool for allocation and deallocation. (ptr to make BlockSink movable).
Definition at line 99 of file block_sink.hpp.
Referenced by BlockSink::AllocateByteBlock(), BlockSink::block_pool(), BlockSink::logger(), and BlockSink::workers_per_host().
size_t local_worker_id_ protected
local worker id to associate pinned block with
Definition at line 103 of file block_sink.hpp.
Referenced by BlockSink::AllocateByteBlock(), StreamSink::AppendPinnedBlock(), StreamSink::Close(), File::GetConsumeReader(), File::GetKeepReader(), File::GetReader(), File::GetReaderAt(), BlockSink::local_worker_id(), and StreamSink::my_worker_rank().
The documentation for this class was generated from the following file:
thrill/data/block_sink.hpp