Thrill: RadixHeap< ValueType, KeyExtract, KeyType, Radix > Class Template Reference
RadixHeap< ValueType, KeyExtract, KeyType, Radix > Class Template Reference
Containers and Data Structures
Detailed Description
template<typename ValueType, typename KeyExtract, typename KeyType, unsigned Radix = 8>
class tlx::RadixHeap< ValueType, KeyExtract, KeyType, Radix >
This class implements a monotonic integer min priority queue, more specific a multi-level radix heap.
Here, monotonic refers to the fact that the heap maintains an insertion limit and does not allow the insertion of keys smaller than this limit. The frontier is increased to the current minimum when invoking the methods top(), pop() and swap_top_bucket(). To query the currently smallest item without updating the insertion limit use peak_top_key().
We implement a two level radix heap. Let k=sizeof(KeyType)*8 be the number of bits in a key. In contrast to an ordinary radix heap which contains k buckets, we maintain ceil(k/log2(Radix)) rows each containing Radix-many buckets. This reduces the number of move operations when reorganizing the data structure.
The implementation loosly follows the description of "An Experimental Study of Priority Queues in External Memory" [Bregel et al.] and is also inspired by https://github.com/iwiwi/radix-heap
Template Parameters
KeyType Has to be an unsigned integer type
DataType Type of data payload
Radix A power of two <= 64.
Definition at line 376 of file radix_heap.hpp.
#include <radix_heap.hpp>
Public Types
using bucket_data_type = std::vector< value_type >
using bucket_index_type = size_t
using key_type = KeyType
using value_type = ValueType
Public Member Functions
RadixHeap (KeyExtract key_extract=KeyExtract{})
RadixHeap (const RadixHeap &)=default
RadixHeap (RadixHeap &&)=default
void clear ()
Clears all internal queues and resets insertion limit.
template<typename... Args>
bucket_index_type emplace (const key_type key, Args &&...args)
template<typename... Args>
void emplace_in_bucket (const bucket_index_type idx, Args &&...args)
template<typename... Args>
bucket_index_type emplace_keyfirst (const key_type key, Args &&...args)
bool empty () const
Indicates whether size() == 0.
bucket_index_type get_bucket (const value_type &value) const
bucket_index_type get_bucket_key (const key_type key) const
RadixHeap & operator= (const RadixHeap &)=default
RadixHeap & operator= (RadixHeap &&)=default
key_type peak_top_key () const
Returns currently smallest key without updating the insertion limit.
void pop ()
bucket_index_type push (const value_type &value)
Insert element with priority key.
void push_to_bucket (const bucket_index_type idx, const value_type &value)
size_t size () const
Returns number of elements currently stored.
void swap_top_bucket (bucket_data_type &exchange_bucket)
const value_type & top ()
Static Public Attributes
static constexpr unsigned radix = Radix
Protected Types
using bucket_map_type = radix_heap_detail::BucketComputation< Radix, ranked_key_type >
using Encoder = radix_heap_detail::IntegerRank< key_type >
using ranked_key_type = typename Encoder::rank_type
Protected Member Functions
void initialize_ ()
void reorganize_ ()
Protected Attributes
bucket_map_type bucket_map_
std::array< bucket_data_type,
num_buckets > buckets_data_
size_t current_bucket_ { 0 }
radix_heap_detail::BitArray
< num_buckets > filled_
ranked_key_type insertion_limit_ { 0 }
KeyExtract key_extract_
std::array< ranked_key_type,
num_buckets > mins_
size_t size_ { 0 }
Static Protected Attributes
static constexpr unsigned num_buckets = bucket_map_type::num_buckets
static constexpr unsigned num_layers
static constexpr unsigned radix_bits = tlx::Log2<radix>::floor
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
using bucket_data_type = std::vector<value_type>
Definition at line 402 of file radix_heap.hpp.
using bucket_index_type = size_t
Definition at line 386 of file radix_heap.hpp.
using bucket_map_type = radix_heap_detail::BucketComputation<Radix, ranked_key_type> protected
Definition at line 394 of file radix_heap.hpp.
using Encoder = radix_heap_detail::IntegerRank<key_type> protected
Definition at line 391 of file radix_heap.hpp.
using key_type = KeyType
Definition at line 384 of file radix_heap.hpp.
using ranked_key_type = typename Encoder::rank_type protected
Definition at line 392 of file radix_heap.hpp.
using value_type = ValueType
Definition at line 385 of file radix_heap.hpp.
Constructor & Destructor Documentation
RadixHeap (KeyExtract key_extract = KeyExtract { }) inline explicit
Definition at line 404 of file radix_heap.hpp.
RadixHeap (const RadixHeap< ValueType, KeyExtract, KeyType, Radix > &) default
RadixHeap (RadixHeap< ValueType, KeyExtract, KeyType, Radix > &&) default
Member Function Documentation
void clear () inline
Clears all internal queues and resets insertion limit.
Definition at line 545 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), and gen_data::x.
bucket_index_type emplace (const key_type key, Args &&... args) inline
Construct and insert element with priority key
Warning
In contrast to all other methods the key has to be provided explicitly as the first argument. All other arguments are passed to the constructor of the element.
Definition at line 433 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::bucket_map_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, and IntegerRank< Int >::rank_of_int().
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_keyfirst().
void emplace_in_bucket (const bucket_index_type idx, Args &&... args) inline
Construct and insert element into bucket idx (useful if an item was inserted into the same bucket directly before)
Warning
Calling any method which updates the current can invalidate this hint
Definition at line 454 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::bucket_map_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::key_extract_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::mins_, IntegerRank< Int >::rank_of_int(), BitArray< Size >::set_bit(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace().
bucket_index_type emplace_keyfirst (const key_type key, Args &&... args) inline
In case the first parameter can be directly casted into key_type, using this method avoid repeating it.
Definition at line 445 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace().
bool empty () const inline
Indicates whether size() == 0.
Definition at line 497 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size().
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::peak_top_key(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
bucket_index_type get_bucket (const value_type & value) const inline
Definition at line 417 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket_key(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::key_extract_.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket().
bucket_index_type get_bucket_key (const key_type key) const inline
Definition at line 421 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::bucket_map_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, and IntegerRank< Int >::rank_of_int().
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket().
void initialize_ () inline protected
Definition at line 563 of file radix_heap.hpp.
References BitArray< Size >::clear_all(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::current_bucket_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, max(), min(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::mins_, and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::clear().
RadixHeap& operator= (const RadixHeap< ValueType, KeyExtract, KeyType, Radix > &) default
RadixHeap& operator= (RadixHeap< ValueType, KeyExtract, KeyType, Radix > &&) default
key_type peak_top_key () const inline
Returns currently smallest key without updating the insertion limit.
Definition at line 507 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, BitArray< Size >::find_lsb(), IntegerRank< Int >::int_at_rank(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::mins_.
void pop () inline
Removes smallest element
Warning
Updates insertion limit; no smaller keys can be inserted later
Definition at line 522 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, BitArray< Size >::clear_bit(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::current_bucket_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
bucket_index_type push (const value_type & value) inline
Insert element with priority key.
Definition at line 467 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::bucket_map_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::key_extract_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), and IntegerRank< Int >::rank_of_int().
void push_to_bucket (const bucket_index_type idx, const value_type & value) inline
Insert element into specific bucket (useful if an item was inserted into the same bucket directly before)
Warning
Calling any method which updates the current can invalidate this hint
Definition at line 482 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::key_extract_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::mins_, IntegerRank< Int >::rank_of_int(), BitArray< Size >::set_bit(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push().
void reorganize_ () inline protected
Definition at line 574 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::bucket_map_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, BitArray< Size >::clear_bit(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::current_bucket_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, BitArray< Size >::find_lsb(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::insertion_limit_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::key_extract_, max(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::mins_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::num_buckets, IntegerRank< Int >::rank_of_int(), BitArray< Size >::set_bit(), TLX_LIKELY, and gen_data::x.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::swap_top_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::top().
size_t size () const inline
Returns number of elements currently stored.
Definition at line 502 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::empty().
void swap_top_bucket (bucket_data_type & exchange_bucket) inline
Exchanges the top buckets with an empty user provided bucket. Can be used for bulk removals and may reduce allocation overhead
Warning
The exchange bucket has to be empty
Updates insertion limit; no smaller keys can be inserted later
Definition at line 534 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, BitArray< Size >::clear_bit(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::current_bucket_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::filled_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size_.
const value_type& top () inline
Returns currently smallest key and data
Warning
Updates insertion limit; no smaller keys can be inserted later
Definition at line 515 of file radix_heap.hpp.
References RadixHeap< ValueType, KeyExtract, KeyType, Radix >::buckets_data_, RadixHeap< ValueType, KeyExtract, KeyType, Radix >::current_bucket_, and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
Member Data Documentation
bucket_map_type bucket_map_ protected
Definition at line 556 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket_key(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
std::array<bucket_data_type, num_buckets> buckets_data_ protected
Definition at line 558 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::clear(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::swap_top_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::top().
size_t current_bucket_ { 0 } protected
Definition at line 554 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::swap_top_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::top().
constexpr bool debug = false static private
Definition at line 381 of file radix_heap.hpp.
radix_heap_detail::BitArray<num_buckets> filled_ protected
Definition at line 561 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::peak_top_key(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::swap_top_bucket().
ranked_key_type insertion_limit_ { 0 } protected
Definition at line 553 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket_key(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
KeyExtract key_extract_ protected
Definition at line 551 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::get_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
std::array<ranked_key_type, num_buckets> mins_ protected
Definition at line 560 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::peak_top_key(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
constexpr unsigned num_buckets = bucket_map_type::num_buckets static protected
Definition at line 399 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::reorganize_().
constexpr unsigned num_layers static protected
Initial value:
=
        div_ceil(8 * sizeof(ranked_key_type), radix_bits)
Definition at line 397 of file radix_heap.hpp.
constexpr unsigned radix = Radix static
Definition at line 388 of file radix_heap.hpp.
constexpr unsigned radix_bits = tlx::Log2<radix>::floor static protected
Definition at line 396 of file radix_heap.hpp.
size_t size_ { 0 } protected
Definition at line 552 of file radix_heap.hpp.
Referenced by RadixHeap< ValueType, KeyExtract, KeyType, Radix >::emplace_in_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::initialize_(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::pop(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::push_to_bucket(), RadixHeap< ValueType, KeyExtract, KeyType, Radix >::size(), and RadixHeap< ValueType, KeyExtract, KeyType, Radix >::swap_top_bucket().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/container/radix_heap.hpp