Thrill: RequestQueueImplQwQr Class Reference
RequestQueueImplQwQr Class Reference
I/O Requests and Queues
Detailed Description
Implementation of a local request queue having two queues, one for read and one for write requests, thus having two threads. This is the default implementation.
Definition at line 36 of file request_queue_impl_qw_qr.hpp.
#include <request_queue_impl_qw_qr.hpp>
Public Member Functions
RequestQueueImplQwQr (int n=1)
~RequestQueueImplQwQr ()
void AddRequest (RequestPtr &req) final
bool CancelRequest (Request *req) final
void SetPriorityOp (PriorityOp op) final
Public Member Functions inherited from RequestQueue
RequestQueue ()=default
RequestQueue (const RequestQueue &)=delete
non-copyable: delete copy-constructor
RequestQueue (RequestQueue &&)=default
move-constructor: default
virtual ~RequestQueue ()
RequestQueue & operator= (const RequestQueue &)=delete
non-copyable: delete assignment operator
RequestQueue & operator= (RequestQueue &&)=default
move-assignment operator: default
Private Types
using Queue = std::list< RequestPtr, mem::GPoolAllocator< RequestPtr > >
Static Private Member Functions
static void * worker (void *arg)
Private Attributes
std::mutex read_mutex_
Queue read_queue_
common::Semaphore sem_
std::thread thread_
common::SharedState< ThreadState > thread_state_
std::mutex write_mutex_
Queue write_queue_
Static Private Attributes
static constexpr bool debug = false
static constexpr PriorityOp priority_op_ = WRITE
Additional Inherited Members
Public Types inherited from RequestQueue
enum PriorityOp { READ, WRITE, NONE }
Protected Types inherited from RequestQueueImplWorker
enum ThreadState { NOT_RUNNING, RUNNING, TERMINATING, TERMINATED }
Protected Member Functions inherited from RequestQueueImplWorker
void StartThread (void *(*worker)(void *), void *arg, std::thread &t, common::SharedState< ThreadState > &s)
void StopThread (std::thread &t, common::SharedState< ThreadState > &s, common::Semaphore &sem)
Member Typedef Documentation
using Queue = std::list<RequestPtr, mem::GPoolAllocator<RequestPtr> > private
Definition at line 41 of file request_queue_impl_qw_qr.hpp.
Constructor & Destructor Documentation
RequestQueueImplQwQr (int n = 1) explicit
Definition at line 37 of file request_queue_impl_qw_qr.cpp.
References RequestQueueImplWorker::StartThread(), RequestQueueImplQwQr::thread_, RequestQueueImplQwQr::thread_state_, tlx::unused(), and RequestQueueImplQwQr::worker().
~RequestQueueImplQwQr ()
Definition at line 126 of file request_queue_impl_qw_qr.cpp.
References RequestQueueImplQwQr::sem_, RequestQueueImplWorker::StopThread(), RequestQueueImplQwQr::thread_, and RequestQueueImplQwQr::thread_state_.
Member Function Documentation
void AddRequest (RequestPtr & req) final virtual
Implements RequestQueue.
Definition at line 43 of file request_queue_impl_qw_qr.cpp.
References CountingPtr< Type, Deleter >::empty(), CountingPtr< Type, Deleter >::get(), LOG1, Request::READ, RequestQueueImplQwQr::read_mutex_, RequestQueueImplQwQr::read_queue_, RequestQueueImplWorker::RUNNING, RequestQueueImplQwQr::sem_, Semaphore::signal(), RequestQueueImplQwQr::thread_state_, THRILL_THROW_INVALID_ARGUMENT, RequestQueueImplQwQr::write_mutex_, and RequestQueueImplQwQr::write_queue_.
bool CancelRequest (Request * req) final virtual
Implements RequestQueue.
Definition at line 87 of file request_queue_impl_qw_qr.cpp.
References LOG1, Request::READ, RequestQueueImplQwQr::read_mutex_, RequestQueueImplQwQr::read_queue_, RequestQueueImplWorker::RUNNING, RequestQueueImplQwQr::sem_, RequestQueueImplQwQr::thread_state_, THRILL_THROW_INVALID_ARGUMENT, Request::type(), Semaphore::wait(), RequestQueueImplQwQr::write_mutex_, and RequestQueueImplQwQr::write_queue_.
void SetPriorityOp (PriorityOp op) inline final virtual
Reimplemented from RequestQueue.
Definition at line 64 of file request_queue_impl_qw_qr.hpp.
References tlx::unused().
void * worker (void * arg) static private
Definition at line 130 of file request_queue_impl_qw_qr.cpp.
References CountingPtr< Type, Deleter >::get(), LOG, RequestQueue::NONE, RequestQueueImplQwQr::priority_op_, RequestQueue::READ, RequestQueueImplQwQr::read_mutex_, RequestQueueImplQwQr::read_queue_, RequestQueueImplQwQr::sem_, SharedState< ValueType >::set_to(), thrill::common::SetCpuAffinity(), Semaphore::signal(), RequestQueueImplWorker::TERMINATED, RequestQueueImplWorker::TERMINATING, RequestQueueImplQwQr::thread_state_, Semaphore::wait(), RequestQueue::WRITE, RequestQueueImplQwQr::write_mutex_, and RequestQueueImplQwQr::write_queue_.
Referenced by RequestQueueImplQwQr::RequestQueueImplQwQr().
Member Data Documentation
constexpr bool debug = false static private
Definition at line 38 of file request_queue_impl_qw_qr.hpp.
constexpr PriorityOp priority_op_ = WRITE static private
Definition at line 52 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::worker().
std::mutex read_mutex_ private
Definition at line 44 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), and RequestQueueImplQwQr::worker().
Queue read_queue_ private
Definition at line 46 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), and RequestQueueImplQwQr::worker().
common::Semaphore sem_ private
Definition at line 50 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), RequestQueueImplQwQr::worker(), and RequestQueueImplQwQr::~RequestQueueImplQwQr().
std::thread thread_ private
Definition at line 49 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::RequestQueueImplQwQr(), and RequestQueueImplQwQr::~RequestQueueImplQwQr().
common::SharedState<ThreadState> thread_state_ private
Definition at line 48 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), RequestQueueImplQwQr::RequestQueueImplQwQr(), RequestQueueImplQwQr::worker(), and RequestQueueImplQwQr::~RequestQueueImplQwQr().
std::mutex write_mutex_ private
Definition at line 43 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), and RequestQueueImplQwQr::worker().
Queue write_queue_ private
Definition at line 45 of file request_queue_impl_qw_qr.hpp.
Referenced by RequestQueueImplQwQr::AddRequest(), RequestQueueImplQwQr::CancelRequest(), and RequestQueueImplQwQr::worker().
The documentation for this class was generated from the following files:
thrill/io/request_queue_impl_qw_qr.hpp
thrill/io/request_queue_impl_qw_qr.cpp