Thrill: SHA512 Class Reference
SHA512 Class Reference
Message Digests
Detailed Description
SHA-512 processor without external dependencies.
Definition at line 28 of file sha512.hpp.
#include <sha512.hpp>
Public Member Functions
SHA512 ()
construct empty object.
SHA512 (const void *data, uint32_t size)
construct context and process data range
SHA512 (const std::string &str)
construct context and process string
std::string digest ()
finalize computation and return 64 byte (512 bit) digest
std::string digest_hex ()
finalize computation and return 64 byte (512 bit) digest hex encoded
std::string digest_hex_uc ()
finalize computation and return 64 byte (512 bit) digest upper-case hex
void finalize (void *digest)
finalize computation and output 64 byte (512 bit) digest
void process (const void *data, uint32_t size)
process more data
void process (const std::string &str)
process more data
Static Public Attributes
static constexpr size_t kDigestLength = 64
digest length in bytes
Private Attributes
uint8_t buf_ [128]
uint32_t curlen_
uint64_t length_
uint64_t state_ [8]
Constructor & Destructor Documentation
SHA512 ()
construct empty object.
Definition at line 146 of file sha512.cpp.
References SHA512::curlen_, SHA512::length_, and SHA512::state_.
SHA512 (const void * data, uint32_t size)
construct context and process data range
Definition at line 159 of file sha512.cpp.
References SHA512::process().
SHA512 (const std::string & str) explicit
construct context and process string
Definition at line 163 of file sha512.cpp.
References SHA512::process().
Member Function Documentation
std::string digest ()
finalize computation and return 64 byte (512 bit) digest
Definition at line 239 of file sha512.cpp.
References SHA512::finalize(), and SHA512::kDigestLength.
Referenced by SHA512::digest_hex(), and SHA512::digest_hex_uc().
std::string digest_hex ()
finalize computation and return 64 byte (512 bit) digest hex encoded
Definition at line 245 of file sha512.cpp.
References SHA512::digest(), SHA512::finalize(), tlx::hexdump_lc(), and SHA512::kDigestLength.
Referenced by tlx::sha512_hex().
std::string digest_hex_uc ()
finalize computation and return 64 byte (512 bit) digest upper-case hex
Definition at line 251 of file sha512.cpp.
References SHA512::digest(), SHA512::finalize(), tlx::hexdump(), and SHA512::kDigestLength.
Referenced by tlx::sha512_hex_uc().
void finalize (void * digest)
finalize computation and output 64 byte (512 bit) digest
Definition at line 205 of file sha512.cpp.
References SHA512::buf_, SHA512::curlen_, SHA512::length_, tlx::digest_detail::sha512_compress(), SHA512::state_, and tlx::digest_detail::store64().
Referenced by SHA512::digest(), SHA512::digest_hex(), and SHA512::digest_hex_uc().
void process (const void * data, uint32_t size)
process more data
Definition at line 167 of file sha512.cpp.
References SHA512::buf_, SHA512::curlen_, SHA512::length_, tlx::digest_detail::min(), tlx::digest_detail::sha512_compress(), and SHA512::state_.
Referenced by SHA512::process(), and SHA512::SHA512().
void process (const std::string & str)
process more data
Definition at line 201 of file sha512.cpp.
References SHA512::process().
Member Data Documentation
uint8_t buf_[128] private
Definition at line 60 of file sha512.hpp.
Referenced by SHA512::finalize(), and SHA512::process().
uint32_t curlen_ private
Definition at line 59 of file sha512.hpp.
Referenced by SHA512::finalize(), SHA512::process(), and SHA512::SHA512().
constexpr size_t kDigestLength = 64 static
digest length in bytes
Definition at line 44 of file sha512.hpp.
Referenced by SHA512::digest(), SHA512::digest_hex(), and SHA512::digest_hex_uc().
uint64_t length_ private
Definition at line 57 of file sha512.hpp.
Referenced by SHA512::finalize(), SHA512::process(), and SHA512::SHA512().
uint64_t state_[8] private
Definition at line 58 of file sha512.hpp.
Referenced by SHA512::finalize(), SHA512::process(), and SHA512::SHA512().
The documentation for this class was generated from the following files:
extlib/tlx/tlx/digest/sha512.hpp
extlib/tlx/tlx/digest/sha512.cpp