Thrill: FileBase Class Reference
FileBase Class Reference abstract
File I/O Implementations
Detailed Description
Defines interface of file.
It is a base class for different implementations that might base on various file systems or even remote storage interfaces
Definition at line 51 of file file_base.hpp.
#include <file_base.hpp>
Public Types
using offset_type = Request::offset_type
the offset of a request, also the size of the file
enum OpenMode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128,
REQUIRE_DIRECT = 256
}
using size_type = Request::size_type
the size of a request
Public Member Functions
FileBase (const FileBase &)=delete
non-copyable: delete copy-constructor
FileBase (FileBase &&)=default
move-constructor: default
FileBase (unsigned int device_id=DEFAULT_DEVICE_ID)
Construct a new file, usually called by a subclass.
virtual ~FileBase ()
virtual RequestPtr aread (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler())=0
virtual RequestPtr awrite (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler())=0
virtual void close_remove ()
close and remove file
virtual void discard (offset_type offset, offset_type size)
virtual int get_allocator_id () const =0
Returns the file's disk allocator number.
unsigned int get_device_id () const
Returns the file's physical device id.
virtual int get_queue_id () const =0
virtual const char * io_type () const =0
virtual void lock ()=0
Locks file for reading and writing (acquires a lock in the file system).
bool need_alignment () const
Returns need_alignment_.
FileBase & operator= (const FileBase &)=delete
non-copyable: delete assignment operator
FileBase & operator= (FileBase &&)=default
move-assignment operator: default
virtual void serve (void *buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type)=0
virtual void set_size (offset_type newsize)=0
virtual offset_type size ()=0
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Static Public Member Functions
Static Functions for Platform Abstraction
static int unlink (const char *path)
unlink path from filesystem
static int truncate (const char *path, size_t length)
Static Public Attributes
static constexpr bool debug = false
static constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1)
static constexpr int DEFAULT_LINUXAIO_QUEUE = -2
static constexpr int DEFAULT_QUEUE = -1
static constexpr int NO_ALLOCATOR = -1
Protected Attributes
unsigned int device_id_
bool need_alignment_ = false
Flag whether read/write operations require alignment.
Member Typedef Documentation
using offset_type = Request::offset_type
the offset of a request, also the size of the file
Definition at line 57 of file file_base.hpp.
using size_type = Request::size_type
the size of a request
Definition at line 59 of file file_base.hpp.
Member Enumeration Documentation
enum OpenMode
Definition of acceptable file open modes. Various open modes in a file system must be converted to this set of acceptable modes.
Enumerator
RDONLY
only reading of the file is allowed
WRONLY
only writing of the file is allowed
RDWR
read and write of the file are allowed
CREAT
in case file does not exist no error occurs and file is newly created
DIRECT
I/Os proceed bypassing file system buffers, i.e. unbuffered I/O. Tries to open with appropriate flags, if fails print warning and open normally.
TRUNC
once file is opened its length becomes zero
SYNC
open the file with O_SYNC | O_DSYNC | O_RSYNC flags set
NO_LOCK
do not acquire an exclusive lock by default
REQUIRE_DIRECT
implies DIRECT, fail if opening with DIRECT flag does not work.
Definition at line 72 of file file_base.hpp.
Constructor & Destructor Documentation
FileBase (const FileBase &) delete
non-copyable: delete copy-constructor
FileBase (FileBase &&) default
move-constructor: default
FileBase (unsigned int device_id = DEFAULT_DEVICE_ID) inline explicit
Construct a new file, usually called by a subclass.
Definition at line 102 of file file_base.hpp.
virtual ~FileBase () inline virtual
Definition at line 160 of file file_base.hpp.
Member Function Documentation
virtual RequestPtr aread (void * buffer, offset_type offset, size_type bytes, const CompletionHandler & on_cmpl = CompletionHandler()) pure virtual
Schedules an asynchronous read request to the file.
Parameters
buffer pointer to memory buffer to read into
offset file position to start read from
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implemented in LinuxaioFile, and DiskQueuedFile.
Referenced by BlockPool::PinBlock(), and TypedBlock< RawSize, Type, NRef, MetaInfoType >::read().
virtual RequestPtr awrite (void * buffer, offset_type offset, size_type bytes, const CompletionHandler & on_cmpl = CompletionHandler()) pure virtual
Schedules an asynchronous write request to the file.
Parameters
buffer pointer to memory buffer to write from
offset starting file position to write
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implemented in LinuxaioFile, and DiskQueuedFile.
Referenced by TypedBlock< RawSize, Type, NRef, MetaInfoType >::write().
virtual void close_remove () inline virtual
close and remove file
Reimplemented in WfsFileBase, and UfsFileBase.
Definition at line 158 of file file_base.hpp.
virtual void discard (offset_type offset, offset_type size) inline virtual
Discard a region of the file (mark it unused). Some specialized file types may need to know freed regions
Reimplemented in MemoryFile.
Definition at line 152 of file file_base.hpp.
References tlx::unused().
virtual int get_allocator_id () const pure virtual
Returns the file's disk allocator number.
Implemented in DiskQueuedFile.
Referenced by BID< 0 >::is_managed(), and BlockManager::new_blocks_int().
unsigned int get_device_id () const inline
Returns the file's physical device id.
Definition at line 180 of file file_base.hpp.
References FileBase::device_id_.
virtual int get_queue_id () const pure virtual
Returns the identifier of the file's queue number.
Remarks
Files allocated on the same physical device usually share the same queue, unless there is a common queue (e.g. with linuxaio).
Implemented in DiskQueuedFile.
virtual const char* io_type () const pure virtual
Identifies the type of I/O implementation.
Returns
pointer to null terminated string of characters, containing the name of I/O implementation
Implemented in LinuxaioFile, WincallFile, MemoryFile, WfsFileBase, MmapFile, SyscallFile, and UfsFileBase.
virtual void lock () pure virtual
Locks file for reading and writing (acquires a lock in the file system).
Implemented in MemoryFile, WfsFileBase, and UfsFileBase.
bool need_alignment () const inline
Returns need_alignment_.
Definition at line 177 of file file_base.hpp.
References FileBase::need_alignment_.
FileBase& operator= (const FileBase &) delete
non-copyable: delete assignment operator
FileBase& operator= (FileBase &&) default
move-assignment operator: default
virtual void serve (void * buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type) pure virtual
Implemented in LinuxaioFile, WincallFile, MmapFile, MemoryFile, and SyscallFile.
virtual void set_size (offset_type newsize) pure virtual
Changes the size of the file.
Parameters
newsize new file size
Implemented in MemoryFile, and UfsFileBase.
Referenced by DiskAllocator::GrowFile(), and DiskAllocator::~DiskAllocator().
virtual offset_type size () pure virtual
Returns size of the file.
Returns
file size in bytes
Implemented in MemoryFile, WfsFileBase, and UfsFileBase.
static int truncate (const char * path, size_t length) static
truncate a path to given length. Use this only if you dont have a fileio-specific object, which provides truncate().
int unlink (const char * path) static
unlink path from filesystem
Definition at line 20 of file file_base.cpp.
Member Data Documentation
constexpr bool debug = false static
Definition at line 54 of file file_base.hpp.
constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1) static
Definition at line 99 of file file_base.hpp.
Referenced by thrill::io::CreateFile(), DiskConfig::fileio_string(), and DiskConfig::parse_line().
constexpr int DEFAULT_LINUXAIO_QUEUE = -2 static
Definition at line 97 of file file_base.hpp.
Referenced by thrill::io::CreateFile(), and DiskConfig::fileio_string().
constexpr int DEFAULT_QUEUE = -1 static
Definition at line 96 of file file_base.hpp.
Referenced by BlockManager::BlockManager(), DiskConfig::fileio_string(), and DiskConfig::parse_line().
unsigned int device_id_ protected
The file's physical device id (e.g. used for prefetching sequence calculation)
Definition at line 173 of file file_base.hpp.
Referenced by FileBase::get_device_id().
bool need_alignment_ = false protected
Flag whether read/write operations require alignment.
Definition at line 169 of file file_base.hpp.
Referenced by FileBase::need_alignment(), UfsFileBase::UfsFileBase(), and WfsFileBase::WfsFileBase().
constexpr int NO_ALLOCATOR = -1 static
Definition at line 98 of file file_base.hpp.
Referenced by BID< Size >::is_managed(), and BID< 0 >::is_managed().
The documentation for this class was generated from the following files:
thrill/io/file_base.hpp
thrill/io/file_base.cpp