Thrill: RequestQueueImplWorker Class Reference
RequestQueueImplWorker Class Reference
I/O Requests and Queues
Detailed Description
Implementation of request queue worker threads. Worker threads can be started by start_thread and stopped with stop_thread. The queue state is checked before termination and updated afterwards.
Definition at line 38 of file request_queue_impl_worker.hpp.
#include <request_queue_impl_worker.hpp>
Classes
struct FileOffsetMatch
Protected Types
enum ThreadState { NOT_RUNNING, RUNNING, TERMINATING, TERMINATED }
Protected Member Functions
void StartThread (void *(*worker)(void *), void *arg, std::thread &t, common::SharedState< ThreadState > &s)
void StopThread (std::thread &t, common::SharedState< ThreadState > &s, common::Semaphore &sem)
Additional Inherited Members
Public Types inherited from RequestQueue
enum PriorityOp { READ, WRITE, NONE }
Public Member Functions inherited from RequestQueue
RequestQueue ()=default
RequestQueue (const RequestQueue &)=delete
non-copyable: delete copy-constructor
RequestQueue (RequestQueue &&)=default
move-constructor: default
virtual ~RequestQueue ()
virtual void AddRequest (RequestPtr &req)=0
virtual bool CancelRequest (Request *req)=0
RequestQueue & operator= (const RequestQueue &)=delete
non-copyable: delete assignment operator
RequestQueue & operator= (RequestQueue &&)=default
move-assignment operator: default
virtual void SetPriorityOp (PriorityOp p)
Member Enumeration Documentation
enum ThreadState protected
Enumerator
NOT_RUNNING
RUNNING
TERMINATING
TERMINATED
Definition at line 41 of file request_queue_impl_worker.hpp.
Member Function Documentation
void StartThread (void *(*)(void *) worker, void * arg, std::thread & t, common::SharedState< ThreadState > & s) protected
Definition at line 34 of file request_queue_impl_worker.cpp.
References RequestQueueImplWorker::NOT_RUNNING, RequestQueueImplWorker::RUNNING, and SharedState< ValueType >::set_to().
Referenced by LinuxaioQueue::LinuxaioQueue(), RequestQueueImpl1Q::RequestQueueImpl1Q(), and RequestQueueImplQwQr::RequestQueueImplQwQr().
void StopThread (std::thread & t, common::SharedState< ThreadState > & s, common::Semaphore & sem) protected
Definition at line 42 of file request_queue_impl_worker.cpp.
References RequestQueueImplWorker::NOT_RUNNING, RequestQueueImplWorker::RUNNING, SharedState< ValueType >::set_to(), Semaphore::signal(), RequestQueueImplWorker::TERMINATED, and RequestQueueImplWorker::TERMINATING.
Referenced by LinuxaioQueue::~LinuxaioQueue(), RequestQueueImpl1Q::~RequestQueueImpl1Q(), and RequestQueueImplQwQr::~RequestQueueImplQwQr().
The documentation for this class was generated from the following files:
thrill/io/request_queue_impl_worker.hpp
thrill/io/request_queue_impl_worker.cpp