Thrill: Select Class Reference
Select Class Reference
TCP Socket API
Detailed Description
Select is an object-oriented wrapper for select().
It takes care of the bit-fields, etc.
Definition at line 34 of file select.hpp.
#include <select.hpp>
Public Member Functions
Select ()
constructor
Select & Clear (int fd)
Clear a file descriptor from all sets.
Select & ClearException (int fd)
Clear a file descriptor from the exception set.
Select & ClearRead (int fd)
Clear a file descriptor from the read set.
Select & ClearWrite (int fd)
Clear a file descriptor from the write set.
bool InException (int fd) const
Check if a file descriptor is in the resulting exception set.
bool InRead (int fd) const
Check if a file descriptor is in the resulting read set.
bool InWrite (int fd) const
Check if a file descriptor is in the resulting Write set.
int select (struct timeval *timeout=nullptr)
Do a select(), which modifies the enclosed file descriptor objects.
int select_timeout (double timeout)
Do a select() with timeout (in ms)
Select & SetException (int fd)
Add a socket to the exception selection set.
Select & SetRead (int fd)
Add a socket to the read and exception selection set.
Select & SetWrite (int fd)
Add a socket to the write and exception selection set.
Private Attributes
fd_set except_set_
exception bit-field
int max_fd_ = 0
maximum file descriptor value in bitsets
fd_set read_set_
read bit-field
fd_set write_set_
write bit-field
Constructor & Destructor Documentation
Select () inline
constructor
Definition at line 38 of file select.hpp.
References Select::except_set_, Select::read_set_, and Select::write_set_.
Member Function Documentation
Select& Clear (int fd) inline
Clear a file descriptor from all sets.
Definition at line 93 of file select.hpp.
References Select::ClearException(), Select::ClearRead(), and Select::ClearWrite().
Select& ClearException (int fd) inline
Clear a file descriptor from the exception set.
Definition at line 89 of file select.hpp.
References Select::except_set_.
Referenced by SelectDispatcher::Cancel(), Select::Clear(), and SelectDispatcher::DispatchOne().
Select& ClearRead (int fd) inline
Clear a file descriptor from the read set.
Definition at line 81 of file select.hpp.
References Select::read_set_.
Referenced by SelectDispatcher::Cancel(), Select::Clear(), and SelectDispatcher::DispatchOne().
Select& ClearWrite (int fd) inline
Clear a file descriptor from the write set.
Definition at line 85 of file select.hpp.
References Select::write_set_.
Referenced by SelectDispatcher::Cancel(), Select::Clear(), and SelectDispatcher::DispatchOne().
bool InException (int fd) const inline
Check if a file descriptor is in the resulting exception set.
Definition at line 77 of file select.hpp.
References Select::except_set_.
Referenced by SelectDispatcher::DispatchOne().
bool InRead (int fd) const inline
Check if a file descriptor is in the resulting read set.
Definition at line 69 of file select.hpp.
References Select::read_set_.
Referenced by SelectDispatcher::DispatchOne().
bool InWrite (int fd) const inline
Check if a file descriptor is in the resulting Write set.
Definition at line 73 of file select.hpp.
References Select::write_set_.
Referenced by SelectDispatcher::DispatchOne().
int select (struct timeval * timeout = nullptr) inline
Do a select(), which modifies the enclosed file descriptor objects.
Definition at line 97 of file select.hpp.
References Select::except_set_, Select::max_fd_, Select::read_set_, and Select::write_set_.
Referenced by Select::select_timeout().
int select_timeout (double timeout) inline
Do a select() with timeout (in ms)
Definition at line 103 of file select.hpp.
References Select::select().
Referenced by SelectDispatcher::DispatchOne().
Select& SetException (int fd) inline
Add a socket to the exception selection set.
Definition at line 61 of file select.hpp.
References Select::except_set_, thrill::common::max(), and Select::max_fd_.
Referenced by SelectDispatcher::AddRead(), SelectDispatcher::AddWrite(), and SelectDispatcher::SetExcept().
Select& SetRead (int fd) inline
Add a socket to the read and exception selection set.
Definition at line 45 of file select.hpp.
References thrill::common::max(), Select::max_fd_, and Select::read_set_.
Referenced by SelectDispatcher::AddRead().
Select& SetWrite (int fd) inline
Add a socket to the write and exception selection set.
Definition at line 53 of file select.hpp.
References thrill::common::max(), Select::max_fd_, and Select::write_set_.
Referenced by SelectDispatcher::AddWrite().
Member Data Documentation
fd_set except_set_ private
exception bit-field
Definition at line 123 of file select.hpp.
Referenced by Select::ClearException(), Select::InException(), Select::Select(), Select::select(), and Select::SetException().
int max_fd_ = 0 private
maximum file descriptor value in bitsets
Definition at line 126 of file select.hpp.
Referenced by Select::select(), Select::SetException(), Select::SetRead(), and Select::SetWrite().
fd_set read_set_ private
read bit-field
Definition at line 117 of file select.hpp.
Referenced by Select::ClearRead(), Select::InRead(), Select::Select(), Select::select(), and Select::SetRead().
fd_set write_set_ private
write bit-field
Definition at line 120 of file select.hpp.
Referenced by Select::ClearWrite(), Select::InWrite(), Select::Select(), Select::select(), and Select::SetWrite().
The documentation for this class was generated from the following file:
thrill/net/tcp/select.hpp