Thrill: AsyncWriteBlock Class Reference
AsyncWriteBlock Class Reference
Network Subsystem Layer
Detailed Description
Definition at line 377 of file dispatcher.hpp.
#include <dispatcher.hpp>
Public Member Functions
AsyncWriteBlock (Connection &conn, data::PinnedBlock &&block, const AsyncWriteCallback &callback)
Construct block writer with callback.
AsyncWriteBlock (const AsyncWriteBlock &)=delete
non-copyable: delete copy-constructor
AsyncWriteBlock (AsyncWriteBlock &&)=default
move-constructor: default
~AsyncWriteBlock ()
Connection * connection () const
Returns conn_.
const uint8_t * data () const
underlying buffer pointer
void DoCallback ()
bool IsDone () const
bool operator() ()
Should be called when the socket is writable.
AsyncWriteBlock & operator= (const AsyncWriteBlock &)=delete
non-copyable: delete assignment operator
AsyncWriteBlock & operator= (AsyncWriteBlock &&)=default
move-assignment operator: default
size_t size () const
underlying buffer size
Private Attributes
data::PinnedBlock block_
Send block (holds a pin on the underlying ByteBlock)
AsyncWriteCallback callback_
functional object to call once data is complete
Connection * conn_
Connection reference.
size_t written_size_ = 0
total size currently written
Constructor & Destructor Documentation
AsyncWriteBlock (Connection & conn, data::PinnedBlock && block, const AsyncWriteCallback & callback) inline
Construct block writer with callback.
Definition at line 381 of file dispatcher.hpp.
References AsyncWriteBlock::block_, thrill::net::debug_async, LOGC, and PinnedBlock::size().
AsyncWriteBlock (const AsyncWriteBlock &) delete
non-copyable: delete copy-constructor
AsyncWriteBlock (AsyncWriteBlock &&) default
move-constructor: default
~AsyncWriteBlock () inline
Definition at line 401 of file dispatcher.hpp.
References AsyncWriteBlock::block_, thrill::net::debug_async, and LOGC.
Referenced by Dispatcher::MpiAsync::~MpiAsync().
Member Function Documentation
Connection* connection () const inline
Returns conn_.
Definition at line 448 of file dispatcher.hpp.
References AsyncWriteBlock::conn_.
Referenced by Dispatcher::MpiAsync::connection(), and Dispatcher::PerformAsync().
const uint8_t* data () const inline
underlying buffer pointer
Definition at line 451 of file dispatcher.hpp.
References AsyncWriteBlock::block_, and PinnedBlock::data_begin().
Referenced by Dispatcher::PerformAsync().
void DoCallback () inline
Definition at line 440 of file dispatcher.hpp.
References AsyncWriteBlock::callback_, and AsyncWriteBlock::conn_.
Referenced by Dispatcher::MpiAsync::DoCallback(), and AsyncWriteBlock::operator()().
bool IsDone () const inline
Definition at line 438 of file dispatcher.hpp.
References AsyncWriteBlock::block_, PinnedBlock::size(), and AsyncWriteBlock::written_size_.
bool operator() () inline
Should be called when the socket is writable.
Definition at line 408 of file dispatcher.hpp.
References AsyncWriteBlock::block_, AsyncWriteBlock::conn_, PinnedBlock::data_begin(), AsyncWriteBlock::DoCallback(), LOG1, Connection::SendOne(), PinnedBlock::size(), and AsyncWriteBlock::written_size_.
AsyncWriteBlock& operator= (const AsyncWriteBlock &) delete
non-copyable: delete assignment operator
AsyncWriteBlock& operator= (AsyncWriteBlock &&) default
move-assignment operator: default
size_t size () const inline
underlying buffer size
Definition at line 454 of file dispatcher.hpp.
References AsyncWriteBlock::block_, and PinnedBlock::size().
Referenced by Dispatcher::PerformAsync().
Member Data Documentation
data::PinnedBlock block_ private
Send block (holds a pin on the underlying ByteBlock)
Definition at line 461 of file dispatcher.hpp.
Referenced by AsyncWriteBlock::AsyncWriteBlock(), AsyncWriteBlock::data(), AsyncWriteBlock::IsDone(), AsyncWriteBlock::operator()(), AsyncWriteBlock::size(), and AsyncWriteBlock::~AsyncWriteBlock().
AsyncWriteCallback callback_ private
functional object to call once data is complete
Definition at line 467 of file dispatcher.hpp.
Referenced by AsyncWriteBlock::DoCallback().
Connection* conn_ private
Connection reference.
Definition at line 458 of file dispatcher.hpp.
Referenced by AsyncWriteBlock::connection(), AsyncWriteBlock::DoCallback(), and AsyncWriteBlock::operator()().
size_t written_size_ = 0 private
total size currently written
Definition at line 464 of file dispatcher.hpp.
Referenced by AsyncWriteBlock::IsDone(), and AsyncWriteBlock::operator()().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp