Thrill: GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection > Class Template Reference
GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection > Class Template Reference
Thrill Layers » DIA API Layer
Detailed Description
template<typename ValueType, typename KeyExtractor, typename GroupFunction, typename HashFunction, bool UseLocationDetection>
class thrill::api::GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >
Definition at line 39 of file group_by_iterator.hpp.
#include <group_by_iterator.hpp>
Classes
class HashCount
struct ValueComparator
Public Member Functions
template<typename ParentDIA >
GroupByNode (const ParentDIA &parent, const KeyExtractor &key_extractor, const GroupFunction &groupby_function, const HashFunction &hash_function=HashFunction())
Constructor for a GroupByNode.
void Dispose () override
Virtual clear method. Triggers actual disposing in sub-classes.
void Execute () override
Virtual execution method. Triggers actual computation in sub-classes.
DIAMemUse ExecuteMemUse () final
Amount of RAM used by Execute()
void PreOp (const ValueIn &v)
Send all elements to their designated PEs.
DIAMemUse PreOpMemUse () final
Amount of RAM used by PreOp after StartPreOp()
void PushData (bool consume) final
Virtual method for pushing data. Triggers actual pushing in sub-classes.
DIAMemUse PushDataMemUse () final
Amount of RAM used by PushData()
void StartPreOp (size_t) final
Virtual method for preparing start of PushData.
void StopPreOp (size_t) final
Virtual method for preparing end of PushData.
Public Member Functions inherited from DOpNode< ValueType >
DOpNode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DOpNode, which sets references to the parent nodes.
DOpNode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DOpNode, which sets references to the parent nodes.
Public Member Functions inherited from DIANode< ValueType >
DIANode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DIANode, which sets references to the parent nodes.
DIANode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DIANode, which sets references to the parent nodes.
virtual void AddChild (DIABase *node, const Callback &callback=Callback(), size_t parent_index=0)
Enables children to push their "folded" function chains to their parent.
std::vector< DIABase * > children () const override
Returns the children of this DIABase.
void PushFile (data::File &file, bool consume) const
void PushItem (const ValueType &item) const
Method for derived classes to Push a single item to all children.
void RemoveAllChildren () override
void RemoveChild (DIABase *node) override
void RunPushData () override
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
virtual void DecConsumeCounter (size_t counter)
const size_t & dia_id () const
return unique id of DIANode subclass as stored by StatsNode
virtual bool ForwardDataOnly () const
virtual void IncConsumeCounter (size_t counter)
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
virtual void SetConsumeCounter (size_t counter)
DIAState state () const
virtual bool OnPreOpFile (const data::File &, size_t)
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Types
using Key = typename common::FunctionTraits< KeyExtractor >::result_type
using Super = DOpNode< ValueType >
using ValueIn = typename common::FunctionTraits< KeyExtractor >::template arg_plain< 0 >
using ValueOut = ValueType
Private Member Functions
void FlushVectorToFile (std::vector< ValueIn > &v)
Sort and store elements in a file.
void MainOp ()
Receive elements from other workers.
void RunUserFunc (data::File &f, bool consume)
Private Attributes
data::CatStream::Writers emitters_
std::deque< data::File > files_
GroupFunction groupby_function_
HashFunction hash_function_
KeyExtractor key_extractor_
core::LocationDetection< HashCount > location_detection_
data::File pre_file_
location detection and associated files
data::File::Writer pre_writer_
data::File sorted_elems_ { context_.GetFile(this) }
data::CatStreamPtr stream_ { context_.GetNewCatStream(this) }
size_t totalsize_ = 0
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Types inherited from DOpNode< ValueType >
using Super = DIANode< ValueType >
Public Types inherited from DIANode< ValueType >
using Callback = tlx::delegate< void(const ValueType &)>
Public Types inherited from DIABase
using DIABasePtr = tlx::CountingPtr< DIABase >
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Protected Attributes inherited from DIANode< ValueType >
std::vector< Child > children_
Callback functions from the child nodes.
Protected Attributes inherited from DIABase
Context & context_
associated Context
const size_t dia_id_
DIA serial id.
const char *const label_
DOp node static label.
DIAState state_ = DIAState::NEW
State of the DIANode. State is NEW on creation.
std::vector< DIABasePtr > parents_
Parents of this DIABase.
DIAMemUse mem_limit_ = 0
size_t consume_counter_ = 1
Member Typedef Documentation
Key
using Key = typename common::FunctionTraits<KeyExtractor>::result_type private
Definition at line 55 of file group_by_key.hpp.
Super
using Super = DOpNode<ValueType> private
Definition at line 52 of file group_by_key.hpp.
ValueIn
using ValueIn = typename common::FunctionTraits<KeyExtractor>::template arg_plain<0> private
Definition at line 58 of file group_by_key.hpp.
ValueOut
using ValueOut = ValueType private
Definition at line 56 of file group_by_key.hpp.
Constructor & Destructor Documentation
GroupByNode()
GroupByNode (const ParentDIA & parent, const KeyExtractor & key_extractor, const GroupFunction & groupby_function, const HashFunction & hash_function = HashFunction()) inline
Constructor for a GroupByNode.
Sets the DataManager, parent, stack, key_extractor and reduce_function.
Definition at line 121 of file group_by_key.hpp.
References DIABase::context_, DIABase::dia_id(), Context::GetFile(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::groupby_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::hash_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::key_extractor_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::location_detection_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_file_, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp().
Member Function Documentation
Dispose()
void Dispose () inline override virtual
Virtual clear method. Triggers actual disposing in sub-classes.
Reimplemented from DIABase.
Definition at line 294 of file group_by_key.hpp.
Execute()
void Execute () inline override virtual
Virtual execution method. Triggers actual computation in sub-classes.
Implements DIABase.
Definition at line 184 of file group_by_key.hpp.
References StreamData::Writers::Close(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::emitters_, File::GetConsumeReader(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::hash_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::key_extractor_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::location_detection_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::MainOp(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_file_.
ExecuteMemUse()
DIAMemUse ExecuteMemUse () inline final virtual
Amount of RAM used by Execute()
Reimplemented from DIABase.
Definition at line 169 of file group_by_key.hpp.
References DIAMemUse::Max().
FlushVectorToFile()
void FlushVectorToFile (std::vector< ValueIn > & v) inline private
Sort and store elements in a file.
Definition at line 334 of file group_by_key.hpp.
References BlockWriter< BlockSink >::Close(), DIABase::context_, Context::GetFile(), BlockWriter< BlockSink >::Put(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::ValueComparator::ValueComparator().
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::MainOp().
MainOp()
void MainOp () inline private
Receive elements from other workers.
Definition at line 348 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::FlushVectorToFile(), LOG, thrill::mem::memory_exceeded, CountingPtr< Type, Deleter >::reset(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::stream_, and tlx::vector_free().
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute().
PreOp()
void PreOp (const ValueIn & v) inline
Send all elements to their designated PEs.
Definition at line 149 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::emitters_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::hash_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::key_extractor_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::location_detection_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_writer_, and BlockWriter< BlockSink >::Put().
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode().
PreOpMemUse()
DIAMemUse PreOpMemUse () inline final virtual
Amount of RAM used by PreOp after StartPreOp()
Reimplemented from DIABase.
Definition at line 165 of file group_by_key.hpp.
References DIAMemUse::Max().
PushData()
void PushData (bool consume) inline final virtual
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Implements DIABase.
Definition at line 204 of file group_by_key.hpp.
References Context::block_pool(), DIABase::context_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::files_, Context::GetFile(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::groupby_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::key_extractor_, LOG, BlockPool::MaxMergeDegreePrefetch(), DIANode< ValueType >::PushItem(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::RunUserFunc(), sLOG1, thrill::data::StartPrefetch(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::ValueComparator::ValueComparator().
PushDataMemUse()
DIAMemUse PushDataMemUse () inline final virtual
Amount of RAM used by PushData()
Reimplemented from DIABase.
Definition at line 173 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::files_, and DIAMemUse::Max().
RunUserFunc()
void RunUserFunc (data::File & f, bool consume) inline private
Definition at line 314 of file group_by_key.hpp.
References File::GetReader(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::groupby_function_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::key_extractor_, LOG, and DIANode< ValueType >::PushItem().
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PushData().
StartPreOp()
void StartPreOp (size_t) inline final virtual
Virtual method for preparing start of PushData.
Reimplemented from DIABase.
Definition at line 141 of file group_by_key.hpp.
References GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::emitters_, File::GetWriter(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::location_detection_, DIABase::mem_limit_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_file_, GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_writer_, and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::stream_.
StopPreOp()
void StopPreOp (size_t) inline final virtual
Virtual method for preparing end of PushData.
Reimplemented from DIABase.
Definition at line 161 of file group_by_key.hpp.
References BlockWriter< BlockSink >::Close(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::pre_writer_.
Member Data Documentation
debug
constexpr bool debug = false static private
Definition at line 50 of file group_by_key.hpp.
emitters_
data::CatStream::Writers emitters_ private
Definition at line 304 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StartPreOp().
files_
std::deque<data::File> files_ private
Definition at line 306 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PushData(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PushDataMemUse().
groupby_function_
GroupFunction groupby_function_ private
Definition at line 298 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PushData(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::RunUserFunc().
hash_function_
HashFunction hash_function_ private
Definition at line 299 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp().
key_extractor_
KeyExtractor key_extractor_ private
Definition at line 297 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::ValueComparator::operator()(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PushData(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::RunUserFunc().
location_detection_
core::LocationDetection<HashCount> location_detection_ private
Definition at line 301 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StartPreOp().
pre_file_
data::File pre_file_ private
location detection and associated files
Definition at line 311 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::GroupByNode(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StartPreOp().
pre_writer_
data::File::Writer pre_writer_ private
Definition at line 312 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::PreOp(), GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StartPreOp(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StopPreOp().
sorted_elems_
data::File sorted_elems_ { context_.GetFile(this) } private
Definition at line 307 of file group_by_key.hpp.
stream_
data::CatStreamPtr stream_ { context_.GetNewCatStream(this) } private
Definition at line 303 of file group_by_key.hpp.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::MainOp(), and GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::StartPreOp().
totalsize_
size_t totalsize_ = 0 private
Definition at line 308 of file group_by_key.hpp.
The documentation for this class was generated from the following files:
thrill/api/group_by_iterator.hpp
thrill/api/group_by_key.hpp