Thrill: AsyncReadByteBlock Class Reference
AsyncReadByteBlock Class Reference
Network Subsystem Layer
Detailed Description
Definition at line 263 of file dispatcher.hpp.
#include <dispatcher.hpp>
Public Member Functions
AsyncReadByteBlock (Connection &conn, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &callback)
Construct block reader with callback.
AsyncReadByteBlock (const AsyncReadByteBlock &)=delete
non-copyable: delete copy-constructor
AsyncReadByteBlock (AsyncReadByteBlock &&)=default
move-constructor: default
~AsyncReadByteBlock ()
data::PinnedByteBlockPtr & byte_block ()
Connection * connection () const
Returns conn_.
uint8_t * data ()
underlying buffer pointer
const uint8_t * data () const
underlying buffer pointer
void DoCallback ()
void DoCallback (size_t size_check)
bool IsDone () const
bool operator() ()
Should be called when the socket is readable.
AsyncReadByteBlock & operator= (const AsyncReadByteBlock &)=delete
non-copyable: delete assignment operator
AsyncReadByteBlock & operator= (AsyncReadByteBlock &&)=default
move-assignment operator: default
size_t size () const
underlying buffer size
Private Attributes
data::PinnedByteBlockPtr block_
Receive block, holds a pin on the memory.
AsyncReadByteBlockCallback callback_
functional object to call once data is complete
Connection * conn_
Connection reference.
size_t pos_ = 0
size currently read
size_t size_
total size to read
Constructor & Destructor Documentation
AsyncReadByteBlock (Connection & conn, size_t size, data::PinnedByteBlockPtr && block, const AsyncReadByteBlockCallback & callback) inline
Construct block reader with callback.
Definition at line 267 of file dispatcher.hpp.
References AsyncReadByteBlock::block_, thrill::net::debug_async, LOGC, and AsyncReadByteBlock::size_.
AsyncReadByteBlock (const AsyncReadByteBlock &) delete
non-copyable: delete copy-constructor
AsyncReadByteBlock (AsyncReadByteBlock &&) default
move-constructor: default
~AsyncReadByteBlock () inline
Definition at line 289 of file dispatcher.hpp.
References AsyncReadByteBlock::block_, thrill::net::debug_async, LOGC, and AsyncReadByteBlock::size_.
Referenced by Dispatcher::MpiAsync::~MpiAsync().
Member Function Documentation
data::PinnedByteBlockPtr& byte_block () inline
Definition at line 332 of file dispatcher.hpp.
References AsyncReadByteBlock::block_.
Connection* connection () const inline
Returns conn_.
Definition at line 347 of file dispatcher.hpp.
References AsyncReadByteBlock::conn_.
Referenced by Dispatcher::MpiAsync::connection(), and Dispatcher::PerformAsync().
uint8_t* data () inline
underlying buffer pointer
Definition at line 350 of file dispatcher.hpp.
References AsyncReadByteBlock::block_.
Referenced by Dispatcher::PerformAsync().
const uint8_t* data () const inline
underlying buffer pointer
Definition at line 353 of file dispatcher.hpp.
References AsyncReadByteBlock::block_.
void DoCallback () inline
Definition at line 334 of file dispatcher.hpp.
References AsyncReadByteBlock::block_, AsyncReadByteBlock::callback_, and AsyncReadByteBlock::conn_.
Referenced by AsyncReadByteBlock::DoCallback(), Dispatcher::MpiAsync::DoCallback(), and AsyncReadByteBlock::operator()().
void DoCallback (size_t size_check) inline
Definition at line 341 of file dispatcher.hpp.
References die_unequal, AsyncReadByteBlock::DoCallback(), and AsyncReadByteBlock::size_.
bool IsDone () const inline
Definition at line 327 of file dispatcher.hpp.
References AsyncReadByteBlock::block_, AsyncReadByteBlock::pos_, and AsyncReadByteBlock::size_.
bool operator() () inline
Should be called when the socket is readable.
Definition at line 297 of file dispatcher.hpp.
References AsyncReadByteBlock::block_, AsyncReadByteBlock::conn_, AsyncReadByteBlock::DoCallback(), AsyncReadByteBlock::pos_, Connection::RecvOne(), and AsyncReadByteBlock::size_.
AsyncReadByteBlock& operator= (const AsyncReadByteBlock &) delete
non-copyable: delete assignment operator
AsyncReadByteBlock& operator= (AsyncReadByteBlock &&) default
move-assignment operator: default
size_t size () const inline
underlying buffer size
Definition at line 356 of file dispatcher.hpp.
References AsyncReadByteBlock::size_.
Referenced by Dispatcher::PerformAsync().
Member Data Documentation
data::PinnedByteBlockPtr block_ private
Receive block, holds a pin on the memory.
Definition at line 363 of file dispatcher.hpp.
Referenced by AsyncReadByteBlock::AsyncReadByteBlock(), AsyncReadByteBlock::byte_block(), AsyncReadByteBlock::data(), AsyncReadByteBlock::DoCallback(), AsyncReadByteBlock::IsDone(), AsyncReadByteBlock::operator()(), and AsyncReadByteBlock::~AsyncReadByteBlock().
AsyncReadByteBlockCallback callback_ private
functional object to call once data is complete
Definition at line 372 of file dispatcher.hpp.
Referenced by AsyncReadByteBlock::DoCallback().
Connection* conn_ private
Connection reference.
Definition at line 360 of file dispatcher.hpp.
Referenced by AsyncReadByteBlock::connection(), AsyncReadByteBlock::DoCallback(), and AsyncReadByteBlock::operator()().
size_t pos_ = 0 private
size currently read
Definition at line 366 of file dispatcher.hpp.
Referenced by AsyncReadByteBlock::IsDone(), and AsyncReadByteBlock::operator()().
size_t size_ private
total size to read
Definition at line 369 of file dispatcher.hpp.
Referenced by AsyncReadByteBlock::AsyncReadByteBlock(), AsyncReadByteBlock::DoCallback(), AsyncReadByteBlock::IsDone(), AsyncReadByteBlock::operator()(), AsyncReadByteBlock::size(), and AsyncReadByteBlock::~AsyncReadByteBlock().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp