Thrill: StochasticGradientDescent< Vector > Class Template Reference
StochasticGradientDescent< Vector > Class Template Reference
Detailed Description
template<typename Vector>
class examples::stochastic_gradient_descent::StochasticGradientDescent< Vector >
Definition at line 99 of file stochastic_gradient_descent.hpp.
#include <stochastic_gradient_descent.hpp>
Public Member Functions
StochasticGradientDescent (size_t num_iterations, double mini_batch_fraction, double step_size, double tolerance)
Vector optimize (const DIA< DataPoint< Vector > > &input_points, const Vector &initial_weights)
do the actual computation
Private Member Functions
bool is_converged (Vector &old, Vector &curr, double tolerance)
Private Attributes
double mini_batch_fraction
size_t num_iterations
double step_size
double tolerance
Constructor & Destructor Documentation
StochasticGradientDescent()
StochasticGradientDescent (size_t num_iterations, double mini_batch_fraction, double step_size, double tolerance) inline
Definition at line 102 of file stochastic_gradient_descent.hpp.
Member Function Documentation
is_converged()
bool is_converged (Vector & old, Vector & curr, double tolerance) inline private
Definition at line 167 of file stochastic_gradient_descent.hpp.
References Vector< D, Type >::Distance(), max(), and Vector< D, Type >::Norm().
optimize()
Vector optimize (const DIA< DataPoint< Vector > > & input_points, const Vector & initial_weights) inline
do the actual computation
Definition at line 111 of file stochastic_gradient_descent.hpp.
References LeastSquaresGradient< Vector >::Compute(), SumResult< Vector >::count, DataPoint< Vector >::data, SumResult< Vector >::grad, DataPoint< Vector >::label, LOG1, and Vector< D, double >::Make().
Member Data Documentation
mini_batch_fraction
double mini_batch_fraction private
Definition at line 163 of file stochastic_gradient_descent.hpp.
num_iterations
size_t num_iterations private
Definition at line 162 of file stochastic_gradient_descent.hpp.
step_size
double step_size private
Definition at line 164 of file stochastic_gradient_descent.hpp.
tolerance
double tolerance private
Definition at line 165 of file stochastic_gradient_descent.hpp.
The documentation for this class was generated from the following file:
examples/stochastic_gradient_descent/stochastic_gradient_descent.hpp