Thrill: PinRequest Class Reference
PinRequest Class Reference
Data Subsystem Layer
Detailed Description
Definition at line 331 of file block.hpp.
#include <block.hpp>
Public Member Functions
ByteBlockPtr & byte_block ()
bool ready () const
whether the read is completed, cannot block.
PinnedBlock Wait ()
wait and get the PinnedBlock. this may block until the read is complete.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Member Functions
PinRequest (BlockPool *block_pool, PinnedBlock &&block, bool ready=true)
void OnComplete (foxxll::request *req, bool success)
calls BlockPool::OnReadComplete used to tlx::delegate
Private Attributes
PinnedBlock block_
BlockPool * block_pool_
reference back to BlockPool
std::atomic< bool > ready_
indication that the PinnedBlocks ready
foxxll::request_ptr req_
running read request
Constructor & Destructor Documentation
PinRequest (BlockPool * block_pool, PinnedBlock && block, bool ready = true) inline private
Definition at line 346 of file block.hpp.
Member Function Documentation
ByteBlockPtr& byte_block () inline
Definition at line 340 of file block.hpp.
References PinRequest::block_, and PinnedBlock::byte_block().
Referenced by BlockPool::OnReadComplete().
void OnComplete (foxxll::request * req, bool success) private
calls BlockPool::OnReadComplete used to tlx::delegate
Definition at line 719 of file block_pool.cpp.
References PinRequest::block_pool_, and BlockPool::OnReadComplete().
Referenced by BlockPool::PinBlock().
bool ready () const inline
whether the read is completed, cannot block.
Definition at line 338 of file block.hpp.
References PinRequest::ready_.
PinnedBlock Wait ()
wait and get the PinnedBlock. this may block until the read is complete.
Definition at line 64 of file block.cpp.
References PinRequest::block_, PinRequest::block_pool_, BlockPool::cv_read_complete_, BlockPool::mutex_, and PinRequest::ready_.
Member Data Documentation
PinnedBlock block_ private
pinned block which will be returned, this PinnedBlock may already be partially initialized for the read!
Definition at line 353 of file block.hpp.
Referenced by PinRequest::byte_block(), BlockPool::OnReadComplete(), and PinRequest::Wait().
BlockPool* block_pool_ private
reference back to BlockPool
Definition at line 350 of file block.hpp.
Referenced by PinRequest::OnComplete(), and PinRequest::Wait().
std::atomic<bool> ready_ private
indication that the PinnedBlocks ready
Definition at line 358 of file block.hpp.
Referenced by BlockPool::OnReadComplete(), PinRequest::ready(), and PinRequest::Wait().
foxxll::request_ptr req_ private
running read request
Definition at line 355 of file block.hpp.
The documentation for this class was generated from the following files:
thrill/data/block.hpp
thrill/data/block.cpp
thrill/data/block_pool.cpp