Thrill: Aggregate< Type_ > Class Template Reference
Aggregate< Type_ > Class Template Reference
Detailed Description
template<typename Type_>
class thrill::common::Aggregate< Type_ >
Calculate running aggregate statistics: feed it with values, and it will keep the minimum, the maximum, the average, the value number, and the standard deviation is values.
Definition at line 31 of file aggregate.hpp.
#include <aggregate.hpp>
Public Types
using Type = Type_
Public Member Functions
Aggregate ()=default
default constructor
Aggregate (size_t count, const double &mean, const double nvar, const Type &min, const Type &max) noexcept
initializing constructor
Aggregate & Add (const Type &value) noexcept
add a value to the running aggregation
double Average () const noexcept
return the average over all values aggregated
double Avg () const noexcept
return the average over all values aggregated
size_t Count () const noexcept
return number of values aggregated
const Type & Max () const noexcept
return maximum over all values aggregated
double Mean () const noexcept
return the average over all values aggregated
const Type & Min () const noexcept
return minimum over all values aggregated
Aggregate operator+ (const Aggregate &a) const noexcept
operator +
Aggregate & operator+= (const Aggregate &a) noexcept
operator +=
double StandardDeviation (size_t ddof=1) const
return the standard deviation of all values aggregated
double StDev (size_t ddof=1) const
return the standard deviation of all values aggregated
template<typename Archive >
void ThrillSerialize (Archive &ar) const
serialization with Thrill's serializer
const Type Total () const
return sum over all values aggregated
Static Public Member Functions
template<typename Archive >
static Aggregate ThrillDeserialize (Archive &ar)
deserialization with Thrill's serializer
Static Public Attributes
static constexpr size_t thrill_fixed_size
static constexpr bool thrill_is_fixed_size = true
Private Member Functions
double merged_variance (const Aggregate &other) const noexcept
Private Attributes
size_t count_ = 0
number of values aggregated
Type max_ = std::numeric_limits<Type>::lowest()
maximum value
double mean_ = 0
mean of values
Type min_ = std::numeric_limits<Type>::max()
minimum value
double nvar_ = 0.0
approximate count * variance; stddev = sqrt(nvar / (count-1))
Member Typedef Documentation
using Type = Type_
Definition at line 34 of file aggregate.hpp.
Constructor & Destructor Documentation
Aggregate () default
default constructor
Referenced by Aggregate< Type_ >::operator+().
Aggregate (size_t count, const double & mean, const double nvar, const Type & min, const Type & max) inline noexcept
initializing constructor
Definition at line 40 of file aggregate.hpp.
Member Function Documentation
Aggregate& Add (const Type & value) inline noexcept
add a value to the running aggregation
Definition at line 46 of file aggregate.hpp.
References Aggregate< Type_ >::count_, examples::select::delta, thrill::common::max(), Aggregate< Type_ >::max_, Aggregate< Type_ >::mean_, thrill::common::min(), Aggregate< Type_ >::min_, Aggregate< Type_ >::nvar_, TLX_UNLIKELY, and gen_data::value.
double Average () const inline noexcept
return the average over all values aggregated
Definition at line 72 of file aggregate.hpp.
References Aggregate< Type_ >::mean_.
Referenced by Aggregate< Type_ >::Avg(), and Aggregate< Type_ >::Mean().
double Avg () const inline noexcept
return the average over all values aggregated
Definition at line 75 of file aggregate.hpp.
References Aggregate< Type_ >::Average().
size_t Count () const inline noexcept
return number of values aggregated
Definition at line 65 of file aggregate.hpp.
References Aggregate< Type_ >::count_.
const Type& Max () const inline noexcept
return maximum over all values aggregated
Definition at line 84 of file aggregate.hpp.
References Aggregate< Type_ >::max_.
double Mean () const inline noexcept
return the average over all values aggregated
Definition at line 78 of file aggregate.hpp.
References Aggregate< Type_ >::Average().
double merged_variance (const Aggregate< Type_ > & other) const inline private noexcept
Definition at line 150 of file aggregate.hpp.
References Aggregate< Type_ >::count_, examples::select::delta, Aggregate< Type_ >::mean_, and Aggregate< Type_ >::nvar_.
Referenced by Aggregate< Type_ >::operator+(), and Aggregate< Type_ >::operator+=().
const Type& Min () const inline noexcept
return minimum over all values aggregated
Definition at line 81 of file aggregate.hpp.
References Aggregate< Type_ >::min_.
Aggregate operator+ (const Aggregate< Type_ > & a) const inline noexcept
operator +
Definition at line 99 of file aggregate.hpp.
References Aggregate< Type_ >::Aggregate(), Aggregate< Type_ >::count_, thrill::common::max(), Aggregate< Type_ >::max_, Aggregate< Type_ >::mean_, Aggregate< Type_ >::merged_variance(), thrill::common::min(), and Aggregate< Type_ >::min_.
Aggregate& operator+= (const Aggregate< Type_ > & a) inline noexcept
operator +=
Definition at line 111 of file aggregate.hpp.
References Aggregate< Type_ >::count_, thrill::common::max(), Aggregate< Type_ >::max_, Aggregate< Type_ >::mean_, Aggregate< Type_ >::merged_variance(), thrill::common::min(), Aggregate< Type_ >::min_, and Aggregate< Type_ >::nvar_.
double StandardDeviation (size_t ddof = 1) const inline
return the standard deviation of all values aggregated
Definition at line 87 of file aggregate.hpp.
References Aggregate< Type_ >::count_, and Aggregate< Type_ >::nvar_.
Referenced by Aggregate< Type_ >::StDev().
double StDev (size_t ddof = 1) const inline
return the standard deviation of all values aggregated
Definition at line 96 of file aggregate.hpp.
References Aggregate< Type_ >::StandardDeviation().
static Aggregate ThrillDeserialize (Archive & ar) inline static
deserialization with Thrill's serializer
Definition at line 133 of file aggregate.hpp.
References Aggregate< Type_ >::count_, Aggregate< Type_ >::max_, Aggregate< Type_ >::mean_, Aggregate< Type_ >::min_, and Aggregate< Type_ >::nvar_.
void ThrillSerialize (Archive & ar) const inline
serialization with Thrill's serializer
Definition at line 123 of file aggregate.hpp.
References Aggregate< Type_ >::count_, Aggregate< Type_ >::max_, Aggregate< Type_ >::mean_, Aggregate< Type_ >::min_, and Aggregate< Type_ >::nvar_.
const Type Total () const inline
return sum over all values aggregated
Definition at line 69 of file aggregate.hpp.
References Aggregate< Type_ >::count_, and Aggregate< Type_ >::mean_.
Member Data Documentation
size_t count_ = 0 private
number of values aggregated
Definition at line 157 of file aggregate.hpp.
Referenced by Aggregate< Type_ >::Add(), Aggregate< Type_ >::Count(), Aggregate< Type_ >::merged_variance(), Aggregate< Type_ >::operator+(), Aggregate< Type_ >::operator+=(), Aggregate< Type_ >::StandardDeviation(), Aggregate< Type_ >::ThrillDeserialize(), Aggregate< Type_ >::ThrillSerialize(), and Aggregate< Type_ >::Total().
Type max_ = std::numeric_limits<Type>::lowest() private
maximum value
Definition at line 169 of file aggregate.hpp.
Referenced by Aggregate< Type_ >::Add(), Aggregate< Type_ >::Max(), Aggregate< Type_ >::operator+(), Aggregate< Type_ >::operator+=(), Aggregate< Type_ >::ThrillDeserialize(), and Aggregate< Type_ >::ThrillSerialize().
double mean_ = 0 private
mean of values
Definition at line 160 of file aggregate.hpp.
Referenced by Aggregate< Type_ >::Add(), Aggregate< Type_ >::Average(), Aggregate< Type_ >::merged_variance(), Aggregate< Type_ >::operator+(), Aggregate< Type_ >::operator+=(), Aggregate< Type_ >::ThrillDeserialize(), Aggregate< Type_ >::ThrillSerialize(), and Aggregate< Type_ >::Total().
Type min_ = std::numeric_limits<Type>::max() private
minimum value
Definition at line 166 of file aggregate.hpp.
Referenced by Aggregate< Type_ >::Add(), Aggregate< Type_ >::Min(), Aggregate< Type_ >::operator+(), Aggregate< Type_ >::operator+=(), Aggregate< Type_ >::ThrillDeserialize(), and Aggregate< Type_ >::ThrillSerialize().
double nvar_ = 0.0 private
approximate count * variance; stddev = sqrt(nvar / (count-1))
Definition at line 163 of file aggregate.hpp.
Referenced by Aggregate< Type_ >::Add(), Aggregate< Type_ >::merged_variance(), Aggregate< Type_ >::operator+=(), Aggregate< Type_ >::StandardDeviation(), Aggregate< Type_ >::ThrillDeserialize(), and Aggregate< Type_ >::ThrillSerialize().
constexpr size_t thrill_fixed_size static
Initial value:
=
        sizeof(size_t) + 2 * sizeof(double) + 2 * sizeof(Type)
Definition at line 144 of file aggregate.hpp.
constexpr bool thrill_is_fixed_size = true static
Definition at line 143 of file aggregate.hpp.
The documentation for this class was generated from the following file:
thrill/common/aggregate.hpp