Thrill: StringSuffixSet Class Reference
StringSuffixSet Class Reference
Detailed Description
Class implementing StringSet concept for suffix sorting indexes of a std::string text object.
Definition at line 575 of file string_set.hpp.
#include <string_set.hpp>
Public Member Functions
StringSuffixSet (const Text &text, const Iterator &begin, const Iterator &end)
Construct from begin and end string pointers.
StringSuffixSet (Container &c)
Construct from a string container.
Container allocate (size_t n) const
Allocate a new temporary string container with n empty Strings.
Iterator begin () const
Iterator representing first String position.
Iterator end () const
Iterator representing beyond last String position.
CharIterator get_chars (const String &s, size_t depth) const
Return CharIterator for referenced string, which belongs to this set.
std::string get_string (const String &s, size_t depth=0) const
Return complete string (for debugging purposes)
bool is_end (const String &, const CharIterator &i) const
Returns true if CharIterator is at end of the given String.
String & operator[] (const Iterator &i) const
Array access (readable and writable) to String objects.
size_t size () const
Return size of string array.
StringSuffixSet sub (Iterator begin, Iterator end) const
Subset this string set using iterator range.
Public Member Functions inherited from StringSetBase< StringSuffixSet, StringSuffixSetTraits >
StringSuffixSetTraits::String & at (size_t i) const
index-based array access (readable and writable) to String objects.
bool check_order (const typename StringSuffixSetTraits::String &s1, const typename StringSuffixSetTraits::String &s2) const
bool check_order () const
void print () const
StringSuffixSet subi (size_t begin, size_t end) const
Subset this string set using index range.
bool is_equal (const typename StringSuffixSetTraits::String &a, const typename StringSuffixSetTraits::CharIterator &ai, const typename StringSuffixSetTraits::String &b, const typename StringSuffixSetTraits::CharIterator &bi) const
check equality of two strings a and b at char iterators ai and bi.
bool is_less (const typename StringSuffixSetTraits::String &a, const typename StringSuffixSetTraits::CharIterator &ai, const typename StringSuffixSetTraits::String &b, const typename StringSuffixSetTraits::CharIterator &bi) const
check if string a is less or equal to string b at iterators ai and bi.
bool is_leq (const typename StringSuffixSetTraits::String &a, const typename StringSuffixSetTraits::CharIterator &ai, const typename StringSuffixSetTraits::String &b, const typename StringSuffixSetTraits::CharIterator &bi) const
check if string a is less or equal to string b at iterators ai and bi.
StringSuffixSetTraits::Char get_char (const typename StringSuffixSetTraits::String &s, size_t depth) const
uint8_t get_uint8 (const typename StringSuffixSetTraits::String &s, typename StringSuffixSetTraits::CharIterator i) const
uint8_t get_uint8 (const typename StringSuffixSetTraits::String &s, size_t depth) const
uint16_t get_uint16 (const typename StringSuffixSetTraits::String &s, typename StringSuffixSetTraits::CharIterator i) const
uint16_t get_uint16 (const typename StringSuffixSetTraits::String &s, size_t depth) const
uint32_t get_uint32 (const typename StringSuffixSetTraits::String &s, typename StringSuffixSetTraits::CharIterator i) const
uint32_t get_uint32 (const typename StringSuffixSetTraits::String &s, size_t depth) const
uint64_t get_uint64 (const typename StringSuffixSetTraits::String &s, typename StringSuffixSetTraits::CharIterator i) const
uint64_t get_uint64 (const typename StringSuffixSetTraits::String &s, size_t depth) const
Static Public Member Functions
static void deallocate (Container &c)
Deallocate a temporary string container.
static StringSuffixSet Initialize (const Text &text, std::vector< String > &sa)
Initializing constructor which fills output vector sa with indices.
Protected Attributes
Iterator begin_
iterators inside the output suffix array.
Iterator end_
const Text * text_
reference to base text
Additional Inherited Members
Public Types inherited from StringSuffixSetTraits
typedef uint8_t Char
exported alias for character type
typedef const Char * CharIterator
iterator of characters in a string
typedef std::pair< Text,
std::vector< String > > Container
exported alias for assumed string container
typedef std::vector< String >
::iterator Iterator
typedef Text::size_type String
String reference: suffix index of the text.
typedef std::string Text
exported alias for assumed string container
Constructor & Destructor Documentation
StringSuffixSet (const Text & text, const Iterator & begin, const Iterator & end) inline
Construct from begin and end string pointers.
Definition at line 581 of file string_set.hpp.
Referenced by StringSuffixSet::Initialize(), and StringSuffixSet::sub().
StringSuffixSet (Container & c) inline explicit
Construct from a string container.
Definition at line 632 of file string_set.hpp.
Member Function Documentation
Container allocate (size_t n) const inline
Allocate a new temporary string container with n empty Strings.
Definition at line 624 of file string_set.hpp.
References StringSuffixSet::text_.
Iterator begin () const inline
Iterator representing first String position.
Definition at line 599 of file string_set.hpp.
References StringSuffixSet::begin_.
static void deallocate (Container & c) inline static
Deallocate a temporary string container.
Definition at line 628 of file string_set.hpp.
Iterator end () const inline
Iterator representing beyond last String position.
Definition at line 601 of file string_set.hpp.
References StringSuffixSet::end_.
CharIterator get_chars (const String & s, size_t depth) const inline
Return CharIterator for referenced string, which belongs to this set.
Definition at line 608 of file string_set.hpp.
References StringSuffixSet::text_.
std::string get_string (const String & s, size_t depth = 0) const inline
Return complete string (for debugging purposes)
Definition at line 616 of file string_set.hpp.
References StringSuffixSet::text_.
static StringSuffixSet Initialize (const Text & text, std::vector< String > & sa) inline static
Initializing constructor which fills output vector sa with indices.
Definition at line 589 of file string_set.hpp.
References StringSuffixSet::StringSuffixSet().
bool is_end (const String & , const CharIterator & i) const inline
Returns true if CharIterator is at end of the given String.
Definition at line 612 of file string_set.hpp.
References StringSuffixSet::text_.
String& operator[] (const Iterator & i) const inline
Array access (readable and writable) to String objects.
Definition at line 604 of file string_set.hpp.
size_t size () const inline
Return size of string array.
Definition at line 597 of file string_set.hpp.
References StringSuffixSet::begin_, and StringSuffixSet::end_.
StringSuffixSet sub (Iterator begin, Iterator end) const inline
Subset this string set using iterator range.
Definition at line 620 of file string_set.hpp.
References StringSuffixSet::StringSuffixSet(), and StringSuffixSet::text_.
Referenced by StringSetBase< StringSuffixSet, StringSuffixSetTraits >::subi().
Member Data Documentation
Iterator begin_ protected
iterators inside the output suffix array.
Definition at line 642 of file string_set.hpp.
Referenced by StringSuffixSet::begin(), and StringSuffixSet::size().
Iterator end_ protected
Definition at line 642 of file string_set.hpp.
Referenced by StringSuffixSet::end(), and StringSuffixSet::size().
const Text* text_ protected
reference to base text
Definition at line 639 of file string_set.hpp.
Referenced by StringSuffixSet::allocate(), StringSuffixSet::get_chars(), StringSuffixSet::get_string(), StringSuffixSet::is_end(), and StringSuffixSet::sub().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/string_set.hpp