Thrill: Dispatcher::MpiAsync Class Reference
Dispatcher::MpiAsync Class Reference
Detailed Description
This is the big answer to what happens when an MPI async request is signaled as complete: it unifies all possible async requests, including the reference counts they hold on the appropriate buffers, and dispatches the correct callbacks when done.
Definition at line 254 of file dispatcher.hpp.
Public Types
enum Type {
NONE, REQUEST, WRITE_BUFFER, READ_BUFFER,
WRITE_BLOCK, READ_BYTE_BLOCK
}
Public Member Functions
MpiAsync ()
default constructor for resize
MpiAsync (const AsyncRequestCallback &callback)
construct generic MPI async request
MpiAsync (net::Connection &conn, uint32_t seq, Buffer &&buffer, const AsyncWriteCallback &callback)
Construct AsyncWrite with Buffer.
MpiAsync (net::Connection &conn, uint32_t seq, size_t buffer_size, const AsyncReadBufferCallback &callback)
Construct AsyncRead with Buffer.
MpiAsync (net::Connection &conn, uint32_t seq, data::PinnedBlock &&block, const AsyncWriteCallback &callback)
Construct AsyncWrite with Block.
MpiAsync (net::Connection &conn, uint32_t seq, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &callback)
Construct AsyncRead with ByteBuffer.
MpiAsync (const MpiAsync &ma)=default
MpiAsync (MpiAsync &&ma)
move-constructor: move item
~MpiAsync ()
Connection * connection ()
Return mpi Connection pointer.
void DoCallback (MPI_Status &s)
Dispatch done message to correct callback.
MpiAsync & operator= (MpiAsync &&ma) noexcept
move-assignment
Private Member Functions
void Acquire (MpiAsync &&ma) noexcept
assign myself the other object's content
Private Attributes
union {
AsyncRequest arequest_
AsyncReadBuffer read_buffer_
AsyncReadByteBlock read_byte_block_
AsyncWriteBlock write_block_
AsyncWriteBuffer write_buffer_
};
uint32_t seq_
sequence id
Type type_
type of this async
Member Enumeration Documentation
enum Type
Enumerator
NONE
REQUEST
WRITE_BUFFER
READ_BUFFER
WRITE_BLOCK
READ_BYTE_BLOCK
Definition at line 257 of file dispatcher.hpp.
Constructor & Destructor Documentation
MpiAsync () inline
default constructor for resize
Definition at line 265 of file dispatcher.hpp.
MpiAsync (const AsyncRequestCallback & callback) inline
construct generic MPI async request
Definition at line 268 of file dispatcher.hpp.
MpiAsync (net::Connection & conn, uint32_t seq, Buffer && buffer, const AsyncWriteCallback & callback) inline
Construct AsyncWrite with Buffer.
Definition at line 273 of file dispatcher.hpp.
MpiAsync (net::Connection & conn, uint32_t seq, size_t buffer_size, const AsyncReadBufferCallback & callback) inline
Construct AsyncRead with Buffer.
Definition at line 280 of file dispatcher.hpp.
MpiAsync (net::Connection & conn, uint32_t seq, data::PinnedBlock && block, const AsyncWriteCallback & callback) inline
Construct AsyncWrite with Block.
Definition at line 286 of file dispatcher.hpp.
MpiAsync (net::Connection & conn, uint32_t seq, size_t size, data::PinnedByteBlockPtr && block, const AsyncReadByteBlockCallback & callback) inline
Construct AsyncRead with ByteBuffer.
Definition at line 293 of file dispatcher.hpp.
MpiAsync (const MpiAsync & ma) default
copy-constructor: default (work as long as union members are default copyable)
MpiAsync (MpiAsync && ma) inline
move-constructor: move item
Definition at line 305 of file dispatcher.hpp.
References Dispatcher::MpiAsync::Acquire(), and Dispatcher::MpiAsync::NONE.
~MpiAsync () inline
Definition at line 326 of file dispatcher.hpp.
References Dispatcher::MpiAsync::arequest_, Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::read_buffer_, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::MpiAsync::read_byte_block_, Dispatcher::MpiAsync::REQUEST, Dispatcher::MpiAsync::type_, Dispatcher::MpiAsync::WRITE_BLOCK, Dispatcher::MpiAsync::write_block_, Dispatcher::MpiAsync::WRITE_BUFFER, Dispatcher::MpiAsync::write_buffer_, AsyncReadBuffer::~AsyncReadBuffer(), AsyncReadByteBlock::~AsyncReadByteBlock(), AsyncRequest::~AsyncRequest(), AsyncWriteBlock::~AsyncWriteBlock(), and AsyncWriteBuffer::~AsyncWriteBuffer().
Referenced by Dispatcher::MpiAsync::operator=().
Member Function Documentation
void Acquire (MpiAsync && ma) inline private noexcept
assign myself the other object's content
Definition at line 393 of file dispatcher.hpp.
References Dispatcher::MpiAsync::arequest_, Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::read_buffer_, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::MpiAsync::read_byte_block_, Dispatcher::MpiAsync::REQUEST, Dispatcher::MpiAsync::seq_, Dispatcher::MpiAsync::type_, Dispatcher::MpiAsync::WRITE_BLOCK, Dispatcher::MpiAsync::write_block_, Dispatcher::MpiAsync::WRITE_BUFFER, and Dispatcher::MpiAsync::write_buffer_.
Referenced by Dispatcher::MpiAsync::MpiAsync(), and Dispatcher::MpiAsync::operator=().
Connection* connection () inline
Return mpi Connection pointer.
Definition at line 361 of file dispatcher.hpp.
References AsyncReadBuffer::connection(), AsyncWriteBuffer::connection(), AsyncReadByteBlock::connection(), AsyncWriteBlock::connection(), die, Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::read_buffer_, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::MpiAsync::read_byte_block_, Dispatcher::MpiAsync::REQUEST, Dispatcher::MpiAsync::type_, Dispatcher::MpiAsync::WRITE_BLOCK, Dispatcher::MpiAsync::write_block_, Dispatcher::MpiAsync::WRITE_BUFFER, and Dispatcher::MpiAsync::write_buffer_.
Referenced by Dispatcher::DispatchOne().
void DoCallback (MPI_Status & s) inline
Dispatch done message to correct callback.
Definition at line 341 of file dispatcher.hpp.
References Dispatcher::MpiAsync::arequest_, AsyncRequest::DoCallback(), AsyncReadBuffer::DoCallback(), AsyncWriteBuffer::DoCallback(), AsyncReadByteBlock::DoCallback(), AsyncWriteBlock::DoCallback(), Dispatcher::MpiAsync::READ_BUFFER, Dispatcher::MpiAsync::read_buffer_, Dispatcher::MpiAsync::READ_BYTE_BLOCK, Dispatcher::MpiAsync::read_byte_block_, Dispatcher::MpiAsync::REQUEST, Dispatcher::MpiAsync::type_, Dispatcher::MpiAsync::WRITE_BLOCK, Dispatcher::MpiAsync::write_block_, Dispatcher::MpiAsync::WRITE_BUFFER, and Dispatcher::MpiAsync::write_buffer_.
MpiAsync& operator= (MpiAsync && ma) inline noexcept
move-assignment
Definition at line 312 of file dispatcher.hpp.
References Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::NONE, Dispatcher::MpiAsync::type_, and Dispatcher::MpiAsync::~MpiAsync().
Member Data Documentation
union { ... }
the big unification of async receivers. these also hold reference counts on the Buffer or Block objects.
AsyncRequest arequest_
Definition at line 385 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::DoCallback(), and Dispatcher::MpiAsync::~MpiAsync().
AsyncReadBuffer read_buffer_
Definition at line 387 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::connection(), Dispatcher::MpiAsync::DoCallback(), and Dispatcher::MpiAsync::~MpiAsync().
AsyncReadByteBlock read_byte_block_
Definition at line 389 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::connection(), Dispatcher::MpiAsync::DoCallback(), and Dispatcher::MpiAsync::~MpiAsync().
uint32_t seq_ private
sequence id
Definition at line 380 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire().
Type type_ private
type of this async
Definition at line 377 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::connection(), Dispatcher::DispatchOne(), Dispatcher::MpiAsync::DoCallback(), Dispatcher::MpiAsync::operator=(), and Dispatcher::MpiAsync::~MpiAsync().
AsyncWriteBlock write_block_
Definition at line 388 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::connection(), Dispatcher::MpiAsync::DoCallback(), and Dispatcher::MpiAsync::~MpiAsync().
AsyncWriteBuffer write_buffer_
Definition at line 386 of file dispatcher.hpp.
Referenced by Dispatcher::MpiAsync::Acquire(), Dispatcher::MpiAsync::connection(), Dispatcher::MpiAsync::DoCallback(), and Dispatcher::MpiAsync::~MpiAsync().
The documentation for this class was generated from the following file:
thrill/net/mpi/dispatcher.hpp