Thrill: MemoryFile Class Reference
MemoryFile Class Reference final
File I/O Implementations
Detailed Description
Implementation of file based on new[] and memcpy.
Definition at line 32 of file memory_file.hpp.
#include <memory_file.hpp>
Public Member Functions
MemoryFile (int queue_id=DEFAULT_QUEUE, int allocator_id=NO_ALLOCATOR, unsigned int device_id=DEFAULT_DEVICE_ID)
constructs file object.
~MemoryFile ()
void discard (offset_type offset, offset_type size) final
const char * io_type () const final
void lock () final
Locks file for reading and writing (acquires a lock in the file system).
void serve (void *buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type)
void set_size (offset_type newsize) final
offset_type size () final
Public Member Functions inherited from DiskQueuedFile
DiskQueuedFile (int queue_id, int allocator_id)
RequestPtr aread (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
RequestPtr awrite (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
int get_allocator_id () const override
Returns the file's disk allocator number.
int get_queue_id () const override
Public Member Functions inherited from FileBase
FileBase (const FileBase &)=delete
non-copyable: delete copy-constructor
FileBase (FileBase &&)=default
move-constructor: default
FileBase (unsigned int device_id=DEFAULT_DEVICE_ID)
Construct a new file, usually called by a subclass.
virtual ~FileBase ()
virtual void close_remove ()
close and remove file
unsigned int get_device_id () const
Returns the file's physical device id.
bool need_alignment () const
Returns need_alignment_.
FileBase & operator= (const FileBase &)=delete
non-copyable: delete assignment operator
FileBase & operator= (FileBase &&)=default
move-assignment operator: default
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Attributes
std::mutex mutex_
sequentialize function calls
char * ptr_
pointer to memory area of "file"
offset_type size_
size of memory area
Additional Inherited Members
Public Types inherited from FileBase
using offset_type = Request::offset_type
the offset of a request, also the size of the file
enum OpenMode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128,
REQUIRE_DIRECT = 256
}
using size_type = Request::size_type
the size of a request
Static Public Member Functions inherited from FileBase
static int unlink (const char *path)
unlink path from filesystem
static int truncate (const char *path, size_t length)
Static Public Attributes inherited from FileBase
static constexpr bool debug = false
static constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1)
static constexpr int DEFAULT_LINUXAIO_QUEUE = -2
static constexpr int DEFAULT_QUEUE = -1
static constexpr int NO_ALLOCATOR = -1
Protected Attributes inherited from FileBase
unsigned int device_id_
bool need_alignment_ = false
Flag whether read/write operations require alignment.
Constructor & Destructor Documentation
MemoryFile (int queue_id = DEFAULT_QUEUE, int allocator_id = NO_ALLOCATOR, unsigned int device_id = DEFAULT_DEVICE_ID) inline
constructs file object.
Definition at line 45 of file memory_file.hpp.
~MemoryFile ()
Definition at line 46 of file memory_file.cpp.
References free(), and MemoryFile::ptr_.
Member Function Documentation
void discard (offset_type offset, offset_type size) final virtual
Discard a region of the file (mark it unused). Some specialized file types may need to know freed regions
Reimplemented from FileBase.
Definition at line 67 of file memory_file.cpp.
References free(), MemoryFile::lock(), LOG, malloc(), thrill::common::max(), MemoryFile::mutex_, MemoryFile::ptr_, MemoryFile::size(), THRILL_DEFAULT_ALIGN, and tlx::unused().
const char * io_type () const final virtual
Identifies the type of I/O implementation.
Returns
pointer to null terminated string of characters, containing the name of I/O implementation
Implements FileBase.
Definition at line 42 of file memory_file.cpp.
void lock () final virtual
Locks file for reading and writing (acquires a lock in the file system).
Implements FileBase.
Definition at line 51 of file memory_file.cpp.
Referenced by thrill::io::CreateFile(), MemoryFile::discard(), MemoryFile::serve(), and MemoryFile::set_size().
void serve (void * buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type) virtual
Implements FileBase.
Definition at line 26 of file memory_file.cpp.
References MemoryFile::lock(), MemoryFile::mutex_, MemoryFile::ptr_, and Request::READ.
void set_size (offset_type newsize) final virtual
Changes the size of the file.
Parameters
newsize new file size
Implements FileBase.
Definition at line 59 of file memory_file.cpp.
References MemoryFile::lock(), thrill::common::max(), MemoryFile::mutex_, MemoryFile::ptr_, realloc(), and MemoryFile::size_.
FileBase::offset_type size () final virtual
Returns size of the file.
Returns
file size in bytes
Implements FileBase.
Definition at line 55 of file memory_file.cpp.
References MemoryFile::size_.
Referenced by MemoryFile::discard().
Member Data Documentation
std::mutex mutex_ private
sequentialize function calls
Definition at line 41 of file memory_file.hpp.
Referenced by MemoryFile::discard(), MemoryFile::serve(), and MemoryFile::set_size().
char* ptr_ private
pointer to memory area of "file"
Definition at line 35 of file memory_file.hpp.
Referenced by MemoryFile::discard(), MemoryFile::serve(), MemoryFile::set_size(), and MemoryFile::~MemoryFile().
offset_type size_ private
size of memory area
Definition at line 38 of file memory_file.hpp.
Referenced by MemoryFile::set_size(), and MemoryFile::size().
The documentation for this class was generated from the following files:
thrill/io/memory_file.hpp
thrill/io/memory_file.cpp