Thrill: ByteBlock::Deleter Class Reference
ByteBlock::Deleter Class Reference
Detailed Description
deleter for CountingPtr<ByteBlock>
Definition at line 57 of file byte_block.hpp.
#include <byte_block.hpp>
Public Member Functions
void operator() (ByteBlock *bb) const
void operator() (const ByteBlock *bb) const
Member Function Documentation
operator()() [1/2]
void operator() (ByteBlock * bb) const
Definition at line 45 of file byte_block.cpp.
References ByteBlock::block_pool_, Pool::destroy(), BlockPool::DestroyBlock(), thrill::mem::GPool(), ByteBlock::pin_count_str(), ReferenceCounter::reference_count(), sLOG, and ByteBlock::total_pins_.
operator()() [2/2]
void operator() (const ByteBlock * bb) const
Definition at line 59 of file byte_block.cpp.
The documentation for this class was generated from the following files:
thrill/data/byte_block.hpp
thrill/data/byte_block.cpp