Thrill: GolombBitStreamWriter< BlockWriter > Class Template Reference
GolombBitStreamWriter< BlockWriter > Class Template Reference
Detailed Description
template<typename BlockWriter>
class thrill::core::GolombBitStreamWriter< BlockWriter >
Definition at line 29 of file golomb_bit_stream.hpp.
#include <golomb_bit_stream.hpp>
Public Member Functions
GolombBitStreamWriter (BlockWriter &block_writer, const size_t &b)
GolombBitStreamWriter (const GolombBitStreamWriter &)=delete
non-copyable: delete copy-constructor
GolombBitStreamWriter (GolombBitStreamWriter &&)=default
move-constructor: default
~GolombBitStreamWriter ()
GolombBitStreamWriter & operator= (const GolombBitStreamWriter &)=delete
non-copyable: delete assignment operator
GolombBitStreamWriter & operator= (GolombBitStreamWriter &&)=default
move-assignment operator: default
void Put (size_t value)
void PutGolomb (const size_t &value)
Append new Golomb-encoded value to bitset.
Public Member Functions inherited from BitStreamWriter< BlockWriter >
BitStreamWriter (BlockWriter &block_writer)
BitStreamWriter (const BitStreamWriter &)=delete
non-copyable: delete copy-constructor
BitStreamWriter (BitStreamWriter &&)=default
move-constructor: default
~BitStreamWriter ()
void FlushBits ()
Flush out buffered bits.
BitStreamWriter & operator= (const BitStreamWriter &)=delete
non-copyable: delete assignment operator
BitStreamWriter & operator= (BitStreamWriter &&)=default
move-assignment operator: default
void PutBits (const size_t &value, unsigned bits)
Append k bits to the data array.
Private Types
enum : size_t { all_set = ~((size_t)0) }
using Super = BitStreamWriter< BlockWriter >
Private Attributes
size_t b_
Golomb code parameter.
bool first_call_ = true
false, when PutGolomb_in was called already
int log2b_
ceil(log2(b_))
size_t max_little_value_
escape value
Additional Inherited Members
Protected Types inherited from BitStreamWriter< BlockWriter >
enum : size_t { buffer_bits_ = sizeof(size_t) * 8 }
number of bits in buffer_
enum : size_t { mask = buffer_bits_ - 1 }
modulo mask of number of bits in buffer for pos_ counter
Protected Attributes inherited from BitStreamWriter< BlockWriter >
BlockWriter & block_writer_
Output BlockWriter.
size_t buffer_ = 0
current buffer of 32/64 bits
size_t pos_ = 0
currently filled number of bits
Member Typedef Documentation
Super
using Super = BitStreamWriter<BlockWriter> private
Definition at line 32 of file golomb_bit_stream.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum : size_t private
Enumerator
all_set
Definition at line 36 of file golomb_bit_stream.hpp.
Constructor & Destructor Documentation
GolombBitStreamWriter() [1/3]
GolombBitStreamWriter (BlockWriter & block_writer, const size_t & b) inline
Definition at line 39 of file golomb_bit_stream.hpp.
References die_unless, and GolombBitStreamWriter< BlockWriter >::operator=().
GolombBitStreamWriter() [2/3]
GolombBitStreamWriter (const GolombBitStreamWriter< BlockWriter > &) delete
non-copyable: delete copy-constructor
GolombBitStreamWriter() [3/3]
GolombBitStreamWriter (GolombBitStreamWriter< BlockWriter > &&) default
move-constructor: default
~GolombBitStreamWriter()
~GolombBitStreamWriter () inline
Definition at line 56 of file golomb_bit_stream.hpp.
References GolombBitStreamWriter< BlockWriter >::all_set, BitStreamWriter< BlockWriter >::buffer_bits_, BitStreamWriter< BlockWriter >::pos_, and BitStreamWriter< BlockWriter >::PutBits().
Member Function Documentation
operator=() [1/2]
GolombBitStreamWriter& operator= (const GolombBitStreamWriter< BlockWriter > &) delete
non-copyable: delete assignment operator
Referenced by GolombBitStreamReader< BlockReader >::GolombBitStreamReader(), and GolombBitStreamWriter< BlockWriter >::GolombBitStreamWriter().
operator=() [2/2]
GolombBitStreamWriter& operator= (GolombBitStreamWriter< BlockWriter > &&) default
move-assignment operator: default
Put()
void Put (size_t value) inline
Definition at line 123 of file golomb_bit_stream.hpp.
References GolombBitStreamWriter< BlockWriter >::PutGolomb().
PutGolomb()
void PutGolomb (const size_t & value) inline
Append new Golomb-encoded value to bitset.
Definition at line 69 of file golomb_bit_stream.hpp.
References GolombBitStreamWriter< BlockWriter >::all_set, GolombBitStreamWriter< BlockWriter >::b_, BitStreamWriter< BlockWriter >::block_writer_, BitStreamWriter< BlockWriter >::buffer_bits_, GolombBitStreamWriter< BlockWriter >::first_call_, GolombBitStreamWriter< BlockWriter >::log2b_, GolombBitStreamWriter< BlockWriter >::max_little_value_, BitStreamWriter< BlockWriter >::PutBits(), and TLX_UNLIKELY.
Referenced by GolombBitStreamWriter< BlockWriter >::Put().
Member Data Documentation
b_
size_t b_ private
Golomb code parameter.
Definition at line 129 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb(), and GolombBitStreamWriter< BlockWriter >::PutGolomb().
first_call_
bool first_call_ = true private
false, when PutGolomb_in was called already
Definition at line 138 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb(), GolombBitStreamReader< BlockReader >::HasNext(), and GolombBitStreamWriter< BlockWriter >::PutGolomb().
log2b_
int log2b_ private
ceil(log2(b_))
Definition at line 132 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb(), and GolombBitStreamWriter< BlockWriter >::PutGolomb().
max_little_value_
size_t max_little_value_ private
escape value
Definition at line 135 of file golomb_bit_stream.hpp.
Referenced by GolombBitStreamReader< BlockReader >::GetGolomb(), and GolombBitStreamWriter< BlockWriter >::PutGolomb().
The documentation for this class was generated from the following file:
thrill/core/golomb_bit_stream.hpp