Thrill: Semaphore Class Reference
Semaphore Class Reference
Detailed Description
Definition at line 25 of file semaphore.hpp.
#include <semaphore.hpp>
Public Member Functions
Semaphore (size_t init_value=0)
construct semaphore
Semaphore (const Semaphore &)=delete
non-copyable: delete copy-constructor
Semaphore (Semaphore &&s)
move-constructor: just move the value
Semaphore & operator= (const Semaphore &)=delete
non-copyable: delete assignment operator
size_t signal ()
size_t signal (size_t delta)
size_t value () const
return the current value – should only be used for debugging.
size_t wait ()
Private Attributes
std::condition_variable cv_
condition variable
std::mutex mutex_
mutex for condition variable
size_t value_
value of the semaphore
Constructor & Destructor Documentation
Semaphore (size_t init_value = 0) inline explicit
construct semaphore
Definition at line 29 of file semaphore.hpp.
Semaphore (const Semaphore &) delete
non-copyable: delete copy-constructor
Semaphore (Semaphore && s) inline
move-constructor: just move the value
Definition at line 37 of file semaphore.hpp.
Member Function Documentation
Semaphore& operator= (const Semaphore &) delete
non-copyable: delete assignment operator
size_t signal () inline
function increments the semaphore and signals any threads that are blocked waiting a change in the semaphore
Definition at line 41 of file semaphore.hpp.
References Semaphore::cv_, Semaphore::mutex_, and Semaphore::value_.
Referenced by RequestQueueImpl1Q::AddRequest(), RequestQueueImplQwQr::AddRequest(), LinuxaioQueue::AddRequest(), StreamSink::AppendPinnedBlock(), LinuxaioQueue::CancelRequest(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::LinuxaioQueue(), MixStream::OnCloseStream(), LinuxaioQueue::PostRequests(), RequestQueueImplWorker::StopThread(), LinuxaioQueue::WaitRequests(), RequestQueueImpl1Q::worker(), and RequestQueueImplQwQr::worker().
size_t signal (size_t delta) inline
function increments the semaphore and signals any threads that are blocked waiting a change in the semaphore
Definition at line 49 of file semaphore.hpp.
References Semaphore::cv_, examples::select::delta, Semaphore::mutex_, and Semaphore::value_.
size_t value () const inline
return the current value – should only be used for debugging.
Definition at line 65 of file semaphore.hpp.
References Semaphore::value_.
size_t wait () inline
function decrements the semaphore and blocks if the semaphore is <= 0 until another thread signals a change
Definition at line 57 of file semaphore.hpp.
References Semaphore::cv_, Semaphore::mutex_, and Semaphore::value_.
Referenced by StreamSink::AppendPinnedBlock(), RequestQueueImpl1Q::CancelRequest(), RequestQueueImplQwQr::CancelRequest(), LinuxaioQueue::CancelRequest(), StreamSink::Close(), MixStream::Close(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::PostRequests(), LinuxaioQueue::WaitRequests(), RequestQueueImpl1Q::worker(), and RequestQueueImplQwQr::worker().
Member Data Documentation
std::condition_variable cv_ private
condition variable
Definition at line 75 of file semaphore.hpp.
Referenced by Semaphore::signal(), and Semaphore::wait().
std::mutex mutex_ private
mutex for condition variable
Definition at line 72 of file semaphore.hpp.
Referenced by Semaphore::signal(), and Semaphore::wait().
size_t value_ private
value of the semaphore
Definition at line 69 of file semaphore.hpp.
Referenced by Semaphore::signal(), Semaphore::value(), and Semaphore::wait().
The documentation for this class was generated from the following file:
thrill/common/semaphore.hpp