Thrill: Stats::ScopedReadTimer Class Reference
Stats::ScopedReadTimer Class Reference
Detailed Description
Definition at line 167 of file iostats.hpp.
#include <iostats.hpp>
Public Member Functions
ScopedReadTimer (size_type size)
~ScopedReadTimer ()
void Start (size_type size)
void Stop ()
Private Types
using size_type = size_t
Private Attributes
bool running_ = false
Member Typedef Documentation
using size_type = size_t private
Definition at line 169 of file iostats.hpp.
Constructor & Destructor Documentation
ScopedReadTimer (size_type size) inline explicit
Definition at line 174 of file iostats.hpp.
References Stats::ScopedReadTimer::Start().
~ScopedReadTimer () inline
Definition at line 178 of file iostats.hpp.
References Stats::ScopedReadTimer::Stop().
Member Function Documentation
void Start (size_type size) inline
Definition at line 182 of file iostats.hpp.
References Singleton< Stats >::GetInstance(), and Stats::ScopedReadTimer::running_.
Referenced by Stats::ScopedReadTimer::ScopedReadTimer().
void Stop () inline
Definition at line 189 of file iostats.hpp.
References Singleton< Stats >::GetInstance(), and Stats::ScopedReadTimer::running_.
Referenced by Stats::ScopedReadTimer::~ScopedReadTimer().
Member Data Documentation
bool running_ = false private
Definition at line 171 of file iostats.hpp.
Referenced by Stats::ScopedReadTimer::Start(), and Stats::ScopedReadTimer::Stop().
The documentation for this class was generated from the following file:
thrill/io/iostats.hpp