Thrill: stats::scoped_wait_timer Class Reference
stats::scoped_wait_timer Class Reference
Detailed Description
Definition at line 370 of file iostats.hpp.
#include <iostats.hpp>
Public Member Functions
scoped_wait_timer (wait_op_type wait_op, bool measure_time=true)
~scoped_wait_timer ()
void start ()
void stop ()
Private Attributes
bool running_ = false
wait_op_type wait_op_
Constructor & Destructor Documentation
scoped_wait_timer()
scoped_wait_timer (wait_op_type wait_op, bool measure_time = true) inline explicit
Definition at line 378 of file iostats.hpp.
References file_stats::scoped_read_write_timer::start().
~scoped_wait_timer()
~scoped_wait_timer () inline
Definition at line 387 of file iostats.hpp.
References file_stats::scoped_read_write_timer::stop().
Member Function Documentation
start()
void start () inline
Definition at line 392 of file iostats.hpp.
References singleton< stats >::get_instance(), and stats::wait_started().
stop()
void stop () inline
Definition at line 402 of file iostats.hpp.
References singleton< stats >::get_instance(), and stats::wait_finished().
Member Data Documentation
running_
bool running_ = false private
Definition at line 373 of file iostats.hpp.
wait_op_
wait_op_type wait_op_ private
Definition at line 374 of file iostats.hpp.
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/io/iostats.hpp