Thrill: PS5SmallsortJob< Context, StringPtr, BktSizeType > Class Template Reference
PS5SmallsortJob< Context, StringPtr, BktSizeType > Class Template Reference
Detailed Description
template<typename Context, typename StringPtr, typename BktSizeType>
class tlx::sort_strings_detail::PS5SmallsortJob< Context, StringPtr, BktSizeType >
SampleSort: Non-Recursive In-Place Sequential Sample Sort for Small Sorts.
Definition at line 291 of file parallel_sample_sort.hpp.
#include <parallel_sample_sort.hpp>
Classes
class MKQSStep
class SeqSampleSortStep
Stack of Recursive Sample Sort Steps.
Public Types
typedef BktSizeType bktsize_type
typedef Context::key_type key_type
typedef StringPtr::StringSet StringSet
Public Member Functions
PS5SmallsortJob (Context &ctx, PS5SortStep *pstep, const StringPtr &strptr, size_t depth)
~PS5SmallsortJob ()
void mkqs_free_work ()
void run ()
void sample_sort_free_work ()
void sort_mkqs_cache (const StringPtr &strptr, size_t depth)
void sort_sample_sort (const StringPtr &strptr, size_t depth)
void substep_all_done () final
Pure virtual function called by substep when all substeps are done.
Public Member Functions inherited from PS5SortStep
void substep_notify_done ()
Notify superstep that the currently substep is done.
Static Public Member Functions
static int cmp (const key_type &a, const key_type &b)
Stack of Recursive MKQS Steps.
template<bool CacheDirty>
static void insertion_sort_cache (const StringPtr &_strptr, key_type *cache, size_t depth)
Insertion sort, but use cached characters if possible.
static void insertion_sort_cache_block (const StringPtr &strptr, key_type *cache)
Insertion sort the strings only based on the cached characters.
template<typename Type >
static size_t med3 (Type *A, size_t i, size_t j, size_t k)
Public Attributes
simple_vector< uint8_t > bktcache_
size_t bktcache_size_ = 0
Context & ctx_
size_t depth_
size_t ms_front_ = 0
std::vector< MKQSStep > ms_stack_
MultiTimer mtimer_
PS5SortStep * pstep_
parent sort step
size_t ss_front_ = 0
std::vector< SeqSampleSortStep > ss_stack_
StringPtr strptr_
Additional Inherited Members
Protected Member Functions inherited from PS5SortStep
PS5SortStep ()
virtual ~PS5SortStep ()
void substep_add ()
Register new substep.
Member Typedef Documentation
typedef BktSizeType bktsize_type
Definition at line 305 of file parallel_sample_sort.hpp.
typedef Context::key_type key_type
Definition at line 303 of file parallel_sample_sort.hpp.
typedef StringPtr::StringSet StringSet
Definition at line 304 of file parallel_sample_sort.hpp.
Constructor & Destructor Documentation
PS5SmallsortJob (Context & ctx, PS5SortStep * pstep, const StringPtr & strptr, size_t depth) inline
Definition at line 307 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::depth_, StringPtr< StringSet_ >::size(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::strptr_, and TLX_LOGC.
~PS5SmallsortJob () inline
Definition at line 315 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::mtimer_, and MultiTimer::stop().
Member Function Documentation
static int cmp (const key_type & a, const key_type & b) inline static
Stack of Recursive MKQS Steps.
Definition at line 647 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::MKQSStep().
static void insertion_sort_cache (const StringPtr & _strptr, key_type * cache, size_t depth) inline static
Insertion sort, but use cached characters if possible.
Definition at line 691 of file parallel_sample_sort.hpp.
References StringPtr< StringSet_ >::fill_lcp(), tlx::sort_strings_detail::insertion_sort(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache_block(), tlx::sort_strings_detail::lcpKeyDepth(), tlx::sort_strings_detail::lcpKeyType(), StringPtr< StringSet_ >::set_lcp(), StringPtr< StringSet_ >::size(), StringPtr< StringSet_ >::sub(), and StringPtr< StringSet_ >::with_lcp.
static void insertion_sort_cache_block (const StringPtr & strptr, key_type * cache) inline static
Insertion sort the strings only based on the cached characters.
Definition at line 670 of file parallel_sample_sort.hpp.
References StringPtr< StringSet_ >::active(), and StringPtr< StringSet_ >::size().
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache().
static size_t med3 (Type * A, size_t i, size_t j, size_t k) inline static
Definition at line 653 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::MKQSStep().
void mkqs_free_work () inline
Definition at line 1016 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::depth_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::eq_recurse_, StringPtr< StringSet_ >::fill_lcp(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::idx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::lcp_eq_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_stack_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_eq_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_gt_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_lt_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::strptr_, StringPtr< StringSet_ >::sub(), PS5SortStep::substep_add(), and TLX_LOGC.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work().
void run () inline
Definition at line 323 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::bktcache_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::depth_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::mtimer_, StringPtr< StringSet_ >::size(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), MultiTimer::start(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::strptr_, PS5SortStep::substep_add(), PS5SortStep::substep_notify_done(), and TLX_LOGC.
void sample_sort_free_work () inline
Definition at line 563 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, StringPtr< StringSet_ >::fill_lcp(), tlx::sort_strings_detail::lcpKeyDepth(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_stack_, PS5SortStep::substep_add(), TLX_LOGC, and StringPtr< StringSet_ >::with_lcp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort().
void sort_mkqs_cache (const StringPtr & strptr, size_t depth) inline
Definition at line 898 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::bktcache_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::cache_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::depth_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::eq_recurse_, StringPtr< StringSet_ >::fill_lcp(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::idx_, tlx::sort_strings_detail::insertion_sort(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::lcp_eq_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_stack_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::mtimer_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_eq_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_gt_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::num_lt_, MultiTimer::running(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), StringPtr< StringSet_ >::size(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::strptr_, StringPtr< StringSet_ >::sub(), and TLX_LOGC.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort().
void sort_sample_sort (const StringPtr & strptr, size_t depth) inline
Definition at line 444 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::bktcache_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, StringPtr< StringSet_ >::fill_lcp(), tlx::sort_strings_detail::lcpKeyDepth(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::mtimer_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_stack_, TLX_LOGC, and StringPtr< StringSet_ >::with_lcp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::run().
void substep_all_done () inline final virtual
Pure virtual function called by substep when all substeps are done.
Implements PS5SortStep.
Definition at line 1070 of file parallel_sample_sort.hpp.
References PS5SmallsortJob< Context, StringPtr, BktSizeType >::ctx_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::depth_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ms_stack_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::pstep_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_front_, PS5SmallsortJob< Context, StringPtr, BktSizeType >::ss_stack_, PS5SortStep::substep_notify_done(), and TLX_LOGC.
Member Data Documentation
simple_vector<uint8_t> bktcache_
Definition at line 320 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort().
size_t bktcache_size_ = 0
Definition at line 321 of file parallel_sample_sort.hpp.
Context& ctx_
Definition at line 294 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::PS5SmallsortJob(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::~PS5SmallsortJob().
size_t depth_
Definition at line 300 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::PS5SmallsortJob(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
size_t ms_front_ = 0
Definition at line 895 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
std::vector<MKQSStep> ms_stack_
Definition at line 896 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
MultiTimer mtimer_
Definition at line 301 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::~PS5SmallsortJob().
PS5SortStep* pstep_
parent sort step
Definition at line 297 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
size_t ss_front_ = 0
Definition at line 441 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
std::vector<SeqSampleSortStep> ss_stack_
Definition at line 442 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::substep_all_done().
StringPtr strptr_
Definition at line 299 of file parallel_sample_sort.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::PS5SmallsortJob(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::run().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/parallel_sample_sort.hpp