Thrill: AggregateMinMax< Type_ > Class Template Reference
AggregateMinMax< Type_ > Class Template Reference
Math Functions
Detailed Description
template<typename Type_>
class tlx::AggregateMinMax< Type_ >
Calculate running aggregate statistics: feed it with values, and it will keep the minimum and the maximum values.
Definition at line 27 of file aggregate_min_max.hpp.
#include <aggregate_min_max.hpp>
Public Types
using Type = Type_
Public Member Functions
AggregateMinMax ()=default
default constructor
AggregateMinMax (const Type &min, const Type &max) noexcept
initializing constructor
AggregateMinMax & add (const Type &value) noexcept
add a value to the running aggregation
const Type & max () const noexcept
return maximum over all values aggregated
const Type & min () const noexcept
return minimum over all values aggregated
AggregateMinMax operator+ (const AggregateMinMax &a) const noexcept
operator + to combine two AggregateMinMax<>
AggregateMinMax & operator+= (const AggregateMinMax &a) noexcept
operator += to combine two AggregateMinMax<>
template<typename Archive >
void serialize (Archive &archive)
serialization method for cereal.
void set_max (const Type &v) noexcept
change currently aggregated minimum
void set_min (const Type &v) noexcept
change currently aggregated minimum
Type span () const noexcept
return maximum - minimum over all values aggregated
Private Attributes
Type max_ = std::numeric_limits<Type>::lowest()
maximum value
Type min_ = std::numeric_limits<Type>::max()
minimum value
Member Typedef Documentation
using Type = Type_
Definition at line 30 of file aggregate_min_max.hpp.
Constructor & Destructor Documentation
AggregateMinMax () default
default constructor
Referenced by AggregateMinMax< Type_ >::operator+().
AggregateMinMax (const Type & min, const Type & max) inline noexcept
initializing constructor
Definition at line 36 of file aggregate_min_max.hpp.
Member Function Documentation
AggregateMinMax& add (const Type & value) inline noexcept
add a value to the running aggregation
Definition at line 40 of file aggregate_min_max.hpp.
References max(), AggregateMinMax< Type_ >::max_, min(), AggregateMinMax< Type_ >::min_, and gen_data::value.
const Type& max () const inline noexcept
return maximum over all values aggregated
Definition at line 50 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::max_.
const Type& min () const inline noexcept
return minimum over all values aggregated
Definition at line 47 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::min_.
AggregateMinMax operator+ (const AggregateMinMax< Type_ > & a) const inline noexcept
operator + to combine two AggregateMinMax<>
Definition at line 62 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::AggregateMinMax(), max(), AggregateMinMax< Type_ >::max_, min(), and AggregateMinMax< Type_ >::min_.
AggregateMinMax& operator+= (const AggregateMinMax< Type_ > & a) inline noexcept
operator += to combine two AggregateMinMax<>
Definition at line 69 of file aggregate_min_max.hpp.
References max(), AggregateMinMax< Type_ >::max_, min(), and AggregateMinMax< Type_ >::min_.
void serialize (Archive & archive) inline
serialization method for cereal.
Definition at line 77 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::max_, and AggregateMinMax< Type_ >::min_.
void set_max (const Type & v) inline noexcept
change currently aggregated minimum
Definition at line 59 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::max_.
void set_min (const Type & v) inline noexcept
change currently aggregated minimum
Definition at line 56 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::min_.
Type span () const inline noexcept
return maximum - minimum over all values aggregated
Definition at line 53 of file aggregate_min_max.hpp.
References AggregateMinMax< Type_ >::max_, and AggregateMinMax< Type_ >::min_.
Member Data Documentation
Type max_ = std::numeric_limits<Type>::lowest() private
maximum value
Definition at line 86 of file aggregate_min_max.hpp.
Referenced by AggregateMinMax< Type_ >::add(), AggregateMinMax< Type_ >::max(), AggregateMinMax< Type_ >::operator+(), AggregateMinMax< Type_ >::operator+=(), AggregateMinMax< Type_ >::serialize(), AggregateMinMax< Type_ >::set_max(), and AggregateMinMax< Type_ >::span().
Type min_ = std::numeric_limits<Type>::max() private
minimum value
Definition at line 83 of file aggregate_min_max.hpp.
Referenced by AggregateMinMax< Type_ >::add(), AggregateMinMax< Type_ >::min(), AggregateMinMax< Type_ >::operator+(), AggregateMinMax< Type_ >::operator+=(), AggregateMinMax< Type_ >::serialize(), AggregateMinMax< Type_ >::set_min(), and AggregateMinMax< Type_ >::span().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/math/aggregate_min_max.hpp