Thrill: Dispatcher::AsyncReadBuffer Class Reference
Dispatcher::AsyncReadBuffer Class Reference
Detailed Description
Definition at line 798 of file dispatcher.hpp.
#include <dispatcher.hpp>
Public Member Functions
AsyncReadBuffer (Connection &conn, size_t buffer_size, const AsyncReadBufferCallback &callback)
Construct buffered reader with callback.
Buffer & buffer ()
reference to Buffer
void DoCallback ()
bool IsDone () const
bool operator() ()
Should be called when the socket is readable.
Private Attributes
Buffer buffer_
Receive buffer (allocates memory)
AsyncReadBufferCallback callback_
functional object to call once data is complete
Connection * conn_
Connection reference.
size_t size_ = 0
total size currently read
Constructor & Destructor Documentation
AsyncReadBuffer (Connection & conn, size_t buffer_size, const AsyncReadBufferCallback & callback) inline
Construct buffered reader with callback.
Definition at line 802 of file dispatcher.hpp.
Member Function Documentation
Buffer& buffer () inline
reference to Buffer
Definition at line 844 of file dispatcher.hpp.
References Dispatcher::AsyncReadBuffer::buffer_.
void DoCallback () inline
Definition at line 846 of file dispatcher.hpp.
References Dispatcher::AsyncReadBuffer::buffer_, Dispatcher::AsyncReadBuffer::callback_, and Dispatcher::AsyncReadBuffer::conn_.
Referenced by Dispatcher::MpiAsync::operator()(), and Dispatcher::AsyncReadBuffer::operator()().
bool IsDone () const inline
Definition at line 841 of file dispatcher.hpp.
References Dispatcher::AsyncReadBuffer::buffer_, Buffer::size(), and Dispatcher::AsyncReadBuffer::size_.
bool operator() () inline
Should be called when the socket is readable.
Definition at line 810 of file dispatcher.hpp.
References Dispatcher::AsyncReadBuffer::buffer_, Dispatcher::AsyncReadBuffer::callback_, Dispatcher::AsyncReadBuffer::conn_, Buffer::data(), Dispatcher::AsyncReadBuffer::DoCallback(), Connection::RecvOne(), Buffer::size(), Dispatcher::AsyncReadBuffer::size_, and Connection::ToString().
Member Data Documentation
Buffer buffer_ private
Receive buffer (allocates memory)
Definition at line 855 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncReadBuffer::buffer(), Dispatcher::AsyncReadBuffer::DoCallback(), Dispatcher::AsyncReadBuffer::IsDone(), and Dispatcher::AsyncReadBuffer::operator()().
AsyncReadBufferCallback callback_ private
functional object to call once data is complete
Definition at line 861 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncReadBuffer::DoCallback(), and Dispatcher::AsyncReadBuffer::operator()().
Connection* conn_ private
Connection reference.
Definition at line 852 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncReadBuffer::DoCallback(), and Dispatcher::AsyncReadBuffer::operator()().
size_t size_ = 0 private
total size currently read
Definition at line 858 of file dispatcher.hpp.
Referenced by Dispatcher::AsyncReadBuffer::IsDone(), and Dispatcher::AsyncReadBuffer::operator()().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp