Thrill: DiskQueuedFile Class Reference
DiskQueuedFile Class Reference
File I/O Implementations
Detailed Description
Implementation of some file methods based on serving_request.
Definition at line 30 of file disk_queued_file.hpp.
#include <disk_queued_file.hpp>
Public Member Functions
DiskQueuedFile (int queue_id, int allocator_id)
RequestPtr aread (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
RequestPtr awrite (void *buffer, offset_type offset, size_type bytes, const CompletionHandler &on_cmpl=CompletionHandler()) override
int get_allocator_id () const override
Returns the file's disk allocator number.
int get_queue_id () const override
Public Member Functions inherited from FileBase
FileBase (const FileBase &)=delete
non-copyable: delete copy-constructor
FileBase (FileBase &&)=default
move-constructor: default
FileBase (unsigned int device_id=DEFAULT_DEVICE_ID)
Construct a new file, usually called by a subclass.
virtual ~FileBase ()
virtual void close_remove ()
close and remove file
virtual void discard (offset_type offset, offset_type size)
unsigned int get_device_id () const
Returns the file's physical device id.
virtual const char * io_type () const =0
virtual void lock ()=0
Locks file for reading and writing (acquires a lock in the file system).
bool need_alignment () const
Returns need_alignment_.
FileBase & operator= (const FileBase &)=delete
non-copyable: delete assignment operator
FileBase & operator= (FileBase &&)=default
move-assignment operator: default
virtual void serve (void *buffer, offset_type offset, size_type bytes, Request::ReadOrWriteType type)=0
virtual void set_size (offset_type newsize)=0
virtual offset_type size ()=0
Private Attributes
int allocator_id_
int queue_id_
Additional Inherited Members
Public Types inherited from FileBase
using offset_type = Request::offset_type
the offset of a request, also the size of the file
enum OpenMode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128,
REQUIRE_DIRECT = 256
}
using size_type = Request::size_type
the size of a request
Static Public Member Functions inherited from FileBase
static int unlink (const char *path)
unlink path from filesystem
static int truncate (const char *path, size_t length)
Static Public Attributes inherited from FileBase
static constexpr bool debug = false
static constexpr unsigned int DEFAULT_DEVICE_ID = (unsigned int)(-1)
static constexpr int DEFAULT_LINUXAIO_QUEUE = -2
static constexpr int DEFAULT_QUEUE = -1
static constexpr int NO_ALLOCATOR = -1
Protected Attributes inherited from FileBase
unsigned int device_id_
bool need_alignment_ = false
Flag whether read/write operations require alignment.
Constructor & Destructor Documentation
DiskQueuedFile (int queue_id, int allocator_id) inline
Definition at line 35 of file disk_queued_file.hpp.
Member Function Documentation
RequestPtr aread (void * buffer, offset_type offset, size_type bytes, const CompletionHandler & on_cmpl = CompletionHandler()) override virtual
Schedules an asynchronous read request to the file.
Parameters
buffer pointer to memory buffer to read into
offset file position to start read from
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implements FileBase.
Reimplemented in LinuxaioFile.
Definition at line 24 of file disk_queued_file.cpp.
References DiskQueuedFile::get_queue_id(), Singleton< Instance, destroy_on_exit >::GetInstance(), thrill::mem::GPool(), and Request::READ.
RequestPtr awrite (void * buffer, offset_type offset, size_type bytes, const CompletionHandler & on_cmpl = CompletionHandler()) override virtual
Schedules an asynchronous write request to the file.
Parameters
buffer pointer to memory buffer to write from
offset starting file position to write
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implements FileBase.
Reimplemented in LinuxaioFile.
Definition at line 37 of file disk_queued_file.cpp.
References DiskQueuedFile::get_queue_id(), Singleton< Instance, destroy_on_exit >::GetInstance(), thrill::mem::GPool(), and Request::WRITE.
int get_allocator_id () const inline override virtual
Returns the file's disk allocator number.
Implements FileBase.
Definition at line 51 of file disk_queued_file.hpp.
References DiskQueuedFile::allocator_id_.
int get_queue_id () const inline override virtual
Returns the identifier of the file's queue number.
Remarks
Files allocated on the same physical device usually share the same queue, unless there is a common queue (e.g. with linuxaio).
Implements FileBase.
Definition at line 47 of file disk_queued_file.hpp.
References DiskQueuedFile::queue_id_.
Referenced by DiskQueuedFile::aread(), LinuxaioFile::aread(), DiskQueuedFile::awrite(), and LinuxaioFile::awrite().
Member Data Documentation
int allocator_id_ private
Definition at line 32 of file disk_queued_file.hpp.
Referenced by DiskQueuedFile::get_allocator_id().
int queue_id_ private
Definition at line 32 of file disk_queued_file.hpp.
Referenced by DiskQueuedFile::get_queue_id().
The documentation for this class was generated from the following files:
thrill/io/disk_queued_file.hpp
thrill/io/disk_queued_file.cpp