Thrill: write_pool< BlockType > Class Template Reference
write_pool< BlockType > Class Template Reference
Block Scheduling Sublayer
Detailed Description
template<class BlockType>
class foxxll::write_pool< BlockType >
Implements dynamically resizable buffered writing pool.
Definition at line 37 of file write_pool.hpp.
#include <write_pool.hpp>
Classes
struct busy_entry
Public Types
using bid_type = typename block_type::bid_type
using block_type = BlockType
using busy_blocks_iterator = typename std::list< busy_entry >::iterator
using free_blocks_iterator = typename std::list< block_type * >::iterator
Public Member Functions
write_pool (size_t init_size=1)
write_pool (const write_pool &)=delete
non-copyable: delete copy-constructor
~write_pool ()
Waits for completion of all ongoing write requests and frees memory.
void add (block_type *&block)
bool has_request (bid_type bid)
write_pool & operator= (const write_pool &)=delete
non-copyable: delete assignment operator
void resize (size_t new_size)
size_t size () const
Returns number of owned blocks.
block_type * steal ()
std::pair< block_type
*, request_ptr > steal_request (bid_type bid)
void swap (write_pool &obj)
request_ptr write (block_type *&block, bid_type bid)
Protected Member Functions
void check_all_busy ()
Protected Attributes
std::list< busy_entry > busy_blocks
std::list< block_type * > free_blocks
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
using bid_type = typename block_type::bid_type
Definition at line 43 of file write_pool.hpp.
using block_type = BlockType
Definition at line 42 of file write_pool.hpp.
using busy_blocks_iterator = typename std::list<busy_entry>::iterator
Definition at line 60 of file write_pool.hpp.
using free_blocks_iterator = typename std::list<block_type*>::iterator
Definition at line 59 of file write_pool.hpp.
Constructor & Destructor Documentation
write_pool (size_t init_size = 1) inline explicit
Constructs pool.
Parameters
init_size initial number of blocks in the pool
Definition at line 71 of file write_pool.hpp.
References FOXXLL_VERBOSE_WPOOL, and write_pool< BlockType >::free_blocks.
write_pool (const write_pool< BlockType > &) delete
non-copyable: delete copy-constructor
~write_pool () inline
Waits for completion of all ongoing write requests and frees memory.
Definition at line 92 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, FOXXLL_VERBOSE_WPOOL, and write_pool< BlockType >::free_blocks.
Member Function Documentation
void add (block_type *& block) inline
Definition at line 226 of file write_pool.hpp.
References FOXXLL_VERBOSE_WPOOL, and write_pool< BlockType >::free_blocks.
Referenced by read_write_pool< BlockType >::add(), prefetch_pool< BlockType >::hint(), and prefetch_pool< BlockType >::read().
void check_all_busy () inline protected
Definition at line 234 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, FOXXLL_VERBOSE_WPOOL, and write_pool< BlockType >::free_blocks.
Referenced by write_pool< BlockType >::steal().
bool has_request (bid_type bid) inline
Definition at line 194 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks.
Referenced by prefetch_pool< BlockType >::hint(), and prefetch_pool< BlockType >::read().
write_pool& operator= (const write_pool< BlockType > &) delete
non-copyable: delete assignment operator
void resize (size_t new_size) inline
Resizes size of the pool.
Parameters
new_size new size of the pool after the call
Definition at line 176 of file write_pool.hpp.
References FOXXLL_VERBOSE_WPOOL, write_pool< BlockType >::free_blocks, write_pool< BlockType >::size(), and write_pool< BlockType >::steal().
Referenced by read_write_pool< BlockType >::resize_write().
size_t size () const inline
Returns number of owned blocks.
Definition at line 122 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, and write_pool< BlockType >::free_blocks.
Referenced by write_pool< BlockType >::resize(), read_write_pool< BlockType >::size_write(), and write_pool< BlockType >::steal().
block_type* steal () inline
Take out a block from the pool.
Returns
pointer to the block. Ownership of the block goes to the caller.
Definition at line 153 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, write_pool< BlockType >::check_all_busy(), FOXXLL_VERBOSE_WPOOL, write_pool< BlockType >::free_blocks, write_pool< BlockType >::size(), and foxxll::wait_any().
Referenced by write_pool< BlockType >::resize(), and read_write_pool< BlockType >::steal().
std::pair<block_type*, request_ptr> steal_request (bid_type bid) inline
Definition at line 205 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, and FOXXLL_VERBOSE_WPOOL.
Referenced by prefetch_pool< BlockType >::hint(), and prefetch_pool< BlockType >::read().
void swap (write_pool< BlockType > & obj) inline
Definition at line 85 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, and write_pool< BlockType >::free_blocks.
request_ptr write (block_type *& block, bid_type bid) inline
Passes a block to the pool for writing.
Parameters
block block to write. Ownership of the block goes to the pool. block must be allocated dynamically with using new .
bid location, where to write
Warning
block must be allocated dynamically with using new .
Returns
request object of the write operation
Definition at line 130 of file write_pool.hpp.
References write_pool< BlockType >::busy_blocks, and FOXXLL_VERBOSE_WPOOL.
Referenced by read_write_pool< BlockType >::write().
Member Data Documentation
std::list<busy_entry> busy_blocks protected
Definition at line 66 of file write_pool.hpp.
Referenced by write_pool< BlockType >::check_all_busy(), write_pool< BlockType >::has_request(), write_pool< BlockType >::size(), write_pool< BlockType >::steal(), write_pool< BlockType >::steal_request(), write_pool< BlockType >::swap(), write_pool< BlockType >::write(), and write_pool< BlockType >::~write_pool().
constexpr bool debug = false static private
Definition at line 39 of file write_pool.hpp.
std::list<block_type*> free_blocks protected
Definition at line 64 of file write_pool.hpp.
Referenced by write_pool< BlockType >::add(), write_pool< BlockType >::check_all_busy(), write_pool< BlockType >::resize(), write_pool< BlockType >::size(), write_pool< BlockType >::steal(), write_pool< BlockType >::swap(), write_pool< BlockType >::write_pool(), and write_pool< BlockType >::~write_pool().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/write_pool.hpp