Thrill: AsyncReadBuffer Class Reference
AsyncReadBuffer Class Reference
Thrill Layers » Network Subsystem Layer
Detailed Description
Definition at line 66 of file dispatcher.hpp.
#include <dispatcher.hpp>
Public Member Functions
AsyncReadBuffer (Connection &conn, size_t buffer_size, const AsyncReadBufferCallback &callback)
Construct buffered reader with callback.
AsyncReadBuffer (const AsyncReadBuffer &)=delete
non-copyable: delete copy-constructor
AsyncReadBuffer (AsyncReadBuffer &&)=default
move-constructor: default
~AsyncReadBuffer ()
Buffer & buffer ()
reference to Buffer
Connection * connection () const
Returns conn_.
uint8_t * data ()
underlying buffer pointer
const uint8_t * data () const
underlying buffer pointer
void DoCallback ()
void DoCallback (size_t size_check)
bool IsDone () const
bool operator() ()
Should be called when the socket is readable.
AsyncReadBuffer & operator= (const AsyncReadBuffer &)=delete
non-copyable: delete assignment operator
AsyncReadBuffer & operator= (AsyncReadBuffer &&)=default
move-assignment operator: default
size_t size () const
underlying buffer size
Private Attributes
Buffer buffer_
Receive buffer (allocates memory)
AsyncReadBufferCallback callback_
functional object to call once data is complete
Connection * conn_
Connection reference.
size_t read_size_ = 0
total size currently read
Constructor & Destructor Documentation
AsyncReadBuffer() [1/3]
AsyncReadBuffer (Connection & conn, size_t buffer_size, const AsyncReadBufferCallback & callback) inline
Construct buffered reader with callback.
Definition at line 70 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, AsyncReadBuffer::conn_, LOGC, AsyncReadBuffer::operator=(), Connection::rx_active_, and Buffer::size().
AsyncReadBuffer() [2/3]
AsyncReadBuffer (const AsyncReadBuffer &) delete
non-copyable: delete copy-constructor
AsyncReadBuffer() [3/3]
AsyncReadBuffer (AsyncReadBuffer &&) default
move-constructor: default
~AsyncReadBuffer()
~AsyncReadBuffer () inline
Definition at line 90 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, LOGC, and Buffer::size().
Member Function Documentation
buffer()
Buffer& buffer () inline
reference to Buffer
Definition at line 137 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_.
Referenced by Dispatcher::AsyncWrite().
connection()
Connection* connection () const inline
Returns conn_.
Definition at line 152 of file dispatcher.hpp.
References AsyncReadBuffer::conn_.
Referenced by Dispatcher::PerformAsync().
data() [1/2]
uint8_t* data () inline
underlying buffer pointer
Definition at line 155 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, and Buffer::data().
Referenced by Dispatcher::PerformAsync().
data() [2/2]
const uint8_t* data () const inline
underlying buffer pointer
Definition at line 158 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, and Buffer::data().
DoCallback() [1/2]
void DoCallback () inline
Definition at line 139 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, AsyncReadBuffer::callback_, and AsyncReadBuffer::conn_.
Referenced by AsyncReadBuffer::DoCallback(), AsyncReadByteBlock::DoCallback(), AsyncReadBuffer::operator()(), AsyncWriteBuffer::operator()(), AsyncReadByteBlock::operator()(), and AsyncWriteBlock::operator()().
DoCallback() [2/2]
void DoCallback (size_t size_check) inline
Definition at line 146 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, die_unequal, AsyncReadBuffer::DoCallback(), and Buffer::size().
IsDone()
bool IsDone () const inline
Definition at line 134 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, AsyncReadBuffer::read_size_, and Buffer::size().
operator()()
bool operator() () inline
Should be called when the socket is readable.
Definition at line 97 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, AsyncReadBuffer::callback_, AsyncReadBuffer::conn_, Buffer::data(), AsyncReadBuffer::DoCallback(), LOGC, AsyncReadBuffer::read_size_, Connection::RecvOne(), Connection::rx_active_, Buffer::size(), and Connection::ToString().
operator=() [1/2]
AsyncReadBuffer& operator= (const AsyncReadBuffer &) delete
non-copyable: delete assignment operator
Referenced by AsyncReadBuffer::AsyncReadBuffer(), AsyncReadByteBlock::AsyncReadByteBlock(), AsyncWriteBlock::AsyncWriteBlock(), and AsyncWriteBuffer::AsyncWriteBuffer().
operator=() [2/2]
AsyncReadBuffer& operator= (AsyncReadBuffer &&) default
move-assignment operator: default
size()
size_t size () const inline
underlying buffer size
Definition at line 161 of file dispatcher.hpp.
References AsyncReadBuffer::buffer_, and Buffer::size().
Referenced by Dispatcher::PerformAsync().
Member Data Documentation
buffer_
Buffer buffer_ private
Receive buffer (allocates memory)
Definition at line 168 of file dispatcher.hpp.
Referenced by AsyncReadBuffer::AsyncReadBuffer(), AsyncWriteBuffer::AsyncWriteBuffer(), AsyncReadBuffer::buffer(), AsyncReadBuffer::data(), AsyncWriteBuffer::data(), AsyncReadBuffer::DoCallback(), AsyncReadBuffer::IsDone(), AsyncWriteBuffer::IsDone(), AsyncReadBuffer::operator()(), AsyncWriteBuffer::operator()(), AsyncReadBuffer::size(), AsyncWriteBuffer::size(), AsyncReadBuffer::~AsyncReadBuffer(), and AsyncWriteBuffer::~AsyncWriteBuffer().
callback_
AsyncReadBufferCallback callback_ private
functional object to call once data is complete
Definition at line 174 of file dispatcher.hpp.
Referenced by AsyncReadBuffer::DoCallback(), AsyncWriteBuffer::DoCallback(), AsyncReadByteBlock::DoCallback(), AsyncWriteBlock::DoCallback(), and AsyncReadBuffer::operator()().
conn_
Connection* conn_ private
Connection reference.
Definition at line 165 of file dispatcher.hpp.
Referenced by AsyncReadBuffer::AsyncReadBuffer(), AsyncReadByteBlock::AsyncReadByteBlock(), AsyncWriteBlock::AsyncWriteBlock(), AsyncWriteBuffer::AsyncWriteBuffer(), AsyncReadBuffer::connection(), AsyncWriteBuffer::connection(), AsyncReadByteBlock::connection(), AsyncWriteBlock::connection(), AsyncReadBuffer::DoCallback(), AsyncWriteBuffer::DoCallback(), AsyncReadByteBlock::DoCallback(), AsyncWriteBlock::DoCallback(), AsyncReadBuffer::operator()(), AsyncWriteBuffer::operator()(), AsyncReadByteBlock::operator()(), and AsyncWriteBlock::operator()().
read_size_
size_t read_size_ = 0 private
total size currently read
Definition at line 171 of file dispatcher.hpp.
Referenced by AsyncReadBuffer::IsDone(), and AsyncReadBuffer::operator()().
The documentation for this class was generated from the following file:
thrill/net/dispatcher.hpp