Thrill: DiskQueues Class Reference
DiskQueues Class Reference
I/O Requests and Queues
Detailed Description
Encapsulates disk queues.
Remarks
is a singleton
Definition at line 34 of file disk_queues.hpp.
#include <disk_queues.hpp>
Public Types
using DiskId = int64_t
Public Member Functions
~DiskQueues ()
void AddRequest (RequestPtr &req, DiskId disk)
bool CancelRequest (Request *req, DiskId disk)
Cancel a request.
RequestQueue * GetQueue (DiskId disk)
void MakeQueue (const FileBasePtr &file)
void SetPriorityOp (RequestQueue::PriorityOp op)
Public Member Functions inherited from Singleton< Instance, destroy_on_exit >
Singleton ()=default
Singleton (const Singleton &)=delete
non-copyable: delete copy-constructor
Singleton (Singleton &&)=default
move-constructor: default
Singleton & operator= (const Singleton &)=delete
non-copyable: delete assignment operator
Singleton & operator= (Singleton &&)=default
move-assignment operator: default
Protected Member Functions
DiskQueues ()
Private Attributes
std::unique_ptr< Data > d_
Additional Inherited Members
Static Public Member Functions inherited from Singleton< Instance, destroy_on_exit >
static instance_pointer GetInstance ()
Member Typedef Documentation
using DiskId = int64_t
Definition at line 46 of file disk_queues.hpp.
Constructor & Destructor Documentation
DiskQueues () protected
Definition at line 37 of file disk_queues.cpp.
References Singleton< Stats >::GetInstance().
~DiskQueues ()
Definition at line 43 of file disk_queues.cpp.
References DiskQueues::d_.
Member Function Documentation
void AddRequest (RequestPtr & req, DiskId disk)
Definition at line 67 of file disk_queues.cpp.
References RequestQueue::AddRequest(), DiskQueues::d_, and CountingPtr< Type, Deleter >::get().
bool CancelRequest (Request * req, DiskId disk)
Cancel a request.
The specified request is canceled unless already being processed. However, cancelation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
Parameters
req request to cancel
disk disk number for disk that req was scheduled on
Returns
true iff the request was canceled successfully
Definition at line 91 of file disk_queues.cpp.
References DiskQueues::d_.
RequestQueue * GetQueue (DiskId disk)
Definition at line 101 of file disk_queues.cpp.
References DiskQueues::d_.
void MakeQueue (const FileBasePtr & file)
Definition at line 49 of file disk_queues.cpp.
References DiskQueues::d_, and CountingPtr< Type, Deleter >::get().
void SetPriorityOp (RequestQueue::PriorityOp op)
Changes requests priorities.
Parameters
op one of:
READ, read requests are served before write requests within a disk queue
WRITE, write requests are served before read requests within a disk queue
NONE, read and write requests are served by turns, alternately
Definition at line 108 of file disk_queues.cpp.
References DiskQueues::d_.
Member Data Documentation
std::unique_ptr<Data> d_ private
Definition at line 39 of file disk_queues.hpp.
Referenced by DiskQueues::AddRequest(), DiskQueues::CancelRequest(), DiskQueues::GetQueue(), DiskQueues::MakeQueue(), DiskQueues::SetPriorityOp(), and DiskQueues::~DiskQueues().
The documentation for this class was generated from the following files:
thrill/io/disk_queues.hpp
thrill/io/disk_queues.cpp