Thrill: StackAllocator< Type, Size > Class Template Reference
StackAllocator< Type, Size > Class Template Reference
Detailed Description
template<typename Type, size_t Size>
class tlx::StackAllocator< Type, Size >
Definition at line 114 of file stack_allocator.hpp.
#include <stack_allocator.hpp>
Classes
struct rebind
required rebind.
Public Types
using const_pointer = const Type *
using const_reference = const Type &
using difference_type = std::ptrdiff_t
using is_always_equal = std::false_type
C++11 type flag.
using pointer = Type *
using reference = Type &
using size_type = std::size_t
using value_type = Type
Public Types inherited from AllocatorBase< Type >
using const_pointer = const Type *
using const_reference = const Type &
using difference_type = std::ptrdiff_t
using is_always_equal = std::true_type
C++11 type flag.
using pointer = Type *
using propagate_on_container_move_assignment = std::true_type
C++11 type flag.
using reference = Type &
using size_type = std::size_t
using value_type = Type
Public Member Functions
StackAllocator () noexcept
default constructor to invalid arena
StackAllocator (StackArena< Size > &arena) noexcept
constructor with explicit arena reference
template<typename Other >
StackAllocator (const StackAllocator< Other, Size > &other) noexcept
constructor from another allocator with same arena size
StackAllocator (const StackAllocator &) noexcept=default
copy-constructor: default
StackAllocator (StackAllocator &&) noexcept=default
move-constructor: default
pointer allocate (size_t n)
allocate method: get memory from arena
void deallocate (pointer p, size_t n) noexcept
deallocate method: release from arena
template<typename Other , size_t OtherSize>
bool operator!= (const StackAllocator< Other, OtherSize > &other) const noexcept
StackAllocator & operator= (const StackAllocator &) noexcept=default
copy-assignment: default
StackAllocator & operator= (StackAllocator &&) noexcept=default
move-assignment: default
template<typename Other , size_t OtherSize>
bool operator== (const StackAllocator< Other, OtherSize > &other) const noexcept
Public Member Functions inherited from AllocatorBase< Type >
pointer address (reference x) const noexcept
Returns the address of x.
const_pointer address (const_reference x) const noexcept
Returns the address of x.
void construct (pointer p, const_reference value)
Constructs an element object on the location pointed by p.
template<typename SubType , typename... Args>
void construct (SubType *p, Args &&... args)
Constructs an element object on the location pointed by p.
void destroy (pointer p) const noexcept
Destroys in-place the object pointed by p.
template<typename SubType >
void destroy (SubType *p) const noexcept
Destroys in-place the object pointed by p.
size_type max_size () const noexcept
Maximum size possible to allocate.
Private Attributes
StackArena< Size > * arena_
Member Typedef Documentation
const_pointer
using const_pointer = const Type *
Definition at line 119 of file stack_allocator.hpp.
const_reference
using const_reference = const Type&
Definition at line 121 of file stack_allocator.hpp.
difference_type
using difference_type = std::ptrdiff_t
Definition at line 123 of file stack_allocator.hpp.
is_always_equal
using is_always_equal = std::false_type
C++11 type flag.
Definition at line 126 of file stack_allocator.hpp.
pointer
using pointer = Type *
Definition at line 118 of file stack_allocator.hpp.
reference
using reference = Type&
Definition at line 120 of file stack_allocator.hpp.
size_type
using size_type = std::size_t
Definition at line 122 of file stack_allocator.hpp.
value_type
using value_type = Type
Definition at line 117 of file stack_allocator.hpp.
Constructor & Destructor Documentation
StackAllocator() [1/5]
StackAllocator () inline noexcept
default constructor to invalid arena
Definition at line 133 of file stack_allocator.hpp.
StackAllocator() [2/5]
StackAllocator (StackArena< Size > & arena) inline explicit noexcept
constructor with explicit arena reference
Definition at line 136 of file stack_allocator.hpp.
StackAllocator() [3/5]
StackAllocator (const StackAllocator< Other, Size > & other) inline noexcept
constructor from another allocator with same arena size
Definition at line 141 of file stack_allocator.hpp.
References StackArena< Size >::operator=().
StackAllocator() [4/5]
StackAllocator (const StackAllocator< Type, Size > &) default noexcept
copy-constructor: default
StackAllocator() [5/5]
StackAllocator (StackAllocator< Type, Size > &&) default noexcept
move-constructor: default
Member Function Documentation
allocate()
pointer allocate (size_t n) inline
allocate method: get memory from arena
Definition at line 159 of file stack_allocator.hpp.
deallocate()
void deallocate (pointer p, size_t n) inline noexcept
deallocate method: release from arena
Definition at line 164 of file stack_allocator.hpp.
References StackAllocator< Type, Size >::deallocate(), and StackArena< Size >::AlignmentHelper::p.
Referenced by StackAllocator< Type, Size >::deallocate().
operator!=()
bool operator!= (const StackAllocator< Other, OtherSize > & other) const inline noexcept
Definition at line 175 of file stack_allocator.hpp.
References tlx::operator==().
operator=() [1/2]
StackAllocator& operator= (const StackAllocator< Type, Size > &) default noexcept
copy-assignment: default
operator=() [2/2]
StackAllocator& operator= (StackAllocator< Type, Size > &&) default noexcept
move-assignment: default
operator==()
bool operator== (const StackAllocator< Other, OtherSize > & other) const inline noexcept
Definition at line 169 of file stack_allocator.hpp.
References StackAllocator< Type, Size >::arena_.
Member Data Documentation
arena_
StackArena<Size>* arena_ private
Definition at line 184 of file stack_allocator.hpp.
Referenced by StackAllocator< Type, Size >::operator==().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/stack_allocator.hpp