Thrill: file_stats::scoped_write_timer Class Reference
file_stats::scoped_write_timer Class Reference
Detailed Description
Definition at line 112 of file iostats.hpp.
#include <iostats.hpp>
Public Member Functions
scoped_write_timer (file_stats *file_stats, size_type size)
~scoped_write_timer ()
void start (size_type size)
void stop ()
Private Types
using size_type = size_t
Private Attributes
file_stats & file_stats_
bool running_ = false
Member Typedef Documentation
size_type
using size_type = size_t private
Definition at line 114 of file iostats.hpp.
Constructor & Destructor Documentation
scoped_write_timer()
scoped_write_timer (file_stats * file_stats, size_type size) inline explicit
Definition at line 120 of file iostats.hpp.
References file_stats::scoped_read_write_timer::start().
~scoped_write_timer()
~scoped_write_timer () inline
Definition at line 126 of file iostats.hpp.
References file_stats::scoped_read_write_timer::stop().
Member Function Documentation
start()
void start (size_type size) inline
Definition at line 131 of file iostats.hpp.
References file_stats::write_started().
stop()
void stop () inline
Definition at line 139 of file iostats.hpp.
References file_stats::write_finished().
Member Data Documentation
file_stats_
file_stats& file_stats_ private
Definition at line 115 of file iostats.hpp.
running_
bool running_ = false private
Definition at line 117 of file iostats.hpp.
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/io/iostats.hpp