Thrill: StringPtr< StringSet_ > Class Template Reference
StringPtr< StringSet_ > Class Template Reference
Detailed Description
template<typename StringSet_>
class tlx::sort_strings_detail::StringPtr< StringSet_ >
Objectified string array pointer array.
Definition at line 47 of file string_ptr.hpp.
#include <string_ptr.hpp>
Public Types
typedef StringSet::String String
typedef StringSet_ StringSet
typedef StringShadowPtr< StringSet_ > WithShadow
objectified string and shadow pointer class
Public Member Functions
StringPtr (const StringSet &ss)
constructor specifying all attributes
const StringSet & active () const
return currently active array
WithShadow add_shadow (const StringSet &shadow) const
construct objectified string and shadow pointer class
template<typename LcpType >
void fill_lcp (const LcpType &) const
fill entire LCP array with v, excluding the first lcp[0] position!
template<typename LcpType >
void set_lcp (size_t, const LcpType &) const
set the i-th lcp to v and check its value
size_t size () const
return valid length
StringPtr sub (size_t offset, size_t sub_size) const
Advance (both) pointers by given offset, return sub-array.
Static Public Attributes
static const bool with_lcp = false
if we want to save the LCPs
Protected Attributes
StringSet active_
strings (front) array
Member Typedef Documentation
String
typedef StringSet::String String
Definition at line 51 of file string_ptr.hpp.
StringSet
typedef StringSet_ StringSet
Definition at line 50 of file string_ptr.hpp.
WithShadow
typedef StringShadowPtr<StringSet_> WithShadow
objectified string and shadow pointer class
Definition at line 86 of file string_ptr.hpp.
Constructor & Destructor Documentation
StringPtr()
StringPtr (const StringSet & ss) inline
constructor specifying all attributes
Definition at line 59 of file string_ptr.hpp.
Referenced by StringPtr< StringSet_ >::sub().
Member Function Documentation
active()
const StringSet& active () const inline
return currently active array
Definition at line 63 of file string_ptr.hpp.
References StringPtr< StringSet_ >::active_.
Referenced by PS5BigSortStep< Context, StringPtr >::count(), PS5BigSortStep< Context, StringPtr >::distribute(), tlx::sort_strings_detail::insertion_sort(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache_block(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::MKQSStep(), tlx::sort_strings_detail::multikey_quicksort(), tlx::sort_strings_detail::parallel_sample_sort_params(), tlx::sort_strings_detail::ps5_sample_sort_lcp(), tlx::sort_strings_detail::radixsort_CE0(), tlx::sort_strings_detail::radixsort_CE2(), tlx::sort_strings_detail::radixsort_CE3(), RadixStep_CI2< StringPtr >::RadixStep_CI2(), RadixStep_CI3< StringPtr >::RadixStep_CI3(), PS5BigSortStep< Context, StringPtr >::sample(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::SeqSampleSortStep().
add_shadow()
StringShadowPtr< StringSet_ > add_shadow (const StringSet & shadow) const
construct objectified string and shadow pointer class
Definition at line 343 of file string_ptr.hpp.
References StringPtr< StringSet_ >::active_.
Referenced by tlx::sort_strings_detail::radixsort_CE0(), tlx::sort_strings_detail::radixsort_CE2(), and tlx::sort_strings_detail::radixsort_CE3().
fill_lcp()
void fill_lcp (const LcpType &) const inline
fill entire LCP array with v, excluding the first lcp[0] position!
Definition at line 83 of file string_ptr.hpp.
Referenced by PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort().
set_lcp()
void set_lcp (size_t , const LcpType &) const inline
set the i-th lcp to v and check its value
Definition at line 79 of file string_ptr.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::calculate_lcp(), StringLcpPtr< StringSet_, LcpType_ >::fill_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::fill_lcp(), tlx::sort_strings_detail::insertion_sort(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache(), tlx::sort_strings_detail::multikey_quicksort(), tlx::sort_strings_detail::ps5_sample_sort_lcp(), tlx::sort_strings_detail::radixsort_CI3(), RadixStep_CI2< StringPtr >::RadixStep_CI2(), and RadixStep_CI3< StringPtr >::RadixStep_CI3().
size()
size_t size () const inline
return valid length
Definition at line 66 of file string_ptr.hpp.
Referenced by PS5BigSortStep< Context, StringPtr >::count(), PS5BigSortStep< Context, StringPtr >::count_finished(), PS5BigSortStep< Context, StringPtr >::distribute(), PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5Context< Parameters >::enqueue(), StringLcpPtr< StringSet_, LcpType_ >::fill_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::fill_lcp(), StringShadowPtr< StringSet_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringLcpPtr< StringSet_, LcpType_ >::get_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::get_lcp(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache_block(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::MKQSStep(), tlx::sort_strings_detail::parallel_sample_sort_base(), PS5BigSortStep< Context, StringPtr >::PS5BigSortStep(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::PS5SmallsortJob(), tlx::sort_strings_detail::radixsort_CI2(), tlx::sort_strings_detail::radixsort_CI3(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::run(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::SeqSampleSortStep(), StringLcpPtr< StringSet_, LcpType_ >::set_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::set_lcp(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache(), StringPtr< StringSet_ >::sub(), StringLcpPtr< StringSet_, LcpType_ >::sub(), StringShadowPtr< StringSet_ >::sub(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
sub()
StringPtr sub (size_t offset, size_t sub_size) const inline
Advance (both) pointers by given offset, return sub-array.
Definition at line 69 of file string_ptr.hpp.
References StringPtr< StringSet_ >::size(), and StringPtr< StringSet_ >::StringPtr().
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::mkqs_free_work(), tlx::sort_strings_detail::multikey_quicksort(), tlx::sort_strings_detail::radixsort_CI2(), tlx::sort_strings_detail::radixsort_CI3(), and PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_mkqs_cache().
Member Data Documentation
active_
StringSet active_ protected
strings (front) array
Definition at line 55 of file string_ptr.hpp.
Referenced by StringPtr< StringSet_ >::active(), StringLcpPtr< StringSet_, LcpType_ >::active(), StringShadowPtr< StringSet_ >::active(), StringShadowLcpPtr< StringSet_, LcpType_ >::active(), StringPtr< StringSet_ >::add_shadow(), and StringLcpPtr< StringSet_, LcpType_ >::add_shadow().
with_lcp
const bool with_lcp = false static
if we want to save the LCPs
Definition at line 75 of file string_ptr.hpp.
Referenced by PS5SmallsortJob< Context, StringPtr, BktSizeType >::SeqSampleSortStep::calculate_lcp(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::calculate_lcp(), PS5BigSortStep< Context, StringPtr >::distribute_finished(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::insertion_sort_cache(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::MKQSStep::MKQSStep(), RadixStep_CI2< StringPtr >::RadixStep_CI2(), RadixStep_CI3< StringPtr >::RadixStep_CI3(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sample_sort_free_work(), PS5SmallsortJob< Context, StringPtr, BktSizeType >::sort_sample_sort(), and PS5BigSortStep< Context, StringPtr >::substep_all_done().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/string_ptr.hpp