Thrill: Group Class Reference
Group Class Reference final
MPI Network API
Detailed Description
A net group backed by virtual MPI connection.
As MPI already sets up communication, not much is done. Each Group communicates using a unique MPI tag, the group id. Each host's rank within the group is plaining its MPI rank.
Definition at line 137 of file group.hpp.
#include <group.hpp>
Public Member Functions
Base Functions
Group (size_t my_rank, int group_tag, size_t group_size, DispatcherThread &dispatcher)
Initialize a Group for the given size and rank.
int group_tag () const
return MPI tag used to communicate
size_t num_hosts () const final
number of hosts configured.
DispatcherThread & dispatcher ()
reference to the main MPI dispatcher thread
net::Connection & connection (size_t peer) final
Return Connection to client id.
void Close () final
Close.
size_t num_parallel_async () const final
Number of parallel sends or recvs requests supported by net backend.
std::unique_ptr< net::Dispatcher > ConstructDispatcher () const final
void Barrier ()
run a MPI_Barrier() for synchronization.
Public Member Functions inherited from Group
Group (size_t my_rank)
initializing constructor
Group (const Group &)=delete
non-copyable: delete copy-constructor
Group (Group &&)=default
move-constructor: default
virtual ~Group ()
virtual destructor
template<>
void AllReduce (int &value, std::plus< int >)
template<>
void AllReduce (int &value, common::minimum< int >)
template<>
void AllReduce (int &value, common::maximum< int >)
template<>
void AllReduce (unsigned int &value, std::plus< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::minimum< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::maximum< unsigned int >)
template<>
void AllReduce (long &value, std::plus< long >)
template<>
void AllReduce (long &value, common::minimum< long >)
template<>
void AllReduce (long &value, common::maximum< long >)
template<>
void AllReduce (unsigned long &value, std::plus< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::minimum< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::maximum< unsigned long >)
template<>
void AllReduce (long long &value, std::plus< long long >)
template<>
void AllReduce (long long &value, common::minimum< long long >)
template<>
void AllReduce (long long &value, common::maximum< long long >)
template<>
void AllReduce (unsigned long long &value, std::plus< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::minimum< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::maximum< unsigned long long >)
template<>
void Broadcast (int &value, size_t origin)
template<>
void Broadcast (unsigned int &value, size_t origin)
template<>
void Broadcast (long &value, size_t origin)
template<>
void Broadcast (unsigned long &value, size_t origin)
template<>
void Broadcast (long long &value, size_t origin)
template<>
void Broadcast (unsigned long long &value, size_t origin)
template<>
void ExPrefixSum (int &value, std::plus< int >, const int &initial)
template<>
void ExPrefixSum (unsigned int &value, std::plus< unsigned int >, const unsigned int &initial)
template<>
void ExPrefixSum (long &value, std::plus< long >, const long &initial)
template<>
void ExPrefixSum (unsigned long &value, std::plus< unsigned long >, const unsigned long &initial)
template<>
void ExPrefixSum (long long &value, std::plus< long long >, const long long &initial)
template<>
void ExPrefixSum (unsigned long long &value, std::plus< unsigned long long >, const unsigned long long &initial)
Group & operator= (const Group &)=delete
non-copyable: delete assignment operator
Group & operator= (Group &&)=default
move-assignment operator: default
template<>
void PrefixSum (int &value, std::plus< int >, const int &initial)
template<>
void PrefixSum (unsigned int &value, std::plus< unsigned int >, const unsigned int &initial)
template<>
void PrefixSum (long &value, std::plus< long >, const long &initial)
template<>
void PrefixSum (unsigned long &value, std::plus< unsigned long >, const unsigned long &initial)
template<>
void PrefixSum (long long &value, std::plus< long long >, const long long &initial)
template<>
void PrefixSum (unsigned long long &value, std::plus< unsigned long long >, const unsigned long long &initial)
size_t my_host_rank () const
Return our rank among hosts in this group.
size_t OneFactorSize () const
Number of of 1-factor iterations.
size_t OneFactorPeer (size_t round) const
template<typename T >
void SendTo (size_t dest, const T &data)
Sends a serializable type to the given peer.
template<typename T >
void ReceiveFrom (size_t src, T *data)
Receives a serializable type from the given peer.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSum (T &value, BinarySumOp sum_op=BinarySumOp(), const T &initial=T())
Calculate inclusive prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void ExPrefixSum (T &value, BinarySumOp sum_op=BinarySumOp(), const T &initial=T())
Calculate exclusive prefix sum.
template<typename T >
void Broadcast (T &value, size_t origin=0)
Broadcast a value from the worker "origin".
template<typename T , typename BinarySumOp = std::plus<T>>
void Reduce (T &value, size_t root=0, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to the worker 0.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduce (T &value, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to all workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumSelect (T &value, BinarySumOp sum_op=BinarySumOp(), const T &initial=T(), bool inclusive=true)
select prefixsum implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumDoubling (T &value, BinarySumOp sum_op=BinarySumOp(), const T &initial=T(), bool inclusive=true)
Calculate for every worker his prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate for every worker his prefix sum.
template<typename T >
void BroadcastSelect (T &value, size_t origin=0)
select broadcast implementation (often due to total number of processors)
template<typename T >
void BroadcastTrivial (T &value, size_t origin=0)
Broadcasts the value of the peer with index 0 to all the others.
template<typename T >
void BroadcastBinomialTree (T &value, size_t origin=0)
Broadcasts the value of the worker with index "origin" to all the others.
template<typename T >
void AllGatherRecursiveDoublingPowerOfTwo (T *values, size_t n)
template<typename T >
void AllGatherBruck (T *values, size_t n)
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSelect (T &value, BinarySumOp sum_op=BinarySumOp())
select allreduce implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSimple (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce on the workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceAtRoot (T &value, BinarySumOp sum_op=BinarySumOp())
Broadcasts the value of the peer with index 0 to all the others.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce for powers of two.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceElimination (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce using the elimination protocol described in R.
Private Member Functions
template<typename MpiCall >
void WaitForRequest (MpiCall call)
Virtual Synchronous Collectives to Override Implementations
void PrefixSumPlusInt (int &value, const int &initial) final
void ExPrefixSumPlusInt (int &value, const int &initial) final
void BroadcastInt (int &value, size_t origin) final
void AllReducePlusInt (int &value) final
void AllReduceMinimumInt (int &value) final
void AllReduceMaximumInt (int &value) final
void PrefixSumPlusUnsignedInt (unsigned int &value, const unsigned int &initial) final
void ExPrefixSumPlusUnsignedInt (unsigned int &value, const unsigned int &initial) final
void BroadcastUnsignedInt (unsigned int &value, size_t origin) final
void AllReducePlusUnsignedInt (unsigned int &value) final
void AllReduceMinimumUnsignedInt (unsigned int &value) final
void AllReduceMaximumUnsignedInt (unsigned int &value) final
void PrefixSumPlusLong (long &value, const long &initial) final
void ExPrefixSumPlusLong (long &value, const long &initial) final
void BroadcastLong (long &value, size_t origin) final
void AllReducePlusLong (long &value) final
void AllReduceMinimumLong (long &value) final
void AllReduceMaximumLong (long &value) final
void PrefixSumPlusUnsignedLong (unsigned long &value, const unsigned long &initial) final
void ExPrefixSumPlusUnsignedLong (unsigned long &value, const unsigned long &initial) final
void BroadcastUnsignedLong (unsigned long &value, size_t origin) final
void AllReducePlusUnsignedLong (unsigned long &value) final
void AllReduceMinimumUnsignedLong (unsigned long &value) final
void AllReduceMaximumUnsignedLong (unsigned long &value) final
void PrefixSumPlusLongLong (long long &value, const long long &initial) final
void ExPrefixSumPlusLongLong (long long &value, const long long &initial) final
void BroadcastLongLong (long long &value, size_t origin) final
void AllReducePlusLongLong (long long &value) final
void AllReduceMinimumLongLong (long long &value) final
void AllReduceMaximumLongLong (long long &value) final
void PrefixSumPlusUnsignedLongLong (unsigned long long &value, const unsigned long long &initial) final
void ExPrefixSumPlusUnsignedLongLong (unsigned long long &value, const unsigned long long &initial) final
void BroadcastUnsignedLongLong (unsigned long long &value, size_t origin) final
void AllReducePlusUnsignedLongLong (unsigned long long &value) final
void AllReduceMinimumUnsignedLongLong (unsigned long long &value) final
void AllReduceMaximumUnsignedLongLong (unsigned long long &value) final
Private Attributes
std::vector< Connection > conns_
vector of virtual connection objects to remote peers
DispatcherThread & dispatcher_
reference to the main MPI dispatcher thread
int group_tag_
this group's MPI tag
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Protected Member Functions inherited from Group
template<typename T , typename BinarySumOp >
T SendReceiveReduce (size_t peer, const T &value, BinarySumOp sum_op)
Helper method for AllReduce().
template<typename T , typename BinarySumOp >
void AllReduceEliminationProcess (size_t host_id, size_t group_size, size_t remaining_hosts, size_t send_to, T &value, BinarySumOp sum_op)
Helper method for AllReduce().
Protected Attributes inherited from Group
size_t my_rank_
our rank in the network group
Constructor & Destructor Documentation
Group (size_t my_rank, int group_tag, size_t group_size, DispatcherThread & dispatcher) inline
Initialize a Group for the given size and rank.
Definition at line 146 of file group.hpp.
References Group::conns_, and thrill::net::mpi::Initialize().
Member Function Documentation
void AllReduceMaximumInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 354 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMaximumLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 460 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMaximumLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 566 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMaximumUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 407 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMaximumUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 513 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMaximumUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 619 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 345 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 451 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 557 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 398 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 504 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReduceMinimumUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 610 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 336 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 442 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 548 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 389 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 495 of file group.cpp.
References LOG, and Group::WaitForRequest().
void AllReducePlusUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 601 of file group.cpp.
References LOG, and Group::WaitForRequest().
void Barrier ()
run a MPI_Barrier() for synchronization.
Definition at line 190 of file group.cpp.
References Dispatcher::AddAsyncRequest(), Group::dispatcher(), Group::dispatcher_, thrill::net::mpi::g_mutex, and DispatcherThread::RunInThread().
void BroadcastInt (int & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 328 of file group.cpp.
References LOG, and Group::WaitForRequest().
void BroadcastLong (long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 434 of file group.cpp.
References LOG, and Group::WaitForRequest().
void BroadcastLongLong (long long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 540 of file group.cpp.
References LOG, and Group::WaitForRequest().
void BroadcastUnsignedInt (unsigned int & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 381 of file group.cpp.
References LOG, and Group::WaitForRequest().
void BroadcastUnsignedLong (unsigned long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 487 of file group.cpp.
References LOG, and Group::WaitForRequest().
void BroadcastUnsignedLongLong (unsigned long long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 593 of file group.cpp.
References LOG, and Group::WaitForRequest().
void Close () inline final virtual
Close.
Implements Group.
Definition at line 171 of file group.hpp.
net::Connection& connection (size_t id) inline final virtual
Return Connection to client id.
Implements Group.
Definition at line 166 of file group.hpp.
References Group::conns_.
std::unique_ptr< net::Dispatcher > ConstructDispatcher () const final virtual
Construct a network dispatcher object for the network backend used by this group, matching its internal implementation. A dispatcher may be shared between groups of the same type.
Implements Group.
Definition at line 185 of file group.cpp.
References Group::num_hosts().
DispatcherThread& dispatcher () inline
reference to the main MPI dispatcher thread
Definition at line 164 of file group.hpp.
References Group::dispatcher_.
Referenced by Group::Barrier(), Connection::SyncRecv(), Connection::SyncSend(), Connection::SyncSendRecv(), and Group::WaitForRequest().
void ExPrefixSumPlusInt (int & value, const int & initial) final private virtual
Reimplemented from Group.
Definition at line 319 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
void ExPrefixSumPlusLong (long & value, const long & initial) final private virtual
Reimplemented from Group.
Definition at line 425 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
void ExPrefixSumPlusLongLong (long long & value, const long long & initial) final private virtual
Reimplemented from Group.
Definition at line 531 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
void ExPrefixSumPlusUnsignedInt (unsigned int & value, const unsigned int & initial) final private virtual
Reimplemented from Group.
Definition at line 372 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
void ExPrefixSumPlusUnsignedLong (unsigned long & value, const unsigned long & initial) final private virtual
Reimplemented from Group.
Definition at line 478 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
void ExPrefixSumPlusUnsignedLongLong (unsigned long long & value, const unsigned long long & initial) final private virtual
Reimplemented from Group.
Definition at line 584 of file group.cpp.
References LOG, Group::my_rank_, and Group::WaitForRequest().
int group_tag () const inline
return MPI tag used to communicate
Definition at line 158 of file group.hpp.
References Group::group_tag_.
Referenced by Connection::OutputOstream(), Connection::SyncRecv(), Connection::SyncSend(), and Connection::SyncSendRecv().
size_t num_hosts () const inline final virtual
number of hosts configured.
Implements Group.
Definition at line 161 of file group.hpp.
References Group::conns_.
Referenced by Group::ConstructDispatcher().
size_t num_parallel_async () const final virtual
Number of parallel sends or recvs requests supported by net backend.
Reimplemented from Group.
Definition at line 181 of file group.cpp.
void PrefixSumPlusInt (int & value, const int & initial) final private virtual
Reimplemented from Group.
Definition at line 310 of file group.cpp.
References LOG, and Group::WaitForRequest().
void PrefixSumPlusLong (long & value, const long & initial) final private virtual
Reimplemented from Group.
Definition at line 416 of file group.cpp.
References LOG, and Group::WaitForRequest().
void PrefixSumPlusLongLong (long long & value, const long long & initial) final private virtual
Reimplemented from Group.
Definition at line 522 of file group.cpp.
References LOG, and Group::WaitForRequest().
void PrefixSumPlusUnsignedInt (unsigned int & value, const unsigned int & initial) final private virtual
Reimplemented from Group.
Definition at line 363 of file group.cpp.
References LOG, and Group::WaitForRequest().
void PrefixSumPlusUnsignedLong (unsigned long & value, const unsigned long & initial) final private virtual
Reimplemented from Group.
Definition at line 469 of file group.cpp.
References LOG, and Group::WaitForRequest().
void PrefixSumPlusUnsignedLongLong (unsigned long long & value, const unsigned long long & initial) final private virtual
Reimplemented from Group.
Definition at line 575 of file group.cpp.
References LOG, and Group::WaitForRequest().
void WaitForRequest (MpiCall call) private
Definition at line 214 of file group.cpp.
References Dispatcher::AddAsyncRequest(), Group::dispatcher(), Group::dispatcher_, thrill::net::mpi::g_mutex, and DispatcherThread::RunInThread().
Referenced by Group::AllReduceMaximumInt(), Group::AllReduceMaximumLong(), Group::AllReduceMaximumLongLong(), Group::AllReduceMaximumUnsignedInt(), Group::AllReduceMaximumUnsignedLong(), Group::AllReduceMaximumUnsignedLongLong(), Group::AllReduceMinimumInt(), Group::AllReduceMinimumLong(), Group::AllReduceMinimumLongLong(), Group::AllReduceMinimumUnsignedInt(), Group::AllReduceMinimumUnsignedLong(), Group::AllReduceMinimumUnsignedLongLong(), Group::AllReducePlusInt(), Group::AllReducePlusLong(), Group::AllReducePlusLongLong(), Group::AllReducePlusUnsignedInt(), Group::AllReducePlusUnsignedLong(), Group::AllReducePlusUnsignedLongLong(), Group::BroadcastInt(), Group::BroadcastLong(), Group::BroadcastLongLong(), Group::BroadcastUnsignedInt(), Group::BroadcastUnsignedLong(), Group::BroadcastUnsignedLongLong(), Group::ExPrefixSumPlusInt(), Group::ExPrefixSumPlusLong(), Group::ExPrefixSumPlusLongLong(), Group::ExPrefixSumPlusUnsignedInt(), Group::ExPrefixSumPlusUnsignedLong(), Group::ExPrefixSumPlusUnsignedLongLong(), Group::PrefixSumPlusInt(), Group::PrefixSumPlusLong(), Group::PrefixSumPlusLongLong(), Group::PrefixSumPlusUnsignedInt(), Group::PrefixSumPlusUnsignedLong(), and Group::PrefixSumPlusUnsignedLongLong().
Member Data Documentation
std::vector<Connection> conns_ private
vector of virtual connection objects to remote peers
Definition at line 191 of file group.hpp.
Referenced by Group::connection(), Group::Group(), and Group::num_hosts().
constexpr bool debug = false static private
Definition at line 139 of file group.hpp.
DispatcherThread& dispatcher_ private
reference to the main MPI dispatcher thread
Definition at line 194 of file group.hpp.
Referenced by Group::Barrier(), Group::dispatcher(), and Group::WaitForRequest().
int group_tag_ private
this group's MPI tag
Definition at line 188 of file group.hpp.
Referenced by Group::group_tag().
The documentation for this class was generated from the following files:
thrill/net/mpi/group.hpp
thrill/net/mpi/group.cpp