Thrill: StreamData::Writers Class Reference
StreamData::Writers Class Reference
Detailed Description
An extra class derived from std::vector<> for delivery of the BlockWriters of a Stream.
The purpose is to enforce a custom way to close stream writers cyclically such that PE k first sends it's Close-packet to k+1, k+2, etc.
Definition at line 59 of file stream_data.hpp.
Inherits vector< T >.
#include <stream_data.hpp>
Public Member Functions
Writers (size_t my_worker_rank=0)
Writers (const Writers &)=default
copyable: default copy-constructor
Writers (Writers &&)=default
move-constructor: default
~Writers ()
custom destructor to close writers is a cyclic fashion
void Close ()
custom destructor to close writers is a cyclic fashion
Writers & operator= (const Writers &)=default
copyable: default assignment operator
Writers & operator= (Writers &&)=default
move-assignment operator: default
Private Attributes
size_t my_worker_rank_
rank of this worker
Constructor & Destructor Documentation
Writers() [1/3]
Writers (size_t my_worker_rank = 0)
Definition at line 88 of file stream_data.cpp.
Writers() [2/3]
Writers (const Writers &) default
copyable: default copy-constructor
Writers() [3/3]
Writers (Writers &&) default
move-constructor: default
~Writers()
~Writers ()
custom destructor to close writers is a cyclic fashion
Definition at line 100 of file stream_data.cpp.
References StreamData::Writers::Close().
Member Function Documentation
Close()
void Close ()
custom destructor to close writers is a cyclic fashion
Definition at line 92 of file stream_data.cpp.
References StreamData::Writers::my_worker_rank_.
Referenced by GroupByNode< ValueType, KeyExtractor, GroupFunction, HashFunction, UseLocationDetection >::Execute(), DuplicateDetection::FindNonDuplicates(), LocationDetection< thrill::api::JoinNode::HashCount >::Flush(), SortNode< ValueType, CompareFunction, SortAlgorithm, Stable >::MainOp(), Stream::ScatterKeep(), AllGatherNode< ValueType >::StopPreOp(), GroupToIndexNode< ValueType, KeyExtractor, GroupFunction >::StopPreOp(), and StreamData::Writers::~Writers().
operator=() [1/2]
Writers& operator= (const Writers &) default
copyable: default assignment operator
operator=() [2/2]
Writers& operator= (Writers &&) default
move-assignment operator: default
Member Data Documentation
my_worker_rank_
size_t my_worker_rank_ private
rank of this worker
Definition at line 81 of file stream_data.hpp.
Referenced by StreamData::Writers::Close().
The documentation for this class was generated from the following files:
thrill/data/stream_data.hpp
thrill/data/stream_data.cpp