Thrill: btree_multiset< Key_, Compare_, Traits_, Alloc_ > Class Template Reference
btree_multiset< Key_, Compare_, Traits_, Alloc_ > Class Template Reference
B+ Trees
Detailed Description
template<typename Key_, typename Compare_ = std::less<Key_>, typename Traits_ = btree_default_traits<Key_, Key_>, typename Alloc_ = std::allocator<Key_>>
class tlx::btree_multiset< Key_, Compare_, Traits_, Alloc_ >
Specialized B+ tree template class implementing STL's multiset container.
Implements the STL multiset using a B+ tree. It can be used as a drop-in replacement for std::multiset. Not all asymptotic time requirements are met in theory. The class has a traits class defining B+ tree properties like slots and self-verification. Furthermore an allocator can be specified for tree nodes.
It is somewhat inefficient to implement a multiset using a B+ tree, a plain B tree would hold fewer copies of the keys.
Definition at line 41 of file btree_multiset.hpp.
#include <btree_multiset.hpp>
Classes
struct key_of_value
Key Extractor Struct.
Public Types
Template Parameter Types
typedef Key_ key_type
typedef Compare_ key_compare
Second template parameter: Key comparison function object.
typedef Traits_ traits
typedef Alloc_ allocator_type
Fourth template parameter: STL allocator.
Constructed Types
typedef key_type value_type
Construct the set value_type: the key_type.
typedef btree_multiset
< key_type, key_compare,
traits, allocator_type > self
Typedef of our own type.
typedef BTree< key_type,
value_type, key_of_value,
key_compare, traits, true,
allocator_type > btree_impl
Implementation type of the btree_base.
typedef btree_impl::value_compare value_compare
Function class comparing two value_type keys.
typedef btree_impl::size_type size_type
Size type used to count keys.
typedef btree_impl::tree_stats tree_stats
Small structure containing statistics about the tree.
Iterators and Reverse Iterators
typedef btree_impl::iterator iterator
typedef btree_impl::const_iterator const_iterator
typedef
btree_impl::reverse_iterator reverse_iterator
create mutable reverse iterator by using STL magic
typedef
btree_impl::const_reverse_iterator const_reverse_iterator
create constant reverse iterator by using STL magic
Public Member Functions
Constructors and Destructor
btree_multiset (const allocator_type &alloc=allocator_type())
btree_multiset (const key_compare &kcf, const allocator_type &alloc=allocator_type())
template<class InputIterator >
btree_multiset (InputIterator first, InputIterator last, const allocator_type &alloc=allocator_type())
Constructor initializing a B+ tree with the range [first,last)
template<class InputIterator >
btree_multiset (InputIterator first, InputIterator last, const key_compare &kcf, const allocator_type &alloc=allocator_type())
~btree_multiset ()
Frees up all used B+ tree memory pages.
void swap (btree_multiset &from)
Fast swapping of two identical B+ tree objects.
Key and Value Comparison Function Objects
key_compare key_comp () const
Constant access to the key comparison object sorting the B+ tree.
value_compare value_comp () const
Allocators
allocator_type get_allocator () const
Return the base node allocator provided during construction.
Fast Destruction of the B+ Tree
void clear ()
Frees all keys and all nodes of the tree.
STL Iterator Construction Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
Access Functions to the Item Count
size_type size () const
Return the number of keys in the B+ tree.
bool empty () const
Returns true if there is at least one key in the B+ tree.
size_type max_size () const
const tree_stats & get_stats () const
Return a const reference to the current statistics.
STL Access Functions Querying the Tree by Descending to a Leaf
bool exists (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
size_type count (const key_type &key) const
iterator lower_bound (const key_type &key)
const_iterator lower_bound (const key_type &key) const
iterator upper_bound (const key_type &key)
const_iterator upper_bound (const key_type &key) const
std::pair< iterator, iterator > equal_range (const key_type &key)
Searches the B+ tree and returns both lower_bound() and upper_bound().
std::pair< const_iterator,
const_iterator > equal_range (const key_type &key) const
Searches the B+ tree and returns both lower_bound() and upper_bound().
B+ Tree Object Comparison Functions
bool operator== (const btree_multiset &other) const
bool operator!= (const btree_multiset &other) const
Inequality relation. Based on operator==.
bool operator< (const btree_multiset &other) const
bool operator> (const btree_multiset &other) const
Greater relation. Based on operator<.
bool operator<= (const btree_multiset &other) const
Less-equal relation. Based on operator<.
bool operator>= (const btree_multiset &other) const
Greater-equal relation. Based on operator<.
Fast Copy: Assign Operator and Copy Constructors
btree_multiset & operator= (const btree_multiset &other)
Assignment operator. All the keys are copied.
btree_multiset (const btree_multiset &other)
Public Insertion Functions
iterator insert (const key_type &x)
iterator insert (iterator hint, const key_type &x)
template<typename InputIterator >
void insert (InputIterator first, InputIterator last)
template<typename Iterator >
void bulk_load (Iterator first, Iterator last)
Public Erase Functions
bool erase_one (const key_type &key)
Erases one (the first) entry of the given key.
size_type erase (const key_type &key)
void erase (iterator iter)
Erase the key/data pair referenced by the iterator.
Verification of B+ Tree Invariants
void verify () const
Public Attributes
TLX_BTREE_FRIENDS
Static Public Attributes
Static Constant Options and Values of the B+ Tree
static const unsigned short leaf_slotmax = btree_impl::leaf_slotmax
Base B+ tree parameter: The number of key/data slots in each leaf.
static const unsigned short inner_slotmax = btree_impl::inner_slotmax
static const unsigned short leaf_slotmin = btree_impl::leaf_slotmin
static const unsigned short inner_slotmin = btree_impl::inner_slotmin
static const bool self_verify = btree_impl::self_verify
static const bool debug = btree_impl::debug
static const bool allow_duplicates = btree_impl::allow_duplicates
Operational parameter: Allow duplicate keys in the btree.
Private Attributes
Tree Implementation Object
btree_impl tree_
The contained implementation object.
Member Typedef Documentation
typedef Alloc_ allocator_type
Fourth template parameter: STL allocator.
Definition at line 59 of file btree_multiset.hpp.
typedef BTree<key_type, value_type, key_of_value, key_compare, traits, true, allocator_type> btree_impl
Implementation type of the btree_base.
Definition at line 86 of file btree_multiset.hpp.
typedef btree_impl::const_iterator const_iterator
STL-like iterator object for B+ tree items. The iterator points to a specific slot number in a leaf.
Definition at line 144 of file btree_multiset.hpp.
typedef btree_impl::const_reverse_iterator const_reverse_iterator
create constant reverse iterator by using STL magic
Definition at line 150 of file btree_multiset.hpp.
typedef btree_impl::iterator iterator
STL-like iterator object for B+ tree items. The iterator points to a specific slot number in a leaf.
Definition at line 140 of file btree_multiset.hpp.
typedef Compare_ key_compare
Second template parameter: Key comparison function object.
Definition at line 52 of file btree_multiset.hpp.
typedef Key_ key_type
First template parameter: The key type of the btree. This is stored in inner nodes and leaves.
Definition at line 49 of file btree_multiset.hpp.
typedef btree_impl::reverse_iterator reverse_iterator
create mutable reverse iterator by using STL magic
Definition at line 147 of file btree_multiset.hpp.
typedef btree_multiset<key_type, key_compare, traits, allocator_type> self
Typedef of our own type.
Definition at line 76 of file btree_multiset.hpp.
typedef btree_impl::size_type size_type
Size type used to count keys.
Definition at line 92 of file btree_multiset.hpp.
typedef Traits_ traits
Third template parameter: Traits object used to define more parameters of the B+ tree
Definition at line 56 of file btree_multiset.hpp.
typedef btree_impl::tree_stats tree_stats
Small structure containing statistics about the tree.
Definition at line 95 of file btree_multiset.hpp.
typedef btree_impl::value_compare value_compare
Function class comparing two value_type keys.
Definition at line 89 of file btree_multiset.hpp.
typedef key_type value_type
Construct the set value_type: the key_type.
Definition at line 73 of file btree_multiset.hpp.
Constructor & Destructor Documentation
btree_multiset (const allocator_type & alloc = allocator_type()) inline explicit
Default constructor initializing an empty B+ tree with the standard key comparison function
Definition at line 169 of file btree_multiset.hpp.
btree_multiset (const key_compare & kcf, const allocator_type & alloc = allocator_type()) inline explicit
Constructor initializing an empty B+ tree with a special key comparison object
Definition at line 175 of file btree_multiset.hpp.
btree_multiset (InputIterator first, InputIterator last, const allocator_type & alloc = allocator_type()) inline
Constructor initializing a B+ tree with the range [first,last)
Definition at line 182 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::insert().
btree_multiset (InputIterator first, InputIterator last, const key_compare & kcf, const allocator_type & alloc = allocator_type()) inline
Constructor initializing a B+ tree with the range [first,last) and a special key comparison object
Definition at line 191 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::insert().
~btree_multiset () inline
Frees up all used B+ tree memory pages.
Definition at line 199 of file btree_multiset.hpp.
btree_multiset (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) inline
Copy constructor. The newly initialized B+ tree object will contain a copy of all keys.
Definition at line 445 of file btree_multiset.hpp.
Member Function Documentation
iterator begin () inline
Constructs a read/data-write iterator that points to the first slot in the first leaf of the B+ tree.
Definition at line 254 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::begin(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_iterator begin () const inline
Constructs a read-only constant iterator that points to the first slot in the first leaf of the B+ tree.
Definition at line 266 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::begin(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
void bulk_load (Iterator first, Iterator last) inline
Bulk load a sorted range [first,last). Loads items into leaves and constructs a B-tree above them. The tree must be empty when calling this function.
Definition at line 483 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::bulk_load(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
void clear () inline
Frees all keys and all nodes of the tree.
Definition at line 242 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::clear(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
size_type count (const key_type & key) const inline
Tries to locate a key in the B+ tree and returns the number of identical key entries found.
Definition at line 353 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::count(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool empty () const inline
Returns true if there is at least one key in the B+ tree.
Definition at line 312 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::empty(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
iterator end () inline
Constructs a read/data-write iterator that points to the first invalid slot in the last leaf of the B+ tree.
Definition at line 260 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::end(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_iterator end () const inline
Constructs a read-only constant iterator that points to the first invalid slot in the last leaf of the B+ tree.
Definition at line 272 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::end(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
std::pair<iterator, iterator> equal_range (const key_type & key) inline
Searches the B+ tree and returns both lower_bound() and upper_bound().
Definition at line 382 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::equal_range(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
std::pair<const_iterator, const_iterator> equal_range (const key_type & key) const inline
Searches the B+ tree and returns both lower_bound() and upper_bound().
Definition at line 387 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::equal_range(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
size_type erase (const key_type & key) inline
Erases all the entries of the given key. This is implemented using erase_one() and thus not very efficient.
Definition at line 500 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::erase(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
void erase (iterator iter) inline
Erase the key/data pair referenced by the iterator.
Definition at line 505 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::erase(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool erase_one (const key_type & key) inline
Erases one (the first) entry of the given key.
Definition at line 494 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::erase_one(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool exists (const key_type & key) const inline
Non-STL function checking whether a key is in the B+ tree. The same as (find(k) != end()) or (count() != 0).
Definition at line 335 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::exists(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
iterator find (const key_type & key) inline
Tries to locate a key in the B+ tree and returns an iterator to the key slot if found. If unsuccessful it returns end().
Definition at line 341 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::find(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_iterator find (const key_type & key) const inline
Tries to locate a key in the B+ tree and returns an constant iterator to the key slot if found. If unsuccessful it returns end().
Definition at line 347 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::find(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
allocator_type get_allocator () const inline
Return the base node allocator provided during construction.
Definition at line 231 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::get_allocator(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const tree_stats& get_stats () const inline
Return a const reference to the current statistics.
Definition at line 323 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::get_stats(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
iterator insert (const key_type & x) inline
Attempt to insert a key into the B+ tree. As this set allows duplicates, this function never fails.
Definition at line 457 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::insert(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
Referenced by btree_multiset< Key_, Compare_, Traits_, Alloc_ >::btree_multiset(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::insert().
iterator insert (iterator hint, const key_type & x) inline
Attempt to insert a key into the B+ tree. The iterator hint is currently ignored by the B+ tree insertion routine.
Definition at line 463 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::insert(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
void insert (InputIterator first, InputIterator last) inline
Attempt to insert the range [first,last) of key_type into the B+ tree. Each key is inserted individually.
Definition at line 470 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::insert().
key_compare key_comp () const inline
Constant access to the key comparison object sorting the B+ tree.
Definition at line 214 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::key_comp(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
iterator lower_bound (const key_type & key) inline
Searches the B+ tree and returns an iterator to the first pair equal to or greater than key, or end() if all keys are smaller.
Definition at line 359 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::lower_bound(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_iterator lower_bound (const key_type & key) const inline
Searches the B+ tree and returns a constant iterator to the first pair equal to or greater than key, or end() if all keys are smaller.
Definition at line 365 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::lower_bound(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
size_type max_size () const inline
Returns the largest possible size of the B+ Tree. This is just a function required by the STL standard, the B+ Tree can hold more items.
Definition at line 318 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::max_size(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator!= (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Inequality relation. Based on operator==.
Definition at line 405 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator< (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Total ordering relation of B+ trees of the same type. It uses std::lexicographical_compare() for the actual comparison of elements.
Definition at line 411 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator<= (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Less-equal relation. Based on operator<.
Definition at line 421 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
btree_multiset& operator= (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) inline
Assignment operator. All the keys are copied.
Definition at line 437 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator== (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Equality relation of B+ trees of the same type. B+ trees of the same size and equal key (counts) are considered equal.
Definition at line 400 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator> (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Greater relation. Based on operator<.
Definition at line 416 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
bool operator>= (const btree_multiset< Key_, Compare_, Traits_, Alloc_ > & other) const inline
Greater-equal relation. Based on operator<.
Definition at line 426 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
reverse_iterator rbegin () inline
Constructs a read/data-write reverse iterator that points to the first invalid slot in the last leaf of the B+ tree. Uses STL magic.
Definition at line 278 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::rbegin(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_reverse_iterator rbegin () const inline
Constructs a read-only reverse iterator that points to the first invalid slot in the last leaf of the B+ tree. Uses STL magic.
Definition at line 290 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::rbegin(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
reverse_iterator rend () inline
Constructs a read/data-write reverse iterator that points to the first slot in the first leaf of the B+ tree. Uses STL magic.
Definition at line 284 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::rend(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
const_reverse_iterator rend () const inline
Constructs a read-only reverse iterator that points to the first slot in the first leaf of the B+ tree. Uses STL magic.
Definition at line 296 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::rend(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
size_type size () const inline
Return the number of keys in the B+ tree.
Definition at line 307 of file btree_multiset.hpp.
References BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::size(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
void swap (btree_multiset< Key_, Compare_, Traits_, Alloc_ > & from) inline
Fast swapping of two identical B+ tree objects.
Definition at line 203 of file btree_multiset.hpp.
References tlx::swap(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_.
iterator upper_bound (const key_type & key) inline
Searches the B+ tree and returns an iterator to the first pair greater than key, or end() if all keys are smaller or equal.
Definition at line 371 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_, and BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::upper_bound().
const_iterator upper_bound (const key_type & key) const inline
Searches the B+ tree and returns a constant iterator to the first pair greater than key, or end() if all keys are smaller or equal.
Definition at line 377 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_, and BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::upper_bound().
value_compare value_comp () const inline
Constant access to a constructed value_type comparison object. Required by the STL
Definition at line 220 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_, and BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::value_comp().
void verify () const inline
Run a thorough verification of all B+ tree invariants. The program aborts via TLX_BTREE_ASSERT() if something is wrong.
Definition at line 546 of file btree_multiset.hpp.
References btree_multiset< Key_, Compare_, Traits_, Alloc_ >::tree_, and BTree< Key_, Value_, KeyOfValue_, Compare_, Traits_, Duplicates_, Alloc_ >::verify().
Member Data Documentation
const bool allow_duplicates = btree_impl::allow_duplicates static
Operational parameter: Allow duplicate keys in the btree.
Definition at line 130 of file btree_multiset.hpp.
const bool debug = btree_impl::debug static
Debug parameter: Prints out lots of debug information about how the algorithms change the tree. Requires the header file to be compiled with TLX_BTREE_DEBUG and the key type must be std::ostream printable.
Definition at line 127 of file btree_multiset.hpp.
const unsigned short inner_slotmax = btree_impl::inner_slotmax static
Base B+ tree parameter: The number of key slots in each inner node, this can differ from slots in each leaf.
Definition at line 108 of file btree_multiset.hpp.
const unsigned short inner_slotmin = btree_impl::inner_slotmin static
Computed B+ tree parameter: The minimum number of key slots used in an inner node. If fewer slots are used, the inner node will be merged or slots shifted from it's siblings.
Definition at line 118 of file btree_multiset.hpp.
const unsigned short leaf_slotmax = btree_impl::leaf_slotmax static
Base B+ tree parameter: The number of key/data slots in each leaf.
Definition at line 104 of file btree_multiset.hpp.
const unsigned short leaf_slotmin = btree_impl::leaf_slotmin static
Computed B+ tree parameter: The minimum number of key slots used in a leaf. If fewer slots are used, the leaf will be merged or slots shifted from it's siblings.
Definition at line 113 of file btree_multiset.hpp.
const bool self_verify = btree_impl::self_verify static
Debug parameter: Enables expensive and thorough checking of the B+ tree invariants after each insert/erase operation.
Definition at line 122 of file btree_multiset.hpp.
TLX_BTREE_FRIENDS
Definition at line 66 of file btree_multiset.hpp.
btree_impl tree_ private
The contained implementation object.
Definition at line 159 of file btree_multiset.hpp.
Referenced by btree_multiset< Key_, Compare_, Traits_, Alloc_ >::begin(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::bulk_load(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::clear(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::count(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::empty(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::end(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::equal_range(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::erase(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::erase_one(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::exists(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::find(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::get_allocator(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::get_stats(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::insert(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::key_comp(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::lower_bound(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::max_size(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator!=(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator<(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator<=(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator=(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator==(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator>(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::operator>=(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::rbegin(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::rend(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::size(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::swap(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::upper_bound(), btree_multiset< Key_, Compare_, Traits_, Alloc_ >::value_comp(), and btree_multiset< Key_, Compare_, Traits_, Alloc_ >::verify().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/container/btree_multiset.hpp