Thrill: Group Class Reference
Group Class Reference final
TCP Socket API
Detailed Description
Collection of NetConnections to workers, allows point-to-point client communication and simple collectives like MPI.
Definition at line 41 of file group.hpp.
#include <group.hpp>
Public Member Functions
Group (const Group &)=delete
non-copyable: delete copy-constructor
Group (Group &&)=default
move-constructor: default
Group & operator= (const Group &)=delete
non-copyable: delete assignment operator
Group & operator= (Group &&)=default
move-assignment operator: default
Status and Access to NetConnections
Connection & tcp_connection (size_t id)
Return Connection to client id.
net::Connection & connection (size_t id) final
Return Connection to client id.
std::unique_ptr< Dispatcher > ConstructDispatcher (mem::Manager &mem_manager) const final
Connection & AssignConnection (Connection &connection)
Assigns a connection to this net group.
size_t num_hosts () const final
Return number of connections in this group (= number computing hosts)
void Close ()
Closes all client connections.
~Group ()
Closes all client connections.
Public Member Functions inherited from Group
Group (size_t my_rank)
initializing constructor
Group (const Group &)=delete
non-copyable: delete copy-constructor
Group (Group &&)=default
move-constructor: default
template<>
void AllReduce (int &value, std::plus< int >)
template<>
void AllReduce (int &value, common::minimum< int >)
template<>
void AllReduce (int &value, common::maximum< int >)
template<>
void AllReduce (unsigned int &value, std::plus< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::minimum< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::maximum< unsigned int >)
template<>
void AllReduce (long &value, std::plus< long >)
template<>
void AllReduce (long &value, common::minimum< long >)
template<>
void AllReduce (long &value, common::maximum< long >)
template<>
void AllReduce (unsigned long &value, std::plus< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::minimum< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::maximum< unsigned long >)
template<>
void AllReduce (long long &value, std::plus< long long >)
template<>
void AllReduce (long long &value, common::minimum< long long >)
template<>
void AllReduce (long long &value, common::maximum< long long >)
template<>
void AllReduce (unsigned long long &value, std::plus< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::minimum< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::maximum< unsigned long long >)
template<>
void Broadcast (int &value, size_t origin)
template<>
void Broadcast (unsigned int &value, size_t origin)
template<>
void Broadcast (long &value, size_t origin)
template<>
void Broadcast (unsigned long &value, size_t origin)
template<>
void Broadcast (long long &value, size_t origin)
template<>
void Broadcast (unsigned long long &value, size_t origin)
template<>
void ExPrefixSum (int &value, std::plus< int >)
template<>
void ExPrefixSum (unsigned int &value, std::plus< unsigned int >)
template<>
void ExPrefixSum (long &value, std::plus< long >)
template<>
void ExPrefixSum (unsigned long &value, std::plus< unsigned long >)
template<>
void ExPrefixSum (long long &value, std::plus< long long >)
template<>
void ExPrefixSum (unsigned long long &value, std::plus< unsigned long long >)
Group & operator= (const Group &)=delete
non-copyable: delete assignment operator
Group & operator= (Group &&)=default
move-assignment operator: default
template<>
void PrefixSum (int &value, std::plus< int >)
template<>
void PrefixSum (unsigned int &value, std::plus< unsigned int >)
template<>
void PrefixSum (long &value, std::plus< long >)
template<>
void PrefixSum (unsigned long &value, std::plus< unsigned long >)
template<>
void PrefixSum (long long &value, std::plus< long long >)
template<>
void PrefixSum (unsigned long long &value, std::plus< unsigned long long >)
size_t my_host_rank () const
Return our rank among hosts in this group.
size_t OneFactorSize () const
Number of of 1-factor iterations.
size_t OneFactorPeer (size_t round) const
template<typename T >
void SendTo (size_t dest, const T &data)
Sends a serializable type to the given peer.
template<typename T >
void ReceiveFrom (size_t src, T *data)
Receives a serializable type from the given peer.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSum (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate inclusive prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void ExPrefixSum (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate exclusive prefix sum.
template<typename T >
void Broadcast (T &value, size_t origin=0)
Broadcast a value from the worker "origin".
template<typename T , typename BinarySumOp = std::plus<T>>
void Reduce (T &value, size_t root=0, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to the worker 0.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduce (T &value, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to all workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumSelect (T &value, BinarySumOp sum_op=BinarySumOp(), bool inclusive=true)
select prefixsum implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumDoubling (T &value, BinarySumOp sum_op=BinarySumOp(), bool inclusive=true)
Calculate for every worker his prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate for every worker his prefix sum.
template<typename T >
void BroadcastSelect (T &value, size_t origin=0)
select broadcast implementation (often due to total number of processors)
template<typename T >
void BroadcastTrivial (T &value, size_t origin=0)
Broadcasts the value of the peer with index 0 to all the others.
template<typename T >
void BroadcastBinomialTree (T &value, size_t origin=0)
Broadcasts the value of the worker with index "origin" to all the others.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSelect (T &value, BinarySumOp sum_op=BinarySumOp())
select allreduce implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSimple (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce on the workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceAtRoot (T &value, BinarySumOp sum_op=BinarySumOp())
Broadcasts the value of the peer with index 0 to all the others.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce for powers of two.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceElimination (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce using the elimination protocol described in R.
Private Attributes
std::vector< Connection > connections_
Connections to all other clients in the Group.
Static Private Attributes
static constexpr bool debug = false
Construction and Initialization
static std::vector
< std::unique_ptr< Group > > ConstructLoopbackMesh (size_t num_hosts)
Construct a test network with an underlying full mesh of local loopback stream sockets for testing.
static std::vector
< std::unique_ptr< Group > > ConstructLocalRealTCPMesh (size_t num_hosts)
Construct a test network with an underlying full mesh of REAL tcp streams interconnected via localhost ports.
Group (size_t my_rank, size_t group_size)
Initializing constructor, used by tests for creating Groups.
Additional Inherited Members
Protected Member Functions inherited from Group
virtual void PrefixSumPlusInt (int &value)
virtual void ExPrefixSumPlusInt (int &value)
virtual void BroadcastInt (int &value, size_t origin)
virtual void AllReducePlusInt (int &value)
virtual void AllReduceMinimumInt (int &value)
virtual void AllReduceMaximumInt (int &value)
virtual void PrefixSumPlusUnsignedInt (unsigned int &value)
virtual void ExPrefixSumPlusUnsignedInt (unsigned int &value)
virtual void BroadcastUnsignedInt (unsigned int &value, size_t origin)
virtual void AllReducePlusUnsignedInt (unsigned int &value)
virtual void AllReduceMinimumUnsignedInt (unsigned int &value)
virtual void AllReduceMaximumUnsignedInt (unsigned int &value)
virtual void PrefixSumPlusLong (long &value)
virtual void ExPrefixSumPlusLong (long &value)
virtual void BroadcastLong (long &value, size_t origin)
virtual void AllReducePlusLong (long &value)
virtual void AllReduceMinimumLong (long &value)
virtual void AllReduceMaximumLong (long &value)
virtual void PrefixSumPlusUnsignedLong (unsigned long &value)
virtual void ExPrefixSumPlusUnsignedLong (unsigned long &value)
virtual void BroadcastUnsignedLong (unsigned long &value, size_t origin)
virtual void AllReducePlusUnsignedLong (unsigned long &value)
virtual void AllReduceMinimumUnsignedLong (unsigned long &value)
virtual void AllReduceMaximumUnsignedLong (unsigned long &value)
virtual void PrefixSumPlusLongLong (long long &value)
virtual void ExPrefixSumPlusLongLong (long long &value)
virtual void BroadcastLongLong (long long &value, size_t origin)
virtual void AllReducePlusLongLong (long long &value)
virtual void AllReduceMinimumLongLong (long long &value)
virtual void AllReduceMaximumLongLong (long long &value)
virtual void PrefixSumPlusUnsignedLongLong (unsigned long long &value)
virtual void ExPrefixSumPlusUnsignedLongLong (unsigned long long &value)
virtual void BroadcastUnsignedLongLong (unsigned long long &value, size_t origin)
virtual void AllReducePlusUnsignedLongLong (unsigned long long &value)
virtual void AllReduceMinimumUnsignedLongLong (unsigned long long &value)
virtual void AllReduceMaximumUnsignedLongLong (unsigned long long &value)
template<typename T , typename BinarySumOp >
T SendReceiveReduce (size_t peer, const T &value, BinarySumOp sum_op)
Sends and Receives a serializable type from the given peer and returns the value after reduction.
template<typename T , typename BinarySumOp >
void AllReduceEliminationProcess (size_t host_id, size_t group_size, size_t remaining_hosts, size_t send_to, T &value, BinarySumOp sum_op)
used for the recursive implementation of the elimination protocol
Protected Attributes inherited from Group
size_t my_rank_
our rank in the network group
Constructor & Destructor Documentation
Group (size_t my_rank, size_t group_size) inline
Initializing constructor, used by tests for creating Groups.
Definition at line 66 of file group.hpp.
Group (const Group &) delete
non-copyable: delete copy-constructor
Group (Group &&) default
move-constructor: default
~Group () inline virtual
Closes all client connections.
Reimplemented from Group.
Definition at line 145 of file group.hpp.
References Group::Close().
Member Function Documentation
Connection& AssignConnection (Connection & connection) inline
Assigns a connection to this net group.
This method swaps the net connection to memory managed by this group. The reference given to that method will be invalid afterwards.
Parameters
connection The connection to assign.
Returns
A ref to the assigned connection, which is always valid, but might be different from the inut connection.
Definition at line 115 of file group.hpp.
References Group::connections_, Connection::peer_id(), and thrill::mem::to_string().
void Close () inline virtual
Closes all client connections.
Implements Group.
Definition at line 132 of file group.hpp.
References Group::connections_, and Group::my_rank_.
Referenced by Group::~Group().
net::Connection& connection (size_t id) inline final virtual
Return Connection to client id.
Implements Group.
Definition at line 98 of file group.hpp.
References Group::tcp_connection().
std::unique_ptr< Dispatcher > ConstructDispatcher (mem::Manager & mem_manager) const final virtual
Construct a network dispatcher object for this group, matching its internal implementation.
Implements Group.
Definition at line 31 of file group.cpp.
std::vector< std::unique_ptr< Group > > ConstructLocalRealTCPMesh (size_t num_hosts) static
Construct a test network with an underlying full mesh of REAL tcp streams interconnected via localhost ports.
Definition at line 64 of file group.cpp.
References thrill::net::tcp::Construct(), Group::num_hosts(), sLOG, and thrill::mem::to_string().
std::vector< std::unique_ptr< Group > > ConstructLoopbackMesh (size_t num_hosts) static
Construct a test network with an underlying full mesh of local loopback stream sockets for testing.
Returns vector of net::Group interfaces for each virtual client. This is ideal for testing network communication protocols.
Definition at line 36 of file group.cpp.
References Socket::CreatePair(), LOG, and Group::num_hosts().
Referenced by thrill::api::RunLocalSameThread(), and thrill::net::RunLoopbackGroupTest().
size_t num_hosts () const inline final virtual
Return number of connections in this group (= number computing hosts)
Implements Group.
Definition at line 127 of file group.hpp.
References Group::connections_.
Referenced by Group::ConstructLocalRealTCPMesh(), and Group::ConstructLoopbackMesh().
Group& operator= (const Group &) delete
non-copyable: delete assignment operator
Group& operator= (Group &&) default
move-assignment operator: default
Connection& tcp_connection (size_t id) inline
Return Connection to client id.
Definition at line 85 of file group.hpp.
References Group::connections_, Group::my_rank_, and thrill::mem::to_string().
Referenced by Group::connection().
Member Data Documentation
std::vector<Connection> connections_ private
Connections to all other clients in the Group.
Definition at line 153 of file group.hpp.
Referenced by Group::AssignConnection(), Group::Close(), Group::num_hosts(), and Group::tcp_connection().
constexpr bool debug = false static private
Definition at line 43 of file group.hpp.
The documentation for this class was generated from the following files:
thrill/net/tcp/group.hpp
thrill/net/tcp/group.cpp