Thrill: KeepFileBlockSource Class Reference
KeepFileBlockSource Class Reference
Data Subsystem Layer
Detailed Description
A BlockSource to read Blocks from a File.
The KeepFileBlockSource mainly contains an index to the current block, which is incremented when the NextBlock() must be delivered.
Definition at line 292 of file file.hpp.
#include <file.hpp>
Public Member Functions
KeepFileBlockSource (const File &file, size_t local_worker_id, size_t num_prefetch=File::default_prefetch, size_t first_block=0, size_t first_item=keep_first_item)
Start reading a File.
PinnedBlock NextBlock ()
void Prefetch (size_t prefetch)
Perform prefetch.
Protected Member Functions
Block NextUnpinnedBlock ()
Determine current unpinned Block to deliver via NextBlock()
Private Attributes
size_t current_block_
index of current block.
std::deque< PinRequestPtr > fetching_blocks_
current prefetch operations
const File & file_
file to read blocks from
size_t first_block_
number of the first block
size_t first_item_
offset of first item in first block read
size_t local_worker_id_
local worker id reading the File
size_t num_prefetch_
number of block prefetch operations
Static Private Attributes
static constexpr size_t keep_first_item = size_t(-1)
sentinel value for not changing the first_item item
Constructor & Destructor Documentation
KeepFileBlockSource (const File & file, size_t local_worker_id, size_t num_prefetch = File::default_prefetch, size_t first_block = 0, size_t first_item = keep_first_item)
Start reading a File.
Definition at line 104 of file file.cpp.
Member Function Documentation
PinnedBlock NextBlock ()
Advance to next block of file, delivers current_ and end_ for BlockReader
Definition at line 130 of file file.cpp.
References KeepFileBlockSource::current_block_, KeepFileBlockSource::fetching_blocks_, KeepFileBlockSource::file_, KeepFileBlockSource::local_worker_id_, KeepFileBlockSource::NextUnpinnedBlock(), File::num_blocks(), KeepFileBlockSource::num_prefetch_, and Block::PinWait().
Block NextUnpinnedBlock () protected
Determine current unpinned Block to deliver via NextBlock()
Definition at line 158 of file file.cpp.
References File::block(), KeepFileBlockSource::current_block_, KeepFileBlockSource::file_, KeepFileBlockSource::first_block_, KeepFileBlockSource::first_item_, KeepFileBlockSource::keep_first_item, and Block::set_begin().
Referenced by KeepFileBlockSource::NextBlock(), and KeepFileBlockSource::Prefetch().
void Prefetch (size_t prefetch)
Perform prefetch.
Definition at line 113 of file file.cpp.
References KeepFileBlockSource::current_block_, KeepFileBlockSource::fetching_blocks_, KeepFileBlockSource::file_, KeepFileBlockSource::local_worker_id_, KeepFileBlockSource::NextUnpinnedBlock(), File::num_blocks(), and KeepFileBlockSource::num_prefetch_.
Member Data Documentation
size_t current_block_ private
index of current block.
Definition at line 332 of file file.hpp.
Referenced by KeepFileBlockSource::NextBlock(), KeepFileBlockSource::NextUnpinnedBlock(), and KeepFileBlockSource::Prefetch().
std::deque<PinRequestPtr> fetching_blocks_ private
current prefetch operations
Definition at line 326 of file file.hpp.
Referenced by KeepFileBlockSource::NextBlock(), and KeepFileBlockSource::Prefetch().
const File& file_ private
file to read blocks from
Definition at line 317 of file file.hpp.
Referenced by KeepFileBlockSource::NextBlock(), KeepFileBlockSource::NextUnpinnedBlock(), and KeepFileBlockSource::Prefetch().
size_t first_block_ private
number of the first block
Definition at line 329 of file file.hpp.
Referenced by KeepFileBlockSource::NextUnpinnedBlock().
size_t first_item_ private
offset of first item in first block read
Definition at line 335 of file file.hpp.
Referenced by KeepFileBlockSource::NextUnpinnedBlock().
constexpr size_t keep_first_item = size_t(-1) static private
sentinel value for not changing the first_item item
Definition at line 314 of file file.hpp.
Referenced by KeepFileBlockSource::NextUnpinnedBlock().
size_t local_worker_id_ private
local worker id reading the File
Definition at line 320 of file file.hpp.
Referenced by KeepFileBlockSource::NextBlock(), and KeepFileBlockSource::Prefetch().
size_t num_prefetch_ private
number of block prefetch operations
Definition at line 323 of file file.hpp.
Referenced by KeepFileBlockSource::NextBlock(), and KeepFileBlockSource::Prefetch().
The documentation for this class was generated from the following files:
thrill/data/file.hpp
thrill/data/file.cpp