Thrill: JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection > Class Template Reference
JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection > Class Template Reference final
Distributed Operations (DOps)
Detailed Description
template<typename ValueType, typename FirstDIA, typename SecondDIA, typename KeyExtractor1, typename KeyExtractor2, typename JoinFunction, typename HashFunction, bool UseLocationDetection>
class thrill::api::JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >
Performs an inner join between two DIAs.
The key from each DIA element is hereby extracted with a key extractor function. All pairs of elements with equal keys from both DIAs are then joined with the join function.
Template Parameters
KeyExtractor1 Type of the key_extractor1 function. This is a function ValueType to the key type.
KeyExtractor2 Type of the key_extractor2 function. This is a function from SecondDIA::ValueType to the key type.
JoinFunction Type of the join_function. This is a function from ValueType and SecondDIA::ValueType to the type of the output DIA.
Parameters
SecondDIA Other DIA joined with this DIA.
key_extractor1 Key extractor for first DIA
key_extractor2 Key extractor for second DIA
join_function Join function applied to all equal key pairs
Definition at line 62 of file inner_join.hpp.
#include <inner_join.hpp>
Classes
class HashCount
hash counter used by LocationDetection
Public Member Functions
JoinNode (const FirstDIA &parent1, const SecondDIA &parent2, const KeyExtractor1 &key_extractor1, const KeyExtractor2 &key_extractor2, const JoinFunction &join_function, const HashFunction &hash_function)
Constructor for a JoinNode.
void Dispose () final
Virtual clear method. Triggers actual disposing in sub-classes.
CompareFunction auto MakePuller (std::deque< data::File > &files, std::vector< data::File::Reader > &seq, CompareFunction compare_function, bool consume)
void PushData (bool consume) final
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Public Member Functions inherited from DOpNode< ValueType >
DOpNode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DOpNode, which sets references to the parent nodes.
DOpNode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DOpNode, which sets references to the parent nodes.
Public Member Functions inherited from DIANode< ValueType >
DIANode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DIANode, which sets references to the parent nodes.
DIANode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DIANode, which sets references to the parent nodes.
virtual void AddChild (DIABase *node, const Callback &callback=Callback(), size_t parent_index=0)
Enables children to push their "folded" function chains to their parent.
std::vector< DIABase * > children () const override
Returns the children of this DIABase.
void PushFile (data::File &file, bool consume) const
void PushItem (const ValueType &item) const
Method for derived classes to Push a single item to all children.
void RemoveAllChildren () override
void RemoveChild (DIABase *node) override
void RunPushData () override
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
virtual void DecConsumeCounter (size_t counter)
virtual bool ForwardDataOnly () const
const size_t & id () const
return unique id() of DIANode subclass as stored by StatsNode
virtual void IncConsumeCounter (size_t counter)
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
virtual void SetConsumeCounter (size_t counter)
DIAState state () const
virtual bool OnPreOpFile (const data::File &, size_t)
virtual void Execute ()=0
Virtual execution method. Triggers actual computation in sub-classes.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Types
using InputTypeFirst = typename FirstDIA::ValueType
using InputTypeSecond = typename SecondDIA::ValueType
using Key = typename common::FunctionTraits< KeyExtractor1 >::result_type
Key type of join. must be equal to the other key extractor.
using Super = DOpNode< ValueType >
Private Member Functions
template<typename KeyExtractor , typename MergeTree >
std::pair< bool, bool > AddEqualKeysToFile (MergeTree &puller, const KeyExtractor &key_extractor, data::File::Writer &writer, const Key &key)
Adds all elements from merge tree to a data::File, potentially to external memory, afterwards sets the first_element pointer to the first element with a different key.
template<typename ItemType , typename KeyExtractor , typename MergeTree >
std::pair< bool, bool > AddEqualKeysToVec (std::vector< ItemType > &vec, MergeTree &puller, const KeyExtractor &key_extractor, data::FilePtr &file_ptr)
Adds all elements from merge tree to a vector, afterwards sets the first_element pointer to the first element with a different key.
DIAMemUse ExecuteMemUse () final
Amount of RAM used by Execute()
void JoinAllElements (const std::vector< InputTypeFirst > &vec1, bool external1, const std::vector< InputTypeSecond > &vec2, bool external2)
Joins all elements in cartesian product of both vectors.
template<typename ItemType >
size_t JoinCapacity ()
void MainOp ()
Receive elements from other workers, create pre-sorted files.
std::pair< size_t, size_t > MaxMergeDegreePrefetch (std::deque< data::File > &files)
template<typename ItemType , typename CompareFunction >
void MergeFiles (std::deque< data::File > &files, CompareFunction compare_function)
Merge files when there are too many for the merge tree to handle.
void PreOp1 (const InputTypeFirst &input)
void PreOp2 (const InputTypeSecond &input)
DIAMemUse PreOpMemUse () final
Amount of RAM used by PreOp after StartPreOp()
DIAMemUse PushDataMemUse () final
Amount of RAM used by PushData()
template<typename ItemType , typename KeyExtractor >
void ReceiveItems (size_t capacity, data::MixStream::MixReader &reader, std::deque< data::File > &files, const KeyExtractor &key_extractor)
Recieve all elements from a stream and write them to files sorted by key.
template<typename ItemType , typename KeyExtractor >
void SortAndWriteToFile (std::vector< ItemType > &vec, std::deque< data::File > &files, const KeyExtractor &key_extractor)
Sorts all elements in a vector and writes them to a file.
void StartPreOp (size_t id) final
Virtual method for preparing start of PushData.
void StopPreOp (size_t id) final
Virtual method for preparing end of PushData.
Private Attributes
std::deque< data::File > files1_
files for sorted datasets
std::deque< data::File > files2_
HashFunction hash_function_
data::MixStreamPtr hash_stream1_ { context_.GetNewMixStream(this) }
data streams for inter-worker communication of DIA elements
data::MixStreamPtr hash_stream2_ { context_.GetNewMixStream(this) }
std::vector< data::Stream::Writer > hash_writers1_ { hash_stream1_->GetWriters() }
std::vector< data::Stream::Writer > hash_writers2_ { hash_stream2_->GetWriters() }
data::FilePtr join_file1_
data::FilePtr join_file2_
JoinFunction join_function_
KeyExtractor1 key_extractor1_
user-defined functions
KeyExtractor2 key_extractor2_
core::LocationDetection
< HashCount > location_detection_ { context_, Super::id() }
bool location_detection_initialized_ = false
data::File pre_file1_ { context_.GetFile(this) }
location detection and associated files
data::File pre_file2_ { context_.GetFile(this) }
data::File::Writer pre_writer1_
data::File::Writer pre_writer2_
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Types inherited from DOpNode< ValueType >
using Super = DIANode< ValueType >
Public Types inherited from DIANode< ValueType >
using Callback = tlx::delegate< void(const ValueType &)>
Public Types inherited from DIABase
using DIABasePtr = tlx::CountingPtr< DIABase >
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Protected Attributes inherited from DIANode< ValueType >
std::vector< Child > children_
Callback functions from the child nodes.
Protected Attributes inherited from DIABase
Context & context_
associated Context
const size_t id_
DIA serial id.
const char *const label_
DOp node static label.
DIAState state_ = DIAState::NEW
State of the DIANode. State is NEW on creation.
std::vector< DIABasePtr > parents_
Parents of this DIABase.
DIAMemUse mem_limit_ = 0
size_t consume_counter_ = 1
Member Typedef Documentation
using InputTypeFirst = typename FirstDIA::ValueType private
Definition at line 70 of file inner_join.hpp.
using InputTypeSecond = typename SecondDIA::ValueType private
Definition at line 71 of file inner_join.hpp.
using Key = typename common::FunctionTraits<KeyExtractor1>::result_type private
Key type of join. must be equal to the other key extractor.
Definition at line 74 of file inner_join.hpp.
using Super = DOpNode<ValueType> private
Definition at line 67 of file inner_join.hpp.
Constructor & Destructor Documentation
JoinNode (const FirstDIA & parent1, const SecondDIA & parent2, const KeyExtractor1 & key_extractor1, const KeyExtractor2 & key_extractor2, const JoinFunction & join_function, const HashFunction & hash_function) inline
Constructor for a JoinNode.
Definition at line 134 of file inner_join.hpp.
Member Function Documentation
std::pair<bool, bool> AddEqualKeysToFile (MergeTree & puller, const KeyExtractor & key_extractor, data::File::Writer & writer, const Key & key) inline private
Adds all elements from merge tree to a data::File, potentially to external memory, afterwards sets the first_element pointer to the first element with a different key.
Parameters
puller Input merge tree
key_extractor Key extractor function
writer File writer
key target key
Returns
Pair of bools, first bool indicates whether the merge tree is emptied, second bool indicates whether external memory was needed (always true, when this method was called).
Definition at line 436 of file inner_join.hpp.
References BlockWriter< BlockSink >::Put().
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::AddEqualKeysToVec().
std::pair<bool, bool> AddEqualKeysToVec (std::vector< ItemType > & vec, MergeTree & puller, const KeyExtractor & key_extractor, data::FilePtr & file_ptr) inline private
Adds all elements from merge tree to a vector, afterwards sets the first_element pointer to the first element with a different key.
Parameters
vec target vector
puller Input merge tree
key_extractor Key extractor function
file_ptr Pointer to a data::File
Returns
Pair of bools, first bool indicates whether the merge tree is emptied, second bool indicates whether external memory was needed.
vec is very large when this happens swap with empty vector to free the memory
Definition at line 381 of file inner_join.hpp.
References JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::AddEqualKeysToFile(), DIABase::context_, Context::GetFilePtr(), thrill::mem::memory_exceeded, BlockWriter< BlockSink >::Put(), and tlx::swap().
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
void Dispose () inline final virtual
Virtual clear method. Triggers actual disposing in sub-classes.
Reimplemented from DIABase.
Definition at line 290 of file inner_join.hpp.
References JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files1_, and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files2_.
DIAMemUse ExecuteMemUse () inline final private virtual
Amount of RAM used by Execute()
Reimplemented from DIABase.
Definition at line 484 of file inner_join.hpp.
References DIAMemUse::Max().
void JoinAllElements (const std::vector< InputTypeFirst > & vec1, bool external1, const std::vector< InputTypeSecond > & vec2, bool external2) inline private
Joins all elements in cartesian product of both vectors.
Uses files when one of the data sets is too large to fit in memory. (indicated by 'external' bools)
file 2 needs to be read multiple times
non-consuming reader, need to clear now
Definition at line 590 of file inner_join.hpp.
References BlockReader< BlockSource >::HasNext(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::join_file1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::join_file2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::join_function_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor2_, LOG1, thrill::mem::memory_exceeded, and DIANode< ValueType >::PushItem().
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
size_t JoinCapacity () inline private
Definition at line 361 of file inner_join.hpp.
References DIABase::mem_limit_.
void MainOp () inline private
Receive elements from other workers, create pre-sorted files.
Definition at line 344 of file inner_join.hpp.
References JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_stream1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_stream2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor2_, and DIABase::mem_limit_.
CompareFunction auto MakePuller (std::deque< data::File > & files, std::vector< data::File::Reader > & seq, CompareFunction compare_function, bool consume) inline
Definition at line 198 of file inner_join.hpp.
References JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MaxMergeDegreePrefetch(), and thrill::data::StartPrefetch().
std::pair<size_t, size_t> MaxMergeDegreePrefetch (std::deque< data::File > & files) inline private
calculate maximum merging degree from available memory and the number of files. additionally calculate the prefetch size of each File.
Definition at line 518 of file inner_join.hpp.
References thrill::data::default_block_size, and DIABase::mem_limit_.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MakePuller(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MergeFiles().
void MergeFiles (std::deque< data::File > & files, CompareFunction compare_function) inline private
Merge files when there are too many for the merge tree to handle.
Definition at line 540 of file inner_join.hpp.
References DIABase::context_, Context::GetFile(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MaxMergeDegreePrefetch(), sLOG1, and thrill::data::StartPrefetch().
void PreOp1 (const InputTypeFirst & input) inline private
Definition at line 321 of file inner_join.hpp.
References DIABase::context_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::HashCount::hash, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_function_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_writers1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::location_detection_, Context::num_workers(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer1_, and BlockWriter< BlockSink >::Put().
void PreOp2 (const InputTypeSecond & input) inline private
Definition at line 332 of file inner_join.hpp.
References DIABase::context_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::HashCount::hash, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_function_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::hash_writers2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::location_detection_, Context::num_workers(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer2_, and BlockWriter< BlockSink >::Put().
DIAMemUse PreOpMemUse () inline final private virtual
Amount of RAM used by PreOp after StartPreOp()
Reimplemented from DIABase.
Definition at line 452 of file inner_join.hpp.
References DIAMemUse::Max().
void PushData (bool consume) inline final virtual
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Merge files when there are too many for the merge tree.
cache for elements with equal keys, cartesian product of both caches are joined with the join_function
find elements with equal key
Implements DIABase.
Definition at line 214 of file inner_join.hpp.
References JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::AddEqualKeysToVec(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::files2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::join_file1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::join_file2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor1_, and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::key_extractor2_.
DIAMemUse PushDataMemUse () inline final private virtual
Amount of RAM used by PushData()
Reimplemented from DIABase.
Definition at line 488 of file inner_join.hpp.
References DIAMemUse::Max().
void ReceiveItems (size_t capacity, data::MixStream::MixReader & reader, std::deque< data::File > & files, const KeyExtractor & key_extractor) inline private
Recieve all elements from a stream and write them to files sorted by key.
Definition at line 496 of file inner_join.hpp.
References MixBlockQueueReader::HasNext(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::SortAndWriteToFile().
void SortAndWriteToFile (std::vector< ItemType > & vec, std::deque< data::File > & files, const KeyExtractor & key_extractor) inline private
Sorts all elements in a vector and writes them to a file.
Definition at line 670 of file inner_join.hpp.
References BlockPool::AdviseFree(), Context::block_pool(), DIABase::context_, and Context::GetFile().
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::ReceiveItems().
void StartPreOp (size_t) inline final private virtual
Virtual method for preparing start of PushData.
Reimplemented from DIABase.
Definition at line 456 of file inner_join.hpp.
References File::GetWriter(), DIABase::id(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::location_detection_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::location_detection_initialized_, LOG, DIABase::mem_limit_, DIABase::parent_ids(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_file1_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_file2_, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer1_, and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer2_.
void StopPreOp (size_t) inline final private virtual
Virtual method for preparing end of PushData.
Reimplemented from DIABase.
Definition at line 473 of file inner_join.hpp.
References BlockWriter< BlockSink >::Close(), DIABase::id(), LOG, JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer1_, and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::pre_writer2_.
Member Data Documentation
constexpr bool debug = false static private
Definition at line 65 of file inner_join.hpp.
std::deque<data::File> files1_ private
files for sorted datasets
Definition at line 297 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::Dispose(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
std::deque<data::File> files2_ private
Definition at line 298 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::Dispose(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
HashFunction hash_function_ private
Definition at line 304 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2().
data::MixStreamPtr hash_stream1_ { context_.GetNewMixStream(this) } private
data streams for inter-worker communication of DIA elements
Definition at line 307 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp().
data::MixStreamPtr hash_stream2_ { context_.GetNewMixStream(this) } private
Definition at line 309 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp().
std::vector<data::Stream::Writer> hash_writers1_ { hash_stream1_->GetWriters() } private
Definition at line 308 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1().
std::vector<data::Stream::Writer> hash_writers2_ { hash_stream2_->GetWriters() } private
Definition at line 310 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2().
data::FilePtr join_file1_ private
Definition at line 582 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
data::FilePtr join_file2_ private
Definition at line 583 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
JoinFunction join_function_ private
Definition at line 303 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements().
KeyExtractor1 key_extractor1_ private
user-defined functions
Definition at line 301 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
KeyExtractor2 key_extractor2_ private
Definition at line 302 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::JoinAllElements(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::MainOp(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PushData().
core::LocationDetection<HashCount> location_detection_ { context_, Super::id() } private
Definition at line 318 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp().
bool location_detection_initialized_ = false private
Definition at line 319 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp().
data::File pre_file1_ { context_.GetFile(this) } private
location detection and associated files
Definition at line 313 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp().
data::File pre_file2_ { context_.GetFile(this) } private
Definition at line 315 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp().
data::File::Writer pre_writer1_ private
Definition at line 314 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp1(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StopPreOp().
data::File::Writer pre_writer2_ private
Definition at line 316 of file inner_join.hpp.
Referenced by JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::PreOp2(), JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StartPreOp(), and JoinNode< ValueType, FirstDIA, SecondDIA, KeyExtractor1, KeyExtractor2, JoinFunction, HashFunction, UseLocationDetection >::StopPreOp().
The documentation for this class was generated from the following file:
thrill/api/inner_join.hpp