Thrill: Point< D > Class Template Reference
Point< D > Class Template Reference
Detailed Description
template<size_t D>
class examples::k_means::Point< D >
A D-dimensional point with double precision.
Definition at line 41 of file k-means.hpp.
#include <k-means.hpp>
Public Member Functions
double Distance (const Point &b) const
double DistanceSquare (const Point &b) const
Point operator+ (const Point &b) const
Point & operator+= (const Point &b)
Point operator/ (double s) const
Point & operator/= (double s)
Static Public Member Functions
static size_t dim ()
static Point Make (size_t D_)
static Point Origin ()
template<typename Distribution , typename Generator >
static Point Random (size_t dim, Distribution &dist, Generator &gen)
Public Attributes
double x [D]
coordinates array
Friends
std::ostream & operator<< (std::ostream &os, const Point &a)
Member Function Documentation
static size_t dim () inline static
Definition at line 47 of file k-means.hpp.
double Distance (const Point< D > & b) const inline
Definition at line 70 of file k-means.hpp.
References Point< D >::DistanceSquare().
double DistanceSquare (const Point< D > & b) const inline
Definition at line 65 of file k-means.hpp.
References Point< D >::x.
Referenced by KMeansModel< Point >::Classify(), KMeansModel< Point >::ComputeCost(), Point< D >::Distance(), and examples::k_means::KMeans().
static Point Make (size_t D_) inline static
Definition at line 49 of file k-means.hpp.
References die_unless.
Referenced by RunKMeansFile().
Point operator+ (const Point< D > & b) const inline
Definition at line 73 of file k-means.hpp.
References Point< D >::x.
Point& operator+= (const Point< D > & b) inline
Definition at line 78 of file k-means.hpp.
References Point< D >::x.
Point operator/ (double s) const inline
Definition at line 82 of file k-means.hpp.
References Point< D >::x.
Point& operator/= (double s) inline
Definition at line 87 of file k-means.hpp.
References Point< D >::x.
static Point Origin () inline static
Definition at line 53 of file k-means.hpp.
References Point< D >::x.
static Point Random (size_t dim, Distribution & dist, Generator & gen) inline static
Definition at line 59 of file k-means.hpp.
References die_unless, and Point< D >::x.
Referenced by RunKMeansGenerated().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Point< D > & a) friend
Definition at line 91 of file k-means.hpp.
Member Data Documentation
double x[D]
coordinates array
Definition at line 45 of file k-means.hpp.
Referenced by Point< D >::DistanceSquare(), Point< D >::operator+(), Point< D >::operator+=(), Point< D >::operator/(), Point< D >::operator/=(), Point< D >::Origin(), Point< D >::Random(), and RunKMeansFile().
The documentation for this class was generated from the following file:
examples/k-means/k-means.hpp