Thrill: Connection Class Reference
Connection Class Reference final
MPI Network API
Detailed Description
Virtual MPI connection class.
As MPI has no real connections, this class is just the integer which selected an MPI peer. Additionally, it contains the group tag used to separate communication into groups.
Definition at line 62 of file group.hpp.
#include <group.hpp>
Public Member Functions
void Initialize (Group *group, int peer)
construct from group tag and MPI peer
Base Status Functions
bool IsValid () const final
check whether the connection is (still) valid.
int peer () const
return the MPI peer number
std::string ToString () const final
mpi::Connection
std::ostream & OutputOstream (std::ostream &os) const final
virtual method to output to a std::ostream
Send Functions
void SyncSend (const void *data, size_t size, Flags=NoFlags) final
ssize_t SendOne (const void *data, size_t size, Flags flags=NoFlags) final
Receive Functions
void SyncRecv (void *out_data, size_t size) final
ssize_t RecvOne (void *out_data, size_t size) final
Paired SendReceive Methods
void SyncSendRecv (const void *send_data, size_t send_size, void *recv_data, size_t recv_size) final
void SyncRecvSend (const void *send_data, size_t send_size, void *recv_data, size_t recv_size) final
Public Member Functions inherited from Connection
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type Send (const T &value)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type Send (const T &value)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type Send (const T &value)
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type Receive (T *out_value)
Receive any serializable POD item T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type Receive (T *out_value)
Receive any serializable non-POD fixed-length item T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type Receive (T *out_value)
Receive any serializable non-POD fixed-length item T.
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type SendReceive (const T *value, T *out_value, size_t n=1)
SendReceive any serializable POD item T.
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type ReceiveSend (const T &value, T *out_value)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type SendReceive (const T *value, T *out_value, size_t n=1)
SendReceive any serializable non-POD fixed-length item T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type ReceiveSend (const T &value, T *out_value)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type SendReceive (const T *value, T *out_value, size_t n=1)
SendReceive any serializable non-POD fixed-length item T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type ReceiveSend (const T &value, T *out_value)
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type SendN (const T *value, size_t n)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type SendN (const T *value, size_t n)
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type SendN (const T *value, size_t n)
template<typename T >
std::enable_if< std::is_pod< T >
::value, void >::type ReceiveN (T *out_value, size_t n)
Receive an array of serializable POD items T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type ReceiveN (T *out_value, size_t n)
Receive an array of serializable non-POD fixed-length items T.
template<typename T >
std::enable_if< !std::is_pod
< T >::value
&&!data::Serialization
< BufferBuilder, T >
::is_fixed_size, void >::type ReceiveN (T *out_value, size_t n)
Receive an array of serializable non-POD fixed-length items T.
Private Attributes
Group * group_
Group reference.
int peer_
Outgoing peer id of this Connection.
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Types inherited from Connection
enum Flags : size_t { NoFlags = 0, MsgMore = 1 }
Additional flags for sending or receiving.
Public Attributes inherited from Connection
bool is_loopback_ = false
std::atomic< uint32_t > tx_seq_ { 0 }
send sequence
std::atomic< uint32_t > rx_seq_ { 0 }
receive sequence
std::atomic< size_t > tx_bytes_ { 0 }
sent bytes
std::atomic< size_t > rx_bytes_ = { 0 }
received bytes
size_t prev_tx_bytes_ = 0
previous read of sent bytes
size_t prev_rx_bytes_ = 0
previous read of received bytes
Static Public Attributes inherited from Connection
static constexpr bool self_verify_ = common::g_self_verify
Member Function Documentation
void Initialize (Group * group, int peer) inline
construct from group tag and MPI peer
Definition at line 68 of file group.hpp.
References Connection::group_, Connection::peer(), and Connection::peer_.
bool IsValid () const inline final virtual
check whether the connection is (still) valid.
Implements Connection.
Definition at line 76 of file group.hpp.
std::ostream & OutputOstream (std::ostream & os) const final virtual
virtual method to output to a std::ostream
Implements Connection.
Definition at line 50 of file group.cpp.
References Connection::group_, Group::group_tag(), and Connection::peer_.
int peer () const inline
return the MPI peer number
Definition at line 79 of file group.hpp.
References Connection::peer_.
Referenced by Dispatcher::AddRead(), Dispatcher::Cancel(), Dispatcher::DispatchOne(), Connection::Initialize(), Dispatcher::IRecv(), Dispatcher::ISend(), Dispatcher::PerformAsync(), Dispatcher::QueueAsyncRecv(), Dispatcher::QueueAsyncSend(), and Dispatcher::SetExcept().
ssize_t RecvOne (void * out_data, size_t size) inline final virtual
Non-blocking receive of at most size data. returns number of bytes actually received. check errno for errors.
Implements Connection.
Definition at line 106 of file group.hpp.
References Connection::SyncRecv().
ssize_t SendOne (const void * data, size_t size, Flags flags = NoFlags) inline final virtual
Non-blocking send of a (data,size) message. returns number of bytes possible to send. check errno for errors.
Implements Connection.
Definition at line 93 of file group.hpp.
References Connection::SyncSend().
void SyncRecv (void * out_data, size_t size) final virtual
Synchronous blocking receive a message of given size. The size must match the SyncSend size for some network layers may only support matching messages (read: RDMA!, but also true for the mock net). Throws a net::Exception on errors.
Implements Connection.
Definition at line 86 of file group.cpp.
References Group::dispatcher(), Connection::group_, Group::group_tag(), Dispatcher::IRecv(), LOG, max(), Connection::peer_, DispatcherThread::RunInThread(), and Connection::rx_bytes_.
Referenced by Connection::RecvOne().
void SyncRecvSend (const void * send_data, size_t send_size, void * recv_data, size_t recv_size) final virtual
Implements Connection.
Definition at line 173 of file group.cpp.
References Connection::SyncSendRecv().
void SyncSend (const void * data, size_t size, Flags flags = NoFlags) final virtual
Synchronous blocking send of the (data,size) packet. if sending fails, a net::Exception is thrown.
Implements Connection.
Definition at line 57 of file group.cpp.
References Group::dispatcher(), Connection::group_, Group::group_tag(), Dispatcher::ISend(), LOG, max(), Connection::peer_, DispatcherThread::RunInThread(), and Connection::tx_bytes_.
Referenced by Connection::SendOne().
void SyncSendRecv (const void * send_data, size_t send_size, void * recv_data, size_t recv_size) final virtual
Synchronous blocking sending and receive a message of given size. The size must match the SyncSendRecv size for some network layers may only support matching messages (read: RDMA!, but also true for the mock net). Throws a net::Exception on errors.
Implements Connection.
Definition at line 125 of file group.cpp.
References Group::dispatcher(), Connection::group_, Group::group_tag(), Dispatcher::ISend(), LOG, max(), Connection::peer_, DispatcherThread::RunInThread(), Connection::rx_bytes_, and Connection::tx_bytes_.
Referenced by Connection::SyncRecvSend().
std::string ToString () const final virtual
mpi::Connection
Implements Connection.
Definition at line 46 of file group.cpp.
References Connection::peer_, and thrill::mem::to_string().
Member Data Documentation
constexpr bool debug = false static private
Definition at line 64 of file group.hpp.
Group* group_ private
Group reference.
Definition at line 125 of file group.hpp.
Referenced by Connection::Initialize(), Connection::OutputOstream(), Connection::SyncRecv(), Connection::SyncSend(), and Connection::SyncSendRecv().
int peer_ private
Outgoing peer id of this Connection.
Definition at line 128 of file group.hpp.
Referenced by Connection::Initialize(), Connection::OutputOstream(), Connection::peer(), Connection::SyncRecv(), Connection::SyncSend(), Connection::SyncSendRecv(), and Connection::ToString().
The documentation for this class was generated from the following files:
thrill/net/mpi/group.hpp
thrill/net/mpi/group.cpp