Thrill: block_scheduler_algorithm_online_lru< SwappableBlockType > Class Template Reference
block_scheduler_algorithm_online_lru< SwappableBlockType > Class Template Reference
Detailed Description
template<class SwappableBlockType>
class foxxll::block_scheduler_algorithm_online_lru< SwappableBlockType >
Block scheduling algorithm caching via the least recently used policy (online).
Definition at line 253 of file block_scheduler.hpp.
#include <block_scheduler.hpp>
Public Member Functions
block_scheduler_algorithm_online_lru (block_scheduler_type &bs)
block_scheduler_algorithm_online_lru (block_scheduler_algorithm_type *old)
virtual ~block_scheduler_algorithm_online_lru ()
virtual internal_block_type & acquire (const swappable_block_identifier_type sbid, const bool uninitialized=false)
virtual void deinitialize (swappable_block_identifier_type sbid)
virtual bool evictable_blocks_empty ()
virtual
swappable_block_identifier_type evictable_blocks_pop ()
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid)
virtual void initialize (swappable_block_identifier_type sbid, external_block_type eblock)
virtual void release (swappable_block_identifier_type sbid, const bool dirty)
Public Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm (block_scheduler_type &bs)
block_scheduler_algorithm (block_scheduler_algorithm *old)
block_scheduler_algorithm (const block_scheduler_algorithm &)=delete
non-copyable: delete copy-constructor
virtual ~block_scheduler_algorithm ()
virtual void explicit_timestep ()
virtual const
prediction_sequence_type & get_prediction_sequence () const
virtual bool is_initialized (const swappable_block_identifier_type sbid) const
virtual bool is_simulating () const
block_scheduler_algorithm & operator= (const block_scheduler_algorithm &)=delete
non-copyable: delete assignment operator
virtual void swappable_blocks_resize (swappable_block_identifier_type)
Protected Types
using block_scheduler_algorithm_type = block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
Protected Types inherited from block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using prediction_sequence_type = typename block_scheduler_type::prediction_sequence_type
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
using time_type = typename block_scheduler_type::time_type
Protected Member Functions
internal_block_type * get_free_internal_block ()
void init ()
void return_free_internal_block (internal_block_type *iblock)
Protected Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm * get_algorithm_from_block_scheduler ()
internal_block_type * get_free_internal_block_from_block_scheduler ()
void return_free_internal_block_to_block_scheduler (internal_block_type *iblock)
Return an internal_block to the block_scheduler.
Protected Attributes
addressable_fifo_queue
< swappable_block_identifier_type > evictable_blocks
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
Protected Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
prediction_sequence_type prediction_sequence
std::vector< SwappableBlockType > & swappable_blocks
Additional Inherited Members
Public Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_type & bs
Member Typedef Documentation
using block_scheduler_algorithm_type = block_scheduler_algorithm<SwappableBlockType> protected
Definition at line 616 of file block_scheduler.hpp.
using block_scheduler_type = block_scheduler<SwappableBlockType> protected
Definition at line 615 of file block_scheduler.hpp.
using external_block_type = typename block_scheduler_type::external_block_type protected
Definition at line 618 of file block_scheduler.hpp.
using internal_block_type = typename block_scheduler_type::internal_block_type protected
Definition at line 617 of file block_scheduler.hpp.
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type protected
Definition at line 619 of file block_scheduler.hpp.
Constructor & Destructor Documentation
block_scheduler_algorithm_online_lru (block_scheduler_type & bs) inline explicit
Definition at line 651 of file block_scheduler.hpp.
References block_scheduler_algorithm_online_lru< SwappableBlockType >::init().
block_scheduler_algorithm_online_lru (block_scheduler_algorithm_type * old) inline explicit
Definition at line 655 of file block_scheduler.hpp.
References block_scheduler_algorithm_online_lru< SwappableBlockType >::init().
virtual ~block_scheduler_algorithm_online_lru () inline virtual
Definition at line 659 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::empty(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, addressable_fifo_queue< KeyType >::pop(), block_scheduler_algorithm_online_lru< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, and TLX_LOG1.
Member Function Documentation
virtual internal_block_type& acquire (const swappable_block_identifier_type sbid, const bool uninitialized = false) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 677 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::erase(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_online_lru< SwappableBlockType >::get_free_internal_block(), and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
virtual void deinitialize (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 731 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::erase(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_online_lru< SwappableBlockType >::return_free_internal_block(), and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
virtual bool evictable_blocks_empty () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 671 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::empty(), and block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks.
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::init().
virtual swappable_block_identifier_type evictable_blocks_pop () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 674 of file block_scheduler.hpp.
References block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, and addressable_fifo_queue< KeyType >::pop().
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::init().
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 746 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::erase(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_online_lru< SwappableBlockType >::return_free_internal_block(), and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
internal_block_type* get_free_internal_block () inline protected
Definition at line 630 of file block_scheduler.hpp.
References addressable_fifo_queue< KeyType >::empty(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm< SwappableBlockType >::get_free_internal_block_from_block_scheduler(), addressable_fifo_queue< KeyType >::pop(), and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::acquire().
void init () inline protected
Definition at line 643 of file block_scheduler.hpp.
References block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm< SwappableBlockType >::get_algorithm_from_block_scheduler(), and addressable_fifo_queue< KeyType >::insert().
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::block_scheduler_algorithm_online_lru().
virtual void initialize (swappable_block_identifier_type sbid, external_block_type eblock) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 740 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
virtual void release (swappable_block_identifier_type sbid, const bool dirty) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 715 of file block_scheduler.hpp.
References block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks, addressable_fifo_queue< KeyType >::insert(), block_scheduler_algorithm_online_lru< SwappableBlockType >::return_free_internal_block(), and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
void return_free_internal_block (internal_block_type * iblock) inline protected
Definition at line 640 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::return_free_internal_block_to_block_scheduler().
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_online_lru< SwappableBlockType >::extract_external_block(), block_scheduler_algorithm_online_lru< SwappableBlockType >::release(), and block_scheduler_algorithm_online_lru< SwappableBlockType >::~block_scheduler_algorithm_online_lru().
Member Data Documentation
addressable_fifo_queue<swappable_block_identifier_type> evictable_blocks protected
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
Definition at line 628 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_online_lru< SwappableBlockType >::acquire(), block_scheduler_algorithm_online_lru< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_online_lru< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm_online_lru< SwappableBlockType >::extract_external_block(), block_scheduler_algorithm_online_lru< SwappableBlockType >::get_free_internal_block(), block_scheduler_algorithm_online_lru< SwappableBlockType >::init(), block_scheduler_algorithm_online_lru< SwappableBlockType >::release(), and block_scheduler_algorithm_online_lru< SwappableBlockType >::~block_scheduler_algorithm_online_lru().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/block_scheduler.hpp