Thrill: StringShadowLcpPtr< StringSet_, LcpType_ > Class Template Reference
StringShadowLcpPtr< StringSet_, LcpType_ > Class Template Reference
Detailed Description
template<typename StringSet_, typename LcpType_>
class tlx::sort_strings_detail::StringShadowLcpPtr< StringSet_, LcpType_ >
Objectified string array pointer and shadow pointer array for out-of-place swapping of pointers.
Definition at line 40 of file string_ptr.hpp.
#include <string_ptr.hpp>
Public Types
typedef StringSet::Iterator Iterator
typedef LcpType_ LcpType
typedef StringSet::String String
typedef StringSet_ StringSet
Public Member Functions
StringShadowLcpPtr (const StringSet &original, const StringSet &shadow, LcpType *lcp, bool flipped=false)
constructor specifying all attributes
const StringSet & active () const
return currently active array
StringShadowLcpPtr copy_back () const
void fill_lcp (const LcpType &v) const
fill entire LCP array with v, excluding the first lcp[0] position!
StringShadowLcpPtr flip (size_t offset, size_t sub_size) const
bool flipped () const
true if flipped to back array
LcpType get_lcp (size_t i) const
return LCP array value
LcpType * lcp () const
return LCP array pointer
void set_lcp (size_t i, const LcpType &v) const
set the i-th lcp to v and check its value
const StringSet & shadow () const
return current shadow array
size_t size () const
return valid length
StringShadowLcpPtr sub (size_t offset, size_t sub_size) const
Advance (both) pointers by given offset, return sub-array without flip.
Static Public Attributes
static const bool with_lcp = true
if we want to save the LCPs
Protected Attributes
StringSet active_
strings (front) and temporary shadow (back) array
bool flipped_
false if active_ is original, true if shadow_ is original
LcpType * lcp_
lcp array
StringSet shadow_
Member Typedef Documentation
typedef StringSet::Iterator Iterator
Definition at line 253 of file string_ptr.hpp.
typedef LcpType_ LcpType
Definition at line 251 of file string_ptr.hpp.
typedef StringSet::String String
Definition at line 252 of file string_ptr.hpp.
typedef StringSet_ StringSet
Definition at line 250 of file string_ptr.hpp.
Constructor & Destructor Documentation
StringShadowLcpPtr (const StringSet & original, const StringSet & shadow, LcpType * lcp, bool flipped = false) inline
constructor specifying all attributes
Definition at line 267 of file string_ptr.hpp.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::copy_back(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
Member Function Documentation
const StringSet& active () const inline
return currently active array
Definition at line 272 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::active_.
StringShadowLcpPtr copy_back () const inline
return subarray pointer to n strings in original array, might copy from shadow before returning.
Definition at line 302 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::active_, StringShadowLcpPtr< StringSet_, LcpType_ >::flipped_, StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_, StringShadowLcpPtr< StringSet_, LcpType_ >::shadow_, and StringShadowLcpPtr< StringSet_, LcpType_ >::StringShadowLcpPtr().
void fill_lcp (const LcpType & v) const inline
fill entire LCP array with v, excluding the first lcp[0] position!
Definition at line 333 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::set_lcp(), and StringShadowLcpPtr< StringSet_, LcpType_ >::size().
StringShadowLcpPtr flip (size_t offset, size_t sub_size) const inline
construct a StringShadowLcpPtr object specifying a sub-array with flipping to other array.
Definition at line 293 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::active_, StringShadowLcpPtr< StringSet_, LcpType_ >::flipped_, StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_, StringShadowLcpPtr< StringSet_, LcpType_ >::shadow_, StringShadowLcpPtr< StringSet_, LcpType_ >::size(), and StringShadowLcpPtr< StringSet_, LcpType_ >::StringShadowLcpPtr().
bool flipped () const inline
true if flipped to back array
Definition at line 278 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::flipped_.
LcpType get_lcp (size_t i) const inline
return LCP array value
Definition at line 321 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_, and StringShadowLcpPtr< StringSet_, LcpType_ >::size().
LcpType* lcp () const inline
return LCP array pointer
Definition at line 316 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_.
void set_lcp (size_t i, const LcpType & v) const inline
set the i-th lcp to v and check its value
Definition at line 327 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_, and StringShadowLcpPtr< StringSet_, LcpType_ >::size().
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::fill_lcp().
const StringSet& shadow () const inline
return current shadow array
Definition at line 275 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::shadow_.
size_t size () const inline
return valid length
Definition at line 281 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::active_.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::fill_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::get_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::set_lcp(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
StringShadowLcpPtr sub (size_t offset, size_t sub_size) const inline
Advance (both) pointers by given offset, return sub-array without flip.
Definition at line 284 of file string_ptr.hpp.
References StringShadowLcpPtr< StringSet_, LcpType_ >::active_, StringShadowLcpPtr< StringSet_, LcpType_ >::flipped_, StringShadowLcpPtr< StringSet_, LcpType_ >::lcp_, StringShadowLcpPtr< StringSet_, LcpType_ >::shadow_, StringShadowLcpPtr< StringSet_, LcpType_ >::size(), and StringShadowLcpPtr< StringSet_, LcpType_ >::StringShadowLcpPtr().
Member Data Documentation
StringSet active_ protected
strings (front) and temporary shadow (back) array
Definition at line 257 of file string_ptr.hpp.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::active(), StringShadowLcpPtr< StringSet_, LcpType_ >::copy_back(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::size(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
bool flipped_ protected
false if active_ is original, true if shadow_ is original
Definition at line 263 of file string_ptr.hpp.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::copy_back(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::flipped(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
LcpType* lcp_ protected
lcp array
Definition at line 260 of file string_ptr.hpp.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::copy_back(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::get_lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::lcp(), StringShadowLcpPtr< StringSet_, LcpType_ >::set_lcp(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
StringSet shadow_ protected
Definition at line 257 of file string_ptr.hpp.
Referenced by StringShadowLcpPtr< StringSet_, LcpType_ >::copy_back(), StringShadowLcpPtr< StringSet_, LcpType_ >::flip(), StringShadowLcpPtr< StringSet_, LcpType_ >::shadow(), and StringShadowLcpPtr< StringSet_, LcpType_ >::sub().
const bool with_lcp = true static
if we want to save the LCPs
Definition at line 313 of file string_ptr.hpp.
The documentation for this class was generated from the following file:
extlib/tlx/tlx/sort/strings/string_ptr.hpp