Thrill: CmdlineParser Class Reference
CmdlineParser Class Reference
Detailed Description
Command line parser which automatically fills variables and prints nice usage messages.
This is a straightforward command line parser in C++, which will recognize short options -s, long options –long and parameters, both required and optional. It will automatically parse integers and byte sizes with SI/IEC suffixes (e.g. 1 GiB). It also works with lists of strings, e.g. multiple filenames.
#include <thrill/common/cmdline_parser.hpp>
#include <iostream>
#include <string>
int main(int argc, char* argv[]) {
    thrill::common::CmdlineParser cp;
    // add description and author
    cp.SetDescription("This may some day be a useful program, which solves "
                      "many serious problems of the real world and achives "
                      "global peace.");
    cp.SetAuthor("Timo Bingmann <tb@panthema.net>");
    // add an unsigned integer option --rounds <N>
    unsigned int rounds = 0;
    cp.AddUInt('r', "rounds", "N", rounds,
               "Run N rounds of the experiment.");
    // add a byte size argument which the user can enter like '1gi'
    uint64_t a_size = 0;
    cp.AddBytes('s', "size", a_size,
                "Number of bytes to process.");
    // add a required parameter
    std::string a_filename;
    cp.AddParamString("filename", a_filename,
                      "A filename to process");
    // process command line
    if (!cp.Process(argc, argv))
        return -1; // some error occurred and help was always written to user.
    std::cout << "Command line parsed okay." << std::endl;
    // output for debugging
    cp.PrintResult();
    // do something useful
}
When running the program above without arguments, it will print:
$ ./common_cmdline_parser_example
Missing required argument for parameter 'filename'
Usage: ./common_cmdline_parser_example [options] <filename>
This may some day be a useful program, which solves many serious problems of
the real world and achives global peace.
Author: Timo Bingmann <tb@panthema.net>
Parameters:
  filename  A filename to process
Options:
  -r, --rounds N  Run N rounds of the experiment.
  -s, --size      Number of bytes to process.
Nice output, notice the line wrapping of the description and formatting of parameters and arguments. These too are wrapped if the description is too long.
We now try to give the program some arguments:
$ ./common_cmdline_parser_example -s 2GiB -r 42 /dev/null
Option -s, --size set to 2147483648.
Option -r, --rounds N set to 42.
Parameter filename set to "/dev/null".
Command line parsed okay.
Parameters:
  filename        (string)            "/dev/null"
Options:
  -r, --rounds N  (unsigned integer)  42
  -s, --size      (bytes)             2147483648
The output shows pretty much what happens. The command line parser is by default in a verbose mode outputting all arguments and values parsed. The debug summary shows to have values the corresponding variables were set.
One feature worth naming is that the parser also supports lists of strings, i.e. std::vector<std::string> via CmdlineParser::AddParamStringlist() and similar.
Definition at line 79 of file cmdline_parser.hpp.
#include <cmdline_parser.hpp>
Public Member Functions
~CmdlineParser ()
Delete all added arguments.
void AddBytes (char key, const std::string &longkey, const std::string &keytype, uint32_t &dest, const std::string &desc)
void AddBytes (char key, const std::string &longkey, const std::string &keytype, uint64_t &dest, const std::string &desc)
void AddBytes (char key, const std::string &longkey, uint32_t &dest, const std::string &desc)
void AddBytes (char key, const std::string &longkey, uint64_t &dest, const std::string &desc)
void AddDouble (char key, const std::string &longkey, const std::string &keytype, double &dest, const std::string &desc)
void AddDouble (char key, const std::string &longkey, double &dest, const std::string &desc)
void AddFlag (char key, const std::string &longkey, const std::string &keytype, bool &dest, const std::string &desc)
void AddFlag (char key, const std::string &longkey, bool &dest, const std::string &desc)
void AddInt (char key, const std::string &longkey, const std::string &keytype, int &dest, const std::string &desc)
void AddInt (char key, const std::string &longkey, int &dest, const std::string &desc)
void AddOptParamBytes (const std::string &name, uint32_t &dest, const std::string &desc)
void AddOptParamBytes (const std::string &name, uint64_t &dest, const std::string &desc)
void AddOptParamDouble (const std::string &name, double &dest, const std::string &desc)
add optional double parameter [name] with description and store to dest
void AddOptParamInt (const std::string &name, int &dest, const std::string &desc)
void AddOptParamSizeT (const std::string &name, size_t &dest, const std::string &desc)
add optional size_t parameter [name] with description and store to dest
void AddOptParamString (const std::string &name, std::string &dest, const std::string &desc)
add optional string parameter [name] with description and store to dest
void AddOptParamStringlist (const std::string &name, std::vector< std::string > &dest, const std::string &desc)
void AddOptParamUInt (const std::string &name, unsigned int &dest, const std::string &desc)
void AddParamBytes (const std::string &name, uint32_t &dest, const std::string &desc)
void AddParamBytes (const std::string &name, uint64_t &dest, const std::string &desc)
void AddParamDouble (const std::string &name, double &dest, const std::string &desc)
add double parameter [name] with description and store to dest
void AddParamInt (const std::string &name, int &dest, const std::string &desc)
add signed integer parameter [name] with description and store to dest
void AddParamSizeT (const std::string &name, size_t &dest, const std::string &desc)
add size_t parameter [name] with description and store to dest
void AddParamString (const std::string &name, std::string &dest, const std::string &desc)
add string parameter [name] with description and store to dest
void AddParamStringlist (const std::string &name, std::vector< std::string > &dest, const std::string &desc)
void AddParamUInt (const std::string &name, unsigned int &dest, const std::string &desc)
add unsigned integer parameter [name] with description and store to dest
void AddSizeT (char key, const std::string &longkey, const std::string &keytype, size_t &dest, const std::string &desc)
void AddSizeT (char key, const std::string &longkey, size_t &dest, const std::string &desc)
void AddString (char key, const std::string &longkey, const std::string &keytype, std::string &dest, const std::string &desc)
add string option -key, –longkey [keytype] and store to dest
void AddString (char key, const std::string &longkey, std::string &dest, const std::string &desc)
add string option -key, –longkey [keytype] and store to dest
void AddStringlist (char key, const std::string &longkey, const std::string &keytype, std::vector< std::string > &dest, const std::string &desc)
add string list option -key, –longkey [keytype] and store to dest
void AddStringlist (char key, const std::string &longkey, std::vector< std::string > &dest, const std::string &desc)
add string list option -key, –longkey [keytype] and store to dest
void AddUInt (char key, const std::string &longkey, const std::string &keytype, unsigned int &dest, const std::string &desc)
void AddUInt (char key, const std::string &longkey, unsigned int &dest, const std::string &desc)
void PrintResult (std::ostream &os=std::cout)
print nicely formatted result of processing
void PrintUsage (std::ostream &os=std::cout)
bool Process (int argc, const char *const *argv, std::ostream &os=std::cout)
void SetAuthor (const std::string &author)
Set author of program, will be wrapped.
void SetDescription (const std::string &description)
Set description of program, text will be wrapped.
void SetVerboseProcess (bool verbose_process)
Set verbose processing of command line arguments.
Static Public Member Functions
static void OutputWrap (std::ostream &os, const std::string &text, size_t wraplen, size_t indent_first=0, size_t indent_rest=0, size_t current=0, size_t indent_newline=0)
Private Types
using ArgumentList = std::vector< Argument * >
option and parameter list type
Private Member Functions
void CalcOptMax (const Argument *arg)
update maximum formatting width for new option
void CalcParamMax (const Argument *arg)
update maximum formatting width for new parameter
void PrintOptionError (int argc, const char *const *argv, const Argument *arg, std::ostream &os)
print error about option.
void PrintParamError (int argc, const char *const *argv, const Argument *arg, std::ostream &os)
print error about parameter.
Private Attributes
std::string author_
user set author of program, will be wrapped
std::string description_
user set description of program, will be wrapped
unsigned int linewrap_ = 80
set line wrap length
int opt_maxlong_ = 8
formatting width for options, '-s, –switch <#>'
ArgumentList optlist_
list of options available
int param_maxlong_ = 8
formatting width for parameters, 'param <#>'
ArgumentList paramlist_
list of parameters, both required and optional
const char * progname_ = nullptr
argv[0] for usage.
bool verbose_process_ = false
verbose processing of arguments
Static Private Attributes
static constexpr int maxtypename_ = 16
maximum length of a TypeName() result
Member Typedef Documentation
using ArgumentList = std::vector<Argument*> private
option and parameter list type
Definition at line 96 of file cmdline_parser.hpp.
Constructor & Destructor Documentation
~CmdlineParser ()
Delete all added arguments.
Definition at line 436 of file cmdline_parser.cpp.
References CmdlineParser::optlist_, and CmdlineParser::paramlist_.
Member Function Documentation
void AddBytes (char key, const std::string & longkey, const std::string & keytype, uint32_t & dest, const std::string & desc)
add SI/IEC suffixes byte size option -key, –longkey [keytype] and store to 64-bit dest
Definition at line 515 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddBytes().
void AddBytes (char key, const std::string & longkey, const std::string & keytype, uint64_t & dest, const std::string & desc)
add SI/IEC suffixes byte size option -key, –longkey [keytype] and store to 64-bit dest
Definition at line 525 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
void AddBytes (char key, const std::string & longkey, uint32_t & dest, const std::string & desc)
add SI/IEC suffixes byte size option -key, –longkey [keytype] and store to 32-bit dest
Definition at line 592 of file cmdline_parser.cpp.
References CmdlineParser::AddBytes().
void AddBytes (char key, const std::string & longkey, uint64_t & dest, const std::string & desc)
add SI/IEC suffixes byte size option -key, –longkey [keytype] and store to 64-bit dest
Definition at line 600 of file cmdline_parser.cpp.
References CmdlineParser::AddBytes().
void AddDouble (char key, const std::string & longkey, const std::string & keytype, double & dest, const std::string & desc)
add double option -key, –longkey [keytype] with description and store to dest
Definition at line 505 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddDouble(), and main().
void AddDouble (char key, const std::string & longkey, double & dest, const std::string & desc)
add double option -key, –longkey [keytype] with description and store to dest
Definition at line 584 of file cmdline_parser.cpp.
References CmdlineParser::AddDouble().
void AddFlag (char key, const std::string & longkey, const std::string & keytype, bool & dest, const std::string & desc)
add boolean option flag -key, –longkey [keytype] with description and store to dest
Definition at line 465 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddFlag(), and main().
void AddFlag (char key, const std::string & longkey, bool & dest, const std::string & desc)
add boolean option flag -key, –longkey with description and store to dest
Definition at line 554 of file cmdline_parser.cpp.
References CmdlineParser::AddFlag().
void AddInt (char key, const std::string & longkey, const std::string & keytype, int & dest, const std::string & desc)
add signed integer option -key, –longkey [keytype] with description and store to dest
Definition at line 475 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddInt().
void AddInt (char key, const std::string & longkey, int & dest, const std::string & desc)
add signed integer option -key, –longkey with description and store to dest
Definition at line 561 of file cmdline_parser.cpp.
References CmdlineParser::AddInt().
void AddOptParamBytes (const std::string & name, uint32_t & dest, const std::string & desc)
add optional SI/IEC suffixes byte size parameter [name] with description and store to dest
Definition at line 729 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddOptParamBytes (const std::string & name, uint64_t & dest, const std::string & desc)
add optional SI/IEC suffixes byte size parameter [name] with description and store to dest
Definition at line 738 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddOptParamDouble (const std::string & name, double & dest, const std::string & desc)
add optional double parameter [name] with description and store to dest
Definition at line 720 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddOptParamInt (const std::string & name, int & dest, const std::string & desc)
add optional signed integer parameter [name] with description and store to dest
Definition at line 695 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddOptParamSizeT (const std::string & name, size_t & dest, const std::string & desc)
add optional size_t parameter [name] with description and store to dest
Definition at line 712 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddOptParamString (const std::string & name, std::string & dest, const std::string & desc)
add optional string parameter [name] with description and store to dest
Definition at line 746 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddOptParamStringlist (const std::string & name, std::vector< std::string > & dest, const std::string & desc)
add optional string parameter [name] with description and store to dest
Warning
this parameter must be last, as it will gobble all non-option arguments!
Definition at line 756 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddOptParamUInt (const std::string & name, unsigned int & dest, const std::string & desc)
add optional unsigned integer parameter [name] with description and store to dest
Definition at line 704 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddParamBytes (const std::string & name, uint32_t & dest, const std::string & desc)
add SI/IEC suffixes byte size parameter [name] with description and store to dest
Definition at line 656 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddParamBytes (const std::string & name, uint64_t & dest, const std::string & desc)
add SI/IEC suffixes byte size parameter [name] with description and store to dest
Definition at line 665 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddParamDouble (const std::string & name, double & dest, const std::string & desc)
add double parameter [name] with description and store to dest
Definition at line 647 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddParamInt (const std::string & name, int & dest, const std::string & desc)
add signed integer parameter [name] with description and store to dest
Definition at line 623 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
void AddParamSizeT (const std::string & name, size_t & dest, const std::string & desc)
add size_t parameter [name] with description and store to dest
Definition at line 639 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddParamString (const std::string & name, std::string & dest, const std::string & desc)
add string parameter [name] with description and store to dest
Definition at line 673 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddParamStringlist (const std::string & name, std::vector< std::string > & dest, const std::string & desc)
add string list parameter [name] with description and store to dest.
Warning
this parameter must be last, as it will gobble all non-option arguments!
Definition at line 683 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddParamUInt (const std::string & name, unsigned int & dest, const std::string & desc)
add unsigned integer parameter [name] with description and store to dest
Definition at line 631 of file cmdline_parser.cpp.
References CmdlineParser::CalcParamMax(), and CmdlineParser::paramlist_.
Referenced by main().
void AddSizeT (char key, const std::string & longkey, const std::string & keytype, size_t & dest, const std::string & desc)
add size_t option -key, –longkey [keytype] with description and store to dest
Definition at line 495 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddSizeT(), and main().
void AddSizeT (char key, const std::string & longkey, size_t & dest, const std::string & desc)
add size_t option -key, –longkey [keytype] with description and store to dest
Definition at line 576 of file cmdline_parser.cpp.
References CmdlineParser::AddSizeT().
void AddString (char key, const std::string & longkey, const std::string & keytype, std::string & dest, const std::string & desc)
add string option -key, –longkey [keytype] and store to dest
Definition at line 534 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddString(), and main().
void AddString (char key, const std::string & longkey, std::string & dest, const std::string & desc)
add string option -key, –longkey [keytype] and store to dest
Definition at line 607 of file cmdline_parser.cpp.
References CmdlineParser::AddString().
void AddStringlist (char key, const std::string & longkey, const std::string & keytype, std::vector< std::string > & dest, const std::string & desc)
add string list option -key, –longkey [keytype] and store to dest
Definition at line 543 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddStringlist().
void AddStringlist (char key, const std::string & longkey, std::vector< std::string > & dest, const std::string & desc)
add string list option -key, –longkey [keytype] and store to dest
Definition at line 614 of file cmdline_parser.cpp.
References CmdlineParser::AddStringlist().
void AddUInt (char key, const std::string & longkey, const std::string & keytype, unsigned int & dest, const std::string & desc)
add unsigned integer option -key, –longkey [keytype] with description and store to dest
Definition at line 485 of file cmdline_parser.cpp.
References CmdlineParser::CalcOptMax(), and CmdlineParser::optlist_.
Referenced by CmdlineParser::AddUInt(), and main().
void AddUInt (char key, const std::string & longkey, unsigned int & dest, const std::string & desc)
add unsigned integer option -key, –longkey [keytype] with description and store to dest
Definition at line 568 of file cmdline_parser.cpp.
References CmdlineParser::AddUInt().
void CalcOptMax (const Argument * arg) private
update maximum formatting width for new option
Definition at line 380 of file cmdline_parser.cpp.
References thrill::common::max(), and CmdlineParser::opt_maxlong_.
Referenced by CmdlineParser::AddBytes(), CmdlineParser::AddDouble(), CmdlineParser::AddFlag(), CmdlineParser::AddInt(), CmdlineParser::AddSizeT(), CmdlineParser::AddString(), CmdlineParser::AddStringlist(), and CmdlineParser::AddUInt().
void CalcParamMax (const Argument * arg) private
update maximum formatting width for new parameter
Definition at line 386 of file cmdline_parser.cpp.
References thrill::common::max(), and CmdlineParser::param_maxlong_.
Referenced by CmdlineParser::AddOptParamBytes(), CmdlineParser::AddOptParamDouble(), CmdlineParser::AddOptParamInt(), CmdlineParser::AddOptParamSizeT(), CmdlineParser::AddOptParamString(), CmdlineParser::AddOptParamStringlist(), CmdlineParser::AddOptParamUInt(), CmdlineParser::AddParamBytes(), CmdlineParser::AddParamDouble(), CmdlineParser::AddParamInt(), CmdlineParser::AddParamSizeT(), CmdlineParser::AddParamString(), CmdlineParser::AddParamStringlist(), and CmdlineParser::AddParamUInt().
void OutputWrap (std::ostream & os, const std::string & text, size_t wraplen, size_t indent_first = 0, size_t indent_rest = 0, size_t current = 0, size_t indent_newline = 0) static
Wrap a long string at spaces into lines. Prefix is added unconditionally to each line. Lines are wrapped after wraplen characters if possible.
Definition at line 393 of file cmdline_parser.cpp.
Referenced by CmdlineParser::PrintUsage().
void PrintOptionError (int argc, const char *const * argv, const Argument * arg, std::ostream & os) private
print error about option.
Definition at line 833 of file cmdline_parser.cpp.
References CmdlineParser::PrintUsage().
Referenced by CmdlineParser::Process().
void PrintParamError (int argc, const char *const * argv, const Argument * arg, std::ostream & os) private
print error about parameter.
Definition at line 846 of file cmdline_parser.cpp.
References CmdlineParser::PrintUsage().
Referenced by CmdlineParser::Process().
void PrintResult (std::ostream & os = std::cout)
print nicely formatted result of processing
Definition at line 1022 of file cmdline_parser.cpp.
References thrill::common::max(), CmdlineParser::maxtypename_, CmdlineParser::opt_maxlong_, CmdlineParser::optlist_, CmdlineParser::param_maxlong_, and CmdlineParser::paramlist_.
Referenced by main().
void PrintUsage (std::ostream & os = std::cout)
output nicely formatted usage information including description of all parameters and options.
Definition at line 766 of file cmdline_parser.cpp.
References CmdlineParser::author_, CmdlineParser::description_, CmdlineParser::linewrap_, CmdlineParser::opt_maxlong_, CmdlineParser::optlist_, CmdlineParser::OutputWrap(), CmdlineParser::param_maxlong_, CmdlineParser::paramlist_, and CmdlineParser::progname_.
Referenced by CmdlineParser::PrintOptionError(), CmdlineParser::PrintParamError(), and CmdlineParser::Process().
bool Process (int argc, const char *const * argv, std::ostream & os = std::cout)
parse command line options as specified by the options and parameters added.
Returns
true if command line is okay and all required parameters are present.
Definition at line 859 of file cmdline_parser.cpp.
References CmdlineParser::optlist_, CmdlineParser::paramlist_, CmdlineParser::PrintOptionError(), CmdlineParser::PrintParamError(), CmdlineParser::PrintUsage(), CmdlineParser::progname_, and CmdlineParser::verbose_process_.
Referenced by main().
void SetAuthor (const std::string & author)
Set author of program, will be wrapped.
Definition at line 452 of file cmdline_parser.cpp.
References CmdlineParser::author_.
Referenced by main().
void SetDescription (const std::string & description)
Set description of program, text will be wrapped.
Definition at line 447 of file cmdline_parser.cpp.
References CmdlineParser::description_.
Referenced by main().
void SetVerboseProcess (bool verbose_process)
Set verbose processing of command line arguments.
Definition at line 457 of file cmdline_parser.cpp.
References CmdlineParser::verbose_process_.
Referenced by main().
Member Data Documentation
std::string author_ private
user set author of program, will be wrapped
Definition at line 117 of file cmdline_parser.hpp.
Referenced by CmdlineParser::PrintUsage(), and CmdlineParser::SetAuthor().
std::string description_ private
user set description of program, will be wrapped
Definition at line 115 of file cmdline_parser.hpp.
Referenced by CmdlineParser::PrintUsage(), and CmdlineParser::SetDescription().
unsigned int linewrap_ = 80 private
set line wrap length
Definition at line 120 of file cmdline_parser.hpp.
Referenced by CmdlineParser::PrintUsage().
constexpr int maxtypename_ = 16 static private
maximum length of a TypeName() result
Definition at line 123 of file cmdline_parser.hpp.
Referenced by CmdlineParser::PrintResult().
int opt_maxlong_ = 8 private
formatting width for options, '-s, –switch <#>'
Definition at line 104 of file cmdline_parser.hpp.
Referenced by CmdlineParser::CalcOptMax(), CmdlineParser::PrintResult(), and CmdlineParser::PrintUsage().
ArgumentList optlist_ private
list of options available
Definition at line 99 of file cmdline_parser.hpp.
Referenced by CmdlineParser::AddBytes(), CmdlineParser::AddDouble(), CmdlineParser::AddFlag(), CmdlineParser::AddInt(), CmdlineParser::AddSizeT(), CmdlineParser::AddString(), CmdlineParser::AddStringlist(), CmdlineParser::AddUInt(), CmdlineParser::PrintResult(), CmdlineParser::PrintUsage(), CmdlineParser::Process(), and CmdlineParser::~CmdlineParser().
int param_maxlong_ = 8 private
formatting width for parameters, 'param <#>'
Definition at line 106 of file cmdline_parser.hpp.
Referenced by CmdlineParser::CalcParamMax(), CmdlineParser::PrintResult(), and CmdlineParser::PrintUsage().
ArgumentList paramlist_ private
list of parameters, both required and optional
Definition at line 101 of file cmdline_parser.hpp.
Referenced by CmdlineParser::AddOptParamBytes(), CmdlineParser::AddOptParamDouble(), CmdlineParser::AddOptParamInt(), CmdlineParser::AddOptParamSizeT(), CmdlineParser::AddOptParamString(), CmdlineParser::AddOptParamStringlist(), CmdlineParser::AddOptParamUInt(), CmdlineParser::AddParamBytes(), CmdlineParser::AddParamDouble(), CmdlineParser::AddParamInt(), CmdlineParser::AddParamSizeT(), CmdlineParser::AddParamString(), CmdlineParser::AddParamStringlist(), CmdlineParser::AddParamUInt(), CmdlineParser::PrintResult(), CmdlineParser::PrintUsage(), CmdlineParser::Process(), and CmdlineParser::~CmdlineParser().
const char* progname_ = nullptr private
argv[0] for usage.
Definition at line 109 of file cmdline_parser.hpp.
Referenced by CmdlineParser::PrintUsage(), and CmdlineParser::Process().
bool verbose_process_ = false private
verbose processing of arguments
Definition at line 112 of file cmdline_parser.hpp.
Referenced by CmdlineParser::Process(), and CmdlineParser::SetVerboseProcess().
The documentation for this class was generated from the following files:
thrill/common/cmdline_parser.hpp
thrill/common/cmdline_parser.cpp