Thrill: DeltaStreamWriter< StreamWriter, Type, offset_ > Class Template Reference
DeltaStreamWriter< StreamWriter, Type, offset_ > Class Template Reference
Detailed Description
template<typename StreamWriter, typename Type, Type offset_ = Type()>
class thrill::core::DeltaStreamWriter< StreamWriter, Type, offset_ >
Definition at line 27 of file delta_stream.hpp.
#include <delta_stream.hpp>
Public Member Functions
DeltaStreamWriter (StreamWriter &writer, const Type &initial=Type())
void Put (const Type &value)
Private Attributes
Type delta_ = Type()
delta for output
StreamWriter & writer_
output writer
Constructor & Destructor Documentation
DeltaStreamWriter()
DeltaStreamWriter (StreamWriter & writer, const Type & initial = Type()) inline explicit
Definition at line 30 of file delta_stream.hpp.
Member Function Documentation
Put()
void Put (const Type & value) inline
Definition at line 34 of file delta_stream.hpp.
References DeltaStreamWriter< StreamWriter, Type, offset_ >::delta_, gen_data::value, and DeltaStreamWriter< StreamWriter, Type, offset_ >::writer_.
Referenced by DuplicateDetection::WriteEncodedHashes(), and LocationDetection< thrill::api::JoinNode::HashCount >::WriteOccurenceCounts().
Member Data Documentation
delta_
Type delta_ = Type() private
delta for output
Definition at line 45 of file delta_stream.hpp.
Referenced by DeltaStreamReader< StreamReader, Type, offset_ >::Next(), and DeltaStreamWriter< StreamWriter, Type, offset_ >::Put().
writer_
StreamWriter& writer_ private
output writer
Definition at line 42 of file delta_stream.hpp.
Referenced by DeltaStreamWriter< StreamWriter, Type, offset_ >::Put().
The documentation for this class was generated from the following file:
thrill/core/delta_stream.hpp