Thrill: Manager Class Reference
Manager Class Reference final
Thrill Layers » Network Subsystem Layer
Detailed Description
Initializes communication channels, manages communication channels and handles errors.
This class is responsible for initializing the three net::Groups for the major network components, SystemControl, FlowControl and DataManagement,
Definition at line 53 of file manager.hpp.
#include <manager.hpp>
Public Member Functions
Manager (const Manager &)=delete
non-copyable: delete copy-constructor
Manager (std::array< GroupPtr, kGroupCount > &&groups, common::JsonLogger &logger) noexcept
Construct Manager from already initialized net::Groups.
Manager (std::vector< GroupPtr > &&groups, common::JsonLogger &logger) noexcept
Construct Manager from already initialized net::Groups.
void Close ()
Group & GetDataGroup ()
Returns the net::Group for the data manager.
Group & GetFlowGroup ()
Returns the net::Group for the flow control channel.
size_t my_host_rank () const
size_t num_hosts () const
Manager & operator= (const Manager &)=delete
non-copyable: delete assignment operator
net::Traffic Traffic () const
calculate overall traffic for final stats
Methods for ProfileTask
void RunTask (const std::chrono::steady_clock::time_point &tp) final
method called by ProfileThread.
Public Member Functions inherited from ProfileTask
virtual ~ProfileTask ()
virtual destructor
Static Public Attributes
static constexpr size_t kGroupCount = 2
The count of net::Groups to initialize.
Private Attributes
std::array< GroupPtr, kGroupCount > groups_
The Groups initialized and managed by this Manager.
common::JsonLogger & logger_
JsonLogger for statistics output.
std::chrono::steady_clock::time_point tp_last_
last time statistics where outputted
Static Private Attributes
static constexpr bool debug = false
Constructor & Destructor Documentation
Manager() [1/3]
Manager (const Manager &) delete
non-copyable: delete copy-constructor
Manager() [2/3]
Manager (std::array< GroupPtr, kGroupCount > && groups, common::JsonLogger & logger) noexcept
Construct Manager from already initialized net::Groups.
Definition at line 50 of file group.cpp.
Manager() [3/3]
Manager (std::vector< GroupPtr > && groups, common::JsonLogger & logger) noexcept
Construct Manager from already initialized net::Groups.
Definition at line 54 of file group.cpp.
Member Function Documentation
Close()
void Close ()
Definition at line 61 of file group.cpp.
References Manager::groups_, and Manager::kGroupCount.
GetDataGroup()
Group& GetDataGroup () inline
Returns the net::Group for the data manager.
Definition at line 90 of file manager.hpp.
References Traffic::Traffic().
GetFlowGroup()
Group& GetFlowGroup () inline
Returns the net::Group for the flow control channel.
Definition at line 85 of file manager.hpp.
my_host_rank()
size_t my_host_rank () const inline
Definition at line 63 of file manager.hpp.
num_hosts()
size_t num_hosts () const inline
Definition at line 67 of file manager.hpp.
operator=()
Manager& operator= (const Manager &) delete
non-copyable: delete assignment operator
RunTask()
void RunTask (const std::chrono::steady_clock::time_point & tp) final virtual
method called by ProfileThread.
Implements ProfileTask.
Definition at line 84 of file group.cpp.
References Group::connection(), Manager::groups_, Manager::kGroupCount, JsonLogger::line(), Manager::logger_, Group::my_host_rank(), Group::num_hosts(), Connection::prev_rx_bytes_, Connection::prev_tx_bytes_, Connection::rx_active_, Connection::rx_bytes_, JsonLine::sub(), Manager::tp_last_, Connection::tx_active_, and Connection::tx_bytes_.
Traffic()
net::Traffic Traffic () const
calculate overall traffic for final stats
Definition at line 67 of file group.cpp.
References Group::connection(), Manager::groups_, Manager::kGroupCount, Group::my_host_rank(), Group::num_hosts(), Connection::rx_bytes_, and Connection::tx_bytes_.
Referenced by CountTrianglesGenerated(), JoinTPCH4(), Context::Launch(), main(), Percentiles(), RunHashWordCount(), RunJoinPageRankEdgePerLine(), RunKMeansFile(), RunKMeansGenerated(), RunPageRankJoinGenerated(), and RunWordCount().
Member Data Documentation
debug
constexpr bool debug = false static private
Definition at line 55 of file manager.hpp.
groups_
std::array<GroupPtr, kGroupCount> groups_ private
The Groups initialized and managed by this Manager.
Definition at line 108 of file manager.hpp.
Referenced by Manager::Close(), Manager::RunTask(), and Manager::Traffic().
kGroupCount
constexpr size_t kGroupCount = 2 static
The count of net::Groups to initialize.
Definition at line 61 of file manager.hpp.
Referenced by Manager::Close(), thrill::api::ConstructLoopbackHostContexts(), thrill::api::RunBackendLoopback(), thrill::api::RunLocalSameThread(), Manager::RunTask(), and Manager::Traffic().
logger_
common::JsonLogger& logger_ private
JsonLogger for statistics output.
Definition at line 111 of file manager.hpp.
Referenced by Manager::RunTask().
tp_last_
std::chrono::steady_clock::time_point tp_last_ private
last time statistics where outputted
Definition at line 114 of file manager.hpp.
Referenced by Manager::RunTask().
The documentation for this class was generated from the following files:
thrill/net/manager.hpp
thrill/net/group.cpp