Thrill: ServingRequest Class Reference
ServingRequest Class Reference final
I/O Requests and Queues
Detailed Description
Request which serves an I/O by calling the synchronous routine of the file.
Definition at line 28 of file serving_request.hpp.
#include <serving_request.hpp>
Public Member Functions
ServingRequest (const CompletionHandler &on_cmpl, const FileBasePtr &file, void *buffer, offset_type offset, size_type bytes, ReadOrWriteType type)
Public Member Functions inherited from Request
Request (const CompletionHandler &on_complete, const FileBasePtr &file, void *buffer, offset_type offset, size_type bytes, ReadOrWriteType type)
ctor: initialize
Request (const Request &)=delete
non-copyable: delete copy-constructor
Request (Request &&)=default
move-constructor: default
virtual ~Request ()
Request & operator= (const Request &)=delete
non-copyable: delete assignment operator
Request & operator= (Request &&)=default
move-assignment operator: default
const FileBasePtr & file () const
void * buffer () const
offset_type offset () const
size_type bytes () const
ReadOrWriteType type () const
void check_alignment () const
std::ostream & print (std::ostream &out) const
Dumps properties of a request.
void save_error (const mem::safe_string &msg)
IoError * error () const
return error if one occured
void check_error ()
Rises an exception if there was an error with the I/O.
void wait (bool measure_time=true)
Suspends calling thread until completion of the request.
virtual bool cancel ()
Cancel a request.
bool poll ()
Polls the status of the request.
const char * io_type () const
Identifies the type of I/O implementation.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Protected Member Functions
void serve ()
Protected Member Functions inherited from Request
void check_nref (bool after=false)
virtual void completed (bool canceled)
called by file implementations when the request completes
Additional Inherited Members
Public Types inherited from Request
using offset_type = size_t
type for offsets within a file
enum ReadOrWriteType { READ, WRITE }
using size_type = size_t
type for block transfer sizes
enum State { OP = 0, DONE = 1, READY2DIE = 2 }
Protected Attributes inherited from Request
mem::safe_unique_ptr< IoError > error_
CompletionHandler on_complete_
FileBasePtr file_
file implementation to perform I/O with
void * buffer_
data buffer to transfer
offset_type offset_
offset within file
size_type bytes_
number of bytes at buffer_ to transfer
ReadOrWriteType type_
READ or WRITE.
Static Protected Attributes inherited from Request
static constexpr bool debug = false
Constructor & Destructor Documentation
ServingRequest (const CompletionHandler & on_cmpl, const FileBasePtr & file, void * buffer, offset_type offset, size_type bytes, ReadOrWriteType type)
Definition at line 25 of file serving_request.cpp.
References Request::check_alignment().
Member Function Documentation
void serve () protected
Definition at line 40 of file serving_request.cpp.
References Request::buffer_, Request::bytes_, Request::check_nref(), Request::completed(), Request::file_, LOG, Request::offset_, Request::READ, IoError::safe_message(), Request::save_error(), and Request::type_.
The documentation for this class was generated from the following files:
thrill/io/serving_request.hpp
thrill/io/serving_request.cpp