Thrill: SimpleGlobUtil Class Reference
SimpleGlobUtil Class Reference
Detailed Description
String manipulation functions.
Definition at line 235 of file simple_glob.hpp.
#include <simple_glob.hpp>
Static Public Member Functions
static int strcasecmp (const char *s1, const char *s2)
static const char * strchr (const char *s, char c)
static const wchar_t * strchr (const wchar_t *s, wchar_t c)
static int strcmp (const char *s1, const char *s2)
static int strcmp (const wchar_t *s1, const wchar_t *s2)
static void strcpy_s (char *dst, size_t n, const char *src)
static void strcpy_s (wchar_t *dst, size_t n, const wchar_t *src)
static size_t strlen (const char *s)
static size_t strlen (const wchar_t *s)
static const char * strrchr (const char *s, char c)
static const wchar_t * strrchr (const wchar_t *s, wchar_t c)
Member Function Documentation
static int strcasecmp (const char * s1, const char * s2) inline static
Definition at line 302 of file simple_glob.hpp.
References sg_strcasecmp, and SOCHAR_T.
Referenced by CSimpleGlobTempl< SOCHAR >::fileSortCompare().
static const char* strchr (const char * s, char c) inline static
Definition at line 238 of file simple_glob.hpp.
References sg_strchr.
Referenced by CSimpleGlobTempl< SOCHAR >::Add().
static const wchar_t* strchr (const wchar_t * s, wchar_t c) inline static
Definition at line 242 of file simple_glob.hpp.
static int strcmp (const char * s1, const char * s2) inline static
Definition at line 290 of file simple_glob.hpp.
References sg_strcmp, and SOCHAR_T.
static int strcmp (const wchar_t * s1, const wchar_t * s2) inline static
Definition at line 293 of file simple_glob.hpp.
static void strcpy_s (char * dst, size_t n, const char * src) inline static
Definition at line 271 of file simple_glob.hpp.
References sg_strcpy_s.
Referenced by CSimpleGlobTempl< SOCHAR >::Add(), and CSimpleGlobTempl< SOCHAR >::AppendName().
static void strcpy_s (wchar_t * dst, size_t n, const wchar_t * src) inline static
Definition at line 276 of file simple_glob.hpp.
static size_t strlen (const char * s) inline static
Definition at line 265 of file simple_glob.hpp.
Referenced by CSimpleGlobTempl< SOCHAR >::AppendName().
static size_t strlen (const wchar_t * s) inline static
Definition at line 266 of file simple_glob.hpp.
static const char* strrchr (const char * s, char c) inline static
Definition at line 251 of file simple_glob.hpp.
References sg_strrchr.
Referenced by CSimpleGlobTempl< SOCHAR >::Add().
static const wchar_t* strrchr (const wchar_t * s, wchar_t c) inline static
Definition at line 255 of file simple_glob.hpp.
The documentation for this class was generated from the following file:
thrill/vfs/simple_glob.hpp