Thrill: ReadBinaryNode< ValueType >::VfsFileBlockSource Class Reference
ReadBinaryNode< ValueType >::VfsFileBlockSource Class Reference
Detailed Description
template<typename ValueType>
class thrill::api::ReadBinaryNode< ValueType >::VfsFileBlockSource
Definition at line 273 of file read_binary.hpp.
#include <read_binary.hpp>
Public Member Functions
VfsFileBlockSource (const FileInfo &fileinfo, Context &ctx, size_t &stats_total_bytes, size_t &stats_total_reads)
data::PinnedBlock NextBlock ()
Public Attributes
const size_t block_size = data::default_block_size
Private Attributes
Context & context_
bool done_ = false
bool is_compressed_
size_t remain_size_
size_t & stats_total_bytes_
size_t & stats_total_reads_
vfs::ReadStreamPtr stream_
Constructor & Destructor Documentation
VfsFileBlockSource (const FileInfo & fileinfo, Context & ctx, size_t & stats_total_bytes, size_t & stats_total_reads) inline
Definition at line 278 of file read_binary.hpp.
References ReadBinaryNode< ValueType >::VfsFileBlockSource::is_compressed_, thrill::vfs::OpenReadStream(), ReadBinaryNode< ValueType >::FileInfo::path, ReadBinaryNode< ValueType >::FileInfo::range, and ReadBinaryNode< ValueType >::VfsFileBlockSource::stream_.
Member Function Documentation
data::PinnedBlock NextBlock () inline
Definition at line 296 of file read_binary.hpp.
References BlockPool::AllocateByteBlock(), Context::block_pool(), ReadBinaryNode< ValueType >::VfsFileBlockSource::block_size, bytes, ReadBinaryNode< ValueType >::VfsFileBlockSource::context_, ReadBinaryNode< ValueType >::VfsFileBlockSource::done_, ReadBinaryNode< ValueType >::VfsFileBlockSource::is_compressed_, Context::local_worker_id(), LOG, min(), ReadBinaryNode< ValueType >::VfsFileBlockSource::remain_size_, ReadBinaryNode< ValueType >::VfsFileBlockSource::stats_total_bytes_, ReadBinaryNode< ValueType >::VfsFileBlockSource::stats_total_reads_, and ReadBinaryNode< ValueType >::VfsFileBlockSource::stream_.
Member Data Documentation
const size_t block_size = data::default_block_size
Definition at line 276 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
Context& context_ private
Definition at line 333 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
bool done_ = false private
Definition at line 339 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
bool is_compressed_ private
Definition at line 336 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock(), and ReadBinaryNode< ValueType >::VfsFileBlockSource::VfsFileBlockSource().
size_t remain_size_ private
Definition at line 335 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
size_t& stats_total_bytes_ private
Definition at line 337 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
size_t& stats_total_reads_ private
Definition at line 338 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock().
vfs::ReadStreamPtr stream_ private
Definition at line 334 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::VfsFileBlockSource::NextBlock(), and ReadBinaryNode< ValueType >::VfsFileBlockSource::VfsFileBlockSource().
The documentation for this class was generated from the following file:
thrill/api/read_binary.hpp