Thrill: block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType > Class Template Reference
block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType > Class Template Reference
Detailed Description
template<class SwappableBlockType>
class foxxll::block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >
Block scheduling algorithm caching via the least recently used policy (offline), and prefetching in addition.
Definition at line 1149 of file block_scheduler.hpp.
#include <block_scheduler.hpp>
Classes
struct read_after_write
struct scheduled_block_meta
struct write_read_request
Public Member Functions
block_scheduler_algorithm_offline_lru_prefetching (block_scheduler_type &bs)
block_scheduler_algorithm_offline_lru_prefetching (block_scheduler_algorithm_type *old)
virtual ~block_scheduler_algorithm_offline_lru_prefetching ()
virtual internal_block_type & acquire (const swappable_block_identifier_type sbid, const bool uninitialized=false)
virtual void deinitialize (swappable_block_identifier_type sbid)
virtual bool evictable_blocks_empty ()
virtual
swappable_block_identifier_type evictable_blocks_pop ()
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid)
virtual void initialize (swappable_block_identifier_type sbid, external_block_type eblock)
virtual void release (swappable_block_identifier_type sbid, const bool dirty)
Public Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm (block_scheduler_type &bs)
block_scheduler_algorithm (block_scheduler_algorithm *old)
block_scheduler_algorithm (const block_scheduler_algorithm &)=delete
non-copyable: delete copy-constructor
virtual ~block_scheduler_algorithm ()
virtual void explicit_timestep ()
virtual const
prediction_sequence_type & get_prediction_sequence () const
virtual bool is_initialized (const swappable_block_identifier_type sbid) const
virtual bool is_simulating () const
block_scheduler_algorithm & operator= (const block_scheduler_algorithm &)=delete
non-copyable: delete assignment operator
virtual void swappable_blocks_resize (swappable_block_identifier_type)
Protected Types
using block_scheduler_algorithm_type = block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_operation = typename block_scheduler_type::block_scheduler_operation
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using prediction_sequence_type = typename block_scheduler_type::prediction_sequence_type
using scheduled_blocks_iterator = typename scheduled_blocks_type::iterator
using scheduled_blocks_reference = typename scheduled_blocks_type::reference
using scheduled_blocks_type = std::map< swappable_block_identifier_type, scheduled_block_meta >
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
using swappable_blocks_iterator = typename std::vector< SwappableBlockType >::iterator
using time_type = typename block_scheduler_algorithm_type::time_type
using write_scheduled_blocks_iterator = typename write_scheduled_blocks_type::iterator
using write_scheduled_blocks_reference = typename write_scheduled_blocks_type::reference
using write_scheduled_blocks_type = std::map< swappable_block_identifier_type, write_read_request * >
Protected Types inherited from block_scheduler_algorithm< SwappableBlockType >
using block_scheduler_type = block_scheduler< SwappableBlockType >
using external_block_type = typename block_scheduler_type::external_block_type
using internal_block_type = typename block_scheduler_type::internal_block_type
using prediction_sequence_type = typename block_scheduler_type::prediction_sequence_type
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type
using time_type = typename block_scheduler_type::time_type
Protected Member Functions
void deinit ()
internal_block_type * get_ready_block (const scheduled_blocks_iterator &schedule_meta)
block_scheduler_algorithm_type * give_up (std::string err_msg="detected some error in the prediction sequence")
void init (block_scheduler_algorithm_type *old_algo)
void operation_done (scheduled_blocks_iterator &schedule_meta)
void return_free_internal_block (internal_block_type *iblock)
void schedule_next_operations ()
void schedule_read (scheduled_blocks_iterator block_to_read)
write_read_request * schedule_write (const swappable_block_identifier_type sbid)
bool shall_be_cleaned (const scheduled_blocks_iterator &schedule_meta) const
bool shall_be_read (const scheduled_blocks_iterator &schedule_meta, const bool ignore_first=true) const
bool shall_keep_internal_block (const scheduled_blocks_iterator &schedule_meta, const bool ignore_first=true) const
bool try_interrupt_read (const write_scheduled_blocks_iterator &writing_block)
void wait_on_read (const scheduled_blocks_iterator &schedule_meta)
void wait_on_write (const write_scheduled_blocks_iterator &writing_block)
void wait_on_write (const swappable_block_identifier_type &writing_block)
void wait_on_write (const scheduled_blocks_iterator &schedule_meta)
Protected Member Functions inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_algorithm * get_algorithm_from_block_scheduler ()
internal_block_type * get_free_internal_block_from_block_scheduler ()
void return_free_internal_block_to_block_scheduler (internal_block_type *iblock)
Return an internal_block to the block_scheduler.
Protected Attributes
std::set
< swappable_block_identifier_type > free_evictable_blocks
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
prediction_sequence_type::iterator next_op_to_schedule
scheduled_blocks_type scheduled_blocks
Holds not internal swappable_blocks, whose next access has already been scheduled.
std::set
< swappable_block_identifier_type > scheduled_evictable_blocks
write_scheduled_blocks_type write_scheduled_blocks
Holds swappable_blocks, whose internal block has been taken away but the clean did not finish yet.
Protected Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
prediction_sequence_type prediction_sequence
std::vector< SwappableBlockType > & swappable_blocks
Additional Inherited Members
Public Attributes inherited from block_scheduler_algorithm< SwappableBlockType >
block_scheduler_type & bs
Member Typedef Documentation
using block_scheduler_algorithm_type = block_scheduler_algorithm<SwappableBlockType> protected
Definition at line 1156 of file block_scheduler.hpp.
using block_scheduler_operation = typename block_scheduler_type::block_scheduler_operation protected
Definition at line 1162 of file block_scheduler.hpp.
using block_scheduler_type = block_scheduler<SwappableBlockType> protected
Definition at line 1155 of file block_scheduler.hpp.
using external_block_type = typename block_scheduler_type::external_block_type protected
Definition at line 1158 of file block_scheduler.hpp.
using internal_block_type = typename block_scheduler_type::internal_block_type protected
Definition at line 1157 of file block_scheduler.hpp.
using prediction_sequence_type = typename block_scheduler_type::prediction_sequence_type protected
Definition at line 1161 of file block_scheduler.hpp.
using scheduled_blocks_iterator = typename scheduled_blocks_type::iterator protected
Definition at line 1166 of file block_scheduler.hpp.
using scheduled_blocks_reference = typename scheduled_blocks_type::reference protected
Definition at line 1167 of file block_scheduler.hpp.
using scheduled_blocks_type = std::map<swappable_block_identifier_type, scheduled_block_meta> protected
Definition at line 1165 of file block_scheduler.hpp.
using swappable_block_identifier_type = typename block_scheduler_type::swappable_block_identifier_type protected
Definition at line 1159 of file block_scheduler.hpp.
using swappable_blocks_iterator = typename std::vector<SwappableBlockType>::iterator protected
Definition at line 1163 of file block_scheduler.hpp.
using time_type = typename block_scheduler_algorithm_type::time_type protected
Definition at line 1160 of file block_scheduler.hpp.
using write_scheduled_blocks_iterator = typename write_scheduled_blocks_type::iterator protected
Definition at line 1169 of file block_scheduler.hpp.
using write_scheduled_blocks_reference = typename write_scheduled_blocks_type::reference protected
Definition at line 1170 of file block_scheduler.hpp.
using write_scheduled_blocks_type = std::map<swappable_block_identifier_type, write_read_request*> protected
Definition at line 1168 of file block_scheduler.hpp.
Constructor & Destructor Documentation
block_scheduler_algorithm_offline_lru_prefetching (block_scheduler_type & bs) inline explicit
Definition at line 1670 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::get_algorithm_from_block_scheduler(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init().
block_scheduler_algorithm_offline_lru_prefetching (block_scheduler_algorithm_type * old) inline explicit
Definition at line 1675 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init().
virtual ~block_scheduler_algorithm_offline_lru_prefetching () inline virtual
Definition at line 1679 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, foxxll::pop_begin(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, and TLX_LOG1.
Member Function Documentation
virtual internal_block_type& acquire (const swappable_block_identifier_type sbid, const bool uninitialized = false) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1701 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::get_ready_block(), block_scheduler< SwappableBlockType >::op_acquire, block_scheduler< SwappableBlockType >::op_acquire_uninitialized, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::operation_done(), block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_evictable_blocks, block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, tlx::unused(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_read().
void deinit () inline protected
Definition at line 1639 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_evictable_blocks, TLX_LOG1, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::evictable_blocks_empty(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::~block_scheduler_algorithm_offline_lru_prefetching().
virtual void deinitialize (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1812 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::next_op_to_schedule, block_scheduler< SwappableBlockType >::op_deinitialize, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::shall_keep_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, and TLX_LOG1.
virtual bool evictable_blocks_empty () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1692 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init().
virtual swappable_block_identifier_type evictable_blocks_pop () inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1698 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, and foxxll::pop_begin().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init().
virtual external_block_type extract_external_block (swappable_block_identifier_type sbid) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1876 of file block_scheduler.hpp.
internal_block_type* get_ready_block (const scheduled_blocks_iterator & schedule_meta) inline protected
Wait for the write of the giver to finish and return reserved internal_block.
side-effect: erases entry for the write of the giver from write_scheduled_blocks
Definition at line 1442 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::acquire().
block_scheduler_algorithm_type* give_up (std::string err_msg = "detected some error in the prediction sequence") inline protected
Definition at line 1523 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::bs, block_scheduler< SwappableBlockType >::switch_algorithm_to(), and TLX_LOG1.
void init (block_scheduler_algorithm_type * old_algo) inline protected
Definition at line 1627 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, block_scheduler_algorithm< SwappableBlockType >::get_algorithm_from_block_scheduler(), block_scheduler_algorithm< SwappableBlockType >::get_prediction_sequence(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::next_op_to_schedule, block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::block_scheduler_algorithm_offline_lru_prefetching().
virtual void initialize (swappable_block_identifier_type sbid, external_block_type eblock) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1854 of file block_scheduler.hpp.
void operation_done (scheduled_blocks_iterator & schedule_meta) inline protected
Definition at line 1513 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::acquire(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release().
virtual void release (swappable_block_identifier_type sbid, const bool dirty) inline virtual
Implements block_scheduler_algorithm< SwappableBlockType >.
Definition at line 1751 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::next_op_to_schedule, block_scheduler< SwappableBlockType >::op_release, block_scheduler< SwappableBlockType >::op_release_dirty, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::operation_done(), block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::return_free_internal_block(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_write(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::shall_be_cleaned(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::shall_keep_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
void return_free_internal_block (internal_block_type * iblock) inline protected
Definition at line 1534 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::return_free_internal_block_to_block_scheduler().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::~block_scheduler_algorithm_offline_lru_prefetching().
void schedule_next_operations () inline protected
Definition at line 1537 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::free_evictable_blocks, block_scheduler_algorithm< SwappableBlockType >::get_free_internal_block_from_block_scheduler(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::next_op_to_schedule, block_scheduler< SwappableBlockType >::op_acquire, block_scheduler< SwappableBlockType >::op_acquire_uninitialized, block_scheduler< SwappableBlockType >::op_deinitialize, foxxll::pop_begin(), block_scheduler_algorithm< SwappableBlockType >::prediction_sequence, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_write(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::scheduled_evictable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::shall_be_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::shall_keep_internal_block(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_read_request::taker, and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release().
void schedule_read (scheduled_blocks_iterator block_to_read) inline protected
Schedule an internal and external block to read.
If the giver is still writing, schedule read via its write_read_request.
Definition at line 1285 of file block_scheduler.hpp.
References tlx::swap(), block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::try_interrupt_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
write_read_request* schedule_write (const swappable_block_identifier_type sbid) inline protected
Schedule an internal, possibly dirty swappable_block to write.
The block becomes not dirty. if it was dirty, an entry in write_scheduled_blocks is made referencing the write_read_request.
Parameters
sbid block to write
Returns
pointer to the write_read_request
Definition at line 1238 of file block_scheduler.hpp.
References block_scheduler_algorithm< SwappableBlockType >::swappable_blocks, tlx::unused(), CountingPtr< Type, Deleter >::valid(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_read_request::write_req, and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
bool shall_be_cleaned (const scheduled_blocks_iterator & schedule_meta) const inline protected
Definition at line 1479 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_acquire, block_scheduler< SwappableBlockType >::op_acquire_uninitialized, block_scheduler< SwappableBlockType >::op_deinitialize, block_scheduler< SwappableBlockType >::op_extract_external_block, block_scheduler< SwappableBlockType >::op_initialize, block_scheduler< SwappableBlockType >::op_release, and block_scheduler< SwappableBlockType >::op_release_dirty.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release().
bool shall_be_read (const scheduled_blocks_iterator & schedule_meta, const bool ignore_first = true) const inline protected
Definition at line 1505 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_acquire, and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
bool shall_keep_internal_block (const scheduled_blocks_iterator & schedule_meta, const bool ignore_first = true) const inline protected
Definition at line 1450 of file block_scheduler.hpp.
References block_scheduler< SwappableBlockType >::op_acquire, block_scheduler< SwappableBlockType >::op_acquire_uninitialized, block_scheduler< SwappableBlockType >::op_deinitialize, block_scheduler< SwappableBlockType >::op_extract_external_block, block_scheduler< SwappableBlockType >::op_initialize, block_scheduler< SwappableBlockType >::op_release, block_scheduler< SwappableBlockType >::op_release_dirty, and block_scheduler_algorithm< SwappableBlockType >::swappable_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
bool try_interrupt_read (const write_scheduled_blocks_iterator & writing_block) inline protected
Try to interrupt a read scheduled in a write_read_request.
side-effect: possibly erases entry from write_scheduled_blocks, so the iterator writing_block may become invalid
Returns
if successful
Definition at line 1262 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_read().
void wait_on_read (const scheduled_blocks_iterator & schedule_meta) inline protected
Wait for the read to finish.
side-effect: erases entry for the write of the giver from write_scheduled_blocks
Definition at line 1429 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::acquire(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit().
void wait_on_write (const write_scheduled_blocks_iterator & writing_block) inline protected
Wait for the write to finish.
side-effect: erases entry from write_scheduled_blocks
Definition at line 1397 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::get_ready_block(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::try_interrupt_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_read(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
void wait_on_write (const swappable_block_identifier_type & writing_block) inline protected
Wait for the write to finish.
side-effect: erases entry from write_scheduled_blocks
Definition at line 1407 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::write_scheduled_blocks.
void wait_on_write (const scheduled_blocks_iterator & schedule_meta) inline protected
Wait for the write of the giver to finish.
side-effect: erases entry from write_scheduled_blocks
Definition at line 1417 of file block_scheduler.hpp.
References block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
Member Data Documentation
std::set<swappable_block_identifier_type> free_evictable_blocks protected
Holds swappable blocks, whose internal block can be freed, i.e. that are internal but unacquired.
Definition at line 1223 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::evictable_blocks_empty(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::evictable_blocks_pop(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::~block_scheduler_algorithm_offline_lru_prefetching().
prediction_sequence_type::iterator next_op_to_schedule protected
Definition at line 1231 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::init(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
scheduled_blocks_type scheduled_blocks protected
Holds not internal swappable_blocks, whose next access has already been scheduled.
Definition at line 1227 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::acquire(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::operation_done(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
std::set<swappable_block_identifier_type> scheduled_evictable_blocks protected
Definition at line 1224 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::acquire(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinitialize(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations().
write_scheduled_blocks_type write_scheduled_blocks protected
Holds swappable_blocks, whose internal block has been taken away but the clean did not finish yet.
Definition at line 1230 of file block_scheduler.hpp.
Referenced by block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::deinit(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::release(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_next_operations(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_read(), block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_write(), and block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::wait_on_write().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/mng/block_scheduler.hpp