Thrill: Config Class Reference
Config Class Reference
Asynchronous I/O Layer
Detailed Description
Access point to disks properties. Since 1.4.0: no config files are read automatically!
Remarks
is a singleton
Definition at line 114 of file config_file.hpp.
#include <config_file.hpp>
Public Member Functions
Initialization Functions
void check_initialized ()
void load_config_file (const std::string &config_path)
Load disk configuration file.
void load_default_config ()
Load default configuration.
Config & add_disk (const DiskConfig &cfg)
Query Functions
size_t disks_number ()
std::pair< unsigned, unsigned > regular_disk_range () const
std::pair< unsigned, unsigned > flash_range () const
DiskConfig & disk (size_t disk)
Returns mutable disk_config structure for additional disk parameters.
const DiskConfig & disk (size_t disk) const
Returns constant disk_config structure for additional disk parameters.
const std::string & disk_path (size_t disk) const
uint64_t disk_size (size_t disk) const
const std::string & disk_io_impl (size_t disk) const
uint64_t total_size () const
Returns the total size over all disks.
Public Member Functions inherited from Singleton< Config >
Singleton ()=default
Singleton (const Singleton &)=delete
non-copyable: delete copy-constructor
Singleton (Singleton &&)=default
move-constructor: default
Singleton & operator= (const Singleton &)=delete
non-copyable: delete assignment operator
Singleton & operator= (Singleton &&)=default
move-assignment operator: default
Private Types
using disk_list_type = std::vector< DiskConfig >
typedef of list of configured disks
Private Member Functions
Config ()
~Config ()
deletes autogrow files
void find_config ()
Search several places for a config file.
void initialize ()
Private Attributes
disk_list_type disks_list
list of configured disks
unsigned first_flash
In disks_list, flash devices come after all regular disks.
bool is_initialized
Finished initializing config.
Static Private Attributes
static constexpr bool debug = true
Automatic Disk Enumeration Functions
unsigned int max_device_id_
static counter for automatic physical device enumeration
unsigned int get_max_device_id ()
Returns automatic physical device id counter.
unsigned int get_next_device_id ()
Returns next automatic physical device id counter.
void update_max_device_id (unsigned int devid)
Update the automatic physical device id counter.
Additional Inherited Members
Static Public Member Functions inherited from Singleton< Config >
static instance_pointer GetInstance ()
Member Typedef Documentation
using disk_list_type = std::vector<DiskConfig> private
typedef of list of configured disks
Definition at line 120 of file config_file.hpp.
Constructor & Destructor Documentation
Config () inline private
Constructor: this must be inlined to print the header version string.
Definition at line 133 of file config_file.hpp.
~Config () private
deletes autogrow files
Definition at line 48 of file config_file.cpp.
References Config::disks_list.
Member Function Documentation
Config& add_disk (const DiskConfig & cfg) inline
Add a disk to the configuration list.
Warning
This function should only be used during initialization, as it has no effect after construction of block_manager.
Definition at line 168 of file config_file.hpp.
References Config::disks_list.
void check_initialized () inline
Check that initialize() was called.
Note
This function need not be called by the user, block_manager will always call it.
Definition at line 154 of file config_file.hpp.
References Config::initialize(), and Config::is_initialized.
Referenced by BlockManager::BlockManager(), Config::disk(), and Config::disks_number().
DiskConfig& disk (size_t disk) inline
Returns mutable disk_config structure for additional disk parameters.
Definition at line 220 of file config_file.hpp.
References Config::check_initialized(), and Config::disks_list.
Referenced by BlockManager::BlockManager(), Config::disk(), Config::disk_io_impl(), Config::disk_path(), and Config::disk_size().
const DiskConfig& disk (size_t disk) const inline
Returns constant disk_config structure for additional disk parameters.
Definition at line 226 of file config_file.hpp.
References Config::disk(), Config::disks_list, and Config::is_initialized.
const std::string& disk_io_impl (size_t disk) const inline
Returns name of I/O implementation of particular disk.
Parameters
disk disk's identifier
Definition at line 249 of file config_file.hpp.
References Config::disk(), Config::disks_list, and Config::is_initialized.
const std::string& disk_path (size_t disk) const inline
Returns path of disks.
Parameters
disk disk's identifier
Returns
string that contains the disk's path name
Definition at line 234 of file config_file.hpp.
References Config::disk(), Config::disks_list, and Config::is_initialized.
uint64_t disk_size (size_t disk) const inline
Returns disk size.
Parameters
disk disk's identifier
Returns
disk size in bytes
Definition at line 242 of file config_file.hpp.
References Config::disk(), Config::disks_list, and Config::is_initialized.
size_t disks_number () inline
Returns number of disks available to user.
Returns
number of disks
Definition at line 200 of file config_file.hpp.
References Config::check_initialized(), and Config::disks_list.
Referenced by BlockManager::BlockManager().
void find_config () private
Search several places for a config file.
Definition at line 72 of file config_file.cpp.
References thrill::io::exist_file(), Config::load_config_file(), and Config::load_default_config().
Referenced by Config::initialize().
std::pair<unsigned, unsigned> flash_range () const inline
Returns contiguous range of flash devices in the array of all disks.
Returns
range [begin, end) of flash device indices
Definition at line 214 of file config_file.hpp.
References Config::disks_list, Config::first_flash, and Config::is_initialized.
unsigned int get_max_device_id ()
Returns automatic physical device id counter.
Definition at line 179 of file config_file.cpp.
References Config::max_device_id_.
unsigned int get_next_device_id ()
Returns next automatic physical device id counter.
Definition at line 184 of file config_file.cpp.
References Config::max_device_id_.
void initialize () private
If disk list is empty, then search different locations for a disk configuration file, or load a default config if everything fails.
Definition at line 60 of file config_file.cpp.
References Config::disks_list, Config::find_config(), Config::is_initialized, and Config::max_device_id_.
Referenced by Config::check_initialized().
void load_config_file (const std::string & config_path)
Load disk configuration file.
Definition at line 144 of file config_file.cpp.
References Config::disks_list, Config::first_flash, DiskConfig::flash, Config::load_default_config(), DiskConfig::parse_line(), and THRILL_THROW.
Referenced by Config::find_config().
void load_default_config ()
Load default configuration.
Definition at line 119 of file config_file.cpp.
References DiskConfig::autogrow, DiskConfig::delete_on_exit, Config::disks_list, Config::first_flash, DiskConfig::path, THRILL_THROW_WIN_LASTERROR, and DiskConfig::unlink_on_open.
Referenced by Config::find_config(), and Config::load_config_file().
std::pair<unsigned, unsigned> regular_disk_range () const inline
Returns contiguous range of regular disks w/o flash devices in the array of all disks.
Returns
range [begin, end) of regular disk indices
Definition at line 207 of file config_file.hpp.
References Config::first_flash, and Config::is_initialized.
uint64_t total_size () const
Returns the total size over all disks.
Definition at line 194 of file config_file.cpp.
References Config::disks_list, and Config::is_initialized.
void update_max_device_id (unsigned int devid)
Update the automatic physical device id counter.
Definition at line 189 of file config_file.cpp.
References Config::max_device_id_.
Member Data Documentation
constexpr bool debug = true static private
Definition at line 116 of file config_file.hpp.
disk_list_type disks_list private
list of configured disks
Definition at line 123 of file config_file.hpp.
Referenced by Config::add_disk(), Config::disk(), Config::disk_io_impl(), Config::disk_path(), Config::disk_size(), Config::disks_number(), Config::flash_range(), Config::initialize(), Config::load_config_file(), Config::load_default_config(), Config::total_size(), and Config::~Config().
unsigned first_flash private
In disks_list, flash devices come after all regular disks.
Definition at line 126 of file config_file.hpp.
Referenced by Config::flash_range(), Config::load_config_file(), Config::load_default_config(), and Config::regular_disk_range().
bool is_initialized private
Finished initializing config.
Definition at line 129 of file config_file.hpp.
Referenced by Config::check_initialized(), Config::disk(), Config::disk_io_impl(), Config::disk_path(), Config::disk_size(), Config::flash_range(), Config::initialize(), Config::regular_disk_range(), and Config::total_size().
unsigned int max_device_id_ protected
static counter for automatic physical device enumeration
Definition at line 180 of file config_file.hpp.
Referenced by Config::get_max_device_id(), Config::get_next_device_id(), Config::initialize(), and Config::update_max_device_id().
The documentation for this class was generated from the following files:
thrill/io/config_file.hpp
thrill/io/config_file.cpp