Thrill: StackArena< Size > Class Template Reference
StackArena< Size > Class Template Reference
Detailed Description
template<size_t Size>
class thrill::mem::StackArena< Size >
Storage area allocated on the stack and usable by a StackAllocator.
Definition at line 35 of file stack_allocator.hpp.
#include <stack_allocator.hpp>
Public Member Functions
StackArena () noexcept
default constructor: free pointer at the beginning.
StackArena (const StackArena &)=delete
~StackArena ()
destructor clears ptr_ for debugging.
char * allocate (size_t n)
void deallocate (char *p, size_t n) noexcept
StackArena & operator= (const StackArena &)=delete
void reset ()
reset memory area
size_t used () const
return number of bytes used in StackArena
Static Public Member Functions
static constexpr size_t size ()
size of memory area
Private Member Functions
alignas (alignment) char buf_[Size]
stack memory area used for allocations.
bool pointer_in_buffer (char *p) noexcept
debug method to check whether ptr_ is still in buf_.
Private Attributes
char * ptr_
pointer into free bytes in buf_
Static Private Attributes
static constexpr size_t alignment = 16
Constructor & Destructor Documentation
StackArena () inline noexcept
default constructor: free pointer at the beginning.
Definition at line 51 of file stack_allocator.hpp.
~StackArena () inline
destructor clears ptr_ for debugging.
Definition at line 54 of file stack_allocator.hpp.
References StackArena< Size >::ptr_.
StackArena (const StackArena< Size > &) delete
Member Function Documentation
alignas (alignment) private
stack memory area used for allocations.
char* allocate (size_t n) inline
Definition at line 59 of file stack_allocator.hpp.
References StackArena< Size >::alignment, malloc(), StackArena< Size >::pointer_in_buffer(), and StackArena< Size >::ptr_.
void deallocate (char * p, size_t n) inline noexcept
Definition at line 75 of file stack_allocator.hpp.
References free(), StackArena< Size >::pointer_in_buffer(), and StackArena< Size >::ptr_.
StackArena& operator= (const StackArena< Size > &) delete
bool pointer_in_buffer (char * p) inline private noexcept
debug method to check whether ptr_ is still in buf_.
Definition at line 46 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate(), and StackArena< Size >::deallocate().
void reset () inline
reset memory area
Definition at line 96 of file stack_allocator.hpp.
References StackArena< Size >::ptr_.
static constexpr size_t size () inline static
size of memory area
Definition at line 90 of file stack_allocator.hpp.
size_t used () const inline
return number of bytes used in StackArena
Definition at line 93 of file stack_allocator.hpp.
References StackArena< Size >::ptr_.
Member Data Documentation
constexpr size_t alignment = 16 static private
Definition at line 37 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate().
char* ptr_ private
pointer into free bytes in buf_
Definition at line 43 of file stack_allocator.hpp.
Referenced by StackArena< Size >::allocate(), StackArena< Size >::deallocate(), StackArena< Size >::reset(), StackArena< Size >::used(), and StackArena< Size >::~StackArena().
The documentation for this class was generated from the following file:
thrill/mem/stack_allocator.hpp