Thrill: ReferenceCounter Class Reference
ReferenceCounter Class Reference
Detailed Description
Provides reference counting abilities for use with CountingPtr.
Use as superclass of the actual object, this adds a reference_count_ value. Then either use CountingPtr as pointer to manage references and deletion, or just do normal new and delete.
Definition at line 268 of file counting_ptr.hpp.
#include <counting_ptr.hpp>
Public Member Functions
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Private Attributes
std::atomic< size_t > reference_count_
Constructor & Destructor Documentation
ReferenceCounter () inline noexcept
new objects have zero reference count
Definition at line 277 of file counting_ptr.hpp.
ReferenceCounter (const ReferenceCounter &) inline noexcept
coping still creates a new object with zero reference count
Definition at line 281 of file counting_ptr.hpp.
~ReferenceCounter () inline
Definition at line 290 of file counting_ptr.hpp.
References ReferenceCounter::reference_count_.
Member Function Documentation
bool dec_reference () const inline noexcept
Call whenever resetting (i.e.
overwriting) a pointer to the object. IMPORTANT: In case of self-assignment, call AFTER inc_reference().
Returns
if the object has to be deleted (i.e. if it's reference count dropped to zero)
Definition at line 305 of file counting_ptr.hpp.
References ReferenceCounter::reference_count_.
void inc_reference () const inline noexcept
Call whenever setting a pointer to the object.
Definition at line 295 of file counting_ptr.hpp.
References ReferenceCounter::reference_count_.
ReferenceCounter& operator= (const ReferenceCounter &) inline noexcept
assignment operator, leaves pointers unchanged
Definition at line 285 of file counting_ptr.hpp.
size_t reference_count () const inline noexcept
Return the number of references to this object (for debugging)
Definition at line 315 of file counting_ptr.hpp.
References ReferenceCounter::reference_count_.
Referenced by Request::check_nref(), Request::check_nref_failed(), DIA< ValueType_, Stack_ >::node_refcount(), ByteBlock::Deleter::operator()(), Request::Request(), and Request::~Request().
bool unique () const inline noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Definition at line 311 of file counting_ptr.hpp.
References ReferenceCounter::reference_count_.
Member Data Documentation
std::atomic<size_t> reference_count_ mutable private
the reference count is kept mutable for CountingPtr<const Type> to change the reference count.
Definition at line 273 of file counting_ptr.hpp.
Referenced by ReferenceCounter::dec_reference(), ReferenceCounter::inc_reference(), ReferenceCounter::reference_count(), ReferenceCounter::unique(), and ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following file:
extlib/tlx/tlx/counting_ptr.hpp