Thrill: Stream Class Reference
Stream Class Reference abstract
Data Subsystem Layer
Detailed Description
Base class for common structures for ConcatStream and MixedStream.
This is also a virtual base class use by Multiplexer to pass blocks to streams! Instead, it contains common items like stats.
Definition at line 43 of file stream.hpp.
#include <stream.hpp>
Public Types
using Writer = DynBlockWriter
Public Member Functions
Stream (Multiplexer &multiplexer, const StreamId &id, size_t local_worker_id, size_t dia_id)
virtual ~Stream ()
virtual void Close ()=0
shuts the stream down.
virtual bool closed () const =0
virtual std::vector< Writer > GetWriters ()=0
const StreamId & id () const
size_t my_host_rank () const
Returns my_host_rank.
size_t my_worker_rank () const
Returns my_worker_rank_.
size_t num_hosts () const
Number of hosts in system.
size_t num_workers () const
Number of workers in system.
void OnAllClosed (const char *stream_type)
template<typename ItemType >
void Scatter (File &source, const std::vector< size_t > &offsets, bool consume=false)
Scatters a File to many worker: elements from [offset[0],offset[1]) are sent to the first worker, elements from [offset[1], offset[2]) are sent to the second worker, ..., elements from [offset[my_rank - 1],offset[my_rank]) are copied locally, ..., elements from [offset[num_workers - 1], offset[num_workers]) are sent to the last worker.
size_t workers_per_host () const
Returns workers_per_host.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Public Attributes
std::atomic< size_t > rx_int_blocks_ { 0 }
std::atomic< size_t > rx_int_bytes_ { 0 }
std::atomic< size_t > rx_int_items_ { 0 }
common::StatsTimerStart rx_lifetime_
size_t rx_net_blocks_ = 0
size_t rx_net_bytes_ = 0
size_t rx_net_items_ = 0
common::StatsTimerStopped rx_timespan_
std::atomic< size_t > tx_int_blocks_ { 0 }
std::atomic< size_t > tx_int_bytes_ { 0 }
std::atomic< size_t > tx_int_items_ { 0 }
common::StatsTimerStart tx_lifetime_
Timers from creation of stream until rx / tx direction is closed.
std::atomic< size_t > tx_net_blocks_ { 0 }
std::atomic< size_t > tx_net_bytes_ { 0 }
std::atomic< size_t > tx_net_items_ { 0 }
common::StatsTimerStopped tx_timespan_
Timers from first rx / tx package until rx / tx direction is closed.
Protected Attributes
size_t dia_id_
Associated DIANode id.
StreamId id_
our own stream id.
size_t local_worker_id_
Multiplexer & multiplexer_
reference to multiplexer
size_t remaining_closing_blocks_
common::Semaphore sem_closing_blocks_
number of received stream closing Blocks.
Member Typedef Documentation
using Writer = DynBlockWriter
Definition at line 46 of file stream.hpp.
Constructor & Destructor Documentation
Stream (Multiplexer & multiplexer, const StreamId & id, size_t local_worker_id, size_t dia_id)
Definition at line 20 of file stream.cpp.
~Stream () virtual default
Member Function Documentation
virtual void Close () pure virtual
shuts the stream down.
Implemented in CatStream, and MixStream.
virtual bool closed () const pure virtual
Implemented in CatStream, and MixStream.
virtual std::vector<Writer> GetWriters () pure virtual
Creates BlockWriters for each worker. BlockWriter can only be opened once, otherwise the block sequence is incorrectly interleaved!
Implemented in CatStream, and MixStream.
Referenced by Stream::Scatter().
const StreamId& id () const inline
Definition at line 53 of file stream.hpp.
References Stream::id_.
Referenced by CatStream::CatStream(), and MixStream::MixStream().
size_t my_host_rank () const inline
Returns my_host_rank.
Definition at line 56 of file stream.hpp.
References Stream::multiplexer_, and Multiplexer::my_host_rank().
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), MixStream::GetWriters(), MixStream::MixStream(), Stream::my_worker_rank(), and Stream::OnAllClosed().
size_t my_worker_rank () const inline
Returns my_worker_rank_.
Definition at line 65 of file stream.hpp.
References Stream::local_worker_id_, Stream::my_host_rank(), and Stream::workers_per_host().
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and MixStream::OnCloseStream().
size_t num_hosts () const inline
Number of hosts in system.
Definition at line 58 of file stream.hpp.
References Stream::multiplexer_, and Multiplexer::num_hosts().
Referenced by CatStream::CatStream(), MixStream::Close(), MixStream::GetWriters(), and MixStream::MixStream().
size_t num_workers () const inline
Number of workers in system.
Definition at line 60 of file stream.hpp.
References Stream::multiplexer_, and Multiplexer::num_workers().
Referenced by CatStream::CatStream(), MixStream::GetWriters(), MixStream::MixStream(), MixStream::OnCloseStream(), MixStream::OnStreamBlock(), and Stream::Scatter().
void OnAllClosed (const char * stream_type)
Definition at line 31 of file stream.cpp.
References Stream::dia_id_, Stream::id_, Stream::local_worker_id_, Multiplexer::logger(), Stream::multiplexer_, Stream::my_host_rank(), Stream::rx_int_blocks_, Stream::rx_int_bytes_, Stream::rx_int_items_, Stream::rx_net_blocks_, Stream::rx_net_bytes_, Stream::rx_net_items_, Stream::tx_int_blocks_, Stream::tx_int_bytes_, Stream::tx_int_items_, Stream::tx_net_blocks_, Stream::tx_net_bytes_, Stream::tx_net_items_, and Multiplexer::workers_per_host().
Referenced by MixStream::Close().
void Scatter (File & source, const std::vector< size_t > & offsets, bool consume = false) inline
Scatters a File to many worker: elements from [offset[0],offset[1]) are sent to the first worker, elements from [offset[1], offset[2]) are sent to the second worker, ..., elements from [offset[my_rank - 1],offset[my_rank]) are copied locally, ..., elements from [offset[num_workers - 1], offset[num_workers]) are sent to the last worker.
The number of given offsets must be equal to the net::Group::num_hosts() * workers_per_host_ + 1.
/param source File containing the data to be scattered.
/param offsets - as described above. offsets.size must be equal to num_workers + 1
Definition at line 97 of file stream.hpp.
References File::GetReader(), Stream::GetWriters(), Stream::num_workers(), and Stream::tx_timespan_.
size_t workers_per_host () const inline
Returns workers_per_host.
Definition at line 63 of file stream.hpp.
References Stream::multiplexer_, and Multiplexer::workers_per_host().
Referenced by CatStream::CatStream(), MixStream::Close(), MixStream::GetWriters(), MixStream::loopback_queue(), MixStream::MixStream(), and Stream::my_worker_rank().
Member Data Documentation
size_t dia_id_ protected
Associated DIANode id.
Definition at line 184 of file stream.hpp.
Referenced by Stream::OnAllClosed(), and MixStream::set_dia_id().
StreamId id_ protected
our own stream id.
Definition at line 179 of file stream.hpp.
Referenced by CatStream::CatStream(), MixStream::Close(), MixBlockQueueSink::Close(), MixStream::GetWriters(), Stream::id(), Stream::OnAllClosed(), MixStream::OnCloseStream(), and MixStream::OnStreamBlock().
size_t local_worker_id_ protected
Definition at line 181 of file stream.hpp.
Referenced by MixStream::Close(), MixStream::GetMixReader(), MixStream::GetWriters(), Stream::my_worker_rank(), and Stream::OnAllClosed().
Multiplexer& multiplexer_ protected
reference to multiplexer
Definition at line 187 of file stream.hpp.
Referenced by StreamSink::AppendPinnedBlock(), CatStream::CatStream(), StreamSink::Close(), MixStream::Close(), MixStream::GetWriters(), MixStream::MixStream(), Stream::my_host_rank(), Stream::num_hosts(), Stream::num_workers(), Stream::OnAllClosed(), and Stream::workers_per_host().
size_t remaining_closing_blocks_ protected
number of remaining expected stream closing operations. Required to know when to stop rx_lifetime
Definition at line 191 of file stream.hpp.
Referenced by MixStream::OnCloseStream().
std::atomic<size_t> rx_int_blocks_ { 0 }
Definition at line 162 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
std::atomic<size_t> rx_int_bytes_ { 0 }
Definition at line 162 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
std::atomic<size_t> rx_int_items_ { 0 }
StatsCounter for incoming data transfer. Exclusively contains only loopback (internal) data transfer
Definition at line 162 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
common::StatsTimerStart rx_lifetime_
Definition at line 170 of file stream.hpp.
Referenced by MixStream::OnCloseStream().
size_t rx_net_blocks_ = 0
Definition at line 152 of file stream.hpp.
Referenced by Stream::OnAllClosed(), MixStream::OnCloseStream(), and MixStream::OnStreamBlock().
size_t rx_net_bytes_ = 0
Definition at line 152 of file stream.hpp.
Referenced by Stream::OnAllClosed(), and MixStream::OnStreamBlock().
size_t rx_net_items_ = 0
StatsCounter for incoming data transfer. Does not include loopback data transfer
Definition at line 152 of file stream.hpp.
Referenced by Stream::OnAllClosed(), and MixStream::OnStreamBlock().
common::StatsTimerStopped rx_timespan_
Definition at line 173 of file stream.hpp.
Referenced by MixStream::GetMixReader(), MixStream::OnCloseStream(), and MixStream::OnStreamBlock().
common::Semaphore sem_closing_blocks_ protected
number of received stream closing Blocks.
Definition at line 194 of file stream.hpp.
Referenced by MixStream::Close(), and MixStream::OnCloseStream().
std::atomic<size_t> tx_int_blocks_ { 0 }
Definition at line 167 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
std::atomic<size_t> tx_int_bytes_ { 0 }
Definition at line 167 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
std::atomic<size_t> tx_int_items_ { 0 }
StatsCounters for outgoing data transfer - shared by all sinks. Exclusively contains only loopback (internal) data transfer
Definition at line 167 of file stream.hpp.
Referenced by CatStream::CatStream(), MixBlockQueueSink::Close(), and Stream::OnAllClosed().
common::StatsTimerStart tx_lifetime_
Timers from creation of stream until rx / tx direction is closed.
Definition at line 170 of file stream.hpp.
Referenced by MixStream::Close().
std::atomic<size_t> tx_net_blocks_ { 0 }
Definition at line 157 of file stream.hpp.
Referenced by StreamSink::Finalize(), and Stream::OnAllClosed().
std::atomic<size_t> tx_net_bytes_ { 0 }
Definition at line 157 of file stream.hpp.
Referenced by StreamSink::Finalize(), and Stream::OnAllClosed().
std::atomic<size_t> tx_net_items_ { 0 }
StatsCounters for outgoing data transfer - shared by all sinks. Does not include loopback data transfer
Definition at line 157 of file stream.hpp.
Referenced by StreamSink::Finalize(), and Stream::OnAllClosed().
common::StatsTimerStopped tx_timespan_
Timers from first rx / tx package until rx / tx direction is closed.
Definition at line 173 of file stream.hpp.
Referenced by MixStream::Close(), MixStream::GetWriters(), and Stream::Scatter().
The documentation for this class was generated from the following files:
thrill/data/stream.hpp
thrill/data/stream.cpp