Thrill: SHA1 Class Reference
SHA1 Class Reference
Thrill Layers » tlx - C++ Extensions and Utilities » Message Digests
Detailed Description
SHA-1 processor without external dependencies.
Definition at line 28 of file sha1.hpp.
#include <sha1.hpp>
Public Member Functions
SHA1 ()
construct empty object.
SHA1 (const void *data, uint32_t size)
construct context and process data range
SHA1 (const std::string &str)
construct context and process string
std::string digest ()
finalize computation and return 20 byte (160 bit) digest
std::string digest_hex ()
finalize computation and return 20 byte (160 bit) digest hex encoded
std::string digest_hex_uc ()
finalize computation and return 20 byte (160 bit) digest upper-case hex
void finalize (void *digest)
finalize computation and output 20 byte (160 bit) digest
void process (const void *data, uint32_t size)
process more data
void process (const std::string &str)
process more data
Static Public Attributes
static constexpr size_t kDigestLength = 20
digest length in bytes
Private Attributes
uint8_t buf_ [64]
uint32_t curlen_
uint64_t length_
uint32_t state_ [5]
Constructor & Destructor Documentation
SHA1() [1/3]
SHA1 ()
construct empty object.
Definition at line 118 of file sha1.cpp.
Referenced by tlx::sha1_hex(), and tlx::sha1_hex_uc().
SHA1() [2/3]
SHA1 (const void * data, uint32_t size)
construct context and process data range
Definition at line 128 of file sha1.cpp.
References SHA1::process().
SHA1() [3/3]
SHA1 (const std::string & str) explicit
construct context and process string
Definition at line 132 of file sha1.cpp.
References SHA1::process().
Member Function Documentation
digest()
std::string digest ()
finalize computation and return 20 byte (160 bit) digest
Definition at line 204 of file sha1.cpp.
References SHA1::finalize(), and SHA1::kDigestLength.
Referenced by SHA1::digest_hex(), and SHA1::digest_hex_uc().
digest_hex()
std::string digest_hex ()
finalize computation and return 20 byte (160 bit) digest hex encoded
Definition at line 210 of file sha1.cpp.
References SHA1::digest(), SHA1::finalize(), tlx::hexdump_lc(), and SHA1::kDigestLength.
digest_hex_uc()
std::string digest_hex_uc ()
finalize computation and return 20 byte (160 bit) digest upper-case hex
Definition at line 216 of file sha1.cpp.
References SHA1::digest(), SHA1::finalize(), tlx::hexdump(), and SHA1::kDigestLength.
finalize()
void finalize (void * digest)
finalize computation and output 20 byte (160 bit) digest
Definition at line 174 of file sha1.cpp.
References SHA1::buf_, SHA1::curlen_, SHA1::length_, tlx::digest_detail::sha1_compress(), SHA1::state_, tlx::digest_detail::store32h(), and tlx::digest_detail::store64h().
Referenced by SHA1::digest(), SHA1::digest_hex(), and SHA1::digest_hex_uc().
process() [1/2]
void process (const void * data, uint32_t size)
process more data
Definition at line 136 of file sha1.cpp.
References SHA1::buf_, SHA1::curlen_, SHA1::length_, tlx::digest_detail::min(), tlx::digest_detail::sha1_compress(), and SHA1::state_.
Referenced by SHA1::process(), and SHA1::SHA1().
process() [2/2]
void process (const std::string & str)
process more data
Definition at line 170 of file sha1.cpp.
References SHA1::process().
Member Data Documentation
buf_
uint8_t buf_[64] private
Definition at line 60 of file sha1.hpp.
Referenced by SHA1::finalize(), and SHA1::process().
curlen_
uint32_t curlen_ private
Definition at line 59 of file sha1.hpp.
Referenced by SHA1::finalize(), and SHA1::process().
kDigestLength
constexpr size_t kDigestLength = 20 static
digest length in bytes
Definition at line 44 of file sha1.hpp.
Referenced by SHA1::digest(), SHA1::digest_hex(), and SHA1::digest_hex_uc().
length_
uint64_t length_ private
Definition at line 57 of file sha1.hpp.
Referenced by SHA1::finalize(), and SHA1::process().
state_
uint32_t state_[5] private
Definition at line 58 of file sha1.hpp.
Referenced by SHA1::finalize(), and SHA1::process().
The documentation for this class was generated from the following files:
extlib/tlx/tlx/digest/sha1.hpp
extlib/tlx/tlx/digest/sha1.cpp