Thrill: ReadBinaryNode< ValueType > Class Template Reference
ReadBinaryNode< ValueType > Class Template Reference final
DIA API Layer
Detailed Description
template<typename ValueType>
class thrill::api::ReadBinaryNode< ValueType >
A DIANode which performs a line-based Read operation.
Read reads a file from the file system and emits it as a DIA.
Definition at line 45 of file read_binary.hpp.
#include <read_binary.hpp>
Classes
struct FileInfo
structure to store info on what to read from files
class VfsFileBlockSource
Public Types
using Super = SourceNode< ValueType >
using VfsFileBlockReader = data::BlockReader< VfsFileBlockSource >
Public Types inherited from SourceNode< ValueType >
using Super = DIANode< ValueType >
Public Types inherited from DIANode< ValueType >
using Callback = tlx::delegate< void(const ValueType &)>
Public Types inherited from DIABase
using DIABasePtr = tlx::CountingPtr< DIABase >
Public Member Functions
ReadBinaryNode (Context &ctx, const std::vector< std::string > &globlist, uint64_t size_limit, bool local_storage)
ReadBinaryNode (Context &ctx, const std::string &glob, uint64_t size_limit, bool local_storage)
Public Member Functions inherited from SourceNode< ValueType >
SourceNode (Context &ctx, const char *label)
Public Member Functions inherited from DIANode< ValueType >
DIANode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DIANode, which sets references to the parent nodes.
DIANode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DIANode, which sets references to the parent nodes.
virtual void AddChild (DIABase *node, const Callback &callback=Callback(), size_t parent_index=0)
Enables children to push their "folded" function chains to their parent.
std::vector< DIABase * > children () const override
Returns the children of this DIABase.
void PushFile (data::File &file, bool consume) const
void PushItem (const ValueType &item) const
Method for derived classes to Push a single item to all children.
void RemoveAllChildren () override
void RemoveChild (DIABase *node) override
void RunPushData () override
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
virtual void DecConsumeCounter (size_t counter)
const size_t & dia_id () const
return unique id of DIANode subclass as stored by StatsNode
virtual bool ForwardDataOnly () const
virtual void IncConsumeCounter (size_t counter)
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
virtual void SetConsumeCounter (size_t counter)
DIAState state () const
virtual DIAMemUse PreOpMemUse ()
Amount of RAM used by PreOp after StartPreOp()
virtual void StartPreOp (size_t)
Virtual method for preparing start of PushData.
virtual bool OnPreOpFile (const data::File &, size_t)
virtual void StopPreOp (size_t)
Virtual method for preparing end of PushData.
virtual DIAMemUse ExecuteMemUse ()
Amount of RAM used by Execute()
virtual void Execute ()=0
Virtual execution method. Triggers actual computation in sub-classes.
virtual DIAMemUse PushDataMemUse ()
Amount of RAM used by PushData()
virtual void PushData (bool consume)=0
Virtual method for pushing data. Triggers actual pushing in sub-classes.
virtual void Dispose ()
Virtual clear method. Triggers actual disposing in sub-classes.
Public Member Functions inherited from ReferenceCounter
ReferenceCounter () noexcept
new objects have zero reference count
ReferenceCounter (const ReferenceCounter &) noexcept
coping still creates a new object with zero reference count
~ReferenceCounter ()
bool dec_reference () const noexcept
Call whenever resetting (i.e.
void inc_reference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCounter & operator= (const ReferenceCounter &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCounter is referenced by only one CountingPtr.
Public Attributes
data::File ext_file_ { context_.GetFile(this) }
local_storage
size_limit
size_t stats_total_bytes = 0
size_t stats_total_reads = 0
bool use_ext_file_ = false
File containing Blocks mapped directly to a io fileimpl.
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes
static constexpr size_t fixed_size_
fixed size of ValueType or zero.
static constexpr bool is_fixed_size_
flag whether ValueType is fixed size
static constexpr uint64_t no_size_limit_
sentinel to disable size limit
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Static Private Attributes
static constexpr bool debug = false
static constexpr bool debug_no_extfile = false
for testing old method of pushing items instead of PushFile().
Additional Inherited Members
Protected Attributes inherited from DIANode< ValueType >
std::vector< Child > children_
Callback functions from the child nodes.
Protected Attributes inherited from DIABase
Context & context_
associated Context
const size_t dia_id_
DIA serial id.
const char *const label_
DOp node static label.
DIAState state_ = DIAState::NEW
State of the DIANode. State is NEW on creation.
std::vector< DIABasePtr > parents_
Parents of this DIABase.
DIAMemUse mem_limit_ = 0
size_t consume_counter_ = 1
Member Typedef Documentation
using Super = SourceNode<ValueType>
Definition at line 56 of file read_binary.hpp.
using VfsFileBlockReader = data::BlockReader<VfsFileBlockSource>
Definition at line 59 of file read_binary.hpp.
Constructor & Destructor Documentation
ReadBinaryNode (Context & ctx, const std::vector< std::string > & globlist, uint64_t size_limit, bool local_storage) inline
Definition at line 82 of file read_binary.hpp.
References File::AppendBlock(), Range::begin, Context::block_pool(), Context::CalculateLocalRange(), Context::CalculateLocalRangeOnHost(), FileList::contains_compressed, FileList::contains_remote_uri, DIABase::context_, ReadBinaryNode< ValueType >::debug_no_extfile, thrill::data::default_block_size, die, Range::end, ReadBinaryNode< ValueType >::ext_file_, thrill::vfs::File, ReadBinaryNode< ValueType >::fixed_size_, thrill::vfs::Glob(), ReadBinaryNode< ValueType >::FileInfo::is_compressed, ReadBinaryNode< ValueType >::is_fixed_size_, tlx::join(), LOG, BlockPool::MapExternalBlock(), max(), min(), file::NO_LOCK, ReadBinaryNode< ValueType >::no_size_limit_, Context::num_workers(), ReadBinaryNode< ValueType >::FileInfo::path, ReadBinaryNode< ValueType >::FileInfo::range, file::RDONLY, FileList::size_ex_psum(), FileList::size_inc_psum(), sLOG, FileList::total_size, and ReadBinaryNode< ValueType >::use_ext_file_.
ReadBinaryNode (Context & ctx, const std::string & glob, uint64_t size_limit, bool local_storage) inline
Definition at line 224 of file read_binary.hpp.
Member Data Documentation
constexpr bool debug = false static private
Definition at line 47 of file read_binary.hpp.
constexpr bool debug_no_extfile = false static private
for testing old method of pushing items instead of PushFile().
Definition at line 50 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
data::File ext_file_ { context_.GetFile(this) }
Definition at line 268 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
constexpr size_t fixed_size_ static
Initial value:
=
        data::Serialization<VfsFileBlockReader, ValueType>::fixed_size
fixed size of ValueType or zero.
Definition at line 66 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
constexpr bool is_fixed_size_ static
Initial value:
=
        data::Serialization<VfsFileBlockReader, ValueType>::is_fixed_size
flag whether ValueType is fixed size
Definition at line 62 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
local_storage
Definition at line 227 of file read_binary.hpp.
constexpr uint64_t no_size_limit_ static
Initial value:
=
        std::numeric_limits<uint64_t>::max()
sentinel to disable size limit
Definition at line 79 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
size_limit
Definition at line 226 of file read_binary.hpp.
size_t stats_total_bytes = 0
Definition at line 270 of file read_binary.hpp.
size_t stats_total_reads = 0
Definition at line 271 of file read_binary.hpp.
bool use_ext_file_ = false
File containing Blocks mapped directly to a io fileimpl.
Definition at line 267 of file read_binary.hpp.
Referenced by ReadBinaryNode< ValueType >::ReadBinaryNode().
The documentation for this class was generated from the following file:
thrill/api/read_binary.hpp