Thrill: MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable > Class Template Reference
MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable > Class Template Reference
Detailed Description
template<typename ValueType, typename ReaderIterator, typename Comparator, bool Stable = false>
class thrill::core::MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >
Definition at line 30 of file multiway_merge.hpp.
#include <multiway_merge.hpp>
Public Types
using LoserTreeType = tlx::LoserTree< Stable, ValueType, Comparator >
using Reader = typename std::iterator_traits< ReaderIterator >::value_type
Public Member Functions
MultiwayMergeTree (ReaderIterator readers_begin, ReaderIterator readers_end, const Comparator &comp)
bool HasNext () const
ValueType Next ()
std::pair< ValueType, unsigned > NextWithSource ()
Private Attributes
std::vector< std::pair< bool, ValueType > > current_
current values in each input (exist flag, value)
LoserTreeType lt_
unsigned num_inputs_
ReaderIterator readers_
size_t remaining_inputs_
Member Typedef Documentation
LoserTreeType
using LoserTreeType = tlx::LoserTree<Stable, ValueType, Comparator>
Definition at line 35 of file multiway_merge.hpp.
Reader
using Reader = typename std::iterator_traits<ReaderIterator>::value_type
Definition at line 33 of file multiway_merge.hpp.
Constructor & Destructor Documentation
MultiwayMergeTree()
MultiwayMergeTree (ReaderIterator readers_begin, ReaderIterator readers_end, const Comparator & comp) inline
Definition at line 37 of file multiway_merge.hpp.
References MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::current_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::HasNext(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::lt_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::num_inputs_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::readers_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::remaining_inputs_, and TLX_LIKELY.
Member Function Documentation
HasNext()
bool HasNext () const inline
Definition at line 63 of file multiway_merge.hpp.
References MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::remaining_inputs_.
Referenced by GroupByMultiwayMergeIterator< ValueType, KeyExtractor, Comparator >::GetNextElem(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::Next(), and MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::NextWithSource().
Next()
ValueType Next () inline
Definition at line 87 of file multiway_merge.hpp.
References MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::current_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::HasNext(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::lt_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::readers_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::remaining_inputs_, and TLX_LIKELY.
Referenced by GroupByMultiwayMergeIterator< ValueType, KeyExtractor, Comparator >::GetNextElem().
NextWithSource()
std::pair<ValueType, unsigned> NextWithSource () inline
Definition at line 67 of file multiway_merge.hpp.
References MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::current_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::HasNext(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::lt_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::readers_, MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::remaining_inputs_, and TLX_LIKELY.
Member Data Documentation
current_
std::vector<std::pair<bool, ValueType> > current_ private
current values in each input (exist flag, value)
Definition at line 115 of file multiway_merge.hpp.
Referenced by MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::Next(), and MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::NextWithSource().
lt_
LoserTreeType lt_ private
Definition at line 113 of file multiway_merge.hpp.
Referenced by MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::Next(), and MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::NextWithSource().
num_inputs_
unsigned num_inputs_ private
Definition at line 110 of file multiway_merge.hpp.
Referenced by MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree().
readers_
ReaderIterator readers_ private
Definition at line 109 of file multiway_merge.hpp.
Referenced by MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::Next(), and MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::NextWithSource().
remaining_inputs_
size_t remaining_inputs_ private
Definition at line 111 of file multiway_merge.hpp.
Referenced by MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::HasNext(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::MultiwayMergeTree(), MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::Next(), and MultiwayMergeTree< ValueType, ReaderIterator, Comparator, Stable >::NextWithSource().
The documentation for this class was generated from the following file:
thrill/core/multiway_merge.hpp