Thrill: numeric_limits< thrill::common::UIntPair< HighType > > Class Template Reference
numeric_limits< thrill::common::UIntPair< HighType > > Class Template Reference
Detailed Description
template<typename HighType>
class std::numeric_limits< thrill::common::UIntPair< HighType > >
template class providing some numeric_limits fields for UIntPair types.
Definition at line 277 of file uint_types.hpp.
#include <uint_types.hpp>
Public Types
using UIntPair = thrill::common::UIntPair< HighType >
Static Public Member Functions
static const UIntPair epsilon ()
epsilon is zero
static UIntPair lowest ()
return an UIntPair instance containing the smallest value possible
static UIntPair max ()
return an UIntPair instance containing the largest value possible
static UIntPair min ()
return an UIntPair instance containing the smallest value possible
static const UIntPair round_error ()
rounding error is zero
Static Public Attributes
static const int digits = UIntPair::digits
number of binary digits (bits) in UIntPair
static const bool has_infinity = false
no infinity
static const bool is_exact = true
unit_pair types contain exact integers
static const bool is_integer = true
UIntPair types are integers.
static const bool is_signed = false
unit_pair types are unsigned
static const bool is_specialized = true
yes we have information about UIntPair
static const int max_exponent = 0
no exponent
static const int max_exponent10 = 0
no exponent
static const int min_exponent = 0
no exponent
static const int min_exponent10 = 0
no exponent
static const int radix = 2
unit_pair radix is binary
Member Typedef Documentation
using UIntPair = thrill::common::UIntPair<HighType>
Definition at line 280 of file uint_types.hpp.
Member Function Documentation
static const UIntPair epsilon () inline static
epsilon is zero
Definition at line 313 of file uint_types.hpp.
static UIntPair lowest () inline static
return an UIntPair instance containing the smallest value possible
Definition at line 294 of file uint_types.hpp.
References min().
static UIntPair max () inline static
return an UIntPair instance containing the largest value possible
Definition at line 290 of file uint_types.hpp.
References max().
static UIntPair min () inline static
return an UIntPair instance containing the smallest value possible
Definition at line 286 of file uint_types.hpp.
References min().
static const UIntPair round_error () inline static
rounding error is zero
Definition at line 317 of file uint_types.hpp.
Member Data Documentation
const int digits = UIntPair::digits static
number of binary digits (bits) in UIntPair
Definition at line 310 of file uint_types.hpp.
const bool has_infinity = false static
no infinity
Definition at line 333 of file uint_types.hpp.
const bool is_exact = true static
unit_pair types contain exact integers
Definition at line 304 of file uint_types.hpp.
const bool is_integer = true static
UIntPair types are integers.
Definition at line 301 of file uint_types.hpp.
const bool is_signed = false static
unit_pair types are unsigned
Definition at line 298 of file uint_types.hpp.
const bool is_specialized = true static
yes we have information about UIntPair
Definition at line 283 of file uint_types.hpp.
const int max_exponent = 0 static
no exponent
Definition at line 327 of file uint_types.hpp.
const int max_exponent10 = 0 static
no exponent
Definition at line 330 of file uint_types.hpp.
const int min_exponent = 0 static
no exponent
Definition at line 321 of file uint_types.hpp.
const int min_exponent10 = 0 static
no exponent
Definition at line 324 of file uint_types.hpp.
const int radix = 2 static
unit_pair radix is binary
Definition at line 307 of file uint_types.hpp.
The documentation for this class was generated from the following file:
thrill/common/uint_types.hpp