Thrill: Allocator< Type > Class Template Reference
Allocator< Type > Class Template Reference
Detailed Description
template<typename Type>
class thrill::mem::Allocator< Type >
Definition at line 31 of file allocator.hpp.
#include <allocator.hpp>
Classes
struct rebind
Return allocator for different type.
Public Types
using const_pointer = const Type *
using const_reference = const Type &
using difference_type = std::ptrdiff_t
using is_always_equal = std::false_type
C++11 type flag.
using pointer = Type *
using reference = Type &
using size_type = std::size_t
using value_type = Type
Public Types inherited from AllocatorBase< Type >
using const_pointer = const Type *
using const_reference = const Type &
using difference_type = std::ptrdiff_t
using is_always_equal = std::true_type
C++11 type flag.
using pointer = Type *
using propagate_on_container_move_assignment = std::true_type
C++11 type flag.
using reference = Type &
using size_type = std::size_t
using value_type = Type
Public Member Functions
Allocator (Manager &manager) noexcept
Construct Allocator with Manager object.
Allocator (const Allocator &) noexcept=default
copy-constructor
template<typename OtherType >
Allocator (const Allocator< OtherType > &other) noexcept
copy-constructor from a rebound allocator
pointer allocate (size_type n, const void *=nullptr)
void deallocate (pointer p, size_type n) const noexcept
template<typename Other >
bool operator!= (const Allocator< Other > &other) const noexcept
Compare to another allocator of same type.
Allocator & operator= (const Allocator &) noexcept=default
copy-assignment operator
template<typename Other >
bool operator== (const Allocator< Other > &other) const noexcept
Compare to another allocator of same type.
Public Member Functions inherited from AllocatorBase< Type >
pointer address (reference x) const noexcept
Returns the address of x.
const_pointer address (const_reference x) const noexcept
Returns the address of x.
void construct (pointer p, const_reference value)
Constructs an element object on the location pointed by p.
template<typename SubType , typename... Args>
void construct (SubType *p, Args &&... args)
Constructs an element object on the location pointed by p.
void destroy (pointer p) const noexcept
Destroys in-place the object pointed by p.
template<typename SubType >
void destroy (SubType *p) const noexcept
Destroys in-place the object pointed by p.
size_type max_size () const noexcept
Maximum size possible to allocate.
Public Attributes
Manager * manager_
Static Private Attributes
static constexpr bool debug = false
Member Typedef Documentation
const_pointer
using const_pointer = const Type *
Definition at line 38 of file allocator.hpp.
const_reference
using const_reference = const Type&
Definition at line 40 of file allocator.hpp.
difference_type
using difference_type = std::ptrdiff_t
Definition at line 42 of file allocator.hpp.
is_always_equal
using is_always_equal = std::false_type
C++11 type flag.
Definition at line 45 of file allocator.hpp.
pointer
using pointer = Type *
Definition at line 37 of file allocator.hpp.
reference
using reference = Type&
Definition at line 39 of file allocator.hpp.
size_type
using size_type = std::size_t
Definition at line 41 of file allocator.hpp.
value_type
using value_type = Type
Definition at line 36 of file allocator.hpp.
Constructor & Destructor Documentation
Allocator() [1/3]
Allocator (Manager & manager) inline explicit noexcept
Construct Allocator with Manager object.
Definition at line 52 of file allocator.hpp.
Referenced by Allocator< char >::Allocator(), and Allocator< void >::Allocator().
Allocator() [2/3]
Allocator (const Allocator< Type > &) default noexcept
copy-constructor
Allocator() [3/3]
Allocator (const Allocator< OtherType > & other) inline noexcept
copy-constructor from a rebound allocator
Definition at line 60 of file allocator.hpp.
Member Function Documentation
allocate()
pointer allocate (size_type n, const void * = nullptr) inline
Attempts to allocate a block of storage with a size large enough to contain n elements of member type value_type, and returns a pointer to the first element.
Definition at line 69 of file allocator.hpp.
Referenced by thrill::mem::mm_new().
deallocate()
void deallocate (pointer p, size_type n) const inline noexcept
Releases a block of storage previously allocated with member allocate and not yet released.
Definition at line 97 of file allocator.hpp.
Referenced by thrill::mem::mm_delete().
operator!=()
bool operator!= (const Allocator< Other > & other) const inline noexcept
Compare to another allocator of same type.
Definition at line 121 of file allocator.hpp.
operator=()
Allocator& operator= (const Allocator< Type > &) default noexcept
copy-assignment operator
Referenced by Allocator< char >::Allocator().
operator==()
bool operator== (const Allocator< Other > & other) const inline noexcept
Compare to another allocator of same type.
Definition at line 115 of file allocator.hpp.
Member Data Documentation
debug
constexpr bool debug = false static private
Definition at line 33 of file allocator.hpp.
manager_
Manager* manager_
pointer to common Manager object. If we use a reference here, then the allocator cannot be default move/assigned anymore.
Definition at line 111 of file allocator.hpp.
Referenced by Allocator< char >::allocate(), and Allocator< char >::deallocate().
The documentation for this class was generated from the following file:
thrill/mem/allocator.hpp