Thrill: singleton< InstanceType, destroy_on_exit > Class Template Reference
singleton< InstanceType, destroy_on_exit > Class Template Reference
Detailed Description
template<typename InstanceType, bool destroy_on_exit = true>
class foxxll::singleton< InstanceType, destroy_on_exit >
Definition at line 25 of file singleton.hpp.
#include <singleton.hpp>
Public Types
using instance_pointer = instance_type *
using instance_type = InstanceType
using volatile_instance_pointer = volatile instance_pointer
Public Member Functions
singleton ()=default
singleton (const singleton &)=delete
non-copyable: delete copy-constructor
singleton & operator= (const singleton &)=delete
non-copyable: delete assignment operator
Static Public Member Functions
template<typename SubInstanceType >
static instance_pointer create_instance ()
create instance of SubInstanceType and move into singleton
static void destroy_instance ()
destroy singleton and mark as invalid
static instance_pointer get_instance ()
return instance or create base instance if empty
static instance_type & get_ref ()
Static Private Attributes
static volatile_instance_pointer instance_ = nullptr
singleton object instance
static std::mutex singleton_mutex_
mutex to protect instance_
Member Typedef Documentation
instance_pointer
using instance_pointer = instance_type *
Definition at line 29 of file singleton.hpp.
instance_type
using instance_type = InstanceType
Definition at line 28 of file singleton.hpp.
volatile_instance_pointer
using volatile_instance_pointer = volatile instance_pointer
Definition at line 30 of file singleton.hpp.
Constructor & Destructor Documentation
singleton() [1/2]
singleton () default
singleton() [2/2]
singleton (const singleton< InstanceType, destroy_on_exit > &) delete
non-copyable: delete copy-constructor
Member Function Documentation
create_instance()
singleton< InstanceType, destroy_on_exit >::instance_pointer create_instance () static
create instance of SubInstanceType and move into singleton
Definition at line 75 of file singleton.hpp.
Referenced by singleton< disk_queues >::get_ref().
destroy_instance()
void destroy_instance () static
destroy singleton and mark as invalid
Definition at line 87 of file singleton.hpp.
Referenced by singleton< disk_queues >::create_instance(), and singleton< disk_queues >::get_ref().
get_instance()
static instance_pointer get_instance () inline static
return instance or create base instance if empty
Definition at line 41 of file singleton.hpp.
get_ref()
static instance_type& get_ref () inline static
Definition at line 49 of file singleton.hpp.
operator=()
singleton& operator= (const singleton< InstanceType, destroy_on_exit > &) delete
non-copyable: delete assignment operator
Member Data Documentation
instance_
singleton< InstanceType, destroy_on_exit >::volatile_instance_pointer instance_ = nullptr static private
singleton object instance
Definition at line 66 of file singleton.hpp.
Referenced by singleton< disk_queues >::create_instance(), singleton< disk_queues >::destroy_instance(), singleton< disk_queues >::get_instance(), and singleton< disk_queues >::get_ref().
singleton_mutex_
std::mutex singleton_mutex_ static private
mutex to protect instance_
Definition at line 69 of file singleton.hpp.
Referenced by singleton< disk_queues >::create_instance(), and singleton< disk_queues >::destroy_instance().
The documentation for this class was generated from the following file:
extlib/foxxll/foxxll/singleton.hpp