Thrill: Dispatcher Class Reference
Dispatcher Class Reference final
Mock Network API
Detailed Description
A virtual Dispatcher which waits for messages to arrive in the mock network.
It is implemented as a ConcurrentBoundedQueue, into which Connections lay notification events.
Definition at line 171 of file group.hpp.
#include <group.hpp>
Public Types
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Public Member Functions
Dispatcher ()
~Dispatcher ()
virtual destructor
Implementation of Virtual Methods
void AddRead (net::Connection &_c, const Callback &read_cb) final
Register a buffered read callback and a default exception callback.
void AddWrite (net::Connection &_c, const Callback &write_cb) final
Register a buffered write callback and a default exception callback.
void Cancel (net::Connection &) final
Cancel all callbacks on a given connection.
void Notify (Connection *c)
void Interrupt () final
Interrupt current dispatch.
void DispatchOne (const std::chrono::milliseconds &timeout) final
Public Member Functions inherited from Dispatcher
Dispatcher ()=default
default constructor
Dispatcher (const Dispatcher &)=delete
non-copyable: delete copy-constructor
Dispatcher & operator= (const Dispatcher &)=delete
non-copyable: delete assignment operator
void AddTimer (const std::chrono::milliseconds &timeout, const TimerCallback &cb)
Register a relative timeout callback.
virtual void AsyncRead (Connection &c, uint32_t, size_t size, const AsyncReadBufferCallback &done_cb)
asynchronously read n bytes and deliver them to the callback
virtual void AsyncRead (Connection &c, uint32_t, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &done_cb)
asynchronously read the full ByteBlock and deliver it to the callback
virtual void AsyncWrite (Connection &c, uint32_t, Buffer &&buffer, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
virtual void AsyncWrite (Connection &c, uint32_t, data::PinnedBlock &&block, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, uint32_t seq, const void *buffer, size_t size, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, uint32_t seq, const std::string &str, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void Dispatch ()
Dispatch one or more events.
void Loop ()
Loop over Dispatch() until terminate_ flag is set.
void Terminate ()
bool HasAsyncWrites () const
Check whether there are still AsyncWrite()s in the queue.
Private Member Functions
Watch & GetWatch (Connection *c)
lookup method
Private Attributes
std::unique_ptr< Data > d_
pimpl data struct with complex components
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Protected Types inherited from Dispatcher
using TimerPQ = std::priority_queue< Timer, std::vector< Timer, mem::GPoolAllocator< Timer > > >
priority queue of timer callbacks
Static Protected Member Functions inherited from Dispatcher
static bool ExceptionCallback (Connection &c)
Default exception handler.
Protected Attributes inherited from Dispatcher
std::deque< AsyncReadBuffer,
mem::GPoolAllocator
< AsyncReadBuffer > > async_read_
deque of asynchronous readers
std::deque< AsyncReadByteBlock,
mem::GPoolAllocator
< AsyncReadByteBlock > > async_read_block_
deque of asynchronous readers
std::deque< AsyncWriteBuffer,
mem::GPoolAllocator
< AsyncWriteBuffer > > async_write_
deque of asynchronous writers
std::deque< AsyncWriteBlock,
mem::GPoolAllocator
< AsyncWriteBlock > > async_write_block_
deque of asynchronous writers
std::atomic< bool > terminate_ { false }
true if dispatcher needs to stop
TimerPQ timer_pq_
Member Typedef Documentation
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Definition at line 177 of file group.hpp.
Constructor & Destructor Documentation
Dispatcher ()
Definition at line 227 of file group.cpp.
~Dispatcher () virtual
virtual destructor
Reimplemented from Dispatcher.
Definition at line 232 of file group.cpp.
Member Function Documentation
void AddRead (net::Connection & _c, const Callback & read_cb) final virtual
Register a buffered read callback and a default exception callback.
Implements Dispatcher.
Definition at line 236 of file group.cpp.
References Connection::d_, Dispatcher::d_, Dispatcher::GetWatch(), and Dispatcher::Notify().
void AddWrite (net::Connection & c, const Callback & write_cb) final virtual
Register a buffered write callback and a default exception callback.
Implements Dispatcher.
Definition at line 253 of file group.cpp.
References Connection::d_, Dispatcher::d_, Dispatcher::GetWatch(), and Dispatcher::Notify().
void Cancel (net::Connection & c) final virtual
Cancel all callbacks on a given connection.
Implements Dispatcher.
Definition at line 269 of file group.cpp.
void DispatchOne (const std::chrono::milliseconds & timeout) final virtual
Implements Dispatcher.
Definition at line 288 of file group.cpp.
References Connection::d_, Dispatcher::d_, LOG1, and sLOG.
Dispatcher::Watch & GetWatch (Connection * c) private
lookup method
Definition at line 281 of file group.cpp.
References Dispatcher::d_.
Referenced by Dispatcher::AddRead(), and Dispatcher::AddWrite().
void Interrupt () final virtual
Interrupt current dispatch.
Implements Dispatcher.
Definition at line 277 of file group.cpp.
References Dispatcher::Notify().
void Notify (Connection * c)
Definition at line 273 of file group.cpp.
References Dispatcher::d_.
Referenced by Dispatcher::AddRead(), Dispatcher::AddWrite(), Connection::InboundMsg(), and Dispatcher::Interrupt().
Member Data Documentation
std::unique_ptr<Data> d_ private
pimpl data struct with complex components
Definition at line 201 of file group.hpp.
Referenced by Dispatcher::AddRead(), Dispatcher::AddWrite(), Dispatcher::DispatchOne(), Dispatcher::GetWatch(), and Dispatcher::Notify().
constexpr bool debug = false static private
Definition at line 173 of file group.hpp.
The documentation for this class was generated from the following files:
thrill/net/mock/group.hpp
thrill/net/mock/group.cpp