Thrill: stats_data Class Reference
stats_data Class Reference
I/O Primitives Layer
Detailed Description
Definition at line 486 of file iostats.hpp.
#include <iostats.hpp>
Classes
struct summary
Public Member Functions
stats_data ()
stats_data (const stats &s)
double get_elapsed_time () const
double get_io_wait_time () const
stats_data::summary< double > get_pio_speed_summary () const
double get_pio_time () const
stats_data::summary< double > get_pread_speed_summary () const
double get_pread_time () const
stats_data::summary< double > get_pwrite_speed_summary () const
double get_pwrite_time () const
external_size_type get_read_bytes () const
stats_data::summary
< external_size_type > get_read_bytes_summary () const
unsigned get_read_count () const
stats_data::summary< unsigned > get_read_count_summary () const
stats_data::summary< double > get_read_speed_summary () const
double get_read_time () const
stats_data::summary< double > get_read_time_summary () const
double get_wait_read_time () const
double get_wait_write_time () const
external_size_type get_write_bytes () const
stats_data::summary
< external_size_type > get_write_bytes_summary () const
unsigned get_write_count () const
stats_data::summary< unsigned > get_write_count_summary () const
stats_data::summary< double > get_write_speed_summary () const
double get_write_time () const
stats_data::summary< double > get_write_time_summary () const
size_t num_files () const
Returns the number of file_stats_data objects.
stats_data operator+ (const stats_data &a) const
stats_data operator- (const stats_data &a) const
void to_ostream (std::ostream &o, const std::string line_prefix="") const
Private Member Functions
template<typename T , typename Functor >
T fetch_sum (const Functor &get_value) const
aggregator
Private Attributes
double elapsed_
std::vector< file_stats_data > file_stats_data_list_
list of individual file statistics.
double p_ios_
double p_reads_
seconds spent in parallel io
double p_writes_
double t_wait
seconds spent waiting for completion of I/O operations
double t_wait_read_
double t_wait_write_
Friends
std::ostream & operator<< (std::ostream &o, const stats_data &s)
Constructor & Destructor Documentation
stats_data () inline
Definition at line 518 of file iostats.hpp.
stats_data (const stats & s) inline
Definition at line 526 of file iostats.hpp.
Member Function Documentation
T fetch_sum (const Functor & get_value) const private
aggregator
Definition at line 385 of file iostats.cpp.
References stats_data::file_stats_data_list_, and gen_data::x.
double get_elapsed_time () const inline
Retruns elapsed_ time
Remarks
If stats_data is not the difference between two other stats_data objects, then this value is measures the time since the first file object was initialized.
Returns
elapsed_ time
Definition at line 620 of file iostats.hpp.
References stats_data::elapsed_.
Referenced by stats_data::to_ostream().
double get_io_wait_time () const
I/O wait time counter.
Returns
number of seconds spent in I/O waiting functions
Definition at line 649 of file iostats.cpp.
References stats_data::t_wait.
Referenced by stats_data::to_ostream().
stats_data::summary< double > get_pio_speed_summary () const
Definition at line 640 of file iostats.cpp.
References stats_data::file_stats_data_list_, and stats_data::p_ios_.
Referenced by stats_data::to_ostream().
double get_pio_time () const
Period of time when at least one I/O thread was executing a read or a write.
Returns
seconds spent in I/O
Definition at line 599 of file iostats.cpp.
References stats_data::p_ios_.
Referenced by stats_data::to_ostream().
stats_data::summary< double > get_pread_speed_summary () const
Definition at line 613 of file iostats.cpp.
References stats_data::file_stats_data_list_, and stats_data::p_reads_.
Referenced by stats_data::to_ostream().
double get_pread_time () const
Period of time when at least one I/O thread was executing a read.
Returns
seconds spent in reading
Definition at line 589 of file iostats.cpp.
References stats_data::p_reads_.
Referenced by stats_data::to_ostream().
stats_data::summary< double > get_pwrite_speed_summary () const
Definition at line 631 of file iostats.cpp.
References stats_data::file_stats_data_list_, and stats_data::p_writes_.
Referenced by stats_data::to_ostream().
double get_pwrite_time () const
Period of time when at least one I/O thread was executing a write.
Returns
seconds spent in writing
Definition at line 594 of file iostats.cpp.
References stats_data::p_writes_.
Referenced by stats_data::to_ostream().
external_size_type get_read_bytes () const
Returns number of bytes read from disks in total.
Returns
number of bytes read
Definition at line 527 of file iostats.cpp.
Referenced by Context::Launch(), BlockPool::RunTask(), and stats_data::to_ostream().
stats_data::summary< external_size_type > get_read_bytes_summary () const
Returns sum, min, max, avarage and median of all read bytes.
Returns
a summary of the write measurements
Definition at line 534 of file iostats.cpp.
References stats_data::file_stats_data_list_.
Referenced by stats_data::to_ostream().
unsigned get_read_count () const
Returns the sum of all read_count_.
Returns
the sum of all read_count_
Definition at line 497 of file iostats.cpp.
Referenced by BlockPool::RunTask(), and stats_data::to_ostream().
stats_data::summary< unsigned > get_read_count_summary () const
Retruns sum, min, max, avarage and median of all read_count_.
Returns
a summary of the read measurements
Definition at line 503 of file iostats.cpp.
References stats_data::file_stats_data_list_.
stats_data::summary< double > get_read_speed_summary () const
Definition at line 604 of file iostats.cpp.
References stats_data::file_stats_data_list_.
Referenced by stats_data::to_ostream().
double get_read_time () const
Time that would be spent in read syscalls if all parallel read_count_ were serialized.
Returns
seconds spent in reading
Definition at line 559 of file iostats.cpp.
Referenced by stats_data::to_ostream().
stats_data::summary< double > get_read_time_summary () const
Returns sum, min, max, avarage and median of all read times
Returns
a summary of the read times
Definition at line 565 of file iostats.cpp.
References stats_data::file_stats_data_list_.
double get_wait_read_time () const
Definition at line 654 of file iostats.cpp.
References stats_data::t_wait_read_.
Referenced by stats_data::to_ostream().
double get_wait_write_time () const
Definition at line 659 of file iostats.cpp.
References stats_data::t_wait_write_.
Referenced by stats_data::to_ostream().
external_size_type get_write_bytes () const
Returns number of bytes written to the disks in total.
Returns
number of bytes written
Definition at line 543 of file iostats.cpp.
Referenced by Context::Launch(), BlockPool::RunTask(), and stats_data::to_ostream().
stats_data::summary< external_size_type > get_write_bytes_summary () const
Returns sum, min, max, avarage and median of all written bytes.
Returns
a summary of the written bytes
Definition at line 550 of file iostats.cpp.
References stats_data::file_stats_data_list_.
Referenced by stats_data::to_ostream().
unsigned get_write_count () const
Returns the sum of all write_count_.
Returns
the sum of all write_count_
Definition at line 512 of file iostats.cpp.
Referenced by BlockPool::RunTask(), and stats_data::to_ostream().
stats_data::summary< unsigned > get_write_count_summary () const
Returns sum, min, max, avarage and median of all write_count_.
Returns
a summary of the write measurements
Definition at line 518 of file iostats.cpp.
References stats_data::file_stats_data_list_.
stats_data::summary< double > get_write_speed_summary () const
Definition at line 622 of file iostats.cpp.
References stats_data::file_stats_data_list_.
Referenced by stats_data::to_ostream().
double get_write_time () const
Time that would be spent in write syscalls if all parallel write_count_ were serialized.
Returns
the sum of the write times of all files
Definition at line 574 of file iostats.cpp.
Referenced by stats_data::to_ostream().
stats_data::summary< double > get_write_time_summary () const
Returns sum, min, max, avarage and median of all write times
Returns
a summary of the write times
Definition at line 580 of file iostats.cpp.
References stats_data::file_stats_data_list_.
size_t num_files () const
Returns the number of file_stats_data objects.
Definition at line 492 of file iostats.cpp.
References stats_data::file_stats_data_list_.
Referenced by stats_data::to_ostream().
stats_data operator+ (const stats_data & a) const
Definition at line 444 of file iostats.cpp.
References stats_data::elapsed_, stats_data::file_stats_data_list_, tlx::merge_combine(), stats_data::p_ios_, stats_data::p_reads_, stats_data::p_writes_, stats_data::t_wait, stats_data::t_wait_read_, and stats_data::t_wait_write_.
stats_data operator- (const stats_data & a) const
Definition at line 468 of file iostats.cpp.
References stats_data::elapsed_, stats_data::file_stats_data_list_, tlx::merge_combine(), stats_data::p_ios_, stats_data::p_reads_, stats_data::p_writes_, stats_data::t_wait, stats_data::t_wait_read_, and stats_data::t_wait_write_.
void to_ostream (std::ostream & o, const std::string line_prefix = "") const
Definition at line 664 of file iostats.cpp.
References foxxll::add_IEC_binary_multiplier(), stats_data::get_elapsed_time(), stats_data::get_io_wait_time(), stats_data::get_pio_speed_summary(), stats_data::get_pio_time(), stats_data::get_pread_speed_summary(), stats_data::get_pread_time(), stats_data::get_pwrite_speed_summary(), stats_data::get_pwrite_time(), stats_data::get_read_bytes(), stats_data::get_read_bytes_summary(), stats_data::get_read_count(), stats_data::get_read_speed_summary(), stats_data::get_read_time(), stats_data::get_wait_read_time(), stats_data::get_wait_write_time(), stats_data::get_write_bytes(), stats_data::get_write_bytes_summary(), stats_data::get_write_count(), stats_data::get_write_speed_summary(), stats_data::get_write_time(), and stats_data::num_files().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const stats_data & s) friend
Definition at line 635 of file iostats.hpp.
Member Data Documentation
double elapsed_ private
Definition at line 495 of file iostats.hpp.
Referenced by stats_data::get_elapsed_time(), stats_data::operator+(), and stats_data::operator-().
std::vector<file_stats_data> file_stats_data_list_ private
list of individual file statistics.
Definition at line 498 of file iostats.hpp.
Referenced by stats_data::fetch_sum(), stats_data::get_pio_speed_summary(), stats_data::get_pread_speed_summary(), stats_data::get_pwrite_speed_summary(), stats_data::get_read_bytes_summary(), stats_data::get_read_count_summary(), stats_data::get_read_speed_summary(), stats_data::get_read_time_summary(), stats_data::get_write_bytes_summary(), stats_data::get_write_count_summary(), stats_data::get_write_speed_summary(), stats_data::get_write_time_summary(), stats_data::num_files(), stats_data::operator+(), and stats_data::operator-().
double p_ios_ private
Definition at line 489 of file iostats.hpp.
Referenced by stats_data::get_pio_speed_summary(), stats_data::get_pio_time(), stats_data::operator+(), and stats_data::operator-().
double p_reads_ private
seconds spent in parallel io
Definition at line 489 of file iostats.hpp.
Referenced by stats_data::get_pread_speed_summary(), stats_data::get_pread_time(), stats_data::operator+(), and stats_data::operator-().
double p_writes_ private
Definition at line 489 of file iostats.hpp.
Referenced by stats_data::get_pwrite_speed_summary(), stats_data::get_pwrite_time(), stats_data::operator+(), and stats_data::operator-().
double t_wait private
seconds spent waiting for completion of I/O operations
Definition at line 492 of file iostats.hpp.
Referenced by stats_data::get_io_wait_time(), stats_data::operator+(), and stats_data::operator-().
double t_wait_read_ private
Definition at line 493 of file iostats.hpp.
Referenced by stats_data::get_wait_read_time(), stats_data::operator+(), and stats_data::operator-().
double t_wait_write_ private
Definition at line 493 of file iostats.hpp.
Referenced by stats_data::get_wait_write_time(), stats_data::operator+(), and stats_data::operator-().
The documentation for this class was generated from the following files:
extlib/foxxll/foxxll/io/iostats.hpp
extlib/foxxll/foxxll/io/iostats.cpp