Thrill: MixStream Exception Reference
MixStream Exception Reference final
Data Subsystem Layer
Detailed Description
A Stream is a virtual set of connections to all other worker instances, hence a "Stream" bundles them to a logical communication context.
We call an individual connection from a worker to another worker a "Host".
To use a Stream, one can get a vector of BlockWriter via OpenWriters() of outbound Stream. The vector is of size of workers in the system. One can then write items destined to the corresponding worker. The written items are buffered into a Block and only sent when the Block is full. To force a send, use BlockWriter::Flush(). When all items are sent, the BlockWriters must be closed using BlockWriter::Close().
The MixStream allows reading of items from all workers in an unordered sequence, without waiting for any of the workers to complete sending items.
Definition at line 44 of file mix_stream.hpp.
#include <mix_stream.hpp>
Public Types
using MixReader = MixBlockQueueReader
Public Types inherited from Stream
using Writer = DynBlockWriter
Public Member Functions
MixStream (Multiplexer &multiplexer, const StreamId &id, size_t local_worker_id, size_t dia_id)
Creates a new stream instance.
MixStream (const MixStream &)=delete
non-copyable: delete copy-constructor
MixStream (MixStream &&)=default
move-constructor: default
~MixStream () final
void Close () final
shuts the stream down.
bool closed () const final
MixReader GetMixReader (bool consume)
Creates a BlockReader which mixes items from all workers.
MixReader GetReader (bool consume)
Open a MixReader (function name matches a method in File and CatStream).
std::vector< Writer > GetWriters () final
MixStream & operator= (const MixStream &)=delete
non-copyable: delete assignment operator
void set_dia_id (size_t dia_id)
Public Member Functions inherited from Stream
Stream (Multiplexer &multiplexer, const StreamId &id, size_t local_worker_id, size_t dia_id)
virtual ~Stream ()
const StreamId & id () const
size_t my_host_rank () const
Returns my_host_rank.
size_t my_worker_rank () const
Returns my_worker_rank_.
size_t num_hosts () const
Number of hosts in system.
size_t num_workers () const
Number of workers in system.
void OnAllClosed (const char *stream_type)
template<typename ItemType >
void Scatter (File &source, const std::vector< size_t > &offsets, bool consume=false)
Scatters a File to many worker: elements from [offset[0],offset[1]) are sent to the first worker, elements from [offset[1], offset[2]) are sent to the second worker, ..., elements from [offset[my_rank - 1],offset[my_rank]) are copied locally, ..., elements from [offset[num_workers - 1], offset[num_workers]) are sent to the last worker.
size_t workers_per_host () const
Returns workers_per_host.
Public Member Functions inherited from ReferenceCount
ReferenceCount () noexcept
new objects have zero reference count
ReferenceCount (const ReferenceCount &) noexcept
coping still creates a new object with zero reference count
~ReferenceCount ()
bool DecReference () const noexcept
Call whenever resetting (i.e.
void IncReference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCount & operator= (const ReferenceCount &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCount is referenced by only one CountingPtr.
Private Member Functions
MixBlockQueueSink * loopback_queue (size_t from_worker_id)
Returns the loopback queue for the worker of this stream.
void OnCloseStream (size_t from)
void OnStreamBlock (size_t from, PinnedBlock &&b)
called from Multiplexer when there is a new Block for this Stream.
Private Attributes
bool is_closed_ = false
flag if Close() was completed
std::vector< MixBlockQueueSink > loopback_
MixBlockQueue queue_
BlockQueue to store incoming Blocks with source.
std::vector< StreamSink > sinks_
StreamSink objects are receivers of Blocks outbound for other worker.
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Public Attributes inherited from Stream
std::atomic< size_t > rx_int_blocks_ { 0 }
std::atomic< size_t > rx_int_bytes_ { 0 }
std::atomic< size_t > rx_int_items_ { 0 }
common::StatsTimerStart rx_lifetime_
size_t rx_net_blocks_ = 0
size_t rx_net_bytes_ = 0
size_t rx_net_items_ = 0
common::StatsTimerStopped rx_timespan_
std::atomic< size_t > tx_int_blocks_ { 0 }
std::atomic< size_t > tx_int_bytes_ { 0 }
std::atomic< size_t > tx_int_items_ { 0 }
common::StatsTimerStart tx_lifetime_
Timers from creation of stream until rx / tx direction is closed.
std::atomic< size_t > tx_net_blocks_ { 0 }
std::atomic< size_t > tx_net_bytes_ { 0 }
std::atomic< size_t > tx_net_items_ { 0 }
common::StatsTimerStopped tx_timespan_
Timers from first rx / tx package until rx / tx direction is closed.
Protected Attributes inherited from Stream
size_t dia_id_
Associated DIANode id.
StreamId id_
our own stream id.
size_t local_worker_id_
Multiplexer & multiplexer_
reference to multiplexer
size_t remaining_closing_blocks_
common::Semaphore sem_closing_blocks_
number of received stream closing Blocks.
Member Typedef Documentation
using MixReader = MixBlockQueueReader
Definition at line 49 of file mix_stream.hpp.
Constructor & Destructor Documentation
MixStream (Multiplexer & multiplexer, const StreamId & id, size_t local_worker_id, size_t dia_id)
Creates a new stream instance.
Definition at line 24 of file mix_stream.cpp.
References Multiplexer::block_pool_, Group::connection(), Multiplexer::group_, Stream::id(), MixStream::loopback_, thrill::data::MixStreamBlock, Stream::multiplexer_, Stream::my_host_rank(), Stream::num_hosts(), Stream::num_workers(), MixStream::sinks_, Stream::workers_per_host(), and Multiplexer::workers_per_host().
MixStream (const MixStream &) delete
non-copyable: delete copy-constructor
MixStream (MixStream &&) default
move-constructor: default
~MixStream () final
Definition at line 63 of file mix_stream.cpp.
References MixStream::Close().
Member Function Documentation
void Close () final virtual
shuts the stream down.
Implements Stream.
Definition at line 128 of file mix_stream.cpp.
References Multiplexer::active_streams_, MixBlockQueueSink::Close(), MixStream::closed(), Stream::id_, MixStream::is_closed_, Stream::local_worker_id_, LOG, Multiplexer::MixLoopback(), Stream::multiplexer_, Stream::num_hosts(), Stream::OnAllClosed(), Stream::sem_closing_blocks_, MixStream::sinks_, Stream::tx_lifetime_, Stream::tx_timespan_, Semaphore::wait(), Stream::workers_per_host(), and Multiplexer::workers_per_host().
Referenced by MixStream::~MixStream().
bool closed () const final virtual
Indicates if the stream is closed - meaning all remaining outbound queues have been closed.
Implements Stream.
Definition at line 167 of file mix_stream.cpp.
References MixStream::is_closed_, MixStream::queue_, and MixBlockQueue::write_closed().
Referenced by MixStream::Close().
MixStream::MixReader GetMixReader (bool consume)
Creates a BlockReader which mixes items from all workers.
Definition at line 119 of file mix_stream.cpp.
References Stream::local_worker_id_, MixStream::queue_, and Stream::rx_timespan_.
Referenced by MixStream::GetReader().
MixStream::MixReader GetReader (bool consume)
Open a MixReader (function name matches a method in File and CatStream).
Definition at line 124 of file mix_stream.cpp.
References MixStream::GetMixReader().
std::vector< MixStream::Writer > GetWriters () final virtual
Creates BlockWriters for each worker. BlockWriter can only be opened once, otherwise the block sequence is incorrectly interleaved!
Implements Stream.
Definition at line 72 of file mix_stream.cpp.
References Multiplexer::active_streams_, Multiplexer::block_pool_, thrill::data::default_block_size, BlockPool::hard_ram_limit(), Stream::id_, Stream::local_worker_id_, LOG, thrill::common::max(), Multiplexer::max_active_streams_, Multiplexer::MixLoopback(), Stream::multiplexer_, Multiplexer::mutex_, Stream::my_host_rank(), Stream::num_hosts(), Stream::num_workers(), Multiplexer::num_workers(), thrill::common::RoundDownToPowerOfTwo(), MixStream::sinks_, Stream::tx_timespan_, and Stream::workers_per_host().
MixBlockQueueSink * loopback_queue (size_t from_worker_id) private
Returns the loopback queue for the worker of this stream.
Definition at line 208 of file mix_stream.cpp.
References MixStream::loopback_, sLOG0, and Stream::workers_per_host().
void OnCloseStream (size_t from) private
called from Multiplexer when a MixStream closed notification was received.
Definition at line 190 of file mix_stream.cpp.
References MixBlockQueue::Close(), Stream::id_, Stream::my_worker_rank(), Stream::num_workers(), MixStream::queue_, Stream::remaining_closing_blocks_, Stream::rx_lifetime_, Stream::rx_net_blocks_, Stream::rx_timespan_, Stream::sem_closing_blocks_, Semaphore::signal(), and sLOG.
void OnStreamBlock (size_t from, PinnedBlock && b) private
called from Multiplexer when there is a new Block for this Stream.
Definition at line 174 of file mix_stream.cpp.
References MixBlockQueue::AppendBlock(), thrill::common::Hexdump(), Stream::id_, Stream::num_workers(), MixStream::queue_, Stream::rx_net_blocks_, Stream::rx_net_bytes_, Stream::rx_net_items_, Stream::rx_timespan_, sLOG, and sLOG0.
MixStream& operator= (const MixStream &) delete
non-copyable: delete assignment operator
void set_dia_id (size_t dia_id)
change dia_id after construction (needed because it may be unknown at construction)
Definition at line 67 of file mix_stream.cpp.
References Stream::dia_id_, MixStream::queue_, and MixBlockQueue::set_dia_id().
Member Data Documentation
constexpr bool debug = false static private
Definition at line 46 of file mix_stream.hpp.
bool is_closed_ = false private
flag if Close() was completed
Definition at line 87 of file mix_stream.hpp.
Referenced by MixStream::Close(), and MixStream::closed().
std::vector<MixBlockQueueSink> loopback_ private
vector of MixBlockQueueSink which serve as loopback BlockSinks into the MixBlockQueue
Definition at line 97 of file mix_stream.hpp.
Referenced by MixStream::loopback_queue(), and MixStream::MixStream().
MixBlockQueue queue_ private
BlockQueue to store incoming Blocks with source.
Definition at line 93 of file mix_stream.hpp.
Referenced by MixStream::closed(), MixStream::GetMixReader(), MixStream::OnCloseStream(), MixStream::OnStreamBlock(), and MixStream::set_dia_id().
std::vector<StreamSink> sinks_ private
StreamSink objects are receivers of Blocks outbound for other worker.
Definition at line 90 of file mix_stream.hpp.
Referenced by MixStream::Close(), MixStream::GetWriters(), and MixStream::MixStream().
The documentation for this exception was generated from the following files:
thrill/data/mix_stream.hpp
thrill/data/mix_stream.cpp