Thrill: Group Exception Reference
Group Exception Reference final
MPI Network API
Detailed Description
A net group backed by virtual MPI connection.
As MPI already sets up communication, not much is done. Each Group communicates using a unique MPI tag, the group id. Each host's rank within the group is plaining its MPI rank.
Definition at line 144 of file group.hpp.
#include <group.hpp>
Public Member Functions
Base Functions
Group (size_t my_rank, int group_tag, size_t group_size)
Initialize a Group for the given size and rank.
int group_tag () const
return MPI tag used to communicate
size_t num_hosts () const final
number of hosts configured.
net::Connection & connection (size_t peer) final
Return Connection to client id.
void Close () final
Close.
std::unique_ptr< net::Dispatcher > ConstructDispatcher (mem::Manager &mem_manager) const final
construct a mpi::Dispatcher exclusively for this Group.
void Barrier ()
run a MPI_Barrier() for synchronization.
Public Member Functions inherited from Group
Group (size_t my_rank)
initializing constructor
Group (const Group &)=delete
non-copyable: delete copy-constructor
Group (Group &&)=default
move-constructor: default
virtual ~Group ()
virtual destructor
template<>
void AllReduce (int &value, std::plus< int >)
template<>
void AllReduce (int &value, common::minimum< int >)
template<>
void AllReduce (int &value, common::maximum< int >)
template<>
void AllReduce (unsigned int &value, std::plus< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::minimum< unsigned int >)
template<>
void AllReduce (unsigned int &value, common::maximum< unsigned int >)
template<>
void AllReduce (long &value, std::plus< long >)
template<>
void AllReduce (long &value, common::minimum< long >)
template<>
void AllReduce (long &value, common::maximum< long >)
template<>
void AllReduce (unsigned long &value, std::plus< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::minimum< unsigned long >)
template<>
void AllReduce (unsigned long &value, common::maximum< unsigned long >)
template<>
void AllReduce (long long &value, std::plus< long long >)
template<>
void AllReduce (long long &value, common::minimum< long long >)
template<>
void AllReduce (long long &value, common::maximum< long long >)
template<>
void AllReduce (unsigned long long &value, std::plus< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::minimum< unsigned long long >)
template<>
void AllReduce (unsigned long long &value, common::maximum< unsigned long long >)
template<>
void Broadcast (int &value, size_t origin)
template<>
void Broadcast (unsigned int &value, size_t origin)
template<>
void Broadcast (long &value, size_t origin)
template<>
void Broadcast (unsigned long &value, size_t origin)
template<>
void Broadcast (long long &value, size_t origin)
template<>
void Broadcast (unsigned long long &value, size_t origin)
template<>
void ExPrefixSum (int &value, std::plus< int >)
template<>
void ExPrefixSum (unsigned int &value, std::plus< unsigned int >)
template<>
void ExPrefixSum (long &value, std::plus< long >)
template<>
void ExPrefixSum (unsigned long &value, std::plus< unsigned long >)
template<>
void ExPrefixSum (long long &value, std::plus< long long >)
template<>
void ExPrefixSum (unsigned long long &value, std::plus< unsigned long long >)
Group & operator= (const Group &)=delete
non-copyable: delete assignment operator
Group & operator= (Group &&)=default
move-assignment operator: default
template<>
void PrefixSum (int &value, std::plus< int >)
template<>
void PrefixSum (unsigned int &value, std::plus< unsigned int >)
template<>
void PrefixSum (long &value, std::plus< long >)
template<>
void PrefixSum (unsigned long &value, std::plus< unsigned long >)
template<>
void PrefixSum (long long &value, std::plus< long long >)
template<>
void PrefixSum (unsigned long long &value, std::plus< unsigned long long >)
size_t my_host_rank () const
Return our rank among hosts in this group.
size_t OneFactorSize () const
Number of of 1-factor iterations.
size_t OneFactorPeer (size_t round) const
template<typename T >
void SendTo (size_t dest, const T &data)
Sends a serializable type to the given peer.
template<typename T >
void ReceiveFrom (size_t src, T *data)
Receives a serializable type from the given peer.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSum (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate inclusive prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void ExPrefixSum (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate exclusive prefix sum.
template<typename T >
void Broadcast (T &value, size_t origin=0)
Broadcast a value from the worker "origin".
template<typename T , typename BinarySumOp = std::plus<T>>
void Reduce (T &value, size_t root=0, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to the worker 0.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduce (T &value, BinarySumOp sum_op=BinarySumOp())
Reduce a value from all workers to all workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumSelect (T &value, BinarySumOp sum_op=BinarySumOp(), bool inclusive=true)
select prefixsum implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumDoubling (T &value, BinarySumOp sum_op=BinarySumOp(), bool inclusive=true)
Calculate for every worker his prefix sum.
template<typename T , typename BinarySumOp = std::plus<T>>
void PrefixSumHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Calculate for every worker his prefix sum.
template<typename T >
void BroadcastSelect (T &value, size_t origin=0)
select broadcast implementation (often due to total number of processors)
template<typename T >
void BroadcastTrivial (T &value, size_t origin=0)
Broadcasts the value of the peer with index 0 to all the others.
template<typename T >
void BroadcastBinomialTree (T &value, size_t origin=0)
Broadcasts the value of the worker with index "origin" to all the others.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSelect (T &value, BinarySumOp sum_op=BinarySumOp())
select allreduce implementation (often due to total number of processors)
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceSimple (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce on the workers.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceAtRoot (T &value, BinarySumOp sum_op=BinarySumOp())
Broadcasts the value of the peer with index 0 to all the others.
template<typename T , typename BinarySumOp = std::plus<T>>
void AllReduceHypercube (T &value, BinarySumOp sum_op=BinarySumOp())
Perform an All-Reduce for powers of two.
Private Member Functions
Virtual Synchronous Collectives to Override Implementations
void PrefixSumPlusInt (int &value) final
void ExPrefixSumPlusInt (int &value) final
void BroadcastInt (int &value, size_t origin) final
void AllReducePlusInt (int &value) final
void AllReduceMinimumInt (int &value) final
void AllReduceMaximumInt (int &value) final
void PrefixSumPlusUnsignedInt (unsigned int &value) final
void ExPrefixSumPlusUnsignedInt (unsigned int &value) final
void BroadcastUnsignedInt (unsigned int &value, size_t origin) final
void AllReducePlusUnsignedInt (unsigned int &value) final
void AllReduceMinimumUnsignedInt (unsigned int &value) final
void AllReduceMaximumUnsignedInt (unsigned int &value) final
void PrefixSumPlusLong (long &value) final
void ExPrefixSumPlusLong (long &value) final
void BroadcastLong (long &value, size_t origin) final
void AllReducePlusLong (long &value) final
void AllReduceMinimumLong (long &value) final
void AllReduceMaximumLong (long &value) final
void PrefixSumPlusUnsignedLong (unsigned long &value) final
void ExPrefixSumPlusUnsignedLong (unsigned long &value) final
void BroadcastUnsignedLong (unsigned long &value, size_t origin) final
void AllReducePlusUnsignedLong (unsigned long &value) final
void AllReduceMinimumUnsignedLong (unsigned long &value) final
void AllReduceMaximumUnsignedLong (unsigned long &value) final
void PrefixSumPlusLongLong (long long &value) final
void ExPrefixSumPlusLongLong (long long &value) final
void BroadcastLongLong (long long &value, size_t origin) final
void AllReducePlusLongLong (long long &value) final
void AllReduceMinimumLongLong (long long &value) final
void AllReduceMaximumLongLong (long long &value) final
void PrefixSumPlusUnsignedLongLong (unsigned long long &value) final
void ExPrefixSumPlusUnsignedLongLong (unsigned long long &value) final
void BroadcastUnsignedLongLong (unsigned long long &value, size_t origin) final
void AllReducePlusUnsignedLongLong (unsigned long long &value) final
void AllReduceMinimumUnsignedLongLong (unsigned long long &value) final
void AllReduceMaximumUnsignedLongLong (unsigned long long &value) final
Private Attributes
std::vector< Connection > conns_
vector of virtual connection objects to remote peers
int group_tag_
this group's MPI tag
Static Private Attributes
static constexpr bool debug = false
Additional Inherited Members
Virtual Synchronous Collectives to Override Implementations
Protected Attributes inherited from Group
size_t my_rank_
our rank in the network group
Constructor & Destructor Documentation
Group (size_t my_rank, int group_tag, size_t group_size) inline
Initialize a Group for the given size and rank.
Definition at line 153 of file group.hpp.
References Group::conns_, and thrill::net::mpi::Initialize().
Member Function Documentation
void AllReduceMaximumInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 201 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMaximumLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 251 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMaximumLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 301 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMaximumUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 226 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMaximumUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 276 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMaximumUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 326 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 197 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 247 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 297 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 222 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 272 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReduceMinimumUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 322 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 193 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 243 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 293 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 218 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 268 of file group.cpp.
References thrill::net::mpi::g_mutex.
void AllReducePlusUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 318 of file group.cpp.
References thrill::net::mpi::g_mutex.
void Barrier ()
run a MPI_Barrier() for synchronization.
Definition at line 131 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastInt (int & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 189 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastLong (long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 239 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastLongLong (long long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 289 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastUnsignedInt (unsigned int & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 214 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastUnsignedLong (unsigned long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 264 of file group.cpp.
References thrill::net::mpi::g_mutex.
void BroadcastUnsignedLongLong (unsigned long long & value, size_t origin) final private virtual
Reimplemented from Group.
Definition at line 314 of file group.cpp.
References thrill::net::mpi::g_mutex.
void Close () inline final virtual
Close.
Implements Group.
Definition at line 173 of file group.hpp.
net::Connection& connection (size_t id) inline final virtual
Return Connection to client id.
Implements Group.
Definition at line 168 of file group.hpp.
References Group::conns_.
std::unique_ptr< net::Dispatcher > ConstructDispatcher (mem::Manager & mem_manager) const final virtual
construct a mpi::Dispatcher exclusively for this Group.
Implements Group.
Definition at line 125 of file group.cpp.
References Group::group_tag_, and Group::num_hosts().
void ExPrefixSumPlusInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 184 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
void ExPrefixSumPlusLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 234 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
void ExPrefixSumPlusLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 284 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
void ExPrefixSumPlusUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 209 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
void ExPrefixSumPlusUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 259 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
void ExPrefixSumPlusUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 309 of file group.cpp.
References thrill::net::mpi::g_mutex, and gen_data::value.
int group_tag () const inline
return MPI tag used to communicate
Definition at line 163 of file group.hpp.
References Group::group_tag_.
size_t num_hosts () const inline final virtual
number of hosts configured.
Implements Group.
Definition at line 166 of file group.hpp.
References Group::conns_.
Referenced by Group::ConstructDispatcher().
void PrefixSumPlusInt (int & value) final private virtual
Reimplemented from Group.
Definition at line 180 of file group.cpp.
References thrill::net::mpi::g_mutex.
void PrefixSumPlusLong (long & value) final private virtual
Reimplemented from Group.
Definition at line 230 of file group.cpp.
References thrill::net::mpi::g_mutex.
void PrefixSumPlusLongLong (long long & value) final private virtual
Reimplemented from Group.
Definition at line 280 of file group.cpp.
References thrill::net::mpi::g_mutex.
void PrefixSumPlusUnsignedInt (unsigned int & value) final private virtual
Reimplemented from Group.
Definition at line 205 of file group.cpp.
References thrill::net::mpi::g_mutex.
void PrefixSumPlusUnsignedLong (unsigned long & value) final private virtual
Reimplemented from Group.
Definition at line 255 of file group.cpp.
References thrill::net::mpi::g_mutex.
void PrefixSumPlusUnsignedLongLong (unsigned long long & value) final private virtual
Reimplemented from Group.
Definition at line 305 of file group.cpp.
References thrill::net::mpi::g_mutex.
Member Data Documentation
std::vector<Connection> conns_ private
vector of virtual connection objects to remote peers
Definition at line 189 of file group.hpp.
Referenced by Group::connection(), Group::Group(), and Group::num_hosts().
constexpr bool debug = false static private
Definition at line 146 of file group.hpp.
int group_tag_ private
this group's MPI tag
Definition at line 186 of file group.hpp.
Referenced by Group::ConstructDispatcher(), and Group::group_tag().
The documentation for this exception was generated from the following files:
thrill/net/mpi/group.hpp
thrill/net/mpi/group.cpp