Thrill: LinuxaioQueue Exception Reference
LinuxaioQueue Exception Reference final
I/O Requests and Queues
Detailed Description
Queue for linuxaio_file(s)
Only one queue exists in a program, i.e. it is a singleton.
Definition at line 37 of file linuxaio_queue.hpp.
#include <linuxaio_queue.hpp>
Public Member Functions
LinuxaioQueue (int desired_queue_length=0)
~LinuxaioQueue ()
void AddRequest (RequestPtr &req) final
bool CancelRequest (Request *req) final
void CompleteRequest (RequestPtr &req)
Private Types
using Queue = std::list< RequestPtr >
storing linuxaio_request* would drop ownership
using self_type = LinuxaioQueue
Private Member Functions
void HandleEvents (io_event *events, long num_events, bool canceled)
aio_context_t io_context ()
void PostRequests ()
void Suspend ()
void WaitRequests ()
Static Private Member Functions
static void * PostAsync (void *arg)
static void * WaitAsync (void *arg)
Private Attributes
aio_context_t context_
OS context.
int max_events_
max number of OS requests
common::Semaphore num_free_events_
common::Semaphore num_posted_requests_
common::Semaphore num_waiting_requests_
number of requests in waitings_requests
std::thread post_thread_
common::SharedState< ThreadState > post_thread_state_
std::mutex posted_mtx_
Queue posted_requests_
std::thread wait_thread_
common::SharedState< ThreadState > wait_thread_state_
std::mutex waiting_mtx_
Queue waiting_requests_
Static Private Attributes
static constexpr PriorityOp priority_op_ = WRITE
Additional Inherited Members
Public Types inherited from RequestQueue
enum PriorityOp { READ, WRITE, NONE }
Protected Types inherited from RequestQueueImplWorker
enum ThreadState { NOT_RUNNING, RUNNING, TERMINATING, TERMINATED }
Protected Member Functions inherited from RequestQueueImplWorker
void StartThread (void *(*worker)(void *), void *arg, std::thread &t, common::SharedState< ThreadState > &s)
void StopThread (std::thread &t, common::SharedState< ThreadState > &s, common::Semaphore &sem)
Member Typedef Documentation
using Queue = std::list<RequestPtr> private
storing linuxaio_request* would drop ownership
Definition at line 48 of file linuxaio_queue.hpp.
using self_type = LinuxaioQueue private
Definition at line 41 of file linuxaio_queue.hpp.
Constructor & Destructor Documentation
LinuxaioQueue (int desired_queue_length = 0) explicit
Construct queue. Requests max number of requests simultaneously submitted to disk, 0 means as many as possible
Definition at line 35 of file linuxaio_queue.cpp.
References LinuxaioQueue::context_, LOG1, LinuxaioQueue::max_events_, LinuxaioQueue::num_free_events_, LinuxaioQueue::post_thread_, LinuxaioQueue::post_thread_state_, LinuxaioQueue::PostAsync(), Semaphore::signal(), RequestQueueImplWorker::StartThread(), THRILL_THROW_ERRNO, LinuxaioQueue::wait_thread_, LinuxaioQueue::wait_thread_state_, and LinuxaioQueue::WaitAsync().
~LinuxaioQueue ()
Definition at line 66 of file linuxaio_queue.cpp.
References LinuxaioQueue::context_, LinuxaioQueue::num_posted_requests_, LinuxaioQueue::num_waiting_requests_, LinuxaioQueue::post_thread_, LinuxaioQueue::post_thread_state_, RequestQueueImplWorker::StopThread(), LinuxaioQueue::wait_thread_, and LinuxaioQueue::wait_thread_state_.
Member Function Documentation
void AddRequest (RequestPtr & req) final virtual
Implements RequestQueue.
Definition at line 72 of file linuxaio_queue.cpp.
References CountingPtr< Type, Deleter >::empty(), CountingPtr< Type, Deleter >::get(), LOG1, LinuxaioQueue::num_waiting_requests_, LinuxaioQueue::post_thread_state_, RequestQueueImplWorker::RUNNING, Semaphore::signal(), THRILL_THROW_INVALID_ARGUMENT, LinuxaioQueue::waiting_mtx_, and LinuxaioQueue::waiting_requests_.
bool CancelRequest (Request * req) final virtual
Implements RequestQueue.
Definition at line 86 of file linuxaio_queue.cpp.
References LOG1, LinuxaioQueue::num_free_events_, LinuxaioQueue::num_posted_requests_, LinuxaioQueue::num_waiting_requests_, LinuxaioQueue::post_thread_state_, LinuxaioQueue::posted_mtx_, LinuxaioQueue::posted_requests_, RequestQueueImplWorker::RUNNING, Semaphore::signal(), THRILL_THROW_INVALID_ARGUMENT, Semaphore::wait(), LinuxaioQueue::waiting_mtx_, and LinuxaioQueue::waiting_requests_.
Referenced by LinuxaioRequest::cancel().
void CompleteRequest (RequestPtr & req)
void HandleEvents (io_event * events, long num_events, bool canceled) private
Definition at line 198 of file linuxaio_queue.cpp.
References CountingPtr< Type, Deleter >::get(), LinuxaioQueue::num_free_events_, LinuxaioQueue::num_posted_requests_, Semaphore::signal(), and Semaphore::wait().
Referenced by LinuxaioRequest::cancel_aio(), LinuxaioQueue::PostRequests(), and LinuxaioQueue::WaitRequests().
aio_context_t io_context () inline private
Definition at line 82 of file linuxaio_queue.hpp.
References LinuxaioQueue::context_.
Referenced by LinuxaioRequest::cancel_aio(), and LinuxaioRequest::post().
void * PostAsync (void * arg) static private
Definition at line 249 of file linuxaio_queue.cpp.
References LinuxaioQueue::post_thread_state_, SharedState< ValueType >::set_to(), and RequestQueueImplWorker::TERMINATED.
Referenced by LinuxaioQueue::LinuxaioQueue().
void PostRequests () private
Definition at line 139 of file linuxaio_queue.cpp.
References LinuxaioQueue::context_, CountingPtr< Type, Deleter >::get(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::max_events_, LinuxaioQueue::num_free_events_, LinuxaioQueue::num_posted_requests_, LinuxaioQueue::num_waiting_requests_, LinuxaioQueue::post_thread_state_, LinuxaioQueue::posted_mtx_, LinuxaioQueue::posted_requests_, Semaphore::signal(), RequestQueueImplWorker::TERMINATING, THRILL_THROW_ERRNO, Semaphore::wait(), LinuxaioQueue::waiting_mtx_, and LinuxaioQueue::waiting_requests_.
void Suspend () private
void * WaitAsync (void * arg) static private
Definition at line 264 of file linuxaio_queue.cpp.
References SharedState< ValueType >::set_to(), RequestQueueImplWorker::TERMINATED, and LinuxaioQueue::wait_thread_state_.
Referenced by LinuxaioQueue::LinuxaioQueue().
void WaitRequests () private
Definition at line 211 of file linuxaio_queue.cpp.
References LinuxaioQueue::context_, LinuxaioQueue::HandleEvents(), LinuxaioQueue::max_events_, LinuxaioQueue::num_posted_requests_, Semaphore::signal(), RequestQueueImplWorker::TERMINATING, THRILL_THROW_ERRNO, Semaphore::wait(), and LinuxaioQueue::wait_thread_state_.
Member Data Documentation
aio_context_t context_ private
OS context.
Definition at line 45 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::io_context(), LinuxaioQueue::LinuxaioQueue(), LinuxaioQueue::PostRequests(), LinuxaioQueue::WaitRequests(), and LinuxaioQueue::~LinuxaioQueue().
int max_events_ private
max number of OS requests
Definition at line 56 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::LinuxaioQueue(), LinuxaioQueue::PostRequests(), and LinuxaioQueue::WaitRequests().
common::Semaphore num_free_events_ private
Definition at line 58 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::CancelRequest(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::LinuxaioQueue(), and LinuxaioQueue::PostRequests().
common::Semaphore num_posted_requests_ private
Definition at line 58 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::CancelRequest(), LinuxaioQueue::HandleEvents(), LinuxaioQueue::PostRequests(), LinuxaioQueue::WaitRequests(), and LinuxaioQueue::~LinuxaioQueue().
common::Semaphore num_waiting_requests_ private
number of requests in waitings_requests
Definition at line 58 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::AddRequest(), LinuxaioQueue::CancelRequest(), LinuxaioQueue::PostRequests(), and LinuxaioQueue::~LinuxaioQueue().
std::thread post_thread_ private
Definition at line 61 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::LinuxaioQueue(), and LinuxaioQueue::~LinuxaioQueue().
common::SharedState<ThreadState> post_thread_state_ private
Definition at line 62 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::AddRequest(), LinuxaioQueue::CancelRequest(), LinuxaioQueue::LinuxaioQueue(), LinuxaioQueue::PostAsync(), LinuxaioQueue::PostRequests(), and LinuxaioQueue::~LinuxaioQueue().
std::mutex posted_mtx_ private
Definition at line 52 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::CancelRequest(), and LinuxaioQueue::PostRequests().
Queue posted_requests_ private
Definition at line 53 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::CancelRequest(), and LinuxaioQueue::PostRequests().
constexpr PriorityOp priority_op_ = WRITE static private
Definition at line 72 of file linuxaio_queue.hpp.
std::thread wait_thread_ private
Definition at line 61 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::LinuxaioQueue(), and LinuxaioQueue::~LinuxaioQueue().
common::SharedState<ThreadState> wait_thread_state_ private
Definition at line 62 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::LinuxaioQueue(), LinuxaioQueue::WaitAsync(), LinuxaioQueue::WaitRequests(), and LinuxaioQueue::~LinuxaioQueue().
std::mutex waiting_mtx_ private
Definition at line 52 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::AddRequest(), LinuxaioQueue::CancelRequest(), and LinuxaioQueue::PostRequests().
Queue waiting_requests_ private
Definition at line 53 of file linuxaio_queue.hpp.
Referenced by LinuxaioQueue::AddRequest(), LinuxaioQueue::CancelRequest(), and LinuxaioQueue::PostRequests().
The documentation for this exception was generated from the following files:
thrill/io/linuxaio_queue.hpp
thrill/io/linuxaio_queue.cpp