Thrill: SelectDispatcher Exception Reference
SelectDispatcher Exception Reference final
TCP Socket API
Detailed Description
SelectDispatcher is a higher level wrapper for select().
One can register Socket objects for readability and writability checks, buffered reads and writes with completion callbacks, and also timer functions.
Definition at line 51 of file select_dispatcher.hpp.
#include <select_dispatcher.hpp>
Classes
struct Watch
callback vectors per watched file descriptor
Public Types
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Public Member Functions
SelectDispatcher (mem::Manager &mem_manager)
constructor
~SelectDispatcher ()
void AddRead (int fd, const Callback &read_cb)
Register a buffered read callback and a default exception callback.
void AddRead (net::Connection &c, const Callback &read_cb) final
Register a buffered read callback and a default exception callback.
void AddWrite (net::Connection &c, const Callback &write_cb) final
Register a buffered write callback and a default exception callback.
void Cancel (net::Connection &c) final
Cancel all callbacks on a given fd.
void CheckSize (int fd)
Grow table if needed.
void DispatchOne (const std::chrono::milliseconds &timeout) final
Run one iteration of dispatching select().
void Interrupt () final
Interrupt the current select via self-pipe.
void SetExcept (net::Connection &c, const Callback &except_cb)
Register a buffered write callback and a default exception callback.
Public Member Functions inherited from Dispatcher
Dispatcher (mem::Manager &mem_manager)
default constructor
Dispatcher (const Dispatcher &)=delete
non-copyable: delete copy-constructor
virtual ~Dispatcher ()
virtual destructor
Dispatcher & operator= (const Dispatcher &)=delete
non-copyable: delete assignment operator
void AddTimer (const std::chrono::milliseconds &timeout, const TimerCallback &cb)
Register a relative timeout callback.
virtual void AsyncRead (Connection &c, size_t size, const AsyncReadBufferCallback &done_cb)
asynchronously read n bytes and deliver them to the callback
virtual void AsyncRead (Connection &c, size_t size, data::PinnedByteBlockPtr &&block, const AsyncReadByteBlockCallback &done_cb)
asynchronously read the full ByteBlock and deliver it to the callback
virtual void AsyncWrite (Connection &c, Buffer &&buffer, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
virtual void AsyncWrite (Connection &c, data::PinnedBlock &&block, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, const void *buffer, size_t size, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void AsyncWriteCopy (Connection &c, const std::string &str, const AsyncWriteCallback &done_cb=AsyncWriteCallback())
void Dispatch ()
Dispatch one or more events.
void Loop ()
Loop over Dispatch() until terminate_ flag is set.
void Terminate ()
bool HasAsyncWrites () const
Check whether there are still AsyncWrite()s in the queue.
Private Member Functions
bool SelfPipeCallback ()
Self-pipe callback.
Static Private Member Functions
static bool DefaultExceptionCallback ()
Default exception handler.
Private Attributes
Select select_
select() manager object
int self_pipe_ [2]
self-pipe to wake up select.
char self_pipe_buffer_ [32]
buffer to receive one byte signals from self-pipe
mem::vector< Watch > watch_ { mem::Allocator<Watch>(mem_manager_) }
Static Private Attributes
static constexpr bool debug = false
static constexpr bool self_verify_ = common::g_self_verify
Additional Inherited Members
Protected Types inherited from Dispatcher
using TimerPQ = std::priority_queue< Timer, std::vector< Timer, mem::GPoolAllocator< Timer > > >
priority queue of timer callbacks
Static Protected Member Functions inherited from Dispatcher
static bool ExceptionCallback (Connection &c)
Default exception handler.
Protected Attributes inherited from Dispatcher
std::deque< AsyncReadBuffer,
mem::GPoolAllocator
< AsyncReadBuffer > > async_read_
deque of asynchronous readers
std::deque< AsyncReadByteBlock,
mem::GPoolAllocator
< AsyncReadByteBlock > > async_read_block_
deque of asynchronous readers
std::deque< AsyncWriteBuffer,
mem::GPoolAllocator
< AsyncWriteBuffer > > async_write_
deque of asynchronous writers
std::deque< AsyncWriteBlock,
mem::GPoolAllocator
< AsyncWriteBlock > > async_write_block_
deque of asynchronous writers
mem::Manager & mem_manager_
superior memory manager
std::atomic< bool > terminate_ { false }
true if dispatcher needs to stop
TimerPQ timer_pq_
Member Typedef Documentation
using Callback = AsyncCallback
type for file descriptor readiness callbacks
Definition at line 59 of file select_dispatcher.hpp.
Constructor & Destructor Documentation
SelectDispatcher (mem::Manager & mem_manager) inline explicit
constructor
Definition at line 62 of file select_dispatcher.hpp.
References SelectDispatcher::AddRead(), LOG1, thrill::common::MakePipe(), SelectDispatcher::self_pipe_, SelectDispatcher::SelfPipeCallback(), and Socket::SetNonBlocking().
~SelectDispatcher () inline
Definition at line 80 of file select_dispatcher.hpp.
References SelectDispatcher::self_pipe_.
Member Function Documentation
void AddRead (int fd, const Callback & read_cb) inline
Register a buffered read callback and a default exception callback.
Definition at line 94 of file select_dispatcher.hpp.
References SelectDispatcher::CheckSize(), SelectDispatcher::select_, Select::SetException(), Select::SetRead(), and SelectDispatcher::watch_.
Referenced by SelectDispatcher::AddRead(), and SelectDispatcher::SelectDispatcher().
void AddRead (net::Connection & c, const Callback & read_cb) inline final virtual
Register a buffered read callback and a default exception callback.
Implements Dispatcher.
Definition at line 105 of file select_dispatcher.hpp.
References SelectDispatcher::AddRead(), Socket::fd(), and Connection::GetSocket().
void AddWrite (net::Connection & c, const Callback & write_cb) inline final virtual
Register a buffered write callback and a default exception callback.
Implements Dispatcher.
Definition at line 113 of file select_dispatcher.hpp.
References SelectDispatcher::CheckSize(), Socket::fd(), Connection::GetSocket(), SelectDispatcher::select_, Select::SetException(), Select::SetWrite(), and SelectDispatcher::watch_.
void Cancel (net::Connection & c) inline final virtual
Cancel all callbacks on a given fd.
Implements Dispatcher.
Definition at line 140 of file select_dispatcher.hpp.
References SelectDispatcher::Watch::active, SelectDispatcher::CheckSize(), Select::ClearException(), Select::ClearRead(), Select::ClearWrite(), SelectDispatcher::Watch::except_cb, Socket::fd(), Connection::GetSocket(), LOG, SelectDispatcher::Watch::read_cb, SelectDispatcher::select_, SelectDispatcher::watch_, and SelectDispatcher::Watch::write_cb.
void CheckSize (int fd) inline
Grow table if needed.
Definition at line 86 of file select_dispatcher.hpp.
References Dispatcher::mem_manager_, and SelectDispatcher::watch_.
Referenced by SelectDispatcher::AddRead(), SelectDispatcher::AddWrite(), SelectDispatcher::Cancel(), and SelectDispatcher::SetExcept().
static bool DefaultExceptionCallback () inline static private
Default exception handler.
Definition at line 198 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::DispatchOne().
void DispatchOne (const std::chrono::milliseconds & timeout) final virtual
Run one iteration of dispatching select().
Implements Dispatcher.
Definition at line 22 of file select_dispatcher.cpp.
References SelectDispatcher::Watch::active, Select::ClearException(), Select::ClearRead(), Select::ClearWrite(), SelectDispatcher::debug, SelectDispatcher::DefaultExceptionCallback(), SelectDispatcher::Watch::except_cb, Select::InException(), Select::InRead(), Select::InWrite(), LOG, SelectDispatcher::Watch::read_cb, SelectDispatcher::select_, Select::select_timeout(), SelectDispatcher::self_verify_, SelectDispatcher::watch_, and SelectDispatcher::Watch::write_cb.
void Interrupt () final virtual
Interrupt the current select via self-pipe.
Implements Dispatcher.
Definition at line 164 of file select_dispatcher.cpp.
References die_unless, LOG1, and SelectDispatcher::self_pipe_.
bool SelfPipeCallback () private
Self-pipe callback.
Definition at line 182 of file select_dispatcher.cpp.
References SelectDispatcher::self_pipe_, and SelectDispatcher::self_pipe_buffer_.
Referenced by SelectDispatcher::SelectDispatcher().
void SetExcept (net::Connection & c, const Callback & except_cb) inline
Register a buffered write callback and a default exception callback.
Definition at line 127 of file select_dispatcher.hpp.
References SelectDispatcher::CheckSize(), Socket::fd(), Connection::GetSocket(), SelectDispatcher::select_, Select::SetException(), and SelectDispatcher::watch_.
Member Data Documentation
constexpr bool debug = false static private
Definition at line 53 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::DispatchOne().
Select select_ private
select() manager object
Definition at line 170 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::AddRead(), SelectDispatcher::AddWrite(), SelectDispatcher::Cancel(), SelectDispatcher::DispatchOne(), and SelectDispatcher::SetExcept().
int self_pipe_[2] private
self-pipe to wake up select.
Definition at line 173 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::Interrupt(), SelectDispatcher::SelectDispatcher(), SelectDispatcher::SelfPipeCallback(), and SelectDispatcher::~SelectDispatcher().
char self_pipe_buffer_[32] private
buffer to receive one byte signals from self-pipe
Definition at line 176 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::SelfPipeCallback().
constexpr bool self_verify_ = common::g_self_verify static private
Definition at line 55 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::DispatchOne().
mem::vector<Watch> watch_ { mem::Allocator<Watch>(mem_manager_) } private
handlers for all registered file descriptors. the fd integer range should be small enough, otherwise a more complicated data structure is needed.
Definition at line 195 of file select_dispatcher.hpp.
Referenced by SelectDispatcher::AddRead(), SelectDispatcher::AddWrite(), SelectDispatcher::Cancel(), SelectDispatcher::CheckSize(), SelectDispatcher::DispatchOne(), and SelectDispatcher::SetExcept().
The documentation for this exception was generated from the following files:
thrill/net/tcp/select_dispatcher.hpp
thrill/net/tcp/select_dispatcher.cpp