Thrill: SortNode< ValueType, CompareFunction, SortAlgorithm > Exception Template Reference
SortNode< ValueType, CompareFunction, SortAlgorithm > Exception Template Reference final
DIA API Layer
Detailed Description
template<typename ValueType, typename CompareFunction, typename SortAlgorithm>
exception thrill::api::SortNode< ValueType, CompareFunction, SortAlgorithm >
A DIANode which performs a Sort operation.
Sort sorts a DIA according to a given compare function
Template Parameters
ValueType Type of DIA elements
Stack Function stack, which contains the chained lambdas between the last and this DIANode.
CompareFunction Type of the compare function
Definition at line 54 of file sort.hpp.
#include <sort.hpp>
Classes
class TreeBuilder
Public Member Functions
template<typename ParentDIA >
SortNode (const ParentDIA &parent, const CompareFunction &compare_function, const SortAlgorithm &sort_algorithm=SortAlgorithm())
Constructor for a sort node.
void Dispose () final
Virtual clear method. Triggers actual disposing in sub-classes.
size_t MaxMergeDegreePrefetch ()
void PushData (bool consume) final
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Public Member Functions inherited from DOpNode< ValueType >
DOpNode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DOpNode, which sets references to the parent nodes.
DOpNode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DOpNode, which sets references to the parent nodes.
Public Member Functions inherited from DIANode< ValueType >
DIANode (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
Constructor for a DIANode, which sets references to the parent nodes.
DIANode (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
Constructor for a DIANode, which sets references to the parent nodes.
virtual void AddChild (DIABase *node, const Callback &callback=Callback(), size_t parent_index=0)
Enables children to push their "folded" function chains to their parent.
std::vector< DIABase * > children () const override
Returns the children of this DIABase.
void PushFile (data::File &file, bool consume) const
void PushItem (const ValueType &item) const
Method for derived classes to Push a single item to all children.
void RemoveAllChildren () override
void RemoveChild (DIABase *node) override
void RunPushData () override
Public Member Functions inherited from DIABase
DIABase (Context &ctx, const char *label, const std::initializer_list< size_t > &parent_ids, const std::initializer_list< DIABasePtr > &parents)
The constructor for a DIABase.
DIABase (Context &ctx, const char *label, std::vector< size_t > &&parent_ids, std::vector< DIABasePtr > &&parents)
The constructor for a DIABase.
DIABase (const DIABase &)=delete
non-copyable: delete copy-constructor
DIABase (DIABase &&)=default
move-constructor: default
virtual ~DIABase ()
Virtual destructor for a DIABase.
virtual size_t consume_counter () const
Returns consume_counter_.
Context & context ()
Returns the api::Context of this DIABase.
virtual void DecConsumeCounter (size_t counter)
virtual bool ForwardDataOnly () const
const size_t & id () const
return unique id() of DIANode subclass as stored by StatsNode
virtual void IncConsumeCounter (size_t counter)
const char * label () const
return label() of DIANode subclass as stored by StatsNode
mem::Manager & mem_manager ()
Return the Context's memory manager.
DIABase & operator= (const DIABase &)=delete
non-copyable: delete assignment operator
DIABase & operator= (DIABase &&)=default
move-assignment operator: default
std::vector< size_t > parent_ids () const
Returns the parents of this DIABase.
const std::vector< DIABasePtr > & parents () const
Returns the parents of this DIABase.
void RemoveParent (DIABase *p)
Remove a parent.
virtual bool RequireParentPushData (size_t) const
void RunScope ()
void set_mem_limit (const DIAMemUse &mem_limit)
void set_state (const DIAState &state)
virtual void SetConsumeCounter (size_t counter)
DIAState state () const
virtual DIAMemUse PreOpMemUse ()
Amount of RAM used by PreOp after StartPreOp()
virtual void StartPreOp (size_t)
Virtual method for preparing start of PushData.
virtual bool OnPreOpFile (const data::File &, size_t)
virtual void StopPreOp (size_t)
Virtual method for preparing end of PushData.
virtual DIAMemUse ExecuteMemUse ()
Amount of RAM used by Execute()
virtual void Execute ()=0
Virtual execution method. Triggers actual computation in sub-classes.
virtual DIAMemUse PushDataMemUse ()
Amount of RAM used by PushData()
Public Member Functions inherited from ReferenceCount
ReferenceCount () noexcept
new objects have zero reference count
ReferenceCount (const ReferenceCount &) noexcept
coping still creates a new object with zero reference count
~ReferenceCount ()
bool DecReference () const noexcept
Call whenever resetting (i.e.
void IncReference () const noexcept
Call whenever setting a pointer to the object.
ReferenceCount & operator= (const ReferenceCount &) noexcept
assignment operator, leaves pointers unchanged
size_t reference_count () const noexcept
Return the number of references to this object (for debugging)
bool unique () const noexcept
Test if the ReferenceCount is referenced by only one CountingPtr.
Private Types
using RunTimer = common::RunTimer< Timer >
RIAA class for running the timer.
using SampleIndexPair = std::pair< ValueType, size_t >
using Super = DOpNode< ValueType >
using Timer = common::StatsTimerBaseStopped< stats_enabled >
Timer or FakeTimer.
Private Member Functions
bool EqualSampleGreaterIndex (const SampleIndexPair &a, const SampleIndexPair &b)
void FindAndSendSplitters (std::vector< SampleIndexPair > &splitters, size_t sample_size, data::MixStreamPtr &sample_stream, std::vector< data::MixStream::Writer > &sample_writers)
bool LessSampleIndex (const SampleIndexPair &a, const SampleIndexPair &b)
void MainOp ()
void ReceiveItems (data::MixStreamPtr &data_stream)
void SortAndWriteToFile (std::vector< ValueType > &vec)
void TransmitItems (const ValueType *const tree, size_t k, size_t log_k, size_t actual_k, const SampleIndexPair *const sorted_splitters, size_t prefix_items, data::MixStreamPtr &data_stream)
Static Private Member Functions
template<typename Integral >
static size_t RoundDown (Integral n, Integral k)
round n down by k where k is a power of two.
Private Attributes
CompareFunction compare_function_
The comparison function which is applied to two elements.
const bool parent_stack_empty_
Whether the parent stack is empty.
SortAlgorithm sort_algorithm_
Sort function class.
MainOp and PushData
std::deque< data::File > files_
Local data files.
size_t local_out_size_ = 0
Total number of local elements after communication.
Statistics
Timer timer_preop_
time spent in PreOp (including preceding Node's computation)
Timer timer_execute_
time spent in Execute
Timer timer_sort_
time spent in sort()
Static Private Attributes
static constexpr bool debug = false
static constexpr bool stats_enabled = false
Set this variable to true to enable generation and output of stats.
static const bool use_background_thread_ = false
PreOp Phase
static constexpr double desired_imbalance_ = 0.1
epsilon
data::File unsorted_file_ { context_.GetFile(this) }
All local unsorted items before communication.
data::File::Writer unsorted_writer_
Writer for unsorted_file_.
size_t local_items_ = 0
Number of items on this worker.
std::vector< SampleIndexPair > samples_
Sample vector: pairs of (sample,local index)
size_t sample_interval_ = 1
Number of items to process before the next sample was drawn.
std::default_random_engine rng_ { std::random_device { } () }
Random generator.
size_t wanted_sample_size () const
calculate currently desired number of samples
Additional Inherited Members
Public Types inherited from DOpNode< ValueType >
using Super = DIANode< ValueType >
Public Attributes inherited from DIABase
common::JsonLogger logger_
Static Public Attributes inherited from DIABase
static constexpr size_t kNeverConsume = static_cast<size_t>(-1)
Never full consume.
Protected Attributes inherited from DIANode< ValueType >
std::vector< Child > children_
Callback functions from the child nodes.
Member Typedef Documentation
using RunTimer = common::RunTimer<Timer> private
RIAA class for running the timer.
Definition at line 67 of file sort.hpp.
using SampleIndexPair = std::pair<ValueType, size_t> private
Definition at line 69 of file sort.hpp.
using Super = DOpNode<ValueType> private
Definition at line 61 of file sort.hpp.
using Timer = common::StatsTimerBaseStopped<stats_enabled> private
Timer or FakeTimer.
Definition at line 65 of file sort.hpp.
Constructor & Destructor Documentation
SortNode (const ParentDIA & parent, const CompareFunction & compare_function, const SortAlgorithm & sort_algorithm = SortAlgorithm()) inline
Constructor for a sort node.
Definition at line 78 of file sort.hpp.
Member Function Documentation
void Dispose () inline final virtual
Virtual clear method. Triggers actual disposing in sub-classes.
Reimplemented from DIABase.
Definition at line 289 of file sort.hpp.
References SortNode< ValueType, CompareFunction, SortAlgorithm >::files_.
bool EqualSampleGreaterIndex (const SampleIndexPair & a, const SampleIndexPair & b) inline private
Definition at line 440 of file sort.hpp.
References SortNode< ValueType, CompareFunction, SortAlgorithm >::compare_function_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems().
void FindAndSendSplitters (std::vector< SampleIndexPair > & splitters, size_t sample_size, data::MixStreamPtr & sample_stream, std::vector< data::MixStream::Writer > & sample_writers) inline private
Definition at line 357 of file sort.hpp.
References DIABase::context_, SortNode< ValueType, CompareFunction, SortAlgorithm >::LessSampleIndex(), and Context::num_workers().
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
bool LessSampleIndex (const SampleIndexPair & a, const SampleIndexPair & b) inline private
Definition at line 435 of file sort.hpp.
References SortNode< ValueType, CompareFunction, SortAlgorithm >::compare_function_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::FindAndSendSplitters().
void MainOp () inline private
Definition at line 555 of file sort.hpp.
References DIABase::context_, thrill::common::CreateThread(), FlowControlChannel::ExPrefixSumTotal(), SortNode< ValueType, CompareFunction, SortAlgorithm >::FindAndSendSplitters(), Context::GetNewMixStream(), MixBlockQueueReader::HasNext(), thrill::common::IntegerLog2Ceil(), SortNode< ValueType, CompareFunction, SortAlgorithm >::local_items_, SortNode< ValueType, CompareFunction, SortAlgorithm >::local_out_size_, Context::local_worker_id(), DIABase::logger_, Context::my_rank(), Context::net, Context::num_workers(), SortNode< ValueType, CompareFunction, SortAlgorithm >::ReceiveItems(), SortNode< ValueType, CompareFunction, SortAlgorithm >::samples_, thrill::common::SetCpuAffinity(), sLOG, thrill::common::swap(), SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::use_background_thread_.
size_t MaxMergeDegreePrefetch () inline
Definition at line 189 of file sort.hpp.
References thrill::data::default_block_size, SortNode< ValueType, CompareFunction, SortAlgorithm >::files_, and DIABase::mem_limit_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::PushData().
void PushData (bool consume) inline final virtual
Virtual method for pushing data. Triggers actual pushing in sub-classes.
Implements DIABase.
Definition at line 205 of file sort.hpp.
References SortNode< ValueType, CompareFunction, SortAlgorithm >::compare_function_, DIABase::context_, SortNode< ValueType, CompareFunction, SortAlgorithm >::files_, Context::GetFile(), SortNode< ValueType, CompareFunction, SortAlgorithm >::MaxMergeDegreePrefetch(), Context::PrintCollectiveMeanStdev(), DIANode< ValueType >::PushFile(), DIANode< ValueType >::PushItem(), sLOG1, thrill::data::StartPrefetch(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::stats_enabled.
void ReceiveItems (data::MixStreamPtr & data_stream) inline private
Definition at line 684 of file sort.hpp.
References DIABase::context_, LOG0, DIABase::mem_limit_, thrill::mem::memory_exceeded, Context::PrintCollectiveMeanStdev(), SortNode< ValueType, CompareFunction, SortAlgorithm >::SortAndWriteToFile(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::stats_enabled.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
static size_t RoundDown (Integral n, Integral k) inline static private
round n down by k where k is a power of two.
Definition at line 446 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems().
void SortAndWriteToFile (std::vector< ValueType > & vec) inline private
Definition at line 713 of file sort.hpp.
References BlockPool::AdviseFree(), Context::block_pool(), SortNode< ValueType, CompareFunction, SortAlgorithm >::compare_function_, DIABase::context_, Context::GetFile(), LOG, LOG0, DIABase::logger_, SortNode< ValueType, CompareFunction, SortAlgorithm >::sort_algorithm_, and SortNode< ValueType, CompareFunction, SortAlgorithm >::timer_sort_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::ReceiveItems().
void TransmitItems (const ValueType *const tree, size_t k, size_t log_k, size_t actual_k, const SampleIndexPair *const sorted_splitters, size_t prefix_items, data::MixStreamPtr & data_stream) inline private
Definition at line 450 of file sort.hpp.
References SortNode< ValueType, CompareFunction, SortAlgorithm >::compare_function_, SortNode< ValueType, CompareFunction, SortAlgorithm >::EqualSampleGreaterIndex(), File::GetConsumeReader(), SortNode< ValueType, CompareFunction, SortAlgorithm >::local_items_, BlockReader< BlockSource >::Next(), SortNode< ValueType, CompareFunction, SortAlgorithm >::RoundDown(), thrill::common::swap(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::unsorted_file_.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
size_t wanted_sample_size () const inline private
calculate currently desired number of samples
Definition at line 324 of file sort.hpp.
References DIABase::context_, thrill::common::max(), and Context::num_workers().
Member Data Documentation
CompareFunction compare_function_ private
The comparison function which is applied to two elements.
Definition at line 295 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::EqualSampleGreaterIndex(), SortNode< ValueType, CompareFunction, SortAlgorithm >::LessSampleIndex(), SortNode< ValueType, CompareFunction, SortAlgorithm >::PushData(), SortNode< ValueType, CompareFunction, SortAlgorithm >::SortAndWriteToFile(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems().
constexpr bool debug = false static private
Definition at line 56 of file sort.hpp.
constexpr double desired_imbalance_ = 0.1 static private
epsilon
Definition at line 321 of file sort.hpp.
std::deque<data::File> files_ private
Local data files.
Definition at line 337 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::Dispose(), SortNode< ValueType, CompareFunction, SortAlgorithm >::MaxMergeDegreePrefetch(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::PushData().
size_t local_items_ = 0 private
Number of items on this worker.
Definition at line 311 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems().
size_t local_out_size_ = 0 private
Total number of local elements after communication.
Definition at line 339 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
const bool parent_stack_empty_ private
Whether the parent stack is empty.
Definition at line 301 of file sort.hpp.
std::default_random_engine rng_ { std::random_device { } () } private
Random generator.
Definition at line 318 of file sort.hpp.
size_t sample_interval_ = 1 private
Number of items to process before the next sample was drawn.
Definition at line 316 of file sort.hpp.
std::vector<SampleIndexPair> samples_ private
Sample vector: pairs of (sample,local index)
Definition at line 314 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
SortAlgorithm sort_algorithm_ private
Sort function class.
Definition at line 298 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::SortAndWriteToFile().
constexpr bool stats_enabled = false static private
Set this variable to true to enable generation and output of stats.
Definition at line 59 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::PushData(), and SortNode< ValueType, CompareFunction, SortAlgorithm >::ReceiveItems().
Timer timer_execute_ private
time spent in Execute
Definition at line 350 of file sort.hpp.
Timer timer_preop_ private
time spent in PreOp (including preceding Node's computation)
Definition at line 347 of file sort.hpp.
Timer timer_sort_ private
time spent in sort()
Definition at line 353 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::SortAndWriteToFile().
data::File unsorted_file_ { context_.GetFile(this) } private
All local unsorted items before communication.
Definition at line 307 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::TransmitItems().
data::File::Writer unsorted_writer_ private
Writer for unsorted_file_.
Definition at line 309 of file sort.hpp.
const bool use_background_thread_ = false static private
Definition at line 71 of file sort.hpp.
Referenced by SortNode< ValueType, CompareFunction, SortAlgorithm >::MainOp().
The documentation for this exception was generated from the following file:
thrill/api/sort.hpp