Thrill: Math Functions
Math Functions
tlx - C++ Extensions and Utilities
Classes
class Aggregate< Type_ >
Calculate running aggregate statistics: feed it with values, and it will keep the minimum, the maximum, the average, the value number, and the standard deviation is values.
class PolynomialRegression< Type, WithStore >
Calculate the regression polynomial \(a_0+a_1x^1+a_2x^2+\cdots+a_nx^n \) from a list of 2D points.
Functions
template<typename T >
T abs_diff (const T &a, const T &b)
absolute difference, which also works for unsigned types
static uint16_t bswap16 (const uint16_t &v)
bswap16 - generic
static uint16_t bswap16_generic (const uint16_t &x)
bswap16 - generic implementation
static uint32_t bswap32 (const uint32_t &v)
bswap32 - generic
static uint32_t bswap32_generic (const uint32_t &x)
bswap32 - generic implementation
static uint64_t bswap64 (const uint64_t &v)
bswap64 - generic
static uint64_t bswap64_generic (const uint64_t &x)
bswap64 - generic implementation
template<typename Integral >
unsigned clz (Integral x)
template<>
unsigned clz< int > (int i)
clz (count leading zeros)
template<>
unsigned clz< long > (long i)
clz (count leading zeros)
template<>
unsigned clz< long long > (long long i)
clz (count leading zeros)
template<>
unsigned clz< unsigned > (unsigned i)
clz (count leading zeros)
template<>
unsigned clz< unsigned long > (unsigned long i)
clz (count leading zeros)
template<>
unsigned clz< unsigned long long > (unsigned long long i)
clz (count leading zeros)
template<typename Integral >
static unsigned clz_template (Integral x)
clz (count leading zeros) - generic implementation
template<typename IntegralN , typename IntegralK >
static constexpr auto div_ceil (const IntegralN &n, const IntegralK &k) -> decltype(n+k)
calculate n div k with rounding up
static unsigned ffs (int i)
find first set bit in integer, or zero if none are set.
static unsigned ffs (unsigned int i)
find first set bit in integer, or zero if none are set.
static unsigned ffs (long i)
find first set bit in integer, or zero if none are set.
static unsigned ffs (unsigned long i)
find first set bit in integer, or zero if none are set.
static unsigned ffs (long long i)
find first set bit in integer, or zero if none are set.
static unsigned ffs (unsigned long long i)
find first set bit in integer, or zero if none are set.
template<typename Integral >
static unsigned ffs_template (Integral x)
ffs (find first set bit) - generic implementation
static unsigned integer_log2_ceil (int i)
calculate the log2 floor of an integer type
static unsigned integer_log2_ceil (unsigned int i)
calculate the log2 floor of an integer type
static unsigned integer_log2_ceil (long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_ceil (unsigned long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_ceil (long long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_ceil (unsigned long long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (int i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (unsigned int i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (unsigned long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (long long i)
calculate the log2 floor of an integer type
static unsigned integer_log2_floor (unsigned long long i)
calculate the log2 floor of an integer type
template<typename IntegerType >
static unsigned integer_log2_floor_template (IntegerType i)
calculate the log2 floor of an integer type
static bool is_power_of_two (int i)
does what it says: true if i is a power of two
static bool is_power_of_two (unsigned int i)
does what it says: true if i is a power of two
static bool is_power_of_two (long i)
does what it says: true if i is a power of two
static bool is_power_of_two (unsigned long i)
does what it says: true if i is a power of two
static bool is_power_of_two (long long i)
does what it says: true if i is a power of two
static bool is_power_of_two (unsigned long long i)
does what it says: true if i is a power of two
template<typename Integral >
static bool is_power_of_two_template (Integral i)
template<typename Integral >
unsigned popcount (Integral i)
popcount (count one bits)
static size_t popcount (const void *data, size_t size)
static unsigned popcount_generic16 (uint16_t x)
popcount (count one bits) - generic SWAR implementation
static unsigned popcount_generic32 (uint32_t x)
static unsigned popcount_generic64 (uint64_t x)
popcount (count one bits) - generic SWAR implementation
static unsigned popcount_generic8 (uint8_t x)
popcount (count one bits) - generic SWAR implementation
static uint32_t rol32 (const uint32_t &x, int i)
rol32 - generic
static uint32_t rol32_generic (const uint32_t &x, int i)
rol32 - generic implementation
static uint64_t rol64 (const uint64_t &x, int i)
rol64 - generic
static uint64_t rol64_generic (const uint64_t &x, int i)
rol64 - generic implementation
static uint32_t ror32 (const uint32_t &x, int i)
ror32 - generic
static uint32_t ror32_generic (const uint32_t &x, int i)
ror32 - generic implementation
static uint64_t ror64 (const uint64_t &x, int i)
ror64 - generic
static uint64_t ror64_generic (const uint64_t &x, int i)
ror64 - generic implementation
static int round_down_to_power_of_two (int i)
does what it says: round down to next power of two
static unsigned int round_down_to_power_of_two (unsigned int i)
does what it says: round down to next power of two
static long round_down_to_power_of_two (long i)
does what it says: round down to next power of two
static unsigned long round_down_to_power_of_two (unsigned long i)
does what it says: round down to next power of two
static long long round_down_to_power_of_two (long long i)
does what it says: round down to next power of two
static unsigned long long round_down_to_power_of_two (unsigned long long i)
does what it says: round down to next power of two
static int round_up_to_power_of_two (int i)
does what it says: round up to next power of two
static unsigned int round_up_to_power_of_two (unsigned int i)
does what it says: round up to next power of two
static long round_up_to_power_of_two (long i)
does what it says: round up to next power of two
static unsigned long round_up_to_power_of_two (unsigned long i)
does what it says: round up to next power of two
static long long round_up_to_power_of_two (long long i)
does what it says: round up to next power of two
static unsigned long long round_up_to_power_of_two (unsigned long long i)
does what it says: round up to next power of two
template<typename Integral >
static Integral round_up_to_power_of_two_template (Integral n)
template<typename T >
int sgn (const T &val)
sgn() - signum
Detailed Description
Simple math functions
Function Documentation
T tlx::abs_diff (const T & a, const T & b)
absolute difference, which also works for unsigned types
Definition at line 24 of file abs_diff.hpp.
Referenced by Context::Launch(), and MergeNode< ValueType, Comparator, kNumInputs >::MainOp().
static uint16_t tlx::bswap16 (const uint16_t & v) inline static
bswap16 - generic
Definition at line 52 of file bswap.hpp.
References tlx::bswap16_generic().
static uint16_t tlx::bswap16_generic (const uint16_t & x) inline static
bswap16 - generic implementation
Definition at line 31 of file bswap.hpp.
Referenced by tlx::bswap16().
static uint32_t tlx::bswap32 (const uint32_t & v) inline static
bswap32 - generic
Definition at line 84 of file bswap.hpp.
References tlx::bswap32_generic().
static uint32_t tlx::bswap32_generic (const uint32_t & x) inline static
bswap32 - generic implementation
Definition at line 62 of file bswap.hpp.
Referenced by tlx::bswap32().
static uint64_t tlx::bswap64 (const uint64_t & v) inline static
bswap64 - generic
Definition at line 122 of file bswap.hpp.
References tlx::bswap64_generic().
static uint64_t tlx::bswap64_generic (const uint64_t & x) inline static
bswap64 - generic implementation
Definition at line 94 of file bswap.hpp.
Referenced by tlx::bswap64().
unsigned tlx::clz (Integral x) inline
Referenced by thrill::core::hyperloglog::decodeHash(), thrill::core::hyperloglog::encodeHash(), HyperLogLogRegisters< p >::insert_hash(), and BucketComputation< Radix, ranked_key_type >::operator()().
unsigned tlx::clz< int > (int i) inline
clz (count leading zeros)
Definition at line 105 of file clz.hpp.
References tlx::clz_template().
unsigned tlx::clz< long > (long i) inline
clz (count leading zeros)
Definition at line 117 of file clz.hpp.
References tlx::clz_template().
unsigned tlx::clz< long long > (long long i) inline
clz (count leading zeros)
Definition at line 129 of file clz.hpp.
References tlx::clz_template().
unsigned tlx::clz< unsigned > (unsigned i) inline
clz (count leading zeros)
Definition at line 111 of file clz.hpp.
References tlx::clz_template().
unsigned tlx::clz< unsigned long > (unsigned long i) inline
clz (count leading zeros)
Definition at line 123 of file clz.hpp.
References tlx::clz_template().
unsigned tlx::clz< unsigned long long > (unsigned long long i) inline
clz (count leading zeros)
Definition at line 135 of file clz.hpp.
References tlx::clz_template().
static unsigned tlx::clz_template (Integral x) inline static
clz (count leading zeros) - generic implementation
Definition at line 30 of file clz.hpp.
References gen_data::x.
Referenced by tlx::clz< int >(), tlx::clz< long >(), tlx::clz< long long >(), tlx::clz< unsigned >(), tlx::clz< unsigned long >(), and tlx::clz< unsigned long long >().
static constexpr auto tlx::div_ceil (const IntegralN & n, const IntegralK & k) -> decltype(n + k) inline static
calculate n div k with rounding up
Definition at line 25 of file div_ceil.hpp.
static unsigned tlx::ffs (int i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 79 of file ffs.hpp.
References tlx::ffs_template().
Referenced by Group::BroadcastBinomialTree(), and BitArrayRecursive< Size, true >::find_lsb().
static unsigned tlx::ffs (unsigned int i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 85 of file ffs.hpp.
References tlx::ffs_template().
static unsigned tlx::ffs (long i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 91 of file ffs.hpp.
References tlx::ffs_template().
static unsigned tlx::ffs (unsigned long i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 97 of file ffs.hpp.
References tlx::ffs_template().
static unsigned tlx::ffs (long long i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 103 of file ffs.hpp.
References tlx::ffs_template().
static unsigned tlx::ffs (unsigned long long i) inline static
find first set bit in integer, or zero if none are set.
Definition at line 109 of file ffs.hpp.
References tlx::ffs_template().
static unsigned tlx::ffs_template (Integral x) inline static
ffs (find first set bit) - generic implementation
Definition at line 27 of file ffs.hpp.
Referenced by tlx::ffs().
static unsigned tlx::integer_log2_ceil (int i) inline static
calculate the log2 floor of an integer type
Definition at line 111 of file integer_log2.hpp.
References tlx::integer_log2_floor().
Referenced by Group::AllGatherRecursiveDoublingPowerOfTwo(), examples::suffix_sorting::ConstructWaveletTree(), ConstructWaveletTree(), LocationDetection< thrill::api::JoinNode::HashCount >::Flush(), Sampling< RNG >::hash_sample(), SortNode< ValueType, CompareFunction, SortAlgorithm, Stable >::MainOp(), and examples::suffix_sorting::PrefixDoublingPack().
static unsigned tlx::integer_log2_ceil (unsigned int i) inline static
calculate the log2 floor of an integer type
Definition at line 117 of file integer_log2.hpp.
References tlx::integer_log2_floor().
static unsigned tlx::integer_log2_ceil (long i) inline static
calculate the log2 floor of an integer type
Definition at line 123 of file integer_log2.hpp.
References tlx::integer_log2_floor().
static unsigned tlx::integer_log2_ceil (unsigned long i) inline static
calculate the log2 floor of an integer type
Definition at line 129 of file integer_log2.hpp.
References tlx::integer_log2_floor().
static unsigned tlx::integer_log2_ceil (long long i) inline static
calculate the log2 floor of an integer type
Definition at line 135 of file integer_log2.hpp.
References tlx::integer_log2_floor().
static unsigned tlx::integer_log2_ceil (unsigned long long i) inline static
calculate the log2 floor of an integer type
Definition at line 141 of file integer_log2.hpp.
References tlx::integer_log2_floor().
static unsigned tlx::integer_log2_floor (int i) inline static
calculate the log2 floor of an integer type
Definition at line 76 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
Referenced by tlx::integer_log2_ceil(), and examples::suffix_sorting::PrefixDoublingPack().
static unsigned tlx::integer_log2_floor (unsigned int i) inline static
calculate the log2 floor of an integer type
Definition at line 81 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
static unsigned tlx::integer_log2_floor (long i) inline static
calculate the log2 floor of an integer type
Definition at line 86 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
static unsigned tlx::integer_log2_floor (unsigned long i) inline static
calculate the log2 floor of an integer type
Definition at line 91 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
static unsigned tlx::integer_log2_floor (long long i) inline static
calculate the log2 floor of an integer type
Definition at line 96 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
static unsigned tlx::integer_log2_floor (unsigned long long i) inline static
calculate the log2 floor of an integer type
Definition at line 101 of file integer_log2.hpp.
References tlx::integer_log2_floor_template().
static unsigned tlx::integer_log2_floor_template (IntegerType i) inline static
calculate the log2 floor of an integer type
Definition at line 24 of file integer_log2.hpp.
Referenced by thrill::mem::calc_bin_for_size(), and tlx::integer_log2_floor().
static bool tlx::is_power_of_two (int i) inline static
does what it says: true if i is a power of two
Definition at line 31 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
Referenced by FlowControlChannel::AllGather(), and BlockPool::AllocateByteBlock().
static bool tlx::is_power_of_two (unsigned int i) inline static
does what it says: true if i is a power of two
Definition at line 36 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
static bool tlx::is_power_of_two (long i) inline static
does what it says: true if i is a power of two
Definition at line 41 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
static bool tlx::is_power_of_two (unsigned long i) inline static
does what it says: true if i is a power of two
Definition at line 46 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
static bool tlx::is_power_of_two (long long i) inline static
does what it says: true if i is a power of two
Definition at line 51 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
static bool tlx::is_power_of_two (unsigned long long i) inline static
does what it says: true if i is a power of two
Definition at line 56 of file is_power_of_two.hpp.
References tlx::is_power_of_two_template().
static bool tlx::is_power_of_two_template (Integral i) inline static
Definition at line 22 of file is_power_of_two.hpp.
Referenced by tlx::is_power_of_two().
unsigned tlx::popcount (Integral i) inline
popcount (count one bits)
Definition at line 109 of file popcount.hpp.
References tlx::popcount_generic16(), tlx::popcount_generic32(), tlx::popcount_generic64(), and tlx::popcount_generic8().
Referenced by tlx::popcount().
static size_t tlx::popcount (const void * data, size_t size) inline static
Definition at line 128 of file popcount.hpp.
References tlx::popcount().
static unsigned tlx::popcount_generic16 (uint16_t x) inline static
popcount (count one bits) - generic SWAR implementation
Definition at line 39 of file popcount.hpp.
Referenced by tlx::popcount().
static unsigned tlx::popcount_generic32 (uint32_t x) inline static
popcount (count one bits) - generic SWAR implementation from https://stackoverflow.com/questions/109023
Definition at line 47 of file popcount.hpp.
Referenced by tlx::popcount().
static unsigned tlx::popcount_generic64 (uint64_t x) inline static
popcount (count one bits) - generic SWAR implementation
Definition at line 54 of file popcount.hpp.
Referenced by tlx::popcount().
static unsigned tlx::popcount_generic8 (uint8_t x) inline static
popcount (count one bits) - generic SWAR implementation
Definition at line 32 of file popcount.hpp.
Referenced by tlx::popcount().
static uint32_t tlx::rol32 (const uint32_t & x, int i) inline static
rol32 - generic
Definition at line 55 of file rol.hpp.
References tlx::rol32_generic().
Referenced by tlx::digest_detail::FF(), tlx::digest_detail::GG(), tlx::digest_detail::HH(), tlx::digest_detail::II(), and tlx::digest_detail::sha1_compress().
static uint32_t tlx::rol32_generic (const uint32_t & x, int i) inline static
rol32 - generic implementation
Definition at line 31 of file rol.hpp.
Referenced by tlx::rol32().
static uint64_t tlx::rol64 (const uint64_t & x, int i) inline static
rol64 - generic
Definition at line 89 of file rol.hpp.
References tlx::rol64_generic().
static uint64_t tlx::rol64_generic (const uint64_t & x, int i) inline static
rol64 - generic implementation
Definition at line 65 of file rol.hpp.
Referenced by tlx::rol64().
static uint32_t tlx::ror32 (const uint32_t & x, int i) inline static
ror32 - generic
Definition at line 55 of file ror.hpp.
References tlx::ror32_generic().
static uint32_t tlx::ror32_generic (const uint32_t & x, int i) inline static
ror32 - generic implementation
Definition at line 31 of file ror.hpp.
Referenced by tlx::ror32().
static uint64_t tlx::ror64 (const uint64_t & x, int i) inline static
ror64 - generic
Definition at line 89 of file ror.hpp.
References tlx::ror64_generic().
Referenced by tlx::digest_detail::Gamma0(), tlx::digest_detail::Gamma1(), tlx::digest_detail::Sigma0(), and tlx::digest_detail::Sigma1().
static uint64_t tlx::ror64_generic (const uint64_t & x, int i) inline static
ror64 - generic implementation
Definition at line 65 of file ror.hpp.
Referenced by tlx::ror64().
static int tlx::round_down_to_power_of_two (int i) inline static
does what it says: round down to next power of two
Definition at line 72 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
Referenced by MixStreamData::GetWriters(), and CatStreamData::GetWriters().
static unsigned int tlx::round_down_to_power_of_two (unsigned int i) inline static
does what it says: round down to next power of two
Definition at line 77 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
static long tlx::round_down_to_power_of_two (long i) inline static
does what it says: round down to next power of two
Definition at line 82 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
static unsigned long tlx::round_down_to_power_of_two (unsigned long i) inline static
does what it says: round down to next power of two
Definition at line 87 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
static long long tlx::round_down_to_power_of_two (long long i) inline static
does what it says: round down to next power of two
Definition at line 92 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
static unsigned long long tlx::round_down_to_power_of_two (unsigned long long i) inline static
does what it says: round down to next power of two
Definition at line 98 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two().
static int tlx::round_up_to_power_of_two (int i) inline static
does what it says: round up to next power of two
Definition at line 38 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
Referenced by RingBuffer< Input >::allocate(), Group::BroadcastBinomialTree(), RingBuffer< Input >::load(), tlx::multisequence_partition(), tlx::multisequence_selection(), Multiplexer::OnMultiplexerHeader(), and tlx::round_down_to_power_of_two().
static unsigned int tlx::round_up_to_power_of_two (unsigned int i) inline static
does what it says: round up to next power of two
Definition at line 43 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
static long tlx::round_up_to_power_of_two (long i) inline static
does what it says: round up to next power of two
Definition at line 48 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
static unsigned long tlx::round_up_to_power_of_two (unsigned long i) inline static
does what it says: round up to next power of two
Definition at line 53 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
static long long tlx::round_up_to_power_of_two (long long i) inline static
does what it says: round up to next power of two
Definition at line 58 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
static unsigned long long tlx::round_up_to_power_of_two (unsigned long long i) inline static
does what it says: round up to next power of two
Definition at line 64 of file round_to_power_of_two.hpp.
References tlx::round_up_to_power_of_two_template().
static Integral tlx::round_up_to_power_of_two_template (Integral n) inline static
Definition at line 25 of file round_to_power_of_two.hpp.
Referenced by tlx::round_up_to_power_of_two().
int tlx::sgn (const T & val)
sgn() - signum
return the signum (-1, 0, +1) of a value.
Definition at line 26 of file sgn.hpp.