Thrill: Common Utilities and Support Classes
Common Utilities and Support Classes
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management
Supporting classes also useful for applications.
Classes
class fake_timer
Class fake_timer is a drop-in replacement for timer, which does nothing.
class scoped_print_timer
Simple scoped timer, which takes a text message and prints the duration until the scope is destroyed.
class timer
Class timer is a simple stop watch timer.
Typedefs
using uint40 = uint_pair< uint8_t >
Construct a 40-bit unsigned integer stored in five bytes.
using uint48 = uint_pair< uint16_t >
Construct a 48-bit unsigned integer stored in six bytes.
Functions
static double timestamp ()
Returns number of seconds since the epoch, high resolution.
Detailed Description
Supporting classes also useful for applications.
Typedef Documentation
uint40
using uint40 = uint_pair<uint8_t>
Construct a 40-bit unsigned integer stored in five bytes.
Definition at line 260 of file uint_types.hpp.
uint48
using uint48 = uint_pair<uint16_t>
Construct a 48-bit unsigned integer stored in six bytes.
Definition at line 263 of file uint_types.hpp.
Function Documentation
timestamp()
static double foxxll::timestamp () inline static
Returns number of seconds since the epoch, high resolution.
Definition at line 36 of file timer.hpp.
Referenced by file_stats::read_finished(), file_stats::read_started(), timer::timestamp(), stats::wait_finished(), stats::wait_started(), file_stats::write_finished(), and file_stats::write_started().