Thrill: MPI Network API
MPI Network API
Thrill Layers » Network Subsystem Layer
Classes
class AsyncRequest
class Connection
Virtual MPI connection class.
class Dispatcher
class Exception
A derived exception class which looks up MPI error strings.
class Group
A net group backed by virtual MPI connection.
Macros
#define THRILL_NET_MPI_QUEUES 1
Typedefs
using AsyncRequestCallback = tlx::delegate< void(MPI_Status &), mem::GPoolAllocator< char > >
Signature of async MPI request callbacks.
Functions
bool Construct (size_t group_size, DispatcherThread &dispatcher, std::unique_ptr< Group > *groups, size_t group_count)
Construct Group which connects to peers using MPI.
size_t MpiRank ()
Return the rank of this process in the MPI COMM WORLD.
size_t NumMpiProcesses ()
Return the number of MPI processes.
Detailed Description
Macro Definition Documentation
THRILL_NET_MPI_QUEUES
#define THRILL_NET_MPI_QUEUES 1
Definition at line 37 of file dispatcher.hpp.
Typedef Documentation
AsyncRequestCallback
using AsyncRequestCallback = tlx::delegate< void (MPI_Status&), mem::GPoolAllocator<char> >
Signature of async MPI request callbacks.
Definition at line 41 of file dispatcher.hpp.
Function Documentation
Construct()
bool Construct (size_t group_size, DispatcherThread & dispatcher, std::unique_ptr< Group > * groups, size_t group_count)
Construct Group which connects to peers using MPI.
As the MPI environment already defines the connections, no hosts or parameters can be given. Constructs group_count mpi::Group objects at once. Within each Group this host has its MPI rank.
Returns true if this Thrill host participates in the Group.
As the MPI environment already defines the connections, no hosts or parameters can be given. Constructs group_count mpi::Group objects at once. Within each Group this host has its MPI rank.
To enable tests with smaller group sizes, the Construct method takes group_size and returns a Group with less hosts than actual MPI processes! Obviously, group_size must be less-or-equal to the number of processes started with mpirun -np.
Definition at line 675 of file group.cpp.
References Exception::Exception(), and thrill::net::mpi::Initialize().
Referenced by thrill::api::RunBackendLoopback().
MpiRank()
size_t MpiRank ()
Return the rank of this process in the MPI COMM WORLD.
Definition at line 714 of file group.cpp.
References Exception::Exception(), and thrill::net::mpi::Initialize().
Referenced by thrill::api::RunBackendLoopback().
NumMpiProcesses()
size_t NumMpiProcesses ()
Return the number of MPI processes.
This is the maximum group size.
Definition at line 701 of file group.cpp.
References Exception::Exception(), and thrill::net::mpi::Initialize().
Referenced by thrill::api::RunBackendLoopback().