Thrill: TCP Socket API
TCP Socket API
Thrill Layers » Network Subsystem Layer
Classes
class Connection
Connection is a rich point-to-point socket connection to another client (worker, master, or whatever).
class Group
Collection of NetConnections to workers, allows point-to-point client communication and simple collectives like MPI.
class IPv4Address
IPv4 Subclass of SocketAddress for direct initialization from a known IPv4 address, known either in binary format, numerals, or as "ddd.ddd.ddd.ddd" format.
class IPv6Address
IPv6 Subclass of SocketAddress for direct initialization from a known IPv6 address, known either in binary format, numerals, or in some IPv6 format.
class Select
Select is an object-oriented wrapper for select().
class SelectDispatcher
SelectDispatcher is a higher level wrapper for select().
class Socket
Socket is a light-weight wrapper around the BSD socket API.
class SocketAddress
SocketAddress is a super class used to unify the two different IPv4 and IPv6 socket address representation.
Macros
#define MSG_MORE 0
Enumerations
enum ConnectionState : unsigned {
Invalid, Connecting, TransportConnected, HelloReceived,
HelloSent, WaitingForHello, Connected, Disconnected
}
Functions
void Construct (SelectDispatcher &dispatcher, size_t my_rank, const std::vector< std::string > &endpoints, std::unique_ptr< Group > *groups, size_t group_count)
std::vector< std::unique_ptr< net::Group > > Construct (SelectDispatcher &dispatcher, size_t my_rank, const std::vector< std::string > &endpoints, size_t group_count)
Detailed Description
Macro Definition Documentation
MSG_MORE
#define MSG_MORE 0
Definition at line 42 of file connection.hpp.
Referenced by Connection::SendOne(), and Connection::SyncSend().
Enumeration Type Documentation
ConnectionState
enum ConnectionState : unsigned
Enumerator
Invalid
Connecting
TransportConnected
HelloReceived
HelloSent
WaitingForHello
Connected
Disconnected
Definition at line 35 of file connection.hpp.
Function Documentation
Construct() [1/2]
void Construct (SelectDispatcher & dispatcher, size_t my_rank, const std::vector< std::string > & endpoints, std::unique_ptr< Group > * groups, size_t group_count)
Connect to peers via endpoints using TCP sockets. Construct a group_count tcp::Group objects at once. Within each Group this host has my_rank.
Definition at line 543 of file construct.cpp.
Referenced by Group::ConstructLocalRealTCPMesh(), and thrill::api::RunBackendLoopback().
Construct() [2/2]
std::vector< std::unique_ptr< net::Group > > Construct (SelectDispatcher & dispatcher, size_t my_rank, const std::vector< std::string > & endpoints, size_t group_count)
Connect to peers via endpoints using TCP sockets. Construct a group_count net::Group objects at once. Within each Group this host has my_rank.
Definition at line 553 of file construct.cpp.
References thrill::api::Initialize().