Thrill: I/O Primitives Layer
I/O Primitives Layer
Thrill Layers » foxxll - A C++ Library for Asynchronous I/O and Block Management
Group of classes which enable abstraction from operating system calls and support system-independent interfaces for asynchronous I/O.
Modules
File I/O Implementations
I/O Requests and Queues
Classes
class file_stats
class file_stats_data
class scoped_print_iostats
Simple scoped iostats reporter which takes a message and reports the relative IO performance on destruction.
class stats
class stats_data
Functions
static std::string add_IEC_binary_multiplier (const external_size_type number, const std::string &unit="")
static std::string add_SI_multiplier (external_size_type number, const std::string &unit="")
Detailed Description
Group of classes which enable abstraction from operating system calls and support system-independent interfaces for asynchronous I/O.
Function Documentation
add_IEC_binary_multiplier()
static std::string foxxll::add_IEC_binary_multiplier (const external_size_type number, const std::string & unit = "") inline static
Definition at line 643 of file iostats.hpp.
References tlx::format_iec_units().
Referenced by stats_data::to_ostream().
add_SI_multiplier()
static std::string foxxll::add_SI_multiplier (external_size_type number, const std::string & unit = "") inline static
Definition at line 650 of file iostats.hpp.
References tlx::format_si_units().