Thrill: Asynchronous I/O Layer
Asynchronous I/O Layer
Thrill Layers
Modules
Disk Allocation Functors
File I/O Implementations
I/O Requests and Queues
Internals
Namespaces
thrill::io::mng_local
Block Manager Internals.
Classes
class BID< Size >
class BID< 0 >
class BlockManager
class Config
class DiskAllocator
class DiskConfig
class Stats
Collects various I/O statistics.
class StatsData
class TypedBlock< RawSize, Type, NRef, MetaInfoType >
Macros
#define THRILL_DEFAULT_BLOCK_SIZE(type) (2 * 1024 * 1024)
Typedefs
template<size_t BlockSize>
using BIDArray = std::vector< BID< BlockSize > >
Functions
template<size_t BlockSize>
void delete_block (const BID< BlockSize > &bid)
template<typename BIDType , typename DiskAssignFunctor , typename OutputIterator >
void new_blocks_int (const size_t nblocks, const DiskAssignFunctor &functor, size_t offset, OutputIterator out)
template<size_t BlockSize>
std::ostream & operator<< (std::ostream &s, const BID< BlockSize > &bid)
std::ostream & operator<< (std::ostream &o, const StatsData &s)
std::ostream & operator<< (std::ostream &o, const Stats &s)
static double timestamp ()
Returns number of seconds since the epoch, high resolution.
void wait_finished (WaitOp wait_op)
void wait_started (WaitOp wait_op)
Detailed Description
Macro Definition Documentation
#define THRILL_DEFAULT_BLOCK_SIZE (type) (2 * 1024 * 1024)
Definition at line 240 of file block_manager.hpp.
Typedef Documentation
using BIDArray = std::vector<BID<BlockSize> >
Definition at line 129 of file bid.hpp.
Function Documentation
void delete_block (const BID< BlockSize > & bid)
Deallocates a block.
Parameters
bid block identifier
Definition at line 220 of file block_manager.hpp.
References BlockManager::current_allocation_, BlockManager::disk_allocators_, BlockManager::disk_files_, BID< Size >::is_managed(), LOG0, BlockManager::mutex_, and BID< Size >::valid().
Referenced by BlockManager::delete_blocks().
void new_blocks_int (const size_t nblocks, const DiskAssignFunctor & functor, size_t offset, OutputIterator out)
Definition at line 181 of file block_manager.hpp.
References BlockManager::current_allocation_, BlockManager::disk_allocators_, BlockManager::disk_files_, DiskAllocator::free_bytes(), FileBase::get_allocator_id(), LOG0, thrill::common::max(), BlockManager::maximum_allocation_, BlockManager::mutex_, DiskAllocator::NewBlocks(), and BlockManager::total_allocation_.
std::ostream & operator<< (std::ostream & s, const BID< BlockSize > & bid)
Definition at line 27 of file bid.cpp.
std::ostream & operator<< (std::ostream & o, const StatsData & s)
Definition at line 228 of file iostats.cpp.
References StatsData::cached_read_ops(), StatsData::cached_read_volume(), StatsData::cached_write_ops(), StatsData::cached_write_volume(), StatsData::elapsed_time(), hr, StatsData::io_wait_time(), StatsData::parallel_io_time(), StatsData::parallel_read_time(), StatsData::parallel_write_time(), StatsData::read_ops(), StatsData::read_time(), StatsData::read_volume(), StatsData::read_wait_time(), StatsData::write_ops(), StatsData::write_time(), StatsData::write_volume(), and StatsData::write_wait_time().
std::ostream& thrill::io::operator<< (std::ostream & o, const Stats & s) inline
Definition at line 470 of file iostats.hpp.
static double thrill::io::timestamp () inline static
Returns number of seconds since the epoch, high resolution.
Definition at line 45 of file iostats.hpp.
Referenced by LinuxaioRequest::post(), Stats::read_finished(), Stats::read_started(), Stats::wait_finished(), Stats::wait_started(), Stats::write_finished(), and Stats::write_started().
void wait_finished (WaitOp wait_op) inline
Definition at line 194 of file iostats.cpp.
References Stats::io_wait_time_, Stats::last_reset_time_, Stats::READ, Stats::read_wait_time_, thrill::io::timestamp(), Stats::wait_mutex_, and Stats::write_wait_time_.
void wait_started (WaitOp wait_op) inline
Definition at line 168 of file iostats.cpp.
References Stats::io_wait_time_, Stats::READ, Stats::read_wait_time_, thrill::io::timestamp(), Stats::wait_mutex_, and Stats::write_wait_time_.