Thrill: Message Digests
Message Digests
Thrill Layers » tlx - C++ Extensions and Utilities
Classes
class MD5
MD-5 processor without external dependencies.
class SHA1
SHA-1 processor without external dependencies.
class SHA256
SHA-256 processor without external dependencies.
class SHA512
SHA-512 processor without external dependencies.
Functions
std::string md5_hex (const void *data, uint32_t size)
process data and return 16 byte (128 bit) digest hex encoded
std::string md5_hex (const std::string &str)
process data and return 16 byte (128 bit) digest hex encoded
std::string md5_hex_uc (const void *data, uint32_t size)
process data and return 16 byte (128 bit) digest upper-case hex encoded
std::string md5_hex_uc (const std::string &str)
process data and return 16 byte (128 bit) digest upper-case hex encoded
std::string sha1_hex (const void *data, uint32_t size)
process data and return 20 byte (160 bit) digest hex encoded
std::string sha1_hex (const std::string &str)
process data and return 20 byte (160 bit) digest hex encoded
std::string sha1_hex_uc (const void *data, uint32_t size)
process data and return 20 byte (160 bit) digest upper-case hex encoded
std::string sha1_hex_uc (const std::string &str)
process data and return 20 byte (160 bit) digest upper-case hex encoded
std::string sha256_hex (const void *data, uint32_t size)
process data and return 32 byte (256 bit) digest hex encoded
std::string sha256_hex (const std::string &str)
process data and return 32 byte (256 bit) digest hex encoded
std::string sha256_hex_uc (const void *data, uint32_t size)
process data and return 32 byte (256 bit) digest upper-case hex encoded
std::string sha256_hex_uc (const std::string &str)
process data and return 32 byte (256 bit) digest upper-case hex encoded
std::string sha512_hex (const void *data, uint32_t size)
process data and return 64 byte (512 bit) digest hex encoded
std::string sha512_hex (const std::string &str)
process data and return 64 byte (512 bit) digest hex encoded
std::string sha512_hex_uc (const void *data, uint32_t size)
process data and return 64 byte (512 bit) digest upper-case hex encoded
std::string sha512_hex_uc (const std::string &str)
process data and return 64 byte (512 bit) digest upper-case hex encoded
Detailed Description
Message Digests: MD-5, SHA-256, and SHA-512.
Function Documentation
md5_hex() [1/2]
std::string md5_hex (const void * data, uint32_t size)
process data and return 16 byte (128 bit) digest hex encoded
Definition at line 271 of file md5.cpp.
References MD5::MD5().
md5_hex() [2/2]
std::string md5_hex (const std::string & str)
process data and return 16 byte (128 bit) digest hex encoded
Definition at line 275 of file md5.cpp.
References MD5::MD5().
md5_hex_uc() [1/2]
std::string md5_hex_uc (const void * data, uint32_t size)
process data and return 16 byte (128 bit) digest upper-case hex encoded
Definition at line 279 of file md5.cpp.
References MD5::MD5().
md5_hex_uc() [2/2]
std::string md5_hex_uc (const std::string & str)
process data and return 16 byte (128 bit) digest upper-case hex encoded
Definition at line 283 of file md5.cpp.
References MD5::MD5().
sha1_hex() [1/2]
std::string sha1_hex (const void * data, uint32_t size)
process data and return 20 byte (160 bit) digest hex encoded
Definition at line 222 of file sha1.cpp.
References SHA1::SHA1().
sha1_hex() [2/2]
std::string sha1_hex (const std::string & str)
process data and return 20 byte (160 bit) digest hex encoded
Definition at line 226 of file sha1.cpp.
References SHA1::SHA1().
sha1_hex_uc() [1/2]
std::string sha1_hex_uc (const void * data, uint32_t size)
process data and return 20 byte (160 bit) digest upper-case hex encoded
Definition at line 230 of file sha1.cpp.
References SHA1::SHA1().
sha1_hex_uc() [2/2]
std::string sha1_hex_uc (const std::string & str)
process data and return 20 byte (160 bit) digest upper-case hex encoded
Definition at line 234 of file sha1.cpp.
References SHA1::SHA1().
sha256_hex() [1/2]
std::string sha256_hex (const void * data, uint32_t size)
process data and return 32 byte (256 bit) digest hex encoded
Definition at line 238 of file sha256.cpp.
References SHA256::SHA256().
sha256_hex() [2/2]
std::string sha256_hex (const std::string & str)
process data and return 32 byte (256 bit) digest hex encoded
Definition at line 242 of file sha256.cpp.
References SHA256::SHA256().
sha256_hex_uc() [1/2]
std::string sha256_hex_uc (const void * data, uint32_t size)
process data and return 32 byte (256 bit) digest upper-case hex encoded
Definition at line 246 of file sha256.cpp.
References SHA256::SHA256().
sha256_hex_uc() [2/2]
std::string sha256_hex_uc (const std::string & str)
process data and return 32 byte (256 bit) digest upper-case hex encoded
Definition at line 250 of file sha256.cpp.
References SHA256::SHA256().
sha512_hex() [1/2]
std::string sha512_hex (const void * data, uint32_t size)
process data and return 64 byte (512 bit) digest hex encoded
Definition at line 257 of file sha512.cpp.
References SHA512::SHA512().
sha512_hex() [2/2]
std::string sha512_hex (const std::string & str)
process data and return 64 byte (512 bit) digest hex encoded
Definition at line 261 of file sha512.cpp.
References SHA512::SHA512().
sha512_hex_uc() [1/2]
std::string sha512_hex_uc (const void * data, uint32_t size)
process data and return 64 byte (512 bit) digest upper-case hex encoded
Definition at line 265 of file sha512.cpp.
References SHA512::SHA512().
sha512_hex_uc() [2/2]
std::string sha512_hex_uc (const std::string & str)
process data and return 64 byte (512 bit) digest upper-case hex encoded
Definition at line 269 of file sha512.cpp.
References SHA512::SHA512().