Thrill: examples/logistic_regression/logistic_regression.cpp File Reference
logistic_regression.cpp File Reference
#include <thrill/api/cache.hpp>
#include <thrill/api/dia.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/api/print.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/common/cmdline_parser.hpp>
#include <thrill/common/logger.hpp>
#include <thrill/common/string.hpp>
#include <array>
#include <random>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "logistic_regression.hpp"
Macros
#define LOGM LOGC(debug && ctx.my_rank() == 0)
Typedefs
using DataObject = std::pair< bool, Element >
using Element = std::array< T, dim >
using T = double
Functions
static auto GenerateInput (api::Context &ctx, size_t size)
static auto GenerateTestData (api::Context &ctx, size_t size)
int main (int argc, char *argv[])
template<typename Input >
static auto ReadInputFile (api::Context &ctx, const Input &input_path)
template<typename InputDIA >
void TestLogit (api::Context &ctx, const std::string &test_file, const InputDIA &input_dia, const Element &weights)
template<typename InputDIA >
auto TrainLogit (api::Context &ctx, const InputDIA &input_dia, size_t max_iterations, double gamma, double epsilon)
Variables
constexpr size_t dim = 3
Macro Definition Documentation
#define LOGM LOGC(debug && ctx.my_rank() == 0)
Definition at line 39 of file logistic_regression.cpp.
Referenced by TestLogit(), and TrainLogit().
Typedef Documentation
using DataObject = std::pair<bool, Element>
Definition at line 37 of file logistic_regression.cpp.
using Element = std::array<T, dim>
Definition at line 36 of file logistic_regression.cpp.
using T = double
Definition at line 34 of file logistic_regression.cpp.
Function Documentation
static auto GenerateInput (api::Context & ctx, size_t size) static
Definition at line 66 of file logistic_regression.cpp.
References thrill::api::Generate().
Referenced by main().
static auto GenerateTestData (api::Context & ctx, size_t size) static
Definition at line 89 of file logistic_regression.cpp.
References thrill::api::Generate().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 145 of file logistic_regression.cpp.
References CmdlineParser::AddDouble(), CmdlineParser::AddFlag(), CmdlineParser::AddParamString(), CmdlineParser::AddParamStringlist(), CmdlineParser::AddSizeT(), Context::enable_consume(), GenerateInput(), GenerateTestData(), CmdlineParser::PrintResult(), CmdlineParser::Process(), ReadInputFile(), thrill::api::Run(), TestLogit(), and TrainLogit().
static auto ReadInputFile (api::Context & ctx, const Input & input_path) static
Definition at line 42 of file logistic_regression.cpp.
References die_unless, dim, and thrill::api::ReadLines().
Referenced by main().
void TestLogit (api::Context & ctx, const std::string & test_file, const InputDIA & input_dia, const Element & weights)
Definition at line 131 of file logistic_regression.cpp.
References LOGM.
Referenced by main().
auto TrainLogit (api::Context & ctx, const InputDIA & input_dia, size_t max_iterations, double gamma, double epsilon)
Definition at line 111 of file logistic_regression.cpp.
References dim, and LOGM.
Referenced by main().
Variable Documentation
constexpr size_t dim = 3
Definition at line 33 of file logistic_regression.cpp.
Referenced by examples::logistic_regression::calc_norm(), examples::logistic_regression::gradient(), ReadInputFile(), and TrainLogit().