Thrill: examples::select Namespace Reference
examples::select Namespace Reference
Functions
template<typename ValueType , typename InStack , typename Compare = std::less<ValueType>>
std::pair< ValueType, ValueType > PickPivots (const DIA< ValueType, InStack > &data, size_t size, size_t rank, const Compare &compare=Compare())
template<typename ValueType , typename InStack , typename Compare = std::less<ValueType>>
ValueType Select (const DIA< ValueType, InStack > &data, size_t rank, const Compare &compare=Compare())
Variables
static constexpr size_t base_case_size = 1024
static constexpr bool debug = false
static constexpr double delta = 0.1
Function Documentation
PickPivots()
std::pair<ValueType, ValueType> examples::select::PickPivots (const DIA< ValueType, InStack > & data, size_t size, size_t rank, const Compare & compare = Compare())
Definition at line 44 of file select.hpp.
References DIA< ValueType_, Stack_ >::BernoulliSample(), FlowControlChannel::Broadcast(), DIA< ValueType_, Stack_ >::context(), DIA< ValueType_, Stack_ >::Keep(), LOG, LOGM, max(), min(), Context::my_rank(), Context::net, and Context::num_workers().
Referenced by Select().
Select()
ValueType examples::select::Select (const DIA< ValueType, InStack > & data, size_t rank, const Compare & compare = Compare())
Definition at line 91 of file select.hpp.
References FlowControlChannel::Broadcast(), DIA< ValueType_, Stack_ >::context(), DIA< ValueType_, Stack_ >::Filter(), DIA< ValueType_, Stack_ >::Gather(), DIA< ValueType_, Stack_ >::Keep(), LOG, LOGM, DIA< ValueType_, Stack_ >::Map(), Context::my_rank(), Context::net, PickPivots(), and DIA< ValueType_, Stack_ >::Size().
Referenced by RunSelect().
Variable Documentation
base_case_size
constexpr size_t base_case_size = 1024 static
Definition at line 37 of file select.hpp.
debug
constexpr bool debug = false static
Definition at line 33 of file select.hpp.
delta
constexpr double delta = 0.1 static
Definition at line 35 of file select.hpp.
Referenced by Aggregate< Type_ >::add(), Aggregate< Type_ >::combine_variance(), timer::operator+=(), timer::seconds(), Semaphore::signal(), timer::stop(), Semaphore::try_acquire(), timer::useconds(), and Semaphore::wait().