Thrill: tlx::detail Namespace Reference
tlx::detail Namespace Reference
Meta-Template Programming
Classes
class CallForRangeImpl
helper for call_for_range: general recursive case
class CallForRangeImpl< Index, 0, Functor >
helper for call_for_range: base case
struct make_index_sequence_helper
struct make_index_sequence_helper< 0, Indexes...>
class VMapForRangeImpl
helper for vmap_for_range: general recursive case
class VMapForRangeImpl< Index, 0, Functor >
helper for vmap_for_range: base case
Functions
template<typename Functor , typename Tuple , std::size_t... Is>
auto apply_tuple_impl (Functor &&f, Tuple &&t, index_sequence< Is...>)
static auto call_chain ()
Base case for the chaining of functors: zero functors, returns the identity.
template<typename Functor >
auto call_chain (const Functor &functor)
Base case for the chaining of functors.
template<typename Functor , typename... MoreFunctors>
auto call_chain (const Functor &functor, const MoreFunctors &...rest)
Recursive case for the chaining of functors.
template<typename Functor , typename Arg >
void call_foreach_impl (Functor &&f, Arg &&arg)
helper for call_foreach: base case
template<typename Functor , typename Arg , typename... MoreArgs>
void call_foreach_impl (Functor &&f, Arg &&arg, MoreArgs &&...rest)
helper for call_foreach: general recursive case
template<typename Functor , typename Tuple , std::size_t... Is>
void call_foreach_tuple_impl (Functor &&f, Tuple &&t, index_sequence< Is...>)
helper for call_foreach_tuple
template<typename Functor , typename Tuple , std::size_t... Is>
void call_foreach_tuple_with_index_impl (Functor &&f, Tuple &&t, index_sequence< Is...>)
helper for call_foreach_tuple_with_index
template<size_t Index, typename Functor , typename Arg >
void call_foreach_with_index_impl (Functor &&f, Arg &&arg)
helper for call_foreach_with_index: base case
template<size_t Index, typename Functor , typename Arg , typename... MoreArgs>
void call_foreach_with_index_impl (Functor &&f, Arg &&arg, MoreArgs &&...rest)
helper for call_foreach_with_index: general recursive case
template<typename Functor >
auto call_stack (const Functor &functor)
Base case for the chaining of functors.
template<typename Functor , typename... MoreFunctors>
auto call_stack (const Functor &functor, const MoreFunctors &...rest)
Recursive case for the chaining of functors.
template<typename Functor , typename Arg >
auto vmap_foreach_impl (Functor &&f, Arg &&arg)
helper for vmap_foreach: base case
template<typename Functor , typename Arg , typename... MoreArgs>
auto vmap_foreach_impl (Functor &&f, Arg &&arg, MoreArgs &&...rest)
helper for vmap_foreach: general recursive case
template<size_t Index, typename Functor , typename Arg >
auto vmap_foreach_with_index_impl (Functor &&f, Arg &&arg)
helper for vmap_foreach_with_index: base case
template<size_t Index, typename Functor , typename Arg , typename... MoreArgs>
auto vmap_foreach_with_index_impl (Functor &&f, Arg &&arg, MoreArgs &&...rest)
helper for vmap_foreach_with_index: general recursive case
Function Documentation
auto tlx::detail::apply_tuple_impl (Functor && f, Tuple && t, index_sequence< Is...>)
Definition at line 30 of file apply_tuple.hpp.
Referenced by tlx::apply_tuple().
static auto tlx::detail::call_chain () inline static
Base case for the chaining of functors: zero functors, returns the identity.
Definition at line 34 of file function_chain.hpp.
auto tlx::detail::call_chain (const Functor & functor)
Base case for the chaining of functors.
The one functor receives an input element
Parameters
functor functor that represents the chain end.
Definition at line 47 of file function_chain.hpp.
auto tlx::detail::call_chain (const Functor & functor, const MoreFunctors &... rest)
Recursive case for the chaining of functors.
The first functor receives an input element, and the remaining chain is applied to the result.
Parameters
functor Current functor to be chained.
rest Remaining functors.
Definition at line 64 of file function_chain.hpp.
Referenced by FunctionChain< Functors >::fold_chain().
void tlx::detail::call_foreach_impl (Functor && f, Arg && arg)
helper for call_foreach: base case
Definition at line 29 of file call_foreach.hpp.
Referenced by tlx::call_foreach(), and call_foreach_impl().
void tlx::detail::call_foreach_impl (Functor && f, Arg && arg, MoreArgs &&... rest)
helper for call_foreach: general recursive case
Definition at line 35 of file call_foreach.hpp.
References call_foreach_impl().
void tlx::detail::call_foreach_tuple_impl (Functor && f, Tuple && t, index_sequence< Is...>)
helper for call_foreach_tuple
Definition at line 34 of file call_foreach_tuple.hpp.
References tlx::call_foreach().
Referenced by tlx::call_foreach_tuple().
void tlx::detail::call_foreach_tuple_with_index_impl (Functor && f, Tuple && t, index_sequence< Is...>)
helper for call_foreach_tuple_with_index
Definition at line 34 of file call_foreach_tuple_with_index.hpp.
References tlx::call_foreach_with_index().
Referenced by tlx::call_foreach_tuple_with_index().
void tlx::detail::call_foreach_with_index_impl (Functor && f, Arg && arg)
helper for call_foreach_with_index: base case
Definition at line 33 of file call_foreach_with_index.hpp.
void tlx::detail::call_foreach_with_index_impl (Functor && f, Arg && arg, MoreArgs &&... rest)
helper for call_foreach_with_index: general recursive case
Definition at line 39 of file call_foreach_with_index.hpp.
auto tlx::detail::call_stack (const Functor & functor)
Base case for the chaining of functors.
The last functor receives an input element, no emitter and should have no return type. It should therefore store the input parameter externally.
Parameters
functor Functor that represents the chain end.
Definition at line 42 of file function_stack.hpp.
auto tlx::detail::call_stack (const Functor & functor, const MoreFunctors &... rest)
Recursive case for the chaining of functors.
The given functor receives an input element, an emitter and should have no return type. The emitter will be built using the chain of remaining functors.
Parameters
functor Current functor to be chained.
rest Remaining functors.
Definition at line 61 of file function_stack.hpp.
Referenced by FunctionStack< Input_, Functors >::fold_stack().
auto tlx::detail::vmap_foreach_impl (Functor && f, Arg && arg)
helper for vmap_foreach: base case
Definition at line 31 of file vmap_foreach.hpp.
Referenced by tlx::vmap_foreach(), and vmap_foreach_impl().
auto tlx::detail::vmap_foreach_impl (Functor && f, Arg && arg, MoreArgs &&... rest)
helper for vmap_foreach: general recursive case
Definition at line 38 of file vmap_foreach.hpp.
References vmap_foreach_impl(), and gen_data::x.
auto tlx::detail::vmap_foreach_with_index_impl (Functor && f, Arg && arg)
helper for vmap_foreach_with_index: base case
Definition at line 35 of file vmap_foreach_with_index.hpp.
auto tlx::detail::vmap_foreach_with_index_impl (Functor && f, Arg && arg, MoreArgs &&... rest)
helper for vmap_foreach_with_index: general recursive case
Definition at line 42 of file vmap_foreach_with_index.hpp.
References gen_data::x.