Thrill: examples::bfs Namespace Reference
examples::bfs Namespace Reference
Classes
class BfsNode
struct NodeParentPair
struct TreeInfo
Typedefs
using EdgeList = std::vector< VertexId >
using VertexId = size_t
Functions
std::ostream & operator<< (std::ostream &os, const NodeParentPair &pair)
std::ostream & operator<< (std::ostream &os, const BfsNode &node)
Variables
const size_t INVALID = std::numeric_limits<size_t>::max()
Typedef Documentation
EdgeList
using EdgeList = std::vector<VertexId>
Definition at line 26 of file bfs.hpp.
VertexId
using VertexId = size_t
Definition at line 25 of file bfs.hpp.
Function Documentation
operator<<() [1/2]
std::ostream& examples::bfs::operator<< (std::ostream & os, const NodeParentPair & pair)
Definition at line 33 of file bfs.hpp.
References NodeParentPair::node, and NodeParentPair::parent.
operator<<() [2/2]
std::ostream& examples::bfs::operator<< (std::ostream & os, const BfsNode & node)
Definition at line 54 of file bfs.hpp.
References BfsNode::edges, BfsNode::level, BfsNode::nodeIndex, BfsNode::parent, and BfsNode::treeIndex.
Variable Documentation
INVALID
const size_t INVALID = std::numeric_limits<size_t>::max()
Definition at line 24 of file bfs.hpp.
Referenced by BFSNextLevel(), doubleSweepDiameter(), outputBFSResult(), and PrepareNextTree().