Thrill: examples::page_rank Namespace Reference
examples::page_rank Namespace Reference
Classes
struct PagePageLink
A pair (page source, page target)
struct PageRankPair
A pair (page, rank)
class ZipfGraphGen
Typedefs
using LinkedPage = std::pair< PageId, OutgoingLinks >
using OutgoingLinks = std::vector< PageId >
using OutgoingLinksRank = std::pair< std::vector< PageId >, Rank >
using PageId = std::size_t
using PageRankStdPair = std::pair< PageId, Rank >
using Rank = double
using RankedPage = std::pair< PageId, Rank >
Functions
template<typename InStack >
auto PageRank (const DIA< OutgoingLinks, InStack > &links, size_t num_pages, size_t iterations)
template<const bool UseLocationDetection = false, typename InStack >
auto PageRankJoin (const DIA< LinkedPage, InStack > &links, size_t num_pages, size_t iterations)
Variables
static constexpr double dampening = 0.85
static constexpr bool debug = false
struct examples::page_rank::PagePageLink TLX_ATTRIBUTE_PACKED
Typedef Documentation
LinkedPage
using LinkedPage = std::pair<PageId, OutgoingLinks>
Definition at line 67 of file page_rank.hpp.
OutgoingLinks
using OutgoingLinks = std::vector<PageId>
Definition at line 65 of file page_rank.hpp.
OutgoingLinksRank
using OutgoingLinksRank = std::pair<std::vector<PageId>, Rank>
Definition at line 66 of file page_rank.hpp.
PageId
using PageId = std::size_t
Definition at line 42 of file page_rank.hpp.
PageRankStdPair
using PageRankStdPair = std::pair<PageId, Rank>
Definition at line 64 of file page_rank.hpp.
Rank
using Rank = double
Definition at line 43 of file page_rank.hpp.
RankedPage
using RankedPage = std::pair<PageId, Rank>
Definition at line 68 of file page_rank.hpp.
Function Documentation
PageRank()
auto examples::page_rank::PageRank (const DIA< OutgoingLinks, InStack > & links, size_t num_pages, size_t iterations)
Definition at line 71 of file page_rank.hpp.
References DIA< ValueType_, Stack_ >::context(), dampening, thrill::api::Generate(), tlx::join(), PageRankPair::page, PageRankPair::rank, DIA< ValueType_, Stack_ >::ReduceToIndex(), thrill::mem::to_string(), and DIA< ValueType_, Stack_ >::Zip().
Referenced by RunPageRankEdgePerLine(), and RunPageRankGenerated().
PageRankJoin()
auto examples::page_rank::PageRankJoin (const DIA< LinkedPage, InStack > & links, size_t num_pages, size_t iterations)
Definition at line 142 of file page_rank.hpp.
References DIA< ValueType_, Stack_ >::context(), thrill::api::Generate(), thrill::api::InnerJoin(), tlx::join(), DIA< ValueType_, Stack_ >::ReducePair(), and thrill::mem::to_string().
Variable Documentation
dampening
constexpr double dampening = 0.85 static
Definition at line 40 of file page_rank.hpp.
Referenced by PageRank().
debug
constexpr bool debug = false static
Definition at line 38 of file page_rank.hpp.
TLX_ATTRIBUTE_PACKED
struct examples::page_rank::PageRankPair TLX_ATTRIBUTE_PACKED