Thrill: examples::suffix_sorting Namespace Reference
examples::suffix_sorting Namespace Reference
Namespaces
namespace dc3_local
namespace dc7_local
Classes
struct IndexChar
struct IndexFlag
struct IndexRank
A pair (index, rank)
struct IndexRankFlag
Enumerations
enum Status : uint8_t {
UNDECIDED = 0, UNIQUE = 1, FULLY_DISCARDED = 2, UNDECIDED = 0,
UNIQUE = 1, FULLY_DISCARDED = 2
}
enum Status : uint8_t {
UNDECIDED = 0, UNIQUE = 1, FULLY_DISCARDED = 2, UNDECIDED = 0,
UNIQUE = 1, FULLY_DISCARDED = 2
}
Functions
template<typename InputDIA , typename SuffixArrayDIA >
bool CheckSA (const InputDIA &input, const SuffixArrayDIA &suffix_array)
template<typename InputDIA , typename SuffixArrayDIA >
InputDIA ConstructBWT (const InputDIA &input, const SuffixArrayDIA &suffix_array, uint64_t input_size)
template<typename InputDIA , typename IndexDIA >
IndexDIA ConstructLCP (const InputDIA &input, const IndexDIA &, const InputDIA &bwt, uint64_t input_size)
template<typename InputDIA >
auto ConstructWaveletTree (const InputDIA &input_dia, const std::string &output_path)
template<typename InputDIA >
auto ConstructWaveletTree (const InputDIA &input_dia)
template<typename Index , typename InputDIA >
thrill::DIA< Index > DC3 (const InputDIA &input_dia, size_t input_size, size_t K)
template<typename Index , typename InputDIA >
DIA< Index > DC3 (const InputDIA &input_dia, size_t input_size, size_t K)
template DIA< uint32_t > DC3< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, size_t K)
template<typename Index , typename InputDIA >
DIA< dc3_local::StringFragment
< Index, typename
InputDIA::ValueType > > DC3Recursive (const InputDIA &input_dia, size_t input_size, size_t K)
template<typename Index , typename InputDIA >
thrill::DIA< Index > DC7 (const InputDIA &input_dia, size_t input_size, size_t K)
template<typename Index , typename InputDIA >
DIA< Index > DC7 (const InputDIA &input_dia, size_t input_size, size_t K)
template DIA< uint32_t > DC7< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, size_t K)
template<typename Index , typename InputDIA >
DIA< dc7_local::StringFragment
< Index, typename
InputDIA::ValueType > > DC7Recursive (const InputDIA &input_dia, size_t input_size, size_t K)
static bool IsDiffCover7 (size_t i)
template<typename Index , typename InputDIA >
thrill::DIA< Index > PrefixDoubling (const InputDIA &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
DIA< Index > PrefixDoubling (const InputDIA &input_dia, size_t input_size, bool packed)
template DIA< common::uint40 > PrefixDoubling< common::uint40 > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template DIA< uint32_t > PrefixDoubling< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
thrill::DIA< Index > PrefixDoublingDementiev (const InputDIA &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
DIA< Index > PrefixDoublingDementiev (const InputDIA &input_dia, size_t input_size, bool packed)
template DIA< common::uint40 > PrefixDoublingDementiev< common::uint40 > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template DIA< uint32_t > PrefixDoublingDementiev< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
thrill::DIA< Index > PrefixDoublingDiscardingDementiev (const InputDIA &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
DIA< Index > PrefixDoublingDiscardingDementiev (const InputDIA &input_dia, size_t input_size, bool packed)
template DIA< common::uint40 > PrefixDoublingDiscardingDementiev< common::uint40 > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template DIA< uint32_t > PrefixDoublingDiscardingDementiev< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
thrill::DIA< Index > PrefixQuadrupling (const InputDIA &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
DIA< Index > PrefixQuadrupling (const InputDIA &input_dia, size_t input_size, bool packed)
template DIA< common::uint40 > PrefixQuadrupling< common::uint40 > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template DIA< uint32_t > PrefixQuadrupling< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
thrill::DIA< Index > PrefixQuadruplingDiscarding (const InputDIA &input_dia, size_t input_size, bool packed)
template<typename Index , typename InputDIA >
DIA< Index > PrefixQuadruplingDiscarding (const InputDIA &input_dia, size_t input_size, bool packed)
template DIA< common::uint40 > PrefixQuadruplingDiscarding< common::uint40 > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
template DIA< uint32_t > PrefixQuadruplingDiscarding< uint32_t > (const DIA< uint8_t > &input_dia, size_t input_size, bool packed)
Variables
static constexpr bool debug = false
bool debug_print = false
struct
examples::suffix_sorting::IndexRank THRILL_ATTRIBUTE_PACKED
Enumeration Type Documentation
enum Status : uint8_t
Enumerator
UNDECIDED
UNIQUE
FULLY_DISCARDED
UNDECIDED
UNIQUE
FULLY_DISCARDED
Definition at line 107 of file prefix_quadrupling.cpp.
enum Status : uint8_t
Enumerator
UNDECIDED
UNIQUE
FULLY_DISCARDED
UNDECIDED
UNIQUE
FULLY_DISCARDED
Definition at line 135 of file prefix_doubling.cpp.
Function Documentation
bool examples::suffix_sorting::CheckSA (const InputDIA & input, const SuffixArrayDIA & suffix_array)
A pair (rank, index)
Definition at line 28 of file check_sa.hpp.
References IndexRank< Index >::index, LOG1, THRILL_ATTRIBUTE_PACKED, and thrill::api::Zip().
InputDIA examples::suffix_sorting::ConstructBWT (const InputDIA & input, const SuffixArrayDIA & suffix_array, uint64_t input_size)
Definition at line 28 of file construct_bwt.hpp.
References IndexChar< Char, Index >::ch, IndexRank< Index >::index, IndexChar< Char, Index >::index, IndexRank< Index >::rank, THRILL_ATTRIBUTE_PACKED, and thrill::api::Zip().
IndexDIA examples::suffix_sorting::ConstructLCP (const InputDIA & input, const IndexDIA & , const InputDIA & bwt, uint64_t input_size)
Definition at line 77 of file construct_lcp.hpp.
References IndexChar< Char, Index >::ch, debug_print, IndexFlag< Index >::flag, thrill::api::Generate(), IndexRank< Index >::index, IndexChar< Char, Index >::index, IndexFlag< Index >::index, and IndexRank< Index >::rank.
auto examples::suffix_sorting::ConstructWaveletTree (const InputDIA & input_dia, const std::string & output_path)
Definition at line 34 of file construct_wt.hpp.
References debug, thrill::api::DisjointTag, thrill::common::IntegerLog2Ceil(), sLOG, and thrill::common::str_sprintf().
auto examples::suffix_sorting::ConstructWaveletTree (const InputDIA & input_dia)
Definition at line 39 of file wavelet_tree.cpp.
References debug, thrill::common::IntegerLog2Ceil(), sLOG, and thrill::common::str_sprintf().
thrill::DIA<Index> examples::suffix_sorting::DC3 (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 659 of file dc3.cpp.
DIA<Index> examples::suffix_sorting::DC3 (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 659 of file dc3.cpp.
template DIA<uint32_t> examples::suffix_sorting::DC3< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, size_t K)
DIA<dc3_local::StringFragment<Index, typename InputDIA::ValueType> > examples::suffix_sorting::DC3Recursive (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 303 of file dc3.cpp.
References thrill::api::ArrayTag, debug_print, die_unless, thrill::api::DisjointTag, IndexRank< Index >::index, thrill::api::NoRebalanceTag, thrill::api::PadTag, sLOG1, thrill::api::Union(), and thrill::api::ZipWindow().
thrill::DIA<Index> examples::suffix_sorting::DC7 (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 947 of file dc7.cpp.
DIA<Index> examples::suffix_sorting::DC7 (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 947 of file dc7.cpp.
template DIA<uint32_t> examples::suffix_sorting::DC7< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, size_t K)
DIA<dc7_local::StringFragment<Index, typename InputDIA::ValueType> > examples::suffix_sorting::DC7Recursive (const InputDIA & input_dia, size_t input_size, size_t K)
Definition at line 453 of file dc7.cpp.
References thrill::api::ArrayTag, assert_equal, debug_print, die_unless, thrill::api::DisjointTag, IndexRank< Index >::index, IsDiffCover7(), thrill::api::NoRebalanceTag, thrill::api::PadTag, sLOG1, thrill::api::Union(), and thrill::api::ZipWindow().
static bool examples::suffix_sorting::IsDiffCover7 (size_t i) inline static
Definition at line 446 of file dc7.cpp.
Referenced by DC7Recursive().
thrill::DIA<Index> examples::suffix_sorting::PrefixDoubling (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 704 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, PrefixDoubling< uint32_t >(), PrefixDoublingDementiev< uint32_t >(), PrefixDoublingDiscardingDementiev< uint32_t >(), and sLOG1.
DIA<Index> examples::suffix_sorting::PrefixDoubling (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 704 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, PrefixDoubling< uint32_t >(), PrefixDoublingDementiev< uint32_t >(), PrefixDoublingDiscardingDementiev< uint32_t >(), and sLOG1.
template DIA<common::uint40> examples::suffix_sorting::PrefixDoubling< common::uint40 > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
template DIA<uint32_t> examples::suffix_sorting::PrefixDoubling< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
Referenced by PrefixDoubling().
thrill::DIA<Index> examples::suffix_sorting::PrefixDoublingDementiev (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 498 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), and sLOG1.
DIA<Index> examples::suffix_sorting::PrefixDoublingDementiev (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 498 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), and sLOG1.
template DIA<common::uint40> examples::suffix_sorting::PrefixDoublingDementiev< common::uint40 > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
template DIA<uint32_t> examples::suffix_sorting::PrefixDoublingDementiev< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
Referenced by PrefixDoubling().
thrill::DIA<Index> examples::suffix_sorting::PrefixDoublingDiscardingDementiev (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 182 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), sLOG1, and thrill::api::Union().
DIA<Index> examples::suffix_sorting::PrefixDoublingDiscardingDementiev (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 182 of file prefix_doubling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), sLOG1, and thrill::api::Union().
template DIA<common::uint40> examples::suffix_sorting::PrefixDoublingDiscardingDementiev< common::uint40 > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
template DIA<uint32_t> examples::suffix_sorting::PrefixDoublingDiscardingDementiev< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
Referenced by PrefixDoubling().
thrill::DIA<Index> examples::suffix_sorting::PrefixQuadrupling (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 636 of file prefix_quadrupling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), and sLOG1.
DIA<Index> examples::suffix_sorting::PrefixQuadrupling (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 636 of file prefix_quadrupling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, thrill::common::max(), and sLOG1.
template DIA<common::uint40> examples::suffix_sorting::PrefixQuadrupling< common::uint40 > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
template DIA<uint32_t> examples::suffix_sorting::PrefixQuadrupling< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
thrill::DIA<Index> examples::suffix_sorting::PrefixQuadruplingDiscarding (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 168 of file prefix_quadrupling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, sLOG1, and thrill::api::Union().
DIA<Index> examples::suffix_sorting::PrefixQuadruplingDiscarding (const InputDIA & input_dia, size_t input_size, bool packed)
Definition at line 168 of file prefix_quadrupling.cpp.
References debug_print, IndexRank< Index >::index, LOG1, sLOG1, and thrill::api::Union().
template DIA<common::uint40> examples::suffix_sorting::PrefixQuadruplingDiscarding< common::uint40 > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
template DIA<uint32_t> examples::suffix_sorting::PrefixQuadruplingDiscarding< uint32_t > (const DIA< uint8_t > & input_dia, size_t input_size, bool packed)
Variable Documentation
constexpr bool debug = false static
Definition at line 34 of file wavelet_tree.cpp.
Referenced by ConstructWaveletTree().
bool debug_print = false
Definition at line 47 of file suffix_sorting.cpp.
Referenced by ConstructLCP(), DC3Recursive(), DC7Recursive(), main(), PrefixDoubling(), PrefixDoublingDementiev(), PrefixDoublingDiscardingDementiev(), PrefixQuadrupling(), and PrefixQuadruplingDiscarding().
struct examples::suffix_sorting::Index3Rank THRILL_ATTRIBUTE_PACKED
Referenced by CheckSA(), and ConstructBWT().