Thrill: thrill::data::serialization_cereal Namespace Reference
thrill::data::serialization_cereal Namespace Reference
Data Internals
Classes
class ThrillInputArchive
An input archive designed to load data saved using ThrillOutputArchive.
class ThrillOutputArchive
An output archive designed to save data in a compact binary representation.
Functions
template<typename Reader , typename T >
std::enable_if
< std::is_arithmetic< T >
::value, void >::type CEREAL_LOAD_FUNCTION_NAME (ThrillInputArchive< Reader > &ar, T &t)
Loading for POD types from binary.
template<typename Reader , typename T >
void CEREAL_LOAD_FUNCTION_NAME (ThrillInputArchive< Reader > &ar, cereal::BinaryData< T > &bd)
Loading binary data.
template<typename T , typename Writer >
std::enable_if
< std::is_arithmetic< T >
::value, void >::type CEREAL_SAVE_FUNCTION_NAME (ThrillOutputArchive< Writer > &ar, T const &t)
Saving for POD types to binary.
template<typename T , typename Writer >
void CEREAL_SAVE_FUNCTION_NAME (ThrillOutputArchive< Writer > &ar, cereal::BinaryData< T > const &bd)
Saving binary data.
template<typename Writer , typename T >
void CEREAL_SERIALIZE_FUNCTION_NAME (ThrillOutputArchive< Writer > &ar, cereal::NameValuePair< T > &t)
Serializing NVP types to binary.
template<typename Reader , typename T >
void CEREAL_SERIALIZE_FUNCTION_NAME (ThrillInputArchive< Reader > &ar, cereal::NameValuePair< T > &t)
Serializing NVP types to binary.
template<typename Writer , typename T >
void CEREAL_SERIALIZE_FUNCTION_NAME (ThrillOutputArchive< Writer > &ar, cereal::SizeTag< T > &t)
Serializing SizeTags to binary.
template<typename Reader , typename T >
void CEREAL_SERIALIZE_FUNCTION_NAME (ThrillInputArchive< Reader > &ar, cereal::SizeTag< T > &t)
Serializing SizeTags to binary.
Function Documentation
std::enable_if<std::is_arithmetic<T>::value, void>::type thrill::data::serialization_cereal::CEREAL_LOAD_FUNCTION_NAME (ThrillInputArchive< Reader > & ar, T & t) inline
Loading for POD types from binary.
Definition at line 131 of file serialization_cereal.hpp.
References ThrillInputArchive< Reader >::loadBinary().
void thrill::data::serialization_cereal::CEREAL_LOAD_FUNCTION_NAME (ThrillInputArchive< Reader > & ar, cereal::BinaryData< T > & bd) inline
Loading binary data.
Definition at line 178 of file serialization_cereal.hpp.
References ThrillInputArchive< Reader >::loadBinary().
std::enable_if<std::is_arithmetic<T>::value, void>::type thrill::data::serialization_cereal::CEREAL_SAVE_FUNCTION_NAME (ThrillOutputArchive< Writer > & ar, T const & t) inline
Saving for POD types to binary.
Definition at line 123 of file serialization_cereal.hpp.
References ThrillOutputArchive< Writer >::saveBinary().
void thrill::data::serialization_cereal::CEREAL_SAVE_FUNCTION_NAME (ThrillOutputArchive< Writer > & ar, cereal::BinaryData< T > const & bd) inline
Saving binary data.
Definition at line 170 of file serialization_cereal.hpp.
References ThrillOutputArchive< Writer >::saveBinary().
void thrill::data::serialization_cereal::CEREAL_SERIALIZE_FUNCTION_NAME (ThrillOutputArchive< Writer > & ar, cereal::NameValuePair< T > & t) inline
Serializing NVP types to binary.
Definition at line 138 of file serialization_cereal.hpp.
void thrill::data::serialization_cereal::CEREAL_SERIALIZE_FUNCTION_NAME (ThrillInputArchive< Reader > & ar, cereal::NameValuePair< T > & t) inline
Serializing NVP types to binary.
Definition at line 146 of file serialization_cereal.hpp.
void thrill::data::serialization_cereal::CEREAL_SERIALIZE_FUNCTION_NAME (ThrillOutputArchive< Writer > & ar, cereal::SizeTag< T > & t) inline
Serializing SizeTags to binary.
Definition at line 154 of file serialization_cereal.hpp.
void thrill::data::serialization_cereal::CEREAL_SERIALIZE_FUNCTION_NAME (ThrillInputArchive< Reader > & ar, cereal::SizeTag< T > & t) inline
Serializing SizeTags to binary.
Definition at line 162 of file serialization_cereal.hpp.