Thrill: foxxll::async_schedule_local Namespace Reference
foxxll::async_schedule_local Namespace Reference
Typedefs
using write_time_pair = std::pair< size_t, size_t >
Functions
static size_t get_disk (size_t i, const size_t *disks, size_t D)
size_t simulate_async_write (const size_t *disks, const size_t L, const size_t m_init, const size_t D, std::pair< size_t, size_t > *o_time)
Variables
static constexpr bool debug = false
Typedef Documentation
write_time_pair
using write_time_pair = std::pair<size_t, size_t>
Definition at line 54 of file async_schedule.cpp.
Function Documentation
get_disk()
static size_t foxxll::async_schedule_local::get_disk (size_t i, const size_t * disks, size_t D) inline static
Definition at line 63 of file async_schedule.cpp.
References gen_data::D, and file::DEFAULT_DEVICE_ID.
Referenced by simulate_async_write().
simulate_async_write()
size_t foxxll::async_schedule_local::simulate_async_write (const size_t * disks, const size_t L, const size_t m_init, const size_t D, std::pair< size_t, size_t > * o_time)
Definition at line 72 of file async_schedule.cpp.
References gen_data::D, get_disk(), and TLX_LOG.
Referenced by foxxll::compute_prefetch_schedule().
Variable Documentation
debug
constexpr bool debug = false static
Definition at line 36 of file async_schedule.cpp.
Referenced by foxxll::compute_prefetch_schedule().