Thrill: tlx::parallel_mergesort_detail Namespace Reference
tlx::parallel_mergesort_detail Namespace Reference
Sorting Algorithms
Classes
struct PMWMSPiece
Subsequence description.
struct PMWMSSortingData
Data accessed by all threads.
Functions
template<typename RandomAccessIterator , typename DiffType >
void determine_samples (PMWMSSortingData< RandomAccessIterator > *sd, DiffType &num_samples, size_t iam, size_t num_threads)
Select samples from a sequence.
template<bool Stable, typename RandomAccessIterator , typename Comparator >
void parallel_sort_mwms_pu (PMWMSSortingData< RandomAccessIterator > *sd, size_t iam, size_t num_threads, ThreadBarrierMutex &barrier, Comparator &comp, MultiwayMergeSplittingAlgorithm mwmsa)
PMWMS code executed by each thread.
Function Documentation
void tlx::parallel_mergesort_detail::determine_samples (PMWMSSortingData< RandomAccessIterator > * sd, DiffType & num_samples, size_t iam, size_t num_threads)
Select samples from a sequence.
Parameters
sd Pointer to sorting data struct. Result will be placed in sd->samples.
num_samples Number of samples to select.
iam my thread number
num_threads number of threads in group
Definition at line 93 of file parallel_mergesort.hpp.
References SimpleVector< ValueType, Mode >::begin(), tlx::multiway_merge_detail::equally_split(), tlx::parallel_multiway_merge_oversampling, PMWMSSortingData< RandomAccessIterator >::samples, PMWMSSortingData< RandomAccessIterator >::source, and PMWMSSortingData< RandomAccessIterator >::starts.
Referenced by parallel_sort_mwms_pu().
void tlx::parallel_mergesort_detail::parallel_sort_mwms_pu (PMWMSSortingData< RandomAccessIterator > * sd, size_t iam, size_t num_threads, ThreadBarrierMutex & barrier, Comparator & comp, MultiwayMergeSplittingAlgorithm mwmsa)
PMWMS code executed by each thread.
Parameters
sd Pointer to sorting data struct.
iam my thread number
num_threads number of threads in group
comp Comparator.
mwmsa MultiwayMergeSplittingAlgorithm to use.
Definition at line 119 of file parallel_mergesort.hpp.
References SimpleVector< ValueType, Mode >::begin(), determine_samples(), tlx::multisequence_partition(), tlx::multiway_merge_base(), tlx::MWMSA_EXACT, tlx::MWMSA_SAMPLING, PMWMSSortingData< RandomAccessIterator >::pieces, PMWMSSortingData< RandomAccessIterator >::samples, PMWMSSortingData< RandomAccessIterator >::source, PMWMSSortingData< RandomAccessIterator >::starts, PMWMSSortingData< RandomAccessIterator >::temporary, and ThreadBarrierMutex::wait().