Thrill: thrill::net::mpi Namespace Reference
thrill::net::mpi Namespace Reference
Classes
class AsyncRequest
class Connection
Virtual MPI connection class.
class Dispatcher
class Exception
A derived exception class which looks up MPI error strings.
class Group
A net group backed by virtual MPI connection.
Typedefs
using AsyncRequestCallback = tlx::delegate< void(MPI_Status &), mem::GPoolAllocator< char > >
Signature of async MPI request callbacks.
Functions
bool Construct (size_t group_size, DispatcherThread &dispatcher, std::unique_ptr< Group > *groups, size_t group_count)
Construct Group which connects to peers using MPI.
static void Deinitialize ()
atexit() method to deinitialize the MPI library.
static void Initialize ()
run MPI_Init() if not already done (can be called multiple times).
size_t MpiRank ()
Return the rank of this process in the MPI COMM WORLD.
size_t NumMpiProcesses ()
Return the number of MPI processes.
Variables
std::mutex g_mutex
The Grand MPI Library Invocation Mutex (The GMLIM)
static const size_t g_simultaneous = 32
number of simultaneous transfers
Function Documentation
Deinitialize()
static void thrill::net::mpi::Deinitialize () inline static
atexit() method to deinitialize the MPI library.
Definition at line 634 of file group.cpp.
Referenced by Initialize().
Initialize()
static void thrill::net::mpi::Initialize () inline static
run MPI_Init() if not already done (can be called multiple times).
Definition at line 641 of file group.cpp.
References Deinitialize(), die, and Exception::Exception().
Referenced by Construct(), Group::Group(), MpiRank(), and NumMpiProcesses().
Variable Documentation
g_mutex
std::mutex g_mutex
The Grand MPI Library Invocation Mutex (The GMLIM)
Definition at line 26 of file group.cpp.
g_simultaneous
const size_t g_simultaneous = 32 static
number of simultaneous transfers
Definition at line 27 of file dispatcher.cpp.