Thrill: examples/page_rank/page_rank_run.cpp File Reference
page_rank_run.cpp File Reference
#include <examples/page_rank/page_rank.hpp>
#include <examples/page_rank/zipf_graph_gen.hpp>
#include <thrill/api/cache.hpp>
#include <thrill/api/group_by_key.hpp>
#include <thrill/api/group_to_index.hpp>
#include <thrill/api/max.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/api/sum.hpp>
#include <thrill/api/write_lines.hpp>
#include <thrill/api/zip_with_index.hpp>
#include <thrill/common/logger.hpp>
#include <thrill/common/stats_timer.hpp>
#include <tlx/cmdline_parser.hpp>
#include <algorithm>
#include <string>
#include <utility>
#include <vector>
Functions
int main (int argc, char *argv[])
static void RunJoinPageRankEdgePerLine (api::Context &ctx, const std::vector< std::string > &input_path, const std::string &output_path, size_t iterations)
static void RunPageRankEdgePerLine (api::Context &ctx, const std::vector< std::string > &input_path, const std::string &output_path, size_t iterations)
static void RunPageRankGenerated (api::Context &ctx, const std::string &input_path, const ZipfGraphGen &base_graph_gen, const std::string &output_path, size_t iterations)
static void RunPageRankJoinGenerated (api::Context &ctx, const std::string &input_path, const ZipfGraphGen &base_graph_gen, const std::string &output_path, size_t iterations)
Function Documentation
int main (int argc, char * argv[])
Definition at line 311 of file page_rank_run.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_double(), CmdlineParser::add_param_stringlist(), CmdlineParser::add_size_t(), CmdlineParser::add_string(), die_unless, ZipfGraphGen::link_zipf_exponent, ZipfGraphGen::link_zipf_scale, CmdlineParser::print_result(), CmdlineParser::process(), thrill::api::Run(), RunJoinPageRankEdgePerLine(), RunPageRankEdgePerLine(), RunPageRankGenerated(), RunPageRankJoinGenerated(), ZipfGraphGen::size_mean, ZipfGraphGen::size_var, and thrill::mem::to_string().
static void RunJoinPageRankEdgePerLine (api::Context & ctx, const std::vector< std::string > & input_path, const std::string & output_path, size_t iterations) static
Definition at line 122 of file page_rank_run.cpp.
References Context::enable_consume(), LOG1, max(), Context::my_rank(), Context::net_manager(), Context::num_hosts(), thrill::api::ReadLines(), PagePageLink::src, thrill::common::str_sprintf(), PagePageLink::tgt, and Manager::Traffic().
Referenced by main().
static void RunPageRankEdgePerLine (api::Context & ctx, const std::vector< std::string > & input_path, const std::string & output_path, size_t iterations) static
Definition at line 49 of file page_rank_run.cpp.
References Context::enable_consume(), LOG1, max(), Context::my_rank(), examples::page_rank::PageRank(), thrill::api::ReadLines(), PagePageLink::src, thrill::common::str_sprintf(), and PagePageLink::tgt.
Referenced by main().
static void RunPageRankGenerated (api::Context & ctx, const std::string & input_path, const ZipfGraphGen & base_graph_gen, const std::string & output_path, size_t iterations) static
Definition at line 199 of file page_rank_run.cpp.
References die, Context::enable_consume(), thrill::api::Generate(), LOG1, Context::my_rank(), Context::num_hosts(), examples::page_rank::PageRank(), and thrill::mem::to_string().
Referenced by main().
static void RunPageRankJoinGenerated (api::Context & ctx, const std::string & input_path, const ZipfGraphGen & base_graph_gen, const std::string & output_path, size_t iterations) static
Definition at line 254 of file page_rank_run.cpp.
References die, Context::enable_consume(), thrill::api::Generate(), LOG1, Context::my_rank(), Context::net_manager(), Context::num_hosts(), thrill::common::str_sprintf(), and Manager::Traffic().
Referenced by main().