Thrill: examples/percentiles/percentiles.cpp File Reference
percentiles.cpp File Reference
#include <thrill/api/cache.hpp>
#include <thrill/api/dia.hpp>
#include <thrill/api/group_by_key.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/api/size.hpp>
#include <thrill/api/sort.hpp>
#include <thrill/api/sum.hpp>
#include <thrill/common/string.hpp>
#include <tlx/cmdline_parser.hpp>
#include <tlx/string/split.hpp>
#include <algorithm>
#include <ctime>
#include <string>
#include <utility>
#include <vector>
Functions
int main (int argc, char *argv[])
void Percentiles (api::Context &ctx, const std::string &input_path)
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 96 of file percentiles.cpp.
References CmdlineParser::add_param_string(), Percentiles(), CmdlineParser::print_result(), CmdlineParser::process(), and thrill::api::Run().
Percentiles()
void Percentiles (api::Context & ctx, const std::string & input_path)
Definition at line 31 of file percentiles.cpp.
References FlowControlChannel::Barrier(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), thrill::api::ReadLines(), tlx::split(), and Manager::Traffic().
Referenced by main().