Thrill: examples/word_count/random_text_writer.cpp File Reference
random_text_writer.cpp File Reference
#include <examples/word_count/random_text_writer.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/api/write_lines.hpp>
#include <tlx/cmdline_parser.hpp>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <vector>
Functions
int main (int argc, char *argv[])
static void Parallel (api::Context &ctx, const std::string &output)
static int Sequential (std::ostream &os)
Variables
unsigned max_words_key = 10
unsigned max_words_value = 100
unsigned min_words_key = 5
unsigned min_words_value = 20
unsigned range_words_key
unsigned range_words_value
unsigned seed = 123456
bool tab_separator = false
uint64_t totalbytes
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 105 of file random_text_writer.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_param_bytes(), CmdlineParser::add_string(), CmdlineParser::add_unsigned(), max_words_key, max_words_value, min_words_key, min_words_value, Parallel(), CmdlineParser::print_result(), CmdlineParser::process(), range_words_key, range_words_value, thrill::api::Run(), seed, Sequential(), tab_separator, and totalbytes.
Parallel()
static void Parallel (api::Context & ctx, const std::string & output) static
Definition at line 69 of file random_text_writer.cpp.
References thrill::api::Generate(), min_words_key, min_words_value, Context::my_rank(), Context::num_workers(), examples::word_count::RandomTextWriterGenerate(), range_words_key, range_words_value, seed, tab_separator, and totalbytes.
Referenced by main().
Sequential()
static int Sequential (std::ostream & os) static
Definition at line 39 of file random_text_writer.cpp.
References min_words_key, min_words_value, examples::word_count::RandomTextWriterGenerate(), range_words_key, range_words_value, seed, tab_separator, and totalbytes.
Referenced by main().
Variable Documentation
max_words_key
unsigned max_words_key = 10
Definition at line 29 of file random_text_writer.cpp.
Referenced by main().
max_words_value
unsigned max_words_value = 100
Definition at line 30 of file random_text_writer.cpp.
Referenced by main().
min_words_key
unsigned min_words_key = 5
Definition at line 29 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().
min_words_value
unsigned min_words_value = 20
Definition at line 30 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().
range_words_key
unsigned range_words_key
Definition at line 37 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().
range_words_value
unsigned range_words_value
Definition at line 37 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().
seed
unsigned seed = 123456
Definition at line 32 of file random_text_writer.cpp.
Referenced by SampleNode< ValueType >::Execute(), main(), hash< Edge >::operator()(), Parallel(), Sequential(), and TabulationHashing< size, hash_t, prng_t >::TabulationHashing().
tab_separator
bool tab_separator = false
Definition at line 35 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().
totalbytes
uint64_t totalbytes
Definition at line 34 of file random_text_writer.cpp.
Referenced by main(), Parallel(), and Sequential().