Thrill: examples/select/select_run.cpp File Reference
select_run.cpp File Reference
#include <examples/select/select.hpp>
#include <thrill/api/cache.hpp>
#include <thrill/api/context.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/common/logger.hpp>
#include <tlx/cmdline_parser.hpp>
Functions
int main (int argc, char *argv[])
static auto RunSelect (api::Context &ctx, size_t num_elems, size_t rank, bool max)
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 40 of file select_run.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_size_t(), max(), CmdlineParser::print_result(), CmdlineParser::process(), thrill::api::Run(), RunSelect(), and CmdlineParser::set_verbose_process().
RunSelect()
static auto RunSelect (api::Context & ctx, size_t num_elems, size_t rank, bool max) static
Definition at line 22 of file select_run.cpp.
References thrill::api::Generate(), LOG, and examples::select::Select().
Referenced by main().