Thrill: stats_data::summary< T > Struct Template Reference
stats_data::summary< T > Struct Template Reference
Detailed Description
template<typename T>
struct foxxll::stats_data::summary< T >
Definition at line 506 of file iostats.hpp.
#include <iostats.hpp>
Public Member Functions
template<typename Functor >
summary (const std::vector< file_stats_data > &fs, const Functor &get_value)
Public Attributes
double average
T max
double median
T min
T total
std::vector< std::pair< T, unsigned > > values_per_device
Constructor & Destructor Documentation
summary()
summary (const std::vector< file_stats_data > & fs, const Functor & get_value)
Definition at line 394 of file iostats.cpp.
References file_stats_data::get_device_id(), max(), min(), and gen_data::x.
Member Data Documentation
average
double average
Definition at line 509 of file iostats.hpp.
max
T max
Definition at line 508 of file iostats.hpp.
median
double median
Definition at line 509 of file iostats.hpp.
min
T min
Definition at line 508 of file iostats.hpp.
total
T total
Definition at line 508 of file iostats.hpp.
values_per_device
std::vector<std::pair<T, unsigned> > values_per_device
Definition at line 510 of file iostats.hpp.
The documentation for this struct was generated from the following files:
extlib/foxxll/foxxll/io/iostats.hpp
extlib/foxxll/foxxll/io/iostats.cpp