Thrill: HashDataSwitch< std::string > Struct Template Reference
HashDataSwitch< std::string > Struct Template Reference
Detailed Description
template<>
struct thrill::common::HashDataSwitch< std::string >
Definition at line 107 of file hash.hpp.
#include <hash.hpp>
Static Public Member Functions
static const char * ptr (const std::string &s)
static size_t size (const std::string &s)
Member Function Documentation
ptr()
static const char* ptr (const std::string & s) inline static
Definition at line 108 of file hash.hpp.
size()
static size_t size (const std::string & s) inline static
Definition at line 109 of file hash.hpp.
References thrill::common::crc32_slicing_by_8(), HashDataSwitch< T >::ptr(), HashDataSwitch< T >::size(), and TLX_ATTRIBUTE_FALLTHROUGH.
The documentation for this struct was generated from the following file:
thrill/common/hash.hpp