Thrill: RadixStep_CI2< StringPtr > Struct Template Reference
RadixStep_CI2< StringPtr > Struct Template Reference
Detailed Description
template<typename StringPtr>
struct tlx::sort_strings_detail::RadixStep_CI2< StringPtr >
Definition at line 539 of file radix_sort.hpp.
#include <radix_sort.hpp>
Public Types
typedef StringSet::Iterator Iterator
typedef StringSet::String String
typedef StringPtr::StringSet StringSet
Public Member Functions
RadixStep_CI2 (const StringPtr &strptr, size_t base, size_t depth, uint8_t *charcache)
Public Attributes
size_t bkt_size [256]
size_t idx
size_t pos
Member Typedef Documentation
Iterator
typedef StringSet::Iterator Iterator
Definition at line 541 of file radix_sort.hpp.
String
typedef StringSet::String String
Definition at line 542 of file radix_sort.hpp.
StringSet
typedef StringPtr::StringSet StringSet
Definition at line 540 of file radix_sort.hpp.
Constructor & Destructor Documentation
RadixStep_CI2()
RadixStep_CI2 (const StringPtr & strptr, size_t base, size_t depth, uint8_t * charcache) inline
Definition at line 547 of file radix_sort.hpp.
References StringPtr< StringSet_ >::active(), StringPtr< StringSet_ >::set_lcp(), tlx::swap(), and StringPtr< StringSet_ >::with_lcp.
Member Data Documentation
bkt_size
size_t bkt_size[256]
Definition at line 545 of file radix_sort.hpp.
idx
size_t idx
Definition at line 544 of file radix_sort.hpp.
pos
size_t pos
Definition at line 544 of file radix_sort.hpp.
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/radix_sort.hpp