Thrill: PerfectTreeCalculations< TreeBits > Struct Template Reference
PerfectTreeCalculations< TreeBits > Struct Template Reference
Detailed Description
template<size_t TreeBits>
struct tlx::sort_strings_detail::PerfectTreeCalculations< TreeBits >
Class to transform in-order to level-order indexes in a perfect binary tree.
Definition at line 51 of file sample_sort_tools.hpp.
#include <sample_sort_tools.hpp>
Static Public Member Functions
static unsigned int level_to_preorder (unsigned int id)
static unsigned int pre_to_levelorder (unsigned int id)
static void self_verify ()
Static Public Attributes
static const bool debug = false
static const size_t num_nodes = (1 << treebits) - 1
static const size_t treebits = TreeBits
Member Function Documentation
static unsigned int level_to_preorder (unsigned int id) inline static
Definition at line 57 of file sample_sort_tools.hpp.
References PerfectTreeCalculations< TreeBits >::num_nodes, TLX_LOG, tlx::sort_strings_detail::to_binary(), and PerfectTreeCalculations< TreeBits >::treebits.
Referenced by PerfectTreeCalculations< TreeBits >::self_verify().
static unsigned int pre_to_levelorder (unsigned int id) inline static
Definition at line 72 of file sample_sort_tools.hpp.
References PerfectTreeCalculations< TreeBits >::num_nodes, TLX_LOG, tlx::sort_strings_detail::to_binary(), and PerfectTreeCalculations< TreeBits >::treebits.
Referenced by SSClassifyEqualUnroll< key_type, TreeBits >::get_splitter(), SSClassifyTreeCalcUnrollInterleave< key_type, TreeBits, Rollout >::get_splitter(), and PerfectTreeCalculations< TreeBits >::self_verify().
static void self_verify () inline static
Definition at line 87 of file sample_sort_tools.hpp.
References PerfectTreeCalculations< TreeBits >::level_to_preorder(), PerfectTreeCalculations< TreeBits >::num_nodes, PerfectTreeCalculations< TreeBits >::pre_to_levelorder(), tlx_die_unequal, TLX_LOG, tlx::sort_strings_detail::to_binary(), and PerfectTreeCalculations< TreeBits >::treebits.
Referenced by tlx::sort_strings_detail::perfect_tree_calculations_self_verify().
Member Data Documentation
const bool debug = false static
Definition at line 52 of file sample_sort_tools.hpp.
const size_t num_nodes = (1 << treebits) - 1 static
Definition at line 55 of file sample_sort_tools.hpp.
Referenced by PerfectTreeCalculations< TreeBits >::level_to_preorder(), PerfectTreeCalculations< TreeBits >::pre_to_levelorder(), and PerfectTreeCalculations< TreeBits >::self_verify().
const size_t treebits = TreeBits static
Definition at line 54 of file sample_sort_tools.hpp.
Referenced by PerfectTreeCalculations< TreeBits >::level_to_preorder(), PerfectTreeCalculations< TreeBits >::pre_to_levelorder(), and PerfectTreeCalculations< TreeBits >::self_verify().
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/sample_sort_tools.hpp