Thrill: FileList Struct Reference
FileList Struct Reference
Detailed Description
List of file info and additional overall info.
Definition at line 79 of file file_io.hpp.
Inherits vector< T >.
#include <file_io.hpp>
Public Member Functions
uint64_t size_ex_psum (size_t i) const
exclusive prefix sum of file sizes with total_size as sentinel
uint64_t size_inc_psum (size_t i) const
inclusive prefix sum of file sizes (only for symmetry with ex_psum)
Public Attributes
bool contains_compressed
whether the list contains a compressed file.
bool contains_remote_uri
whether the list contains a remote-uri file.
uint64_t total_size
total size of files
Member Function Documentation
size_ex_psum()
uint64_t size_ex_psum (size_t i) const inline
exclusive prefix sum of file sizes with total_size as sentinel
Definition at line 94 of file file_io.hpp.
Referenced by ReadLinesNode::InputLineIteratorUncompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), and ReadBinaryNode< ValueType >::ReadBinaryNode().
size_inc_psum()
uint64_t size_inc_psum (size_t i) const inline
inclusive prefix sum of file sizes (only for symmetry with ex_psum)
Definition at line 90 of file file_io.hpp.
Referenced by ReadLinesNode::InputLineIteratorCompressed::HasNext(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), and ReadBinaryNode< ValueType >::ReadBinaryNode().
Member Data Documentation
contains_compressed
bool contains_compressed
whether the list contains a compressed file.
Definition at line 84 of file file_io.hpp.
Referenced by thrill::vfs::Glob(), ReadLinesNode::PushData(), and ReadBinaryNode< ValueType >::ReadBinaryNode().
contains_remote_uri
bool contains_remote_uri
whether the list contains a remote-uri file.
Definition at line 87 of file file_io.hpp.
Referenced by thrill::vfs::Glob(), and ReadBinaryNode< ValueType >::ReadBinaryNode().
total_size
uint64_t total_size
total size of files
Definition at line 81 of file file_io.hpp.
Referenced by thrill::vfs::Glob(), ReadLinesNode::InputLineIteratorCompressed::InputLineIteratorCompressed(), ReadLinesNode::InputLineIteratorUncompressed::InputLineIteratorUncompressed(), and ReadBinaryNode< ValueType >::ReadBinaryNode().
The documentation for this struct was generated from the following file:
thrill/vfs/file_io.hpp