Thrill: RadixStep_CE2< StringShadowPtr > Struct Template Reference
RadixStep_CE2< StringShadowPtr > Struct Template Reference
Detailed Description
template<typename StringShadowPtr>
struct tlx::sort_strings_detail::RadixStep_CE2< StringShadowPtr >
Definition at line 194 of file radix_sort.hpp.
#include <radix_sort.hpp>
Public Types
typedef StringSet::Iterator Iterator
typedef StringShadowPtr::StringSet StringSet
Public Member Functions
RadixStep_CE2 (const StringShadowPtr &in_strptr, size_t depth, uint8_t *charcache)
Public Attributes
size_t bkt_size [256]
size_t idx
size_t pos
StringShadowPtr strptr
Member Typedef Documentation
Iterator
typedef StringSet::Iterator Iterator
Definition at line 199 of file radix_sort.hpp.
StringSet
typedef StringShadowPtr::StringSet StringSet
Definition at line 198 of file radix_sort.hpp.
Constructor & Destructor Documentation
RadixStep_CE2()
RadixStep_CE2 (const StringShadowPtr & in_strptr, size_t depth, uint8_t * charcache) inline
Definition at line 201 of file radix_sort.hpp.
References StringShadowPtr< StringSet_ >::active(), StringShadowPtr< StringSet_ >::copy_back(), StringShadowPtr< StringSet_ >::flip(), RadixStep_CE0< StringShadowPtr >::pos, tlx::sort_strings_detail::radixsort_CI3(), StringShadowPtr< StringSet_ >::set_lcp(), StringShadowPtr< StringSet_ >::shadow(), StringShadowPtr< StringSet_ >::size(), RadixStep_CE0< StringShadowPtr >::strptr, and StringShadowPtr< StringSet_ >::with_lcp.
Member Data Documentation
bkt_size
size_t bkt_size[256]
Definition at line 196 of file radix_sort.hpp.
idx
size_t idx
Definition at line 196 of file radix_sort.hpp.
pos
size_t pos
Definition at line 196 of file radix_sort.hpp.
strptr
StringShadowPtr strptr
Definition at line 195 of file radix_sort.hpp.
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/radix_sort.hpp