Thrill: HashDataSwitch< T > Struct Template Reference
HashDataSwitch< T > Struct Template Reference
Detailed Description
template<typename T>
struct thrill::common::HashDataSwitch< T >
Hashing helper that decides what is hashed.
Defaults to pointer to the object and sizeof(its type). Override these values for heap-allocated types. Some default overrides are provided.
Definition at line 100 of file hash.hpp.
#include <hash.hpp>
Static Public Member Functions
static const char * ptr (const T &x)
static size_t size (const T &)
Member Function Documentation
ptr()
static const char* ptr (const T & x) inline static
Definition at line 101 of file hash.hpp.
References gen_data::x.
Referenced by HashCrc32Fallback< ValueType >::operator()(), and HashDataSwitch< std::string >::size().
size()
static size_t size (const T &) inline static
Definition at line 103 of file hash.hpp.
Referenced by HashCrc32Fallback< ValueType >::operator()(), and HashDataSwitch< std::string >::size().
The documentation for this struct was generated from the following file:
thrill/common/hash.hpp