Thrill: Traffic Struct Reference
Traffic Struct Reference
Thrill Layers » Network Subsystem Layer
Detailed Description
Definition at line 33 of file manager.hpp.
#include <manager.hpp>
Public Member Functions
Traffic (size_t tx, size_t rx)
constructor
size_t total () const
both transmitted and received bytes
Public Attributes
size_t rx
received bytes
size_t tx
transmitted bytes
Friends
std::ostream & operator<< (std::ostream &os, const Traffic &t)
formatting: print total
Constructor & Destructor Documentation
Traffic()
Traffic (size_t tx, size_t rx) inline
constructor
Definition at line 41 of file manager.hpp.
References Traffic::operator<<.
Referenced by Manager::GetDataGroup().
Member Function Documentation
total()
size_t total () const inline
both transmitted and received bytes
Definition at line 39 of file manager.hpp.
References Traffic::rx.
Referenced by thrill::net::operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Traffic & t) friend
formatting: print total
Definition at line 43 of file group.cpp.
Referenced by Traffic::Traffic().
Member Data Documentation
rx
size_t rx
received bytes
Definition at line 37 of file manager.hpp.
Referenced by Context::Launch(), and Traffic::total().
tx
size_t tx
transmitted bytes
Definition at line 35 of file manager.hpp.
Referenced by Context::Launch().
The documentation for this struct was generated from the following file:
thrill/net/manager.hpp