Thrill: RadixStep_CE3< StringShadowPtr > Struct Template Reference
RadixStep_CE3< StringShadowPtr > Struct Template Reference
Detailed Description
template<typename StringShadowPtr>
struct tlx::sort_strings_detail::RadixStep_CE3< StringShadowPtr >
Definition at line 352 of file radix_sort.hpp.
#include <radix_sort.hpp>
Public Types
enum { RADIX = 0x10000 }
typedef StringSet::Iterator Iterator
typedef StringShadowPtr::StringSet StringSet
Public Member Functions
RadixStep_CE3 (const StringShadowPtr &in_strptr, size_t depth, uint16_t *charcache)
size_t get_next_non_empty_bkt_index (size_t start)
Public Attributes
size_t bkt_size [RADIX]
size_t idx
size_t pos
StringShadowPtr strptr
Member Typedef Documentation
Iterator
typedef StringSet::Iterator Iterator
Definition at line 359 of file radix_sort.hpp.
StringSet
typedef StringShadowPtr::StringSet StringSet
Definition at line 358 of file radix_sort.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
RADIX
Definition at line 353 of file radix_sort.hpp.
Constructor & Destructor Documentation
RadixStep_CE3()
RadixStep_CE3 (const StringShadowPtr & in_strptr, size_t depth, uint16_t * charcache) inline
Definition at line 361 of file radix_sort.hpp.
References StringShadowPtr< StringSet_ >::active(), StringShadowPtr< StringSet_ >::copy_back(), StringShadowPtr< StringSet_ >::flip(), StringShadowPtr< StringSet_ >::set_lcp(), StringShadowPtr< StringSet_ >::shadow(), and StringShadowPtr< StringSet_ >::with_lcp.
Member Function Documentation
get_next_non_empty_bkt_index()
size_t get_next_non_empty_bkt_index (size_t start) inline
Definition at line 415 of file radix_sort.hpp.
Member Data Documentation
bkt_size
size_t bkt_size[RADIX]
Definition at line 356 of file radix_sort.hpp.
idx
size_t idx
Definition at line 356 of file radix_sort.hpp.
pos
size_t pos
Definition at line 356 of file radix_sort.hpp.
strptr
StringShadowPtr strptr
Definition at line 355 of file radix_sort.hpp.
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/radix_sort.hpp