Thrill: RadixStep_CI3< StringPtr > Struct Template Reference
RadixStep_CI3< StringPtr > Struct Template Reference
Detailed Description
template<typename StringPtr>
struct tlx::sort_strings_detail::RadixStep_CI3< StringPtr >
Definition at line 701 of file radix_sort.hpp.
#include <radix_sort.hpp>
Public Types
enum { RADIX = 0x10000 }
typedef StringSet::Iterator Iterator
typedef StringSet::String String
typedef StringPtr::StringSet StringSet
Public Member Functions
RadixStep_CI3 (const StringPtr &strptr, size_t base, size_t depth, uint16_t *charcache)
size_t get_next_non_empty_bkt_index (size_t start)
Public Attributes
size_t bkt_size [RADIX]
size_t idx
size_t pos
Member Typedef Documentation
typedef StringSet::Iterator Iterator
Definition at line 705 of file radix_sort.hpp.
typedef StringSet::String String
Definition at line 706 of file radix_sort.hpp.
typedef StringPtr::StringSet StringSet
Definition at line 704 of file radix_sort.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
RADIX
Definition at line 702 of file radix_sort.hpp.
Constructor & Destructor Documentation
RadixStep_CI3 (const StringPtr & strptr, size_t base, size_t depth, uint16_t * charcache) inline
Definition at line 711 of file radix_sort.hpp.
References StringPtr< StringSet_ >::active(), RadixStep_CI3< StringPtr >::bkt_size, RadixStep_CI3< StringPtr >::get_next_non_empty_bkt_index(), RadixStep_CI3< StringPtr >::idx, RadixStep_CI3< StringPtr >::pos, RadixStep_CI3< StringPtr >::RADIX, StringPtr< StringSet_ >::set_lcp(), tlx::swap(), and StringPtr< StringSet_ >::with_lcp.
Member Function Documentation
size_t get_next_non_empty_bkt_index (size_t start) inline
Definition at line 773 of file radix_sort.hpp.
References RadixStep_CI3< StringPtr >::bkt_size, and RadixStep_CI3< StringPtr >::RADIX.
Referenced by RadixStep_CI3< StringPtr >::RadixStep_CI3().
Member Data Documentation
size_t bkt_size[RADIX]
Definition at line 709 of file radix_sort.hpp.
Referenced by RadixStep_CI3< StringPtr >::get_next_non_empty_bkt_index(), and RadixStep_CI3< StringPtr >::RadixStep_CI3().
size_t idx
Definition at line 708 of file radix_sort.hpp.
Referenced by RadixStep_CI3< StringPtr >::RadixStep_CI3().
size_t pos
Definition at line 708 of file radix_sort.hpp.
Referenced by RadixStep_CI3< StringPtr >::RadixStep_CI3().
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/radix_sort.hpp