Thrill: RadixStep_CE0< StringShadowPtr > Struct Template Reference
RadixStep_CE0< StringShadowPtr > Struct Template Reference
Detailed Description
template<typename StringShadowPtr>
struct tlx::sort_strings_detail::RadixStep_CE0< StringShadowPtr >
Definition at line 48 of file radix_sort.hpp.
#include <radix_sort.hpp>
Public Types
typedef StringSet::Iterator Iterator
typedef StringShadowPtr::StringSet StringSet
Public Member Functions
RadixStep_CE0 (const StringShadowPtr &in_strptr, size_t depth)
Public Attributes
size_t bkt_size [256]
size_t idx
size_t pos
StringShadowPtr strptr
Member Typedef Documentation
Iterator
typedef StringSet::Iterator Iterator
Definition at line 53 of file radix_sort.hpp.
StringSet
typedef StringShadowPtr::StringSet StringSet
Definition at line 52 of file radix_sort.hpp.
Constructor & Destructor Documentation
RadixStep_CE0()
RadixStep_CE0 (const StringShadowPtr & in_strptr, size_t depth) inline
Definition at line 55 of file radix_sort.hpp.
References StringShadowPtr< StringSet_ >::active(), StringShadowPtr< StringSet_ >::copy_back(), StringShadowPtr< StringSet_ >::flip(), RadixStep_CE0< StringShadowPtr >::pos, StringShadowPtr< StringSet_ >::set_lcp(), StringShadowPtr< StringSet_ >::shadow(), StringShadowPtr< StringSet_ >::size(), and StringShadowPtr< StringSet_ >::with_lcp.
Member Data Documentation
bkt_size
size_t bkt_size[256]
Definition at line 50 of file radix_sort.hpp.
Referenced by tlx::sort_strings_detail::radixsort_CE0_loop(), tlx::sort_strings_detail::radixsort_CE2_loop(), tlx::sort_strings_detail::radixsort_CE3_loop(), tlx::sort_strings_detail::radixsort_CI2(), and tlx::sort_strings_detail::radixsort_CI3().
idx
size_t idx
Definition at line 50 of file radix_sort.hpp.
pos
size_t pos
Definition at line 50 of file radix_sort.hpp.
Referenced by RadixStep_CE0< StringShadowPtr >::RadixStep_CE0(), and RadixStep_CE2< StringShadowPtr >::RadixStep_CE2().
strptr
StringShadowPtr strptr
Definition at line 49 of file radix_sort.hpp.
Referenced by RadixStep_CE2< StringShadowPtr >::RadixStep_CE2().
The documentation for this struct was generated from the following file:
extlib/tlx/tlx/sort/strings/radix_sort.hpp