Thrill: examples/terasort/terasort.cpp File Reference
terasort.cpp File Reference
#include <thrill/api/generate.hpp>
#include <thrill/api/read_binary.hpp>
#include <thrill/api/size.hpp>
#include <thrill/api/sort.hpp>
#include <thrill/api/write_binary.hpp>
#include <thrill/common/logger.hpp>
#include <thrill/common/string.hpp>
#include <tlx/cmdline_parser.hpp>
#include <tlx/string/hexdump.hpp>
#include <tlx/string/parse_si_iec_units.hpp>
#include <algorithm>
#include <random>
#include <string>
#include <utility>
#include <vector>
Functions
int main (int argc, char *argv[])
Variables
struct Record TLX_ATTRIBUTE_PACKED
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 120 of file terasort.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_param_stringlist(), CmdlineParser::add_string(), FlowControlChannel::Barrier(), die_unequal, die_unless, Context::enable_consume(), thrill::api::Generate(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), tlx::parse_si_iec_units(), CmdlineParser::print_result(), CmdlineParser::process(), thrill::api::Run(), and Manager::Traffic().
Variable Documentation
TLX_ATTRIBUTE_PACKED
struct RecordSigned TLX_ATTRIBUTE_PACKED