Thrill: examples/tpch/tpch_run.cpp File Reference
tpch_run.cpp File Reference
#include <examples/page_rank/zipf_graph_gen.hpp>
#include <examples/triangles/triangles.hpp>
#include <thrill/api/cache.hpp>
#include <thrill/api/dia.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/api/inner_join.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/api/size.hpp>
#include <thrill/common/logger.hpp>
#include <thrill/common/stats_timer.hpp>
#include <thrill/common/string.hpp>
#include <tlx/cmdline_parser.hpp>
#include <tlx/string/split.hpp>
#include <algorithm>
#include <cmath>
#include <ctime>
#include <functional>
#include <string>
#include <utility>
#include <vector>
Functions
JoinedElement ConstructJoinedElement (const struct LineItem &li, const struct Order &o)
static size_t JoinTPCH4 (api::Context &ctx, const std::vector< std::string > &input_path)
int main (int argc, char *argv[])
time_t time_to_epoch (const std::string &str)
Variables
struct LineItem TLX_ATTRIBUTE_PACKED
Function Documentation
JoinedElement ConstructJoinedElement (const struct LineItem & li, const struct Order & o)
Definition at line 100 of file tpch_run.cpp.
Referenced by JoinTPCH4().
static size_t JoinTPCH4 (api::Context & ctx, const std::vector< std::string > & input_path) static
Definition at line 167 of file tpch_run.cpp.
References FlowControlChannel::Barrier(), ConstructJoinedElement(), Context::enable_consume(), thrill::api::InnerJoin(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), thrill::api::ReadLines(), tlx::split(), time_to_epoch(), and Manager::Traffic().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 279 of file tpch_run.cpp.
References CmdlineParser::add_param_stringlist(), die_unless, Context::enable_consume(), JoinTPCH4(), LOG1, CmdlineParser::print_result(), CmdlineParser::process(), and thrill::api::Run().
time_t time_to_epoch (const std::string & str)
Definition at line 138 of file tpch_run.cpp.
Referenced by JoinTPCH4().
Variable Documentation
struct JoinedElement TLX_ATTRIBUTE_PACKED