Thrill: examples/triangles/triangles_run.cpp File Reference
triangles_run.cpp File Reference
#include <examples/page_rank/zipf_graph_gen.hpp>
#include <examples/triangles/triangles.hpp>
#include <thrill/api/cache.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/api/size.hpp>
#include <thrill/common/logger.hpp>
#include <tlx/cmdline_parser.hpp>
#include <algorithm>
#include <cmath>
#include <functional>
#include <string>
#include <utility>
#include <vector>
Typedefs
using Edge = std::pair< Node, Node >
using Node = size_t
Functions
static size_t CountTrianglesGenerated (api::Context &ctx, const ZipfGraphGen &base_graph_gen, const size_t &num_vertices)
static size_t CountTrianglesPerLine (api::Context &ctx, const std::vector< std::string > &input_path)
int main (int argc, char *argv[])
Typedef Documentation
using Edge = std::pair<Node, Node>
Definition at line 32 of file triangles_run.cpp.
using Node = size_t
Definition at line 31 of file triangles_run.cpp.
Function Documentation
static size_t CountTrianglesGenerated (api::Context & ctx, const ZipfGraphGen & base_graph_gen, const size_t & num_vertices) static
Definition at line 60 of file triangles_run.cpp.
References FlowControlChannel::Barrier(), thrill::api::Generate(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), and Manager::Traffic().
Referenced by main().
static size_t CountTrianglesPerLine (api::Context & ctx, const std::vector< std::string > & input_path) static
Definition at line 34 of file triangles_run.cpp.
References examples::triangles::CountTriangles(), and thrill::api::ReadLines().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 117 of file triangles_run.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_double(), CmdlineParser::add_param_stringlist(), CmdlineParser::add_size_t(), CountTrianglesGenerated(), CountTrianglesPerLine(), die_unless, Context::enable_consume(), ZipfGraphGen::link_zipf_exponent, ZipfGraphGen::link_zipf_scale, CmdlineParser::print_result(), CmdlineParser::process(), thrill::api::Run(), ZipfGraphGen::size_mean, ZipfGraphGen::size_var, and thrill::mem::to_string().