Thrill: examples/word_count/word_count_run.cpp File Reference
word_count_run.cpp File Reference
#include <examples/word_count/random_text_writer.hpp>
#include <examples/word_count/word_count.hpp>
#include <thrill/api/cache.hpp>
#include <thrill/api/generate.hpp>
#include <thrill/api/read_lines.hpp>
#include <thrill/api/write_lines.hpp>
#include <thrill/common/logger.hpp>
#include <thrill/common/stats_timer.hpp>
#include <thrill/common/string.hpp>
#include <tlx/cmdline_parser.hpp>
#include <algorithm>
#include <random>
#include <string>
#include <utility>
#include <vector>
Functions
int main (int argc, char *argv[])
static void RunHashWordCount (api::Context &ctx, const std::vector< std::string > &input_filelist, const std::string &output)
static void RunHashWordCountGenerated (api::Context &ctx, size_t num_words, const std::string &output)
static void RunWordCount (api::Context &ctx, const std::vector< std::string > &input_filelist, const std::string &output)
static void RunWordCountGenerated (api::Context &ctx, size_t num_words, const std::string &output)
Function Documentation
int main (int argc, char * argv[])
Definition at line 158 of file word_count_run.cpp.
References CmdlineParser::add_bool(), CmdlineParser::add_param_stringlist(), CmdlineParser::add_string(), die, CmdlineParser::print_result(), CmdlineParser::process(), thrill::api::Run(), RunHashWordCount(), RunHashWordCountGenerated(), RunWordCount(), and RunWordCountGenerated().
static void RunHashWordCount (api::Context & ctx, const std::vector< std::string > & input_filelist, const std::string & output) static
Definition at line 68 of file word_count_run.cpp.
References FlowControlChannel::Barrier(), Context::enable_consume(), examples::word_count::HashWordCountExample(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), thrill::api::ReadLines(), thrill::mem::to_string(), and Manager::Traffic().
Referenced by main().
static void RunHashWordCountGenerated (api::Context & ctx, size_t num_words, const std::string & output) static
Definition at line 130 of file word_count_run.cpp.
References Context::enable_consume(), thrill::api::Generate(), examples::word_count::HashWordCountExample(), examples::word_count::RandomTextWriterGenerate(), and thrill::mem::to_string().
Referenced by main().
static void RunWordCount (api::Context & ctx, const std::vector< std::string > & input_filelist, const std::string & output) static
Definition at line 36 of file word_count_run.cpp.
References FlowControlChannel::Barrier(), Context::enable_consume(), LOG1, Context::my_rank(), Context::net, Context::net_manager(), Context::num_hosts(), thrill::api::ReadLines(), thrill::mem::to_string(), Manager::Traffic(), and WordCount().
Referenced by main().
static void RunWordCountGenerated (api::Context & ctx, size_t num_words, const std::string & output) static
Definition at line 104 of file word_count_run.cpp.
References Context::enable_consume(), thrill::api::Generate(), examples::word_count::RandomTextWriterGenerate(), thrill::mem::to_string(), and WordCount().
Referenced by main().